Ladybird/Qt/TabBar.cpp, Ladybird/Qt/TabBar.h
Before this change, if would a tab it will pass the add new tab button (+ button).
**Before:**
https://github.com/user-attachments/assets/d36f89ab-3673-4304-a11c-2e712cfbb73a
**After:**
https://github.com/user-attachments/assets/56c85cd9-30d6-410c-932f-3e27b696b7c2
=> UI/Qt: Fix dragging tab pass the + button, closes #1124

Ladybird/AppKit/Application/Application.mm, Ladybird/AppKit/Application/ApplicationDelegate.mm, Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/BrowserWindow.h, Ladybird/RequestServer/CMakeLists.txt, Ladybird/RequestServer/main.cpp, Userland/Libraries/LibIPC/CMakeLists.txt, Userland/Libraries/LibIPC/Connection.cpp, Userland/Libraries/LibIPC/Connection.h, Userland/Libraries/LibRequests/Request.cpp, Userland/Libraries/LibRequests/Request.h, Userland/Libraries/LibRequests/RequestClient.cpp, Userland/Libraries/LibRequests/RequestClient.h, Userland/Libraries/LibRequests/WebSocket.cpp, Userland/Libraries/LibRequests/WebSocket.h, Userland/Libraries/LibWebSocket/WebSocket.cpp, Userland/Libraries/LibWebSocket/WebSocket.h, Userland/Libraries/LibWebView/RequestServerAdapter.cpp, Userland/Services/RequestServer/ConnectionFromClient.cpp, Userland/Services/RequestServer/ConnectionFromClient.h, Userland/Services/RequestServer/RequestClient.ipc, Userland/Services/RequestServer/RequestServer.ipc, vcpkg.json
This replaces the use of our home-grown implementations inherited from SerenityOS.
=> RequestServer: Use libcurl for HTTP and HTTPS downloads

Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/DOM/Node.cpp, Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
DOM nodes that didn't have a layout node before being removed from the DOM are not going to change the shape of the layout tree after being removed.
Observing this, we can avoid a full layout tree rebuild on some DOM node removals.
This avoids a bunch of tree building work when loading https://x.com/
=> LibWeb: Don't invalidate layout tree on all DOM node removals

Ladybird/Qt/WebContentView.cpp, Ladybird/Qt/WebContentView.h, Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp, Userland/Libraries/LibWebView/PageInfo.h, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Libraries/LibWebView/WebContentClient.cpp, Userland/Libraries/LibWebView/WebContentClient.h, Userland/Services/WebContent/ConnectionFromClient.cpp, Userland/Services/WebContent/ConnectionFromClient.h, Userland/Services/WebContent/WebContentClient.ipc, Userland/Services/WebContent/WebContentServer.ipc, Userland/Utilities/headless-browser.cpp
The IPCs to request a page's text, layout tree, etc. are currently all
synchronous. This can result in a deadlock when WebContent also makes
a synchronous IPC call, as both ends will be waiting on each other.
This replaces the page info IPCs with a single, asynchronous IPC. This
new IPC is promise-based, much like our screenshot IPC.
Fixes #1440
(I wasn't actually able to repro, but this should certainly fix the deadlock from the `dump_text` call)
=> LibWebView+WebContent+headless-browser: Make the page info IPCs async

.github/workflows/libjs-test262.yml
It is now failing with the following error:
Unable to locate executable file: rsync.
=> CI: Install rsync on the test262 runner

AK/Utf16View.cpp, AK/Utf8View.cpp, vcpkg.json
Particularly of interest is simdutf, which lets us remove some workarounds for null inputs. They test such cases themselves now, so we shouldn't have to worry about it:
https://github.com/simdutf/simdutf/blob/master/tests/null_safety_tests.cpp
=> Meta: Update curl, sqlite, and simdutf

Ladybird/Qt/LocationEdit.cpp, Ladybird/Qt/Tab.cpp
On master, clear text from location bar and press enter. If search engine is enabled it will search empty string, if not it will reload the current page.
=> UI/Qt: Do not perform search if query text is empty

Userland/Libraries/LibWebView/ViewImplementation.cpp
`1.0 + 0.1 + 0.1 ... (40 times)` is `4.99..`, not `5.0` :shrug:
=> LibWebView: Ensure zoom-level stays between max/min after zoom in/out

Documentation/README.md
The Browser/LibWeb section seems to be missing a reference link to [Browsing Contexts and Navigables](https://github.com/LadybirdBrowser/ladybird/blob/master/Documentation/Browser/BrowsingContextsAndNavigables.md)
=> Documentation: Add Browsing Contexts and Navigables to Browser/LibWeb

Userland/Libraries/LibLine/Editor.cpp, Userland/Libraries/LibLine/Editor.h, Userland/Libraries/LibLine/SuggestionManager.cpp
Ports a fix from Serenity's LibLine.
https://github.com/SerenityOS/serenity/commit/cee0d979cca45c7299fd8872417f22f9bb021502
=> LibLine: Correctly slice completion substrings as unicode strings

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp, Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
Add support for the following date string format when opening [twitch](https://www.twitch.tv/).
```
12460.242 WebContent(113831): Unable to parse date string: "2024-07-05 00:00:00 GMT-0800"
12460.463 WebContent(113831): Unable to parse date string: "2024-07-05 00:00:00 GMT-0800"
12460.511 WebContent(113831): Unable to parse date string: "2024-07-05 00:00:00 GMT-0800"
```
=> LibJS: Extend supported date string formats

Tests/LibWeb/Text/expected/DOM/range-bounding-client-rect-with-nested-text.txt, Tests/LibWeb/Text/expected/DOM/range-get-client-rects.txt, Tests/LibWeb/Text/input/DOM/range-bounding-client-rect-with-nested-text.html, Tests/LibWeb/Text/input/DOM/range-get-client-rects.html, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Range.cpp, Userland/Libraries/LibWeb/DOM/Range.h, Userland/Libraries/LibWeb/Painting/Paintable.h, Userland/Libraries/LibWeb/Painting/PaintableFragment.cpp, Userland/Libraries/LibWeb/Painting/PaintableFragment.h, Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp, Userland/Libraries/LibWeb/Painting/ViewportPaintable.h
This patch implements `Range::getClientRects` and `Range::getBoundingClientRect`. Since the rects returned by invoking getClientRects can be accessed without adding them to the Selection, `ViewportPaintable::recompute_selection_states` has been updated to accept a Range as a parameter, rather than acquiring it through the Document's Selection.
With this change, the following tests now pass:
- [range-bounding-client-rect-with-nested-text](https://wpt.live/css/cssom-view/range-bounding-client-rect-with-nested-text.html)
- [DOMRectList](https://wpt.live/css/cssom-view/DOMRectList.html)
Note: The test [range-bounding-client-rect-with-display-contents](https://wpt.live/css/cssom-view/range-bounding-client-rect-with-display-contents.html) still fails due to an issue with …
=> LibWeb: Implement Range's extension method

Tests/LibWeb/Layout/expected/block-and-inline/inline-float-clear.txt, Tests/LibWeb/Layout/input/block-and-inline/inline-float-clear.html, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
When a block container has `clear` set and some clearance is applied, that clearance prevents margins from adjoining and therefore resets the margin state. But when a floating box has `clear` set, that clearance only goes between floating boxes so should not reset margin state. BlockFormattingContexts already do that correctly, and this PR changes InlineFormattingContext to do the same.
Fixes #1462; adds reduced input from that issue as test.
=> LibWeb: Change inline float clearance to not reset margin collapsing

Tests/LibWeb/Text/expected/ShadowDOM/replace-declarative-shadow-root-with-style-sheet.txt, Tests/LibWeb/Text/input/ShadowDOM/replace-declarative-shadow-root-with-style-sheet.html, Userland/Libraries/LibWeb/DOM/StyleElementUtils.cpp, Userland/Libraries/LibWeb/DOM/StyleElementUtils.h, Userland/Libraries/LibWeb/HTML/HTMLStyleElement.cpp, Userland/Libraries/LibWeb/SVG/SVGStyleElement.cpp
Instead of trying to locate the relevant StyleSheetList on style element removal from the DOM, we now simply keep a pointer to the list instead.
This fixes an issue where using attachShadow() on an element that had a declarative shadow DOM would cause any style elements present to use the wrong StyleSheetList when removing themselves from the tree.
=> LibWeb: Let style elements remember which StyleSheetList they live in

Tests/LibWeb/Text/expected/DOM/Document-defaultView.txt, Tests/LibWeb/Text/input/DOM/Document-defaultView.html, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/DOM/Document.idl, Userland/Libraries/LibWeb/DOM/Element.cpp
This PR updates `document.defaultView` to follow the most recent spec steps, which say that `WindowProxy?` should be returned rather than `Window?`.
I also had to update a few methods that called this method, but still expect it to return a Window object. In these cases, we now use `Document::window()` instead, so that the previous behavior is retained.
This prevents 291 WPT tests in the `editing` directory from timing out. Running `./Meta/WPT.sh run editing` gives the following results:
NOTE: The majority of these tests still error out, because we don't implement the `send_keys()` WebDriver endpoint, but they now fail a lot faster than previously.
Before:
```
Ran 724 tests finished in 692.4 seconds.
• 141 ran as expected. 0 tests skipped.
• 1 tests crashed unexpectedly
• 37 tests had …
```
=> LibWeb: Return a WindowProxy from `document.defaultView`

Userland/Services/RequestServer/ConnectionFromClient.cpp
After #1400, requests of method PATCH, PUT or DELETE that must have or can have bodies stopped working correctly. This patch sets the body for said requests.
=> RequestServer: Set request body for other methods that can have a body

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp, Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
This allows date strings like "01 February 2013" to be parsed. auth0.com also loads now because of this :^)
=> LibJS: Add extra date format "d B Y"

Tests/LibWeb/Layout/input/document-write-incomplete-tag.html, Tests/LibWeb/Text/input/HTML/document-write-flush-character-insertions.html
This ensures the HTML parser completes running if it previously stopped at an insertion point during a call to `document.write`.
=> LibWeb: Always call `document.close` after `document.write`

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h, Userland/Libraries/LibWeb/Loader/Resource.cpp, Userland/Libraries/LibWeb/Loader/Resource.h, Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
The web server for WPT has a tendency to just disconnect after sending us a resource. This makes curl think an error occurred, but it's actually still recoverable and we have the data.
So instead of just bailing, do what we already do for other kinds of resources and try to parse the data we got. If it works out, great!
It would be nice to solve this in the networking layer instead, but I'll leave that as an exercise for our future selves.
=> LibWeb: Make CSS font loader tolerate WPT web server shenanigans

Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
only select input elements that select applies to and has a selectable text.
as per the specs in https://html.spec.whatwg.org/multipage/input.html#do-not-apply
=> LibWeb/HTML: Select html input elements with selectable text

Tests/LibWeb/Text/expected/css/set-style-declaration-shorthand.txt, Tests/LibWeb/Text/input/css/set-style-declaration-shorthand.html, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp
We now expand shorthands into their respective longhand values when assigning to a shorthand named property on a CSSStyleDeclaration.
We also make sure that shorthands can be round-tripped by correctly routing named property access through the getPropertyValue() AO, and expanding it to handle shorthands as well.
A lot of WPT tests for CSS parsing rely on these mechanisms and should now start working. :^)
=> LibWeb: Allow setting shorthand CSS properties via CSSStyleDeclaration

Userland/Libraries/LibWeb/DOM/CharacterData.cpp, Userland/Libraries/LibWeb/DOM/CharacterData.h, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp, Userland/Libraries/LibWeb/Layout/TextNode.cpp, Userland/Libraries/LibWeb/Layout/TextNode.h, Userland/Libraries/LibWeb/Page/EventHandler.cpp
The expensive part of creating a segmenter is doing the locale and UCD
data lookups at creation time. Instead of doing this once per text node,
cache the segmenters on the document, and clone them as needed (cloning
is much, much cheaper).
On a profile loading Ladybird's GitHub repo, the following hot methods
changed as follows:
ChunkIterator ctor: 6.08% -> 0.21%
Segmenter factory:  5.86% ->    0%
Segmenter clone:    N/A   -> 0.09%
=> LibWeb: Move initial creation of Unicode segmenters to the Document

Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp, Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h, Userland/Libraries/LibWeb/CSS/StyleSheetList.cpp
When a style sheet is removed, all font loaders created from that style sheet should also be removed.
=> LibWeb: Remove all font loaders linked to a StyleSheet when it's deleted

Ladybird/AppKit/UI/LadybirdWebView.mm, Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/Tab.cpp, Ladybird/Qt/WebContentView.cpp, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Libraries/LibWebView/WebContentClient.cpp, Userland/Libraries/LibWebView/WebContentClient.h, Userland/Services/WebContent/PageClient.cpp, Userland/Services/WebContent/WebContentClient.ipc, Userland/Utilities/headless-browser.cpp
This removes cookie and history traversal callbacks. We do not need to go to the chromes to handle these any longer.
=> LibWebView: Remove some WebView callbacks that we can handle entirely inside LibWebView

Ladybird/Qt/Tab.cpp
Other browsers put this entry at the top as well.
=> UI/Qt: Move "Open in New Tab" to the top of the link context menu

Userland/Libraries/LibWeb/WebSockets/WebSocket.cpp
Previously, we would crash when attempting to establish a web socket connection from inside a worker, as we were assuming that the ESO's global object was a `Window`.
Running `./Meta/WPT.sh run websockets` gives the following results:
Before:
```
Ran 758 tests finished in 201.5 seconds.
• 249 ran as expected. 0 tests skipped.
• 9 tests crashed unexpectedly
• 21 tests had errors unexpectedly
• 337 tests timed out unexpectedly
• 257 tests had unexpected subtest results
```
After:
```
Ran 758 tests finished in 162.9 seconds.
• 324 ran as expected. 0 tests skipped.
• 9 tests crashed unexpectedly
• 21 tests had errors unexpectedly
• 217 tests timed out unexpectedly
• 358 tests had unexpected subtest results
```
=> LibWeb: Allow WebSockets to be established within workers

Ladybird/AppKit/UI/Palette.mm, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Some small style fixes for `input[type=range]` and `input[type=color]`
*Purple is my macOS system / accent color*
=> LibWeb: Some styling fixes for `input[type=range]`

Userland/Libraries/LibWeb/Animations/Animatable.cpp
Fixes crash on https://nextjs.org
Fixes #1481
=> LibWeb: Remove associated transitions when clearing transitions

Meta/ladybird.sh
Previously, using `ladybird.sh run` with any target that was part of the MacOS app bundle would try to run the given executable from the wrong directory.
=> Meta: Allow `ladybird.sh` to run any target in the MacOS app bundle

Documentation/BuildInstructionsLadybird.md
These packages are required for building on Fedora.
=> Documentation: Add missing required Fedora packages

Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp, Userland/Libraries/LibWeb/HTML/HTMLFormElement.h, Userland/Libraries/LibWeb/Layout/CheckBox.cpp, Userland/Libraries/LibWeb/Layout/CheckBox.h, Userland/Libraries/LibWeb/Layout/RadioButton.cpp, Userland/Libraries/LibWeb/Layout/RadioButton.h, Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.cpp, Userland/Libraries/LibWeb/Painting/CheckBoxPaintable.h, Userland/Libraries/LibWeb/Painting/RadioButtonPaintable.h, Userland/Libraries/LibWeb/XHR/FormDataIterator.cpp
This mainly uses forward declarations as appropriate for input element related files. This reduces the number of targets being built when we change HTMLInputElement.h from 430 to 44.
=> LibWeb: Clean up HTMLInputElement-related includes

Ladybird/ImageDecoder/CMakeLists.txt, Ladybird/RequestServer/CMakeLists.txt, Ladybird/WebContent/CMakeLists.txt, Ladybird/WebWorker/CMakeLists.txt
Ladybird build scripts uses CMake Ninja generator. These changes will help to build Ladybird using different CMake generators (e.g. Makefile)
=> CMake: fix Makefile build on case-insensitive file system

Ladybird/cmake/InstallRules.cmake, Ladybird/cmake/ResourceFiles.cmake
This pattern was in place for out of tree chromes. If needed we can add
it back, but there's no current interest in such chromes.
On macOS, it's a bit trickier to not install them, as we're using the
MACOSX_PACKAGE_LOCATION file property to get them into the build
directory and install tree in the same way.
=> CMake: Don't install service libraries or fonts

Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/HTML/Navigable.cpp
This updates the implementation of [attempt-to-populate-the-history-entry's-document](https://html.spec.whatwg.org/multipage/browsing-the-web.html#attempt-to-populate-the-history-entry's-document) after fixes were made to the logic inside the queued task in https://github.com/whatwg/html/commit/cdd014ae84faf3165f8ce8441d132bb0e76513fb.
=> LibWeb: Fix "attempt to update a history entry's document"

Userland/Libraries/LibJS/Console.cpp
https://github.com/whatwg/console/pull/240 is an editorial change to use the term "implementation-defined" more consistently. This seems to be the only instance in the spec text which we quote verbatim.
=> LibJS: Update wording from Console spec

Tests/LibWeb/Text/expected/WebAnimations/transition-unknown-property.txt, Tests/LibWeb/Text/input/WebAnimations/transition-unknown-property.html, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
If we don't recognize a given transition-property value as a known CSS property (one that we know about, not necessarily an invalid one), we should not extrapolate the other transition-foo values for it.
Fixes #1480
=> LibWeb: Don't extrapolate transition properties for unknown properties

Userland/Libraries/LibWeb/WebDriver/Client.cpp
WPT uses Python's `http.client.HTTPConnection` to send/receive WebDriver messages. For some reason, on Linux, we see an ~0.04s delay between the WPT server receiving the WebDriver response headers and its body. There are tests which make north of 1100 of these requests, which adds up to ~44s.
These connections are almost always going to be over localhost and able the be sent in a single write. So let's send the response all at once.
On my Linux machine, this reduces the runtime of `/cookies/name/name.html` from 45-60s down to 3-4s.
=> WebDriver: Do not break WebDriver responses into multiple socket writes

Ladybird/AppKit/Application/ApplicationDelegate.mm, Ladybird/AppKit/UI/LadybirdWebView.h, Ladybird/AppKit/UI/LadybirdWebView.mm, Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp, Ladybird/AppKit/UI/LadybirdWebViewBridge.h, Ladybird/AppKit/UI/TabController.h, Ladybird/AppKit/UI/TabController.mm, Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/Settings.cpp, Ladybird/Qt/Settings.h, Ladybird/Qt/SettingsDialog.cpp, Ladybird/Qt/SettingsDialog.h, Ladybird/Qt/Tab.cpp, Ladybird/Qt/Tab.h, Ladybird/WebDriver/main.cpp, Userland/Libraries/LibWebView/Application.cpp, Userland/Libraries/LibWebView/Options.h, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Libraries/LibWebView/ViewImplementation.h
This PR adds a command line option `--enable-autoplay`, which enables multimedia autoplay on all websites. An option has also been added to the Qt settings dialog to toggle this option.
The motivation behind this change was to enable autoplay when running WPT tests, as the `webvtt/` tests require autoplay to be enabled, otherwise a significant number of tests time out.
Running `./Meta/WPT.sh run webvtt` gives the following results:
Before:
```
Ran 320 tests finished in 300.6 seconds.
• 4 ran as expected. 0 tests skipped.
• 1 tests failed unexpectedly
• 295 tests timed out unexpectedly
• 71 tests had unexpected subtest results
```
After:
```
Ran 320 tests finished in 75.5 seconds.
• 12 ran as expected. 0 tests skipped.
• 230 tests failed unexpectedly
• 58 tests timed out unexpectedly
• 71 …
```
=> UI+WebDriver: Add an option to enable autoplay globally

Meta/gn/build/download_file.py
The file is not committed to disk until the close which occurs at the termination of the scope. Extract the `rename` to outside the scope allowing this to work on Windows. The `download_file` utility downloads a file in the `gn` build.
=> Meta: Make `download_file` work on Windows

Meta/gn/build/write_cmake_config.py, Meta/gn/secondary/AK/BUILD.gn
The `gn` build did not generate the CMake configuration file for the backtrace module. Update the rules to configure the generated macros mirroring the CMake build.
=> Meta: update the build rules for AK

Meta/gn/secondary/Ladybird/BUILD.gn, Meta/gn/secondary/Ladybird/enable_appkit.gni
The build assumed QT or AppKit are the only build UI frameworks. This extends the default assumption away from that to start experimenting with building on other platforms.
=> Meta: Add an option for building against AppKit

Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp
See:
- https://github.com/whatwg/fetch/pull/1769
- https://github.com/whatwg/fetch/commit/3153e5e
=> LibWeb/Fetch: Handle edge cases in 'get, decode, and split'

Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp, Userland/Libraries/LibJS/Runtime/Intrinsics.cpp, Userland/Libraries/LibJS/Runtime/Intrinsics.h
Instead of creating a unique new prototype shape every time a function object is instantiated, we now keep one cached with the intrinsics.
This avoids a whole lot of shape allocations, reducing GC pressure.
Did this in an effort to make https://blt.se/ load faster. Still lots of work to do. Lots of GC pressure.
=> LibJS: Cache the shape for normal ECMAScriptFunctionObject prototypes

Tests/LibWeb/Text/expected/HTML/Window-onerror.txt, Tests/LibWeb/Text/input/HTML/Window-onerror.html, Userland/Libraries/LibWeb/DOM/EventDispatcher.cpp, Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
We now use the "report an exception" AO when a script has an execution error. This has mostly replaced the older "report the exception" AO in various specifications. Using this newer AO ensures that `window.onerror` is invoked when a script has an execution error.
NOTE: The "report an exception" AO we are now using implements a previous version of the specification, so does not follow the most recent spec text.
There are many other places in the specification where "report an exception" is now used where "report the exception" was used previously, I haven't updated all these places as part of this PR.
This stops a large number of WPT timeouts. For example, these are the results when running `./Meta/WPT.sh run css/css-typed-om/`:
Before:
```
Ran 362 tests finished in 185.0 seconds.
• 12 …
```
=> LibWeb: Fire error event when script has an execution error

Tests/LibWeb/Layout/expected/block-and-inline/percentage-height-box-nested-into-percentage-height-box.txt, Tests/LibWeb/Layout/input/block-and-inline/percentage-height-box-nested-into-percentage-height-box.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
It's possible to resolve box's height without doing inner layout, when computed value is not auto. Doing that fixes height resolution, when box with percentage height has containing block with percentage height.
Before:
- resolve used width
- layout box's content
- resolve height
After:
- resolve used width
- resolve height if treated as not auto
- layout box's content
- resolve height if treated as auto
=> LibWeb: Resolve not auto height before child box layout in BFC

Base/res/ladybird/default-config/BrowserContentFilters.txt, Userland/Libraries/LibWeb/Loader/ContentFilter.cpp
The existing content filters were only ever used to match substrings, so `ContentFilter::is_filtered` can be changed to use `StringUtils::find` instead of `StringUtils::matches`.
This results in a ~3.5x speedup (605ms -> 170ms) in a benchmark of 5210 urls.
(`url_string.find(pattern.text).has_value()` is slightly faster than `url_string.contains(pattern.text)`)
`ContentFilter::set_patterns` could also be simplified now that patterns are no longer being pre-processed, I haven't done that in this PR (but I can if you want)
=> LibWeb: Use substring matching for content filters

Tests/LibWeb/Layout/expected/block-and-inline/percentage-height-in-quirks-mode.txt, Tests/LibWeb/Layout/input/block-and-inline/percentage-height-in-quirks-mode.html, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
See https://quirks.spec.whatwg.org/#the-percentage-height-calculation-quirk
Basically, it means that in quirks mode, percentage height needs to be resolved against nearest ancestor in the containing block chain that does not have height=auto.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/365
=> LibWeb: Implement "The percentage height calculation quirk" in BFC

Userland/Libraries/LibWeb/Painting/Command.h, Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp, Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
This flag is no longer needed after we switched to using scroll frames to account for fixed position.
=> LibWeb: Removed unused is_fixed_position flag from PushStackingContext

Tests/LibWeb/Layout/expected/css-all-unset.txt, Tests/LibWeb/Layout/expected/html-display-contents.txt, Tests/LibWeb/Layout/expected/html-display-inline.txt, Tests/LibWeb/Layout/expected/replaced-within-max-content.txt, Tests/LibWeb/Layout/expected/svg/svg-as-image-implicit-viewbox.txt, Tests/LibWeb/Layout/expected/svg/svg-as-image.txt, Tests/LibWeb/Layout/expected/svg/svg-with-zero-intrinsic-size-and-no-viewbox.txt, Tests/LibWeb/Layout/expected/zero-height-viewport-svg-image.txt, Tests/LibWeb/Layout/expected/zero-width-viewport-svg-image.txt, Tests/LibWeb/Layout/input/html-display-contents.html, Tests/LibWeb/Layout/input/html-display-inline.html, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
This is what the spec tells us to do:
The root element’s display type is always blockified,
and its principal box always establishes an independent
formatting context.
Additionally, a display of contents computes to block
on the root element.
Spec link: https://drafts.csswg.org/css-display/#root
Fixes #1562
=> LibWeb: Always blockify the root element

Userland/Libraries/LibWeb/WebSockets/WebSocket.cpp, Userland/Libraries/LibWebSocket/WebSocket.cpp, Userland/Libraries/LibWebSocket/WebSocket.h
Running `./Meta/WPT.sh run websockets` gives the following results.
Before:
```
Ran 758 tests finished in 187.2 seconds.
• 324 ran as expected. 0 tests skipped.
• 7 tests crashed unexpectedly
• 45 tests had errors unexpectedly
• 193 tests timed out unexpectedly
• 360 tests had unexpected subtest results
```
After:
```
Ran 758 tests finished in 182.2 seconds.
• 335 ran as expected. 0 tests skipped.
• 45 tests had errors unexpectedly
• 189 tests timed out unexpectedly
• 356 tests had unexpected subtest results
```
=> LibWeb/WebSocket: Allow sending binary blob data over a websocket

Tests/LibWeb/Text/expected/UIEvents/mouse-events.txt, Tests/LibWeb/Text/input/UIEvents/mouse-events.html, Userland/Libraries/LibWeb/Page/EventHandler.cpp
We were generating click events always using the primary mouse button
instead of the provided button, and with the buttons field set to that
provided button.
Caught by WPT Perform Actions tests.
=> LibWeb: Dispatch click events using the correct button/buttons 

Tests/LibWeb/TestConfig.ini
=> LibWeb: Disable worker-crypto test for now

Tests/LibWeb/Text/input/css/FontFaceSet-setlike.html, Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp, Userland/Libraries/LibWeb/CSS/FontFaceSet.h, Userland/Libraries/LibWeb/CSS/FontFaceSet.idl, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h, Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
This is an ad-hoc implementation that resolves the ready() promise once
the document and all fonts collected by the style computer are done
loading. A spec-compliant implementation would include creating a proxy
CSS::FontFace for each @font-face and correctly implementing the
specification steps for font fetching, but we are far from there yet.
This hackish implementation should yield good WPT progress because it
will actually start waiting for the Ahem font to load before capturing
layout measurements. For example, it makes
https://wpt.live/css/css-grid/abspos/positioned-grid-descendants-001.html
go from 0/100 to 36/100 passing subtests.
=> Resolve document.fonts.ready() after fonts defined in CSS loaded

Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp, Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.h
If the execution of the event loop's processing steps is interrupted, it's not possible to start the next iteration until the ongoing steps are done.
Fixes crashing on https://playbiolab.com/ in
VERIFY(page.client().is_ready_to_paint()) caused by attempting to start the next repaint before the ongoing repaint is done.
=> LibWeb: Forbid reentrancy of style-layout-repaint in EventLoop

Ladybird/AppKit/UI/LadybirdWebView.mm, Ladybird/Qt/Tab.cpp, Userland/Libraries/LibWeb/HTML/SyntaxHighlighter/SyntaxHighlighter.cpp, Userland/Libraries/LibWeb/HTML/SyntaxHighlighter/SyntaxHighlighter.h, Userland/Libraries/LibWebView/CMakeLists.txt, Userland/Libraries/LibWebView/InspectorClient.cpp, Userland/Libraries/LibWebView/SourceHighlighter.cpp, Userland/Libraries/LibWebView/SourceHighlighter.h
Someone with an aesthetic sense will want to come in and decide which type of token should be which colour, but the important part here is that it works. 🎉
Some of this is in preparation for syntax-highlighting in the style sheet inspector, which I'll work on soon.
=> LibWebView: Use LibSyntax for view-source highlighting, so CSS and JS get highlighted!

Tests/LibRegex/Regex.cpp, Userland/Libraries/LibRegex/RegexMatcher.cpp, Userland/Libraries/LibRegex/RegexOptimizer.cpp, Userland/Libraries/LibRegex/RegexParser.h
Partially fixes #700.
If the first opcode is `CheckBegin` then the pattern can only ever match the start of each line.
This doesn't apply when the multiline flag is enabled.
Speeds up the example in #700 to 151ms 
(I'd include a 'before' time but I'm not patient enough to wait several hours)
If the example is tweaked to check a 10 MB string only 100 times then the execution time goes from 9815ms to 11ms.
=> LibRegex: Only search start of line if pattern begins with ^

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/DOM/Element.cpp
Previously, we set the "needs style update" flag to false at the beginning of recomputing the style. This meant that if any code within the cascade set this flag to true, then we would end style computation thinking the element still needed its style updating. This could occur when starting a transition, and would make TreeBuilder crash.
By ensuring that we always set the flag to false at the very end of style computation, this is avoided, along with any similar issues - I noticed a comment in `Animation::cancel()` which sounds like a workaround was needed for a similar problem previously.
Fixes #1543
=> LibWeb: Ensure Elements don't need style update after computing style

Userland/Libraries/LibCore/StandardPaths.cpp, Userland/Libraries/LibCore/StandardPaths.h, Userland/Libraries/LibWebView/Database.cpp
Fixes #1507
We're supposed to treat an empty `XDG_DATA_DIRS` the same as if it's not present. We didn't, so in that case we wouldn't find any system fonts, which would crash the browser. I've done some small related clean-ups to `StandardPaths` too.
=> LibCore: Handle empty XDG_DATA_DIRS

Tests/LibWeb/Text/expected/html-parser-duplicate-attributes.txt, Tests/LibWeb/Text/input/html-parser-duplicate-attributes.html, Userland/Libraries/LibWeb/HTML/Parser/HTMLToken.cpp, Userland/Libraries/LibWeb/HTML/Parser/HTMLToken.h, Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
The HTML tokenizer specification says that we're supposed to do this when leaving the Attribute name or when emitting the token, as appropriate.
Hopefully 'as appropriate' can mean only when emitting the token, as that's the easiest place to insert this logic without complicating the tokenizer any more.
=> LibWeb: Deduplicate attributes when emitting start and end tags

Ladybird/Qt/EventLoopImplementationQt.cpp, Ladybird/Qt/EventLoopImplementationQt.h
We are currently creating a signal socket and socket notifier before the Qt event loop itself has been created. Thus, when we receive a signal, we are not actually notified when we write that signal number to the signal socket.
This was also the source of the following error message being displayed on every launch of the browser:
QSocketNotifier: Can only be used with threads started with QThread
Fixes #1137
=> UI/Qt: Do not create signal notifiers until after an event loop exists

.github/workflows/lint-code.yml, Meta/lint-ci.sh, Meta/lint-swift.sh, Tests/LibWeb/TestLibWebSwiftBindings.swift
swift-format is available in the Xcode 16 Beta and homebrew.
We will need some extra docs to tell Linux developers how to get it on
their distribution.
This also makes use of the fact that you can pass git diff a colon
delimited pattern to include ':*pattern' or exclude ':!*pattern'
matching files, which is pretty neat.
=> Meta: Add swift-format linter script 

Tests/LibWeb/TestHTMLTokenizerSwift.swift, Userland/Libraries/LibWeb/HTML/Parser/HTMLToken.swift, Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.swift
This patch adds support for start and end tags, as well as script tag rules.
=> LibWeb: Add more HTML tokenization states to Swift implementation

.github/workflows/libjs-test262.yml
Merely specifying `self-hosted` is not enough - to get closer to reproducible timings, we want these jobs to run on dedicated hardware. The `test262-runner` label was introduced for runners that offer this.
=> CI: Use explicit label for test262 workflow

Tests/LibWeb/Text/expected/WebAnimations/misc/get-animations-should-make-sure-style-is-updated.txt, Tests/LibWeb/Text/input/WebAnimations/misc/get-animations-should-make-sure-style-is-updated.html, Userland/Libraries/LibWeb/Animations/Animatable.cpp, Userland/Libraries/LibWeb/Animations/Animatable.h, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
StyleComputer is responsible for assigning animation targets, so we have to make sure there are no pending style updates before querying animations of an element.
This change also introduces a version of getAnimations() that does not check style updates and used by StyleComputer to avoid mutual recursion.
=> LibWeb: Make sure style is up-to-date in getAnimations()

Meta/CMake/ffmpeg.cmake, Meta/gn/build/libs/ffmpeg/BUILD.gn, Userland/Libraries/LibMedia/Audio/Loader.cpp, Userland/Libraries/LibMedia/CMakeLists.txt
Now it should be clearer looking at the build scripts what options are available for building LibMedia, and what packages are required.
=> LibMedia: Mark ffmpeg as required, and reorganize CMakeLists

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
=> LibWeb: Readonly input element's arrow buttons don't change the value

Tests/LibWeb/Text/expected/video-failed-load.txt, Tests/LibWeb/Text/input/DOM/Document-named-properties.html, Tests/LibWeb/Text/input/css/FontFace-load-urls.html, Tests/LibWeb/Text/input/video-failed-load.html
RFC2606 and RFC6761 define .invalid as a guaranteed-invalid TLD, so let's use it. Theoretically this should make the request fail much faster.
This unfortunately doesn't affect my timeout issues, but it can't hurt.
=> Tests: Use .invalid TLD for invalid requests

Meta/gn/secondary/Userland/Libraries/LibGfx/BUILD.gn, Userland/Libraries/LibGfx/BitmapSequence.cpp, Userland/Libraries/LibGfx/BitmapSequence.h, Userland/Libraries/LibGfx/CMakeLists.txt, Userland/Libraries/LibImageDecoderClient/Client.cpp, Userland/Libraries/LibImageDecoderClient/Client.h, Userland/Services/ImageDecoder/ConnectionFromClient.cpp, Userland/Services/ImageDecoder/ConnectionFromClient.h, Userland/Services/ImageDecoder/ImageDecoderClient.ipc
There is an issue (#425) where gifs with many frames cannot be loaded, as each bitmap is sent over IPC using a separate file descriptor, and there is limit on the maximum number of descriptors per IPC message. Thus, trying to load gifs with more than 64 frames (the current limit) causes the image decoder process to die.
This commit introduces the `BitmapSequence class`, which is a thin wrapper around the type `Vector<Optional<NonnullRefPtr<Gfx::Bitmap>>>` and provides an IPC encode/decode routine that collates all bitmap data into a single buffer so that only a single file descriptor is required per IPC transfer, even if multiple frames are being sent. This seems to fix the issue with large gifs (at least on my machine).
Right now, I'm using `memcpy` and pointer math to move data between …
=> ImageDecoder+LibGfx: collate decoded bitmaps before sending over IPC

Userland/Libraries/LibGfx/BitmapSequence.cpp
And a few assorted cleanups to use more moves() to avoid copying Vectors and NonnullRefPtrs.
=> LibGfx: Use more Span methods in BitmapSequence instead of memcpy

AK/Format.cpp
`STDERR_FILENO` is pretty common but not part of the standard. On Windows, in order to get a file number, one must use `_fileno` to convert the `FILE *` to a file number. Adopt this pattern similar to the Android path which uses platform specific operations.
=> AK: Address MSVC/Windows portability for logging

Tests/LibWeb/Text/expected/HTML/History-scrollRestoration.txt, Tests/LibWeb/Text/input/HTML/History-scrollRestoration.html, Userland/Libraries/LibWeb/HTML/History.cpp, Userland/Libraries/LibWeb/HTML/History.h, Userland/Libraries/LibWeb/HTML/History.idl
Resolved this FIXME that I found by looking at https://hyprland.org. Having two enums (IDL `ScrollRestoration` enum and `Web::HTML::ScrollRestorationMode`) is a bit awkward, but they're documented in two different specs as such.
=> LibWeb: Implement `history.scrollRestoration`

Ladybird/WebContent/CMakeLists.txt, Meta/CMake/pulseaudio.cmake, Meta/Lagom/CMakeLists.txt, Tests/LibMedia/CMakeLists.txt, Userland/Libraries/LibMedia/CMakeLists.txt
Note that WebContent/CMakeLists.txt still uses HAVE_PULSEAUDIO to enable Qt Multimedia (or not).
=> LibMedia+Ladybird: Use pkg_check_modules to find pulseaudio

Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
=> LibWeb: Make horizontal scrollbar start from the left edge of viewport

Userland/Libraries/LibWeb/Animations/Animation.cpp, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.h, Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp, Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.h, Userland/Libraries/LibWeb/HTML/EventLoop/Task.h, Userland/Libraries/LibWeb/Page/EventHandler.cpp, Userland/Libraries/LibWeb/Page/Page.h, Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h, Userland/Services/WebContent/PageClient.cpp, Userland/Services/WebContent/PageClient.h, Userland/Services/WebWorker/PageHost.h
Implements https://github.com/whatwg/html/pull/10007 which basically
moves style, layout and painting from HTML processing task into HTML
task with "rendering" source.
The biggest difference is that now we no longer schedule HTML event loop
processing whenever we might need a repaint, but instead queue a global
rendering task 60 times per second that will check if any documents
need a style/layout/paint update.
That is a great simplification of our repaint scheduling model. Before
we had:
- Optional timer that schedules animation updates 60 hz
- Optional timer that schedules rAF updates
- PaintWhenReady state to schedule a paint if navigable doesn't have a
rendering opportunity on the last event loop iteration
Now all that is gone and replaced with a single timer that drives
repainting at …
=> LibWeb: Move updating the rendering into HTML task

Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn, Meta/gn/secondary/Userland/Libraries/LibWeb/ServiceWorker/BUILD.gn, Tests/LibWeb/Text/expected/ServiceWorker/service-worker-register.txt, Tests/LibWeb/Text/input/ServiceWorker/service-worker-register.html, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/HTML/ServiceWorkerContainer.cpp, Userland/Libraries/LibWeb/ServiceWorker/Job.cpp, Userland/Libraries/LibWeb/ServiceWorker/Job.h
Now we can register jobs and they will be executed on the event loop "later". This doesn't feel like the right place to execute them, but the spec needs some updates in this regard anyway.
=> LibWeb: Add ServiceWorker job registration and execution

Ladybird/Qt/Tab.cpp
Removes the unnecessary separator, redundant open action, and changes shortcuts to match other browsers.
=> UI/Qt: Simplify link context menu and update keyboard shortcuts

Tests/LibWeb/TestConfig.ini
After https://github.com/LadybirdBrowser/ladybird/pull/1616 got merged this test started to occasionaly timeout on Linux CI: https://github.com/LadybirdBrowser/ladybird/actions/runs/11174338933/job/31063881592 https://github.com/LadybirdBrowser/ladybird/actions/runs/11177347649/job/31072646967?pr=1623
Since it's only this test that is timing out, I'm concluding that the event loop processing change is working fine and the issue lies with the test itself, so let's disable it for now.
=> Tests/LibWeb: Disable cross-origin-window-properties.html test for now

Tests/LibWeb/Text/expected/DOM/FormAssociatedElement-selection.txt, Tests/LibWeb/Text/expected/HTML/FormAssociatedElement-set-selectionDirection.txt, Tests/LibWeb/Text/input/HTML/FormAssociatedElement-set-selectionDirection.html, Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp, Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h, Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl, Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Fixes a timeout and 259 subtests in:  http://wpt.live/html/semantics/forms/textfieldselection/select-event.html
=> LibWeb: Follow spec steps to set the selectionDirection attribute value

Userland/Libraries/LibWeb/DOM/Document.cpp
Fixes a bunch of tests in `html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh`
=> LibWeb: Handle Refresh header

Userland/Libraries/LibWeb/FileAPI/Blob.cpp, Userland/Libraries/LibWeb/FileAPI/File.cpp, Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp
This makes us pass 1894 / 1898 tests on https://wpt.live/mimesniff/mime-types/parsing.any.html (up from the previous 1292/1898)
See https://github.com/w3c/FileAPI/issues/43 for details about the spec being out of date
=> LibWeb: Parse mimetypes on Blob and File

Tests/LibWeb/Text/expected/all-window-properties.txt, Tests/LibWeb/Text/input/HTML/Window-onerror.html, Tests/LibWeb/Text/input/HTML/WindowOrWorkerGlobalScope-reportError.html, Tests/LibWeb/Text/input/include.js
Previously, if there was an unhandled exception in an async test, it might fail to call done() and timeout. Now we have a default "error" handler to catch unhandled exceptions and fail the test. A few tests want to actually test the behavior of window.onerror, so they need an escape hatch.
=> LibWeb: Add a feature to LibWeb tests to fail on unhandled exceptions

Tests/LibWeb/Text/expected/canvas/pattern-from-video.txt, Tests/LibWeb/Text/input/canvas/pattern-from-video.html, Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawImage.cpp, Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawImage.h, Userland/Libraries/LibWeb/HTML/Canvas/CanvasDrawImage.idl, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Userland/Libraries/LibWeb/HTML/HTMLVideoElement.h
This fixes at least one WPT test [here](http://wpt.live/html/canvas/element/video/2d.video.invalid.html) and also a few FIXME's
This is my first contribution, so feel free to point out anything I did wrong 😄
=>  LibWeb: Make HTMLVideoElement part of CanvasImageSource union

Userland/Libraries/LibWeb/HTML/Navigable.cpp, Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
If we end up in a situation where the navigable no longer has an active window, we can't perform navigation or many other navigable operations.
These are all ad-hoc, since the navigables spec is basically all written as if there's always an active window. Unfortunately, the active window comes from the active document's browsing context, which is a nullable concept even in the spec, so we do need to deal with null here.
This removes all the locally reproducible crashes when running WPT over the legacy Japanese encoding directory on my computer.
Yes, this is a bit of a monkey patch, but it should be harmless since we're (as I understand it) dealing with navigables that are still hanging around with related tasks queued on them. Once all these tasks have been completed, the navigables will …
=> LibWeb: Bail from various navigable operations when no active window

Tests/LibWeb/Layout/expected/grid/justify-content-cols.txt, Tests/LibWeb/Layout/input/grid/justify-content-cols.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Before, we were only adding gap tracks if the css property `gap: ...` had an explicit property. This PR makes sure we always add gap tracks between column tracks (as well as gaps between row tracks). Also, this implements extra space distribution to column gaps as specified in justify-content for `space-around`, `space-between` and `space-evenly`
=> LibWeb/Layout: Implement justify-content for column spacing in grid

Tests/LibWeb/Layout/expected/flex-container-max-content-width-with-definite-height-and-item-that-has-aspect-ratio.txt, Tests/LibWeb/Layout/input/flex-container-max-content-width-with-definite-height-and-item-that-has-aspect-ratio.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
We were already allowing intrinsic height layout to see definite widths, and I can't think of a reason *not* to allow it the other way around.
More importantly, this fixes an issue where things with an aspect ratio didn't have a height to resolve against before.
Makes the logo show up on https://basecamp.com/ :^)
Before:
After:
=> LibWeb: Allow intrinsic width layout to see definite heights

Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp, Userland/Libraries/LibWeb/Layout/FormattingContext.h, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Static position of a box is defined by formatting context type it belongs to, so let's define this algorithm separately for each FC instead of assuming FormattingContext::calculate_static_position_rect() understands how to handle all of them.
Also with this change calculate_static_position_rect() is no longer virtual function.
=> LibWeb: Define static position calculation separately for each FC

Tests/LibWeb/Layout/expected/flex/flex-item-percentage-main-size-during-min-content-sizing.txt, Tests/LibWeb/Layout/input/flex/flex-item-percentage-main-size-during-min-content-sizing.html, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
When the flex container is sized under a min-content constraint in the main axis, any flex items with a percentage main size should collapse to zero width, not take up their own intrinsic min-content size.
This is not in the spec, but matches how other browsers behave.
Fixes an issue where the cartoons on https://basecamp.com/ were way too large. :^)
Before:
After:
=> LibWeb: Resolve flex item % main size to 0 during min-content sizing

Tests/LibWeb/Text/expected/HTML/Location-set-invalid-href-url.txt, Tests/LibWeb/Text/input/HTML/Location-set-invalid-href-url.html, Userland/Libraries/LibWeb/HTML/Location.cpp
Aligning with a spec update, fixing 195 tests for:
https://wpt.live/url/failure.html
This, along with the hack patch:
```patch
diff --git a/Ladybird/Qt/WebContentView.cpp b/Ladybird/Qt/WebContentView.cpp
index 9c0cdb74ed6..bc54686d59b 100644
--- a/Ladybird/Qt/WebContentView.cpp
+++ b/Ladybird/Qt/WebContentView.cpp
@@ -681,7 +681,7 @@ void WebContentView::initialize_client(WebView::ViewImplementation::CreateNewCli
update_screen_rects();
-    if (auto webdriver_content_ipc_path = WebView::Application::chrome_options().webdriver_content_ipc_path; webdriver_content_ipc_path.has_value())
+    if (auto webdriver_content_ipc_path = WebView::Application::chrome_options().webdriver_content_ipc_path; webdriver_content_ipc_path.has_value() && m_client_state.page_index < 2) …
```
=> LibWeb: Throw a SyntaxError on invalid URL for Location href setter

Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp, Userland/Libraries/LibWeb/HTML/EventLoop/TaskQueue.cpp, Userland/Libraries/LibWeb/HTML/EventLoop/TaskQueue.h
If, by the time we need to schedule rendering of the next frame, the previous one is still not processed, we could skip it instead of growing task queue.
Should help with https://github.com/LadybirdBrowser/ladybird/issues/1647
=> LibWeb: Skip queuing a rendering task if task queue already contains it

Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h, Userland/Libraries/LibWeb/Layout/LayoutState.h
There is no need to save vertical offset in UsedValues to use later, when static position could be assigned directly upon encountering abspos box.
=> LibWeb: Simplify static position calculation for block-level boxes

Tests/LibWeb/TestConfig.ini, Userland/Utilities/headless-browser.cpp
We currently create a single WebView and run all 1400+ LibWeb tests in
serial over that WebView. Instead, let's create as many WebViews as
there are processes on the system, and run LibWeb tests concurrently
over those views.
To do this performantly requires that we never block the main thread of
the headless-browser process once the tests are running. Doing so will
effectively pause execution of all other tests. So test execution is now
Promise-based.
On my machine (with a hardware concurrency of 32), this reduces the run
time of LibWeb tests from 31.382s to 3.640s. CPU utilization increases
from 5% to 67%.
=> headless-browser: Support running LibWeb tests concurrently

Documentation/Browser/Patterns.md
Small fix adding `./Meta/ladybird.sh run ...` to docs for generating test expectations file
=> Documentation: Update command for regenerating test expectations

Userland/Libraries/LibWeb/HTML/Window.cpp
Which fixes the following WPT test from failing due to issues stemming from all of the windows which have been opened.
https://wpt.live/url/failure.html
This will give us 1205 new subtests passing in WPT and a ~70 second speedup in test execution time.
=> LibWeb: Throw exception for invalid URL before creating traversable

Tests/LibWeb/Ref/reference/svg-overflow-hidden-ref.html, Tests/LibWeb/Ref/reference/svg-overflow-visible-ref.html, Tests/LibWeb/Ref/svg-overflow-hidden.html, Tests/LibWeb/Ref/svg-overflow-visible.html, Userland/Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
We were overly aggressive in clipping SVG roots, which effectively made them behave as if they always had `overflow: hidden`.
This fixes incorrect clipping of the logo on https://basecamp.com/
=> LibWeb: Allow SVG root elements to have visible overflow

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Transitions are currently not implemented for pseudo elements which
causes the transition to be applied to the "real"/"parent" element. When
a transition adjusts width/height on a pseudo element this causes the
real elements layout to break.
As a quick fix we just skip doing transitions when they are against
pseudo elements.
Here is a minimal reproduction of the issue:
```html
<html>
<head>
<style>
ul { display: flex; }
p { border: 1px solid red; }
p:after {
content: "";
width: 0;
}
li:hover p:after {
content: "";
width: 100px;
transition: width 0.3s ease;
}
</style>
</head>
<body>
<ul>
<li><p>hello</p></li>
<li><p>friends</p></li>
</ul>
</body>
</html>
```
And here is a screencast demonstrating the minimal reproduction:
[Screencast_20241006_223920-1.webm](https://github.com/user-attachmen …
=> LibWeb: Skip transitions for pseudo elements

Tests/LibWeb/Text/expected/iframe-removed-asyncronously.txt, Tests/LibWeb/Text/input/iframe-removed-asyncronously.html, Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
Partially reverting a3149c1ce95a5ee5f58d3303d01722a0fcb54256.
Spinning the event loop was causing a crash on:
https://wpt.live/url/percent-encoding.window.html
As it was turning what is meant to be a synchronous operation into an asynchronous one.
The sequence demonstrated by the reproducing test is as follows:
* A src attribute is changed for the iframe
* process_the_iframe_attributes entered with valid content navigable
* Event loop is spun, allowing the queued iframe removal to execute
* process_the_iframe_attributes continues with null content navigable
* 💥
=> LibWeb: Do not spin the event loop on processing iframe attributes

Tests/LibWeb/Layout/expected/media-query-empty.txt, Tests/LibWeb/Layout/input/media-query-empty.html, Userland/Libraries/LibWeb/CSS/MediaList.cpp, Userland/Libraries/LibWeb/CSS/MediaQueryList.cpp, Userland/Libraries/LibWeb/CSS/Parser/MediaParsing.cpp
Fixes #1551.
The spec appears to be contradictory, so this fix requires some ad-hoc behaviour.
=> LibWeb: Make empty media query lists evaluate to true

Userland/Libraries/LibWeb/Layout/Box.cpp, Userland/Libraries/LibWeb/Layout/Box.h, Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
With these changes https://basecamp.com/ is scrollable using mouse/trackpad.
=> LibWeb: Couple bug fixes for viewport scrolling

.github/actions/setup/action.yml, .github/workflows/lagom-template.yml
This uses the setup-python action in the setup action to install python 3.12, and removes the --break-system-packages hack that the system pip requires.
=> Meta: Avoid messing with the system python in CI

Ladybird/AppKit/main.mm, Ladybird/Qt/main.cpp, Userland/Libraries/LibWebView/Application.cpp, Userland/Libraries/LibWebView/ChromeProcess.cpp, Userland/Libraries/LibWebView/ChromeProcess.h
We don't create a ChromeProcess in headless-browser, so it is currently not increasing it's open file limit. This is causing crashes on macOS, which has a very low default limit.
=> LibWebView: Increase the open file limit in a more central location

Userland/Libraries/LibWeb/HTML/WorkerDebugConsoleClient.cpp
Previously, any message logged to the console within a worker with a log level greater than trace was printed twice.
=> LibWeb: Don't print messages from workers to the console twice

Tests/LibWeb/Text/expected/DOM/beforeunload.txt, Tests/LibWeb/Text/input/DOM/beforeunload.html
This test caused some flakiness due to the about:blank load it triggers. It causes headless-browser to receive a load event for about:blank. If we have moved onto the next test before that event arrived, that test would ultimately time out, as its own load will have been dropped while the about:blank load is still ongoing.
This patch makes us wait for that iframe load event before completing the test.
We may want to consider never sending subframe load events to the UI process as well. We really only care about top-level page loads in the receivers of that event.
=> LibWeb: Wait for the iframe load before completing the beforeunload test

Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/Worker/Worker-close-after-postMessage.txt, Tests/LibWeb/Text/input/Worker/Worker-close-after-postMessage.html, Tests/LibWeb/Text/input/Worker/worker-close-after-postMessage.js, Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
The spec expects `postMessage()` to act as if it is invoked immediately. Since `postMessage()` isn't actually invoked immediately, keep tasks with source `PostedMessage` in the task queue, so that these tasks are processed. Fixes a hang when `WorkerGlobalScope.close()` is called immediately after `postMessage()`.
Fixes:
* https://wpt.live/workers/interfaces/WorkerGlobalScope/close/sending-messages.html
* https://wpt.live/workers/WorkerPerformanceNow.html
=> LibWeb: Don't discard PostedMessage tasks when closing a worker

Tests/LibWeb/Text/expected/HTML/document-close-iframe-load-event.txt, Tests/LibWeb/Text/input/HTML/document-close-iframe-load-event.html, Userland/Libraries/LibWeb/DOM/Document.cpp
This matches the behavior of other browsers.
This gets rid of many timeouts for the HTML parser WPT tests in the `html/syntax/parsing` subdirectory
These are the results of running `./Meta/WPT.sh run html/syntax/parsing`:
Before:
```
Ran 208 tests finished in 213.4 seconds.
• 59 ran as expected. 0 tests skipped.
• 22 tests crashed unexpectedly
• 103 tests timed out unexpectedly
• 24 tests had unexpected subtest results
```
After:
```
Ran 208 tests finished in 173.5 seconds.
• 87 ran as expected. 0 tests skipped.
• 38 tests crashed unexpectedly
• 2 tests timed out unexpectedly
• 81 tests had unexpected subtest results
```
=> LibWeb: Fire iframe load event on document close

Tests/LibWeb/Layout/expected/actually-ignore-the-negative-overflow-region.txt, Tests/LibWeb/Layout/input/actually-ignore-the-negative-overflow-region.html, Userland/Libraries/LibWeb/Layout/LayoutState.cpp
This fixes an issue where https://hey.com/ was horizontally scrollable even though it shouldn't be.
=> LibWeb: Ignore boxes wholly in the negative scrollable overflow region

Documentation/BuildInstructionsLadybird.md
Unlike the current FAQ entry, this error really never involves having to uninstall/reinstall Ninja or invoking it directly.
=> Documentation: Update description of "Unable to find ninja" error

Tests/LibWeb/Text/expected/HTML/onreadystatechange.txt, Tests/LibWeb/Text/input/HTML/onreadystatechange.html, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/DOM/Document.idl
This is just a standard IDL event attribute handler.
Fixes at least one WPT test:
https://wpt.live/html/dom/documents/resource-metadata-management/document-readyState.html
=> LibWeb: Support Document.onreadystatechange

Userland/Libraries/LibCore/System.cpp, Userland/Libraries/LibCore/System.h, Userland/Libraries/LibWeb/HTML/Navigator.h, Userland/Libraries/LibWeb/HTML/Navigator.idl, Userland/Libraries/LibWeb/HTML/NavigatorDeviceMemory.h, Userland/Libraries/LibWeb/HTML/NavigatorDeviceMemory.idl, Userland/Libraries/LibWeb/HTML/WorkerNavigator.h, Userland/Libraries/LibWeb/HTML/WorkerNavigator.idl, Userland/Libraries/LibWeb/WebIDL/Types.h
Fixes at least 2 subtests in wpt/device-memory.
=> LibWeb: Implement navigator.deviceMemory

Tests/LibWeb/Layout/expected/grid/align-content.txt, Tests/LibWeb/Layout/input/grid/align-content.html, Userland/Libraries/LibWeb/CSS/Enums.json, Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
This PR implements `align-content` for grid layouts and adds `start` and `end` values to `align-content` in `Enums.json`. The `start` and `end` values are specifically added to support their usage in grid layouts.
=> LibWeb/Layout: Implement align-content for grid layout

Tests/LibWeb/Text/expected/HTML/HTMLSelectElement-value-change-trigger-onchange.txt, Userland/Utilities/headless-browser.cpp
Fixes a test currently failing on CI.
=> headless-browser: Only rebaseline tests that would have failed, and rebaseline currently failing test

Tests/LibRegex/Regex.cpp, Userland/Libraries/LibRegex/RegexByteCode.cpp, Userland/Libraries/LibRegex/RegexMatch.h
Fixes the lockup/OOM in https://github.com/LadybirdBrowser/ladybird/issues/968.
=> LibRegex: Restore checkpoints when restoring the state post-fork 

Meta/WPT.sh, Meta/ladybird.sh, Meta/shell_include.sh
I generally use the Debug build configuration instead of the default one. While I don't use `ladybird.sh`, I do use `WPT.sh` - so change the script to support a different build folder in line with `ladybird.sh`'s implementation.
=> Meta: Support a different build configuration for WPT.sh

Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp, Userland/Libraries/LibWeb/HTML/TraversableNavigable.h, Userland/Libraries/LibWeb/HTML/Window.cpp
We removed this check as a workaround for a spec issue that was resolved in:
https://github.com/whatwg/html/commit/3a8303ece44ed509928be626a6a65639fd
=> LibWeb: Restore check to prevent closing a traversable twice

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMathFunctions.cpp, Tests/LibWeb/CMakeLists.txt, Tests/LibWeb/TestCSSTokenStream.cpp, Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp, Userland/Libraries/LibWeb/CSS/Parser/MediaParsing.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp, Userland/Libraries/LibWeb/CSS/Parser/TokenStream.h
When the TokenStream code was originally written, there was no such concept in the CSS Syntax spec. But since then, it's been officially added, (https://drafts.csswg.org/css-syntax/#css-token-stream) and the parsing algorithms are described in terms of it. This patch brings our implementation in line with the spec. A few deprecated TokenStream methods are left around until their users are also updated to match the newer spec.
There are a few differences:
- They name things differently. The main confusing one is we had `next_token()` which consumed a token and returned it, but the spec has a `next_token()` which peeks the next token. The spec names are honestly better than what I'd come up with. (`discard_a_token()` is a nice addition too!)
- We used to store the index of the token that …
=> LibWeb/CSS: Bring TokenStream in line with spec

Tests/LibWeb/Text/expected/HTML/image-bitmap-from-invalid-types-no-crash.txt, Tests/LibWeb/Text/input/HTML/image-bitmap-from-invalid-types-no-crash.html, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
If we don't reject the Promise, it lasts forever, so rejecting non implemented Promise functions is essential, to not timeout in e.g. WPT tests
A test that now "just" fails and doesn't timeout would be e.g. [html/canvas/element/manual/imagebitmap/createImageBitmap-exif-orientation_none.html](https://wpt.live/html/canvas/element/manual/imagebitmap/createImageBitmap-exif-orientation_none.html)
But most if not all the timeouts from [html/canvas/element/manual/imagebitmap](https://wpt.fyi/results/html/canvas/element/manual/imagebitmap?product=ladybird&q=status%3Atimeout) now fail with an error, rather than taking 10 seconds, this should bring the test runtime down by round about 120 secs (just an estimate)  but doesn't increase passing tests.
Note: 
I also searched for similar thing sin the …
=> LibWeb: Reject Promise in createImageBitmap for Not Implemented Types

Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/DOM/Range.cpp, Userland/Libraries/LibWeb/DOM/Range.h, Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h
This fixes at least 2 WPT subtests in `selection/onselectionchange-on-document.html`.
Also: PR #406 is superseded by this PR, and by past changes to Selection/Range.
=> LibWeb: Implement selectionchange event according to spec

Tests/LibWeb/Ref/reference/textnode-segmenter-invalidation.html, Tests/LibWeb/Ref/textnode-segmenter-invalidation.html, Userland/Libraries/LibWeb/Layout/TextNode.cpp
We only set the grapheme segmenter's text once after creating a new segmenter, so we also need to clear it whenever we invalidate the text.
I come across this bug while debugging another issue. [This page](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/) shows the difference clearly:
|---|---|
| ![image](https://github.com/user-attachments/assets/e774585a-f7e1-4a95-906a-35ffa80c4fa3) | ![image](https://github.com/user-attachments/assets/a522c301-ff74-4ccd-8edd-81f2ad5c6331) |
=> LibWeb: Clear grapheme segmenter when invalidating TextNode text

Meta/gn/secondary/Userland/Libraries/LibWeb/ServiceWorker/BUILD.gn, Tests/LibWeb/Text/expected/ServiceWorker/service-worker-register.txt, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Internals/Internals.cpp, Userland/Libraries/LibWeb/ServiceWorker/Job.cpp, Userland/Libraries/LibWeb/ServiceWorker/Job.h, Userland/Libraries/LibWeb/ServiceWorker/Registration.cpp, Userland/Libraries/LibWeb/ServiceWorker/Registration.h, Userland/Libraries/LibWeb/ServiceWorker/ServiceWorker.cpp, Userland/Libraries/LibWeb/ServiceWorker/ServiceWorker.h, Userland/Libraries/LibWeb/StorageAPI/StorageKey.h
This approach will need some rework to be properly handled at the user
agent level instead of per renderer process, but it's a start.
... we're going to need a lot of proxy objects in different processes to make this thing work.
=> LibWeb: Implement most of Service Worker registration

Tests/LibTextCodec/TestTextEncoders.cpp, Userland/Libraries/LibTextCodec/Encoder.cpp, Userland/Libraries/LibTextCodec/Encoder.h
They are similar to their already existing decoder counterparts.
=> LibTextCodec: Add SingleByteEncoders

Tests/LibWeb/Layout/expected/grid/justify-content-cols.txt, Tests/LibWeb/Layout/expected/grid/justify-content-fr.txt, Tests/LibWeb/Layout/input/grid/justify-content-fr.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Simplifies grid area positioning calculations for justify-content, aligning with align-content method which is much simpler. Also fixes incorrect grid column justification which is covered in the new test case
=> LibWeb/Layout: Unify grid justify-content handling for grid area

Userland/Libraries/LibRequests/CMakeLists.txt, Userland/Libraries/LibRequests/NetworkErrorEnum.h, Userland/Libraries/LibRequests/Request.cpp, Userland/Libraries/LibRequests/Request.h, Userland/Libraries/LibRequests/RequestClient.cpp, Userland/Libraries/LibRequests/RequestClient.h, Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp, Userland/Services/RequestServer/ConnectionFromClient.cpp, Userland/Services/RequestServer/RequestClient.ipc
This allows us to bubble up network errors to API consumers after finishing a request.
Sample logs:
```
8018.574 WebContent(49434): ResourceLoader: Failed load of: "https://localhost:7174/", Error: SSL verification failed (status code: 0), Duration: 4ms
8059.510 WebContent(49434): ResourceLoader: Failed load of: "https://localhost/notfound", Error: Unable to connect (status code: 0), Duration: 4ms
```
Sample error page:
=> Report network errors on finish and set default timeout for all requests

Userland/Libraries/LibWeb/ServiceWorker/Registration.cpp
Appeasing clang. The binary == wasn't constexpr and that crashed compilation
=> LibWeb: Remove constexpr from service worker ==

Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
Before:
```
7903.420 WebContent(36728): ResourceLoader: Failed load of: "https://httpstat.us/403", Error: Load failed (status code: 403), Duration: 192ms
```
After:
```
7682.557 WebContent(32889): ResourceLoader: Failed load of: "https://httpstat.us/403", Error: Load failed (status: 403 Forbidden), Duration: 268ms
```
=> LibWeb/ResourceLoader: Display HTTP reason phrase in error status

Tests/LibWeb/Layout/expected/grid/abspos-placed-into-augmented-row-and-column.txt, Tests/LibWeb/Layout/expected/grid/abspos-with-auto-column-placed-in-augmented-row.txt, Tests/LibWeb/Layout/expected/grid/abspos-with-auto-row-and-column-contained-by-grid.txt, Tests/LibWeb/Layout/expected/grid/abspos-with-auto-row-placed-in-augmented-column.txt, Tests/LibWeb/Layout/input/grid/abspos-placed-into-augmented-row-and-column.html, Tests/LibWeb/Layout/input/grid/abspos-with-auto-column-placed-in-augmented-row.html, Tests/LibWeb/Layout/input/grid/abspos-with-auto-row-and-column-contained-by-grid.html, Tests/LibWeb/Layout/input/grid/abspos-with-auto-row-placed-in-augmented-column.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
- Add support for placement of abspos items into track formed by last
line and padding edge of grid container
- Correctly handle auto-positioned abspos items by placing them between
padding edges of grid container
Fixes crashing on https://wpt.live/css/css-grid/abspos/positioned-grid-descendants-001.html
=> LibWeb: Improve grid area calculation for abspos items in GFC

Userland/Services/RequestServer/ConnectionFromClient.cpp
Set the connection timeout which only limits the connection phase of the request.
Previously, CURLOPT_TIMEOUT would apply to all transfer operations which could result in legitimate upload or download operations being cancelled.
=> RequestServer: Set CURLOPT_CONNECTTIMEOUT instead of CURLOPT_TIMEOUT

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/Painting/DisplayList.cpp, Userland/Libraries/LibWeb/Painting/DisplayList.h, Userland/Libraries/LibWeb/Painting/ScrollFrame.cpp, Userland/Libraries/LibWeb/Painting/ScrollFrame.h, Userland/Libraries/LibWeb/Painting/ScrollState.h, Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp, Userland/Libraries/LibWeb/Painting/ViewportPaintable.h
This way we don't have to allocate separate vector with both scroll and sticky frame that is used for display list player (scroll and sticky frames share id pool), so player could access offset by frame id.
No behavior change.
=> LibWeb: Store scroll and sticky frames state in single vector

Meta/WPT.sh, Userland/Libraries/LibWeb/WebDriver/TimeoutsConfiguration.cpp, Userland/Libraries/LibWeb/WebDriver/TimeoutsConfiguration.h, Userland/Services/WebContent/WebDriverConnection.cpp
WPT sends us the following Set Timeouts invocations:
```
POST /session/<session id>/timeouts: {"implicit":0}
POST /session/<session id>/timeouts: {"pageLoad":3000}
POST /session/<session id>/timeouts: {"script":1000}
```
So after the last invocation, our page load timeout would be set back to 5 minutes.
=> LibWeb: Update (not replace) timeout values in WebDriver's Set Timeouts

Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp, Userland/Libraries/LibWeb/HTML/Parser/HTMLEncodingDetection.cpp, Userland/Libraries/LibWeb/HTML/Parser/HTMLEncodingDetection.h
Also added proper spec comments.
Fixes at least one WPT test (168 subtests) that was failing previously:
* https://wpt.live/encoding/single-byte-decoder.window.html?document
=> HTMLEncodingDetection: Use mime type in encoding sniffing

Tests/LibWeb/Text/expected/css/import-rule-shift-jis.txt, Tests/LibWeb/Text/input/css/import-rule-shift-jis.html, Userland/Libraries/LibWeb/CSS/CSSImportRule.cpp
This fixes a number of WPT crashes in the /css/CSS2/syntax directory.
=> LibWeb: Allow CSS @import rule to import non-UTF-8 style sheets

.devcontainer/devcontainer.json, .devcontainer/features/ladybird/devcontainer-feature.json, .devcontainer/features/ladybird/install.sh, Documentation/BuildInstructionsLadybird.md
While trying to run the dev container, I faced a few issues:
- the packages were outdated
- some needed packages were missing
This includes the following: 
In Ubuntu 20.04 (jammy) we don't have the minimum CMake version of 3.25, we could add it by using the [kitware apt repo](https://apt.kitware.com/ubuntu/) or by using the newer LTS (See below)
Some packages, that are needed for them to be compiled by vcpkg are missing, they were added to `Documentation/BuildInstructionsLadybird.md` but not to the devcontainer `install.sh` script. e.g. `libavformat-dev` or `nasm`.
Also jammy is the older LTS, the newer LTS noble (22.04) is already out by a half year, so using the newer `mcr.microsoft.com/devcontainers/base` image is a good idea. The official apt repos for llvm also support llvm 19 (see …
=> Meta: Update devcontainer

.devcontainer/optimized/devcontainer.json
The optimized devcontainer workflow downloads an image from the GitHub container registry. Now that we've made that image, which is built in CI, public, it would help to have the correct org name.
=> Meta: Use the correct organization name for the devcontainer base

Meta/ladybird.sh
Prior to this change, running ./Meta/ladybird.sh rebuild would not remove the user-variables.cmake file that was generated by the build script. This caused errors when testing out the .devcontainer on my Mac because the pkg-config binary lived in different dirs in the container vs host.
=> Meta: Clean up generated CMake uservars

Ladybird/CMakeLists.txt
Without this fix trying to build a Debug build on x86_64 macOS fails with the error `Build/ladybird-debug/bin/Ladybird.app: code object is not signed at all`. Thanks to @ADKaster for help with the fix :^)
=> CMake: fix codesigning error on Intel macOS

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Resolution.cpp
This adds support for the 'x' unit and parsing a calculation with resolutions. 
As a result http://wpt.live/css/css-values/round-mod-rem-invalid.html passes.
=> LibWeb: Improve support for resolutions when parsing CSS

Userland/Libraries/LibWeb/HTML/Navigable.cpp
This was previously negated due to a misread of https://url.spec.whatwg.org/#concept-url-equals. This change fixes a bunch of WPT crashes such as "/html/browsers/history/the-history-interface/001".
No regression test because this requires the HTTP protocol to manifest the crash.
=> LibWeb: Compare navigable active_url with fragments included

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
Loading Ladybird on Github results in 37 debug logs about being unable to parse an empty Date string. This log is intended to catch Date formats we do not support to detect web compatability problems, which makes this case not particuarly useful to log.
Instead of trying to parse all of the different date formats and logging that the string is not valid, let's just return NAN immediately.
=> LibJS: Early return from Date string parsing on empty string

Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp, Userland/Libraries/LibWeb/Painting/Paintable.cpp, Userland/Libraries/LibWeb/Painting/Paintable.h
=> LibWeb: Remove BrowsingContext pointer from Paintable

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/FileAPI/unpaired-surrogates-in-constructor.txt, Tests/LibWeb/Text/input/FileAPI/unpaired-surrogates-in-constructor.html
This should fix the last two remaining WPT test failures in FileAPI/unicode.html.
=> LibWeb: Handle unpaired surrogates in File and Blob constructors

Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Layout/Node.h
=> LibWeb: Remove BrowsingContext pointer from Layout::Node

Tests/LibWeb/Text/expected/DOM/Document-svg-title-element-first-child.txt, Tests/LibWeb/Text/input/DOM/Document-svg-title-element-first-child.html, Userland/Libraries/LibWeb/DOM/Document.cpp
Makes the two failing tests pass: https://wpt.fyi/results/html/dom/documents/dom-tree-accessors/document.title-09.html?product=ladybird
=> LibWeb: Insert title as first child on setting title of svg document

Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Similar to https://github.com/LadybirdBrowser/ladybird/pull/1774
Fixes the crash in the WPT test:
https://wpt.fyi/results/html/canvas/element/pixel-manipulation/2d.imageData.get.double.html?label=master&product=ladybird
=> LibWeb: Use abs() dimensions for canvas getImageData()

AK/Utf8View.cpp, AK/Utf8View.h, Userland/Libraries/LibJS/Forward.h, Userland/Libraries/LibJS/Runtime/Error.cpp, Userland/Libraries/LibJS/Runtime/Error.h, Userland/Libraries/LibJS/Runtime/ExecutionContext.h, Userland/Libraries/LibJS/Runtime/VM.cpp
Instead of re-symbolicating entire stacks from scratch every time
we want a JS VM backtrace, we now use the ExecutionContext object as
cache storage via a new CachedSourceRange object.
This means that once a stack frame has been symbolicated, we don't
have to resymbolicate it again (unless the program counter moves
within that stack frame).
This drastically reduces time spent in symbolication in some WPT tests.
(+bonus commit making the hot parts of Utf8View inline)
=> LibJS: Cache symbolicated stack frames on ExecutionContext

Userland/Libraries/LibWeb/CSS/CSSMediaRule.cpp
Half of the fix for https://github.com/LadybirdBrowser/ladybird/issues/1689.
There aren't any tests for this right?
=> LibWeb/CSS: Don't serialize empty rules in CSSMediaRule

Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp
=> LibWeb/CSS: Don't serialize empty rules in CSSStyleRule

Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
We were checking if the parent was _not_ null, and not checking for an auxiliary browsing context at all.
Found this boog when trying to debug another issue
=> LibWeb: Correct some faulty logic in 'apply the history step'

Tests/LibWeb/Text/expected/DOM/domparser-parsefromstring-xml-parsererror.txt, Tests/LibWeb/Text/input/DOM/domparser-parsefromstring-xml-parsererror.html, Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
This runs wpt [domparsing/DOMParser-parseFromString-xml-parsererror.html](https://wpt.fyi/results/domparsing/DOMParser-parseFromString-xml-parsererror.html?product=ladybird) that previously crashed because of a malformed XML namespace in the test.
The test now runs pass.
=> LibWeb: Do not accept malformed xml namespace

Ladybird/Headless/Test.cpp
Previously this would just hang - I assume because the `all_tests_complete` promise could never get resolved without any tests running.
=> headless-browser: Early-out with an error if no tests are found

Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
These are legacy name aliases for the properties without the 'grid-' prefix. See https://drafts.csswg.org/css-align-3/#gap-legacy
I missed these when previously implementing legacy name aliases.
=> LibWeb/CSS: Mark grid-[gap, column-gap, row-gap] properties as aliases

Userland/Libraries/LibMedia/Audio/FFmpegLoader.cpp, Userland/Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp
This makes https://playbiolab.com/ a bit more stable!
=> LibMedia: Handle EOF as end of stream in FFmpegLoader

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/HTML/Navigable.cpp, Userland/Libraries/LibWeb/HTML/Navigation.cpp, Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Minor changes as I have been working towards trying to figure out how to get `scroll_to_the_fragment` to fire at the correct time to fix a WPT test I have been working on (which also included finding the same fix as https://github.com/LadybirdBrowser/ladybird/pull/1759 which sin-ack has merged in).
=> LibWeb: Minor adjustments relating to Navigables & fragment scrolling

Tests/LibWeb/TestLibWebSwiftBindings.swift
This fixes a build error with Swift 6.0 on macOS.
=> Tests: Use Swift.String extension instead of manual conversion

CONTRIBUTING.md, Documentation/BuildInstructionsLadybird.md, Documentation/CodingStyle.md, Documentation/QtCreatorConfiguration.md, Documentation/SelfHostedRunners.md, Meta/lint-clang-format.sh
The clang-format version released with llvm 19 will format many files differently than clang-format-18.
These changes should help to avoid accidental usage of version 19 (or greater) before this issue has been resolved.
Fixes #1750
=> Meta+Documentation: Require clang-format 18 (not greater)

.devcontainer/devcontainer.json, .devcontainer/features/vcpkg-cache/devcontainer-feature.json, .devcontainer/features/vcpkg-cache/install.sh, .github/workflows/dev-container.yml, CMakePresets.json
This also means that the prebuilt devcontainer will have a populated
vcpkg binary cache, speeding up the first build by a lot.
It would be nice to be able to have only the prebuilt container also cache binary artifacts for a debug and sanitizer build as well, but I've left that for a future FIXME.
@joshspicer Since you added the prebuilt image for us when this was the SerenityOS devcontainer, do you know if there's a straightforward way to set different devcontainer feature flags for a devcontainer/ci action run vs a local devcontainer build? I want extra caching for the prebuilt vs a developer creating the container locally. ... preferably without duplicating the entire devcontainer.json as like, devcontainer-ci.json.
Also I'm not 100% convinced that a devcontainer feature is the most …
=> Meta: Add a vcpkg cache to the devcontainer 

Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
This fixes a test in the WebAssembly spec test suite that was added in https://github.com/WebAssembly/spec/commit/924c1f816d30c760bd4b66a9cf8d8f83f7f9ac2c
=> LibWasm: Reject indirect calls to external function references

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Userland/Libraries/LibWeb/WebAudio/AudioBuffer.h, Userland/Libraries/LibWeb/WebAudio/AudioContext.cpp, Userland/Libraries/LibWeb/WebAudio/AudioContext.h, Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.cpp, Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.h, Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.idl
[ZType](https://zty.pe/) was not getting some callback invocations in order to get past the loading screen, which it now does! It's very playable, but still needs some performance improvements to run smoothly.
=> LibWeb: Implement enough of BaseAudioContext.decodeAudioData() to get ZType to work

Tests/LibWeb/Text/expected/css/transition-style-invalidation-crash.txt, Tests/LibWeb/Text/input/css/transition-style-invalidation-crash.html, Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp, Userland/Libraries/LibWeb/DOM/Node.h
This reverts 6d25bf3aac3a10bd741f4193e790ab7886462b93
Invalidating the style here means that transitions can cause an element to leave style computation with its "needs style update" flag set to true. This then causes a VERIFY to fail in the TreeBuilder.
This invalidation does not otherwise seem to have any effect. The original commit suggests this was to fix a bug, but it's not clear what bug that was. If it reappears, we can try to solve the issue in a different way.
Fixes #1586.
=> LibWeb/CSS: Stop invalidating style when setting an animation's effect

Ladybird/AppKit/UI/Tab.mm
Make the tab title icon and text vertical center
=> UI/AppKit: Fix tab title icon and text layout

Ladybird/FontPlugin.cpp, Ladybird/FontPlugin.h, Ladybird/WebContent/main.cpp, Tests/LibGfx/TestWOFF2.cpp, Userland/Libraries/LibGfx/CMakeLists.txt, Userland/Libraries/LibGfx/Font/FontDatabase.cpp, Userland/Libraries/LibGfx/Font/FontDatabase.h, Userland/Libraries/LibGfx/Font/PathFontProvider.cpp, Userland/Libraries/LibGfx/Font/PathFontProvider.h, Userland/Libraries/LibGfx/Font/TypefaceSkia.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
This will be the first step is making better use of system libraries like fontconfig and CoreText to load system fonts for use by the UI process and the CSS style computer.
=> LibGfx: Move FontDatabase internals to SystemFontProvider interface

Userland/Libraries/LibWebSocket/WebSocket.cpp, Userland/Libraries/LibWebSocket/WebSocket.h
Before:
```
Ran 758 tests finished in 137.6 seconds.
• 345 ran as expected. 0 tests skipped.
• 45 tests had errors unexpectedly
• 183 tests timed out unexpectedly
• 346 tests had unexpected subtest results
```
After:
```
Ran 758 tests finished in 128.8 seconds.
• 375 ran as expected. 0 tests skipped.
• 45 tests had errors unexpectedly
• 155 tests timed out unexpectedly
• 321 tests had unexpected subtest results
```
=> LibWebSocket: A few Websocket fixes

Tests/LibWeb/Text/expected/css/calc-missing-context.txt, Tests/LibWeb/Text/input/css/calc-missing-context.html, Userland/Libraries/LibWeb/CSS/Length.h, Userland/Libraries/LibWeb/CSS/StyleValues/CSSMathValue.cpp
We dont always have a valid context when trying to resolve a calculation, this mitigates that somewhat
I'm not sure if this is the correct fix, since we should(?) have a context at this point, but it stops it from crashing atleast
Fixes a crash on https://wpt.live/css/css-values/acos-asin-atan-atan2-computed.html after we [parse the rotate property](https://github.com/LadybirdBrowser/ladybird/pull/1823)
=> LibWeb: Handle calculations without a context better

Tests/LibWeb/Text/expected/math-with-inline-child.txt, Tests/LibWeb/Text/input/math-with-inline-child.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Always create a new formatting context for <math> elements. Previously that didn't happen if they only had inline children, e.g. mtable.
This fixes a crash in the WPT MathML test mathml/crashtests/children-with-negative-block-sizes.html
=> LibWeb: Layout all math elements using InternalDummy context

Tests/LibWeb/Text/expected/HTML/SVGImageElement-load-and-error-events.txt, Tests/LibWeb/Text/input/HTML/SVGImageElement-load-and-error-events.html, Userland/Libraries/LibWeb/SVG/SVGImageElement.cpp
This resolves all WPT timeouts in `html/canvas/element/manual/imagebitmap`.
We can now run an additional 6 tests and 126 subtests :)
This also adds regression tests for this behavior.
=> LibWeb: Add SVGImageElement load and error events

Tests/LibWeb/Layout/expected/css-pseudo-element-display-list-item.txt, Tests/LibWeb/Layout/input/css-pseudo-element-display-list-item.html, Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
This change is required to not crash on the following WPT test:
[http://wpt.live/css/CSS2/generated-content/after-content-display-003.xht](http://wpt.live/css/CSS2/generated-content/after-content-display-003.xht)
It makes a CSS pseudo element display: list-item, which in turn requires the creation of a ::marker pseudo element, leading to the nesting of pseudo elements.
In its current state, TreeBuilder::create_pseudo_element_if_needed creates a ListItemBox, but doesn't create and assign the corresponding ::marker pseudo element. As a result, ListItemBox.m_marker remains a null pointer, leading to a crash.
I've just added a simple check for `is<ListItemBox>(...)` creating the marker directly in `create_pseudo_element_if_needed` to handle this case. However, there may be a need for an …
=> LibWeb/CSS: Allowing CSS Pseudo Element Nesting

Userland/Libraries/LibWeb/WebAudio/AudioContext.cpp, Userland/Libraries/LibWeb/WebAudio/AudioContext.h, Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.cpp, Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.h
Move the pending promises list from AudioContext to BaseAudioContext and deal with all remaining FIXMEs.
=> LibWeb: Implement pending promises in BaseAudioContext

Tests/LibWeb/Text/expected/HTML/DOMParser-parseFromString-document-url.txt, Tests/LibWeb/Text/input/HTML/DOMParser-parseFromString-document-url.html, Userland/Libraries/LibWeb/DOM/Document.cpp
We were hard-coding "about:blank" as the document URL for parsed HTML documents, which was definitely not correct.
This fixes a bunch of WPT tests under /domparsing/ :^)
=> LibWeb: Use the correct document URL in DOMParser.parseFromString()

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/HTML/DedicatedWorkerGlobalScope.cpp, Userland/Libraries/LibWeb/HTML/MessagePort.cpp, Userland/Libraries/LibWeb/HTML/MessagePort.h, Userland/Libraries/LibWeb/HTML/ServiceWorker.h, Userland/Libraries/LibWeb/HTML/StructuredSerializeOptions.h, Userland/Libraries/LibWeb/HTML/Window.cpp, Userland/Libraries/LibWeb/HTML/Window.h, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h, Userland/Libraries/LibWeb/HTML/Worker.cpp, Userland/Libraries/LibWeb/HTML/Worker.h, Userland/Libraries/LibWeb/HTML/WorkerAgent.cpp, Userland/Libraries/LibWeb/HTML/WorkerAgent.h, Userland/Libraries/LibWeb/HTML/WorkerGlobalScope.cpp, Userland/Services/WebWorker/DedicatedWorkerHost.cpp
Without this, a worker can be GC'd in a very simple script such as:
```js
const worker = new Worker("script.js");
worker.onmessage = () => {};
```
Where script.js attempts to post a message back to the parent window.
When the Worker is GC'd, the IPC connection from the WebContent process to the WebWorker process is closed. When this occurs, the WebWorker will exit() from LibIPC, and any message from the worker to its parent does not have a chance to run.
=> LibWeb: Visit the MessagePort's associated Worker target

.pre-commit-config.yaml
Since [pre-commit v4.0.0](https://github.com/pre-commit/pre-commit/releases/tag/v4.0.0) The CLI warns you, that the stage name `commit` is deprecated and you should use `pre-commit`
(See also https://github.com/pre-commit/pre-commit/issues/2732)
```
[WARNING] hook id `meta-lint-ci` uses deprecated stage names (commit) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
```
The stage name `pre-commit` is already supported since [pre-commit v3.2.0](https://github.com/pre-commit/pre-commit/releases/tag/v3.2.0) that released in 2023-03-17
So this should be available to everyone, to be sure, I also set the  config `minimum_pre_commit_version` to `3.2.0` as this version is the first to support the `pre-commit` stage
=> Meta: Replace deprecated pre-commit stage name

Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp, Userland/Libraries/LibWeb/Painting/BackgroundPainting.h, Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
After InlinePaintable is gone it's possible to make this function accept
a PaintableBox instead of more broad
Layout::NodeWithStyleAndBoxModelMetrics type.
=> Accept paintable instead of layout node in paint_background

Tests/LibWeb/Layout/expected/justify-content-flex-start.txt, Tests/LibWeb/Layout/input/justify-content-flex-start.html, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Fixes crashing on https://tweakers.net/
=> LibWeb: Add missing flex-start and flex-end in to_alignment [GFC]

Userland/Libraries/LibCore/System.cpp, Userland/Libraries/LibCore/System.h, Userland/Utilities/abench.cpp, Userland/Utilities/js.cpp, Userland/Utilities/lzcat.cpp, Userland/Utilities/xzcat.cpp
As efforts to begin porting to Windows is underway, doing so should be a
bit less daunting if we clean up syscall wrappers that aren't used.
Note: While this removes Serenity-only wrappers, it leaves the Serenity
implementations of used wrappers in place for now, to not needlessly
complicate merging between the two orgs.
=> LibCore: Remove unused Core::System wrappers

Tests/LibWeb/Text/expected/localStorage.txt, Tests/LibWeb/Text/input/localStorage.html, Userland/Libraries/LibWeb/HTML/Storage.cpp, Userland/Libraries/LibWeb/HTML/Storage.h
We only supported named properties on Storage, and as a result `localStorage[0]` would be disconnected from the Storage's backing map.
Fixes at least 20 subtests in WPT in /webstorage.
=> LibWeb: Implement indexed property support for HTML::Storage

Userland/Libraries/LibWeb/HTML/HTMLElement.idl
This adds an IDL stub for the autocorrect HTMLElement attribute.
Related commit: https://github.com/whatwg/html/commit/7bab05ac69e7992be25b23b2017b03d2ef4f7869
Spec: https://html.spec.whatwg.org/#htmlelement
=> LibWeb/HTML: Add missing HTMLElement IDL `autocorrect` as a stub

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/DOM/Node.cpp
For pseudo elements that represent a browser-generated shadow tree
element, such as ::placeholder, we were reparsing their style attribute
in StyleComputer for some reason.
Instead of doing this, just access the already-parsed version via
Element::inline_style().
Bonus commit: abort ancestor traversal earlier in `Node::set_needs_style_recalc()`
=> LibWeb: Avoid a weird reparse of style attributes for pseudo elements

Tests/LibWeb/TestConfig.ini
It is consistently hanging on mac, which makes running the test suite locally quite annoying. See #1306 for details.
=> LibWeb: Skip DedicatedWorkerGlobalScope-instanceof test

Userland/Libraries/LibWeb/HTML/Navigable.cpp
Previously, we would crash if scripting was disabled and a javascript URL was evaluated.
=> LibWeb/HTML: Check if evaluationStatus has a value before dereferencing

AK/Error.cpp, AK/Error.h, Meta/CMake/lagom_compile_options.cmake, Meta/CMake/use_linker.cmake, Meta/Lagom/CMakeLists.txt, Userland/Libraries/LibCore/CMakeLists.txt, Userland/Libraries/LibCore/DirIterator.cpp, Userland/Libraries/LibCore/DirIterator.h, Userland/Libraries/LibCore/DirIteratorWindows.cpp, Userland/Libraries/LibCore/DirectoryEntry.h, Userland/Libraries/LibCore/DirectoryEntryWindows.cpp
Split from #1794
Peculiarities:
I PIMPLed only OS-specific data in DirIterator because I don't want to access every member through m_impl->
Known problems:
* I removed `#include <windows.h>`, but there are still #ifdefs in classes in LibCore/DirectoryEntry.h and AK/Error.h
If these are unacceptible, what approach should I use to get rid of them?
For DirectoryEntry, I have an idea to move all platform-specific functions to DirIterator.cpp/DirIteratorWindows.cpp,
and name them directory_entry_from_stat, etc. But this is kinda ugly? Also, inode_number is never used, can we remove it?
* <s>on Windows DirIterator::fd() works only after next() is called and it returns new descriptor every time. It is never called - can we just remove it?</s> Update: Stubbed out DirIterator::fd(), it is never …
=> LibCore: Add Windows version of DirIterator

AK/Utf32View.cpp, AK/Utf32View.h, Ladybird/AppKit/UI/LadybirdWebView.mm, Ladybird/Qt/Tab.cpp, Userland/Libraries/LibWebView/InspectorClient.cpp, Userland/Libraries/LibWebView/SourceHighlighter.cpp, Userland/Libraries/LibWebView/SourceHighlighter.h, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Libraries/LibWebView/WebContentClient.cpp, Userland/Libraries/LibWebView/WebContentClient.h, Userland/Services/WebContent/ConnectionFromClient.cpp, Userland/Services/WebContent/WebContentClient.ipc
On the view-source page, generate anchor tags for any `href` or `src` attribute value we come across. This handles both when the attribute contains an absolute URL and a URL relative to the page.
https://github.com/user-attachments/assets/1d4ce950-a3a5-4024-9383-d8b9462eef9b
=> LibWebView: Generate hyperlinks for attributes that represent links

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/HTML/Window.cpp, Userland/Libraries/LibWeb/HTML/Window.h, Userland/Services/WebContent/WebDriverConnection.cpp
This matches the specification steps and fixes a WPT regression caused by us not loading `about:blank` when opening a new window.
=> WebContent: Use window open steps to create a new window with WebDriver

Userland/Libraries/LibCore/CMakeLists.txt, Userland/Libraries/LibCore/File.cpp, Userland/Libraries/LibCore/System.h, Userland/Libraries/LibCore/SystemWindows.cpp
Split from #1794
This should be applied after #1832 because it uses `Error::from_windows_error`.
=> LibCore: Port `File` to Windows

Tests/LibWeb/Layout/expected/css-appearance-none.txt, Tests/LibWeb/Layout/input/css-appearance-none.html, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Per css-ui-4, setting `appearance: none` is supposed to suppress the creation of a native-looking widget for stuff like checkboxes, radio buttons, etc.
This patch implements this behavior by simply falling back to creating a layout node based on the CSS `display` property in such cases.
This fixes an issue on the hey.com imbox page where we were rendering checkboxes on top of sender profile photos.
Before:
After:
=> LibWeb: Honor `appearance: none` when creating input element layout node

Tests/LibWeb/Text/expected/HTML/set-innerText.txt, Tests/LibWeb/Text/input/HTML/set-innerText.html, Userland/Libraries/LibWeb/HTML/HTMLElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLElement.h
Replaced the ad-hoc implementation with a spec compliant one.
This change fixes 36 WPT tests.
https://wpt.fyi/results/html/dom/elements/the-innertext-and-outertext-properties/innertext-setter.html
=> LibWeb/HTML: Implement inner text set according to spec

Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Spec comment included asserts on this behaviour implicitly.
Fixes WPT test here: http://wpt.live/xhr/firing-events-http-no-content-length.html.
=> LibWeb/XHR: Progess event handle empty length

Ladybird/Qt/FindInPageWidget.cpp, Ladybird/Qt/SettingsDialog.cpp
Qt 6.8 deprecated `QCheckbox::stateChanged` function and some distros like Arch Linux updated the qt6-base package to this version causing an error during the build with `-Wno-error=deprecated-declarations` flag.
```
ninja: Entering directory `/home/gear/sources/ladybird/Build/ladybird'
[0/2] Re-checking globbed directories...
[1/4] Building CXX object Ladybird/Qt/CMakeFiles/ladybird.dir/SettingsDialog.cpp.o
FAILED: Ladybird/Qt/CMakeFiles/ladybird.dir/SettingsDialog.cpp.o
/usr/bin/ccache /usr/bin/c++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -D_FILE_OFFSET_BITS=64 -I/home/gear/sources/ladybird/Build/ladybird/Ladybird/Qt/ladybird_autogen/include -I/home/gear/sources/ladybird -I/home/gear/sources/ladybird/Userland/Services …
```
=> Qt: Disable deprecated-declarations flag on Qt >= 6.8

Tests/LibWeb/Layout/expected/tab-size-chars-should-vertically-align.txt, Tests/LibWeb/Layout/expected/tab-size-text-wrap.txt, Tests/LibWeb/Text/expected/regress/recursive-glyph-miscount-dont-crash.txt, Tests/LibWeb/Text/input/regress/recursive-glyph-miscount-dont-crash.html, Userland/Libraries/LibGfx/TextLayout.cpp
This fixes a browser crash as experienced on Wikipedia when encountering the `&ne;` entity. As a side-effect, this also affects some tab-align and -wrap tests.
In particular, harfbuzz keeps changing the internal buffer array around, and writes to `glyph_count` in the later calls, so it's a bad idea to use the first value and use it forever.
CC @kostyafarber, as I this seems to change(?) or break(?) a test that you recently added in #1691. I don't know what's going on, so I have a few stupid questions: Do your tests intentionally check for these exact values? If yes, how do we fix this?
=> LibGfx: Use actual vector size as indicated by HarfBuzz

Userland/Libraries/LibWeb/UIEvents/PointerEvent.cpp, Userland/Libraries/LibWeb/UIEvents/PointerEvent.h, Userland/Libraries/LibWeb/UIEvents/PointerEvent.idl
Fixes at least 6 WPT subtests. :^)
=> LibWeb: PointerEvent improvements

Tests/LibWeb/Text/expected/query-scroll-size-of-inline-node.txt, Tests/LibWeb/Text/input/query-scroll-size-of-inline-node.html, Userland/Libraries/LibWeb/DOM/Element.cpp
With 6a549f62702e8b733dd4fc0caf1fa3e114243070 we need to check if optional scrollable overflow exists for paintable box, because it's not computed for inline nodes.
Fixes crashing after navigating into direct messages screen on Discord.
=> LibWeb: Add missing check if scrollable overflow defined for paintable

Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
This fixes an issue where the text would look very small on macOS.
Before:
After:
=> LibWeb: Scale up "inspected node" hint text to match screen DPI

Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Session.h
Previously, tests would intermittently fail because the current session wasn't yet aware of a newly created window handle.
=> WebDriver: Don't return from `new_window()` until WebDriver is connected

Userland/Services/WebContent/WebDriverConnection.cpp
Although we aren't using this hint (we always create tabs), we do need to validate the payload.
This lets us pass `/webdriver/tests/classic/new_window/new.py` (been running this test a bunch recently to validate our WebDriver against the new WPT infra, so seeing it pass is just a small confidence boost that we're doing things correctly).
=> WebContent: Parse the type hint in WebDriver's New Window endpoint

Tests/LibWeb/Text/expected/form-formEnctype-attribute.txt, Tests/LibWeb/Text/expected/form-formMethod-attribute.txt, Tests/LibWeb/Text/expected/form-method-attribute.txt, Tests/LibWeb/Text/input/form-formEnctype-attribute.html, Tests/LibWeb/Text/input/form-formMethod-attribute.html, Tests/LibWeb/Text/input/form-method-attribute.html, Userland/Libraries/LibWeb/HTML/HTMLButtonElement.idl, Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLFormElement.h, Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl, Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
The values of these attributes must be [limited to only known values](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-fs-action), updated the IDL to enforce this.
This PR fixes many test in [this](https://wpt.fyi/results/html/dom/reflection-forms.html?product=ladybird) WPT test
=> LibWeb/HTML: Use IDL Enumerated for form{Enctype, Method}, method attributes

Ladybird/Headless/Application.cpp, Ladybird/Headless/Application.h, Ladybird/Headless/HeadlessWebView.cpp, Ladybird/Headless/HeadlessWebView.h, Ladybird/Headless/Test.cpp, Ladybird/Headless/main.cpp, Ladybird/WebDriver/main.cpp, Meta/WPT.sh, Userland/Libraries/LibWeb/WebDriver/Capabilities.cpp, Userland/Libraries/LibWeb/WebDriver/Capabilities.h
This contains some headless-browser and WebDriver improvements to be able to run WPT tests (namely, supporting child web views from `window.open`).
```bash
» ./Meta/WPT.sh run --headless /cookies/name/name.html
ninja: Entering directory `/Users/flynn/workspace/ladybird/Build/ladybird'
[0/2] Re-checking globbed directories...
ninja: no work to do.
Running 1 tests in web-platform-tests
Ran 1 tests finished in 2.5 seconds.
• 1 ran as expected. 0 tests skipped.
```
Running with headless-browser instead of Qt drops the runtime of `/encoding/legacy-mb-korean/euc-kr` from 101.5s to 74.5 on my mac.
=> LibWeb+WebDriver+headless-browser: Support running WPT headlessly

Tests/LibWeb/Text/expected/UIEvents/KeyEvent-keypress.txt, Tests/LibWeb/Text/input/UIEvents/KeyEvent-keypress.html, Userland/Libraries/LibUnicode/CharacterTypes.cpp, Userland/Libraries/LibUnicode/CharacterTypes.h, Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp
It should be 0 for `keydown`/`keyup` events.
=> LibWeb: Implement KeyboardEvent.charCode according to spec

Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/Layout/Node.cpp
This will let us start to begin applying this during text shaping.
=> LibWeb: Apply the word-spacing css property to Node

Ladybird/AppKit/UI/Event.mm, Ladybird/Qt/WebContentView.cpp, Userland/Libraries/LibWeb/Internals/Internals.cpp, Userland/Libraries/LibWeb/Page/EventHandler.cpp, Userland/Libraries/LibWeb/Page/EventHandler.h, Userland/Libraries/LibWeb/Page/InputEvent.cpp, Userland/Libraries/LibWeb/Page/InputEvent.h, Userland/Libraries/LibWeb/Page/Page.cpp, Userland/Libraries/LibWeb/Page/Page.h, Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp, Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.h, Userland/Libraries/LibWeb/WebDriver/Actions.cpp, Userland/Services/WebContent/ConnectionFromClient.cpp
The `.repeat` property of a keydown or keyup event indicates whether the keypress was auto-repeated. Additionally, prevent keyup events from being enqueued whenever auto-repeating is happening. This fixes using the arrow keys on https://playbiolab.com/.
=> UI+LibWeb+WebContent: Implement KeyboardEvent.repeat

Userland/Libraries/LibGfx/TextLayout.cpp, Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
Handling tabs during text shaping caused issues because we tried to index 'input_glyph_info' whilst iterating until 'glyph_count' and these can be different sizes.
The difference is due to when one or more characters get merged into the same glyph when calling 'input_glyph_info' (see https://lazka.github.io/pgi-docs/HarfBuzz-0.0/classes/glyph_info_t.html).
We don't want to render tabs as they come up as tofu characters so instead let's strip them out of the text chunk before starting text shaping.
=> LibWeb: Strip tabs before text shaping

Tests/LibWeb/Text/expected/cookie.txt, Tests/LibWeb/Text/input/cookie.html, Userland/Libraries/LibWeb/Cookie/ParsedCookie.cpp, Userland/Libraries/LibWeb/Cookie/ParsedCookie.h, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/Internals/Internals.cpp, Userland/Libraries/LibWeb/Internals/Internals.h, Userland/Libraries/LibWeb/Internals/Internals.idl, Userland/Libraries/LibWebView/CookieJar.cpp, Userland/Libraries/LibWebView/CookieJar.h, Userland/Services/WebContent/WebDriverConnection.cpp
Contains missing steps from both the `document.cookie` and WebDriver steps.
=> LibWeb+WebContent: Implement missing cookie validation steps

Userland/Libraries/LibWeb/HTML/Navigable.cpp
There weren't checks whether `navigation_params`' response was null, since it used to be a `NonnullGCPtr`. Since it is now a `GCPtr` it's existence needs to be checked explicitly.
When checking whether `navigation_params` is null, we only check whether it contains `Empty`. After `NullWithError` was added to the variant in #209, we should also check whether `navigation_params` contains this `NullWithError`, since I believe it's equivalent to null and is just used to move along the error message.
=> LibWeb: Assert navigationParams' request and response are not null

Userland/Libraries/LibJS/Runtime/ShadowRealm.cpp, Userland/Libraries/LibJS/Runtime/ShadowRealm.h, Userland/Libraries/LibJS/Runtime/ShadowRealmConstructor.cpp, Userland/Libraries/LibJS/Runtime/VM.h, Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp, Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Environments.h, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
This implements the LibJS updates needed for the introduction of ShadowRealms into LibWeb as well as catching up to a  HTML spec update that relocates the list/set of pending and about to be notified promises to the global object.
=> LibWeb+LibJS: Some initial steps towards implementing the ShadowRealm proposal

Tests/LibWeb/Text/expected/localStorage.txt, Tests/LibWeb/Text/input/localStorage.html, Userland/Libraries/LibWeb/HTML/Storage.cpp
All tests at now pass: http://wpt.live/webstorage/defineProperty.window.html.
Uncertain whether this is actually the correct change:
https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface indicates that the two getter methods storage[name] and storage.getItem(name) should return null when the name is not present. However the tests assert on this behaviour.
=> LibWeb:Storage: Change getNamedItem default value

Documentation/BuildInstructionsLadybird.md
`git` and `bash` are most likely already installed, `bash` is part of `base-system`, and `git` is required to pull the repository in the first place, but they are not included in `base-minimal` or `base-container`, and they ARE required for a successful build, so I have added them regardless.
`qt6-tools-devel` and `qt6-wayland-devel` were not required to compile and link Ladybird on my machine, but I have included them as they are installed on the other Linux distributions.
=> Meta: Add build instructions for Void Linux

Tests/LibWeb/Text/expected/ServiceWorker/service-worker-register.txt, Tests/LibWeb/Text/input/ServiceWorker/service-worker-register.html, Userland/Libraries/LibWeb/ServiceWorker/Job.cpp, Userland/Libraries/LibWeb/ServiceWorker/Registration.cpp, Userland/Libraries/LibWeb/ServiceWorker/Registration.h
This misses the final, most important part of actually creating a service worker object and sending the script over to it in a WebWorker process.
=> LibWeb: Add most of ServiceWorker Update algorithm

Userland/Libraries/LibJS/Runtime/Uint8Array.cpp, Userland/Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.fromBase64.js
As the comments suggest, `_` is supposed to be translated into `/` but `-` is translated twice instead
I don't have a bug reproduction scenario at hand, as I was chasing a totally different issue and just came by these lines...
It's draft as it seems it breaks some tests, I gotta dig deeper
=> LibJS: fix base64 decoder typo

Ladybird/AppKit/UI/Event.mm
We call ns_event_to_key_event for the NSFlagsChanged event as well. By retrieving the isARepeat flag on those events, we are guaranteed to throw an exception.
See:
https://developer.apple.com/documentation/appkit/nsevent/1528049-arepeat?language=objc
Raises an NSInternalInconsistencyException if sent to an
NSFlagsChanged event or other non-key event.
=> UI/AppKit: Only check the NSEvent isARepeat flag in key down/up events

Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.cpp, Userland/Libraries/LibJS/Runtime/DeclarativeEnvironment.h
`find_binding_and_index` was doing a linear search, and while most environments are small, websites using JavaScript bundlers can have functions with very large environments, like youtube.com, which has environments with over 13K bindings, causing environment lookups to take a noticeable amount of time, showing up high while profiling.
Adding a HashMap significantly increases performance on such websites.
=> LibJS: Add HashMap for finding Bindings by name

Tests/LibWeb/Text/expected/css/FontFaceSet-load.txt, Tests/LibWeb/Text/input/css/FontFaceSet-load.html, Userland/Libraries/LibWeb/CSS/FontFace.h, Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp
This implementation is incomplete in that we do not fully implement the steps to match the given font against the fonts in the set.
This is used by fonts.google.com to load the fonts used for sample text.
For example, https://fonts.google.com/specimen/Inter
Before:
After:
~Due to a regex bug, the above won't quite work on its own.~
That bug was fixed in #1939
=> LibWeb: Begin implementing FontFaceSet.prototype.load

Userland/Libraries/LibWeb/WebDriver/Actions.cpp
There are many WPT subtests which validate how we behave against frames that have been removed. They do this by adding an iframe element with a button whose click action removes the iframe element. When the click is dispatched, the spec would have us generate a mouse event relative to that iframe, rather than the top-level frame, thus the click would miss the target button.
Serendipitously, a spec issue and PR were just opened to generate mouse events relative to the top-level frame. This patch implements that PR; it has some editorial issues to be resolved, but is a clear improvement for these tests.
=> LibWeb: Dispatch WebDriver mouse events relative to the top-level frame

AK/HashMap.h, Userland/Libraries/LibRegex/RegexByteCode.h, Userland/Libraries/LibRegex/RegexMatcher.cpp
While LibJS does cache regex literals, there's more than one way to
create regex objects, this cache is hit regularly just browsing the web,
though no real measurement has been done on its potential speedups.
=> LibRegex: Cache 1 MiB worth of bytecode for each parser

Userland/Libraries/LibJS/Runtime/PrimitiveString.cpp, Userland/Libraries/LibJS/Runtime/Utf16String.cpp, Userland/Libraries/LibJS/Runtime/Utf16String.h, Userland/Libraries/LibJS/Runtime/VM.h
We were already caching UTF-8 and byte strings, so let's add a cache for UTF-16 strings as well. This is particularly profitable whenever we run regular expressions, since the output of regex execution is a set of UTF-16 strings.
Note that this is a weak cache like the other JS string caches, meaning that strings are removed from the cache as they are garbage collected.
This avoids billions of PrimitiveString allocations across a run of WPT, significantly reducing GC activity.
=> LibJS: Cache UTF-16 strings on the VM

Ladybird/Headless/Application.cpp, Ladybird/Headless/CMakeLists.txt, Tests/LibWeb/Text/expected/element-get-bounding-client-rect-of-sticky.txt, Tests/LibWeb/Text/input/element-get-bounding-client-rect-of-sticky.html
It is easy to forget to set this flag on macOS, where doing so causes
many tests to fail. So let's just set it via code along with other
options to make it a bit more foolproof.
=> headless-browser: Force-enable font config via code rather than CMake

Userland/Libraries/LibRegex/RegexByteCode.cpp, Userland/Libraries/LibRegex/RegexByteCode.h, Userland/Libraries/LibRegex/RegexOptimizer.cpp
This commit makes LibRegex's atomic loop rewrite opt also accept cases where the follow block jumps to the end of the forking block (which is essentially a loop without a proper header in fancy clothes)
This makes patterns like /([^x]*)x/ where the loop is not _immediately_ followed by a block significantly faster.
=> LibRegex: Apply atomic loop rewrite in one more case

Tests/LibWeb/Text/expected/iterating-over-storage.txt, Tests/LibWeb/Text/input/iterating-over-storage.html, Userland/Libraries/LibWeb/HTML/Storage.cpp
Since `Storage::item_value` never returns an empty Optional, and since `PlatformObject::is_supported_property_index` only returns false when `item_value` returns an empty Optional, the loop in `PlatformObject::internal_own_property_keys` will never terminate when executed on a `Storage` instance.
This fix allows youtube.com to load successfully :^)
=> LibWeb: Fix infinite loop in `Storage::internal_own_property_keys`

AK/StringBuilder.cpp
And let's at least try to pre-allocate an appropriate amount of buffer space in the builder instead of appending and growing one code point at a time.
=> AK: Add ASCII fast path in StringBuilder::append(Utf16View)

Tests/LibWeb/Layout/expected/svg/svg-inside-inline-block.txt, Tests/LibWeb/Layout/input/svg/svg-inside-inline-block.html, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
This condition was included to implement flex containers with auto height, but it actually can reset the definitive height to 0 for inline blocks with only replaced elements such as an SVG. Removing the condition does not break any in-tree test, so let's improve the situation on the SVG side of things for now.
Fixes the https://tweakers.net logo:
|---|---|
| ![image](https://github.com/user-attachments/assets/6969e57a-2761-4a3d-8efa-c3ec8dbd9f1a) | ![image](https://github.com/user-attachments/assets/bd49b936-3d93-4e64-bb5d-a312f9376e06) |
=> LibWeb: Do not resolve inline block height early if height is definite

Tests/LibWeb/Text/expected/Crypto/SubtleCrypto-import-rsaoaep-minimal_jwk.txt, Tests/LibWeb/Text/input/Crypto/SubtleCrypto-import-rsaoaep-minimal_jwk.html, Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
This fixes a crash in WPT:
[WebCryptoAPI/import_export/rsa_importKey.https.any](https://wpt.fyi/results/WebCryptoAPI/import_export/rsa_importKey.https.any.html?product=ladybird)
This allows us to pass 240 tests!
=> LibWeb: Fix crash when importing malformed RSAOAEP key

Ladybird/Qt/Tab.cpp, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/DocumentObserver.cpp, Userland/Libraries/LibWeb/DOM/DocumentObserver.h, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/HTML/Navigable.cpp, Userland/Libraries/LibWeb/HTML/Navigable.h, Userland/Libraries/LibWeb/HTML/NavigationObserver.cpp, Userland/Libraries/LibWeb/HTML/NavigationObserver.h, Userland/Libraries/LibWeb/Page/Page.cpp, Userland/Libraries/LibWeb/Page/Page.h, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp, Userland/Libraries/LibWeb/WebDriver/HeapTimer.cpp, Userland/Libraries/LibWeb/WebDriver/HeapTimer.h, Userland/Services/WebContent/PageClient.cpp, Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebContent/WebDriverConnection.h, Userland/Services/WebContent/WebDriverServer.ipc, Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Session.cpp, Userland/Services/WebDriver/Session.h, Userland/Services/WebDriver/WebContentConnection.cpp, Userland/Services/WebDriver/WebContentConnection.h
Similar to commit c2cf65adac78912883996153fb608dafe389b6e0, we should avoid spinning the event loop from the WebContent-side of the WebDriver connection. This can result in deadlocks if another component in LibWeb also spins the event loop.
The AO to await navigations has two event loop spinners - waiting for the navigation to complete and for the document to reach the target readiness state. We now use NavigationObserver and DocumentObserver to be notified when these conditions are met. And we use the same async IPC mechanism as script execution to notify the WebDriver process when all conditions are met (or timed out).
This lets us pass `/webdriver/tests/classic/accept_alert/accept.py`. This should also eliminate a bunch of timeouts related to navigation / alert handling.
=> LibWeb+WebContent+WebDriver: Asynchronously wait for navigations to complete

Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/Filter.h, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.h, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Painting/Command.h, Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp, Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp, Userland/Libraries/LibWeb/Painting/DisplayListRecorder.h, Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Nice site to try this out with: https://cssgenerator.org/filter-css-generator.html
Also fixes the dark mode for some websites that use `filter: invert(1)` :^)
|---|---|
| ![image](https://github.com/user-attachments/assets/a1374c81-3698-4dfa-a52a-82100d370e74) | ![image](https://github.com/user-attachments/assets/1c51dda3-392e-46e6-919d-dbf462110458) |
=> LibWeb: Implement CSS filter property

Meta/WPT.sh
To help people in troubleshooting problems when running the WPT.sh script, this change makes the script echo to stdout the complete `wpt run` invocation (including all the flags and path args).
For context, see https://discord.com/channels/1247070541085671459/1247090166909374474/1299207453212151891.
I don’t feel strongly that this needs to be added — so I’m fine with this PR just being closed if this seems not necessary. I just figured going ahead and doing a patch for it would be quicker than first having a discussion about whether or not to actually do it…
=> Meta: Make WPT.sh echo the “wpt run” invocation

Userland/Libraries/LibJS/Forward.h, Userland/Libraries/LibJS/Runtime/RegExpObject.cpp, Userland/Libraries/LibJS/Runtime/RegExpObject.h, Userland/Libraries/LibJS/Runtime/RegExpPrototype.cpp, Userland/Libraries/LibJS/Runtime/RegExpPrototype.h
This avoids having to do O(n) contains() in the various flag accessors.
Yields a ~20% speed-up on the following microbenchmark:
const re = /foo/dgimsvy;
for (let i = 0; i < 1_000_000; ++i)
re.flags;
=> LibJS: Store RegExp flags as a bitmask

Userland/Libraries/LibGfx/Font/Font.h, Userland/Libraries/LibGfx/Font/ScaledFont.h, Userland/Libraries/LibGfx/Font/Typeface.h, Userland/Libraries/LibGfx/Font/TypefaceSkia.cpp, Userland/Libraries/LibGfx/Font/TypefaceSkia.h
This value gets converted to FlyString a lot, so let's just make it a FlyString in the first place!
=> LibGfx: Use `FlyString` for family name

CMakePresets.json, Meta/CMake/vcpkg/sanitizer-triplets/sanitizer.cmake
LLVM recommends compiling with at least -O1 to have decent performance with sanitizers enabled. Indeed, this improves CI performance of LibWeb tests as follows:
GCC on Linux:   160.61s to 119.68s (40.93s faster)
Clang on Linux:  65.56s to  55.64s ( 9.92s faster)
=> Meta: Use release builds as the basis for Sanitizer builds

Userland/Libraries/LibWeb/WebAudio/AudioContext.cpp
Fixes a crash seen on twitter.com, namely from the 'resume' function.
Will unfortunately cause me some more conflcits ontop of https://github.com/LadybirdBrowser/ladybird/pull/1955 where TemporaryExecutionContext is changed to accept a Realm&
=> LibWeb: Add temp execution context for resolving promise in AudioContext

Userland/Libraries/LibWeb/CSS/Selector.h
This avoids many allocations and deallocations.
=> LibWeb: Return `Web::CSS::Selector::pseudo_element` by reference

Userland/Libraries/LibWeb/HTML/HTMLElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Spotted in WPT tests that few elements have incorrect ARIA Roles:
* https://wpt.fyi/results/html-aam/roles.html?label=experimental&product=ladybird
Update existing default roles for `hgroup` and `input type="search"`, add default role for `address` and `s` tags according to the specification:
* https://www.w3.org/TR/html-aria/#docconformance
=> LibWeb: correct default ARIA Roles for few tags

Tests/LibWeb/Layout/expected/aspect-ratio-degenerate-ratio.txt, Tests/LibWeb/Layout/input/aspect-ratio-degenerate-ratio.html, Userland/Libraries/LibWeb/Layout/Node.cpp
When `aspect-ratio` is degenerate (e.g. 0/1 or 1/0) we should fallback to the same behaviour as `aspect-ratio: auto` according to spec (see https://drafts.csswg.org/css-sizing-4/#aspect-ratio)
This PR explicitly handles this specific, albeit very rare, case and fixes five WPT test in `css/css-sizing/aspect-ratio` (zero-or-infinity-[006-010])
This is my first ladybird PR so please have some patience with me if I've missed something obvious.
It is possible to achieve the same result with a change to `Box::preferred_aspect_ratio`, but from my understanding of the code, it's more appropriate to do the fix in `NodeWithStyle::apply_style` as otherwise we need to consider a special case for each render without much gain as far as I can tell.
=> LibWeb: fallback to auto when aspect ratio is degenerate as per spec

Tests/LibWeb/Layout/expected/tab-size-letter-spacing.txt, Tests/LibWeb/Layout/expected/tab-size-word-spacing.txt, Tests/LibWeb/Layout/input/tab-size-letter-spacing.html, Tests/LibWeb/Layout/input/tab-size-word-spacing.html, Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
When the css tab-size property is a number, we need to add the associated letter-spacing and word-spacing to it's width.
=> LibWeb: Bring tab-size closer to the spec

Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.h, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h
The old code was cloning the cached response, but after a second reading of RFC9111, I have come to the conclusion that the spec expects the cached response to be passed around by (mutable) reference. Cloning causes some changes to not be propagated on revalidation, which may result in CORS violations and missing headers.
This fixes WPT test [wpt/cors/304.htm](http://wpt.live/cors/304.htm).
=> LibWeb/Fetch: Update cached responses when revalidating 

Documentation/EditorConfiguration/VSCodeConfiguration.md
Probably a remnant from Ladybird being in Serenity :^).
=> Documentation: Change in name from Serenity to Ladybird

AK/Utf8View.cpp
This also makes `Utf8View::trim` significantly faster, since most strings start and end with ASCII.
=> AK: Add ASCII fast path for `Utf8View::contains`

AK/DeprecatedFlyString.h, AK/FlyString.h
This avoid unnecessairy reference counting.
=> AK: Pass `(Deprecated)FlyString::is_one_of` arguments by reference

Userland/Libraries/LibCore/System.cpp
This avoids an "Invalid argument (errno=22)" error on systems with lower hard limits.
=> LibCore: Respect system hard limit in `set_resource_limits`

Userland/Libraries/LibWebView/Process.h
The compiler is unable to deduce template arguments during aggregate initialization of `ProcessAndClient`, causing build failures in `HelperProcess.cpp`.
Explicitly specify the `ClientType` template parameter when constructing `ProcessAndClient` in the `Process::spawn()` function. This allows proper template argument deduction without requiring changes to the struct definition.
=> LibWebView: Fix ProcessAndClient template deduction causing build error

Userland/Libraries/LibWeb/Crypto/Crypto.cpp
This passes an additional test in WPT:
WebCryptoAPI/getRandomValues.any
In particular, this brings us on par with the Flow browser:
https://wpt.fyi/results/WebCryptoAPI/getRandomValues.any.html?product=ladybird&product=flow&aligned&diff&filter=ADC
(The other test is red because we don't yet support Float16 arrays. When we implement them, the code in this PR will automatically do the right thing.)
=> LibWeb: Refuse to fill float array with random values

Meta/WPT.sh
We now ensure that the directory for the currently selected build preset is used as the base certificate path. 
I've also included a change to ensure that log files are written to the correct place when an absolute path is given, previously the path was always appended to the current directory.
**NOTE:** The `-P` option can't be used with `realpath` since the option isn't available on MacOS.
=> Meta: Use correct certificate path when invoking WPT 

Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CSSLabLike.h
Small code deduplication. NFC.
=> LibWeb/CSS: Make all children of CSSLabLike share the create() method

Tests/LibWeb/Layout/expected/tab-size-spacing-001.txt, Tests/LibWeb/Layout/input/tab-size-spacing-001.html, Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
We should be adding the computed value for word spacing not letter spacing twice.
=> LibWeb: Add word spacing to tab size correctly

Userland/Libraries/LibWeb/CSS/CSSConditionRule.cpp, Userland/Libraries/LibWeb/CSS/CSSConditionRule.h, Userland/Libraries/LibWeb/CSS/CSSFontFaceRule.cpp, Userland/Libraries/LibWeb/CSS/CSSFontFaceRule.h, Userland/Libraries/LibWeb/CSS/CSSGroupingRule.cpp, Userland/Libraries/LibWeb/CSS/CSSGroupingRule.h, Userland/Libraries/LibWeb/CSS/CSSImportRule.cpp, Userland/Libraries/LibWeb/CSS/CSSImportRule.h, Userland/Libraries/LibWeb/CSS/CSSKeyframeRule.cpp, Userland/Libraries/LibWeb/CSS/CSSKeyframeRule.h, Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.cpp, Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.h, Userland/Libraries/LibWeb/CSS/CSSLayerBlockRule.cpp, Userland/Libraries/LibWeb/CSS/CSSLayerBlockRule.h, Userland/Libraries/LibWeb/CSS/CSSLayerStatementRule.cpp, Userland/Libraries/LibWeb/CSS/CSSLayerStatementRule.h, Userland/Libraries/LibWeb/CSS/CSSMediaRule.cpp, Userland/Libraries/LibWeb/CSS/CSSMediaRule.h, Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.cpp, Userland/Libraries/LibWeb/CSS/CSSNamespaceRule.h, Userland/Libraries/LibWeb/CSS/CSSNestedDeclarations.cpp, Userland/Libraries/LibWeb/CSS/CSSNestedDeclarations.h, Userland/Libraries/LibWeb/CSS/CSSPropertyRule.cpp, Userland/Libraries/LibWeb/CSS/CSSPropertyRule.h, Userland/Libraries/LibWeb/CSS/CSSRule.cpp, Userland/Libraries/LibWeb/CSS/CSSRule.h, Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp, Userland/Libraries/LibWeb/CSS/CSSStyleRule.h, Userland/Libraries/LibWeb/CSS/CSSSupportsRule.cpp, Userland/Libraries/LibWeb/CSS/CSSSupportsRule.h
All its overrides return constants, and without virtual dispatch the `qualified_layer_name` and `absolutized_selectors` functions can benefit from slightly better optimizations.
`CSSRule`s aren't allocated that often, so the memory impact is minimal.
=> LibWeb: Make `CSSRule::type()` non-virtual

Tests/LibWeb/Text/expected/DOM/Element-to_titlecase-lang.txt, Tests/LibWeb/Text/input/DOM/Element-to_titlecase-lang.html, Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/DOM/Element.h, Userland/Libraries/LibWeb/Layout/TextNode.cpp
This fixes: https://wpt.fyi/results/css/css-text/text-transform/text-transform-tailoring-001.html
Also, implemented a `lang()` member function in `DOM::Element` in accordance with the spec: https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes
=> LibWeb: Use the correct locale when applying titlecase in TextNode

Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/StyleValues/BUILD.gn, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h, Userland/Libraries/LibWeb/CSS/StyleValues/CSSColor.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CSSColor.h, Userland/Libraries/LibWeb/CSS/StyleValues/CSSColorValue.h
This is really bare bone as we only support the `xyz-d50` color space for the moment.
It makes us pass the following WPT tests:
- css/css-color/predefined-016.html
- css/css-color/xyz-d50-001.html
- css/css-color/xyz-d50-002.html
=> LibWeb/CSS: Start parsing the `color()` function

Userland/Libraries/LibHTTP/HttpRequest.h, Userland/Libraries/LibWeb/WebDriver/Client.cpp, Userland/Libraries/LibWeb/WebDriver/Client.h
We can currently crash on WebDriver session shutdown when we receive a
Delete Session command. This destroys the WebDriver client while we are
inside the client's socket's on_ready_to_read callback. This is not
allowed by AK::Function.
To avoid this, we now only read data from the socket in the callback. We
then defer handling the message to break out of the callback.
=> LibWeb: Defer handling of WebDriver endpoint invocations

Ladybird/Headless/HeadlessWebView.cpp, Ladybird/Headless/HeadlessWebView.h
This allows us to headlessly run WPT tests which involve dialogs.
=> headless-browser: Implement dialog-related WebView callbacks

Meta/WPT.sh, Meta/shell_include.sh
Previously, `realpath` was being used to absolutize log file paths in `WPT.sh`, but this doesn't work as expected on MacOS, where `realpath` returns an error if the given path doesn't exist.
=> Meta: Add cross-platform function for absolutizing paths and use it in `WPT.sh`

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/URL.cpp, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp, Userland/Libraries/LibWeb/Infra/Strings.cpp, Userland/Libraries/LibWeb/Infra/Strings.h
> To [isomorphic decode](https://infra.spec.whatwg.org/#isomorphic-decode) a [byte sequence](https://infra.spec.whatwg.org/#byte-sequence) input, return a [string](https://infra.spec.whatwg.org/#string) whose [code point length](https://infra.spec.whatwg.org/#string-code-point-length) is equal to input’s [length](https://infra.spec.whatwg.org/#byte-sequence-length) and whose [code points](https://infra.spec.whatwg.org/#code-point) have the same [values](https://infra.spec.whatwg.org/#code-point-value) as the [values](https://infra.spec.whatwg.org/#byte-value) of input’s [bytes](https://infra.spec.whatwg.org/#byte), in the same order.
This is essentially spec-speak for "Decode as ISO-8859-1 / Latin-1", but existing code interpreted it as "Transparently interpret as UTF-8" which is only …
=> LibWeb: Implement and use "isomorphic decoding"

Tests/LibWeb/Text/expected/WebAudio/compressor-node-channel-cound-mode.txt, Tests/LibWeb/Text/input/WebAudio/compressor-node-channel-cound-mode.html, Userland/Libraries/LibWeb/WebAudio/AudioNode.cpp, Userland/Libraries/LibWeb/WebAudio/AudioNode.h, Userland/Libraries/LibWeb/WebAudio/DynamicsCompressorNode.cpp, Userland/Libraries/LibWeb/WebAudio/DynamicsCompressorNode.h
This PR help passing more WPT tests under [/webaudio/the-audio-api/the-dynamicscompressornode-interface/ctor-dynamicscompressor.html](http://wpt.live//webaudio/the-audio-api/the-dynamicscompressornode-interface/ctor-dynamicscompressor.html)
I have managed to write a test to show the issue (Ladybird passes it manually only with this PR), however, I have not actually managed to automate it...
=> LibWeb : Manage channelCountMode and channelCount for DynamicsCompressor

Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/StyleValues/BUILD.gn, Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/CSS/CSSStyleValue.cpp, Userland/Libraries/LibWeb/CSS/CSSStyleValue.h, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/CSS/StyleValues/CSSMathValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CSSMathValue.h, Userland/Libraries/LibWeb/CSS/StyleValues/RotationStyleValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/RotationStyleValue.h, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/Layout/Node.cpp
Adds support for parsing the [rotate property](https://www.w3.org/TR/2021/WD-css-transforms-2-20211109/#propdef-rotate)
=> LibWeb: Parse the rotate css property

Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
> [https://html.spec.whatwg.org/multipage/form-elements.html#dom-textarea-cols](https://html.spec.whatwg.org/multipage/form-elements.html#dom-textarea-cols)
The cols and rows attributes are limited to only positive numbers with fallback. The cols IDL attribute's default value is 20. The rows IDL attribute's default value is 2.
The default value was returned only for negative value of the attribute (instead of non-positive). I added an additional check for the missing case when the attribute is 0.
This fixes 2 WPT tests. [TEST 1](https://wpt.fyi/results/html/rendering/bindings/the-textarea-element-0/cols-zero.html?label=master&product=ladybird) [TEST 2](https://wpt.fyi/results/html/rendering/bindings/the-textarea-element-0/rows-zero.html?label=master&product=ladybird)
=> LibWeb: Set `textarea` rows and cols default value if 0

Tests/LibWeb/Layout/expected/grid/grid-with-min-content-max-width.txt, Tests/LibWeb/Layout/input/grid/grid-with-min-content-max-width.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Treat max-width as auto when it's specified to min/max-content and available size is intrinsic constraint.
Fixes stack overflow on https://claude.ai/
=> LibWeb: Fix infinite recursion when max-width is min/max-content in GFC

Userland/Libraries/LibWebSocket/WebSocket.cpp
This fixes a regression introduced in #1826.
Results of running: `./Meta/WPT.sh run websockets`:
Before:
```
Ran 758 tests finished in 227.5 seconds.
• 243 ran as expected. 0 tests skipped.
• 45 tests had errors unexpectedly
• 306 tests timed out unexpectedly
• 436 tests had unexpected subtest results
```
After:
```
After:
Ran 758 tests finished in 188.8 seconds.
• 369 ran as expected. 0 tests skipped.
• 45 tests had errors unexpectedly
• 156 tests timed out unexpectedly
• 327 tests had unexpected subtest results
```
Fixes: #2041
=> LibWebSocket: Don't send closing frame if connection is already closed

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp, Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.h, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.h, Userland/Services/WebContent/WebContentConsoleClient.cpp
We implement these built-in accessors via a lexical environment override
on the inspected document's global scope. However, ClassicScript will
parse the script we provide as a JS program, in which any evaluated
bindings will be interpreted as global bindings. Our global binding
lookup in the bytecode interpreter does not search the lexical env for
the binding, thus scripts like "$0" fail to evaluate.
Instead, we can create an ECMAScriptFunctionObject to evaluate scripts
entered into the Inspector. These are not evaluated as JS programs, and
thus any evaluated bindings are interpreted as non-global bindings. The
lexical environment override we set will then be considered.
CC @AtkinsSJ
=> WebContent: Restore ability to use Inspector accessors like `$0`

Ladybird/AppKit/CMakeLists.txt, Ladybird/AppKit/UI/Inspector.h, Ladybird/AppKit/UI/Inspector.mm, Ladybird/AppKit/UI/LadybirdWebViewWindow.h, Ladybird/AppKit/UI/LadybirdWebViewWindow.mm, Ladybird/AppKit/UI/Tab.h, Ladybird/AppKit/UI/Tab.mm, Ladybird/AppKit/UI/TaskManager.h, Ladybird/AppKit/UI/TaskManager.mm
When a window containing a WebView becomes visibile, we have to inform WebContent. This was only implemented for the Tab class (not Inspector or Task Manaager).
This patch adds LadybirdWebViewWindow to contain the bare minimum needed to render a LadybirdWebView. All windows containing a WebView inherit from this class, to ensure their WebContent processes know they became visible.
=> UI/AppKit: Extract bare minimum WebView functionality into its own class

AK/ByteBuffer.h, AK/StringBuilder.cpp, AK/UnicodeUtils.h, AK/Utf16View.h, Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
Adds a fast path for valid UTF-16 using `simdutf`, and fall back to the slow path for unmatched surrogates.
```
111.48% faster for random ASCII
111.51% faster for random (99% ASCII)
135.38% faster for random (90% ASCII)
197.82% faster for random (75% ASCII)
252.42% faster for random (50% ASCII)
187.54% faster for random BMP
114.49% faster for random
257.53% faster for random surrogates
2.64% faster for random high surrogates
6.30% faster for random (50% high surrogates, 50% BMP)
```
=> Use `simdutf` when appending UTF-16 to `StringBuilder`

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h, Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.cpp, Userland/Libraries/LibJS/Runtime/Temporal/PlainDatePrototype.h, Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp, Userland/Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.h, Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.cpp, Userland/Libraries/LibJS/Runtime/Temporal/PlainMonthDayPrototype.h, Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.cpp, Userland/Libraries/LibJS/Runtime/Temporal/PlainYearMonthPrototype.h, Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp, Userland/Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.h, Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDate/PlainDate.prototype.calendarId.js, Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.calendarId.js, Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainMonthDay/PlainMonthDay.prototype.calendarId.js, Userland/Libraries/LibJS/Tests/builtins/Temporal/PlainYearMonth/PlainYearMonth.prototype.calendarId.js, Userland/Libraries/LibJS/Tests/builtins/Temporal/ZonedDateTime/ZonedDateTime.prototype.calendarId.js
=> LibJS: calendarId getters within Temporal

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp, Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
This format is used on https://jetbrains.com/
=> LibJS: Parse dates like "Tuesday, October 29, 2024, 18:00 UTC"

Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
As per Jelle Raaijmakers at discord, this is a leftover from coordinate/rect translation from the code
=> LibWeb: Remove variable self-assignment

Userland/Libraries/LibWeb/HTML/Numbers.cpp
Fixes compilation error with clang from Homebrew introduced in https://github.com/LadybirdBrowser/ladybird/pull/1962
=> LibWeb: Remove usage of math functions from std namespace

Meta/import-wpt-test.py
Use with `./Meta/import-wpt-test.py {URL TO TEST}`
This script will:
* Create an empty expectation file
* Download the source for the provided page
* Replace the relative src of all script tags with the correct in-tree path
* Download all referenced scripts
It has been tested with [dynamic-getter.html](https://wpt.live/html/dom/elements/the-innertext-and-outertext-properties/dynamic-getter.html) and provides the same output as the file currently in the repository (with a minor whitespace difference)
=> Meta: Add a script to import WPT tests

Tests/LibWeb/Ref/grid-item-and-css-filter.html, Tests/LibWeb/Ref/reference/grid-item-and-css-filter-ref.html, Userland/Libraries/LibWeb/Painting/StackingContext.cpp
We paint grid item nodes as a stacking context when they have no
`z-index` style set. However, a grid item could already have a stacking
context established - for example, when the `filter` style is applied.
This causes these nodes to be drawn twice.
Skip painting grid item nodes if a stacking context is already present.
=> LibWeb: Prevent painting grid items twice as a stacking context

.gitignore, Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp, Userland/Libraries/LibWeb/WebDriver/ElementReference.h, Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebContent/WebDriverConnection.h, Userland/Services/WebContent/WebDriverServer.ipc, Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Session.cpp, Userland/Services/WebDriver/Session.h, Userland/Services/WebDriver/WebContentConnection.cpp, Userland/Services/WebDriver/WebContentConnection.h
Removes the last instance of `spin_until` from WebDriverConnection.cpp.
=> LibWeb+WebContent+WebDriver: Make the element locator endpoints async, implement shadow references correctly

Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_embedded_control.txt, Tests/LibWeb/Text/input/wpt-import/accname/name/comp_embedded_control.html, Tests/LibWeb/Text/input/wpt-import/resources/testdriver-actions.js, Tests/LibWeb/Text/input/wpt-import/resources/testdriver-vendor.js, Tests/LibWeb/Text/input/wpt-import/resources/testdriver.js, Tests/LibWeb/Text/input/wpt-import/wai-aria/scripts/aria-utils.js, Userland/Libraries/LibWeb/DOM/Node.cpp, Userland/Libraries/LibWeb/Internals/Internals.cpp, Userland/Libraries/LibWeb/Internals/Internals.h, Userland/Libraries/LibWeb/Internals/Internals.idl
This change implements the “C: Embedded Control” step at https://w3c.github.io/accname/#step2C in the “Accessible Name and Description Computation” spec — to compute the accessible names for labeled form controls.
This gets Ladybird passing all 26 tests at https://wpt.fyi/results/accname/name/comp_embedded_control.html?product=ladybird.
This change also imports the WPT `accname/name/comp_embedded_control.html` test, and exposes a new `window.internals.get_computed_label` function for use in that test.
=> LibWeb: Support getting accessible name for labeled form controls

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
Fixes wpt/png/exif-chunk.html.
At some point there should probably be some mechanism to handle this outside of the individual decoder plugins. The TIFF decoder seems to have its own version of this, and as far as I can tell, the JPEG decoder doesn't handle this at all, even though that's probably the most common use case for Exif orientations. :^)
=> LibGfx: Apply Exif orientation for PNG images

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.cpp, Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.h, Userland/Libraries/LibWeb/HTML/Window.cpp, Userland/Libraries/LibWeb/HTML/Window.h, Userland/Libraries/LibWeb/WebDriver/Screenshot.cpp, Userland/Libraries/LibWeb/WebDriver/Screenshot.h, Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebContent/WebDriverServer.ipc, Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Session.cpp, Userland/Services/WebDriver/Session.h, Userland/Services/WebDriver/WebContentConnection.cpp, Userland/Services/WebDriver/WebContentConnection.h
From what I can see, these are the last WebDriver endpoints doing any event loop spinning in the WebContent process.
=> LibWeb+WebContent+WebDriver: Make the screenshot endpoints asynchronous

Meta/import-wpt-test.py
This change makes the `Meta/import-wpt-test.py` script handle URLs such as `https://wpt.live//WebCryptoAPI/generateKey/../util/helpers.js` and paths containing, e.g., `wpt-import/WebCryptoAPI/generateKey/../util/helpers.js` (that is, URLs and paths with `..` parent-directory references in them).
Otherwise, without this change, when the `import-wpt-test.py` script tries a URL like `https://wpt.live//WebCryptoAPI/generateKey/../util/helpers.js` that contains a `..` parent-directory reference, the script fails with a _“urllib.error.HTTPError: HTTP Error 404: Not Found”_ error message.
For example, without the patch in this PR applied, try running this:
```
./Meta/import-wpt-test.py https://wpt.live/WebCryptoAPI/generateKey/failures_AES-CTR.https.any.html
```
That will fail with the …
=> Meta: Make import-wpt-test.py resolve “..” parent refs in URLs/pathnames

Tests/LibWeb/Text/expected/HTML/HTMLProgressElement-large-max-value.txt, Tests/LibWeb/Text/input/HTML/HTMLProgressElement-large-max-value.html, Userland/Libraries/LibWeb/HTML/Numbers.cpp
Previously, attempting to parse a floating point number with an integer part larger than `(2 ^ 31)  - 1` would cause the browser to crash. We now avoid this by converting the integer part of the number to a `double` rather than an `i32`.
Fixes a regression in:  http://wpt.live/html/dom/reflection-forms.html
=> LibWeb: Don't crash when parsing large floating point number values

Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp, Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.h, Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp
Now passes all the tests on [failures_AES-CTR.https.any.html](https://wpt.live/WebCryptoAPI/generateKey/failures_AES-CTR.https.any.html), [aes_ctr.https.any.html](https://wpt.live/WebCryptoAPI/encrypt_decrypt/aes_ctr.https.any.html) and probably a few other places too
=> LibWeb: Implement AES-CTR for SubtleCrypto

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md, Documentation/Troubleshooting.md, ISSUES.md, SECURITY.md, Userland/Libraries/LibWebView/ViewImplementation.cpp
After working on https://github.com/LadybirdBrowser/ladybird/pull/830, it occurred to me we could further enforce issue-reporting requirements by putting the details from https://github.com/LadybirdBrowser/ladybird/blob/4dbb5aa90d/ISSUES.md#detailed-issue-reporting-guidelines into the issue form itself, rather than just in the docs.
To see what the results look like:
- https://github.com/sideshowbarker/ladybird/issues/new/choose
- https://github.com/sideshowbarker/ladybird/issues/new?template=bug_report.yml
Here are some notes about the different parts:
- This makes raising issues for things other than bug reports a bit more difficult. But maybe that’s a feature — since the project doesn’t encourage using the issue tracker for questions, feature requests, etc. That said, when users (or …
=> GitHub: For issue reports, move to using structured template

Userland/Libraries/LibWeb/WebAudio/BiquadFilterNode.cpp, Userland/Libraries/LibWeb/WebAudio/BiquadFilterNode.h
That helps to pass WPT tests
under webaudio/the-audio-api/the-biquadfilternode-interface/ctor-biquadfilter.html
=> WebAudio: Initialize BiquadFilterNode properly

Userland/Libraries/LibJS/SyntaxHighlighter.cpp
This fixes issue #1847, a crash on view-source sites with non-ascii characters in <script>tags, like https://chalmers.se
=> LibJS: Count code-points instead of bytes for syntax highlight.

Userland/Libraries/LibCrypto/PK/PK.h, Userland/Libraries/LibTLS/Certificate.cpp, Userland/Libraries/LibTLS/Certificate.h, Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp, Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.h, Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp
Fixes most tests on https://wpt.live/WebCryptoAPI/derive_bits_keys/cfrg_curves_bits_curve25519.https.any.html
But the remaining two need `ECDH` support to run
=> LibWeb: Implement X25519 algorithms for SubtleCrypto

Tests/LibWeb/Text/expected/DOM/Document-createElementNS-custom.txt, Tests/LibWeb/Text/input/DOM/Document-createElementNS-custom.html, Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
The DOM spec gets overridden by both the SVG2 and MathML core specs in that unknown elements should not inherit DOM::Element, but SVG::SVGElement and MathML::MathMLElement respectively.
CC @tcl3
=> LibWeb: Use right interface for custom SVG and MathML elements

Userland/Libraries/LibJS/Console.cpp
Corresponds to the change in this PR:
https://github.com/whatwg/console/pull/241
=> LibJS: Update console spec's use of "Type()" -> "is a"

Tests/LibWeb/Text/expected/HTML/background-shorthand.txt, Tests/LibWeb/Text/expected/HTML/place-items-shorthand.txt, Tests/LibWeb/Text/input/HTML/background-shorthand.html, Tests/LibWeb/Text/input/HTML/place-items-shorthand.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Better support for CSS shorthands when setting style attribute. This impoves some tests in WPT
/css/css-align/default-alignment/*shorthand
Small impovements in shorthand serialzaion to return shorter version when all longhands are the same.
Focus was on thist test http://wpt.live/css/css-align/default-alignment/place-items-shorthand-001.html
NOTE: this is may first contribution and I have limited C++ experience
=> LibWeb: support shorthands when setting style attribute

Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp
This corresponds to this spec change:
https://github.com/whatwg/html/pull/10705
(We don't implement showPopover() yet.)
=> LibWeb/HTML: Guard showModal() with fully active check

Tests/LibWeb/Text/expected/HTML/requestAnimationFrame-gc.txt, Tests/LibWeb/Text/input/HTML/requestAnimationFrame-gc.html, Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.cpp, Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.h
Stealing the callbacks from the `AnimationFrameCallbackDriver` made them no longer safe from GC. Continue to store them on the class until we have finished their execution.
=> LibWeb: Protect animation frame callbacks from GC while they execute

Tests/LibWeb/TestConfig.ini
=> LibWeb: Disable css/transition-basics.html test

Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
This is part of the changes in https://github.com/whatwg/html/pull/10456
=> LibWeb/HTML: Update legacy color parsing steps to match spec

Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp, Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.h, Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp
Fixes about 50% of the tests on https://wpt.live/WebCryptoAPI/encrypt_decrypt/aes_gcm.https.any.html
=> LibWeb: Implement / Stub out AES-GCM for SubtleCrypto

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
This makes the following WPT test pass (instead of our previous crash)  https://wpt.live/dom/nodes/node-appendchild-crash.html
I am honestly a little confused about what the expected behaviour should be here, or if this is the correct fix for this. But the changes do seem reasonable enough to me.
This seems to be a difficult test to fully execute as the appendChild(document.body) puts the document into a weird state
=> LibWeb: Fix crash running https://wpt.live/dom/nodes/node-appendchild-crash.html

Userland/Libraries/LibIDL/IDLParser.cpp
IDL enumerations are one of the rare (only?) list types in the IDL spec that allow for a trailing comma:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=17508
=> LibIDL: Allow trailing comma in enumerations

Tests/LibWeb/Text/expected/selectionchange-on-textarea.txt, Tests/LibWeb/Text/input/selectionchange-on-textarea.html, Userland/Libraries/LibWeb/DOM/Range.cpp, Userland/Libraries/LibWeb/DOM/Range.h, Userland/Libraries/LibWeb/DOM/SelectionchangeEventDispatching.h, Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp, Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h
With a8077f79cc65a37f82078a6249f161e469e96c3a Selection object is no longer aware of selection state inside text controls (<textarea> and <input>), so this change makes them responsible for dispatching `selectionchange` if their selection state was changed.
=> LibWeb: Fix `selectionchange` event dispatch on text control elements

Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_text_node.txt, Tests/LibWeb/Text/input/wpt-import/accname/name/comp_text_node.html, Userland/Libraries/LibWeb/DOM/Node.cpp, Userland/Libraries/LibWeb/DOM/Node.h
This change implements the _“is a descendant of a native host language text alternative element”_ condition in the “F: Name From Content” step at https://w3c.github.io/accname/#step2F in the “Accessible Name and Description Computation” spec — to ensure that all descendant nodes get included as expected in computations for accessible names for elements.
Otherwise, without this change, Ladybird unexpectedly skips descendant element nodes when computing accessible names — which can result in the wrong accessible name being returned.
This change gets us passing all 50 tests in the `comp_text_node.html` test at https://wpt.fyi/results/accname/name?product=ladybird
=> LibWeb: Correctly descend element nodes when computing accessible name

Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp, Userland/Libraries/LibWeb/MimeSniff/MimeType.cpp, Userland/Libraries/LibWeb/MimeSniff/MimeType.h
When mime essence matching, the spec only asks for a string comparison ignoring ascii case. The whitespace trimming and parsing of the mime produces unexpected and wrong results.
This fixes all the following tests on WPT:
[script-type-and-language-js-xhtml](https://wpt.fyi/results/html/semantics/scripting-1/the-script-element/script-type-and-language-js-xhtml.xhtml?label=master&product=ladybird)
[script-type-and-language-js](https://wpt.fyi/results/html/semantics/scripting-1/the-script-element/script-type-and-language-js.html?label=master&product=ladybird)
[script-type-and-language-with-params](https://wpt.fyi/results/html/semantics/scripting-1/the-script-element/script-type-and-language-with-params.html?label=master&product=ladybird)
I also checked that the other script-type* and …
=> LibWeb: Make javascript mime matching more compliant with spec.

Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
This was causing crashes in Worker test cases making use of promises, fixing a regression introduced in
da18551f1005300d1b80761462fabe34e142e5d0
=> LibWeb: Don't assume a Window global object in HostEnqueuePromiseJob

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Userland/Libraries/LibJS/Runtime/ArgumentsObject.cpp, Userland/Libraries/LibJS/Runtime/ArgumentsObject.h, Userland/Libraries/LibJS/Runtime/Array.cpp, Userland/Libraries/LibJS/Runtime/Array.h, Userland/Libraries/LibJS/Runtime/ModuleNamespaceObject.cpp, Userland/Libraries/LibJS/Runtime/ModuleNamespaceObject.h, Userland/Libraries/LibJS/Runtime/Object.cpp, Userland/Libraries/LibJS/Runtime/Object.h, Userland/Libraries/LibJS/Runtime/ProxyObject.cpp, Userland/Libraries/LibJS/Runtime/ProxyObject.h, Userland/Libraries/LibJS/Runtime/StringObject.cpp, Userland/Libraries/LibJS/Runtime/StringObject.h, Userland/Libraries/LibJS/Runtime/TypedArray.h, Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp, Userland/Libraries/LibWeb/Bindings/PlatformObject.h, Userland/Libraries/LibWeb/HTML/Location.cpp, Userland/Libraries/LibWeb/HTML/Location.h, Userland/Libraries/LibWeb/HTML/WindowProxy.cpp, Userland/Libraries/LibWeb/HTML/WindowProxy.h
The `[[GetOwnProperty]]` internal method invocation in `OrdinarySetWithOwnDescriptor` was being invocated again with the same parameters in the `[[DefineOwnProperty]]` internal method that is also later called in `OrdinarySetWithOwnDescriptor`.
The `PlatformObject.[[DefineOwnProperty]]` has similair logic.
This change adds an optional parameter to the `[[DefineOwnProperty]]` internal method so the results of the previous `[[GetOwnProperty]]` internal method invocation can be re-used.
=> LibJS+LibWeb: Prevent double invocation of `[[GetOwnProperty]]`

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
Fixes https://wpt.fyi/results/jpegxl/3x3a_srgb_lossless.html?product=ladybird and https://wpt.fyi/results/jpegxl/3x3a_srgb_lossy.html?product=ladybird
Fixes images on https://jpegxl.info/resources/jpeg-xl-test-page
=> LibGfx: Respect unpremultiplied alpha for JPEG XL

Ladybird/RequestServer/CMakeLists.txt, Userland/Libraries/LibRequests/Request.cpp, Userland/Libraries/LibRequests/Request.h, Userland/Libraries/LibRequests/RequestClient.cpp, Userland/Libraries/LibRequests/RequestClient.h, Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp, Userland/Libraries/LibWeb/Loader/ResourceLoader.h, Userland/Services/RequestServer/ConnectionFromClient.cpp, Userland/Services/RequestServer/RequestClient.ipc
Fixes 54 test cases across the following WPT tests :^)
- http://wpt.live/xhr/status-basic.htm
- http://wpt.live/xhr/status-async.htm
=> LibRequests+LibWeb+RequestServer: Propagate HTTP reason phrase

Tests/LibWeb/Ref/background-clip-text.html, Tests/LibWeb/Ref/reference/background-clip-text-ref.html, Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
This save() call did not have matching restore(). For mask application it's display list builder responsibility to emit save() and restore() so mask is applied only to relevant portion.
Progress on https://www.jetbrains.com/
=> LibWeb: Remove save() call in DisplayListPlayerSkia::add_mask()

Userland/Libraries/LibJS/Runtime/IndexedProperties.cpp, Userland/Libraries/LibJS/Runtime/IndexedProperties.h
There is no need to do a full linear search from start to end when we can just remember the position and continue where we left off.
=> LibJS: Remember the position into the cached indices

Tests/LibWeb/Text/expected/css/cubic-bezier-infinite-slope-crash.txt, Tests/LibWeb/Text/input/css/cubic-bezier-infinite-slope-crash.html, Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp
In some cases floating point imprecision can cause a cubic bezier with an infinite slope at the end to never reach exactly x=1.
Fixes a crash on https://comp.anu.edu.au/sapling/index.html when a dropdown animation finishes.
Also includes a crash test.
=> LibWeb: Use machine epsilon when approximating cubic bezier

Tests/LibWeb/Text/expected/Crypto/SubtleCrypto-aesgcm.txt, Tests/LibWeb/Text/input/Crypto/SubtleCrypto-aesgcm.html, Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
Previously, callers were passing the size in bytes, but the method expected bits. This caused a crash in LibCrypto when verifying the key size later on.
Also make the naming of local variables and parameters a little more clear between the different AES algorithms :^)
cc: @BenWiederhake
=> LibWeb/Crypto: Fix sizes being passed into `generate_aes_key()`

Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebContent/WebDriverConnection.h, Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Session.cpp
Making these async were all actually pretty trivial. This patch does so, and removes the deprecated synchronous user prompt handler.
This should fix ~400 WPT subtests.
=> WebContent+WebDriver: Convert all user prompt handlers to be async

Userland/Libraries/LibWeb/ServiceWorker/Job.cpp
`vm.realm()` might not exist, and was probably not even the right realm to use in the first place.
=> LibWeb: Use the realm from the `ServiceWorker` client

Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/wpt-import/html/infrastructure/safe-passing-of-structured-data/structured-cloning-error-extra.txt, Tests/LibWeb/Text/expected/wpt-import/html/infrastructure/safe-passing-of-structured-data/structuredclone_0.txt, Tests/LibWeb/Text/expected/wpt-import/html/infrastructure/safe-passing-of-structured-data/window-postmessage.window.txt, Tests/LibWeb/Text/input/wpt-import/common/sab.js, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/messagechannel.any.js, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/resources/echo-iframe.html, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/resources/echo-iframe.html.headers, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/resources/echo-worker.js, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/resources/echo-worker.js.headers, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/resources/iframe-resizable-arraybuffer-helper.html, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/resources/post-parent-type-error.html, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/structured-cloning-error-extra.html, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/structured-cloning-error-stack-optional.sub.window.js, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/structuredclone_0.html, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/transfer-errors.window.js, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/window-postmessage.window.html, Tests/LibWeb/Text/input/wpt-import/html/infrastructure/safe-passing-of-structured-data/window-postmessage.window.js, Tests/LibWeb/Text/input/wpt-import/html/webappapis/structured-clone/structured-clone-battery-of-tests-harness.js, Tests/LibWeb/Text/input/wpt-import/html/webappapis/structured-clone/structured-clone-battery-of-tests-with-transferables.js, Tests/LibWeb/Text/input/wpt-import/html/webappapis/structured-clone/structured-clone-battery-of-tests.js, Userland/Libraries/LibJS/Runtime/DataView.h
This fixes structured serialization of DataView. It was expected to be uniform with TypedArray, which returns u32 for byte_offset().
This was covered by a number of WPT infrastructure tests, which this commit also imports.
=> LibJS: Make DataView::byte_offset() return u32

AK/String.h, Tests/AK/TestString.cpp, Userland/Libraries/LibUnicode/CharacterTypes.cpp, Userland/Libraries/LibUnicode/CharacterTypes.h, Userland/Libraries/LibUnicode/String.cpp, Userland/Libraries/LibWeb/WebDriver/ElementLocationStrategies.cpp, Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp, Userland/Libraries/LibWeb/WebDriver/ElementReference.h, Userland/Services/WebContent/WebDriverConnection.cpp
This implements:
* Switching frames via numeric IDs
* Non-XPath element locators
* A step towards a spec-compliant method of getting rendered text
=> LibWeb: Implement some missing WebDriver features

Meta/WPT.sh
This change allows the test list given to `WPT.sh run` to include full filesystem relative or absolute pathnames. That facilitates using tab completion in the shell to browse for pathnames, and also facilitates copy-paste of full filesystem pathnames. For example:
```
./Meta/WPT.sh run Tests/LibWeb/WPT/wpt/dom/historical.html
./Meta/WPT.sh run /opt/ladybird/Tests/LibWeb/WPT/wpt/dom/historical.html
```
Otherwise, without this change, the test list can’t include full filesystem pathnames, but is instead limited to only path fragments that specify WPT subdirectory pathnames — which doesn’t allow for tab completion on pathnames in the shell, nor copy-paste of full pathnames.
=> Tests: Allow full relative or absolute pathnames for test files to run

Tests/LibWeb/Text/expected/HTML/HTMLFrameElement-add-remove.txt, Tests/LibWeb/Text/expected/HTML/HTMLFrameElement-load.txt, Tests/LibWeb/Text/input/HTML/HTMLFrameElement-add-remove.html, Tests/LibWeb/Text/input/HTML/HTMLFrameElement-load.html, Userland/Libraries/LibWeb/HTML/HTMLFrameElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLFrameElement.h, Userland/Libraries/LibWeb/HTML/HTMLFrameElement.idl, Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp, Userland/Libraries/LibWebView/InspectorClient.cpp, Userland/Libraries/LibWebView/InspectorClient.h, Userland/Services/WebContent/WebDriverConnection.cpp
NavigableContainer is our home grown concept which already contains the
AOs needed for `frame` and `iframe` elements. This patch simply aligns our
HTMLFrameElement implementation with this class.
A couple of notes:
1. The `<script>` in the `<head>` element is intentional. The `<frameset>`
element effectively takes the place of the `<body>` element, and we
cannot add a `<script>` to a `<frameset>` element.
2. We don't render `<frameset>` or `<frame>` at all. Rendering is defined
in the following spec:
https://html.spec.whatwg.org/multipage/rendering.html#frames-and-framesets
3. If you load the test page in your browser, you won't see anything,
regardless of (2). Our test infra adds a `<pre>` element to the "body"
element (which is the `<frameset>` element here). Such children will
never be …
=> LibWeb: Implement HTMLFrameElement as a NavigableContainer

Tests/LibWeb/Text/expected/HTML/HTMLInputElement-blur.txt, Tests/LibWeb/Text/input/HTML/HTMLInputElement-blur.html, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Fixes a crash seen on http://wpt.live when attempting to filter passing or failing tests.
=> LibWeb: Don't crash when input with no associated text node loses focus

Tests/LibWeb/Ref/color-hsl.html, Tests/LibWeb/Ref/color-hwb.html, Tests/LibWeb/Ref/color-oklab.html, Tests/LibWeb/Ref/color-oklch.html, Tests/LibWeb/Ref/color-rgb.html, Tests/LibWeb/Ref/reference/color-hsl-ref.html, Tests/LibWeb/Ref/reference/color-hwb-ref.html, Tests/LibWeb/Ref/reference/color-oklab-ref.html, Tests/LibWeb/Ref/reference/color-oklch-ref.html, Tests/LibWeb/Ref/reference/color-rgb-ref.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.h
This PR updates the CSS parser to support the keyword 'none' in the CSS4 color functions. The underlying CSSColorValue already supports this keyword, meaning the parser can instantiate the color directly.
This removes 3 TODOs and fixes a few WPT tests, mainly in `css/css-color/parsing` and in HSL tests.
In the new tests, I avoided colors that have rounding issues, so these should be stable in time.
=> LibWeb: Parse the keyword 'none' in the CSS4 color functions

Meta/WPT.sh
This invokes the existing `import-wpt-test.py` script, then uses `headless-browser` to create an expectation file.
=> Meta: Add an option to `WPT.sh` to import WPT tests

Tests/LibWeb/Layout/expected/css-table-cell-verticalalign-text-top.txt, Tests/LibWeb/Layout/input/css-table-cell-verticalalign-text-top.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
This seems to be a totally right thing to do. As per https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align
```
[baseline](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align#baseline_2) (and sub, super, text-top, text-bottom, <length>, and <percentage>)
Aligns the baseline of the cell with the baseline of all other cells in the row that are baseline-aligned.
```
I have a test that demonstates the issue
```
<html lang="en">
<head>
<title>Vertical Align Test: text-top, text-bottom, and baseline</title>
<style>
table {
width: 100%;
border-collapse: collapse;
}
td {
border: 1px solid black;
width: 300px;
height: 300px;
text-align: center;
}
</style>
</head>
<body>
<table>
<tr>
<td style="vertical-align: text-top;">
Text aligned at the top
</td>
<td …
```
=> Verticalalign table cells

Meta/CMake/common_compile_options.cmake
This warning is already enabled by our existing flags with gcc-13, so make sure that clang checks these as well.
=> CMake: Add warning for missing field initializers globally

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Previously, input elements weren't always redrawn when their checkedness was set programmatically.
The issue can be seen on the following test page:
```html
<input id="checkbox" type="checkbox">
<input id="radio1" type="radio" name="radio">
<input id="radio2" type="radio" name="radio">
<script>
const checkbox = document.getElementById("checkbox");
const radio1 = document.getElementById("radio1");
const radio2 = document.getElementById("radio2");
let currentRadio = radio1
setInterval(() => {
checkbox.click();
currentRadio.click();
currentRadio = currentRadio === radio1 ? radio2 : radio1;
}, 100);
</script>
```
Before this change, all of the above inputs would appear to remain unchecked - unless something happened which forced a repaint - such as a window resize.
I've tried …
=> LibWeb: Ensure inputs are repainted when their checkedness is toggled

Userland/Libraries/LibWeb/HTML/HTMLButtonElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLButtonElement.h, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h, Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLSelectElement.h, Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
According to the specification "actually disabled" elements should not be focusable:
* https://html.spec.whatwg.org/multipage/interaction.html#focusable-area
The definition of "actually disabled" elements:
* https://html.spec.whatwg.org/multipage/semantics-other.html#concept-element-disabled
Should fix most of the following tests:
* https://wpt.fyi/results/html/semantics/disabled-elements/disabledElement.html?label=experimental&product=ladybird
This PR changes the `is_focusable` implementations for the few form elements to account for the `disabled` state using already inherited `FormAssociatedElement::enabled()` method.
https://github.com/user-attachments/assets/5b4eaa2c-eab4-4ade-98c2-a15289235fed
=> LibWeb: Do not allow focusing "actually disabled" elements

Tests/LibWeb/Layout/expected/table/clip-spans-to-table-end.txt, Tests/LibWeb/Layout/expected/table/colspan-overflow-crash.txt, Tests/LibWeb/Layout/input/table/colspan-overflow-crash.html, Userland/Libraries/LibWeb/Layout/TableGrid.cpp
Prevents a crash on https://en.wikipedia.org/wiki/Roguelike.
The crash occurs when a colspan causes cell's position to be further than the width of the first row (see crashtest).
=> LibWeb: Consider every row when calculating table width

AK/GenericLexer.cpp, AK/GenericLexer.h, Tests/LibWeb/Text/expected/css/unicode-range-all-wildcard.txt, Tests/LibWeb/Text/input/css/unicode-range-all-wildcard.html, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
Fixes a segfault when parsing a wildcard-only unicode range.
=> LibWeb+AK: Prevent segfault when parsing unicode ranges

Documentation/Testing.md, Meta/import-wpt-test.py, Tests/LibWeb/Ref/expected/wpt-import/css/css-nesting/nesting-basic-ref.html, Tests/LibWeb/Ref/input/wpt-import/css/css-nesting/nesting-basic.html, Tests/LibWeb/Text/expected/wpt-import/css/css-nesting/cssom.txt, Tests/LibWeb/Text/input/wpt-import/css/css-nesting/cssom.html
First off, my Python knowledge is pretty lacking so my code is probably horrible. Apologies in advance, and suggestions welcome. A lot of what I was writing felt a bit hacky.
Usage is still `Meta/WPT.sh some/path/to/a/ref/test.html`: It figures out what kind of test it is, so you don't have to care.
As noted, I've imported a couple of nesting tests (a ref test and a text test) to make sure it all worked right.
One difference with importing ref tests is that you have to wait until they pass before you import them, because unlike text tests, there's no way to save an expectation of "these subtests pass but that one doesn't". Though, the normal skip mechanism will work if you still want to import them.
=> Tests: Allow importing WPT ref-tests

Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Session.cpp, Userland/Services/WebDriver/Session.h
Capabilities are configured on a per-session basis, but we were only applying these options to the first WebContent process created. We need to pass these options to new windows created from that process.
This fixes the following WPT tests:
`/webdriver/tests/classic/close_window/user_prompts.py`
`/webdriver/tests/classic/switch_to_window/switch.py`
=> WebDriver: Transfer session capabilities to new windows, and some window closing fixes

Tests/LibXML/TestParser.cpp, Userland/Libraries/LibXML/Parser/Parser.cpp
1901 new passing tests in http://wpt.live/dom/nodes/ParentNode-querySelector-All-xht.xht
This is a somewhat hacky way to get code points out of a `GenericLexer`, alternative solutions include:
- Adding `*_code_point` methods to `GenericLexer`
- Creating a new "unicode-aware" lexer (`Utf8Lexer`?)
=> LibXML: Read code points when parsing names

Tests/LibWeb/Layout/expected/table/border-conflict-resolutions-with-more-cells-than-cols.txt, Tests/LibWeb/Layout/input/table/border-conflict-resolutions-with-more-cells-than-cols.html, Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Propagated checks (that were already in some parts of the code) to ensure we are within a valid range of m_col_elements_by_index.
This crashed an internal Jenkins instance page, but I could not find a public one to demo.
On Chrome:
After fixing Ladybird:
=> LibWeb: Fix out-of-bound crash when there's more table cells than cols

AK/NonnullRawPtr.h, Userland/Libraries/LibWeb/CSS/Parser/ComponentValue.cpp, Userland/Libraries/LibWeb/CSS/Parser/ComponentValue.h, Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp, Userland/Libraries/LibWeb/CSS/Parser/MediaParsing.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
This class was being copied all over the place, however, most of these
cases can be easily prevented with `auto const&` or `Nonnull<>`.
It also didn't have a move constructor, causing `Vector` to copy on
every resize as well.
Removing all these copies results in an almost 15% increase in
performance for CSS parsing, as measured with callgrind.
=> LibWeb: Remove most of the copying of `CSS::Parser::ComponentValue`

Userland/Libraries/LibWeb/DOM/Document.cpp
While traversing the DOM tree, looking for nodes that need a style update, we were recomputing style for every node visited along the way, even nodes that didn't themselves need a style update (but one of their descendants did).
This avoids a bunch of completely unnecessary style recomputation on basically every website.
=> LibWeb: Avoid unnecessary style recomputation during traversal

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/DOM/DocumentObserver.cpp, Userland/Libraries/LibWeb/DOM/DocumentObserver.h, Userland/Libraries/LibWeb/Page/Page.h, Userland/Libraries/LibWebView/WebContentClient.cpp, Userland/Libraries/LibWebView/WebContentClient.h, Userland/Services/WebContent/PageClient.cpp, Userland/Services/WebContent/PageClient.h, Userland/Services/WebContent/WebContentClient.ipc, Userland/Services/WebContent/WebDriverConnection.cpp
Fixes the following tests, which were previously timing out:
```
/webdriver/tests/classic/back/back.py
/webdriver/tests/classic/back/user_prompts.py
/webdriver/tests/classic/forward/forward.py
/webdriver/tests/classic/forward/user_prompts.py
```
=> WebDriver: Bring the Back and Forward endpoints up to spec

Userland/Libraries/LibWeb/CSS/StyleValues/CSSColorValue.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CSSHWB.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CSSRGB.cpp
As seen in https://github.com/LadybirdBrowser/ladybird/pull/1091#issuecomment-2407342711
=> LibWeb/CSS: Avoid double promotion in CSSColorValue code

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Bytecode/Interpreter.h, Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp, Userland/Libraries/LibWeb/HTML/Scripting/ClassicScript.h, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.h, Userland/Services/WebContent/WebContentConsoleClient.cpp
The previous fix essentially generated a script of the form:
```js
function() {
// ... the script entered into the console ...
}
```
Thus, any `let` expressions would not escape the function scope. This PR reverts that attempt, and instead fixes `$0` by avoiding global binding bytecode generation when we've overridden the lexical environment with a `with` object at runtime. We already use this same avoidance at parse time, i.e. the following script:
```js
with (foo) {
console.log(x);
}
```
will not generate a global binding lookup for the variable `x`. Our environment override is a completely ad-hoc feature, and is a run time feature - so we must employ the same tactic as `with` statement at run time.
CC @gmta
=> LibWeb: Revert previous attempt to fix `$0`

.github/workflows/lint-code.yml, Meta/lint-prettier.sh, Userland/Libraries/LibJS/Tests/modules/import-with-assertions.mjs, Userland/Libraries/LibJS/Tests/test-common-tests.js, Userland/Libraries/LibJS/Tests/this-value-strict.js, Userland/Libraries/LibJS/Tests/this-value.js
Prettier v3 was released over a year ago, and most users will have it by default by now.
=> Meta+LibJS: Upgrade to prettier version 3.3.3

Tests/LibGfx/TestImageDecoder.cpp, Userland/Libraries/LibGfx/Bitmap.cpp, Userland/Libraries/LibGfx/Bitmap.h, Userland/Libraries/LibGfx/ImageFormats/BMPLoader.cpp, Userland/Libraries/LibGfx/PainterSkia.cpp, Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp, Userland/Utilities/image.cpp
I was inspired by comments here https://github.com/LadybirdBrowser/ladybird/pull/1167 and I tried to implement passing RGBx data (w/o alpha channel) to Skia.
Fixes #1132
=> LibGfx: Fix BMPs and send RGBx data to Skia

Ladybird/Headless/Test.cpp, Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/abspos/abspos-containing-block-initial-004-ref.xht, Tests/LibWeb/Ref/input/wpt-import/css/CSS2/abspos/abspos-containing-block-initial-004a.xht
This makes importing WPT reftests with an xht extension easier.
=> headless-browser: Support running tests with the ".xht" extension

Ladybird/Headless/Test.cpp
Paths in `headless-browser` tests were being compared by string value. With this patch, they will be compared by their real path instead, ensuring relative paths and symlinks are handled correctly.
=> Tests: Use `FileSystem::real_path` when comparing paths

Ladybird/AppKit/UI/Event.h, Ladybird/AppKit/UI/Event.mm, Ladybird/AppKit/UI/Inspector.mm, Ladybird/AppKit/UI/LadybirdWebView.h, Ladybird/AppKit/UI/LadybirdWebView.mm, Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp, Ladybird/AppKit/UI/LadybirdWebViewBridge.h, Ladybird/AppKit/UI/LadybirdWebViewWindow.mm, Ladybird/AppKit/UI/Tab.mm, Ladybird/AppKit/UI/TaskManager.mm, Ladybird/AppKit/UI/TaskManager.swift, Ladybird/AppKit/module.modulemap, Ladybird/Qt/FindInPageWidget.cpp, Ladybird/Qt/WebContentView.cpp, Ladybird/Qt/WebContentView.h, Userland/Libraries/LibWeb/CSS/Parser/Types.h, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Libraries/LibWebView/WebContentClient.cpp, Userland/Libraries/LibWebView/WebContentClient.h, Userland/Services/WebContent/PageClient.cpp, Userland/Services/WebContent/WebContentClient.ipc
Now that scrolling and rendering scrollbars is handled entirely in the WebContent process, there's no reason to place the WebView inside scroll views.
This doesn't make much of a difference for Qt, but for AppKit we had to do a fair amount of extra work do deal with scroll views, as AppKit separately tracks "content" and "document" views (described here https://github.com/trflynn89/ladybird-appkit/commit/6e5ec9275ed1de3ea39467b342aa80a26cfde2a6).
=> UI: Do not place the WebView inside a scroll view

.github/workflows/ci.yml, .github/workflows/lagom-template.yml
For some reason, Microsoft have decided to remove Xcode 16 from macOS 14
images. We require Xcode 16 for Swift 6.
See: https://github.com/actions/runner-images/issues/10703
Because macOS 15 images are still in preview, their availability is much
lower than macOS 14 images. To hopefully alleviate the amount of time we
are waiting in the runner queue, for now this only upgrades the workflow
which uses Swift.
=> CI: Upgrade to macOS 15

Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp, Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Services/WebContent/WebDriverConnection.cpp
This removes unnecessairy reference counting.
=> LibWeb: Return `CSS::StyleProperties::property` results by reference 

Tests/LibWeb/TestConfig.ini
Timed out here: https://github.com/LadybirdBrowser/ladybird/actions/runs/11739680501/job/32704663141?pr=2216#step:17:3378
Seems like animations tests are generally flaky so I've grouped them.
cc @awesomekling as you added this one yesterday.
=> Tests: Disable an animation test that's flaky on CI

Meta/gn/README.md
Homebrew doesn't have an entry for gn, so this was confusing.
=> Documentation: Stop telling people to get gn from homebrew

.devcontainer/features/ladybird/devcontainer-feature.json, .devcontainer/features/ladybird/install.sh, .github/actions/setup/action.yml, Documentation/BuildInstructionsLadybird.md, Meta/CMake/fontconfig.cmake, Meta/CMake/skia.cmake, Meta/CMake/vulkan.cmake, vcpkg.json
Now that we are using shared libraries, it is possible to add
into our vcpkg dependencies without worrying about LGPL.
And some assorted vcpkg + CMake cleanup.
Replacement for #291
=> Meta: Add ffmpeg to vcpkg dependencies

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp, Userland/Libraries/LibJS/Tests/functions/function-assignment-in-arguments.js
As shown in the test added by this patch, it was possible to re-assign the `this` value of a member function call while it was executing. Let's copy the original this value like we already do with the callee.
Fixes #2226.
=> LibJS: Preserve the original `this` value

.github/workflows/ladybird-js-artifacts.yml, AK/CMakeLists.txt, CMakePresets.json, Meta/CMake/vcpkg/distribution-triplets/arm64-linux.cmake, Meta/CMake/vcpkg/distribution-triplets/arm64-osx.cmake, Meta/CMake/vcpkg/distribution-triplets/distribution.cmake, Meta/CMake/vcpkg/distribution-triplets/x64-linux.cmake, Meta/CMake/vcpkg/distribution-triplets/x64-osx.cmake, Meta/Lagom/CMakeLists.txt
This adds the vcpkg triplets and CMake preset to perform official builds for distribution. These builds are fully static, and currently intended to be used for the `js` ESVU release.
In the future, linking everything statically into the final binary is probably not what we will do for released Ladybird builds. Instead, we may have a "libladybird.so", which is then linked into the binary. But this should be fine for `js` for now.
Example build:
https://github.com/trflynn89/ladybird/actions/runs/11743377506
=> CI: Add CMake a preset for "official" builds, and use it for `js` artifacts

Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_tooltip.txt, Tests/LibWeb/Text/input/wpt-import/accname/name/comp_tooltip.html, Userland/Libraries/LibWeb/DOM/Node.cpp
This change fixes accessible-name computation for:
- an element that has empty text content but that also has a `title` attribute (”tooltip”) with a non-empty value
- an `img` element whose `alt` attribute is the empty string but that also has a `title` attribute with a non-empty value
Otherwise, without this change, the accessible name unexpectedly isn’t computed correctly for those cases.
This change gets us passing all 23 subtests in the `comp_tooltip.html` test at https://wpt.fyi/results/accname/name?product=ladybird.
=> LibWeb: Fix accessible-name computation for “tooltip” & empty-alt cases

Tests/LibWeb/Text/expected/wpt-import/streams/writable-streams/aborting.any.txt, Tests/LibWeb/Text/input/wpt-import/streams/writable-streams/aborting.any.html, Tests/LibWeb/Text/input/wpt-import/streams/writable-streams/aborting.any.js, Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
This fixes a crash seen on:
http://wpt.live/streams/writable-streams/aborting.any.html
I believe this is a spec bug, which has been reported to the Streams spec.
=> LibWeb: Reorder step to get chunk size after checking for aborted stream

Tests/LibWeb/Text/expected/wpt-import/streams/readable-byte-streams/read-min.any.txt, Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/read-min.any.html, Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/read-min.any.js, Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
Fixes a crash running the imported WPT test.
=> LibWeb: Enable callbacks for ByteStreamTeeBYOBReadRequest::on_chunk

Userland/Libraries/LibGfx/Bitmap.cpp, Userland/Libraries/LibGfx/Bitmap.h
I'm just modifying your header files so you'll have to call a mass rebuild, accelerating climate change in the process. This important work was proudly sponsored by the Reptoid Shadow Government™.
Jokes aside, this PR removes the now-obsolete Gfx::Bitmap encoder and decoder, which were replaced by BitmapSequence in #1435. The .ipc files no longer reference them, and calling IPC::encode or IPC::decode on these will result in compiler errors, ensuring they aren’t mistakenly used.
Let me know if you spot any hidden Reptoid agendas in the code!
=> IPC: Remove Gfx::Bitmap encoder and decoder

.devcontainer/features/vcpkg-cache/install.sh, Userland/Libraries/LibWeb/HTML/MessagePort.cpp
We were delaying sending an IPC message until the HTML PortMessage
task was run, but we were not queuing the task in on the receiver
side. The result of this was that message port posting was
needlessly creating an HTML task just to send an IPC message.
On the flip side, we were directly calling dispatch_event from the
socket notifier of the target port's message queue. This is a huge
problem, because it means that we were effectively running
javascript-aware code from an 'in parallel' context.
By switching around which side of the IPC interface is responsible
for queuing a task, we can avoid problems where a document is
destroyed from a port message-attached callback and crashes.
This fixes the crash in https://github.com/LadybirdBrowser/ladybird/issues/2242
=> LibWeb: Queue the task for MessagePort receive in targetPort's realm

Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp
"determine the computed MIME type" != "extract a MIME type"
Fixes two 60 second timemouts and 645 subtests on [dom/nodes/Document-characterSet-normalization-1.html](http://wpt.live/dom/nodes/Document-characterSet-normalization-1.html) and [dom/nodes/Document-characterSet-normalization-2.html](http://wpt.live/dom/nodes/Document-characterSet-normalization-2.html)
Unfortunately I don't think I can write an in-tree test for this without a http server, remind me when #1801 is merged. 
(or we could hardcode a link to wpt.live's server)
=> LibWeb: Compute mimetype when loading a document

Tests/LibWeb/Ref/expected/wpt-import/css/css-color/greensquare-ref.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/xyz-001.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/xyz-d65-001.html, Userland/Libraries/LibGfx/Color.cpp, Userland/Libraries/LibGfx/Color.h, Userland/Libraries/LibWeb/CSS/StyleValues/CSSColor.cpp, Userland/Libraries/LibWeb/CSS/StyleValues/CSSColor.h, Userland/Libraries/LibWeb/CSS/StyleValues/CSSColorValue.h
This also adds support for `xyz` as it defaults to `xyz-d65`. We now
pass the following WPT tests:
- css/css-color/xyz-001.html
- css/css-color/xyz-002.html
- css/css-color/xyz-004.html
- css/css-color/xyz-d65-001.html
- css/css-color/xyz-d65-002.html
- css/css-color/xyz-d65-004.html
=> LibWeb/CSS: Support the xyz-d65 colorspace in the color() function

Userland/Libraries/LibWeb/HTML/EventNames.h, Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
Corresponds to https://github.com/whatwg/html/pull/10091
=> LibWeb/HTML: Dispatch toggle and beforetoggle events from dialogs

Meta/WPT.sh
This change allows you to give `http[s]://wpt.live/` URLs to the `WPT.sh` script for both the `WPT.sh run` and `WPT.sh import` commands.
That facilitates the use case where you’ve navigated to a wpt.live URL in a browser, and you want to just directly copy-paste the URL in order to either run the test in Ladybird, or import the test into the repo.
Otherwise, without this change, when using `WPT.sh`, you’re limited to needing to specify either a WPT path fragment or filesystem pathname — which doesn’t allow for easy copy-paste directly from wpt.fyi.
=> Tests: Allow wpt.live URLs for both “WPT.sh run” and “WPT.sh import”

Documentation/FAQ.md
This is an attempt at beefing up the FAQ a bit by adding some detailed-yet-succinct overview stuff about the project and its history.
https://github.com/sideshowbarker/ladybird/blob/overview.md-add/Documentation/FAQ.md#what-are-some-things-that-ladybird-isnt (and forward from there) has the rendered (HTML) view of the additions to the FAQ.
=> Docs: Beef up the FAQ

Libraries/LibJS/Runtime/AbstractOperations.cpp, Libraries/LibJS/Tests/builtins/String/String.prototype.replace.js
This was resulting in a crash for the WPT test case:
https://wpt.live/xhr/send-data-string-invalid-unicode.any.html
=> LibJS: Allow unpaired surrogates in String.prototype.replace

Libraries/LibWeb/Painting/Command.h, Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp, Libraries/LibWeb/Painting/DisplayListRecorder.cpp, Libraries/LibWeb/Painting/DisplayListRecorder.h, Libraries/LibWeb/Painting/PaintableBox.h, Libraries/LibWeb/Painting/SVGForeignObjectPaintable.h, Libraries/LibWeb/Painting/SVGGraphicsPaintable.h, Libraries/LibWeb/Painting/SVGMaskable.cpp, Libraries/LibWeb/Painting/SVGMaskable.h
This allows to delete duplicated code between DisplayListPlayerSkia.cpp and ImmutableBitmap.cpp responsible for wrapping Gfx::Bitmap in SkImage.
=> LibWeb: Save Gfx::ImmutableBitmap in ApplyBitmapMask display list item

Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Libraries/LibWeb/Layout/FlexFormattingContext.h, Libraries/LibWeb/Layout/FormattingContext.cpp, Libraries/LibWeb/Layout/FormattingContext.h, Tests/LibWeb/Text/expected/wpt-import/css/css-flexbox/flex-minimum-height-flex-items-012.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-flexbox/percentage-size-quirks.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-flexbox/percentage-size.txt
If available space is definite it should always match the size of the containing block. Therefore, there is no need to do containing block node lookup.
=> LibWeb: Use available space to resolve sizes in FFC

Libraries/LibWeb/Layout/GridFormattingContext.cpp, Tests/LibWeb/Layout/expected/grid/grid-row-overflow-crash.txt, Tests/LibWeb/Layout/expected/grid/row-gaps-with-overflowing-spans-crash.txt, Tests/LibWeb/Layout/input/grid/grid-row-overflow-crash.html, Tests/LibWeb/Layout/input/grid/row-gaps-with-overflowing-spans-crash.html
Fixes 9 crashes in WPT `/css/css-grid/`.
This removes a check added in https://github.com/SerenityOS/serenity/pull/16669 which was added to fix a separate bug.
The test added in that PR was removed in https://github.com/LadybirdBrowser/ladybird/pull/1584 so I have re-added it as a layout test.
The check appears to no longer be necessary as the old test still passes without it.
I have also verified that this change doesn't cause any regressions by comparing WPT results before and after (with the VERIFY removed so that the crashes don't hide any regressions).
Finally, I have added a minimised reproduction of a WPT crash.
=> LibWeb: Don't crash from clipping grid spans

UI/Headless/Application.cpp, UI/Headless/Application.h, UI/Headless/Test.cpp
We now skip so many tests that the list of skipped tests exceeds the height of my terminal. Let's skip logging these by default, as it is too noisy to find actually relevant information.
=> headless-browser: Do not log skipped tests by default

Libraries/LibJS/Parser.cpp, Libraries/LibJS/Tests/syntax/slash-after-block.js
The following syntax is valid:
```js
e?.example / 1.2
```
Previously, the `/` would be treated as a unterminated regex literal, because it was calling the regular `consume` instead of `consume_and_allow_division`.
This is what is done when parsing IdentifierNames in parse_secondary_expression when a period is encountered.
Allows us to parse clients-main-[hash].js on https://ubereats.com/
=> LibJS: Allow division after IdentifierNames in optional chain

Libraries/LibWeb/DOM/ParentNode.cpp, Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/wpt-import/css/css-nesting/top-level-is-scope.txt
This is kind of two unrelated changes, I just didn't realise they were unrelated at the time. 😆 
Saw the test fails, immediately noticed that the two querySelector implementations duplicated a lot of code and decided to combine them. Then... discovered that the test now passes anyway even without that change. Something must have fixed the crash since I added it.
=> querySelector things

Libraries/LibWeb/CSS/ComputedValues.h, Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWeb/DOM/Node.h, Libraries/LibWeb/HTML/HTMLImageElement.h, Libraries/LibWeb/Layout/TreeBuilder.cpp, Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_name_from_content.txt, Tests/LibWeb/Text/input/wpt-import/accname/name/comp_name_from_content.html
This PR updates the implementation for [computing accessible names](https://w3c.github.io/accname/#computation-steps) (begun in da5c918) such that it gets Ladybird passing all 60 subtests in the `comp_name_from_content`.html test at https://wpt.fyi/results/accname/name?product=ladybird — an increase in 41 new passes.
To facilitate review and to provide for a more-granular commit history, the changes in this PR are in 7 separate commits:
a6993d243b6 Fix accessible-name computation for pseudo-element content
3f038859253 Fix accessible-name computation for `aria-labelledby` cases
744f325e91b Support computing accessible names from image `alt` attributes
ad53c74fbe2 Use rendered text in accessible-name computation
904899fe791 Ensure spaces get added where expected within accessible names …
=> LibWeb: Make all  WPT accname/name/comp_name_from_content.html tests pass

Libraries/LibRegex/RegexOptimizer.cpp, Tests/LibRegex/Regex.cpp
=> LibRegex: Don't ignore references that weren't bound in checked blocks

Libraries/LibJS/Runtime/DateConstructor.cpp, Libraries/LibJS/Tests/builtins/Date/Date.parse.js
This format is used on https://jojowiki.com/ to show countdowns to new releases.
=> LibJS: Parse dates like "November 19 2024 00:00:00 +0900"

Libraries/LibWebView/ViewImplementation.cpp, Libraries/LibWebView/ViewImplementation.h, UI/Headless/HeadlessWebView.cpp, UI/Headless/HeadlessWebView.h, UI/Headless/Test.cpp, UI/Headless/Test.h
Instead of bringing the whole browser down, let's re-initialize the WebContent client so we can move on. This is particularly needed for WPT.
=> headless-browser: Handle WebContent crashes similar to the graphical UIs

Libraries/LibJS/AST.cpp, Libraries/LibJS/Heap/ConservativeVector.h, Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp, Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.h
Today we put an end to the leaks on Speedometer!
And also fix an issue where JS `class` constructors could have their static fields corrupted by a badly-timed GC.
=> The daily batch of GC fixes

Libraries/LibJS/Bytecode/Interpreter.cpp
When the cached value was not an accessor, it was simply ignored. This is the value we really want, so we can just return it. 
Not sure why this was not done before, but I could not find any problems with it.
Shows up to 5x improvements on some benchmarks, and 1.4x in general js-benchmarks.
I was specifically profiling imaging-gaussian-blur.js, which saw the greatest improvement.
```
Suite       Test                                   Speedup  Old (Mean ± Range)        New (Mean ± Range)
----------  -----------------------------------  ---------  ------------------------  ------------------------
...
Kraken      imaging-gaussian-blur.js                 5.181  69.403 ± 61.580 … 73.960  13.397 ± 12.160 … 15.240
...
SunSpider   Total                                    1.244  3.413 …
```
=> LibJS: Correctly return cached value for global var bindings

Libraries/LibGfx/PaintingSurface.cpp, Libraries/LibGfx/PaintingSurface.h, Libraries/LibWeb/WebDriver/Screenshot.cpp
Previously, we always returned a blank canvas from `draw_bounding_box_from_the_framebuffer()`, which caused many WPT reftests to pass erroneously.
=> LibGfx+LibWeb: Copy bitmap onto the returned canvas when taking a screenshot

Libraries/LibWeb/DOM/ShadowRoot.h, Libraries/LibWeb/HTML/HTMLIFrameElement.cpp, Tests/LibWeb/Text/expected/DOM/shadow-root-boundary-of-inserted-node-is-traversed.txt, Tests/LibWeb/Text/expected/HTML/iframe-successfully-loads-in-shadow-root.txt, Tests/LibWeb/Text/input/DOM/shadow-root-boundary-of-inserted-node-is-traversed.html, Tests/LibWeb/Text/input/HTML/iframe-successfully-loads-in-shadow-root.html
Embedded Cloudflare Turnstile widgets stopped appearing because they have started inserting the widget iframe into a shadow tree. This PR fixes that!
LibWeb: Actually traverse the shadow root of the inclusive descendant
Previously, the inclusive descendant, which is the node that for_each_shadow_including_inclusive_descendant was called on, would not have it's shadow root traversed if it had one.
This is because the shadow root traversal was in the `for` loop, which begins with the node's first child. The fix here is to move the shadow root traversal outside of the loop, and check if the current node is an element instead.
----
LibWeb: Make iframe insertion steps check the shadow including root
The insertion steps for iframes were following an old version of the spec, where it was …
=> LibWeb: Make embedded Cloudflare Turnstile widgets appear again

Libraries/LibWeb/CSS/MediaQueryList.cpp, Libraries/LibWeb/CSS/MediaQueryList.h
A recently imported WPT test has a subtest that effectively does the following:
```js
const mql = window.matchMedia("");
mql.removeListener(null);
```
This should fix the all-red CI currently on master.
=> LibWeb: Guard MediaQueryList event listener removal against null 

Libraries/LibWeb/Painting/Command.h, Libraries/LibWeb/Painting/DisplayList.cpp, Tests/LibWeb/Ref/expected/clip-offscreen-ref.html, Tests/LibWeb/Ref/input/clip-offscreen.html
These operations should still apply even if they are off screen, because they affect painting of things outside of their bounding rectangles.
This commit makes us always apply these, regardless of if they are in the visible region. However, if they are outside that region, we replace them with simple clip-rect commands, which have the same effect (not painting anything) but are cheaper than computing a full mask bitmap.
Fixes #2271
=> LibWeb/Painting: Apply clip and mask operations that are off-screen

Libraries/LibWeb/Streams/AbstractOperations.cpp, Tests/LibWeb/Text/expected/wpt-import/streams/writable-streams/bad-strategies.any.txt, Tests/LibWeb/Text/input/wpt-import/streams/writable-streams/bad-strategies.any.html, Tests/LibWeb/Text/input/wpt-import/streams/writable-streams/bad-strategies.any.js
This unfortunately caused a regression for the included WPT test. Instead of reordering the spec step, fall back to the default size strategy of 1.
=> LibWeb: Use alternative workaround for null strategy algorithm on abort

Libraries/LibWebView/ViewImplementation.cpp, Libraries/LibWebView/ViewImplementation.h, Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp, Services/WebContent/ConnectionFromClient.cpp, Services/WebContent/ConnectionFromClient.h, Services/WebContent/WebContentServer.ipc, UI/AppKit/Interface/LadybirdWebView.mm, UI/AppKit/Interface/LadybirdWebViewBridge.cpp, UI/AppKit/Interface/LadybirdWebViewBridge.h, UI/Headless/HeadlessWebView.cpp, UI/Qt/WebContentView.cpp
After a crash, we need to inform the new WebContent process of the current system visibility state.
I think at this point, we can move most of the work that all `initialize_client` implementations do to LibWebView, but that should be a separate refactor.
=> UI: Send the current system visibility state to new WebContent clients

Services/WebContent/ConnectionFromClient.cpp
Also include a header to say what shadow root each style sheet is in, so we can distinguish between them.
=> WebContent: Dump style sheets that are inside shadow roots

Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp, Libraries/LibWeb/CSS/Selector.cpp, Libraries/LibWeb/CSS/Selector.h, Libraries/LibWeb/CSS/SelectorEngine.cpp, Libraries/LibWeb/Dump.cpp, Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/css/serialize-invalid-forgiving-selectors.txt, Tests/LibWeb/Text/input/css/serialize-invalid-forgiving-selectors.html
Selectors like `:is(.valid, &!?!?!invalid)` need to keep the invalid part around, even though it will never match, for a couple of reasons:
- Serialization needs to include them
- For nesting, we care if a `&` appeared anywhere in the selector, even in an invalid part.
So this patch introduces an `Invalid` simple selector type, which simply holds its original ComponentValues. We search through these looking for `&`, and we dump them out directly when asked to serialize.
This passes a WPT ref-test we were previously failing. I'm surprised the serialization wasn't tested by WPT but maybe I just couldn't find the test. I've added a local one for it.
=> LibWeb/CSS: Keep invalid parts of `<forgiving-selector-list>`s around

UI/Headless/Application.cpp, UI/Headless/Application.h, UI/Headless/main.cpp
This change is required for https://github.com/LadybirdBrowser/ladybird/issues/2306
Otherwise, tests cannot be matched correctly
=> UI: Set headless-browser width and height

Libraries/LibWeb/CSS/StyleValues/CSSColor.cpp, Libraries/LibWeb/CSS/StyleValues/CSSColor.h, Libraries/LibWeb/CSS/StyleValues/CSSColorValue.h, Tests/LibWeb/Ref/expected/wpt-import/css/css-color/greensquare-090-ref.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/predefined-001.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/predefined-002.html
It makes the following WPT tests pass:
- css/css-color/predefined-001.html
- css/css-color/xyz-003.html
- css/css-color/xyz-d50-003.html
- css/css-color/xyz-d50-004.html
- css/css-color/xyz-d65-003.html
Also we now render the reference of color-mix-currentcolor-nested-for- color-property.html properly. Which means that it's now different from the actual test, that is still rendered incorrectly. In other word, the false positive for this test is now turned into a true negative.
---
This was a silly mistake on my end and percentages values are not
covered by device-independent color space, so I had to add support for
srgb to run a WPT test that made me realize the mistake.
This makes the following test pass:
- css/css-color/predefined-002.html
=> LibWeb/CSS: Add support for the `srgb` color space in `color()`

Libraries/LibWebView/Application.cpp, Libraries/LibWebView/Application.h, Libraries/LibWebView/HelperProcess.cpp, Libraries/LibWebView/HelperProcess.h, Libraries/LibWebView/ViewImplementation.cpp, Libraries/LibWebView/ViewImplementation.h, Libraries/LibWebView/WebContentClient.cpp, UI/AppKit/Application/Application.h, UI/AppKit/Application/Application.mm, UI/AppKit/Interface/LadybirdWebView.mm, UI/AppKit/Interface/LadybirdWebViewBridge.cpp, UI/AppKit/Interface/LadybirdWebViewBridge.h, UI/AppKit/main.mm, UI/Headless/Application.cpp, UI/Headless/Application.h, UI/Headless/HeadlessWebView.cpp, UI/Headless/HeadlessWebView.h, UI/Qt/Application.cpp, UI/Qt/Application.h, UI/Qt/WebContentView.cpp, UI/Qt/main.cpp
Now that these steps can all be handled within LibWebView, there's no need to have every UI manually implement them.
=> LibWebView+UI: Move common process launching / WebView init to LibWebView

Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Range.cpp, Libraries/LibWeb/HTML/FormAssociatedElement.cpp, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp, Libraries/LibWeb/Painting/Paintable.h, Libraries/LibWeb/Painting/PaintableFragment.cpp, Libraries/LibWeb/Painting/ViewportPaintable.cpp, Libraries/LibWeb/Painting/ViewportPaintable.h
Fixes a bug when text selection disappears after relayout.
With this change Slate.js becomes way more usable:
https://github.com/user-attachments/assets/3a91826b-5475-4e75-8b73-9a6bf0042667
=> LibWeb: Recompute selection state in Document::update_layout()

Libraries/LibWeb/CSS/CSSStyleRule.cpp, Libraries/LibWeb/CSS/Parser/Parser.h, Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp, Libraries/LibWeb/CSS/PseudoClasses.json, Libraries/LibWeb/CSS/Selector.cpp, Libraries/LibWeb/CSS/Selector.h, Libraries/LibWeb/Dump.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoClass.cpp, Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/css/invalid-selector-in-has.txt, Tests/LibWeb/Text/expected/wpt-import/css/selectors/invalidation/has-with-pseudo-class.txt, Tests/LibWeb/Text/input/css/invalid-selector-in-has.html
Fixes #2124.
A few `:has()`-related fixes:
- Make it take a non-forgiving `<relative-selector-list>`
- Prevent `:has( :has() )`
- Prevent `:has( ::pseudo-element )`
Theoretically some pseudo-elements are allowed inside `:has()`, but none are yet defined in any spec that I could find. I've left a `is_has_allowed_pseudo_element()` function that we can add exceptions to in the future.
=> LibWeb/CSS: Disallow `:has()` and pseudo-elements inside `:has()`

Libraries/LibWeb/Layout/TextNode.cpp, Tests/LibWeb/Layout/expected/unicode-password-input.txt, Tests/LibWeb/Layout/input/unicode-password-input.html
This means that an `<input type=password>` will show the correct number of *s in it when non-ASCII characters are entered.
We also don't need to perform text-transform on these as that doesn't affect the output length, so I've moved it earlier.
(The text is supposedly "Well, hello friends!" in Japanese, but I'm having to trust Kagi Translate on that.)
=> LibWeb: Calculate hidden password text using code-point count

Libraries/LibWeb/HTML/HTMLCanvasElement.cpp, Libraries/LibWeb/HTML/HTMLCanvasElement.h, Libraries/LibWeb/HTML/HTMLCanvasElement.idl, Libraries/LibWeb/WebDriver/Screenshot.cpp
Fix the function signatures of Canvas.toDataURL() and Canvas.toBlob() and make both functions accept non-numbers as the quality parameter, in which case it will just use the default quality instead of raising an exception.
This makes toDataURL.arguments.1.html, toDataURL.arguments.2.html and toDataURL.jpeg.quality.notnumber.html in
wpt/html/semantics/embedded-content/the-canvas-element pass :^)
=> LibWeb: Fix Canvas.toDataURL and Canvas.toBlob signatures

Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp, Libraries/LibWeb/Crypto/SubtleCrypto.cpp
There seems to be a bit of confusion in the spec about who is setting the `extractable` property for keys; sometimes `SubtleCrypto` does so, other times the specific algorithm implementations have a step for this. Unfortunately for `SubtleCrypto.deriveKey()`, no one takes the responsibility for this property.
Fixes ~4000 WPT subtests in `WebCryptoAPI`.
=> LibWeb: Set `extractable` key property in `SubtleCrypto.deriveKey()`

Meta/WPT.sh
This change removes the `--headless` option, which is now the default behavior and adds the `--show-window` option to force tests to run in a visible browser window.
=> Meta: Use `headless-browser` by default when running tests with `WPT.sh`

Libraries/LibCore/MimeData.cpp
Fixes a bug when https://wpt.live/css/CSS2/positioning/abspos-001.xht saved as file fails because we incorrectly recognized its MIME type as HTML, leading to incorrect self-closing tag handling and thus incorrect rendering.
=> LibCore: Recognize .xht as XHTML in MIME parser for file names

Libraries/LibJS/SourceTextModule.cpp, Libraries/LibJS/Tests/builtins/ShadowRealm/ShadowRealm.prototype.importValue.js, Libraries/LibJS/Tests/builtins/ShadowRealm/async-module.mjs
Previously it was only pushing the module context for the call to capture the module execution context. This is incorrect, as the capture occurs upon function construction. This resulted in it capturing the execution context that execute_module was called from, instead of the newly created module_context.
https://github.com/LadybirdBrowser/ladybird/blob/f87041bf3a8c76dce547dbd1f64d32b119f5468c/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp#L92
This can be demonstrated with the following setup: index.html:
```html
<script>
var foo = 1;
</script>
<script type="module">
import {test} from "./scriptA.mjs";
</script>
```
scriptA.mjs:
```js
function foo() {
return {a: "b"};
}
export let test = await foo();
```
Before this fix, this would throw:
```
[TypeError] 1 is not a function …
```
=> LibJS: Perform TLA async function construction in the module context

Libraries/LibWeb/CSS/StyleValues/CSSColor.cpp, Libraries/LibWeb/CSS/StyleValues/CSSColor.h, Libraries/LibWeb/CSS/StyleValues/CSSColorValue.h, Tests/LibWeb/Ref/expected/wpt-import/css/css-color/blacksquare-ref.html, Tests/LibWeb/Ref/expected/wpt-import/css/css-color/srgb-linear-003-ref.html, Tests/LibWeb/Ref/expected/wpt-import/css/css-color/srgb-linear-004-ref.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/srgb-linear-001.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/srgb-linear-002.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/srgb-linear-003.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/srgb-linear-004.html, Tests/LibWeb/TestConfig.ini
That makes us pass the following WPT tests:
- css/css-color/srgb-linear-001.html
- css/css-color/srgb-linear-002.html
- css/css-color/srgb-linear-003.html
=> LibWeb/CSS: Add support for the `srgb-linear` color space in `color()`

Libraries/LibWeb/HTML/EventLoop/Task.h, Libraries/LibWeb/WebSockets/WebSocket.cpp
The WebSocket spec tells us to queue tasks instead of firing events synchronously at WebSockets, so this commit does exactly that.
The way we've implemented web sockets means that the work is spread across multiple libraries and even processes, which is why it doesn't look like the spec verbatim.
=> LibWeb: Add WebSocket task source

Libraries/LibWeb/HTML/BrowsingContext.cpp, Libraries/LibWeb/HTML/BrowsingContext.h
In #1537, determine_the_origin() changed to take
`Optional<URL::URL> const&` as first parameter, but it's passed `Web::Fetch::Infrastructure::Response::url()`, which returns `Optional<URL::URL const&>`. Ladybird does not have SerenityOS/serenity#22870 (yet?), so this mismatch silently creates a copy.
Change determine_the_origin() to take `Optional<URL::URL const&>` instead. No behavior change, saves a copy, and is probably what was originally intended.
=> LibWeb: Don't copy url when calling determine_the_origin() in Navigable

Libraries/LibWeb/Selection/Selection.cpp
This matches the behavior of all major engines, and is covered by hundreds of subtests in WPT.
Spec PR: https://github.com/w3c/selection-api/pull/342
=> LibWeb: Make Selection APIs throw on DocumentType node inputs

Libraries/LibWeb/DOM/Node.cpp, Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_labelledby.txt, Tests/LibWeb/Text/input/wpt-import/accname/name/comp_labelledby.html
This change ensures that:
- if an element for which an accessible name otherwise wouldn’t be computed is referenced in an `aria-labelledby` value, the accessible name for the element will be computed as expected.
- if an element has both an `aria-label` value and also an `aria-labelledby` value, the text from the `aria-label` value gets included in the computation of the element’s accessible name.
Otherwise, without this change, some elements with `aria-labelledby` values will unexpectedly end up without accessible names, and some elements with `aria-label` values will unexpectedly not have that `aria-label` value included in the element’s accessible name.
This change gets us passing all subtests from the `comp_labelledby.html` test at …
=> LibWeb: Fix accname computation for all aria-labelledby cases

Libraries/LibWeb/Streams/WritableStream.cpp, Libraries/LibWeb/Streams/WritableStream.h, Libraries/LibWeb/Streams/WritableStreamDefaultWriter.cpp, Libraries/LibWeb/Streams/WritableStreamDefaultWriter.h, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/wpt-import/streams/readable-byte-streams/read-min.any.txt
We were previously throwing an exception if the generated code was
throwing an exception before it hit the implementation of the interface.
Instead, we are meant to catch any exception, and wrap that in a
rejected promise.
For example, this was impacting the fixed test in this commit as an
exception was being thrown when invoking WebIDL::convert_to_int<T>
as the given number was out of range, and the [EnforceRange]
extended attribute decorates that attribute.
This same type of case is seen for a few tests in WPT.
=> LibWeb: Always return a rejected Promise for functions which throw

Libraries/LibRegex/RegexOptimizer.cpp, Tests/LibRegex/Regex.cpp
fe46b2c1411 added the reset-temp-inverse flag, but set it up so all tempinverse ops were negated at the start of the next op; this commit makes it so these flags actually persist for one op and not zero.
Fixes #2296.
=> LibRegex: Don't immediately ignore TempInverse in optimizer

Libraries/LibWeb/HTML/Navigable.cpp
I noticed this missing check when trying to debug an unrelated issue. I don't know what it could fix, but this seems like an oversight.
=> LibWeb: Fix missing auxiliary logic for cross document navigation

Libraries/LibRegex/RegexOptimizer.cpp, Tests/LibRegex/Regex.cpp
=> LibRegex: Avoid generating ForkJumps when jumping to the next alt block

Libraries/LibWeb/Loader/GeneratedPagesLoader.cpp
The result of three hours of trying to figure out why going to `data:text/html;<button style="position: absolute">Hello!</button>` loads both the error document and the real document from the malformed data URL into the same page.
(It is malformed because it has a semicolon, not a comma)
=> LibWeb: Properly escape URL on error page

Libraries/LibGfx/Color.cpp, Tests/LibGfx/TestColor.cpp, Tests/LibWeb/TestConfig.ini
TL;DR: There are two available sets of coefficients for the conversion matrices from XYZ to sRGB. We switched from one set to the other, which is what the WPT tests are expecting.
All RGB color spaces, like display-p3 or rec2020, are defined by their three color chromacities and a white point. This is also the case for the video color space Rec. 709, from which the sRGB color space is derived. The sRGB specification is however a bit different.
In 1996, when formalizing the sRGB spec the authors published a draft that is still available here [1]. In this document, they also provide the matrix to convert from the XYZ color space to sRGB. This matrix can be verified quite easily by using the usual math equations. But hold on, here come the plot twist: at the time of publication, the spec …
=> LibGfx: Adjust matrices for XYZ -> sRGB conversions

Libraries/LibWeb/HTML/Focus.cpp, Libraries/LibWeb/Page/DragAndDropEventHandler.cpp, Libraries/LibWeb/UIEvents/CompositionEvent.cpp, Libraries/LibWeb/UIEvents/CompositionEvent.h, Libraries/LibWeb/UIEvents/CompositionEvent.idl, Libraries/LibWeb/UIEvents/KeyboardEvent.cpp, Libraries/LibWeb/UIEvents/KeyboardEvent.h, Libraries/LibWeb/UIEvents/KeyboardEvent.idl, Libraries/LibWeb/UIEvents/MouseEvent.cpp, Libraries/LibWeb/UIEvents/MouseEvent.h, Libraries/LibWeb/UIEvents/MouseEvent.idl, Libraries/LibWeb/UIEvents/TextEvent.cpp, Libraries/LibWeb/UIEvents/TextEvent.h, Libraries/LibWeb/UIEvents/TextEvent.idl, Libraries/LibWeb/UIEvents/UIEvent.cpp, Libraries/LibWeb/UIEvents/UIEvent.h, Libraries/LibWeb/UIEvents/UIEvent.idl, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/wpt-import/dom/events/Event-init-while-dispatching.txt, Tests/LibWeb/Text/expected/wpt-import/dom/events/Event-subclasses-constructors.txt
I believe this is an error in the UI Events spec, and it should be updated to match the HTML spec (which uses WindowProxy everywhere).
This fixes a bunch of issues already covered by existing WPT tests.
Spec bug: https://github.com/w3c/uievents/issues/388
Note that WebKit has been using WindowProxy instead of Window in UI Events IDL since 2018:
https://github.com/WebKit/WebKit/commit/816158b4aa33e65f8ffa931ad17453883f91818a
=> LibWeb: Use WindowProxy instead of Window in UI Events IDL

Utilities/js.cpp
This avoids a crash in the fully static distribution build, due to static init order fiasco.
"Temporary" workaround for https://github.com/LadybirdBrowser/ladybird/issues/2412
=> js: Don't destroy the JS VM on shutdown

Libraries/LibWeb/HTML/HTMLInputElement.cpp, Tests/LibWeb/Text/input/checkbox-focus-lost-no-change-event.html
Toggling the checkbox is committing a specific value so the change event should not be re-fired when the checkbox looses focus.
I *think* this should also apply to radio buttons but I haven't checked and also never used one, so I'm not including that in this PR for now.
A specific page that is fixed by this is the very bottom 'Developer Options' checkbox at https://battle.crossuniverse.net/settings/index.html which currently incorrectly hides the options it revealed when losing focus.
=> LibWeb: Prevent checkboxes from firing change events when losing focus

Libraries/LibJS/Bytecode/Interpreter.cpp
For getting I didn't need to change `fast_typed_array_get_element` because constructing `Value` with a double already handles the case where it is `nan`, which the normal `typed_array_get_element` seems to do redundantly. 
For setting I'm only handling the case where the value is also a double and if its not I fallback to the normal method.
=> LibJS: Add fast paths for get and set on float typed arrays

Libraries/LibWeb/Bindings/MainThreadVM.cpp, Libraries/LibWeb/CMakeLists.txt, Libraries/LibWeb/MediaSourceExtensions/EventNames.cpp, Libraries/LibWeb/MediaSourceExtensions/EventNames.h, Libraries/LibWeb/MediaSourceExtensions/ManagedMediaSource.cpp, Libraries/LibWeb/MediaSourceExtensions/ManagedMediaSource.h, Libraries/LibWeb/MediaSourceExtensions/ManagedMediaSource.idl, Libraries/LibWeb/MediaSourceExtensions/ManagedSourceBuffer.cpp, Libraries/LibWeb/MediaSourceExtensions/ManagedSourceBuffer.h, Libraries/LibWeb/MediaSourceExtensions/ManagedSourceBuffer.idl, Libraries/LibWeb/MediaSourceExtensions/MediaSource.cpp, Libraries/LibWeb/MediaSourceExtensions/MediaSource.h, Libraries/LibWeb/MediaSourceExtensions/MediaSource.idl, Libraries/LibWeb/MediaSourceExtensions/SourceBuffer.cpp, Libraries/LibWeb/MediaSourceExtensions/SourceBuffer.h, Libraries/LibWeb/MediaSourceExtensions/SourceBuffer.idl, Libraries/LibWeb/MediaSourceExtensions/SourceBufferList.cpp, Libraries/LibWeb/MediaSourceExtensions/SourceBufferList.h, Libraries/LibWeb/MediaSourceExtensions/SourceBufferList.idl
Continuing the boilerplate for these interfaces.
=> LibWeb: Add MediaSourceExtensions events

Libraries/LibGfx/CMakeLists.txt, Libraries/LibGfx/ImmutableBitmap.cpp, Libraries/LibGfx/PaintingSurface.cpp, Libraries/LibGfx/SkiaUtils.h
My 100,000th attempt to unify this. After countless tries, I’ve finally decided to copypaste it to prevent having two conflicting implementations.
=> LibGfx: Sync to_skia_color_type

Libraries/LibWeb/Painting/Paintable.cpp, Libraries/LibWeb/Painting/Paintable.h, Libraries/LibWeb/Painting/PaintableBox.cpp, Libraries/LibWeb/Painting/PaintableBox.h, Libraries/LibWeb/Painting/StackingContext.cpp, Libraries/LibWeb/Painting/StackingContext.h, Libraries/LibWeb/Painting/ViewportPaintable.cpp
For a while we used the wider Paintable type for stacking context, because it was allowed to be created by InlinePaintable and PaintableBox. Now, when InlinePaintable type is gone, we can use more specific PaintableBox type for a stacking context.
=> LibWeb: Allow stacking context to only be created by PaintableBox

Libraries/LibWeb/DOM/EventDispatcher.cpp, Libraries/LibWeb/DOM/EventTarget.cpp, Libraries/LibWeb/DOM/EventTarget.h
https://github.com/whatwg/dom/issues/1323 was fixed, and the solution ended up slightly different from what we had, so let's follow the spec.
=> LibWeb: Update handling of "once" event listeners now that spec is fixed

AK/NumberFormat.cpp, AK/NumberFormat.h, Libraries/LibJS/Console.cpp, Libraries/LibJS/Console.h, Libraries/LibJS/Runtime/Date.cpp, Libraries/LibJS/Runtime/Date.h, Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp, Libraries/LibJS/Runtime/Intl/DurationFormat.cpp, Libraries/LibJS/Runtime/Intl/DurationFormat.h, Libraries/LibJS/Runtime/Intl/Intl.cpp, Libraries/LibJS/Tests/builtins/Function/Function.prototype.toString.js, Libraries/LibJS/Tests/test-common.js
These commits are to prepare us to get caught back up with the Temporal spec. My plan is to basically remove our current Temporal implementation and begin anew. I've tried a few times to make updates in place, but everything in Temporal is so intertwined that I've become convinced that is a non-starter.
So the commits here fall into one of two categories:
1. Stop using Temporal facilities that have been removed (e.g. parsing UTC offset strings)
2. Stop using Temporal facilities where we can achieve the same behavior without Temporal (e.g. when we only need millisecond resolution, and not nanoseconds from Temporal).
No test262 diff here.
=> LibJS: Some prepatory commits to begin anew with Temporal

Libraries/LibCompress/Zlib.cpp, Libraries/LibCompress/Zlib.h, Libraries/LibWeb/Compression/DecompressionStream.cpp, Tests/LibCompress/TestZlib.cpp, Tests/LibWeb/Text/expected/Compression/DecompressionStream.txt, Tests/LibWeb/Text/input/Compression/DecompressionStream.html
Instead of checking the header in `ZlibDecompressor::create()`, we now check it in `read_some()` when it is called for the first time. This resolves a `FIXME` in the [new DecompressionStream implementation](https://github.com/LadybirdBrowser/ladybird/blob/ed80e929e5dd97e576a549e1429ddcfcb16eed01/Libraries/LibWeb/Compression/DecompressionStream.cpp#L35).
=> LibCompress: Don't assume zlib header is available right away

Libraries/LibWeb/Painting/SVGSVGPaintable.cpp, Tests/LibWeb/Ref/input/svg-text-crash.html
This makes it so that ``<foreignObject>``s no longer crash the SVG renderer.
This used to crash but now doesn't:
```html
<svg>
<foreignObject width="160" height="160">
<span>foo</span>
</foreignObject>
</svg>
```
A page that is fixed by this is https://battle.crossuniverse.net/game/index.html
This just skips rendering TextPaintables inside of SVGs.
=> LibWeb: Fix crash from text inside SVG

Libraries/LibGfx/Bitmap.cpp, Libraries/LibGfx/Bitmap.h
We don't use them anyway, and it doesn't feel right to have file loading code inside a Bitmap
=> LibGfx: Remove unused Bitmap loaders

AK/LexicalPath.cpp, AK/LexicalPath.h, AK/LexicalPathWindows.cpp, Libraries/LibCore/SystemWindows.cpp, Libraries/LibFileSystem/CMakeLists.txt, Libraries/LibFileSystem/FileSystem.cpp, Libraries/LibFileSystem/FileSystem.h
This PR requires #1918.
<s>This PR is ready for review, but must be rebased before merging. First 3 commits belong to #1918.</s> Update: rebased.
Ported only functions that are actually used. Note: TempFile is not used anywhere.
=> LibFileSystem: Port to Windows

AK/LexicalPath.cpp, AK/LexicalPath.h, AK/LexicalPathWindows.cpp, Libraries/LibCore/AnonymousBufferWindows.cpp, Libraries/LibCore/ConfigFile.cpp, Libraries/LibCore/Directory.cpp, Libraries/LibCore/Directory.h, Libraries/LibCore/SystemWindows.cpp
This PR requires #1918.
<s>This PR is ready for review, but must be rebased before merging. First 3 commits belong to #1918.</s> Update: rebased.
NOTE: The only methods of Directory that are used are create (static), is_valid_directory (static), chown and path, also adopt_fd and is_valid_directory are used internally.
The most used method is create, and it is always called with Directory::CreateDirectories::Yes.
Directory::is_valid_directory is called externally only from Web::ResourceLoader::load.
Directory::chown is called only from SessionManagement::create_session_temporary_directory_if_needed.
Directory::path is called only from ConfigFile::open_for_lib and other ConfigFile methods (indirectly through Formatter\<Directory>::format).
Among these, only chown uses m_directory_fd. As …
=> LibCore: Port Directory to Windows

Libraries/LibWeb/DOM/Node.cpp, Tests/LibWeb/Text/expected/DOM/CDATASection-cloneNode.txt, Tests/LibWeb/Text/input/DOM/CDATASection-cloneNode.html
We were cloning these as plain Text nodes, but the clone must also be a CDATASection node.
=> LibWeb: Clone CDATASection nodes with the correct node type

Libraries/LibCompress/Deflate.cpp, Libraries/LibCompress/Gzip.cpp
This change aims to improve the speed of incremental builds in the future.
=> LibCompress: Clean up #include directives

Libraries/LibFileSystem/FileSystem.cpp, Libraries/LibFileSystem/FileSystem.h
This change aims to improve the speed of incremental builds in the future.
=> LibFileSystem: Clean up #include directives

Libraries/LibGfx/Font/Font.h, Libraries/LibGfx/Font/ScaledFont.h, Libraries/LibGfx/Font/Typeface.h, Libraries/LibGfx/Font/TypefaceSkia.cpp, Libraries/LibGfx/Font/TypefaceSkia.h, Libraries/LibWeb/CSS/ParsedFontFace.h, Libraries/LibWeb/CSS/StyleComputer.cpp, Libraries/LibWeb/CSS/StyleComputer.h
`StyleComputer::font_matching_algorithm` was creating a copy of a
`FlyString` every time a `MatchingFontCandidate` was constructed or
copied, causing millions of unnecessairy reference updates when a
lot of fonts are loaded.
While a more permanent solution would be to not load so many unused
fonts, let's do the right thing and remove the unnecessairy copies of
`FlyString`.
=> LibWeb: Compare font keys by reference 

Libraries/LibWeb/DOM/Document.h, Tests/LibWeb/Text/expected/HTML/document-readyState-is-initially-complete.txt, Tests/LibWeb/Text/input/HTML/Window-postMessage.html, Tests/LibWeb/Text/input/HTML/document-readyState-is-initially-complete.html
This is required by mini Cloudflare invisible challenges, as it will only run if the readyState is not "loading". If it is "loading", then it waits for readystatechange to check that it's not "loading" anymore.
Initial about:blank iframes do not go through the full navigation and thus don't go through HTMLParser::the_end, which sets the ready state to something other than "loading". Therefore, the challenge would never run, as readyState would never change.
Seen on https://discord.com/login
=> LibWeb: Make default document readiness be "complete"

Libraries/LibWeb/Bindings/MainThreadVM.cpp, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/EventTarget.cpp, Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp, Libraries/LibWeb/HTML/HTMLDialogElement.cpp, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/ShadowRealmGlobalScope.cpp, Libraries/LibWeb/HTML/UniversalGlobalScope.cpp, Libraries/LibWeb/HTML/UniversalGlobalScope.h, Libraries/LibWeb/HTML/Window.cpp, Libraries/LibWeb/HTML/Window.h, Libraries/LibWeb/HTML/WorkerGlobalScope.cpp, Libraries/LibWeb/ResizeObserver/ResizeObserver.cpp, Libraries/LibWeb/Streams/AbstractOperations.cpp, Libraries/LibWeb/Streams/ByteLengthQueuingStrategy.cpp, Libraries/LibWeb/Streams/CountQueuingStrategy.cpp, Libraries/LibWeb/WebIDL/AbstractOperations.cpp, Libraries/LibWeb/WebIDL/CallbackType.cpp, Libraries/LibWeb/WebIDL/CallbackType.h, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/Streams/QueuingStrategy-same-instance.txt, Tests/LibWeb/Text/input/Streams/QueuingStrategy-same-instance.html
This fixes a crash which was being detected as a timeout for the following WPT test: https://wpt.live/streams/queuing-strategies.any.worker.html
Since worker test cases have been known to be flakey in CI, I instead wrote a test for this using a ShadowRealm, which involved tweaks to IDL callback context taking a realm instead of settings object.
=> LibWeb: Allow using queuing strategies on globals other than Window, improve ShadowRealm support

Documentation/README.md
`Browser/Patterns.md` was moved to `LibWebPatterns.md`, this PR updates link of "LibWeb Code Style & Patterns" to point to new url.
=> Documentation: fix broken link in README

Libraries/LibWeb/Page/EventHandler.cpp, Tests/LibWeb/Text/expected/CSSOMView/mouse-event-x-y-values.txt, Tests/LibWeb/Text/input/CSSOMView/mouse-event-x-y-values.html
The clientX and clientY values are, as per the spec, the offset from the viewport.
This makes them actually be that and also fixes up the calculations for offsetX, offsetY, pageX and pageY.
I assume all of these got messed up in some sort of refactor in the past.
The spec comment from the now-removed ``compute_mouse_event_client_offset()`` function sadly has no convenient place to be anymore so, for now, it is just gone as well.
Personally, I think it'd make sense to refactor a lot of this file so that not every mouse event repeats a large chunk of (almost) identical code. That way there'd be a nice place to put the comment without repeating it all over the file.
But that is out of the scope of this PR.
Also: I know, offsetX and Y are not fully fixed yet, they still don't ignore the …
=> LibWeb: Fix MouseEvent position values

Libraries/LibWeb/Page/EventHandler.cpp, Libraries/LibWeb/Painting/Paintable.h, Libraries/LibWeb/Painting/TextPaintable.cpp, Libraries/LibWeb/Painting/TextPaintable.h, Tests/LibWeb/Text/expected/UIEvents/click-event-on-input-control-associated-with-label-element.txt, Tests/LibWeb/Text/input/UIEvents/click-event-on-input-control-associated-with-label-element.html
For example, in the following HTML:
```html
<label>
<input type="radio" name="fruit" value="apple" id="radio1">
<span class="box"></span>
</label>
```
When any descendant of a <label> element is clicked, a "click" event must be dispatched on the <input> element nested within the <label>, in addition to the "click" event dispatched on the clicked descendant.
Previously, this behavior was implemented only for text node descendants by "overriding" the mouse event target using `mouse_event_target()` in the TextPaintable. This approach was incorrect because it was limited to text nodes, whereas the behavior should apply to any box. Moreover, the "click" event for the input control must be dispatched *in addition* to the event on the clicked element, rather than redirecting it.
Combined with …
=> LibWeb: Dispatch "click" event on input control associated with <label>

Libraries/LibWeb/DOM/Document.cpp
An inopportune garbage collection may cause collected `ResizeObserver`s to unregister themselves from `m_resize_observers` while we are iterating over it, resulting in a use-after-free.
Copy the vector to avoid this scenario.
Fixes #2011.
A better solution might be to queue `ResizeObserver` de-registrations, or to `swap_remove` unregistered `ResizeObserver`s in such a way that indexed iteration remains well-defined (assuming the order of `ResizeObserver` in `m_resize_observers` is irrelevant).
> **EDIT**: The order of resize observers _is_ relevant. It is possible to still keep well-defined indexed iteration _without_ `swap_remove` or memory allocations, though, with:
> ```c++
> GC::Ptr<ResizeObserver> observer;
> for (size_t i=0; i < m_resize_observers.size(); i += size_t(observer.ptr() …
```
=> LibWeb: Copy `m_resize_observers` before iterating

Libraries/LibWeb/WebIDL/AbstractOperations.cpp, Libraries/LibWeb/WebIDL/AbstractOperations.h, Libraries/LibWeb/XHR/XMLHttpRequest.idl, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/wpt-import/xhr/setrequestheader-bogus-name.txt, Tests/LibWeb/Text/expected/wpt-import/xhr/setrequestheader-bogus-value.txt, Tests/LibWeb/Text/input/wpt-import/xhr/setrequestheader-bogus-name.htm, Tests/LibWeb/Text/input/wpt-import/xhr/setrequestheader-bogus-value.htm, UI/Headless/Test.cpp
This PR implements the ByteString conversion specified here: https://webidl.spec.whatwg.org/#ref-for-idl-ByteString%E2%91%A7 and also updates `XMLHTTPRequest.setRequestHeader()` to use the correct argument type.
I've also updated `headless-browser` to accept test files ending in '.htm', which allows the relevant WPT test to be imported and run.
Fixes these WPT tests in `xhr/`:
* http://wpt.live/xhr/setrequestheader-bogus-name.htm
* http://wpt.live/xhr/setrequestheader-bogus-value.htm
Also likely fixes a few WPT tests in `fetch/`
=> IDLGenerators: Throw TypeError if IDL ByteString contains element > 255

Libraries/LibGfx/Color.h, Tests/LibGfx/TestColor.cpp
- Hue now wraps properly when negative or larger than 360
- The hsl to rgb conversion now closely mirrors the code example from the spec.
This fixes a number of WPT tests in
/css/css-color/parsing/color-computed-hsl.html
=> LibGfx: Reimplement from_hsla

Libraries/LibGfx/Path.h, Libraries/LibWeb/Painting/Command.h, Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp, Libraries/LibWeb/Painting/DisplayListRecorder.cpp, Libraries/LibWeb/Painting/DisplayListRecorder.h, Libraries/LibWeb/Painting/MediaPaintable.cpp, Libraries/LibWeb/Painting/SVGPathPaintable.cpp
The state is still ignored there, so no behavior change, but this should make it fairly easy to actually implement complete stroking support for SVGs.
=> LibWeb: Plumb svg stroking state to DisplayListPlayerSkia

Libraries/LibWeb/HTML/HTMLInputElement.cpp, Tests/LibWeb/Text/expected/checkbox-focus-lost-no-change-event.txt, Tests/LibWeb/Text/expected/radio-button-focus-lost-no-change-event.txt, Tests/LibWeb/Text/input/checkbox-focus-lost-no-change-event.html, Tests/LibWeb/Text/input/radio-button-focus-lost-no-change-event.html
I have checked since #2379 and radio buttons should indeed work this way also.
=> LibWeb: Stop radio buttons firing change events when losing focus

Libraries/LibGfx/Bitmap.h
This commit moves some of the actual code from the header file to the CPP file to reduce header size and improve encapsulation. Additionally, it ensures that the bpp is correctly returned for all supported image formats, which may help prevent potential runtime crashes in the future.
=> LibGfx: Do not return or store BPP

Libraries/LibWeb/Layout/FlexFormattingContext.cpp
It just went to the wrong algorithm.
=> LibWeb: Fix spec link in FlexFormattingContext

Libraries/LibWeb/DOM/Node.cpp, Tests/LibWeb/Text/expected/wpt-import/svg-aam/name/comp_host_language_label.txt, Tests/LibWeb/Text/input/wpt-import/svg-aam/name/comp_host_language_label.html
This change adds support for computing accessible names for SVG elements, per the https://w3c.github.io/svg-aam/#mapping_additional_nd spec requirements. Otherwise, without this change, accessible names for SVG elements don’t get exposed as expected.
This change gets us passing all the `comp_host_language_label.html` tests at https://wpt.fyi/results/svg-aam/name?product=ladybird
=> LibWeb: Support accessible-name computation for SVG elements

Libraries/LibWeb/CSS/Parser/Parser.cpp, Libraries/LibWeb/CSS/Parser/Parser.h, Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp, Libraries/LibWeb/IntersectionObserver/IntersectionObserver.h, Libraries/LibWeb/IntersectionObserver/IntersectionObserver.idl, Tests/LibWeb/Text/expected/wpt-import/intersection-observer/observer-attributes.txt, Tests/LibWeb/Text/expected/wpt-import/intersection-observer/observer-exceptions.txt, Tests/LibWeb/Text/input/wpt-import/intersection-observer/observer-attributes.html, Tests/LibWeb/Text/input/wpt-import/intersection-observer/observer-exceptions.html
This adds the missing IntersectionObserver attributes that we currently do not have.
Only the `rootMargin` is actually functional, since that was easy to do and a FIXME in the same file.
But the other properties now exist so they can be accessed from the right algorithms and from JS.
This also makes us pass some more WPT tests (how many?), two of which I have imported to verify the behavior.
Sadly, the tests for `rootMargin` functionality are very sensitive to floating point errors, so we don't pass those yet.
(but hey, Firefox and Chrome don't pass them either)
=> LibWeb: Implement more IntersectionObserver attributes

.github/workflows/ci.yml
This will prevent CI from running if:
- the only changes included are under the Documentation folder, or
- the only changes included are *.md files in the root
See:
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-excluding-paths
=> CI: Ignore changes to Documentation related files

Libraries/LibWeb/CSS/Supports.h
It didn't go to the right level of the spec. (anymore, probably)
=> LibWeb: Fix incorrect spec link for the @supports rule

Libraries/LibWeb/Painting/Command.h, Libraries/LibWeb/Painting/DisplayList.cpp, Libraries/LibWeb/Painting/DisplayList.h, Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp, Libraries/LibWeb/Painting/DisplayListPlayerSkia.h, Libraries/LibWeb/Painting/DisplayListRecorder.cpp, Libraries/LibWeb/Painting/DisplayListRecorder.h, Libraries/LibWeb/Painting/SVGSVGPaintable.cpp, Libraries/LibWeb/Painting/StackingContext.cpp
The code largely mirrors the one in StackingContext::paint() for applying CSS filters to a generic context, with some minor changes.
There's a weird compile issue where `matrix_with_scaled_translation()` is not being found by the compiler, even though StackingContext::paint() uses it with no issues. PaintableBox also has the relevant header file imported as well, so it is not like it is missing somewhere down in an inherited object either.
Compile log (with matrix_with_scaled_translation):
```
/usr/bin/ccache /usr/bin/c++ -DENABLE_COMPILETIME_FORMAT_CHECK -DHAVE_PULSEAUDIO=1 -DLibWeb_EXPORTS -DSK_CODEC_DECODES_BMP -DSK_CODEC_DECODES_GIF -DSK_CODEC_DECODES_ICO -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_RAW -DSK_CODEC_DECODES_WBMP -DSK_CODEC_DECODES_WEBP …
```
=> LibWeb: Apply CSS filters on SVGs

UI/Qt/main.cpp
Previously, we did a bit of guessing.
That approach was hacky and less reliable.
=> UI/Qt: Set dark theme as reported by Qt

Libraries/LibWeb/Painting/PaintableBox.cpp, Tests/LibWeb/Text/expected/hit_testing/css-transforms.txt, Tests/LibWeb/Text/input/hit_testing/css-transforms.html
Elements with transforms were tested on their pre-transformed
positions, causing incorrect hits.
Copy the position transformation done in `StackingContext::hit_test`
to ensure that hit tests are done on the _actual_ position.
Fixes #2530.
=> LibWeb: Transform PaintableBox::hit_test positions

Libraries/LibWeb/DOM/NamedNodeMap.cpp, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/attributes.txt, Tests/LibWeb/Text/input/wpt-import/dom/nodes/attributes.html, Tests/LibWeb/Text/input/wpt-import/dom/nodes/attributes.js, Tests/LibWeb/Text/input/wpt-import/dom/nodes/productions.js
Previously, we were doing a case insensitive comparison rather than converting tha attribute name to lower case then comparing.
Fixes 2 subtests in: http://wpt.live/dom/nodes/attributes.html
=> LibWeb: Use correct comparison logic in `NamedNodeMap::get_attribute()`

Libraries/LibWeb/Painting/SVGSVGPaintable.cpp, Tests/LibWeb/Ref/expected/svg-restore-after-filter.html, Tests/LibWeb/Ref/input/svg-restore-after-filter.html
This fixes a regression introduced by #2248.
=> LibWeb: Unapply CSS filters after applying them to SVG

Libraries/LibWeb/DOM/NamedNodeMap.cpp, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/attributes.txt
This fixes the [WPT node attribute tests](https://wpt.fyi/results/dom/nodes/attributes.html?label=master&product=ladybird). See the individual commits for more details.
=> LibWeb: Fix WPT node attribute tests

Libraries/LibWeb/Bindings/MainThreadVM.cpp, Tests/LibWeb/Text/expected/HTML/custom-elements-throw-in-constructor.txt, Tests/LibWeb/Text/expected/wpt-import/custom-elements/upgrading.txt, Tests/LibWeb/Text/input/HTML/custom-elements-throw-in-constructor.html, Tests/LibWeb/Text/input/wpt-import/custom-elements/resources/custom-elements-helpers.js, Tests/LibWeb/Text/input/wpt-import/custom-elements/upgrading.html
This fixes a WPT test and exposes a few more places that we aren't reporting exceptions from callback objects properly.
Seems we should probably remote HTML::report_exception entirely.
=> LibWeb: Report exceptions from custom element upgrades to global object

Libraries/LibRegex/RegexParser.cpp, Libraries/LibRegex/RegexParser.h, Tests/LibRegex/Regex.cpp
This restricts nested RegExp capture groups from having the same / conflicting names.
This requires removal of the recorded minimum length of the named capture group directly, so it now needs to be looked up indirectly via the group minimum lengths table.
Also tacks on a fix where group indices were being narrowed from `size_t` -> `int`.
=> LibRegex: Ensure nested capture groups have non-conflicting names

Libraries/LibWeb/Painting/SVGSVGPaintable.cpp, Libraries/LibWeb/Painting/SVGSVGPaintable.h, Libraries/LibWeb/Painting/StackingContext.cpp, Tests/LibWeb/Ref/expected/svg-with-css-transform.html, Tests/LibWeb/Ref/input/svg-with-css-transform.html
SVG elements used to not care about their CSS transforms.
Now they do.
I've just added a new test, chances are there's one in the WPT suite but I wouldn't quite know where to look.
This fixes a bug on https://battle.crossuniverse.net.
=> LibWeb: Make SVGs respect their CSS transforms

Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Libraries/LibWeb/Layout/BlockFormattingContext.h
Rather than accumulating margins into a vector, and then looping through them when resolving the margin, it's much simpler to just update two fields, and sum them when resolving.
=> LibWeb/Layout: Simplified margin collapsing.

Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp, Libraries/LibWeb/HTML/EventLoop/EventLoop.h
Instead of collecting all documents in a big vector and then filtering the vector (twice!) with remove_all_matching(), we now pass a filter callback to documents_in_this_event_loop_matching() and avoid all the extra shuffling work.
Saw this stuff hogging ~20% of CPU time when profiling a WebContent process in the middle of a WPT run.
=> LibWeb: Avoid expensive Vector filtering in event loop

Libraries/LibTLS/Socket.cpp
Prior to this commit LibTLS closed the connection but did not consider it terminated after receiving and acknowledging a CloseNotify from the server, which led to hangs in DoT (and possibly other users).
=> LibTLS: Change connection state to disconnected after server CloseNotify

Libraries/LibWeb/Bindings/MainThreadVM.cpp, Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Libraries/LibWeb/HTML/Scripting/Fetching.cpp, Libraries/LibWeb/HTML/Scripting/SyntheticRealmSettings.cpp, Libraries/LibWeb/HTML/Scripting/SyntheticRealmSettings.h, Tests/LibWeb/Text/data/external-module.mjs, Tests/LibWeb/Text/expected/HTML/ShadowRealm-importValue.txt, Tests/LibWeb/Text/input/HTML/ShadowRealm-importValue.html
Fixes two different crashes, and some minor catchup to spec changes in the open HTML spec PR.
=> LibWeb: Make ShadowRealm importValue work

Libraries/LibWeb/HTML/FormAssociatedElement.cpp
Before this change, skipping a word to the left in a non empty text input element would crash when near the end of the text as the offset + length of the substring would exceed the length of the string.
=> LibWeb: Fix crash when skipping to previous word with ctrl+left arrow

UI/Qt/main.cpp
The Qt style hints' color scheme can return ::Unknown, in which case we still need to fall back to our 'old' method of using the luma component of the background role color.
Related PR: #2529
=> UI/Qt: Fall back to luma dark mode detection for unknown color scheme

AK/Optional.h, Libraries/LibTest/Macros.h, Tests/AK/TestOptional.cpp
There was an existing check to ensure that `U` was an lvalue reference, but when this check fails, overload resolution will just move right on to the copy asignment operator, which will cause the temporary to be assigned anyway.
Disallowing `Optional<T&>`s to be created from temporaries entirely would be undesired, since existing code has valid reasons for creating `Optional<T&>`s from temporaries, such as for function call arguments.
This fix explicitly deletes the `Optional::operator=(U&&)` operator, so overload resolution stops.
=> AK: Fix "assignment from temporary" check of `Optional::operator=`

Libraries/LibWeb/DOM/Node.cpp, Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_host_language_label.txt, Tests/LibWeb/Text/input/wpt-import/accname/name/comp_host_language_label.html
This PR branch contains three commits:
- e85812a64fe018f300611197536fdfdc6a7b1255 LibWeb: Fix accessible-name computation for “encapsulation” cases
This change makes Ladybird correctly handle all “encapsulation” tests in the https://wpt.fyi/results/accname/name/comp_host_language_label.html set of tests in WPT.
Those all test the requirement that when computing the accessible name for a `<label>`-ed form control, then any content (text content or attribute values) from the control itself that would otherwise be included in the accessible-name computation for it ancestor `<label>` must instead be skipped and not included.
The HTML-AAM spec seems to try to achieve that result by expressing specific steps for each particular type of form control. But what all that …
=> Fix accessible-name computation for table, fieldset, image input elements, and for “encapsulation” cases

Libraries/LibWeb/CSS/Parser/Parser.cpp, Libraries/LibWeb/CSS/StyleComputer.cpp, Libraries/LibWeb/CSS/StyleValues/CSSColorValue.cpp, Libraries/LibWeb/CSS/StyleValues/CSSColorValue.h, Libraries/LibWeb/CSS/StyleValues/CSSRGB.cpp, Libraries/LibWeb/CSS/StyleValues/CSSRGB.h, Tests/LibWeb/Text/expected/HTML/background-shorthand.txt, Tests/LibWeb/Text/expected/css/PropertyOwningCSSStyleDeclaration-serialized-custom-properties.txt, Tests/LibWeb/Text/expected/css/keyframes-css-rules.txt, Tests/LibWeb/Text/expected/css/set-style-declaration-shorthand.txt, Tests/LibWeb/Text/expected/css/style-declaration-parent-rule.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-nesting/cssom.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-nesting/invalid-inner-rules.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-nesting/serialize-group-rules-with-decls.txt, Tests/LibWeb/Text/expected/wpt-import/domparsing/style_attribute_html.txt, Tests/LibWeb/Text/input/wpt-import/domparsing/style_attribute_html.html
When serializing an sRGB color value that originated from a named color, it should simply return the color name. This requires storing the color name (if it has one).
This fixes 2 WPT subtests of https://wpt.fyi/results/domparsing/style_attribute_html.html?label=master&product=ladybird.
This is the easiest way I could find to store the original color name, though there is also the option of storing an enum.
=> LibWeb: Store CSS color name in CSSRGB

Libraries/LibWeb/DOM/EventDispatcher.cpp
Two differences:
1. An extra step inserted to record timing info, which we don't yet implement.
2. The last step in the loop breaks instead of returning the value directly. (But this is functionally the same, as the following step does return that value.)
(Also removed the duplicated part of the comment in step 11 née 10.)
So, there's no actual change in behavior.
=> LibWeb/DOM: Update "inner invoke" to current spec

Libraries/LibWeb/HTML/HTMLInputElement.cpp, Tests/LibWeb/Text/expected/wpt-import/html/rendering/widgets/input-text-size.txt, Tests/LibWeb/Text/input/wpt-import/html/rendering/widgets/input-text-size.html
According to the HTML specification, the `size` attribute of an input element must be a valid non-negative integer greater than zero. If the value is invalid or set to `0`, the default size of `20` should be used.
This change fixes one issue identified in https://wpt.live/html/rendering/widgets/input-text-size.html
=> LibWeb/HTML: Use default input size (20) when value is 0

Libraries/LibWeb/HTML/HTMLModElement.idl, Libraries/LibWeb/HTML/HTMLQuoteElement.idl, Tests/LibWeb/Text/expected/usvstring-url-reflection.txt, Tests/LibWeb/Text/input/usvstring-url-reflection.html
Implements the cite attribute of `q` and `blockqoute` elements according to spec by returning a valid URL.
This makes the remaining cases in http://wpt.live/html/dom/reflection-text.html pass.
=> LibWeb/HTML: Implement cite attribute according to spec

Libraries/LibWeb/DOM/ElementFactory.cpp
This fixes the typo in `HTMLFieldSetElement` and adds valid local names for `<meta>`, `<ol>` and `<optgroup>`. An additional 20 subtests passes in WPT's `custom-elements/reactions/customized-builtins`.
=> LibWeb: Fix various local names for custom elements

Libraries/LibWeb/CSS/Screen.idl
Followup to: https://github.com/LadybirdBrowser/ladybird/pull/2586#issuecomment-2500686474
=> LibWeb: Update `Screen` IDL definition to not inherit from `EventTarget`

Libraries/LibWeb/HTML/HTMLVideoElement.idl, Tests/LibWeb/Text/expected/usvstring-url-reflection.txt, Tests/LibWeb/Text/input/usvstring-url-reflection.html
This fixes 40 subtests in http://wpt.live/html/dom/reflection-embedded.html
=> LibWeb: Use `[URL]` extended attribute for `HTMLVideoElement.poster`

Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp, Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.prototype.total.js
We were comparing the incorrect offset.
test262 diff:
```
Diff Tests:
+5 ✅    -5 ❌
Diff Tests:
test/intl402/Temporal/Duration/compare/relativeto-sub-minute-offset.js         ❌ -> ✅
test/intl402/Temporal/Duration/prototype/round/relativeto-sub-minute-offset.js ❌ -> ✅
test/intl402/Temporal/Duration/prototype/total/relativeto-sub-minute-offset.js ❌ -> ✅
test/intl402/Temporal/ZonedDateTime/from/zoneddatetime-sub-minute-offset.js    ❌ -> ✅
test/intl402/Temporal/ZonedDateTime/prototype/equals/sub-minute-offset.js      ❌ -> ✅
```
=> LibJS: Use correct epoch offset in InterpretISODateTimeOffset

Libraries/LibJS/Runtime/CommonPropertyNames.h, Libraries/LibJS/Runtime/DateConstructor.cpp, Libraries/LibJS/Runtime/DatePrototype.cpp, Libraries/LibJS/Runtime/DatePrototype.h, Libraries/LibJS/Runtime/Temporal/Now.cpp, Libraries/LibJS/Runtime/Temporal/Now.h, Libraries/LibJS/Tests/builtins/Date/Date.parse.js, Libraries/LibJS/Tests/builtins/Date/Date.prototype.toTemporalInstant.js
\+ a flyby fix to `Date.parse` so that we pass all `Date` test262 tests :)
test262 diff:
```
Diff Tests:
+9 ✅    -9 ❌
Diff Tests:
test/built-ins/Date/parse/time-value-maximum-range.js                      ❌ -> ✅
test/built-ins/Date/prototype/toTemporalInstant/length.js                  ❌ -> ✅
test/built-ins/Date/prototype/toTemporalInstant/name.js                    ❌ -> ✅
test/built-ins/Date/prototype/toTemporalInstant/not-a-constructor.js       ❌ -> ✅
test/built-ins/Date/prototype/toTemporalInstant/prop-desc.js               ❌ -> ✅
test/built-ins/Date/prototype/toTemporalInstant/this-value-invalid-date.js ❌ -> ✅
test/built-ins/Date/prototype/toTemporalInstant/this-value-non-date.js     ❌ -> ✅
test/built-ins/Date/prototype/toTemporalInstant/this-value-non-object.js   ❌ -> ✅ …
```
=> LibJS: Implement Date-related Temporal modifications

Libraries/LibWeb/HTML/AttributeNames.h, Libraries/LibWeb/HTML/HTMLImageElement.cpp, Libraries/LibWeb/HTML/HTMLImageElement.h, Libraries/LibWeb/HTML/HTMLImageElement.idl
This ensures the correct behavior when the value of the `decoding` attribute is changed with `setAttribute()`.
Fixes 36 subtests in: http://wpt.live/html/dom/reflection-embedded.html
=> LibWeb: Use [Reflect] to implement `HTMLImageElement.decoding`

Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/HTML/Parser/HTMLParser.cpp, Tests/LibWeb/Text/expected/wpt-import/html/semantics/scripting-1/the-script-element/execution-timing/149.txt, Tests/LibWeb/Text/expected/wpt-import/html/syntax/parsing/html5lib_scripted_webkit01.txt, Tests/LibWeb/Text/input/wpt-import/html/semantics/scripting-1/the-script-element/execution-timing/149.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/scripting-1/the-script-element/execution-timing/testlib/testlib.js
Fixes #2564, also fixes 13 WPT timeouts (the largest has been imported).
I've run `domparsing`, `dom`, `html/dom`, `html/syntax/parsing`, `html/semantics/scripting-1/the-script-element`, `html/browsers/browsing-the-web`, and `html/webappapis` to confirm that there aren't any regressions.
=> LibWeb: Don't end parsing after reaching the insertion point

Libraries/LibWeb/HTML/HTMLInputElement.idl, Tests/LibWeb/Text/expected/usvstring-url-reflection.txt, Tests/LibWeb/Text/input/usvstring-url-reflection.html
This fixes 40 subtests in:  http://wpt.live/html/dom/reflection-forms-weekmonth.html
=> LibWeb: Use `[URL]` extended attribute for `HTMLInputElement.src`

Libraries/LibWeb/HTML/HTMLMarqueeElement.cpp, Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/HTML/unsigned-long-reflection.txt, Tests/LibWeb/Text/input/HTML/unsigned-long-reflection.html
Setting an unsigned long attribute with IDL to a value outside the range 0 to 2147483647, the value should be set to 0.
Fixes 4 subtests in  http://wpt.live/html/dom/reflection-obsolete.html and 12 subtests in  http://wpt.live/html/dom/reflection-embedded.html
=> IDLGenerators: Set reflected unsigned long values according to spec

Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Adds the `<search>` element to the list of [Special](https://html.spec.whatwg.org/multipage/parsing.html#special) tags, since I didn't realize we had that list when I made the initial PR.
=> LibWeb: Add search element to list of Special tags

Libraries/LibWeb/XML/XMLDocumentBuilder.cpp, Tests/LibWeb/Text/expected/wpt-import/domparsing/XMLSerializer-serializeToString.txt, Tests/LibWeb/Text/input/wpt-import/domparsing/XMLSerializer-serializeToString.html
While the code that did this referred to the HTML spec, other browsers appear not to have this behavior when parsing XML, and it breaks a WPT subtest (at https://wpt.fyi/results/domparsing/XMLSerializer-serializeToString.html?label=master&product=ladybird).
This change does not appear to break any tests, and fixes 1 WPT subtest.
@alimpfard
=> LibWeb: Do not give the HTML namespace to elements when parsing XML

Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/Navigable.h, Libraries/LibWeb/HTML/TraversableNavigable.cpp
To check whether a NavigationParams is null, we have to check whether it's `Empty` or `NullWithError`. Instead, we can merge both of these possible variants into an optional `NullOrError`. If `NullOrError` has no value it's null, otherwise it contains the error message that is shown to the user when there's a navigation error.
=> LibWeb: Merge NavigationParams' `Empty` and `NullWithError` into `NullOrError`

Libraries/LibWeb/Layout/FormattingContext.cpp, Tests/LibWeb/Layout/expected/child-of-abspos-percentage-height.txt, Tests/LibWeb/Layout/input/child-of-abspos-percentage-height.html
This fixes an issue where the welcome screen wasn't showing up the first time you visit https://puter.com/ :^)
Before:
After:
=> LibWeb: Don't treat auto insets as definite for child of abspos element

Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp, Libraries/LibWeb/Crypto/CryptoAlgorithms.h, Libraries/LibWeb/Crypto/SubtleCrypto.cpp, Tests/LibWeb/Text/expected/wpt-import/WebCryptoAPI/derive_bits_keys/cfrg_curves_bits_curve448.https.any.txt, Tests/LibWeb/Text/expected/wpt-import/WebCryptoAPI/derive_bits_keys/ecdh_bits.https.any.txt, Tests/LibWeb/Text/expected/wpt-import/WebCryptoAPI/derive_bits_keys/ecdh_keys.https.any.txt
Following https://github.com/LadybirdBrowser/ladybird/pull/2598#discussion_r1859263798, I have investigated how we handle case-sensitiveness for WebCryptoAPI and made two adjustments:
- All case-insesitive matches have been removed where not stated by the spec
- Algorithm name matching has been made case-insensitive by correcting some existing code and making it closer to spec
Fixes 5 WPT tests and a typo :).
=> LibWeb: Refactor WebCryptoAPI case-sensitiveness + fix typo

Tests/LibWeb/TestConfig.ini
Consistently times out locally, but not on CI somehow.
=> Tests: Disable a worker test that's flaky on macOS

.github/workflows/lagom-template.yml
We seem to be brushing up against the 1500s limit (25 minutes) on both macOS and Linux+GCC workflows. As we keep importing more WPT tests, we will exasperate the issue.
=> CI: Increase the default ctest timeout to 1 hour

.github/workflows/lagom-template.yml
This reverts commit aeaa284be3881b2ea4b38b967bf4327738119a17.
This didn't actually help. It appears we actually just get stuck, so increasing the timeout to an hour just makes CI take longer.
=> Revert "CI: Increase the default ctest timeout to 1 hour"

Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLInputElement.h, Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp, Libraries/LibWeb/HTML/HTMLTextAreaElement.h, Tests/LibWeb/Text/expected/HTML/unsigned-long-reflection.txt, Tests/LibWeb/Text/input/HTML/unsigned-long-reflection.html
Attempting to set `HTMLInputElement.size` to 0 via IDL now throws an IndexSizeError DOMException. Attempting to set it to a value larger than 2147483647 results in it being set to the default value.
Fixes 3 subtests in: http://wpt.live/html/dom/reflection-forms-weekmonth.html
=> LibWeb: Limit `HTMLInputElement.size` to allowed values

Libraries/LibWeb/HTML/HTMLLinkElement.cpp, Libraries/LibWeb/HTML/HTMLLinkElement.h, Libraries/LibWeb/HTML/HTMLLinkElement.idl
Also ensure that all valid potential destinations are permitted.
This fixes 23 subtests in: http://wpt.live/html/dom/reflection-metadata.html
=> LibWeb: Use the [Reflect] attribute to implement `HTMLLinkElement.as`

Libraries/LibWeb/DOM/Element.cpp, Libraries/LibWeb/DOM/Element.h, Libraries/LibWeb/DOM/Node.cpp, Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_hidden_not_referenced.txt, Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_label.txt, Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_labelledby_hidden_nodes.txt, Tests/LibWeb/Text/input/wpt-import/accname/name/comp_hidden_not_referenced.html, Tests/LibWeb/Text/input/wpt-import/accname/name/comp_label.html, Tests/LibWeb/Text/input/wpt-import/accname/name/comp_labelledby_hidden_nodes.html
This change implements full support for the _“A. Hidden Not Referenced”_ step at https://w3c.github.io/accname/#step2A in the “Accessible Name and Description Computation” spec — including handling all hidden nodes that must be ignored, as well as handling hidden nodes that, for the purposes of accessible-name computation, must not be ignored (due to having `aria-labelledby`/`aria-describedby` references from other nodes).
Otherwise, without this change, not all cases of hidden nodes get ignored as expected, while cases of nodes that are hidden but that have `aria-labelledby`/`aria-describedby` references from other nodes get unexpectedly ignored.
For the tests at https://wpt.fyi/results/accname/name?product=ladybird, this change gets us passing:
- all 27 subtests in the …
=> LibWeb: Compute accessible names for hidden/hidden-but-referenced nodes

Libraries/LibWeb/CMakeLists.txt, Libraries/LibWeb/Forward.h, Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Libraries/LibWeb/Layout/FieldSetBox.cpp, Libraries/LibWeb/Layout/FieldSetBox.h, Libraries/LibWeb/Layout/TreeBuilder.cpp, Libraries/LibWeb/Painting/FieldSetPaintable.cpp, Libraries/LibWeb/Painting/FieldSetPaintable.h, Tests/LibWeb/Layout/expected/fieldset-with-rendered-legend.txt, Tests/LibWeb/Layout/input/fieldset-with-rendered-legend.html, Tests/LibWeb/Text/expected/wpt-import/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend.txt, Tests/LibWeb/Text/input/wpt-import/html/rendering/non-replaced-elements/the-fieldset-and-legend-elements/legend.html
This fixes the legend position on my website :^) https://kostyafarber.com/about
with change:
without change:
=> LibWeb: Layout the fieldset's rendered legend

Libraries/LibWeb/HTML/HTMLProgressElement.cpp, Libraries/LibWeb/HTML/HTMLProgressElement.h, Tests/LibWeb/Text/expected/HTML/HTMLProgressElement-set-attributes.txt
When attempting to set `HTMLProgressElement.max` to a value not greater than 0, we were previously setting the value to 1. We now retain the previous value.
This fixes 4 subtests in: http://wpt.live/html/dom/reflection-forms.html
=> LibWeb: Ignore negative values when setting `HTMLProgressElement.max`

Libraries/LibWeb/Layout/TableFormattingContext.cpp, Tests/LibWeb/Layout/expected/table/absolute-positioning-alignment.txt, Tests/LibWeb/Layout/expected/table/display-table-size.txt, Tests/LibWeb/Layout/expected/table/table-header-and-footer-groups.txt, Tests/LibWeb/Layout/input/table/display-table-size.html
Fixes #1726
Fixes
wpt/css/CSS2/abspos/abspos-containing-block-initial-004c.xht 
wpt/css/CSS2/abspos/abspos-containing-block-initial-004d.xht 
wpt/css/CSS2/abspos/abspos-containing-block-initial-005b.xht 
wpt/css/CSS2/abspos/abspos-containing-block-initial-005d.xht
I didn't import these wpt tests because they were failing for a reason unrelated to what they are actually testing. Instead, I use a custom test that tests these changes directly.
=> LibWeb/Layout: Account for box-sizing in table width/height calculations

vcpkg.json
libpxbackend was not being installed from vcpkg which lead to use of libpxbackend on the system causing library mismatch in rolling distros(ie arch linux)
**Before:**
**After:**
=> Build: Fix libpxbackend dependency mismatch

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Comment-constructor.txt, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/DOMImplementation-createHTMLDocument.txt, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Text-constructor.txt, Tests/LibWeb/Text/expected/wpt-import/html/dom/documents/dom-tree-accessors/document.title-07.txt, Tests/LibWeb/Text/expected/wpt-import/uievents/constructors/inputevent-constructor.txt, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Comment-Text-constructor.js, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Comment-constructor.html, Tests/LibWeb/Text/input/wpt-import/dom/nodes/DOMImplementation-createHTMLDocument.html, Tests/LibWeb/Text/input/wpt-import/dom/nodes/DOMImplementation-createHTMLDocument.js, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Text-constructor.html, Tests/LibWeb/Text/input/wpt-import/html/dom/documents/dom-tree-accessors/document.title-07.html, Tests/LibWeb/Text/input/wpt-import/uievents/constructors/inputevent-constructor.html
As suggested by @yyny on Discord
Resolves issues where nullable or optional WebIDL DOMString parameters were set to 'null' instead of actual null
https://webidl.spec.whatwg.org/#LegacyNullToEmptyString
> Note: This means that even DOMString? must not use [LegacyNullToEmptyString], since null is a valid value of that type.
I cannot reopen https://github.com/LadybirdBrowser/ladybird/pull/2626, so I had to create a new one
Fixes https://github.com/LadybirdBrowser/ladybird/pull/2628 (instead of a hack I introduced there)
=> IDL Generator: Fix nullable string set to 'null' instead of actual null

Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLInputElement.h, Libraries/LibWeb/HTML/HTMLInputElement.idl, Tests/LibWeb/Text/expected/HTML/unsigned-long-reflection.txt, Tests/LibWeb/Text/input/HTML/unsigned-long-reflection.html
These allow the width and height of image button inputs to be set and queried.
Fixes a total of 32 subtests in http://wpt.live/html/dom/reflection-forms.html and http://wpt.live/html/dom/reflection-forms-weekmonth.html
=> LibWeb: Implement the `HTMLInputElement` width and height attributes

Libraries/LibCrypto/ASN1/Constants.h, Libraries/LibCrypto/ASN1/DER.h, Libraries/LibCrypto/ASN1/PEM.cpp, Libraries/LibCrypto/ASN1/PEM.h, Libraries/LibCrypto/Certificate/Certificate.cpp, Libraries/LibCrypto/Certificate/Certificate.h, Libraries/LibCrypto/PK/EC.cpp, Libraries/LibCrypto/PK/EC.h, Libraries/LibCrypto/PK/RSA.cpp, Libraries/LibCrypto/PK/RSA.h, Libraries/LibTLS/TLSv12.cpp, Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp, Meta/Lagom/Fuzzers/FuzzRSAKeyParsing.cpp, Tests/LibCrypto/TestRSA.cpp, Tests/LibTLS/TestTLSCertificateParser.cpp, Tests/LibWeb/Text/expected/wpt-import/WebCryptoAPI/derive_bits_keys/ecdh_bits.https.any.txt, Tests/LibWeb/Text/expected/wpt-import/WebCryptoAPI/derive_bits_keys/ecdh_keys.https.any.txt, Tests/LibWeb/Text/expected/wpt-import/WebCryptoAPI/import_export/ec_importKey.https.any.txt, Tests/LibWeb/Text/expected/wpt-import/WebCryptoAPI/import_export/ec_importKey_failures_ECDH.https.any.txt
This is mainly refactoring of the ASN1 and PEM code around RSA and EC:
- Some stuff has been moved from `Crypto::Certificate` to `Crypto::ASN1` to be easily accessible.
- Treating ASN1 OIDs has been made simpler by categorizing them by length
- PEM decoding has been improved by returning the type and verifying the header and footer are consistent
- `RSA::parse_rsa_key` has been heavily simplified by utilizing existing code for PKCS#8 parsing
Got a couple of WPT tests as a bonus.
=> LibCrypto+LibWeb: Refactor PEM decoding + RSA / EC key parsing

Libraries/LibJS/Runtime/TypedArray.cpp, Libraries/LibJS/Runtime/TypedArray.h, Libraries/LibJS/Tests/builtins/Object/Object.freeze.js
This is a normative change in the ECMA-262 spec. See: 
https://github.com/tc39/ecma262/commit/c1040ff
This will actually cause a test262 failure:
```
test/built-ins/Object/freeze/typedarray-backed-by-resizable-buffer.js ✅ -> ❌
```
But there is an open PR to update that test already:
https://github.com/tc39/test262/pull/4324
=> LibJS: Prevent extensions of TypedArray exotic objects

Libraries/LibWeb/Bindings/MainThreadVM.cpp, Libraries/LibWeb/CMakeLists.txt, Libraries/LibWeb/DOM/AbstractRange.cpp, Libraries/LibWeb/DOM/AbstractRange.h, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/DOM/Document.idl, Libraries/LibWeb/DOM/Range.cpp, Libraries/LibWeb/DOM/Range.h, Libraries/LibWeb/Editing/CommandNames.cpp, Libraries/LibWeb/Editing/CommandNames.h, Libraries/LibWeb/Editing/Commands.cpp, Libraries/LibWeb/Editing/Commands.h, Libraries/LibWeb/Editing/ExecCommand.cpp, Libraries/LibWeb/Editing/Internal/Algorithms.cpp, Libraries/LibWeb/Editing/Internal/Algorithms.h, Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/Painting/ViewportPaintable.cpp, Tests/LibWeb/Text/expected/Editing/execCommand-delete.txt, Tests/LibWeb/Text/input/Editing/execCommand-delete.html
+12,477 new WPT passes in `editing`. The `selection` tests show no regressions.
This implements editing APIs such as `document.execCommand()` for `delete`, `defaultParagraphSeparator` and `styleWithCSS`.
=> LibWeb: Start implementing the editing API

.github/workflows/lagom-template.yml, Tests/LibWeb/TestConfig.ini, UI/Headless/Application.cpp, UI/Headless/Application.h, UI/Headless/CMakeLists.txt, UI/Headless/Test.cpp, UI/Headless/Test.h
We currently have 2 issues with Web tests on CI:
* The GCC pipeline is regularly timing out, and barely finishes in the 1500 second limit when it does pass.
* The macOS pipeline hangs indefinitely until killed by ctest.
To help with these, this bumps the timeout to 1800 seconds, and adds more verbose logging for macOS, so we can see which tests are starting but not finishing (and their duration if they do finish).
=> CI: Increase timeout a bit, and log each test duration

Toolchain/BuildVcpkg.py, vcpkg.json
This patch updates to the latest release of `vcpkg`. 
It fixes this warning:
```
CMake Warning (dev) at scripts/cmake/vcpkg_find_acquire_program.cmake:70 (cmake_parse_arguments):
The INTERPRETER keyword was followed by an empty string or no value at all.
Policy CMP0174 is not set, so cmake_parse_arguments() will unset the
arg_INTERPRETER variable rather than setting it to an empty string.
Call Stack (most recent call first):
scripts/cmake/vcpkg_find_acquire_program.cmake:143 (z_vcpkg_find_acquire_program_find_internal)
/Users/beeman/dev/github/beeman/ladybird/Build/release/vcpkg_installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:116 (vcpkg_find_acquire_program)
buildtrees/versioning_/versions/brotli/4e5b5ae1ad26c80535c893cc0307121f0398549e/portfile.cmake:14 …
```
=> Meta: Update vcpkg to the November 2024 release

Libraries/LibGC/Root.h, Libraries/LibJS/Console.cpp, Libraries/LibJS/Runtime/CommonPropertyNames.h, Libraries/LibJS/Runtime/PropertyKey.h, Libraries/LibWeb/Animations/KeyframeEffect.cpp, Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp, Libraries/LibWeb/HTML/HTMLAllCollection.cpp, Libraries/LibWeb/HTML/Window.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp, Services/WebContent/WebContentConsoleClient.cpp, Utilities/js.cpp
Lazily coercing might have made sense in the past, but since hashing
and comparing requires the `PropertyKey` to be coerced, and since a
`PropertyKey` will be used to index into a hashmap 99% of the time,
which will hash the `PropertyKey` and use it in comparisons, the
extra complexity and branching produced by lazily coercing has
become more trouble than it is worth.
Remove the lazy coercions, which then also neatly allows us to
switch to a `Variant`-based implementation.
=> LibJS: Stop lazily coercing numeric PropertyKeys

Libraries/LibWeb/CSS/Parser/Parser.cpp, Libraries/LibWeb/CSS/Parser/Parser.h
When the "Consume a component value from input, and do nothing." step in `Parser::consume_the_remnants_of_a_bad_declaration` was executed, it would allocate a `ComponentValue` that was then immediately discarded.
Add explicitly `{}_and_do_nothing` functions for this case that never allocate a `ComponentValue` in the first place.
Also remove a `(Token)` cast, which was unnecessarily copying a `Token` as well.
=> LibWeb: Stop allocating `Token`s and `ComponentValue`s unnecessarily

Libraries/LibJS/Runtime/ModuleRequest.h, Libraries/LibWeb/Bindings/MainThreadVM.cpp, Libraries/LibWeb/HTML/Scripting/ModuleScript.cpp
The begins the process of catching us up to various module related changes made in the spec
Edit: just noticed https://github.com/LadybirdBrowser/ladybird/issues/1549 after making this, I think this fixes #1549? We can't combine the two implementations, the 'ad-hoc' one is needed as the standalone JS implementation which is overridden in MainTheadVM for the HTML integration. Definitely more module catchup that we need to do though in general - e.g to fix the many crashes that we have in WPT and test262 tests.
=> LibWeb: Catch us up to some module related spec changes

Libraries/LibWeb/Painting/SVGSVGPaintable.cpp, Libraries/LibWeb/Painting/StackingContext.cpp
ApplyFilter internally calls canvas.saveLayer() which requires a matching canvas.restore() to be called.
Fixes painting on https://supabase.com/ regressed by 8562b0e33bd057d9aa5be1b6ce66db039bc99576
=> LibWeb: Use separate restore() for each ApplyFilters display list item

Documentation/BuildInstructionsLadybird.md, UI/default.nix, flake.lock, flake.nix
The current flake's devShell tries to import `Ladybird` which was renamed to `UI`.
Additionally, many dependencies aren't currently included in the devShell. As ladybird is already packaged downstream, we can pull in those buildInputs along with the extra dev dependencies already defined.
This gets the shell working and ladybird buildable :3
=> flake: Fix a broken dev shell

Libraries/LibWeb/Painting/StackingContext.cpp
restore() corresponding to ApplyFilters should be called after stacking context content is painted, not before.
Fixes regression introduced in c94b4316e7a2f3d245f9b48f77a7f9f76785218a
=> LibWeb: Fix CSS filters painting

Libraries/LibWeb/HTML/NavigationType.h, Tests/LibWeb/Text/expected/navigation/navigation-navigate.txt, Tests/LibWeb/Text/expected/wpt-import/navigation-api/navigate-event/event-constructor.txt, Tests/LibWeb/Text/input/wpt-import/navigation-api/navigate-event/event-constructor.html
Fix a typo in `NavigationType` enum. Convert it to lowercase strings, as described in the spec.
This PR fixes 2 WPT sub-tests in `event-constructor.html`.
=> LibWeb: Fix NavigationType enum to string conversion

Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLTableCellElement.cpp, Libraries/LibWeb/HTML/HTMLTableCellElement.h, Libraries/LibWeb/HTML/HTMLTableColElement.cpp, Libraries/LibWeb/HTML/HTMLTableColElement.h, Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp, Libraries/LibWeb/HTML/Numbers.cpp, Libraries/LibWeb/HTML/Numbers.h, Tests/LibWeb/Text/expected/HTML/unsigned-long-reflection.txt, Tests/LibWeb/Text/input/HTML/unsigned-long-reflection.html
Note: The first 4 commits have no impact on any tests - they are required to prevent regressions that would otherwise be introduced by the 5th commit that introduces `parse_integer_digits`.
This fixes all 30 failing subtests in: http://wpt.live/html/dom/reflection-tabular.html
=> LibWeb: Limit tabular element properties to allowed values

Documentation/EditorConfiguration/QtCreatorConfiguration.md, Meta/refresh-ladybird-qtcreator.sh
We no longer use C or raw assembly (*.S), and generated include files have moved to Build/release/Lagom/.
EDIT: Whoops, I thought the char limit per line in the commit body was 78, apparently it's 72. Fixed.
=> Meta+Documentation: Update config for QtCreator

Libraries/LibJS/Position.h, Libraries/LibJS/SourceCode.cpp
The source code position cache was moved from a line based approach to a "chunk"-based approach to improve performance on large, minified JavaScript files with few lines, but this has had an adverse effect on _multi-line_ source files.
Reintroduce some of the old behaviour by caching lines again, with some added sanity limits to avoid caching empty/overly small lines.
Source code positions in files with few lines will still be cached less often, since minified JavaScript files can be assumed to be unusually large, and since stack traces for minified JavaScript are less useful as well.
On WPT tests with large JavaScript dependencies like `css/css-masking/animations/clip-interpolation.html` this reduces the amount of time spent in `SourceCode::range_from_offsets` by as much as 99.98%, for …
=> LibJS: Cache source code positions more often

Libraries/LibWeb/CSS/CharacterTypes.h, Libraries/LibWeb/CSS/Parser/Parser.cpp, Libraries/LibWeb/CSS/Parser/Tokenizer.cpp, Libraries/LibWeb/CSS/StyleValues/GridTemplateAreaStyleValue.cpp, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/grid-definition/grid-support-grid-template-areas-001.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-shorthand-serialization.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-shorthand.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-template-areas-computed.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-template-areas-invalid.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-template-areas-one-cell.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-template-areas-valid.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-template-shorthand-areas-valid.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-template-shorthand.txt, Tests/LibWeb/Text/input/wpt-import/css/css-grid/grid-definition/grid-support-grid-template-areas-001.html, Tests/LibWeb/Text/input/wpt-import/css/css-grid/grid-definition/support/testing-utils.js
- `"foo."` should be parsed as `"foo ."`
- Identifiers must only contain "ident code point"s
- Each row must have the same number of columns 
- (this used to cause crashes on https://wpt.live/css/css-grid/grid-definition/grid-inline-support-grid-template-areas-001.html and https://wpt.live/css/css-grid/grid-definition/grid-support-grid-template-areas-001.html)
- `"a b" "c d"` should be serialised as itself (used to be `a b, c d`)
Overall this brings 108 new passing subtests in WPT's /css/css-grid/ and prevents a crash.
We still need to reject `grid-template-area` values with non-rectangular areas, but I'll leave that for later.
=> LibWeb: Improve grid-template-area parsing and serialization

AK/Assertions.cpp, AK/Assertions.h, AK/Format.h, AK/Try.h
```
VERIFICATION FAILED: !_temporary_result.is_error()
```
is not really a helpful error message.
When we are including `AK/Format.h`, which is most of the time, we can easily print a much more useful error message:
```
UNEXPECTED ERROR: Cannot allocate memory (errno=12)
```
=> AK: Print a more useful error message when a `MUST(...)` fails

UI/Qt/WebContentView.cpp
Fixes https://github.com/LadybirdBrowser/ladybird/issues/2163
=> UI/Qt: Do not pass left shift modifier on every return

.github/workflows/lagom-template.yml
I noticed that we had some CI runs where one set of test artifacts would be lost because of the naming conflict:
> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
> https://github.com/LadybirdBrowser/ladybird/actions/runs/12107691399/job/33754854370?pr=2663#step:18:30
So, let's make that impossible by using all the run's input values in the file name. And while I'm at it, correct the retention settings to use the default ones, instead of hard-coding it at 7 days, which is not very long.
=> CI: Prevent test artifacts disappearing from naming conflicts, and keep them around for longer

Libraries/LibWeb/Layout/FlexFormattingContext.cpp
This makes these values the same as `start` and `end`. While this is not entirely correct, it is better than centering which is what we did previously.
This fixes misaligned images on https://nos.nl
=> LibWeb/CSS: Do not ignore self-start/self-end alignment in flex layout

Libraries/LibWeb/Editing/ExecCommand.cpp, Libraries/LibWeb/Editing/Internal/Algorithms.cpp, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLElement.h, Tests/LibWeb/Text/expected/wpt-import/html/editing/editing-0/contenteditable/contenteditable-enumerated-ascii-case-insensitive.txt, Tests/LibWeb/Text/input/wpt-import/html/editing/editing-0/contenteditable/contenteditable-enumerated-ascii-case-insensitive.html
Adds at least 191 WPT passes from `editing/plaintext-only` to our total.
=> LibWeb: Implement "plaintext-only" state for contenteditable

Libraries/LibWeb/HTML/PromiseRejectionEvent.h, Libraries/LibWeb/HTML/ShadowRealmGlobalScope.h, Libraries/LibWeb/HTML/UniversalGlobalScope.cpp, Libraries/LibWeb/HTML/UniversalGlobalScope.h, Libraries/LibWeb/HTML/Window.h, Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h, Libraries/LibWeb/HTML/WorkerGlobalScope.h, Tests/LibWeb/Text/expected/wpt-import/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-event-constructor.txt, Tests/LibWeb/Text/input/wpt-import/html/webappapis/scripting/processing-model-2/unhandled-promise-rejections/promise-rejection-event-constructor.html
The 'reason' was getting initialized to 'empty' state when not
provided through the constructor, which results in a crash when
accessed through throw_dom_exception_if_needed in the generated
IDL getter.
=> LibWeb: Fix crash accessing 'empty' PromiseRejectionEvent reason

Libraries/LibWeb/DOM/Range.cpp, Tests/LibWeb/Text/expected/wpt-import/selection/shadow-dom/tentative/Selection-direction.txt, Tests/LibWeb/Text/input/wpt-import/selection/shadow-dom/tentative/Selection-direction.html
Previously, it was assumed that nodes must share the same root, prior to the calculation of their relative boundary point positions. This is no longer the case, since `Selection.setBaseAndExtent()` now accepts anchor and focus nodes that may be in different shadow trees.
This prevents 7 WPT test crashes in `/selection/shadow-dom/tentative`
=> LibWeb: Assert that nodes share shadow-including root in BP calculation

Libraries/LibWeb/HTML/StructuredSerialize.cpp, Libraries/LibWeb/HTML/StructuredSerialize.h, Tests/LibWeb/Text/expected/Worker/Worker-postMessage-transfer.txt, Tests/LibWeb/Text/expected/wpt-import/html/infrastructure/safe-passing-of-structured-data/window-postmessage.window.txt, Tests/LibWeb/Text/input/Worker/Worker-postMessage-transfer.html
Implement transfer logic for ArrayBuffer and ResizableArrayBuffer.
Change TransferDataHolder data type to Vector<u32> to reuse existing
serialization infrastructure.
Fix 5 WPT tests in `safe-passing-of-structured-data/window-postmessage.window.html`
that are related to transport, as well as `LibWeb/Text/input/Worker/Worker-postMessage-transfer.html`.
The latter is currently ignored due to flakiness in CI, so no rebaseline is
needed.
During serialization with transfer, initialize memory with known index
and initialize Serializer at position that dependent on the memory.
This is mandatory to make ArrayBuffer transport to work. It also happens
to fix 4 WPT tests, that are related to curcular references during
serialization.
=> LibWeb: Implement transfer for Resizable/ArrayBuffer

AK/Optional.h, AK/StringView.h, Libraries/LibCrypto/Certificate/Certificate.h, Libraries/LibHTTP/HeaderMap.h, Libraries/LibJS/Runtime/IndexedProperties.cpp, Libraries/LibURL/Parser.cpp, Libraries/LibURL/Parser.h, Libraries/LibUnicode/CurrencyCode.cpp, Libraries/LibUnicode/CurrencyCode.h, Libraries/LibWasm/Wasi.h, Libraries/LibWeb/CSS/CSSStyleDeclaration.h, Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp, Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.h, Libraries/LibWeb/DOMURL/DOMURL.cpp, Libraries/LibWeb/DOMURL/DOMURL.h, Libraries/LibWeb/Fetch/Request.cpp, Libraries/LibWeb/FileAPI/BlobURLStore.cpp, Libraries/LibWeb/FileAPI/BlobURLStore.h, Libraries/LibWeb/IndexedDB/Internal/Database.cpp, Libraries/LibWeb/IndexedDB/Internal/Database.h, Libraries/LibWebView/CookieJar.cpp, Libraries/LibWebView/CookieJar.h, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWindowOrWorkerInterfaces.cpp, Tests/AK/TestOptional.cpp
C++ will jovially select the implicit conversion operator, even if it's
complete bogus, such as for unknown-size types or non-destructible
types. Therefore, all such conversions (which incur a copy) must
(unfortunately) be explicit so that non-copyable types continue to work.
NOTE: We make an exception for trivially copyable types, since they
are, well, trivially copyable.
=> AK: Don't implicitly convert `Optional<T&>` to `Optional<T>`

Libraries/LibWeb/CSS/ComputedValues.h, Libraries/LibWeb/Painting/PaintableBox.cpp
Most computed border-radii contain their initial values, and since the normalized initial border radii are always zero, there is no need to do expensive floating point math to normalize them.
=> LibWeb: Do not normalize border radii containing their initial values

Documentation/Porting.md
"Unixen" sounds too German for an English document ;^)
Also, Haiku has never pretended to be a UNIX-like operating system...
Also, I added some info on the current status of the Android port
=> Documentation: Minor rewordings in Porting.md

Toolchain/BuildVcpkg.py
In the move to a python version of this script, I didn't notice that running the bootstrap script in shell mode precluded it from actually accepting the -disableMetrics argument.
Existing vcpkg installs can be un-metrics'd by re-running the bootstrap script with the disable argument, or by adding a vcpkg.disable-metrics file in $VCPKG_ROOT
thanks to @BenWiederhake for pointing this out 😅
=> Toolchain: Actually disable vcpkg metrics

Libraries/LibWeb/CSS/CalculatedOr.cpp, Libraries/LibWeb/CSS/CalculatedOr.h, Libraries/LibWeb/CSS/Length.cpp, Libraries/LibWeb/CSS/Length.h, Libraries/LibWeb/CSS/MediaQuery.cpp, Libraries/LibWeb/CSS/MediaQuery.h, Libraries/LibWeb/CSS/Parser/MediaParsing.cpp, Libraries/LibWeb/CSS/StyleValues/CSSMathValue.cpp, Libraries/LibWeb/CSS/StyleValues/CSSMathValue.h, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-001.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-002.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-003.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-004.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-005.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-006.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-007.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-008.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-resolution.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-sign-function-001.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-sign-function-002.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-sign-function-004.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-sign-function-005.html, Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-calc-sign-function-006.html
It was initially thought that the spec disallows them, but this turned out to be incorrect. This fixes several WPT subtests. It also fixes an issue on Wikipedia articles where the table of contents is sometimes rendered above the title, if the viewport width is small enough.
=> LibWeb/CSS: Allow calc() values in media queries

Libraries/LibCrypto/BigFraction/BigFraction.cpp, Libraries/LibCrypto/BigFraction/BigFraction.h, Libraries/LibJS/Runtime/CommonPropertyNames.h, Libraries/LibJS/Runtime/Intl/DurationFormat.cpp, Libraries/LibJS/Runtime/Intl/DurationFormat.h, Libraries/LibJS/Runtime/Intl/DurationFormatConstructor.cpp, Libraries/LibJS/Runtime/Intl/DurationFormatPrototype.cpp, Libraries/LibJS/Tests/builtins/Intl/DurationFormat/DurationFormat.prototype.format.js, Tests/LibCrypto/TestBigFraction.cpp
test262 diff (from the last commit):
```
Diff Tests:
test/intl402/DurationFormat/prototype/format/negative-zero.js                       ❌ -> ✅
test/intl402/DurationFormat/prototype/format/precision-exact-mathematical-values.js ❌ -> ✅
```
We now pass all Intl.DurationFormat tests:
```
test/intl402/DurationFormat    102/102   (100.00%) [ ✅ 102   ]
```
=> LibJS: Apply recent editorial updates to Intl.DurationFormat, and use MVs for large computations

Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
...in HTMLCanvasElement::to_data_url() and HTMLCanvasElement::to_blob().
This fixes the problem when surface is not allocated because context is not initialized yet, even though canvas size is non-zero.
Fixes broken WebDriver screenshot endpoint.
=> LibWeb: Allocate transparent surface based on surface null check

.github/workflows/lagom-template.yml, CMakePresets.json
Instead of writing ASAN and UBSAN output into the same stream we use for test logging, direct them to log files, named asan.log.$PID and ubsan.log.$PID, and then output them in a separate CI job that runs afterwards. This should hopefully make it easier to see which tests are failing.
The downside is that it's now harder to tell which tests the *SAN errors are related to. Any ideas on that are appreciated. Right now, I think making the test logs actually readable is more important, (after all, we've had thousands-of-lines-long *SAN outputs for months and not solved those issues,) but maybe other people disagree.
For now, a failing workflow showing the results of this can be seen at https://github.com/AtkinsSJ/ladybird/actions/runs/11979541011?pr=1
=> CI: Move sanitizer output into a separate CI step

Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Tests/LibWeb/Text/expected/canvas/fill-0x0-canvas-should-not-crash.txt, Tests/LibWeb/Text/input/canvas/fill-0x0-canvas-should-not-crash.html
Fixes https://github.com/LadybirdBrowser/ladybird/issues/2755
=> LibWeb: Null-check surface before allocating painter for context2d

Libraries/LibWeb/CSS/StyleValues/CSSColorValue.cpp, Libraries/LibWeb/CSS/StyleValues/CSSRGB.cpp, Tests/LibWeb/Text/expected/wpt-import/css/css-color/parsing/color-valid-hwb.txt, Tests/LibWeb/Text/input/wpt-import/css/css-color/parsing/color-valid-hwb.html
Fixes the crash in css/css-color/parsing/color-valid-hwb.html.
The crash was probably introduced in https://github.com/LadybirdBrowser/ladybird/commit/248e4bb517c2e26b90e588a4a5d3068cd44bc1cf, as it was the first
commit to VERIFY that the value given to `Color::with_opacity` were in
the correct range. As the values in color-valid-hwb.html were resolved
as NaN, the check never passed.
---
~And that I'm not sure this is the correct place to do this "clamping". Indeed, no clamping is done for other channels, and it seems that the spec only requires it for rgb-based color space ([here](https://www.w3.org/TR/css-color-4/#resolving-sRGB-values) and that [spec issue](https://github.com/w3c/csswg-drafts/issues/8629) seems to be relevant).~
EDIT from the next day: After reading the spec a bit …
=> LibWeb/CSS: Interpret NaN as 0 when resolving alpha

Libraries/LibWeb/Editing/Commands.cpp
Step 9 of this algorithm might end up at the document node, which does not have a parent. Fixes 2 WPT crash subtests.
=> LibWeb: Prevent crash when editing outside of <body>

Libraries/LibWeb/CSS/SelectorEngine.cpp, Tests/LibWeb/Text/expected/css-shadow-host-selector-matching.txt, Tests/LibWeb/Text/input/css-shadow-host-selector-matching.html
Fixes an issue where selectors inside a shadow root could incorrectly match their shadow host directly using selectors like #host, instead of requiring :host pseudo-class selectors.
Fixes issue #2319
=> LibWeb/CSS: Block shadow host matching in DOM

Libraries/LibWeb/Layout/LayoutState.cpp, Tests/LibWeb/Ref/expected/scrollable-overflow-viewport-bug.html, Tests/LibWeb/Ref/input/scrollable-overflow-viewport-bug.html
Nothing in the spec says that this part should unconditionally run for the viewport and this is breaking on https://battle.crossuniverse.net/intro, making the page scrollable when it shouldn't be.
I wasn't sure what to call the test for this, so if anyone has better ideas, I'd love to rename it.
Also, yes, it needs to append the child with javascript, if the child is in the page initially, the bug does not occur.
=> LibWeb: Remove non-spec condition in scrollable overflow calculation

Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWebView/InspectorClient.cpp
This adds some extra info to the side of nodes in the devtools to indicate whether they are scrollable, invisible or create a stacking context.
It indents a large chunk of the code in InspectorClient.cpp so that these can show up on non-element nodes as well, sine those used to early-exit.
Examples:
Note: "stacking context" has been replaced with "isolated" since.
=> LibWebView: Display layouting information in devtools

Meta/import-wpt-test.py, Services/WebContent/ConnectionFromClient.cpp, Tests/LibWeb/Ref/expected/mismatch-test-ref.html, Tests/LibWeb/Ref/input/mismatch-test.html, UI/Headless/Test.cpp, UI/Headless/Test.h
Ref tests can now have a `<link rel="mismatch">` condition. The test will pass if the expectation page doesn't match the test page.
The WPT test importer has also been modified to allow importing WPT reftests with mismatch conditions. Note that we currently don't support multiple conditions, the first condition found will be the only one that's checked.
NOTE: This change won't be able to detect certain types of issues that we may have with WPT reftests, since the mechanism the WPT test runner uses to compare reftests is significantly different to ours.
Fixes #2712
=> WebContent+headless-browser: Implement mismatch conditions for ref tests

Libraries/LibGfx/ImageFormats/PNGLoader.cpp
Fixes #2185
This makes [this image](https://www.db.yugioh-card.com/yugiohdb/external/image/00_logo_DuelLinks.png) and some others (found on https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=1 ) load without printing `libpng warning: Interlace handling should be turned on when using png_read_image` to the console.
To be honest, I am not sure what exactly this does, since the images load fine without, but if libpng says it should be turned on, it's probably correct.
Also, more notably, this triggers on http://acid2.acidtests.org/#top, due to the eyes.
=> LibGfx: Set png interlace handling on interlaced images

Documentation/CodingStyle.md
The requirement to use // for comments wasn't described anywhere, so now it is! Also updated the rule about TODO comments because we've allowed those for a while now.
=> Documentation: Update coding style rules about comments

.github/workflows/lagom-template.yml
Even in a successful LibWeb test run, on Linux, we currently always have
LSAN output. Causing this step to fail is currently making every run of
CI fail.
If LibWeb tests did fail, they should exit with a non-zero status code
on their own, causing the pipeline to fail.
=> CI: Do not fail the entire pipeline if there are LSAN logs

Libraries/LibJS/Runtime/Intl/PluralRules.cpp, Libraries/LibJS/Runtime/Intl/PluralRulesPrototype.cpp, Libraries/LibJS/Tests/builtins/Intl/PluralRules/PluralRules.prototype.resolvedOptions.js, Libraries/LibUnicode/NumberFormat.cpp, Libraries/LibUnicode/PluralRules.h
This is a normative change in the ECMA-402 spec. See:
https://github.com/tc39/ecma402/commit/62fe5db
test262 diff:
```
test/intl402/PluralRules/prototype/resolvedOptions/plural-categories-order.js ❌ -> ✅
```
=> LibJS+LibUnicode: Designate a sort order for plural rules categories

Libraries/LibWeb/CSS/Default.css, Libraries/LibWeb/CSS/Selector.cpp, Libraries/LibWeb/CSS/Selector.h, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Tests/LibWeb/Ref/expected/wpt-import/css/css-pseudo/file-selector-button-001-notref.html, Tests/LibWeb/Ref/input/wpt-import/css/css-pseudo/file-selector-button-001.html, Tests/LibWeb/Text/expected/wpt-import/css/css-pseudo/file-selector-button-inherit.txt, Tests/LibWeb/Text/input/wpt-import/css/css-pseudo/file-selector-button-inherit.html
The button for a file input now matches `::file-selector-button`.
=> LibWeb: Implement `::file-selector-button` pseudo element

Libraries/LibWeb/DOM/Node.cpp
This change includes two commits:
- 5e65b07c37d LibWeb: Minor code cleanup; use HTML::AttributeNames::value, not string
- 55c8088d01f3e3313101e99f807d577870d0e492 LibWeb: Use element.aria_foo(), not element.has_attribute("aria-foo"_string)
=> LibWeb: Code cleanup for attribute getting in Node::name_or_description

Libraries/LibWeb/HTML/HTMLCanvasElement.cpp, Tests/LibWeb/Text/expected/canvas/fill-0-height-canvas-should-not-crash.txt, Tests/LibWeb/Text/input/canvas/fill-0-height-canvas-should-not-crash.html
Fixes crashing when Gfx::PaintingSurface::create_with_size() is called with a size of 0.
=> LibWeb: Add missing empty size check before allocating PaintingSurface

Libraries/LibWeb/Infra/Types.h, Libraries/LibWeb/WebIDL/Types.h
Corresponds to https://github.com/whatwg/webidl/pull/1452
=> LibWeb: Redefine WebIDL types in terms of Infra spec

Libraries/LibWeb/ARIA/ARIAMixin.h, Libraries/LibWeb/ARIA/AttributeNames.cpp, Libraries/LibWeb/ARIA/AttributeNames.h, Libraries/LibWeb/CMakeLists.txt, Libraries/LibWeb/DOM/Element.h, Libraries/LibWeb/DOM/Node.cpp
We are currently constructing the attribute names as `FlyString`s every
time we invoke one of the ARIA attributes getters/setters. If there are
not any other instances of these strings in-memory, then we're thrashing
the `FlyString` cache.
Instead, let's follow suit of all other Web attributes - use an x-macro
to generate the attribute names.
=> LibWeb: Use a standard x-macro to create FlyString ARIA attribute names

Libraries/LibWeb/Streams/AbstractOperations.cpp, Libraries/LibWeb/Streams/AbstractOperations.h, Tests/LibWeb/Text/expected/wpt-import/streams/readable-byte-streams/patched-global.any.txt, Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/patched-global.any.html, Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/patched-global.any.js
This aligns us with the latest streams specification changes to accommodate for the security advisor GHSA-p5g2-876g-95h9.
See relevant links:
https://github.com/whatwg/streams/security/advisories/GHSA-p5g2-876g-95h9
https://github.com/whatwg/streams/pull/1326
Previously we would just crash on an assert in ReadableByteStreamControllerFillHeadPullIntoDescriptor which verifies that controller controller.raw_byob_request() should be null.
These changes make sure that we postpone calls to ReadableByteStreamControllerCommitPullIntoDescriptor until after all
pull-into descriptors have been filled up by ReadableByteStreamControllerProcessPullIntoDescriptorsUsingQueue.
The attached test verifies that a patched then() will see a null byobRequest.
=>  LibWeb: Commit pull-into descriptors after filling from queue

Meta/CMake/common_compile_options.cmake
This commit changes the exception flag to match the description and turn off exceptions. This matches the behavior of -fno-exceptions. However, on Windows SEH exceptions are always available, and there's no easy way to turn them off. This flag should also suppress previous /EHsc flags, if they get automatically set by cmake. Reference: https://learn.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=msvc-170
=> CMake: Fix Windows exceptions flag.

Libraries/LibWeb/Forward.h, Libraries/LibWeb/WebGL/Types.h, Libraries/LibWeb/WebGL/WebGLBuffer.cpp, Libraries/LibWeb/WebGL/WebGLBuffer.h, Libraries/LibWeb/WebGL/WebGLFramebuffer.cpp, Libraries/LibWeb/WebGL/WebGLFramebuffer.h, Libraries/LibWeb/WebGL/WebGLObject.cpp, Libraries/LibWeb/WebGL/WebGLObject.h, Libraries/LibWeb/WebGL/WebGLProgram.cpp, Libraries/LibWeb/WebGL/WebGLProgram.h, Libraries/LibWeb/WebGL/WebGLRenderbuffer.cpp, Libraries/LibWeb/WebGL/WebGLRenderbuffer.h, Libraries/LibWeb/WebGL/WebGLRenderingContextBase.idl, Libraries/LibWeb/WebGL/WebGLRenderingContextOverloads.idl, Libraries/LibWeb/WebGL/WebGLShader.cpp, Libraries/LibWeb/WebGL/WebGLShader.h, Libraries/LibWeb/WebGL/WebGLShaderPrecisionFormat.cpp, Libraries/LibWeb/WebGL/WebGLShaderPrecisionFormat.h, Libraries/LibWeb/WebGL/WebGLShaderPrecisionFormat.idl, Libraries/LibWeb/WebGL/WebGLTexture.cpp, Libraries/LibWeb/WebGL/WebGLTexture.h, Libraries/LibWeb/WebGL/WebGLUniformLocation.cpp, Libraries/LibWeb/WebGL/WebGLUniformLocation.h, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp
Some demos that now start working:
Shadertoy:
https://github.com/user-attachments/assets/950fe0ff-433a-40e8-8012-8edac0ab4fe6
WebGL Samples:
https://github.com/user-attachments/assets/7eeb424e-a405-407c-86ad-58adcba5167d
cc @kalenikaliaksandr, I believe you has a better implementation of texImage2D which does colour conversion, I'll happily drop the texImage2D commit for your version if you wish!
https://github.com/user-attachments/assets/82c4e98f-2c7d-45b2-b034-3df786c9be95
https://github.com/user-attachments/assets/555bc123-2c73-4b43-b095-c6a7635691cb
=> LibWeb: Implement a bunch of WebGL functions

Tests/LibWeb/TestConfig.ini
This partially reverts commit f1bbba2ba54913876830c1de2a293d6faee20535.
These tests are frequently timing out on macOS CI.
=> LibWeb: Re-disable SVG rendering tests

Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp, Libraries/LibJS/Runtime/Temporal/Calendar.cpp, Libraries/LibJS/Runtime/Temporal/Calendar.h, Libraries/LibJS/Runtime/Temporal/Duration.cpp, Libraries/LibJS/Runtime/Temporal/Duration.h, Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp, Libraries/LibJS/Runtime/Temporal/Instant.cpp, Libraries/LibJS/Runtime/Temporal/PlainDate.cpp, Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp, Libraries/LibJS/Runtime/Temporal/PlainDateTime.h, Libraries/LibJS/Runtime/Temporal/PlainTime.cpp, Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp, Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp, Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp, Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.prototype.round.js, Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.prototype.total.js
The last commit is a workaround for a [spec issue](https://github.com/tc39/proposal-temporal/issues/3015), for which a test has been added to test262 already that `master` now crashes on.
test262 diff:
```
Diff Tests:
test/built-ins/Temporal/Duration/prototype/round/relativeto-string-limits.js 💥 -> ✅
test/built-ins/Temporal/Duration/prototype/total/relativeto-string-limits.js 💥 -> ✅
```
=> LibJS: Round of Temporal editorial updates, and a spec issue workaround

Libraries/LibWeb/HTML/HTMLImageElement.cpp
This corresponds to https://github.com/whatwg/html/pull/10753
While I was here, I've also implemented the check for the current request changing, and reformatted the spec comments to match our style.
=> LibWeb/HTML: Resolve image decoding promises inside tasks

Libraries/LibWeb/HTML/StructuredSerialize.cpp, Tests/LibWeb/Text/expected/wpt-import/html/infrastructure/safe-passing-of-structured-data/window-postmessage.window.txt
Add serialization for the following array buffer types:
* ResizableArrayBuffer
* SharedArrayBuffer
* GrowableSharedArrayBuffer
I haven't added tests to cover shared array buffers, since they are hard to implement due to cross-origin isolation. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements
=> LibWeb: Serialization for resizable/shared array buffers

Libraries/LibWeb/DOM/Range.cpp, Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Libraries/LibWeb/Layout/LineBox.cpp, Libraries/LibWeb/Layout/SVGFormattingContext.cpp, Libraries/LibWeb/Painting/PaintableBox.cpp, Libraries/LibWeb/Painting/PaintableFragment.cpp, Libraries/LibWeb/Painting/PaintableFragment.h
Partly addresses #2787.
I found a few places where we're calling `first_available_font()` for things where we *actually* want to know the exact font used by these particular code-points. And, I've fixed some. Specifically, selection rectangles and text-editing cursor positions.
[Screencast_20241205_200256.webm](https://github.com/user-attachments/assets/c057ecb7-d70e-488e-b150-37053b6bd04a)
[Screencast_20241205_200448.webm](https://github.com/user-attachments/assets/c68a29c4-072c-46b3-897a-654ca10e990a)
```html
<style>
html, textarea { font-family: lololol; }
</style>
<textarea>Well hello friends! 😅😅😅😅😅😅😅😅😅😅</textarea>
```
It is *absolutely* not perfect still. A couple of issues:
1. Somehow, _Noto Emoji_ has a space character, and since that's the first font, that's the space character we …
=> LibWeb: Use GlyphRun fonts, not the first available font, for more things

AK/InsertionSort.h, Tests/AK/TestInsertionSort.cpp
Previously, it ignored 'start', sorting from the array's beginning. This caused unintended changes and slower performance. Fix ensures sorting stays within 'start' and 'end' indices only.
Fixes #2275
=> AK: Fix InsertionSort to respect specified bounds

Libraries/LibWeb/HTML/SharedResourceRequest.cpp
Introduced in bd932858, the code would try to move `result.color_space` into the ImmutableBitmap created for each single frame of an image. For animated images, this would result in a use-after-move from the second frame.
---
Thanks @Lubrsi for pointing that out.
=> LibWeb: Fix use-after-move in `handle_successful_bitmap_decode`

Libraries/LibWeb/CSS/Selector.cpp, Libraries/LibWeb/CSS/Selector.h, Libraries/LibWeb/HTML/HTMLDetailsElement.cpp, Tests/LibWeb/Ref/expected/wpt-import/html/rendering/the-details-element/details-pseudo-elements-001-ref.html, Tests/LibWeb/Ref/expected/wpt-import/html/rendering/the-details-element/details-pseudo-elements-003-ref.html, Tests/LibWeb/Ref/input/wpt-import/html/rendering/the-details-element/details-pseudo-elements-001.html, Tests/LibWeb/Ref/input/wpt-import/html/rendering/the-details-element/details-pseudo-elements-003.html
Details' contents matches a new details-content pseudo element.
Further work is required to make this pseudo-element behave per spec.
This pseudo should be element-backed per
https://drafts.csswg.org/css-pseudo/#element-backed
=> LibWeb: Implement `::details-content` pseudo element

Libraries/LibWeb/CSS/PseudoClasses.json, Libraries/LibWeb/CSS/SelectorEngine.cpp, Libraries/LibWeb/HTML/HTMLDialogElement.cpp, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLElement.h, Libraries/LibWeb/HTML/HTMLElement.idl, Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/popover-active-document.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/popover-types.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/togglePopover.txt, Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/popover-active-document.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/popover-types.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/togglePopover.html
Implements basics of showPopover, hidePopover and togglePopover.
Follow on from https://github.com/LadybirdBrowser/ladybird/pull/336
This improves the pass rate of various WPTs inside of wpt.live/html/semantics/popovers/
=> LibWeb: Implement popover methods

Libraries/LibJS/Runtime/Intl/DateTimeFormat.cpp, Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp, Libraries/LibJS/Runtime/Temporal/PlainDateTime.h, Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.format.js, Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatRange.js, Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatRangeToParts.js, Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatToParts.js
...electric boogaloo
test262 diff (from the fix in the last commit):
```
test/intl402/DateTimeFormat/prototype/format/temporal-objects-not-overlapping-options.js             ❌ -> ✅
test/intl402/DateTimeFormat/prototype/formatRange/temporal-objects-not-overlapping-options.js        ❌ -> ✅
test/intl402/DateTimeFormat/prototype/formatRangeToParts/temporal-objects-not-overlapping-options.js ❌ -> ✅
test/intl402/DateTimeFormat/prototype/formatToParts/temporal-objects-not-overlapping-options.js      ❌ -> ✅
```
=> LibJS: Temporal editorials, part two

Libraries/LibWeb/ARIA/ARIAMixin.cpp, Libraries/LibWeb/ARIA/ARIAMixin.h, Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/Internals/Internals.cpp, Libraries/LibWeb/Internals/Internals.h, Libraries/LibWeb/Internals/Internals.idl, Tests/LibWeb/Text/expected/wpt-import/html-aam/roles-contextual.txt, Tests/LibWeb/Text/input/wpt-import/html-aam/roles-contextual.html, Tests/LibWeb/Text/input/wpt-import/resources/testdriver.js
This change implements spec-conformant computation of default ARIA roles for elements whose expected default role depends on the element’s context — specifically, either on the element’s ancestry, or on whether the element has an accessible name, or both. This affects the `aside`, `footer`, `header`, and `section` elements.
Otherwise, without this change, `aside`, `footer`, `header`, and `section` elements may unexpectedly end up with the wrong default roles.
This gets us passing 100% of the subtests in the `roles-contextual.html` test at https://wpt.fyi/results/html-aam?product=ladybird.
This change includes an additional commit that adds a `window.internals.getComputedLabel(element)` function, for use in our imported copies of the WPT tests related to the behavior in this change.
=> LibWeb: Compute default ARIA roles context-sensitively where required

Tests/LibWeb/Text/expected/wpt-import/accname/basic.txt, Tests/LibWeb/Text/input/wpt-import/accname/basic.html, Tests/LibWeb/Text/input/wpt-import/resources/testdriver.js, Tests/LibWeb/Text/input/wpt-import/wai-aria/scripts/aria-utils.js
This change includes two commits:
- 835e11fbcf3 Tests: Move `window.internals.getComputedLabel` into `testdriver.js` file
- 292681db665 Tests: Import the WPT `accname/basic.html` test
=> Tests: Minor cleanup; Move window.internals.getComputedLabel, and import accname/basic.html

Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/NavigationParams.cpp, Libraries/LibWeb/HTML/NavigationParams.h
This PR adds support for the `X-Frame-Options` header. Additionally, the user agent now also acts as if it had stopped parsing once the error page has been set up.
This makes all of the [WPT Tests for X-Frame-Options](https://wpt.fyi/results/x-frame-options) pass, except for those where a combination of CSP and X-Frame-Options is used.
=> LibWeb: Support the `X-Frame-Options` header

Tests/LibWeb/Fixtures/http-test-server.py
This was mistakenly changed from int -> str in a previous commit: 08b8c88ac3ad5f44fcb8d29748480913252bb47b
Thanks @alissonlauffer for spotting this.
=> Tests/LibWeb: Fix type for delay_ms property in HTTP echo server

Libraries/LibGfx/Rect.h
The CenterRight and TopCenter alignment cases were mistakenly identical due to a copy-paste error, causing the function to behave unexpectedly.
Rather than attempting to fix it, remove aligned_within entirely.
=> LibGfx: Remove aligned_within from Rect

Documentation/FAQ.md
I’m not wedded to the particular wording of either the answer or the question here. But we get this question (in some form) frequently enough from people showing up on Discord — for example, see https://discord.com/channels/1247070541085671459/1247070543136690270/1315167861567914047 from just a few hours ago today — that it seems to merit being included in the FAQ.
=> Docs: Add “Is [some particular site] usable in Ladybird” to FAQ

Libraries/LibCore/ArgsParser.cpp
A bit of history:
isnan() was introduced in b143e604d71a202dafe57a6600a9991b883bffea and later moved to math.h in a45b6dbc0781a3968a730582509e838b370a31cb
It was required for `convert_to_double` to work. However, later on, in e2e7c4d5747, it was replaced with `StringView::to_number<double>`, and no longer unnecessary header has never been removed.
=> LibCore: Do not include math.h in ArgsParser

Libraries/LibWeb/HTML/StructuredSerialize.cpp, Libraries/LibWeb/WebAssembly/Instance.cpp, Libraries/LibWeb/WebAssembly/Memory.cpp, Libraries/LibWeb/WebAssembly/Memory.h, Libraries/LibWeb/WebAssembly/Memory.idl, Tests/LibWeb/Text/expected/wpt-import/wasm/jsapi/memory/constructor-shared.tentative.any.txt, Tests/LibWeb/Text/expected/wpt-import/wasm/jsapi/memory/grow.any.txt, Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/assertions.js, Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/memory/assertions.js, Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/memory/constructor-shared.tentative.any.html, Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/memory/constructor-shared.tentative.any.js, Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/memory/grow.any.html, Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/memory/grow.any.js
Add support for shared memory creation in WebAssembly memory API.
This API is needed for WPT tests that use shared array buffers.
Implementation is based on this [proposal](https://github.com/WebAssembly/threads/blob/main/proposals/threads/Overview.md#webassemblymemory-constructor) as per [MDN](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory/Memory#specifications).
Import related WPT tests.
Fix incorrect constructor function usage in `StructuredSerialize.cpp` when creating shared array buffers.
Related [whatwg issue](https://github.com/whatwg/html/issues/5380).
=> LibWeb: support creation of shared memory in WebAssembly memory API

Libraries/LibCrypto/ASN1/DER.cpp
On x86_64 Windows an unsigned long is 4 bytes, while a size_t is 8. As such this code causes a static assert checking that the size of both arguments to ceil_div is equal to fail at compilation time. This commit fixes this by replacing the unsigned long int literal with a size_t int literal.
=> LibCrypto: Use size_t integer literal in ASN1/Der.cpp

Libraries/LibCore/ResourceImplementation.cpp, Libraries/LibCore/ResourceImplementationFile.cpp
Adds include for dirent.h which we use in LibCore to provide the S_ISDIR macro on Windows. Fixes compilation of ResourceImplementation.cpp and ResourceImplementationFile.cpp
=> LibCore: Add includes for S_ISDIR on Windows

Libraries/LibJS/CMakeLists.txt
Clang-cl doesn't recognize -fno-omit-frame-pointe, and it is a noop on Windows.
=> LibJS: Make compile flag compatible with clang-cl

Libraries/LibWeb/HTML/HTMLInputElement.cpp, Tests/LibWeb/Text/expected/wpt-import/html-aam/roles.tentative.txt, Tests/LibWeb/Text/input/wpt-import/html-aam/roles.tentative.html
Merging this would get us 100% passing the WPT test at https://wpt.fyi/results/html-aam/roles.tentative.html?product=ladybird
=> LibWeb: Assign ARIA role “switch” to <input type=checkbox switch>

Libraries/LibWeb/XML/XMLDocumentBuilder.cpp, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-firstElementChild-namespace-xhtml.txt, Tests/LibWeb/Text/expected/wpt-import/domparsing/XMLSerializer-serializeToString.txt, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-firstElementChild-namespace-xhtml.xhtml
This fixes (at least) one WPT test and I imported it :)
The expected behavior is described here in the spec:
https://dom.spec.whatwg.org/#concept-element-local-name
It was already implemented correctly when constructing a `QualifiedName` in `Element::validate_and_extract`.
I don't know if my sequence of string conversions is the most efficient though, but don't hesitate to comment if there is a better one so that I can learn my way around AK.
=> LibWeb: Split the qualified name if there is a prefix

Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
This looks like the right thing to do, but PLEASE be careful merging this, as I am not sure if I'm getting things right.
This is not a security issue, as Validator doesn't allow wasm apps to pass out-of-bounds value here anyway
=> LibWasm: Respect instance.types() bounds

Libraries/LibWeb/MathML/Default.css
Proposed by bean at Discord
Updates `mfrac` styling in `MathML/Default.css` to align with the MathML Core Editor's Draft (26 November 2024).
- 2023 Working Draft: https://www.w3.org/TR/2023/WD-mathml-core-20231127/#fractions-mfrac
- 2024 Editor's Draft: https://w3c.github.io/mathml-core/#fractions-mfrac
=> LibWeb: Align mfrac Padding with Updated MathML Core Spec

Libraries/LibWeb/HTML/HTMLImageElement.cpp
Add an HTMLImageElement bug fix related to capturing local variables in a lambda that's passed to GC::Function.
=> LibWeb: Don't capture local variables in HTMLImageElement::decode

Libraries/LibWeb/Bindings/ExceptionOrUtils.h, Libraries/LibWeb/Bindings/MainThreadVM.cpp, Libraries/LibWeb/CSS/FontFaceSet.cpp, Libraries/LibWeb/Compression/CompressionStream.cpp, Libraries/LibWeb/Compression/DecompressionStream.cpp, Libraries/LibWeb/Crypto/SubtleCrypto.cpp, Libraries/LibWeb/Fetch/BodyInit.cpp, Libraries/LibWeb/Fetch/BodyInit.h, Libraries/LibWeb/Fetch/FetchMethod.cpp, Libraries/LibWeb/Fetch/Fetching/FetchedDataReceiver.cpp, Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp, Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.h, Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp, Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h, Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/Navigable.h, Libraries/LibWeb/HTML/Parser/HTMLParser.cpp, Libraries/LibWeb/HTML/Scripting/ImportMapParseResult.cpp, Libraries/LibWeb/Streams/AbstractOperations.cpp, Libraries/LibWeb/WebAssembly/WebAssembly.cpp, Libraries/LibWeb/WebIDL/Promise.cpp, Libraries/LibWeb/XHR/XMLHttpRequest.cpp
By actually using streams, they get marked as disturbed and the `.bodyUsed` API starts to work. Fixes at least 94 subtests in the WPT `fetch/api/request` test suite.
Pretty far out of my comfort zone for this so a thorough review is appreciated!
WPT results for `fetch/api/request`, before:
```
Ran 1065 checks (971 subtests, 94 tests)
Expected results: 813
Unexpected results: 252
test: 35 (35 error)
subtest: 217 (217 fail)
```
And after:
```
Ran 1065 checks (971 subtests, 94 tests)
Expected results: 907
Unexpected results: 158
test: 35 (35 error)
subtest: 123 (123 fail)
```
=> LibWeb: Implement Web::Fetch::Body::fully_read() closer to spec

Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWeb/DOM/Node.h, Libraries/LibWeb/HTML/HTMLScriptElement.cpp, Libraries/LibWeb/HTML/HTMLScriptElement.h, Tests/LibWeb/Text/expected/wpt-import/html/semantics/scripting-1/the-script-element/change-src-attr-prepare-a-script.txt, Tests/LibWeb/Text/input/wpt-import/html/semantics/scripting-1/the-script-element/change-src-attr-prepare-a-script.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/scripting-1/the-script-element/resources/flag-setter-different.js, Tests/LibWeb/Text/input/wpt-import/html/semantics/scripting-1/the-script-element/resources/flag-setter.js
Changed in the spec to align with Chrome and Webkit behavior.
(note: minor manual changes were needed for the WPT import as it was relying on the python service ?different query)
=> LibWeb: Implement post connection steps for HTML <script> elements

Libraries/LibWeb/Page/EventHandler.cpp, Libraries/LibWeb/Page/Page.h
Previously: https://github.com/SerenityOS/serenity/pull/24039
=> LibWeb: Request cursor change, leave tooltip area, and unhover link only when needed

Libraries/LibWeb/CSS/SelectorEngine.cpp, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/DOM/EditingHostManager.cpp, Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWeb/DOM/Node.h, Libraries/LibWeb/DOM/Text.h, Libraries/LibWeb/Editing/Commands.cpp, Libraries/LibWeb/Editing/ExecCommand.cpp, Libraries/LibWeb/Editing/Internal/Algorithms.cpp, Libraries/LibWeb/Editing/Internal/Algorithms.h, Libraries/LibWeb/HTML/FormAssociatedElement.cpp, Libraries/LibWeb/HTML/FormAssociatedElement.h, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLElement.h, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLInputElement.h, Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp, Libraries/LibWeb/HTML/HTMLTextAreaElement.h, Libraries/LibWeb/Internals/Internals.cpp, Libraries/LibWeb/Internals/Internals.h, Libraries/LibWeb/Internals/Internals.idl, Libraries/LibWeb/Page/DragAndDropEventHandler.cpp, Libraries/LibWeb/Page/EventHandler.cpp, Libraries/LibWeb/Painting/PaintableBox.cpp, Libraries/LibWeb/WebDriver/ElementReference.cpp, Tests/LibWeb/Text/expected/Editing/selection-in-contenteditable-crash-regression.txt, Tests/LibWeb/Text/input/Editing/selection-in-contenteditable-crash-regression.html
We were winging the invocations of "delete the selection" by calling into `DOM::Range::delete_contents()`, but that only got us so far. These changes give us a net +44 WPT subtest passes in `editing`.
* `Node::is_editable()` is completely redefined and made spec-compliant. I've found no regressions.
* A new `Internals` method called `mouseDown` is introduced in order to be able to simulate moving the mouse while keeping a button pressed.
* The "delete the selection" algorithm is almost completely implemented, except for recording and restoring current states & overrides.
=> LibWeb: Implement the "delete the selection" editing algorithm

Libraries/LibWeb/Crypto/Crypto.cpp, Tests/LibWeb/Text/expected/Crypto/Crypto-getRandomValues-respects-subarrays.txt, Tests/LibWeb/Text/input/Crypto/Crypto-getRandomValues-respects-subarrays.html
It is the responsibility of code that deals with TypedArrays to apply the byte offset and byte length. Not doing this caused Unity Web to crash, as they call getRandomValues with views into their full main memory. Previously, it would fill their entire memory of about 33.5 MB with random bytes.
=> LibWeb: Respect subarrays in Crypto#getRandomBytes
