- .github/workflows/lagom-template.yml
- .github/workflows/libjs-test262.yml
- .github/workflows/nightly-android.yml
- .github/workflows/serenity-js-artifacts.yml
- .github/workflows/wasm.yml
- Documentation/RunningTests.md
- Ladybird/CMakeLists.txt
- Ladybird/ImageDecoder/CMakeLists.txt
- Ladybird/RequestServer/CMakeLists.txt
- Ladybird/SQLServer/CMakeLists.txt
- Ladybird/WebContent/CMakeLists.txt
- Ladybird/WebDriver/CMakeLists.txt
- Ladybird/WebWorker/CMakeLists.txt
- Ladybird/cmake/AndroidExtras.cmake
- Ladybird/cmake/EnableLagom.cmake
- Ladybird/cmake/InstallRules.cmake
- Ladybird/cmake/ResourceFiles.cmake
- Meta/HeaderCheck/generate_all.py
- Meta/Lagom/CMakeLists.txt
- Meta/ShellCompletions/zsh/_serenity
- Meta/check-markdown.sh
- Meta/install-ports-tree.sh
- Meta/ladybird.sh
- Tests/LibWeb/WPT/run.sh
- Tests/LibWeb/rebaseline-libweb-test
- Userland/Libraries/LibTest/JavaScriptTestRunnerMain.cpp
In order to have checkouts of both SerenityOS and Ladybird, we need to use a different environment variable for Ladybird.
> Everywhere: Replace SERENITY_SOURCE_DIR with LADYBIRD_SOURCE_DIR

- Ladybird/default.nix
Ladybird needs python3 in order to build, but the devshell doesn't include it.
> nix: Add python3 to nix devshell

- Ladybird/Qt/FindInPageWidget.cpp
This matches the behavior of other browsers.
Example:
https://github.com/LadybirdWebBrowser/ladybird/assets/2817754/21b2a2c8-6c28-49ed-a0b7-2fec4e78f047
> Ladybird/Qt: Set find in page query to selected text on initial focus

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
Previously, line box borders were only set for the current tab when the option was toggled.
https://github.com/LadybirdWebBrowser/ladybird/assets/2817754/e72b9b2e-5a91-478c-a375-861a77bcece6
> Ladybird/Qt: Draw line box borders for all tabs when option is toggled

- Documentation/QtCreatorConfiguration.md
I'll leave the change of variable `__serenity__` in another PR, also
code need to be changed.
> Documentation: Fix name in QtCreator documentation

- Documentation/Browser/ProcessArchitecture.md
The commit removes an unnecessary newline character in the documentation that was breaking the bold formatting for **SystemServer**.
> Documentation: Remove unnecessary newline in documentation

- .github/workflows/lagom-template.yml
- .gitignore
- .ycm_extra_conf.py
- CMakeLists.txt
- CMakePresets.json
- Documentation/AdvancedBuildInstructions.md
- Documentation/BuildInstructionsLadybird.md
- Documentation/CLionConfiguration.md
- Documentation/EmacsConfiguration.md
- Documentation/HelixConfiguration.md
- Documentation/NvimConfiguration.md
- Documentation/VSCodeConfiguration.md
- Ladybird/CMakeLists.txt
- Ladybird/cmake/EnableLagom.cmake
- Ladybird/cmake/InstallRules.cmake
- Meta/ladybird.sh
- Tests/LibWeb/WPT/run.sh
This still preserves the ability to use Meta/Lagom as a top-level project, but kinda breaks using Meta/Lagom to build Ladybird. Hopefully we can discourage that from now on, and use Meta/Lagom as a top level project only for things like Fuzzers and cross-compile tools builds.
> Meta: Add new top-level CMakeLists, default to Build/ladybird

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
This matches the behavior of other browsers.
Example usage:
https://github.com/LadybirdWebBrowser/ladybird/assets/2817754/71642dcb-2d0b-4732-b203-1118a00e1fc0
> LibWeb: Extend text selection when left clicking and holding shift

- Documentation/README.md
The documentation for ladybird contained links to outdated and already removed guides, such as os specific build instructions. I also changed `Serenity development` to `Ladybird developement`.
I also fixed a typo in the link to the build instructions, see #55
> Documentation: Remove links to outdated guides

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
Previously, clicking while holding shift without having previously made any text selection would cause a crash.
Follow-up to: #54
:sweat_smile:
> LibWeb: Ensure anchor node is not null when extending selection

- Tests/AK/TestNeverDestroyed.cpp
Instead of attempting a stack use-after-free by reading an out-of-scope object's data member, let's keep a flag that checks if the destructor had been called in the outer scope.
Fixes #64
> Tests: Stop invoking UB in `AK::NeverDestroyed`'s tests

- Userland/Libraries/LibTimeZone/TimeZone.cpp
Fallback to reading /etc/timezone by calling system_time_zone() when unable determine time zone from /etc/localtime.
This works on systems where /etc/localtime is a file and not a symlink.
Fixes #65
> LibTimeZone: Read /etc/timezone for current TZ

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
All of the checkbox options in the Debug menu are now set across all tabs when the option is toggled. The spoof user agent option is also applied to all tabs when it is changed.
These options are also now applied to new tabs when they are created.
> UI/Qt: Set debug menu options across all tabs

- Ladybird/CMakeLists.txt
- Userland/Libraries/LibProtocol/RequestClient.cpp
- Userland/Libraries/LibProtocol/RequestClient.h
This fixes the running of headless-browser tests on CI.
Due to `IPC::ConnectionToServer::die` having a default implementation of `exit(0)`, we were gracefully exiting the headless-browser process when RequestServer failed to launch.
> Meta: Do not pass an empty --resources flag to headless-browser

- CMakePresets.json
This makes the build system to detect the vcpkg when using clion and other ide
> CMake: Added VCPKG_ROOT env to presets

- Userland/Libraries/LibCore/StandardPaths.cpp
- Userland/Libraries/LibGfx/Font/FontDatabase.cpp
NixOS doesn't have `/usr/share/fonts`, so Ladybird was only loading the default bitmap font. This fixes that by replacing hardcoded paths (`/usr/share/fonts`, `/usr/local/share/fonts`, `$HOME/.local/share/fonts`) with their XDG base directory equivalents (with fallbacks included so nothing changes on systems where `$XDG_DATA_HOME` or `$XDG_DATA_DIRS` are unset). It also silences the warnings when nonexistent directories are returned from `StandardPaths.cpp::font_directories()`, since that is to be expected with the updated code that checks for more possible directories.
> Fix fonts on NixOS and any other XDG-compliant distro with unusual directory structure

- Documentation/BuildInstructionsLadybird.md
Sometimes, especially on WSL, no fonts are installed, which will fail `VERIFY(m_default_font)` in Ladybird/FontPlugin.
Note that Liberation Sans does not provide fonts for `cursive` and `fantasy`, which will fall back to the default, sans-serif, font.
To cover all generic font families Microsoft's "Core fonts for the Web" are available as `ttf-mscorefonts-installer`, `ttf-ms-fonts`, etc.
> Documentation: Add some fonts to required packages

- Documentation/BuildInstructionsLadybird.md
My system was missing `zip` which gave me this message:
```
Could not find zip. Please install it (and other dependencies) with:
On Debian and Ubuntu derivatives:
sudo apt-get install curl zip unzip tar
On recent Red Hat and Fedora derivatives:
sudo dnf install curl zip unzip tar
On older Red Hat and Fedora derivatives:
sudo yum install curl zip unzip tar
On SUSE Linux and derivatives:
sudo zypper install curl zip unzip tar
On Arch Linux and derivatives:
sudo pacman -S curl zip unzip tar cmake ninja
On Alpine:
apk add build-base cmake ninja zip unzip curl git
```
I guess most systems have these installed.
> Documentation: Add new dependencies for vcpkg

- Userland/Libraries/LibWeb/Painting/Command.cpp
- Userland/Libraries/LibWeb/Painting/PaintOuterBoxShadowParams.h
- Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
- Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
This struct had all members in CSSPixels and DevicePixels, but only the latter are needed for painting.
Shrinks PaintOuterBoxShadowParams from 144 bytes to 72 bytes.
> LibWeb: Remove unused members in PaintOuterBoxShadowParams

- .github/actions/cache-restore/action.yml
- .github/workflows/lagom-template.yml
- .github/workflows/nightly-android.yml
- .github/workflows/serenity-js-artifacts.yml
- CMakeLists.txt
- CMakePresets.json
- Meta/ladybird.sh
Also add a vcpkg command to ladybird.sh to ensure that vcpkg is setup,
and use a local binary cache for vcpkg build and install media to
avoid cluttering $XDG_CACHE_HOME.
Ref:
Binary caching in general https://learn.microsoft.com/en-us/vcpkg/users/binarycaching#default-binary-cache
GA cache: https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
Local cache: https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-local?pivots=shell-bash
> Meta: Cache VcPkg in CI, and move enablement of vcpkg to ladybird.sh and CMakePresets.json

- Userland/Libraries/LibWeb/Painting/Command.cpp
- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandList.h
- Userland/Libraries/LibWeb/Painting/PaintBoxShadowParams.h
- Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
- Userland/Libraries/LibWeb/Painting/RecordingPainter.h
- Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
- Userland/Libraries/LibWeb/Painting/ShadowPainting.h
Before this change we were painting inner shadows lying outside of viewport.
Improves painting performance on Github and Twitter where this command is used a lot.
> LibWeb: Implement rejection by bounding box for PaintInnerBoxShadow

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
Small PR to fix a ubsan error (that appears when using the new spec-test generation).
> LibWasm: Check data section offset for overflow during instantiation

- Tests/LibWeb/TestConfig.ini
- Tests/LibWeb/Text/input/HTML/form-image-submission.html
This makes the `form-image-submission.html` test pass more reliably.
Fixes #100
> Tests/LibWeb: Wait until document fully loaded before simulating click

- Ladybird/FontPlugin.cpp
- Ladybird/WebContent/CMakeLists.txt
- Ladybird/WebWorker/CMakeLists.txt
- Meta/CMake/fontconfig.cmake
- vcpkg.json
If we get a suggestion from fontconfig, we try those fonts first, before falling back on the hard coded list of known suitable fonts for each generic family.
> Ladybird: Use fontconfig to choose generic fonts on non-Apple systems

- Userland/Libraries/LibWeb/ReferrerPolicy/AbstractOperations.cpp
This fixes a bug introduced in ab6b687d4c which was causing many live sites (such as chat.openai.com and github.com/serenityos/serenity) to crash.
> LibWeb: Do not release_value twice parsing a referrer policy

- Tests/LibWeb/Text/expected/Streams/ReadableStream-from-asyncIterator.txt
- Tests/LibWeb/Text/input/Streams/ReadableStream-from-asyncIterator.html
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.h
- Userland/Libraries/LibWeb/Streams/ReadableStream.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStream.h
- Userland/Libraries/LibWeb/Streams/ReadableStream.idl
Adds the static method `ReadableStream.from()` which can be used to wrap iterable and async iterable objects as readable streams.
> LibWeb: Implement static method ReadableStream.from(asyncIterable)

- Tests/LibWasm/test-wasm.cpp
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Operators.h
Adds all the arithmetic ops for f32x4 and f64x2 SIMD instructions.
With this, we pass 8701 additional tests :)
Quite a few of the spec tests for this are still failing. I confirmed with the wasmer runtime manually for a number of them, and we seem to match their and results. I'm not really sure what's happening here, a spec bug or wasmer is broken in the same way.
18802 failed before.
10101 failed after.
> LibWasm: FP SIMD arithmetric operations

- AK/Utf16View.cpp
- AK/Utf8View.h
- Tests/AK/TestUtf8.cpp
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Types.h
The [UTF-8](https://datatracker.ietf.org/doc/html/rfc3629#page-5) standard says to reject strings with upper or lower surrogates. However, in many standards ([ECMAScript included](https://262.ecma-international.org/14.0/#sec-ecmascript-language-types-string-type)) unpaired surrogates (and therefore UTF-8 surrogates) are allowed in strings. So, this commit extends the UTF-8 validation API with `AllowSurrogates`, which will reject upper and lower surrogate characters.
Unfortunately, there are two behaviors: surrogates are allowed and surrogates not allowed. I tried to reconcile them both into one API, but I ended up just extending `Utf8View`. Let me know if that approach isn't a good idea.
Also in this PR: validating that Wasm strings are UTF-8 (which spurred the change to AK code)
> LibWasm+AK: Validate that Wasm names are UTF-8

- Documentation/BuildInstructionsLadybird.md
After pulling master this morning, the CMake configure failed for the ICU dep. Installing this package fixed it
> Documentation: Add missing required Arch package

- Documentation/BuildInstructionsLadybird.md
Same as with #117, this package is required for building on Fedora.
> Documentation: Add missing required Fedora package

- Ladybird/Qt/FindInPageWidget.cpp
- Ladybird/Qt/FindInPageWidget.h
- Ladybird/Qt/Tab.cpp
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/WebContentClient.ipc
With this PR the results of a find in page query can now be reported back to the user interface. Currently, the number of results found and the current match index are reported.
I've updated the Qt chrome to show the results in the find in page panel. I haven't touched the MacOS chrome in this PR.
Demo:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/dae1da9c-83a9-48fa-9d4f-8ba9d89260e3
> LibWeb+WebContent+UI/Qt: Provide feedback on find in page requests

- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
This fixes a build failure when built with CMake option '-DENABLE_ALL_THE_DEBUG_MACROS=ON'.
Noticed this on pipeline SerenityOS (GNU, ubuntu-22.04, x86_64, ALL_DEBUG) / CI
https://github.com/SerenityOS/serenity/actions/runs/9437632127/job/25993714543#step:12:5623
> Fetch: Make sure we iterate over HeaderMap's headers()

- Tests/LibWeb/Text/expected/Streams/ReadableStream-can-cancel.txt
- Tests/LibWeb/Text/expected/Streams/TransformStream-cancelled-by-readable-side.txt
- Tests/LibWeb/Text/expected/Streams/TransformStream-cancelled-by-writable-side.txt
- Tests/LibWeb/Text/input/Streams/ReadableStream-can-cancel.html
- Tests/LibWeb/Text/input/Streams/TransformStream-cancelled-by-readable-side.html
- Tests/LibWeb/Text/input/Streams/TransformStream-cancelled-by-writable-side.html
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.h
- Userland/Libraries/LibWeb/Streams/TransformStreamDefaultController.cpp
- Userland/Libraries/LibWeb/Streams/TransformStreamDefaultController.h
- Userland/Libraries/LibWeb/Streams/Transformer.cpp
- Userland/Libraries/LibWeb/Streams/Transformer.h
This implements the `cancel` callback for TransformStream. The `cancel` callback is raised when the readable side of the TransformStream is cancelled, or the writable side is aborted.
Also added a test to prove a ReadableStream can be cancelled, noticed this behavior lacked a test.
> LibWeb: Implement and wire up TransformStream's cancel callback

- .github/workflows/serenity-js-artifacts.yml
Turns out vcpkg does not yet support Universal binaries. While they are working on it, lets produce arm64 binaries only for now to unblock the pipeline.
> CI: Release only arm64 JS artifacts on macOS for now

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
- Userland/Services/WebContent/PageClient.cpp
This way we leak less LibWeb implementation details into WebContent.
> LibWeb+WebContent: Move PageClient::paint() into TraversableNavigable

- Meta/Lagom/CMakeLists.txt
- Tests/LibURL/TestURL.cpp
- Userland/Libraries/LibURL/Parser.cpp
- Userland/Libraries/LibWebView/URL.cpp
Previously, part of the procedure we used to sanitize URLs entered via the command line would check the host against the public suffix database. This led to some valid, but not publicly accessible URLs being treated as invalid.
This allows me to visit my favorite website (http://web-platform.test:8000) by entering it on the command line.
URLs are now also now converted to lowercase when they are sanitized, previously an uppercase string entered into the URL bar, such as EXAMPLE.COM, would fail to load as expected.
> LibWebView: Don't query public suffix list when sanitizing URLs

- Ladybird/Qt/LocationEdit.cpp
The placeholder text is there to prompt the user as to what could be added in the address bar. The current text tells the user that they can "Search or enter web address" even when the search setting is disabled. When attempting to "Search" the user is instead sent to page ":", with an error in the console:
WebContent(575249): (FIXME) Don't know how to navigate to :
This patch fixes this by checking whether the search feature is enabled and setting the placeholder appropriately. This provides a slightly better user experience.
Closes #132
> UI/Qt: Update placeholder text if search disabled

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
This now matches the behavior of did_request_link_context_menu and friends. Previously the coordinates relative to the page rather than viewport were sent to the chrome.
> LibWeb: Use viewport position for did_enter_tooltip_area

- Ladybird/Qt/BrowserWindow.cpp
On my system `QKeySequence::StandardKey::ZoomIn` includes both `Ctrl++` and `Ctrl+=`, so explicitly adding the secondary `Ctrl+=` shortcut  ourselves results in an ambiguous shortcut error message being shown.
According to the Qt documentation the key bindings returned by `QKeySequence::StandardKey::*` are platform specific, so we may still need to add the secondary shortcut on some systems. Therefore, we now check whether our secondary shortcut is already in the shortcut list before adding it.
FWIW, I'm using Linux with KDE Plasma and a UK keyboard layout. I'd be interested to know whether this problem occurred for people on other systems.
The error message I saw when trying to zoom in prior to this PR:
> UI/Qt: Ensure we don't add the same zoom shortcut key more than once

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibIDL/IDLParser.cpp
- Userland/Libraries/LibJS/Runtime/Object.cpp
- Userland/Libraries/LibJS/Runtime/PropertyAttributes.h
- Userland/Libraries/LibJS/Runtime/PropertyDescriptor.h
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
This PR adds a new `JS::Attribute` - [[Unimplemented]]. Properties marked with the [[Unimplemented]] attribute behave as normal but invoke the `VM::on_unimplemented_property_access` callback whenever they are accessed.
This attribute is now used to implement IDL interfaces with the [FIXME] extended attribute. This fixes an issue where [FIXME] methods broke feature detection on some sites.
> LibJS+LibIDL+LibWeb: Reduce [FIXME] attribute unintended side effects

- Ladybird/AppKit/Application/ApplicationDelegate.h
- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/WebContentView.h
- Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/BUILD.gn
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/PreferredContrast.cpp
- Userland/Libraries/LibWeb/CSS/PreferredContrast.h
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentServer.ipc
- Userland/Services/WebWorker/PageHost.cpp
- Userland/Services/WebWorker/PageHost.h
This adds a contrast preference to the browser UI similar to the existing one for color scheme. Both AppKit UI and Qt UI has these new preference. The auto value is currently = NoPreference, follow ups can address wiring that up to the actual preference for the OS.
> LibWeb: Add Contrast preference

- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
Previously, `memory.fill` filled memory with 4-byte values, even though `memory.fill` should fill with just one byte. Also fixes some other issues with some of the bulk memory instructions, like `memory.init`. This PR gets `memory_fill.wast` and `memory_copy.wast` to fully pass!
> LibWasm: Make `memory.fill` fill with single bytes

- Meta/CMake/wasm_spec_tests.cmake
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
This also enables the compilation of `loop.wast` into a JavaScript test file, since it should no longer cause timeouts or segfault.
> LibWasm: Make loops work

- Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Validator.h
The validator now checks for stack height mismatches when encountering the `end` and `else` pseudo-instructions, and at the end of functions. This makes the core validation algorithm pretty much fully spec-compliant! There's a few miscellaneous validation issues left, but those can be handled in future PRs. This fixes around 300 failing tests (not including SIMD). That means `block.wast`, the various `local*.wast`, `select.wast`, and more all fully pass!
In order to support the stack height mismatch checks, the method of supporting stack polymorphism has changed. Instead of tracking `Unknown` entries, we now use the `unreachable` field of the `Frame` struct (both introduced in this PR). This is more like the [algorithm suggested in the …
> LibWasm: Tighten validation algorithm

- Userland/Libraries/LibGfx/PaintStyle.h
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
- Userland/Libraries/LibWeb/Painting/PaintStyle.cpp
- Userland/Libraries/LibWeb/Painting/PaintStyle.h
- Userland/Libraries/LibWeb/Painting/RecordingPainter.h
- Userland/Libraries/LibWeb/SVG/SVGGradientElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGGradientElement.h
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
- Userland/Libraries/LibWeb/SVG/SVGLinearGradientElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGLinearGradientElement.h
- Userland/Libraries/LibWeb/SVG/SVGRadialGradientElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGRadialGradientElement.h
...with a struct defined in LibWeb. This is a step towards uncoupling LibWeb from LibGfx, so we can try third-party libraries for painting.
> LibWeb: Replace usage of Gfx::PaintStyle in fill{stoke}_path commands

- Userland/Libraries/LibWeb/MixedContent/AbstractOperations.cpp
Previously, navigating to or from `about:newtab` caused a crash due to inadvertent null dereferences when checking whether a request or response to a request should be blocked as mixed content.
Fixes #160
> LibWeb: Avoid null dereference when performing mixed content checks

- Userland/Libraries/LibJS/CMakeLists.txt
Linking LibLocale publicly ensures that libicudata.a is also available in all embedders of LibJS. Otherwise, ICU crashes in hard-to-track-down ways at runtime when the data is not available.
Fixes #163
> LibJS: Link LibLocale publicly to ensure ICU data is available

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/FindInPageWidget.cpp
- Ladybird/Qt/FindInPageWidget.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
This commit adds the standard shortcuts for the Find Next and Find Previous buttons on the find in page panel. These shortcuts are usually F3 and Shift+F3 respectively, although Qt standard shortcuts may vary across platforms.
Video:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/af9fcd2b-3eec-45a6-8de0-e68bf0a2f4d6
> UI/Qt: Add standard shortcuts for find in page actions

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Executable.h
- Userland/Libraries/LibJS/Bytecode/Generator.cpp
- Userland/Libraries/LibJS/Bytecode/Generator.h
- Userland/Libraries/LibJS/Bytecode/Instruction.h
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Bytecode/Op.h
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Parser.h
- Make `let` and `const` variables fast locals in the global scope as well (except in the very topmost scope).
- Give `typeof` an environment coordinate cache.
Knocks down two 10% profile items to <1% when loading YouTube. No change on tracked benchmarks (or test262.)
> LibJS/Bytecode: Mid-June mixed bag of JS optimizations

- Userland/Libraries/LibWeb/DOM/Document.cpp
Previously, the find in page function would fail to find text which was split across multiple text nodes. For example, given the following markup: `WH<span>F` the query `WHF` would previously fail to be matched.
This is done by traversing all of the document's text nodes - constructing a complete string to query against and keeping track of the locations where that string is split across multiple nodes.
There are currently a few issues with this approach:
* The list of text node positions is currently reconstructed on every query. It would be more efficient to cache this and only recompute it when the document layout is invalidated.
* I've changed some places in `Document::find_matching_text()` that were using UTF-8 code point offsets to use byte offsets instead, as using a mixture of the …
> LibWeb: Support finding text split across multiple text nodes

- Userland/Services/WebContent/PageClient.cpp
Fixes compilation when ```HAS_ACCELERATED_GRAPHICS``` is not defined.
> WebContent: Add missing ifdef

- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
Previously, the "Find Next Match" and "Find Previous Match" actions simply updated the match index of the last query to be performed. This led to incorrect results if the page had been modified after the last query had been run.
`Page::find_in_page_next_match()` and `Page::find_in_page_previous_match()` both now rerun the last query to ensure the results are up to date before updating the match index.
The match index is also reset if the URL of the active document has changed since the last query. The current match index is maintained if only the URL fragment changes.
This PR also includes a fix to ensure that we only consider documents that are currently associated with the active window. This prevents a bug that would previously occur when navigating between pages, where results for …
> LibWeb: Rerun find in page query when navigating between URLs

- Userland/Libraries/LibAccelGfx/GlyphAtlas.cpp
- Userland/Libraries/LibGfx/Bitmap.h
- Userland/Libraries/LibGfx/Font/Font.h
- Userland/Libraries/LibGfx/Font/ScaledFont.cpp
- Userland/Libraries/LibGfx/Font/ScaledFont.h
- Userland/Libraries/LibGfx/Painter.cpp
Fixes https://github.com/LadybirdBrowser/ladybird/issues/88
> LibGfx: Don't try to paint glyphs that aren't in a font

- .github/actions/setup/action.yml
- .github/workflows/lint-code.yml
- .github/workflows/lint-commits.yml
- Meta/CMake/all_the_debug_macros.cmake
- Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.h
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/HTML/ValidityState.cpp
- Userland/Libraries/LibWeb/HTML/ValidityState.h
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
We mistakenly did not add the clang-format linter to the new repo's CI,
and some unformatted code made its way into the repo.
> CI: Restore the code linting job

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
- Userland/Libraries/LibWasm/Parser/Parser.cpp
This gets `elem.wast` to almost fully pass (2 tests left)! The remaining tests are pretty hard to fix with our current representation of constant expressions. They're simple enough in the spec that we don't need a full-fledged `Expression` to handle them, which might be relevant in a future PR.
> LibWasm: Improve element validation and instantiation

- Ladybird/Qt/Application.cpp
- Ladybird/Qt/Application.h
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/main.cpp
- Ladybird/WebDriver/main.cpp
This PR adds the `--allow-popups` option to Qt Ladybird, which disables popup blocking by default. WebDriver now uses this option to ensure popups are enabled for testing. This prevents an "unable to find test window" error on tests that
attempt to open a new window.
> UI/Qt+WebDriver: Add `--allow-popups` option and make WebDriver use it

- CMakePresets.json
By default, we were linking the debug version of all vcpkg dependencies, which was very noticeable in benchmarks. Let's default to a build type with reasonable performance.
> Meta: Change the default build type to RelWithDebInfo

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/LocationEdit.cpp
- Ladybird/Qt/LocationEdit.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
Previously, I often found myself in this situation:
* Copy a URL from somewhere
* Open a new tab Ladybird
* Paste the new URL and hit Enter
* `about:newtabhttp://some-site-i-want-to-visit.com not found` :sob: 
This PR makes 2 separate but related changes that make it easier for the user to copy and paste URLs into a new tab.  
Firstly, the `about:newtab` URL is no longer displayed in the location bar when viewing the new tab page. This also has the effect of allowing the user to see the placeholder text when opening a new tab
~~Secondly, the "Page on New Tab" option has been replaced with a "Page on New Window" option. The `about:newtab` page is now shown when opening a new tab in an existing window. This matches the behavior of all other browsers that I have used - Firefox also allows …
> UI/Qt: Don't show URL when a new tab is initially focused

- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Intl/CollatorConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DurationFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormatConstructor.cpp
- Userland/Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.format.js
This almost worked out of the box, but we need to be sure we pass the full locale (e.g. `en-u-ca-hebrew`) and not just the data locale (`en`) to ICU. This PR also includes a bug fix for handling null vs undefined locale keys, as passing the full locale to ICU otherwise regressed some tests.
test262 diff:
```
Summary:
Diff Tests:
+6 ✅    -6 ❌
Diff Tests:
test/intl402/DateTimeFormat/prototype/format/related-year-zh.js                          ❌ -> ✅
test/intl402/DateTimeFormat/prototype/formatRangeToParts/pattern-on-calendar.js          ❌ -> ✅
test/intl402/DateTimeFormat/prototype/formatToParts/pattern-on-calendar.js               ❌ -> ✅
test/intl402/DateTimeFormat/prototype/formatToParts/related-year-zh.js                   ❌ -> ✅ …
```
> LibJS: Support non-Gregorian calendars for Intl.DateTimeFormat

- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Intl/DurationFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/Intl.cpp
- Userland/Libraries/LibJS/Runtime/Intl/ListFormat.cpp
- Userland/Libraries/LibJS/Runtime/Intl/ListFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/ListFormatConstructor.cpp
- Userland/Libraries/LibLocale/ListFormat.cpp
- Userland/Libraries/LibLocale/ListFormat.h
Removing some dead code and changing ListFormat to match the caching style of other formats (number, datetime, etc).
No functional change, no test262 diff.
> LibJS+LibLocale: Some code removal / cleanup leftover from ICU porting

- Ladybird/WebDriver/main.cpp
This allows multiple WPT tests to be run in parallel with using the `--processes` option.
> WebDriver: Launch Ladybird with `--force-new-process`

- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
No other browser allows opening the select element dropdown with the select.click() function.
This change stops this happening in Ladybird.
You can test this with https://demo.lukewarlow.dev/showPicker/ - select.click() won't open the picker UI in any browser. focus will on iOS only, showPicker will in Chrome and Firefox (safari support isn't finished yet)
There's no explicit callout for this in the HTML spec as lots of the form control UI is UA defined, but https://html.spec.whatwg.org/multipage/input.html#the-input-element:activation-behaviour-2 shows that .click() should only show the picker for legacy cases of file and color inputs, no other input's picker should show, and this includes select elements.
> LibWeb: Prevent select.click() opening the dropdown

- Meta/CMake/common_compile_options.cmake
- Meta/CMake/lagom_compile_options.cmake
As part of https://github.com/LadybirdWebBrowser/ladybird/issues/38 - the first baby step, is to make sure that we do not use compile flags not supported by clang-cl.
If the clang-cl version I got installed from VisualStudio 2022 is not enough - we have another step.
```
C:\Program Files\Microsoft Visual Studio\2022\Community>clang-cl --version
clang version 17.0.3
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin
```
After this patch - we got syntax errors and missing APIs to fix, and longer compile flags issues.
> Meta/Windows: fix compilation flags for clang-cl

- Ladybird/AppKit/Application/ApplicationDelegate.h
- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/BUILD.gn
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/PreferredMotion.cpp
- Userland/Libraries/LibWeb/CSS/PreferredMotion.h
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentServer.ipc
- Userland/Services/WebWorker/PageHost.cpp
- Userland/Services/WebWorker/PageHost.h
This adds a motion preference to the browser UI similar to the existing ones for color scheme and contrast. Both AppKit UI and Qt UI has this new preference. The auto value is currently = NoPreference, follow ups can address wiring that up to the actual preference for the OS.
> LibWeb: Add Motion preference

- Ladybird/HelperProcess.cpp
- Ladybird/Qt/main.cpp
- Ladybird/Types.h
- Ladybird/WebContent/main.cpp
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/Painting/AffineCommandExecutorCPU.cpp
- Userland/Libraries/LibWeb/Painting/AffineCommandExecutorCPU.h
- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorCPU.h
- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorGPU.h
- Userland/Libraries/LibWeb/Painting/CommandExecutorSkia.cpp
- Userland/Libraries/LibWeb/Painting/CommandExecutorSkia.h
- Userland/Libraries/LibWeb/Painting/CommandList.cpp
- Userland/Libraries/LibWeb/Painting/CommandList.h
- Userland/Libraries/LibWeb/Painting/PaintStyle.h
- Userland/Libraries/LibWeb/Painting/RecordingPainter.cpp
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- vcpkg.json
This change introduces Skia painter available under a flag. It's not
yet match capabilities of Gfx::Painter and is not ready to replace it.
Motivation:
- The current CPU painter is a performance bottleneck on most websites.
Our own GPU painter implementation is very immature and has received
relatively little attention.
- There is ongoing effort on building painter that supports affine
transforms (AffineCommandExecutorCPU) but it is far from being on par
with the default CPU painter. Skia will allow us to immediately get
full transformation support for all painting commands.
GPU painting:
I experimented with Ganesh GPU-backend, however profiling revealed that
without sharing viewport texture between WebContent and Browser
processes, it won't bring much performance improvement compared to …
>  LibWeb: Add Skia painting command executor

- Userland/Libraries/LibJS/Print.cpp
- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp
- Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.h
- Userland/Libraries/LibJS/Runtime/Intl/CollatorConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DisplayNamesConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DurationFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/DurationFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/ListFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/LocaleConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/NumberFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/PluralRulesConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormat.h
- Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormatConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/SegmenterConstructor.cpp
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/Intl/Locale/Locale.prototype.calendar.js
- Userland/Libraries/LibLocale/Locale.cpp
- Userland/Libraries/LibLocale/Locale.h
There have been a number of changes to the locale resolution AOs that we've fallen behind on. Mostly editorial, but includes one normative change to canonicalize Unicode extension keywords in the Intl.Locale constructor.
The normative change is actually a fix for [a bug I reported ~2 years ago](https://github.com/tc39/ecma402/issues/707), so that's neat :^)
```
Diff Tests:
test/intl402/Locale/constructor-options-canonicalized.js ❌ -> ✅
test/intl402/Locale/prototype/calendar/canonicalize.js   ❌ -> ✅
```
We now pass all `Intl.Locale` tests:
```
test/intl402/Locale    147/147   (100.00%) [ ✅ 147   ]
```
> LibJS+LibLocale: Update AOs involved in locale resolution to the latest ECMA-402

- Userland/Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp
Apple Clang doesn't like this, rather than waiting for their version of random-clang-commit-to-call-a-release to catch up with llvm trunk, just work around the issue.
> LibWeb/CSS: Avoid capturing local references in lambda

- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebWorker/PageHost.h
Now SVGDecodedImageData uses Skia painter, if it's selected.
>  LibWeb: Respect selected painter in SVGDecodedImageData

- Userland/Libraries/LibLocale/DateTimeFormat.cpp
- Userland/Libraries/LibLocale/NumberFormat.cpp
- Userland/Libraries/LibLocale/PartitionRange.h
- Userland/Libraries/LibLocale/RelativeTimeFormat.cpp
We were redefining a Range type in a few formatters. Move it to its own header to avoid ODR violations (and give it a more descriptive name).
> LibLocale: Move definition of Range structure to dedicated header

- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Tests/async-this-value.js
When resuming execution of a suspended function, we must not overwrite any cached `this` value with something from the ExecutionContext.
This was causing an empty JS::Value to leak into the VM when resuming an async arrow function, since the "this mode" for such functions is lexical and thus ExecutionContext will have an empty `this`.
It became a problem due to the bytecode optimization where we allow ourselves to assume that `this` remains cached after we've executed a ResolveThisBinding in this (or the first) basic block of the executable.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/138
> LibJS: Don't overwrite cached `this` value on async/generator reentry

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
Find in page will no longer match text that spans across block elements. Previously, given the markup `WH<div>F</div>`, the query `WHF` would find a match. We would now match `WH` and `F` separately, but not `WHF`.
This PR also fixes another Find In Page issue where the Find Next button needed to be pressed twice before the match index would be updated.
> LibWeb: Don't match text across block elements for find in page queries 

- Ladybird/Qt/Application.cpp
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/main.cpp
The location bar URL is no longer hidden when creating a new tab or opening a new window that has an associated URL. Conversely, the location bar is now always focused and the URL hidden when creating a window or tab without an associated URL.
The location bar is focused when:
* Opening the browser from the command line with no URL arguments
* Opening a new tab (Ctrl+T)
* Opening a new window (Ctrl+N)
The location bar is not focused when:
* Opening the browser from the command line with one or more URLs
* Opening hyperlinks in a new tab
* Clicking a hyperlink with `target="_blank"`
This matches the behavior of other major browsers.
Video:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/9286d9a4-f9fa-4bd9-a641-aac2798f98b1
Fixes #227
> UI/Qt: Don't hide the location bar URL when creating a tab from a URL 

- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
This change fixes image loading where unsupported image types are included in the list of source elements.
Relevant website source code:
```html
<picture>
<source srcset="/assets/luke-0amITIOs.avif" type="image/avif">
</picture>
```
| -------|------|
|  <img width="443" alt="image" src="https://github.com/LadybirdBrowser/ladybird/assets/32498324/b9f4248b-5e58-4ffa-94fd-d501b9601be2">  | <img width="497" alt="image" src="https://github.com/LadybirdBrowser/ladybird/assets/32498324/a24e8267-0352-4a62-b55f-7a75e31a6737"> |
> LibWeb: Implement type attribute validation for image loading

- Documentation/BuildInstructionsLadybird.md
When building on macOS (Apple Silicon; homebrew), I got this error:
```
CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:166 (message):
Could not find pkg-config.  Please install it via your package manager:
brew install pkg-config
Call Stack (most recent call first):
scripts/cmake/vcpkg_fixup_pkgconfig.cmake:193 (vcpkg_find_acquire_program)
buildtrees/versioning_/versions/libpng/1b0781214ef5a3497d0e7db2c0ed7f7fae74248b/portfile.cmake:94 (vcpkg_fixup_pkgconfig)
scripts/ports.cmake:175 (include)
```
after installing `pkg-config` I was able to successfully build Ladybird.
> Documentation: Add pkg-config to homebrew deps

- Tests/LibWeb/Text/expected/UIEvents/auxevent.txt
- Tests/LibWeb/Text/input/UIEvents/auxevent.html
- Userland/Libraries/LibWeb/Internals/Internals.cpp
- Userland/Libraries/LibWeb/Internals/Internals.h
- Userland/Libraries/LibWeb/Internals/Internals.idl
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
Previously, no event was fired on middle click. This change also allows the UI to open a link in a new tab on middle click.
https://github.com/LadybirdBrowser/ladybird/assets/2817754/6e116fa3-83d6-42d1-b4e6-4ec38304ea54
Fixes #175
> LibWeb: Fire `auxclick` event on middle click

- Tests/LibWeb/Ref/css-case-insensitive-html-attributes-selector.html
- Tests/LibWeb/Ref/reference/css-case-insensitive-html-attributes-selector-ref.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
Before:
After:
Firefox as reference:
https://github.com/mozilla/gecko-dev/blob/a18d79db1695fc6019cac47874113fd3bb65a821/servo/components/selectors/build.rs#L30
> LibWeb: Add attribute list that must always be compared without casing

- Ladybird/AppKit/main.mm
- Ladybird/HelperProcess.cpp
- Ladybird/Qt/main.cpp
- Ladybird/Types.h
- Ladybird/WebContent/main.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp
This patch adds a simple in-memory HTTP cache to each WebContent process.
It's currently off by default (turn it on with `--enable-http-cache`) since the validation logic is lacking and incomplete.
> LibWeb: Implement very basic in-memory HTTP caching

- Meta/ladybird.sh
- Toolchain/BuildVcpkg.sh
- vcpkg.json
In the ICU update, there is no functional change, but they added an error message to the install output to indicate what host tools need to be installed. This has tripped some people up, so it seems worth updating to.
> Meta: Detect vcpkg updates and update ICU

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
With this change it is no longer possible for the paste action to change the text of non-editable text nodes.
Ideally, we would hide the paste button in the context menu completely. I already have some code to do this, but it doesn't behave exactly as other browsers do, due to how we focus the text cursor. I plan to look at this in a separate PR.
Before:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/3bcbacb8-9c27-408b-ade9-21b4a4d5ffab
After:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/83984b46-bb5a-43b9-98c5-de0982bd76ad
> LibWeb: Disallow pasting into non-editable text nodes

- Userland/Libraries/LibWeb/HTML/CloseWatcher.h
- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
Dialog elements now correctly establish a close watcher when shown modally.
This means modal dialogs now correctly close with an escape key press.
https://github.com/LadybirdBrowser/ladybird/assets/32498324/a063fe92-2f61-4933-ba31-4dd7edb75dbe
> LibWeb: Implement dialog element's close watcher

- .github/actions/setup/action.yml
- .github/workflows/lagom-template.yml
- .github/workflows/nightly-android.yml
Most users will be building with Xcode Clang on macOS anyway, as our
build scripts default to the system compiler if it's new enough. We
already have an upstream Clang-based workflow on Linux, so we won't lose
any compiler coverage by switching to Apple Clang on macOS.
This should help us avoid build breakages like https://github.com/LadybirdBrowser/ladybird/issues/186.
> CI: Use Xcode's Clang in the macOS workflows

- Tests/LibWebView/TestWebViewURL.cpp
- Userland/Libraries/LibWebView/URL.cpp
Allow navigation to data URLs from browser UI.
> LibWebView: Allow data URLs in sanitize_url

- Ladybird/AppKit/main.mm
- Ladybird/HelperProcess.cpp
- Ladybird/MachPortServer.cpp
- Ladybird/MachPortServer.h
- Ladybird/Qt/main.cpp
- Ladybird/WebContent/CMakeLists.txt
- Ladybird/WebContent/main.cpp
- Userland/Libraries/LibCore/CMakeLists.txt
- Userland/Libraries/LibCore/Forward.h
- Userland/Libraries/LibCore/IOSurface.cpp
- Userland/Libraries/LibCore/IOSurface.h
- Userland/Libraries/LibCore/MachPort.h
- Userland/Libraries/LibCore/Platform/MachMessageTypes.h
- Userland/Libraries/LibCore/Platform/ProcessStatisticsMach.cpp
- Userland/Libraries/LibCore/Platform/ProcessStatisticsMach.h
- Userland/Libraries/LibGfx/Bitmap.cpp
- Userland/Libraries/LibGfx/Bitmap.h
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/BackingStoreManager.cpp
- Userland/Services/WebContent/BackingStoreManager.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentClient.ipc
- Userland/Services/WebContent/WebContentServer.ipc
Using mmap-allocated memory for backing stores does not allow us to
benefit from using GPU-accelerated painting, because all the performance
increase we get is mostly negated by reading the GPU-allocated texture
back into RAM, so it can be shared with the browser process.
With IOSurface, we get a framebuffer that is both shareable between
processes and can be used as underlying memory for an OpenGL/Metal
texture.
This change does not yet benefit from using IOSurface and merely wraps
them into Gfx::Bitmap to be used by the CPU painter.
>  Everywhere: Use IOSurface as backing store on macOS

- Userland/Libraries/LibWeb/DOM/Range.cpp
This fixes an issue where clearing the find in page query would not always visually clear the selection.
Before:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/02431fff-5e54-4f20-928f-05721e14fa27
After:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/999cb547-2e5e-4278-b000-9dde40e5b85a
> LibWeb: Ensure a repaint occurs when the current selection is cleared

- Meta/Lagom/CMakeLists.txt
- Meta/Lagom/Tools/CodeGenerators/LibTimeZone/GenerateTimeZoneData.cpp
- Tests/LibTimeZone/TestTimeZone.cpp
- Userland/Libraries/LibTimeZone/CMakeLists.txt
- Userland/Libraries/LibTimeZone/TimeZone.cpp
- Userland/Libraries/LibTimeZone/TimeZone.h
Just some cleanup to make it simpler to find a TZDB replacement. This way we don't have to keep mental track of what functionality actually needs to be replaced. At quick glance, we may be able to use ICU for this.
> LibTimeZone: Remove entirely unused time zone methods

- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.h
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.idl
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasState.h
Implement setLineDash() and getLineDash() in CanvasPathDrawingStyles,
which write/read from the CanvasState object.
This doesn't implement the actual drawing of a dashed line, but at least
sites using the Chart.js library no longer fail with an exception.
Unfortunately the Painter classes don't support dashed/dotted lines
based on segments yet.
> LibWeb: Initial support for dashed lines in Canvas

- Ladybird/Qt/LocationEdit.cpp
- Ladybird/Qt/LocationEdit.h
- Ladybird/Qt/Settings.cpp
- Ladybird/Qt/Settings.h
The placeholder text shows "Search or enter web address" which doesn't tell the user about *how* the search will be performed. Other popular open source browsers show the search engine that will be used. For example:
Chromium: "Search **engine** or type a URL"
Firefox: "Search with **engine** or enter address"
This change changes the placeholder text of the location bar to show "Search with **engine** or enter web address".
> UI/Qt: Show search engine name in location bar

- Userland/Libraries/LibMedia/Containers/Matroska/Reader.cpp
I encountered this message when attempting to play a video on Wikipedia. It looks like the intention was to put this message behind a flag.
> LibMedia: Hide Matroska debug message behind a flag

- Tests/LibWasm/test-wasm.cpp
Prior to this commit, the test runner was ignoring the result, which meant that values that fit in less than 128 bits were shifted to remove the zero words (which is obviously incorrect).
> Tests/LibWasm: Don't ignore the result of BigInt::export_data()

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Element.idl
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp
- Userland/Libraries/LibWeb/DOM/ShadowRoot.h
- Userland/Libraries/LibWeb/DOM/ShadowRoot.idl
- Userland/Libraries/LibWeb/HTML/DOMParser.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.h
Both Element's and ShadowRoot's setHTMLUnsafe, and Document's static parseHTMLUnsafe methods are implemented.
See https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#unsafe-html-parsing-methods
All tests in https://wpt.live/html/webappapis/dynamic-markup-insertion/html-unsafe-methods/ now pass except for:
- https://wpt.live/html/webappapis/dynamic-markup-insertion/html-unsafe-methods/setHTMLUnsafe-xml.html - which seems like it could be due to be a pre-existing bug with html parsing in XML documents.
- https://wpt.live/html/webappapis/dynamic-markup-insertion/html-unsafe-methods/Document-parseHTMLUnsafe-style-attribute.html - which seems to be due to unrelated CSS serialisation bugs.
> LibWeb: Implement unsafe HTML parsing methods

- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
An input event is now fired when the step up or step down button of an input element of type number is clicked.
This ensures that any associated `<output>` element is updated when these buttons are clicked.
Demo:
https://github.com/SerenityOS/serenity/assets/2817754/86b44f2a-1a26-411f-947f-d03a4d9f62b4
This is the same change as: https://github.com/SerenityOS/serenity/pull/24347
> LibWeb: Fire input event on user interaction with input element buttons

- Userland/Libraries/LibJS/Tests/builtins/Array/Array.prototype.sort.js
- Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.add.js
- Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.and.js
- Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.compareExchange.js
- Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.exchange.js
- Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.or.js
- Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.sub.js
- Userland/Libraries/LibJS/Tests/builtins/Atomics/Atomics.xor.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.copyWithin.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.reverse.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.toReversed.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.with.js
- Userland/Libraries/LibJS/Tests/object-spread.js
- Userland/Libraries/LibJS/Tests/test-common.js
The deepEquals algorithm incorrectly evaluated equality of objects in the cases where the second object b has a superset of the keys of a, or had a different prototype.
For example:
```javascript
let a = { x: 1, y: 2 };
let b = { x: 1, y: 2, z: 3 };
deepEquals(a, b); // true
```
The new algorithm considers that the second object could have more keys than the first, and compares the prototypes of the objects.
Original PR: https://github.com/SerenityOS/serenity/pull/24521
> LibJS: Improve deep equals algorithms in tests

- Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/SecureContexts/AbstractOperations.cpp
This makes icons once again load in the directory listings
> LibWeb: Block file: and resource: URLs on websites (and make resource: work on file: pages)

- Ladybird/AppKit/Application/Application.h
- Ladybird/AppKit/Application/Application.mm
- Ladybird/AppKit/Application/ApplicationBridge.cpp
- Ladybird/AppKit/Application/ApplicationBridge.h
- Ladybird/AppKit/main.mm
- Ladybird/HelperProcess.cpp
- Ladybird/HelperProcess.h
- Ladybird/ImageCodecPlugin.cpp
- Ladybird/ImageCodecPlugin.h
- Ladybird/ImageDecoder/main.cpp
- Ladybird/Qt/Application.cpp
- Ladybird/Qt/Application.h
- Ladybird/Qt/WebContentView.cpp
- Ladybird/Qt/main.cpp
- Ladybird/WebContent/main.cpp
- Userland/Libraries/LibIPC/File.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/ImageDecoder/ConnectionFromClient.cpp
- Userland/Services/ImageDecoder/ConnectionFromClient.h
- Userland/Services/ImageDecoder/ImageDecoderServer.ipc
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageHost.h
- Userland/Services/WebContent/WebContentServer.ipc
- Userland/Utilities/headless-browser.cpp
This is the same behavior as RequestServer, with the added benefit that
we know how to gracefully reconnect ImageDecoder to all WebContent
processes on restart.
> Everywhere: Transition ImageDecoder to be single-instance, owned by UI     

- Tests/LibWeb/TestConfig.ini
This test is currently causing intermittent CI failures.
Ref: #296
> Tests: Skip `css-keyframe-fill-forwards.html` ref test

- Tests/LibWeb/Text/expected/HTML/Window-find.txt
- Tests/LibWeb/Text/input/HTML/Window-find.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
- Userland/Libraries/LibWeb/HTML/Window.idl
- Userland/Libraries/LibWeb/Page/Page.cpp
- Userland/Libraries/LibWeb/Page/Page.h
This is a non-standard API that other browsers implement, which highlights matching text in the current window.
This is just a thin wrapper around our find in page functionality, the main motivation for adding this API is that it allows us to write tests for our find in page implementation.
> LibWeb: Implement a minimal version of `Window.find()`

- Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
Cherry-picked from https://github.com/SerenityOS/serenity/commit/9f4f319277f90e7534de2b39edcc98387fc68b1d
> LibCore: Handle destroyed owner when unregistering timers and notifiers

- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/Qt/WebContentView.cpp
- Userland/Libraries/LibCore/CMakeLists.txt
- Userland/Libraries/LibCore/IOSurface.cpp
- Userland/Libraries/LibCore/IOSurface.h
- Userland/Libraries/LibCore/MetalContext.h
- Userland/Libraries/LibCore/MetalContext.mm
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/Painting/BackingStore.cpp
- Userland/Libraries/LibWeb/Painting/BackingStore.h
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.h
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.h
- Userland/Libraries/LibWebView/ViewImplementation.cpp
- Userland/Services/WebContent/BackingStoreManager.cpp
- Userland/Services/WebContent/BackingStoreManager.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebWorker/PageHost.cpp
- Userland/Services/WebWorker/PageHost.h
- vcpkg.json
If Metal context and IOSurface are available, Skia painter will use
Ganesh GPU backend on macOS, which is noticeably faster than the default
CPU backend.
Painting pipeline:
1. (WebContent) Allocate IOSurface for backing store
2. (WebContent) Allocate MTLTexture that wraps IOSurface
3. (WebContent) Paint into MTLTexture using Skia
4. (Browser) Wrap IOSurface into Gfx::Painter and use
QPainter/CoreGraphics to blit backing store into viewport.
Things we should improve in the future:
1. Upload textures for images in advance instead of doing that before
every repaint.
2. Teach AppKit client to read directly from IOSurface instead of
copying.
> LibCore+LibWeb: Use Metal backend for Skia painter on macOS

- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
LLVM 18 on macOS correctly errs when we try to allocate an incomplete SkiaSurface object.
> LibWeb: Ensure SkiaSurface is fully defined before it is allocated

- Meta/ladybird.sh
Hi,
In the [documentation](https://github.com/LadybirdBrowser/ladybird/blob/master/Documentation/BuildInstructionsLadybird.md#using-ladybirdsh), it says
> The simplest way to build and run ladybird is via the ladybird.sh script:
> ```bash
> # From /path/to/ladybird
> ./Meta/ladybird.sh run ladybird
> ./Meta/ladybird.sh gdb ladybird
> ```
So when the user types `gdb ladybird`, we need to convert `LAGOM_EXECUTABLE` to the package name.
Otherwise, `gdb` will throw an error: `/path/to/ladybird/Build/ladybird/bin/ladybird: No such file or directory.`
Thanks
> Meta: Handle LAGOM_EXECUTABLE in gdb command properly

- .github/CODEOWNERS
I don't expect Ladybird to be the upstream to any of these (some of them even having been removed already), so it's not much use for me to be notified on any unrelated changes.
Of course, if anything comes up Ladybird-side that actually requires my input, I'll be happy to provide that.
> Meta: Remove myself from CODEOWNERS

- Tests/LibWeb/Text/expected/HTML/HTMLTrackElement-kind-attribute.txt
- Tests/LibWeb/Text/input/HTML/HTMLTrackElement-kind-attribute.html
- Userland/Libraries/LibWeb/HTML/AttributeNames.h
- Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl
This reflects the HTML `kind` attribute.
Gets rid of a FIXME message I encountered while browsing Wikipedia.
> LibWeb: Implement the `HTMLTrackElement.kind` attribute

- Ladybird/Qt/BrowserWindow.cpp
This avoids a segfault that would previously occur when middle clicking to close a tab if only 1 tab was open.
Fixes #310
> UI/Qt: Ignore tab bar middle clicks if the user didn't click on a tab

- Userland/Libraries/LibAccelGfx/Painter.cpp
- Userland/Libraries/LibAccelGfx/Painter.h
- Userland/Libraries/LibGfx/Font/Font.h
- Userland/Libraries/LibGfx/Font/ScaledFont.h
- Userland/Libraries/LibGfx/Path.cpp
- Userland/Libraries/LibGfx/TextLayout.cpp
- Userland/Libraries/LibGfx/TextLayout.h
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.h
- Userland/Libraries/LibWeb/Layout/LineBox.cpp
- Userland/Libraries/LibWeb/Layout/LineBox.h
- Userland/Libraries/LibWeb/Layout/LineBoxFragment.h
- Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
- Userland/Libraries/LibWeb/Layout/LineBuilder.h
- Userland/Libraries/LibWeb/Layout/TextNode.cpp
- Userland/Libraries/LibWeb/Layout/TextNode.h
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Userland/Libraries/LibWeb/Painting/DisplayList.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerCPU.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerGPU.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableFragment.h
- Userland/Libraries/LibWeb/Painting/ShadowPainting.cpp
The ChunkIterator now limits a chunk to using only one font (before, it was possible to have a chunk with >1 font, when `unicode-range` CSS property is used).
This change allows us to reduce some complexity in the text shaping and painting code and makes us compatible with the APIs in Skia and HarfBuzz.
> Everywhere: Limit layout text fragments to use one font for all glyphs

- Userland/Libraries/LibWasm/WASI/Wasi.cpp
Doing so results in incorrect values being created, ultimately leading to traps or errors.
(cherry picked from commit f6c3b333334f7bb5314a844804cb259cf277005e)
> LibWasm/WASI: Don't convert enums and u8s into i64

- AK/Assertions.cpp
- AK/Backtrace.h.in
- Meta/Lagom/CMakeLists.txt
As recommended by the CMake docs, let's tolerate systems or setups that don't have backtrace(3) in the `<execinfo.h>` header file, such as those using libbacktrace directly.
@sideeffect42 does this fix your issue in the same way that #274 does?
> AK+CMake: Use the find module to find the correct backtrace(3) header

- Documentation/BuildInstructionsLadybird.md
In our build instructions, we provide command for installing everything **except a compiler**. This PR adds instruction on how to install a compatible version of **clang**.
This is purely to help newer devs (less familiar with c++ and Linux ecosystem), to make their onboarding experience better. As seen in last week in `#build-problems` channel in discord.
> Documentation: Add steps to install clang

- Userland/Libraries/LibWeb/HTML/AnimationFrameCallbackDriver.h
This avoids an unecessary lossy conversion for the current time from double to i32. And avoids an UBSAN failure on macOS that's dependent on the current uptime.
> LibWeb: Use double as the argument for AnimationFrameCallbacks

- Tests/LibWeb/Text/expected/geometry/domrect-create.txt
- Tests/LibWeb/Text/input/geometry/domrect-create.html
- Userland/Libraries/LibWeb/Geometry/DOMQuad.cpp
- Userland/Libraries/LibWeb/Geometry/DOMRect.idl
- Userland/Libraries/LibWeb/Geometry/DOMRectReadOnly.idl
Small fix, fixes http://wpt.live/css/geometry/DOMQuad*.html and http://wpt.live/css/geometry/DOMRect*.html :^)
> LibWeb/Geometry: Make DOMRect doubles unrestricted

- Userland/Libraries/LibCore/Process.h
clang 19 (git) complains that LocalSocket is an incomplete type and errors out. Including the full definition fixes the build.
The full error generated by clang looks like this:
FAILED: Lagom/Userland/Libraries/LibWebView/CMakeFiles/LibWebView.dir/ProcessManager.cpp.o
/usr/bin/ccache /home/doc/.local/bin/clang++ -DENABLE_COMPILETIME_FORMAT_CHECK -DENABLE_PUBLIC_SUFFIX=1 -DLibWebView_EXPORTS -I/home/doc/programming/ladybird -I/home/doc/programming/ladybird/Userland/Services -I/home/doc/programming/ladybird/Userland/Libraries -I/home/doc/programming/ladybird/Build/ladybird/Lagom -I/home/doc/programming/ladybird/Build/ladybird/Lagom/Userland/Services -I/home/doc/programming/ladybird/Build/ladybird/Lagom/Userland/Libraries -I/home/doc/programming/ladybird/Meta/Lagom/../.. …
> LibCore: Include full definition for LocalSocket

- Ladybird/AppKit/UI/TabController.mm
By Setting `setBordered` property on header buttons to `Yes` this path makes the whole button clickable. Previously the only the icon was clickable, now it's easy to click.
> UI/AppKit: Make the header buttons more accessible

- Ladybird/AppKit/UI/TabController.mm
Is necessary, since history navigation was refactored
> Ladybird/AppKit: Enable reload action

- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
This is an attempt to fix the hanging CI on macOS caused by some screenshot requests being stuck unprocessed. With this change, we at least make sure that the HTML event loop processing, which triggers repainting, will happen as long as there are navigables that need to be repainted.
> LibWeb: Reschedule HTML event loop processing if navigable needs repaint

- Documentation/BuildInstructionsLadybird.md
- Ladybird/CMakeLists.txt
- Meta/debug.plist
- Meta/ladybird.sh
- use lldb instead of gdb
- code sign with get-task-allow in debug builds (or upon request) to make opening the app in Instruments.app easier.
> Meta+CMake: Improve macOS debugging experience

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Layout/Viewport.cpp
- Userland/Libraries/LibWeb/Layout/Viewport.h
This PR makes 2 changes, which greatly improve the performance of find in page on pages with a lot of text. 
See the descriptions of the individual commits for details.
There is still more work that could be done to improve performance further. Case-insensitive matching is still slow on documents containing very large text blocks, such as [this copy](https://raw.githubusercontent.com/mmcky/nyu-econ-370/master/notebooks/data/book-war-and-peace.txt) of War & Peace.
I've included a test on one of the longest articles on Wikipedia.
Before:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/b825e5ac-9d25-4225-a1d3-c0bbbd2dd981
After:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/d0bd32ae-747f-4999-ad8e-103509755cac
Note: For both of the above tests, I waited a good 30 …
> LibWeb: Improve find in page performance on large documents

- Documentation/BuildInstructionsLadybird.md
Was unable to build Ladybird due to to the following error on Fedora 40:
```
--   Package 'libavcodec' not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:619 (message):
The following required packages were not found:
- libavcodec
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
Userland/Libraries/LibMedia/CMakeLists.txt:17 (pkg_check_modules)
```
```
$ pkg-config --libs libavcodec
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libavcodec', required by 'virtual:world', not found
```
Installed `ffmpeg-devel` which contains `libavcodec, Ladybird now builds and runs.
```
$ …
```
> Documentation: Add ffmpeg-devel package in Fedora instructions

- Documentation/BuildInstructionsLadybird.md
Add automake to the build instructions on Arch, Fedora and openSUSE.
This will bring them inline with Ubuntu and MacOS which already has automake listed as a dependency.
> Documentation: Add automake as dependency on Arch, Fedora and openSUSE

- Base/res/ladybird/newtab.html
- Ladybird/DefaultSettings.h
A giant white about:blank page was killing my eyes 🙃
> Ladybird: Replace the new tab page with a dark mode friendly blank page

- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/Qt/WebContentView.cpp
- Ladybird/Qt/WebContentView.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentClient.ipc
Now instead of sending the position in which the user entered the tooltip area, send just the text, and let the chrome figure out how to display it.
In the case of Qt, wait for 600 milliseconds of no mouse movement, then display it under the mouse cursor.
> LibWeb+UI/Qt: Display 'title' tooltips only when the mouse stops moving

- AK/GenericLexer.h
- AK/JsonParser.cpp
- Tests/AK/TestJSON.cpp
Twitter encodes the data for a tweet in a JSON value, and escapes e.g. emoji as paired surrogates. Without this change, we have incorrectly decoded data:
With this change, we get the almighty :nerd_face: emoji
> AK: Decode paired UTF-16 surrogates in a JSON string

- Tests/LibWeb/Text/expected/set-selection-inside-shadow-root.txt
- Tests/LibWeb/Text/input/set-selection-inside-shadow-root.html
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Selection/Selection.cpp
This PR makes the changes necessary to allow text selection to work within shadow roots, which allows the user to select text within `<textarea>` and `<input>` elements.
See individual commits for details
Video:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/f9399bfa-2628-44c5-9480-929f36b29508
NOTE: I believe a similar change to that made for `Selection::set_base_and_extent()` should also be made for `Selection::add_range()` to make it behave like other browsers, as the following doesn't work with shadow roots. 
https://github.com/LadybirdBrowser/ladybird/blob/5f06594bbd2d045ac026cbdba7c912249cdd5812/Userland/Libraries/LibWeb/Selection/Selection.cpp#L133-L135
I haven't made that change as part of this PR because the spec text for that method hasn't been updated.
> LibWeb: Make text selection work inside shadow roots

- Documentation/BuildInstructionsLadybird.md
Hi all, when installing on Ubuntu 22.04 these two packages were also required for Ladybird to build.
> Documentation: Add missing dependencies for Ubuntu

- Userland/Libraries/LibCrypto/Checksum/CRC32.cpp
The `__builtin_arm_*` intrinsics don't exist on all ARMv8 systems, e.g. the compilation failed on my Rockchip RK3399 system (Gentoo, GCC 13).
I propose to use the standardized [ARM C Language Extensions (ACLE)](https://developer.arm.com/documentation/ihi0053/latest/) intrinsics, instead.
> LibCrypto: Use ARM C Language Extensions (ACLE) for CRC32 intrinsics

- Userland/Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.h
- Userland/Services/WebWorker/DedicatedWorkerHost.cpp
Fetch requests from web workers fail CORS checks because the origin is not inherited from the outside settings. Ensure web worker origin is correctly inherited from outside settings. Fixes #189
> LibWeb: Add Web Worker Origin Inheritance

- Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
`if.wast` passes completely now!
> LibWasm: Validate potentially empty `else` branch in `if` instruction

- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
This will reduce log noise when visiting sites that have a lot of filtered content. Previously, red error text would be displayed in the logs for each filtered URL.
> LibWeb: Add log_filtered_request() method in ResourceLoader

- Meta/CMake/vulkan.cmake
- Userland/Libraries/LibCore/CMakeLists.txt
- Userland/Libraries/LibCore/VulkanContext.cpp
- Userland/Libraries/LibCore/VulkanContext.h
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.h
- vcpkg.json
Skia now uses GPU-accelerated painting on Linux if Vulkan is available.
Most of the performance gain is currently negated by reading the GPU
backend back into RAM to pass it to the Browser process. In the future,
this could be improved by sharing GPU-allocated memory across the
Browser and WebContent processes.
>  LibWeb+LibCore: Use Vulkan backend for Skia on Linux

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Tab.cpp
- Ladybird/Qt/Tab.h
- Userland/Libraries/LibWeb/HTML/NavigatorID.cpp
- Userland/Libraries/LibWeb/HTML/NavigatorID.h
- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
- Userland/Libraries/LibWeb/Loader/ResourceLoader.h
- Userland/Libraries/LibWeb/Loader/UserAgent.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
I will continue to work on this tomorrow, adding options to the GUI to change this setting :)
I'll also look into how to support a partial interface that should be implemented when the setting is Gecko.
```idl
partial interface mixin NavigatorID {
[Exposed=Window] boolean taintEnabled(); // constant false
[Exposed=Window] readonly attribute DOMString oscpu;
};
```
> LibWeb: Support Gecko and WebKit navigator compatibility modes

- Tests/LibWeb/rebaseline-libweb-test
- Userland/Libraries/LibWeb/HTML/AttributeNames.h
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLElement.h
- Userland/Libraries/LibWeb/HTML/HTMLElement.idl
The popover property now reflects the attribute.
It cannot currently use the Reflect IDL concept because the empty string value is special cased.
https://wpt.live/html/semantics/popovers/popover-attribute-basic.html - IDL Attribute Reflection subtest now passes.
> LibWeb: Implement popover property and attribute

- Documentation/BuildInstructionsLadybird.md
Adding packages that are required to compile without errors: `autoconf-archive` and `ffmpeg-7-libavcodec-devel`.
> Documentation: Update BuildInstructionsLadybird.md for openSUSE

- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
This was only ever used within SerenityOS. The current implementation of this method did nothing.
> LibWeb: Remove `ResourceLoader::emit_signpost()`

- Tests/LibAudio/TestPlaybackStream.cpp
- Tests/LibAudio/TestWav.cpp
- Tests/LibCompress/TestBrotli.cpp
- Tests/LibCompress/TestDeflate.cpp
- Tests/LibGfx/BenchmarkJPEGLoader.cpp
- Tests/LibGfx/TestICCProfile.cpp
- Tests/LibGfx/TestImageDecoder.cpp
- Tests/LibGfx/TestWOFF.cpp
- Tests/LibGfx/TestWOFF2.cpp
- Tests/LibJS/test262-runner.cpp
- Tests/LibWeb/TestHTMLTokenizer.cpp
We no longer run our tests on Serenity.
> Everywhere: Remove Serenity specific code from tests

- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
... to prevent that left-floating elements inside the list element push the list marker into the (non-floating) content of the list element.
Two small test pages. The second is a reduction from ao3.org. The bottom example shows a clear improvement (now the same as Chromium and Firefox), whereas the first example shows no degradation. (Still different from the other two browsers.)
I have tried to use the same const style as in the surrounding code, even if CLion did recommend  I place const qualifiers in a few more places. If this is not recommended and we want to follow the const-notes from clang-tidy, I'll fix that up.
```html
<body>
<div style="float: left; background-color: red; height: 50px; width: 150px; opacity: 50%;"></div>
<ul>
<li> <div>TEXT</div> <div …
```
> LibWeb: Save float-intrusion for marker before list elements layout

- Userland/Libraries/LibWeb/HTML/HTMLTrackElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTrackElement.h
I had a 'did I?' moment when I saw https://github.com/LadybirdBrowser/ladybird/commit/67e3ac8916d7354c8485b4bbe9c4162392e0e99c was merged.
> LibWeb: Add missing edge visit for TextTrack in HTMLTrackElement

- Userland/Libraries/LibGfx/TextLayout.cpp
The Replacement Character (U+FFFD) is most commonly used to signal a text encoding error, i.e. when a stream of bytes couldn't be converted to a sequence of code points. For glyphs that don't exist in a particular font, our rendering logic already does the right thing by drawing empty boxes (`.notdef`); let's not forcibly turn these into U+FFFD during rendering.
| before | after |
|-----------|---------|
| ![image](https://github.com/LadybirdBrowser/ladybird/assets/25866827/a36ec53c-7bbb-4943-8556-ba3d71c02dd5)    | ![image](https://github.com/LadybirdBrowser/ladybird/assets/25866827/d8505ef3-8c07-47c6-81e4-204218624f3e) |
(just a tiny pedantic annoyance I noticed while reading Discord scrollback about Arabic font rendering)
> LibGfx: Do not draw U+FFFD for unknown glyphs

- Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.h
NetBSD provides its own popcount() function.
Fixes
```
In file included from /scratch/wip/ladybird-git/work/serenity/Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.cpp:12:
/scratch/wip/ladybird-git/work/serenity/Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.h:26:2:   in 'constexpr' expansion of '<lambda closure object>Gfx::Detail::<lambda()>().Gfx::Detail::<lambda()>()'
/scratch/wip/ladybird-git/work/serenity/Userland/Libraries/LibGfx/EdgeFlagPathRasterizer.h:24:40: error: call to non-'constexpr' function 'unsigned int popcount(unsigned int)'
24 |         coverage_lut[sample] = popcount(sample);
|                                ~~~~~~~~^~~~~~~~
In file included from /usr/include/string.h:98,
from /scratch/wip/ladybird-git/work/serenity/AK/Error.h:17,
from …
```
> Fix build on NetBSD.

- AK/FloatingPoint.h
- AK/FloatingPointStringConversions.cpp
- AK/Math.h
Fixes FloatExtractors and implements `read_eight_digits` for big-endian CPUs.
The `read_eight_digits` implementation could certainly be optimized further with some shifting and masking like in the little-endian case, but it's the best I could come up with.
> AK: Implement FloatExtractors and floating-point conversions for big-endian

- AK/Format.cpp
Just casting an integer type to a char pointer does not work on big endian.
Instead, the value needs to be properly converted into a char.
I uncommented the 7-bit ASCII check while at it. I think it's better to be safer than necessary to spot cases where high ASCII/UTF-8 support would be needed earlier.
> AK: Fix {:c} formatter for big-endian

- AK/StringBase.h
- Tests/AK/TestString.cpp
I'm opening this PR to collect feedback on which parts of `StringBase.h` are little-endian only.
It seems to work fine on big-endian as is.
Since all fields of the struct are `u8` I also don't see anything endian-specific.
> AK: Implement ShortStrings for big-endian

- AK/Assertions.h
- AK/Platform.h
- Userland/Libraries/LibWeb/Loader/UserAgent.h
This PR adds `AK_IS_ARCH` defines for ppc/ppc64/ppc64le and user agent CPU strings for 32-bit and 64-bit PowerPC.
For the 64-bit PowerPC user agent I followed the `RISC-V 64` pretty-printed example instead of using `ppc64(le)` like `x86_64` or `AArch64`.
These changes are not complete, only the first step to enable PowerPC support in Ladybird.
LibJS also needs to be updated (sign-extension of pointers) for getting little-endian ppc64le to work. (I didn't do it in this PR because I don't know how to do it correctly.)
For big-endian support in general more work is needed (#395, ...).
> AK+LibWeb: First steps for PowerPC CPU architecture support

- Documentation/NvimConfiguration.md
`nvim-lspconfig` has become more popular recently and is from the Neovim organization directly. Headers have also been shifted to match other documentation files.
I'm not sure if the `coc.nvim` setup guide is worth keeping around. As far as I know, it hasn't been validated in recent years, and assumes the person reading the guide has no existing setup.
For now, I've left both of them in.
> Documentation: Add `nvim-lspconfig` support to Neovim config guide

- Meta/ladybird.sh
Retrieve the build preset with environment variable BUILD_PRESET, which if unset is initialized to "default".
It's a minor change, but I've found it helpful, since trying to set up a cmake build from scratch gets a bit tricky with all of the vcpkg deps that aren't pulled in automatically
> Meta: permit specifying a build preset in ./Meta/ladybird.sh

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/DOM/derived-interface-prototype.txt
- Tests/LibWeb/Text/input/DOM/derived-interface-prototype.html
Following the rules in the algorithm from
https://webidl.spec.whatwg.org/#js-platform-objects, "To Internally create a new object implementing the interface interface", this change incorporates the steps to load a prototype from new.target, and write it to the created instance returned from constructor_impl(). This mirrors the code for generate_html_constructor(), which incorporates additional steps needed by Custom Elements.
Bug #334
> LibWeb: Implement WebIDL constructor flow for derived classes

- Tests/LibWeb/Layout/expected/flex/justify-content-on-min-content-with-gap.txt
- Tests/LibWeb/Layout/input/flex/justify-content-on-min-content-with-gap.html
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
This was reported in issue https://github.com/LadybirdBrowser/ladybird/issues/364
Handling gaps doesn't appear to be part of CSS-FLEXBOX-1, so it's unclear what this behaviour should be. But FireFox, Chrome and Safari all treat the main gap as a minimum value. This pull request matches that behaviour.
> LibWeb: Fix `justify-content: space-*` removing gaps

- CMakeLists.txt
- Ladybird/Android/BuildLagomTools.sh
- Ladybird/Android/CMakeLists.txt
- Ladybird/Android/build.gradle.kts
- Ladybird/Android/src/main/cpp/LadybirdActivity.cpp
- Ladybird/Android/src/main/cpp/WebContentService.cpp
- Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
- Ladybird/Android/src/main/cpp/WebViewImplementationNative.h
- Ladybird/Android/vcpkg_android.cmake
- Ladybird/FontPlugin.cpp
- Ladybird/WebContent/CMakeLists.txt
- Ladybird/cmake/AndroidExtras.cmake
- Meta/CMake/fontconfig.cmake
- Meta/CMake/use_linker.cmake
- Userland/Libraries/LibCore/StandardPaths.cpp
- Userland/Libraries/LibMedia/CMakeLists.txt
- Userland/Libraries/LibMedia/FFmpeg/FFmpegVideoDecoderStub.cpp
- vcpkg.json
This PR fixes various issues with the Android build, and gets it back in a somewhat working state. (Fixes #220)
It is not super stable (sometimes you have to reload a page a few times to get it to work, sometimes some resources aren't loaded properly) but it does somewhat work!
There were a variety of changes - most of them had to do with supporting the new external dependencies, but there were also some name/function signature changes that had to be accommodated in the Android-specific code.
I realize there are quite a few commits here, so let me know if you have any questions/feedback or if you'd like me to split this into multiple PRs!
Screenshots:
(I have not yet gotten ladybird.org to load with both correct fonts and correct CSS...I think there are still a few bugs to chase down)
> Android: Get the build in a working state again

- Base/res/ladybird/templates/error.html
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/Loader/GeneratedPagesLoader.cpp
- Userland/Libraries/LibWeb/Loader/GeneratedPagesLoader.h
- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
This adds a non-standard "null" state to the navigation params which can contain an additional error message, this is then passed to the `load_error_page` function
This changes the generic "HTTP request failed" error into the one provided by ResourceLoader
This changes the errors from file: and resource: loads to "network errors", which trigger the error page instead of silently failing. Alternatively we could map `errno`s to status codes more intelligently, and have empty bodies trigger the error page. (From what I can tell this already mostly happens with HTTP requests [but it results in a network error as well](https://github.com/LadybirdBrowser/ladybird/blob/8c9d3b30cf62016ffb03e425f1e7e3f2461262bf/Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp#L421))
Hook up the error messages …
> LibWeb: Display error message on error page + error passing changes

- Tests/LibWeb/rebaseline-libweb-test
This makes it so that `rebaseline-libweb-test` can be run on *nix or MacOS as the path to `headless-browser` on MacOS is `./bin/Ladybird.app/Contents/MacOS/headless-browser` while it is `./bin/headless-browser` on *nix.
> Tests: Make `rebaseline-libweb-test` OS aware

- .github/actions/setup/action.yml
- Meta/CMake/vulkan.cmake
- Userland/Libraries/LibCore/CMakeLists.txt
- Userland/Libraries/LibUnicode/CMakeLists.txt
- vcpkg.json
Also require a specific ICU version to not run into unexpected problems.
Fixes #444
> Meta: Add vulkan and vulkan-headers to vcpkg dependencies

- Userland/Libraries/LibWeb/CSS/Properties.json
This PR ensures the correct initial values for the `font`, `font-family` and `color` CSS properties are used.
Fixes the following WPT test: http://wpt.live/infrastructure/assumptions/html-elements.html
> LibWeb/CSS: Use correct initial values for CSS properties

- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
> LibWeb: Push temporary EC before rejecting failed image decode

- Tests/LibWeb/Layout/expected/block-and-inline/out-of-flows-not-inserted-into-generated-box.txt
- Tests/LibWeb/Layout/input/block-and-inline/out-of-flows-not-inserted-into-generated-box.html
- Userland/Libraries/LibWeb/Layout/Node.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
If a pseudo element (`::before` or `::after`) is a block `display` (for instance `body::before { display: block; }`) then some adjacent element is added as a child to the pseudo element's generated wrapper element if the adjacent element is a floating element. This essentially means that the element would be added as an inline element to the pseudo element.
This fixes some layout issues on the Swedish tax agency's site (skatteverket.se), such as the logo being really small and some list items being misaligned :)
This PR also includes a small refactor where out-of-flow and in-flow is added to functions to `Layout::Node` as `is_out_of_flow()` and `is_flow()`.
> LibWeb: Fix layout issues with floats and block level pseudo elements

- Tests/LibWeb/Layout/expected/input-placeholder.txt
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
So that it is closer to the spec.
https://www.w3.org/TR/css-ui-4/#input-rules
Updated the relavant test to reflect the changes. 
Before:
After:
> LibWeb/HTML: Update Text Input Styling

- Tests/LibWeb/Ref/css-color-functions.html
- Tests/LibWeb/Ref/reference/css-color-functions-ref.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
This PR breaks the original `parse_rgb_or_hsl_color` method into several `parse_*_color` methods for each color function.
It passes all existing ladybird tests (if you want new tests in this PR then I'll need to be told how to add them), and I didn't find any regressions in the web platform tests.
Here's some before and after screenshots from a website that uses `oklch`:
> LibWeb/CSS: Add support for hwb, oklab and oklch color functions

- Userland/Libraries/LibCore/VulkanContext.cpp
Good to have at least some information about instance creation failure.
> LibCore: Print error code returned by vkCreateInstance()

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
Previously, new tabs always had the `auto` color scheme, regardless of what the user has selected before.
Replace the 3 individual slots with a `set_preferred_color_scheme` method.
> Ladybird/Qt: Apply selected color scheme for new tabs

- Documentation/BuildInstructionsLadybird.md
[This PR](https://github.com/LadybirdBrowser/ladybird/pull/446) by @ADKaster added new dependencies that broke build process. So, adding it to documentation for future new folks to project.
I don't have experience with other distros, so not updating their instructions incase their process is not as straight forward as this.
> Documentation: Add new dependencies libx11-dev libxrandr-dev

- Ladybird/AppKit/Application/ApplicationBridge.cpp
- Ladybird/HelperProcess.cpp
- Ladybird/HelperProcess.h
- Ladybird/Qt/WebContentView.cpp
- Ladybird/Qt/main.cpp
- Ladybird/WebDriver/main.cpp
- Ladybird/WebWorker/CMakeLists.txt
- Ladybird/WebWorker/main.cpp
- Tests/LibWeb/WPT/run.sh
Using Qt networking when running web platform tests improves performance significantly. The time to run the subset of tests we run on CI drops from 21.9 seconds to 8.2 seconds on my machine.
> WebDriver: Add option to use Qt networking

- .ycm_extra_conf.py
As per YCM's own .ycm_extra_conf.py:
```python
final_flags = list( compilation_info.compiler_flags_ )
```
Before this change clangd would crash.
> Meta: Make YCM return flags as Python list

- Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp
- Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.h
- Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.idl
This adds the CustomElementRegistry getName function, as [specified](https://html.spec.whatwg.org/multipage/custom-elements.html#dom-customelementregistry-getname).
Verified that it works by visiting [wpt.live getName tests](https://wpt.live/custom-elements/CustomElementRegistry-getName.html) and seeing that the test passes.
> Add customElements.getName

- Ladybird/Android/src/main/cpp/RequestServerService.cpp
- Ladybird/RequestServer/main.cpp
- Meta/Lagom/CMakeLists.txt
- README.md
- Tests/LibTLS/CMakeLists.txt
- Tests/LibTLS/TestTLSHandshake.cpp
- Userland/Libraries/LibCore/Socket.h
- Userland/Libraries/LibCrypto/Authentication/HMAC.h
- Userland/Libraries/LibHTTP/HttpsJob.cpp
- Userland/Libraries/LibTLS/CMakeLists.txt
- Userland/Libraries/LibTLS/Certificate.h
- Userland/Libraries/LibTLS/CipherSuite.h
- Userland/Libraries/LibTLS/Handshake.cpp
- Userland/Libraries/LibTLS/HandshakeCertificate.cpp
- Userland/Libraries/LibTLS/HandshakeClient.cpp
- Userland/Libraries/LibTLS/HandshakeServer.cpp
- Userland/Libraries/LibTLS/Record.cpp
- Userland/Libraries/LibTLS/Socket.cpp
- Userland/Libraries/LibTLS/TLSPacketBuilder.h
- Userland/Libraries/LibTLS/TLSv12.cpp
- Userland/Libraries/LibTLS/TLSv12.h
- Userland/Libraries/LibWebSocket/Impl/WebSocketImplSerenity.cpp
- Userland/Libraries/LibWebSocket/WebSocket.cpp
- Userland/Services/RequestServer/CMakeLists.txt
- Userland/Services/RequestServer/ConnectionCache.cpp
- Userland/Services/RequestServer/ConnectionCache.h
- Userland/Services/RequestServer/main.cpp
- vcpkg.json
This reverts commit 8bb610b97a4394f50e23b84956ed6b399065f224. Linking wolfSSL seems to cause more legal trouble than it's worth due to it being GPLv2, so let's undo this for now.
> Revert "LibTLS+Everywhere: Switch to using WolfSSL"

- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Userland/Libraries/LibWeb/HTML/SharedImageRequest.cpp
We would attempt to decode the body data as an image regardless of the response status, so I added a couple checks.
> LibWeb: Check for failed response when fetching images and favicons

- Documentation/BuildInstructionsLadybird.md
openSUSE comes in two flavors, Leap and Tumbleweed.
The proposed changes address the build instructions for openSUSE Leap.
They are based on my successful execution of ` ./Meta/ladybird.sh run ladybird` on my machine (openSUSE Leap 15.5)
> Documentation: Extend openSUSE Leap build instructions.

- Userland/Libraries/LibMedia/Color/ColorConverter.cpp
- Userland/Libraries/LibMedia/PlaybackManager.cpp
- Userland/Libraries/LibMedia/VideoFrame.cpp
BT.470 B/G "Matrix coefficients" doesn't work in current master branch.
Handle BT.470 B/G color matrix the same as BT.601. This seemed to work fine with the limited number of videos I tested.
You can generate a video with the BT.470 color matrix by identifying the current color matrix:
```bash
ffprobe -v error -select_streams v:0 -show_entries stream=color_space -of default=noprint_wrappers=1:nokey=1 video.webm 
bt709
```
Then converting the color matrix like so:
```bash
ffmpeg -i input.webm -vf "colormatrix=bt709:bt470bg" output.webm
```
The colors appear to match pretty well using the existing matrix.
> LibMedia: Support videos with BT470BG color matrix

- Userland/Libraries/LibWeb/Page/EventHandler.cpp
This patch implements basic keyboard functionality for page scrolling and history traversal.
> LibWeb: Scroll page and nav history with keyboard

- Meta/ladybird.sh
This should fix the control-c issue mentioned in
https://github.com/LadybirdBrowser/ladybird/issues/68
> Meta: Use the binary to run the app instead of open on macos

- Userland/Libraries/LibJS/Runtime/NumberConstructor.cpp
When compiling with `-O2 -g1` optimizations (as done in the main Serenity build), no out-of-line definitions end up emitted for `Value::to_numeric`, causing files that reference the function but don't include the definition from `ValueInlines.h` to add an undefined reference in LibJS.so.
(cherry picked from commit 85b7ce8c2f6daf0db80e801d7fb2503d070765ce)
> LibJS: Add missing `ValueInlines.h` include for `Value::to_numeric`

- Tests/LibWeb/Text/expected/HTML/WindowOrWorkerGlobalScope-reportError.txt
- Tests/LibWeb/Text/input/HTML/WindowOrWorkerGlobalScope-reportError.html
- Userland/Libraries/LibWeb/HTML/Window.h
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.idl
This pull requests add a initial implementation of global.reportError() function.
refs: https://html.spec.whatwg.org/multipage/webappapis.html#runtime-script-errors
Example document to check the behaviour:
```html
<html>
<head></head>
<body>
<script>
window.onerror = (message, filename, lineno, colno, error) => {
console.log('Caught an error.', {message, filename, lineno, colno, error});
};
window.reportError(new Error('Reporting an Error!'));
</script>
</body>
</html>
```
> LibWeb: Add initial implementation of global.reportError()

- Ladybird/Android/src/main/cpp/WebViewImplementationNative.cpp
- Ladybird/Android/src/main/cpp/WebViewImplementationNative.h
- Ladybird/Android/src/main/cpp/WebViewImplementationNativeJNI.cpp
- Ladybird/Android/src/main/java/org/serenityos/ladybird/WebView.kt
- Ladybird/Android/src/main/java/org/serenityos/ladybird/WebViewImplementation.kt
- Ladybird/Android/src/main/res/layout/activity_main.xml
This PR adds support for touch events in the Ladybird WebView by passing them through as `Web::MouseEvent`s.
This is not ideal, mainly because it means scrolling works as it does on desktop (you have to tap and drag the scrollbar). (And also, the pages don't know that they are receiving touch events, and we have no way of supporting multitouch gestures, and many other problems...) But at least now the user can interact with the page!
I also changed the SwipeRefreshLayout that contained the WebView to a FrameLayout. This is because the swipe-to-refresh gesture was interfering with touch events on the WebView (whenever you dragged up it would get intercepted by the SwipeRefreshLayout). Once we implement the proper scrolling interfaces then this can be changed back I think.
> Android: Handle touch events (by treating them as mouse events)

- Userland/Libraries/LibJS/Bytecode/CommonImplementations.h
- Userland/Libraries/LibJS/Bytecode/Executable.h
This allows global `let` and `const` variable accesses to be cached
by the GetGlobal instruction, and works even when the access is in a
different translation unit from the declaration.
Knocks a ~10% item off the profile on https://ventrella.com/Clusters/
> LibJS: Cache environment index for global declarative bindings

- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
The style of input and textarea elements is now invalidated when focus is changed to a new element. This ensures any `:focus` selectors are applied correctly.
Fixes #471
> LibWeb: Invalidate input element style on focus change

- Tests/LibWeb/Text/expected/HTML/WindowOrWorkerGlobalScope-reportError.txt
- Tests/LibWeb/Text/input/HTML/WindowOrWorkerGlobalScope-reportError.html
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Previously, when `WindowOrWorkerGlobalScope.reportError()` was called the `filename` property of the dispatched error event was blank. It is now populated with the full path of the active script.
> LibWeb: Populate filename in `WindowOrWorkerGlobalScope.reportError()`

- Tests/LibWeb/Layout/expected/dialog-open-modal.txt
- Tests/LibWeb/Layout/expected/dialog-open-non-modal.txt
- Tests/LibWeb/Layout/expected/top-layer.txt
- Tests/LibWeb/Layout/input/dialog-open-modal.html
- Tests/LibWeb/Layout/input/dialog-open-non-modal.html
- Userland/Libraries/LibWeb/CSS/PseudoClasses.json
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/HTML/HTMLDialogElement.h
Adds the `:modal` pseudo class which matches dialogs opened with showModal().
Passes all but 1 assertions within the first subtest of https://wpt.live/css/selectors/modal-pseudo-class.html
That final assertion seems to be failing due to a spec bug: https://github.com/whatwg/html/issues/10452
I'll do a follow up PR to fix this in Ladybird once the spec is updated.
> LibWeb: Implement :modal pseudo class

- Meta/generate-libwasm-spec-test.py
- Tests/LibWasm/test-wasm.cpp
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Operators.h
All tests related to floats now fully pass!
There are now 11 non-SIMD tests that don't pass on my machine.
> LibWasm: Make float operations fully spec-compliant

- Userland/Libraries/LibWeb/CSS/Default.css
Instead of using fixed arbitrary colors for the background of the bar, 
AccentColor and Background are now used.
> LibWeb: Use system colors for input type range and progress as default

- CMakeLists.txt
Hello,
In the documentation, it says
```markdown
`ninja check-style`: Runs the same linters the CI does to verify project style on changed files.
```
In `CMakeLists.txt`, `check-style` target will run `check-style.sh`.
```cmake
add_custom_target(check-style
COMMAND "${ladybird_SOURCE_DIR}/Meta/check-style.sh"
USES_TERMINAL
)
```
But we only have `check-style.py` in `${ladybird_SOURCE_DIR}/Meta`.
Thanks.
> Meta: CMakeLists invoke check_style.py

- Ladybird/Qt/Tab.cpp
This prevents the user being able to shrink the window to the point that the location bar and other controls are no longer visible.
Before:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/7e002ee6-7515-46b8-9647-858d8b8add1e
After:
https://github.com/LadybirdBrowser/ladybird/assets/2817754/5d18c1ef-45a3-4bd1-a687-bbe840205758
> UI/Qt: Set a minimum size policy for the navigation control toolbar

- .clangd
- Documentation/EmacsConfiguration.md
- Documentation/HelixConfiguration.md
- Documentation/NvimConfiguration.md
- Documentation/VSCodeConfiguration.md
This change adds a `.clangd` file in the repo root, for the (initial) purpose of specifying the `CompilationDatabase` path — so that clangd (and people’s editors) can find and use the `Build/ladybird/compile_commands.json` file
Otherwise (without this change) nobody’s editors will actually be able to use all the clangd-provided features — because clangd by default just looks directly (non-recursively) only in the source directory (repo root) — and not within the `Build` directory at all.
Currently, people can work around this by symlinking the `Build/ladybird/compile_commands.json` file into the repo root. But it’d be more convenient for developer ergonomics if they didn’t have to do that, and if everything would instead “Just Work” for them out of the box.
> Meta: Add .clangd config file (with CompilationDatabase path specified)

- Tests/LibWasm/test-wasm.cpp
- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Userland/Libraries/LibWasm/Types.h
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
As far as I know, they're not in the spec and don't serve any purposes in the internals of LibWasm.
> LibWasm: Remove `Wasm::ValueType::Kind::Null*` variants

- AK/ConstrainedStream.h
- Userland/Libraries/LibWasm/Parser/Parser.cpp
`custom.wast` now fully passes!
> LibWasm: Error when parsed section lengths are invalidated

- Tests/LibWasm/test-wasm.cpp
- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Userland/Libraries/LibWasm/WASI/Wasi.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
- Userland/Utilities/wasm.cpp
Resolves the FIXME. This also requires that host functions have names. We could make it an optional parameter or something, but I figured that the information is important enough. Let me know if that's an okay assumption.
Also, is this something we should test for?
See the relevant spec section: https://webassembly.github.io/spec/js-api/index.html#name-of-the-webassembly-function
> LibWasm: Give names to functions exported to JS via `ref.func`

- .github/workflows/libjs-test262.yml
- Documentation/BuildInstructionsLadybird.md
This is required for `libavif`.
> CI+Documentation: List `nasm` as a required package, install it on the test262 runner

- AK/Assertions.cpp
- AK/Assertions.h
- Userland/Libraries/LibJS/Heap/GCPtr.h
- Userland/Libraries/LibJS/Runtime/Value.h
Let's move towards using these for things that are "nice to check in
debug builds, but not essential".
This PR adds `ASSERT()` and `ASSERT_NOT_REACHED()` and uses them for a handful of things in LibJS that were hot in profiles (~5%) without adding justifiable value.
> AK+LibJS: Add ASSERT() and ASSERT_NOT_REACHED() for debug-only assertions

- Ladybird/Qt/Application.cpp
- Ladybird/Qt/Application.h
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/RequestManagerQt.cpp
- Ladybird/Qt/RequestManagerQt.h
- Ladybird/Qt/TaskManagerWindow.cpp
- Ladybird/Qt/TaskManagerWindow.h
- Ladybird/WebContent/main.cpp
- Ladybird/WebWorker/main.cpp
This change adds a `--certificate` option to both WebContent and WebWorker, which allows one or more custom root certificate paths to be specified. Certificates are then loaded from these paths when Qt networking is used.
This allows WPT tests that require a https connection to be run locally with Qt networking.
> WebContent+WebWorker: Use custom certificate paths with Qt networking

- .github/workflows/lagom-template.yml
- Meta/Lagom/Tools/CMakeLists.txt
- Tests/LibAudio/CMakeLists.txt
- Tests/LibCompress/CMakeLists.txt
- Tests/LibCore/CMakeLists.txt
- Tests/LibGfx/CMakeLists.txt
- Tests/LibJS/CMakeLists.txt
- Tests/LibWasm/CMakeLists.txt
- Tests/LibWeb/CMakeLists.txt
These files are not needed in the final installation.
Generators and test binaries are only used during the compilation process.
> Everywhere: Don't install code generators and test binaries

- Tests/LibWeb/Ref/reference/webkit-text-fill-color.html
- Tests/LibWeb/Ref/webkit-text-fill-color.html
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
As defined in https://compat.spec.whatwg.org/#the-webkit-text-fill-color
-webkit-text-fill-color overrides the color of text only
> LibWeb: Add support for -webkit-text-fill-color

- Userland/Libraries/LibWeb/CSS/Default.css
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Previously the entire slider track was colored.
Now only the lower part of the slider track (left side of the thumb) is colored.
Chrome and Firefox do the same.
Implementation note:
I called the new shadow dom element "-moz-range-progress", because I have not found the corresponding name with the "-webkit" prefix.
Screenshot Ladybird before:
Screenshot Ladybird after:
Screenshot Chrome:
Screenshot Firefox:
> LibWeb: Harmonize look of range input element

- Userland/Libraries/LibGfx/GradientPainting.cpp
- Userland/Libraries/LibGfx/Gradients.h
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
Skia does not have built-in support for gradient transition hints. So instead of adding custom gradient painting, now we do the same thing as other engines and preprocess color stops by replacing transition hints with a bunch of points lying between adjacent color stops and calculated using non-linear formula from the spec. As a result we get visually close enough rendering we would get by applying spec-formula individually to each point of a gradient.
> LibGfx+LibWeb: Support CSS gradient "transition hints" in Skia painter

- Userland/Libraries/LibJS/Runtime/Value.h
On PowerPC 64 pointers can use all 64 bits, however by convention on Linux user-space addresses use only the lower 43 bits.
I'm not 100% certain that the masking off of the 16 high bits is the proper solution, but it matches the rest of the LibJS code which assumes pointers only use the lower 48 bits.
https://www.kernel.org/doc/ols/2001/ppc64.pdf
> LibJS: Implement extract_pointer_bits for ppc64

- Tests/LibWeb/Layout/expected/abspos-box-bottom-with-max-height.txt
- Tests/LibWeb/Layout/input/abspos-box-bottom-with-max-height.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
This bug was found in issue https://github.com/LadybirdBrowser/ladybird/issues/325
The function for solving absolute lengths was using the unconstrained height. This would cause the computed value to differ from the final height used, and create a gap underneath.
> LibWeb: When solving absolute lengths, use min max constrained height

- Userland/Libraries/LibWeb/Layout/Viewport.cpp
This change makes find-in-page ignore content that’s been added to the document using CSS `::after` or `::before` pseudo-elements. Ignoring such pseudo-element content for find-in-page matches the behavior in Chrome and Safari (though not in Firefox).
Otherwise, without this change, find-in-page doesn’t ignore the pseudo-element content, and we instead crash in `DOM::Range::common_ancestor_container` after hitting an assert, due to the start container and end container for the matched range not having a common ancestor.
Note: <s>I’ve not found any</s> [There is no spec that normatively defines the required behavior for find-in-page with pseudo-element content](https://matrixlogs.bakkot.com/WHATWG/2024-07-09#L1). But since there are two existing implementations which ignore it — versus one …
> LibWeb: Fix handling of find-in-page with pseudo-element content

- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Operators.h
`simd_bitwise.wast` fully passes.
> LibWasm: Implement SIMD bitwise operations

- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
Single-type blocktypes previously gave loop labels an arity of 1, even though they're shorthand for `[] -> [T]`. This makes `label.wast` fully pass.
> LibWasm: Fix loop arity for single-type blocktypes

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Userland/Libraries/LibWeb/WebAssembly/Memory.cpp
After a `memory.grow`, the type of the memory instance should be updated so potential memory imports on the boundary are unlinkable. This makes `import.wast` basically fully pass (the only one that fails tests that we don't support multiple memories, because multi-memory isn't in the main spec yet, but we support them anyway).
> LibWasm: Make `memory.grow` grow the memory's type

- Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp
This workaround for #75 is inspired by  https://github.com/LadybirdBrowser/ladybird/issues/75#issuecomment-2219877451
> LibGfx: Add workaround for un-parseable OpenType font family names

- Tests/LibWeb/Text/expected/Streams/ReadableStreamBYOBReader-read-min.txt
- Tests/LibWeb/Text/input/Streams/ReadableStreamBYOBReader-read-min.html
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/AbstractOperations.h
- Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.cpp
- Userland/Libraries/LibWeb/Streams/ReadableByteStreamController.h
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.h
- Userland/Libraries/LibWeb/Streams/ReadableStreamBYOBReader.idl
When the min option is given the read will only be fulfilled when there are min or more elements available in the readable byte stream.
When the min option is not given the default value for min is 1.
> LibWeb: Implement min option for ReadableStreamBYOBReader.read()

- Tests/LibWeb/Layout/expected/input-range.txt
- Tests/LibWeb/Layout/input/input-range.html
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Previously the input element was displayed with value 0, when no value was set in the HTML. Now it uses `value_sanitization_algorithm()`, which will calculate the default value.
In `value_sanitization_algorithm()` there was a logical mistake/typo. The comment from the spec says "unless the maximum is less than the minimum".
The added layout test would fail without the code changes. Fixes #520
> LibWeb: Use correct default value for <input type=range>

- Userland/Libraries/LibWeb/UIEvents/FocusEvent.cpp
This fixes some WPT failures caused by the "view" parameter not being initialized from the property bag.
> LibWeb: pass event_init to base class constructor in FocusEvent

- README.md
Issue: #575 
The first link to the main website of the projet in the README was still refering to the old URL https://ladybird.dev, instead of https://ladybird.org. This has been updated.
> Readme: Change ladybird.dev to ladybird.org in README

- .github/workflows/nightly-android.yml
- The steps `Install NDK` and `Start Android Emulator` were broken, as `tools/bin/sdkmanager` and `tools/bin/avdmanager` contain strange bugs. Changed to use `cmdline-tools/latest/bin/sdkmanager` and `cmdline-tools/latest/bin/avdmanager`
- Maybe we will make the workflow upload the built apk in the future?
> CI: Fixed the broken steps in nightly-android

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
- Userland/Libraries/LibWeb/UIEvents/WheelEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/WheelEvent.h
These methods were overriding properties specified by the EventInit property bags in the constructor for WheelEvent and MouseEvent.
They appear to be legacy code and no longer relevant, as they would have been used for ensuring natively dispatched events had the correct properties --- This is now done in separate create methods, such as MouseEvent::create_from_platform_event.
This fixes a couple WPT failures (e.g. in /dom/events/Event-subclasses-constructors.html)
> LibWeb: Remove set_event_characteristics()

- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
This aligns AO transform_stream_error_writable_and_unblock_write() with the spec.
No functional change is introduced by this amendment.
This change was introduced in https://github.com/whatwg/streams/commit/007d729f1476f7f1ea34731ba9bd2becb702117e and should have been part of #95.
> LibWeb: Align transform_stream_error_writable_and_unblock_write w/ spec

- Meta/generate-libwasm-spec-test.py
- Tests/LibWasm/test-wasm.cpp
`nan:arithmetic` and `nan:canonical` are indeterminate in the sense that the allowed bit patterns represent a set of `NaN`s. We now properly check these bit patterns in the tests, both scalar floats and vectors containing floats.
> LibWasm: Check for correct NaN bit patterns in tests

- Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
Previously the validator put a `v128` on the stack, which is not what the spec defines.
> LibWasm: Validate stack correctly in `v128_store*_lane` instructions

- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
This makes all `simd_f*.wast` pass!
> LibWasm: Make SIMD float min/max operations binary ops

- Tests/LibWeb/Layout/expected/input-as-button-align-center.txt
- Tests/LibWeb/Layout/expected/input-as-button-shrink-to-fit.txt
- Userland/Libraries/LibWeb/CSS/Default.css
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
User interaction events are now no longer dispatched to form associated elements if they are disabled. Disabled form associated elements also no longer receive focus when clicked.
I've also added some styling to disabled buttons, so that you can tell when a button is disabled
I had trouble coming up with a reliable test for these changes. It's not clear how to test for an event that doesn't fire without having some arbitrary timeout.
With these changes the "Projects" buttons in [Universal paperclips](https://www.decisionproblem.com/paperclips/) now behave as expected:
> LibWeb: Don't dispatch click events to disabled FormAssociatedElements

- Tests/LibWeb/Text/expected/DOM/Node-normalize.txt
- Tests/LibWeb/Text/input/DOM/Node-normalize.html
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/DOM/Node.idl
This method puts the given node and all of its sub-tree into a normalized form. A normalized sub-tree has no empty text nodes and no adjacent text nodes.
This method is used by the html5lib HTML parsing tests in: http://wpt.live/html/syntax/parsing/, so this change increases our pass rate for these tests.
The relevant WPT test for this method is: https://wpt.live/dom/nodes/Node-normalize.html, which now passes.
> LibWeb: Implement `Node.normalize()`

- Userland/Libraries/LibWasm/AbstractMachine/Operators.h
All `simd_*_cmp.wast` now fully pass!
> LibWasm: Fix sign issues in SIMD cmp ops

- Ladybird/Qt/Tab.cpp
This resolves a bug where if you opened a link in a new tab and quickly went back to the original, the navigation buttons would update for the new page shortly after.
> Ladybird/Qt: Only update navigation buttons for current tab

- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Previously, the scrollbar thumbs were (almost) invisible, when the page background color was similar to the scrollbar thumb color (DarkGray).
Now, in addition to the filled rounded rectangle, the scrollbar thumbs are painted with a 1px solid LightGrey border. On a white or light color background the border stays invisible.
Screenshot before:
Screenshots after:
> LibWeb: Make scrollbar thumbs visible on dark background

- Meta/generate-libwasm-spec-test.py
Since we support the multi-memory proposal, we should skip tests that validate that we have only one memory. Once multi-memory gets included in the main WebAssembly specification (and the testsuite is updated), we can revert this commit.
> LibWasm: Ignore tests that check that we don't support 2+ memories

- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Operators.h
With this we pass an additional ~2100 tests.
There's still some test cases in the iNxM tests that fail with this PR, but they are somewhat weird.
---
I checked out @Enverbalalic's [original PR](https://github.com/LadybirdBrowser/ladybird/pull/159) to see if I could help with the UBSAN issue (since I ran into similar issues with some other Wasm instructions) and I talked with them about it. I'm now listed as a co-author to Enver's original commit.
> LibWasm: Implement most of iNxM SIMD operations

- Userland/Libraries/LibWebView/URL.cpp
Previously, the presence of surrounding whitespace would give file paths the `https` schema instead of the `file` schema, making navigation unsuccessful.
> LibWebView: Trim whitespace when sanitizing file paths

- Meta/ladybird.sh
On Mac, a very old bash is installed. 
In `ladybird.sh`, `declare -A` is used, but this does not work on old bash version.
```console
$/bin/bash Meta/ladybird.sh run ladybird
Meta/ladybird.sh: line 104: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```
In this PR, instead of using an associative array, I use case statement to determine $BUID_DIR. This is POSIX compatible and would work across several platforms.
patched version result:
```console
/bin/bash Meta/ladybird.sh run ladybird
~/ghq/github.com/LadybirdBrowser/ladybird/Toolchain/Tarballs ~/ghq/github.com/LadybirdBrowser/ladybird/Toolchain
ninja: Entering directory `/Users/taro3/ghq/github.com/LadybirdBrowser/ladybird/Build/ladybird'
[0/2] Re-checking globbed directories...
ninja: no work to …
```
> Meta: Make ladybird.sh old bash compatible

- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
All bitmaps passed to Skia during rendering are not supposed to be mutated.
> LibWeb: Mark bitmaps passed to Skia as immutable

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoClass.cpp
- Tests/LibWeb/Ref/css-has-compound.html
- Tests/LibWeb/Ref/css-has-descendant.html
- Tests/LibWeb/Ref/css-has-direct-child.html
- Tests/LibWeb/Ref/css-has-next-sibling.html
- Tests/LibWeb/Ref/css-has-subsequent-sibling.html
- Tests/LibWeb/Ref/css-nested-has.html
- Tests/LibWeb/Ref/css-pseudo-element-in-has.html
- Tests/LibWeb/Ref/reference/css-has-compound.html
- Tests/LibWeb/Ref/reference/css-has-descendant.html
- Tests/LibWeb/Ref/reference/css-has-direct-child.html
- Tests/LibWeb/Ref/reference/css-has-next-sibling.html
- Tests/LibWeb/Ref/reference/css-has-subsequent-sibling.html
- Tests/LibWeb/Ref/reference/css-nested-has.html
- Tests/LibWeb/Ref/reference/css-pseudo-element-in-has.html
- Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
- Userland/Libraries/LibWeb/CSS/PseudoClasses.json
- Userland/Libraries/LibWeb/CSS/Selector.cpp
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/CSS/SelectorEngine.h
- Userland/Libraries/LibWeb/Dump.cpp
See https://drafts.csswg.org/selectors-4/#relational.
> LibWeb: Implement the `:has()` pseudo-class

- Tests/LibWeb/Ref/reference/webkit-box-shadow.html
- Tests/LibWeb/Ref/webkit-box-shadow.html
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Includes most of the properties from the "legacy name aliases" specified by https://compat.spec.whatwg.org/, excluding -webkit-background-size and any whose alias isn't currently supported by Ladybird
> LibWeb: Add more legacy -webkit- aliases

- Userland/Libraries/LibWeb/CSS/Default.css
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLProgressElement.h
Fixes #466 and #556
Supersedes https://github.com/LadybirdBrowser/ladybird/pull/564 
Screenshot before:
Screenshot after:
> LibWeb: Support `accent-color` for range input and progress element

- Tests/LibWasm/test-wasm.cpp
-Wmissing-declarations would complain about these.
> Tests/LibWasm: Mark two static functions "static"

- Tests/LibWeb/WPT/run.sh
--enable-qt-networking doesn't exist on the AppKit chrome
> Tests: Drop --enable-qt-networking arg in WPT/run.sh

- Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp
- Userland/Services/RequestServer/ConnectionFromClient.cpp
Ultimately it's RequestServer who knows which kind of encodings it can handle and decompress, so let's have it set the Accept-Encoding.
> LibWeb+RequestServer: Let RequestServer set HTTP Accept-Encoding header

- Documentation/BuildInstructionsLadybird.md
- Meta/lint-clang-format.sh
- Meta/lint-gn.sh
- Meta/lint-prettier.sh
- Meta/lint-python.sh
- Meta/lint-shell-scripts.sh
This change makes all the pre-commit CI scripts runnable under Bash 3.2 — by replacing `mapfile` invocations in them with code that first explicitly creates an array, and then uses a while loop to populate the array.
Otherwise, without this change, the scripts all fail to run under Bash 3.2 — due to lack of support for `mapfile`.
Note: Each of these `mapfile` cases is in the `then` part of an if-then-else block in which the existing code in the `else` part is first explicitly creating an array, and then populating in in a loop. So the change in this PR is arguably making the code somewhat more consistent. (Though maybe that’s just a rationalization…)
Fixes https://github.com/LadybirdBrowser/ladybird/issues/283
> Meta: Make all pre-commit CI scripts work with Bash 3.2

- Meta/check-debug-flags.sh
This change updates the `Meta/check-debug-flags.sh` script to avoid an apparent Bach 3.2 parser bug. Specifically, it takes a comment and some code of a process substitution and moves it into a separate function.
Otherwise, without this change, trying to run the `check-debug-flags.sh` script with Bash 3.2 fails with the following error:
```
line 39: bad substitution: no closing `)' in <(
```
...apparently because Bash 3.2 chokes on the comment (and doesn’t choke if the comment is completely removed).
Relates to https://github.com/LadybirdBrowser/ladybird/issues/283
> Meta: Make check-debug-flags.sh runnable in Bash 3.2

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Tests/loops/for-scopes.js
Implement for [CreatePerIterationEnvironment](https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-createperiterationenvironment) for 'for' loops per the Ecma Standard. This ensures each iteration of a 'for' loop has its own lexical environment so that variables declared in the loop are scoped to the current iteration (i.e ensures `let` variables are now captured by value as described in #602). 
Diffing the results of the test262 suite against the current master branch(`5eeb5eb36e92693b01f88a2dcba5c3756ebb604d`) produces:
```bash
venv ❯ python3 per_file_result_diff.py -o original -n updated
Duration:
+6.77s
Summary:
Diff Tests:
+7 ✅    -7 ❌
Diff Tests:
test/language/statements/for/scope-body-lex-boundary.js …
```
> LibJS: Implement CreatePerIterationEnvironment for 'for' statements

- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
Each item in clip_paths represents a glyph run, and applying them as a clip in intersection mode one by one results in an empty clip. Instead, now all clip paths are joined and applied as a clip together.
This change fixes rendering of "background-clip: text" when an element has more than one glyph run.
Fixed ref-test: Tests/LibWeb/Ref/css-background-clip-text.html
> LibWeb: Join text clip paths before application in Skia painter

- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
Choose a better name for private members which were added in https://github.com/LadybirdBrowser/ladybird/pull/513
> LibWeb: Rename HTMLInputElement members related to range shadow tree

- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/CSS/StyleValues/StringStyleValue.h
We already have a FlyString of its value from parsing, and most users want a FlyString from it, so let's use that instead of converting and forwards.
The two users that did want a String are:
- Quotes, which make sense as FlyString instead, so I've converted that.
- Animation names, which should probably be FlyString too, but the code also allows for other kinds of StyleValue, and I don't want to dive into this right now to figure out if that's needed or not.
Another user was this unused and incorrect-looking `StyleProperties::grid_area()` method, so I've just removed that.
> LibWeb/CSS: Make StringStyleValue hold a FlyString

- Ladybird/WebContent/main.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
Enforce the use of the CPU backend in test mode to ensure that ref-tests produce consistent results across different computers, as this consistency cannot be achieved with the GPU backend.
> Ladybird+LibWeb+WebContent: Always use Skia CPU backend in tests mode

- AK/Assertions.h
NDEBUG is defined in release builds. So we want to enable the ASSERT macro when it *isn't* defined.
> AK: Enable ASSERT in debug builds only

- Tests/LibWeb/WPT/run.sh
The change causes `Tests/LibWeb/WPT/run.sh` to run an arbitrary subset of tests you give it as arguments. If you don’t specify any arguments, it has the same behavior as it does without this patch: It just runs an explicit subset of test names hardcoded into the script.
Otherwise without this change, `Tests/LibWeb/WPT/run.sh` doesn’t have the ability to run any tests other than the explicit subset of test names hardcoded into the script
> Tests: Enable WPT/run.sh to run an arbitrary subset of tests

- AK/BitCast.h
- AK/SIMD.h
- AK/SIMDExtras.h
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Operators.h
(cherry picked from commit 1b8fd5c35afda8f797f1e8a39c332fa14950006e)
cc @Hendiadyoin1.
> AK: Add generic SIMD shuffle/reverse functions

- Userland/Libraries/LibJS/Runtime/VM.h
The JS::Error types all store their exception messages as a String. So by using ByteString, we hit the StringView constructor, and end up allocating the same string twice.
> LibJS: Create exception messages as Strings

- Tests/LibWeb/Layout/expected/grid/1fr-1000px.txt
- Tests/LibWeb/Layout/input/grid/1fr-1000px.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Change min track sizing function to be "auto" when flex size is specified.
- Never check if min track sizing funciton is flexible, because only max is allowed to be flexible.
- Address FIXME in automatic_minimum_size to avoid regressions after making two fixes mentioned above.
> LibWeb: Fix flexible track sizing in GFC

- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
This change is needed to match behavior of default Gfx::Painter.
Fixes Tests/LibWeb/Ref/text-shadow.html
> LibWeb: Use `blur_radius / 2` as sigma to blur text shadow using Skia

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Userland/Libraries/LibWeb/DOM/Node.idl
- Userland/Libraries/LibWeb/DOM/Text.idl
- Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl
- Userland/Libraries/LibWeb/HighResolutionTime/Performance.idl
- Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.h
- Userland/Libraries/LibWeb/UIEvents/KeyboardEvent.idl
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.idl
- Userland/Libraries/LibWeb/UIEvents/UIEvent.h
Work towards [GH-24168](https://github.com/SerenityOS/serenity/issues/24168).
| Interface | Name | Status |
| --- | --- | --- |
| Node | lookupPrefix | Stubbed |
| Node | lookupNamespaceURI | Stubbed |
| Node | isDefaultNamespace | Stubbed |
| Performance | toJSON | Implemented |
| HTMLTrackElement | NONE | Implemented |
| HTMLTrackElement | LOADING | Implemented |
| HTMLTrackElement | LOADED | Implemented |
| HTMLTrackElement | ERROR | Implemented |
| KeyboardEvent | initKeyboardEvent | Implemented |
| MouseEvent | initMouseEvent | Implemented |
| Text | wholeText | Stubbed |
> LibWeb: Stub/implement some missing attributes/functions

- AK/Assertions.h
- Ladybird/AppKit/Application/EventLoopImplementation.mm
- Ladybird/Qt/EventLoopImplementationQt.cpp
- Ladybird/Qt/InspectorWidget.h
- Ladybird/Qt/TabBar.h
- Ladybird/Qt/main.cpp
- Ladybird/RequestServer/main.cpp
- Meta/CMake/common_compile_options.cmake
- Meta/Lagom/Fuzzers/CMakeLists.txt
- Meta/Lagom/Fuzzers/FuzzilliJs.cpp
- Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
- Meta/Lagom/Tools/CodeGenerators/LibTextCodec/GenerateEncodingIndexes.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/main.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateAriaRoles.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMathFunctions.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GeneratorUtil.h
- Tests/LibJS/test262-runner.cpp
- Userland/Libraries/LibCore/VulkanContext.cpp
- Userland/Libraries/LibGfx/ImageFormats/JPEGWriter.cpp
- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Userland/Libraries/LibWeb/WebIDL/Tracing.h
These used to be enabled in `serenity_compile_options.cmake` for Serenity builds and were removed in https://github.com/LadybirdBrowser/ladybird/commit/9b05fb98f3c742e66b70a661952f0c601e8437c6. This is a slightly more conservative subset of those, with ones that are enabled by default omitted.
This should prevent our code quality regressing in the long run.
If no header includes the prototype of a function, then it cannot be used from outside the translation unit it was defined in. In that case, it should be marked as `static`, in order to avoid possible ODR problems, unnecessary exported symbols, and allow the compiler to better optimize those.
If this warning triggers in a function defined in a header, `inline` needs to be added, otherwise if the header is included in more than one TU, …
> Harden compiler flags with more warnings and mitigations

- Documentation/BuildInstructionsLadybird.md
This PR adds the dependency `zlib-ng-compat-static` which is required for building on Fedora.
> Documentation: Add missing Fedora dependency

- Tests/LibWeb/Layout/expected/grid/define-area-using-line-names.txt
- Tests/LibWeb/Layout/input/grid/define-area-using-line-names.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Areas are disassembled into boundary lines on `build_grid_areas()` step,
so we can always use them to find grid item's position during placement.
This way we support both ways to define area: `grid-template-areas` and
implicitly using `-start` and `-end` boundary line names.
> LibWeb: Change grid item placement to look for area by boundary lines

- Tests/LibWeb/Text/expected/DOM/Node-isDefaultNamespace.txt
- Tests/LibWeb/Text/expected/DOM/Node-lookupNamespaceURI.txt
- Tests/LibWeb/Text/input/DOM/Node-isDefaultNamespace.html
- Tests/LibWeb/Text/input/DOM/Node-lookupNamespaceURI.html
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/DOM/Node.idl
This PR implements `Node.lookupNamespaceURI()` and `Node.isDefaultNamespace()`. See individual commits for details.
All subtests of the relevant WPT test now pass: http://wpt.live/dom/nodes/Node-lookupNamespaceURI.html
> LibWeb: Add 2 missing methods to `DOM::Node`

- CMakeLists.txt
- Documentation/VSCodeConfiguration.md
- Meta/CMake/vcpkg/base-triplets/arm64-linux.cmake
- Meta/CMake/vcpkg/base-triplets/arm64-osx.cmake
- Meta/CMake/vcpkg/base-triplets/base.cmake
- Meta/CMake/vcpkg/base-triplets/x64-linux.cmake
- Meta/CMake/vcpkg/base-triplets/x64-osx.cmake
- Meta/CMake/vcpkg/generate_vcpkg_toolchain_variables.cmake
Override the vcpkg/scripts/detect_compiler behavior of always pulling
$CC and $CXX at the time that vcpkg install is determined to need called
by forcing $ENV{CXX} and $ENV{CC} to our CMake-determined compiler.
This prevents strange behavior such as running the following:
./Meta/ladybird.sh run
make changes...
ninja -C Build/ladybird
Where the second build step would be run without CC or CXX set in the
environment, causing a total cache miss from vcpkg and a full rebuild.
It also helps prevent full rebuilds when an IDE passes a slightly
different compiler to the build step than ladybird.sh.
> CMake: Force vcpkg to use CMAKE_CXX_COMPILER as specified to CMake

- Userland/Libraries/LibJS/Runtime/Intrinsics.cpp
- Userland/Libraries/LibJS/Runtime/Iterator.cpp
- Userland/Libraries/LibJS/Runtime/Iterator.h
- Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp
- Userland/Libraries/LibJS/Runtime/IteratorPrototype.h
- Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.@@toStringTag.js
- Userland/Libraries/LibJS/Tests/builtins/Iterator/Iterator.prototype.constructor.js
The spec oddly allows *setting* these on non built-in Iterator objects.
test262 diff:
```
Diff Tests:
+4 ✅    -4 ❌
Diff Tests:
test/built-ins/Iterator/prototype/Symbol.toStringTag/prop-desc.js    ❌ -> ✅
test/built-ins/Iterator/prototype/Symbol.toStringTag/weird-setter.js ❌ -> ✅
test/built-ins/Iterator/prototype/constructor/prop-desc.js           ❌ -> ✅
test/built-ins/Iterator/prototype/constructor/weird-setter.js        ❌ -> ✅
```
We now pass all `Iterator` test262 tests:
```
test/built-ins/Iterator    380/380   (100.00%) [ ✅ 380   ]
```
> LibJS: Implement `Iterator.prototype [ @@toStringTag ]` and `Iterator.prototype.constructor` according to spec 

- Base/res/ladybird/inspector.js
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/EventDispatcher.cpp
- Userland/Libraries/LibWeb/DOM/Utils.h
Now keep a track of the DOM nodes which are actually visible in the Inspector, and allow the user to navigate the tree using the keyboard.
>  LibWebView: Add keyboard navigation to the Inspector

- AK/Endian.h
- AK/String.cpp
- AK/Utf16View.cpp
- AK/Utf16View.h
- Tests/AK/TestUtf16.cpp
- Tests/LibTextCodec/TestTextDecoders.cpp
- Userland/Libraries/LibTextCodec/Decoder.cpp
Follow-up to #674 
This allows LibTextCodec to make use of simdutf, and also reduces the number of places with manual UTF-16 implementations. To do so, we must first support non-native endianness in `Utf16View`.
> AK+LibTextCodec: Use AK facilities to validate and convert UTF-16 to UTF-8 

- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
Just removing some dead code in `BytecodeInterpreter` and removing some memory-related checks that don't need because of validation.
> LibWasm: Some minor cleanups

- Userland/Libraries/LibWeb/DOM/Utils.h
GCC 14 emits a warning when an always succeeding `dynamic_cast`'s return value is compared to NULL inside the `AK::is<T>(U)` template when `T` == `U`.
While warning on tautological `is` calls seems useful, it's a bit awkward when it comes from a function template where the cast may fail in some instantiation. There is a GCC bug open for it: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115664
Work around the warning by performing the algorithm on the base type (`EventTarget`), with a wrapper that casts it to the more specialized input type.
> LibWeb/DOM: Work around GCC 14 warning on always true `is<T>()`

- Tests/LibWeb/Text/expected/DOM/Node-isEqualNode.txt
- Tests/LibWeb/Text/input/DOM/Node-isEqualNode.html
- Userland/Libraries/LibWeb/DOM/DocumentType.idl
- Userland/Libraries/LibWeb/DOM/Node.cpp
This PR fixes a couple of issues that I found in `DOM::Node`, while investigating various WPT failures.
Fixes the following WPT tests:
http://wpt.live/dom/nodes/Node-isEqualNode.html
http://wpt.live/dom/nodes/Node-insertBefore.html
http://wpt.live/dom/nodes/ParentNode-append.html
http://wpt.live/dom/nodes/ParentNode-replaceChildren.html
> LibWeb: An assortment of fixes for `DOM::Node`

- .github/workflows/notes-push.yml
This change, for each commit pushed/merged to master:
- causes new git Notes with GitHub PR/issue/reviewer/author links to be auto-generated for that commit
- pushes the updated `refs/notes/commits` tree+references back to the repo
> CI: Add notes-push.yml, for updating commit Notes on push to master

- AK/ByteBuffer.h
- AK/Forward.h
- AK/String.cpp
- AK/String.h
- AK/StringBase.cpp
- AK/StringBase.h
- AK/StringBuilder.cpp
- AK/StringBuilder.h
- AK/StringData.h
- Userland/Libraries/LibJS/Runtime/PrimitiveString.cpp
This makes 2 changes to improve rope string resolution:
1. Allow `StringBuilder` to transfer ownership of its string buffer to `String`, so we don't have to re-allocate and copy the string data
2. Allocate the resolved rope's `StringBuilder` capacity up front
For a ballpark idea of how we perform relative to other rope string implementations, I compared us to [fatal's rope string](https://github.com/facebook/fatal/blob/main/fatal/string/rope.h).
<details>
<summary>Benchmark code</summary><p>
```c++
static auto vm = JS::VM::create().release_value();
static auto create_libjs_rope()
{
auto string = JS::PrimitiveString::create(vm, MUST(String::repeated("abcdef"_string, 200)));
auto rope = JS::PrimitiveString::create(vm, string, string);
for (size_t i = 0; i < 1'000'000; ++i)
rope = …
```
> AK+LibJS: Performance improvements for resolving large rope strings

- .github/workflows/notes-push.yml
This change makes the `notes-push.yml`·workflow fetch the entire history on each push, rather than just the one HEAD commit it otherwise sees.
Because we push multiple commits from PR merges, `git-gloss` need access on each push to an arbitrary number of commits (however many commits were pushed in a PR that got merged). There’s no easy way from GH Actions to know how may commits got pushed at the same time. So we instead fetch the whole history.
> CI: Make the notes-push.yml workflow fetch the entire repo history

- Tests/LibWeb/Layout/expected/details-closed.txt
- Tests/LibWeb/Layout/expected/details-open.txt
- Tests/LibWeb/Layout/expected/details-summary-default-ua-style.txt
- Tests/LibWeb/Layout/input/details-summary-default-ua-style.html
- Userland/Libraries/LibWeb/CSS/Default.css
This is the expected behavior per the HTML spec. Fixes an issue where styling these elements wouldn't have the expected effect unless you also set the display property.
Visual progression on https://brave.com
Before:
After:
> LibWeb: Make details and summary elements display:block in the UA style

- Userland/Libraries/LibGfx/Font/OpenType/Tables.cpp
This change makes `OpenType::Name::string_for_id` handle fonts whose names are UTF-16-encoded (along with handling UTF-8-encoded names).
Otherwise, without this change, the existing code assumes the names are UTF-8-encoded, fails gracelessly if they’re not, and crashes.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/75
> LibGfx: Handle UTF-16-encoded OpenType font names

- Userland/Libraries/LibTextCodec/Decoder.cpp
This way, we still perform UTF-8 validation, but don't go through the slow generic code path that rebuilds the decoded string one code point at a time.
This was a bottleneck when loading a canned copy of reddit.com, which ended up being ~120 MiB large.
- Time spent decoding UTF-8 before this change: 1192 ms
- Time spent decoding UTF-8 after this change:  154 ms
That's still a long time, but 7.7x faster is nothing to sneeze at! :^)
> LibTextCodec: Use String::from_utf8() when decoding UTF-8 to UTF-8

- Documentation/FAQ.md
People do ask… — e.g., new folks showing up on the Discord server — and the FAQ is a place we’re already pointing them to, so it seems like maybe an appropriate/useful place to have this too.
Anyway, for reviewers, here are some comments:
- Wording: I’m not wedded to any of the particular wording, so any and all reviewers should please feel free to directly commit any changes you want to this. But if you prefer to make commit suggestions (from the GitHub web UI), that’d be find too.
- LibJS: As currently written, the patch here doesn’t mention LibJS at all. Maybe it should, I dunno. But for now I intentionally omitted it in the interest of trying to keep things shorter/simpler — and since this is after all a FAQ… (That said, I think it’d also be fine to include it.)
> Documentation: Add a bit of history to the FAQ

- Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
- Userland/Libraries/LibWeb/HTML/History.idl
- Userland/Libraries/LibWeb/SVG/SVGLength.idl
- Userland/Libraries/LibWeb/SVG/SVGSymbolElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGSymbolElement.h
- Userland/Libraries/LibWeb/SVG/SVGSymbolElement.idl
Work towards [GH-24168](https://github.com/SerenityOS/serenity/issues/24168).
| Interface | Name | Status |
| --- | --- | --- |
| SVGSymbolElement | viewBox | Implemented |
| SVGSymbolElement | preserveAspectRatio | Stubbed |
| SVGLength | valueInSpecifiedUnits | Stubbed |
| SVGLength | valueAsString | Stubbed |
| SVGLength | newValueSpecifiedUnits | Stubbed |
| SVGLength | convertToSpecifiedUnits | Stubbed |
| HTMLImageElement | x | Stubbed |
| HTMLImageElement | y | Stubbed |
| History | scrollRestoration | Stubbed |
> LibWeb: Stub missing attributes in SVGLength & HTMLImageElement

- Tests/LibWeb/Text/expected/DOM/getElementById-multiple.txt
- Tests/LibWeb/Text/input/DOM/getElementById-multiple.html
- Userland/Libraries/LibWeb/DOM/NonElementParentNode.h
We had a const and non-const version of this function, with slightly different behavior (oops!)
This patch consolidates the implementations and keeps only the correct behavior in there.
Fixes an issue where comments were not collapsible on Hacker News.
> LibWeb: Make getElementById() always return first match in tree order

- .github/workflows/notes-push.yml
This should stop the "Push notes" job from failing on CI.
> CI: Use single quotes for a literal string in `notes-push.yml`

- Base/res/ladybird/inspector.css
- Base/res/ladybird/inspector.js
We currently display scroll bars for the JS console and its parent tab container. We want the console output to be separately scrollable from the tab content, but since both containers are scrollable, we end up with nested scroll bars. This also makes actually scrolling feel pretty awkward.
Prevent this by making the tab container non-scrollable when the JS console is shown.
Before:
After:
> LibWebView: Prevent displaying two scroll bars in the inspector console

- Tests/LibWeb/Layout/expected/svg-text-with-percentage-values.txt
- Tests/LibWeb/Layout/expected/svg/svg-line-with-percentage-values.txt
- Tests/LibWeb/Layout/input/svg-text-with-percentage-values.html
- Tests/LibWeb/Layout/input/svg/svg-line-with-percentage-values.html
- Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
- Userland/Libraries/LibWeb/SVG/SVGLineElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGLineElement.h
- Userland/Libraries/LibWeb/SVG/SVGTextPositioningElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGTextPositioningElement.h
Text element before:
After:
Line element before:
\<blank page\>
After:
> LibWeb: Support percentage values in SVG text/line element

- AK/String.cpp
- AK/Utf16View.cpp
- AK/Utf8View.cpp
- Tests/AK/TestUtf16.cpp
- Tests/AK/TestUtf8.cpp
The underlying CPU-specific instructions for validating UTF-16 strings behave differently for null inputs. Add an explicit check for this state for consistency.
Fixes #727
(@tcl3 or @jamierocks, can you try this patch on wikipedia and the unit test on your machines as well?)
> AK: Explicitly check for null data in Utf16View::validate

- Userland/Libraries/LibWeb/DOM/Document.cpp
Minor optimization to avoid looking up the navigable during a layout operation.
> LibWeb/DOM: Avoid repeated calls to Node::navigable

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/EventDispatcher.cpp
- Userland/Libraries/LibWeb/DOM/Utils.cpp
- Userland/Libraries/LibWeb/DOM/Utils.h
The templating is not necessary anywhere and was effectively just a cast
> LibWeb: Replace templated retarget function with a regular one

- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/Tab.cpp
Uses the tab bar's width to determine the location of the button. The button is hidden if the window is small enough
This is in reference to #252
QToolBar with a single action is used instead of just a QToolButton, there is an issue where the button is completely black when just using a button. If that is resolved, it could be used instead.
> UI/Qt: Move New Tab button in tab bar

- Ladybird/Qt/Icon.cpp
Ladybird now uses the correct theme colours when hovering over icons.
> Ladybird/Qt: Add missing filters for TVG icons

- Userland/Services/RequestServer/ConnectionFromClient.cpp
- Userland/Services/RequestServer/ConnectionFromClient.h
Previously we made one thread pool per ipc client, which is excessive and can eat up all the available fds very fast.
Fixes #760.
> RequestServer: Make the ThreadPool global

- Tests/LibWeb/Text/expected/DOM/getElementById-empty-string.txt
- Tests/LibWeb/Text/expected/DOM/getElementsByClassName-empty-string.txt
- Tests/LibWeb/Text/expected/DOM/getElementsName-empty-string.txt
- Tests/LibWeb/Text/input/DOM/getElementById-empty-string.html
- Tests/LibWeb/Text/input/DOM/getElementsByClassName-empty-string.html
- Tests/LibWeb/Text/input/DOM/getElementsName-empty-string.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Document.idl
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/ParentNode.cpp
- Userland/Libraries/LibWeb/DOM/ParentNode.h
This PR includes changes to align `document.getElementById()`, `document.getElementByClassName()` and `document.getElementByName()` with the specification.
See individual commits for details
Fixes the following WPT tests (and possibly others):
https://wpt.live/dom/nodes/Document-getElementById.html
https://wpt.live/html/dom/documents/dom-tree-accessors/document.getElementsByName/document.getElementsByName-interface.html
http://wpt.live/dom/nodes/getElementsByClassName-01.htm
http://wpt.live/dom/nodes/getElementsByClassName-02.htm
> LibWeb: A handful of fixes for some element querying methods

- Ladybird/AppKit/main.mm
- Ladybird/Qt/main.cpp
- Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
- Userland/Libraries/LibCore/System.cpp
- Userland/Libraries/LibCore/System.h
- Userland/Libraries/LibWebView/ChromeProcess.cpp
- Userland/Libraries/LibWebView/ChromeProcess.h
The default limit (at least on Linux) causes us to run out of file
descriptors at around 15 tabs. Increase this limit to 8k. This is a
rather arbitrary number, but matches the limit set by Chrome.
Fixes #760
> LibCore+LibWebView+UI: Raise the chrome process open file limit

- Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.idl
More work towards [GH-24168](https://github.com/SerenityOS/serenity/issues/24168) :)
Should knock many off https://idl-compare.pages.dev/.
> LibWeb/WebGL: Stub missing properties in WebGLRenderingContextBase

- Userland/Libraries/LibJS/Bytecode/Interpreter.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibJS/Runtime/Value.cpp
- Userland/Libraries/LibJS/Runtime/Value.h
The typeof operator has a very small set of possible resulting strings, so let's make it much faster by caching those strings on the VM.
~8x speed-up on this microbenchmark:
for (let i = 0; i < 10_000_000; ++i) {
typeof i;
}
> LibJS: Make `typeof` a lot faster by caching all possible results

- .github/workflows/notes-push.yml
It’s possible but unlikely that a push of generated notes back to the remote can fail with a message like
> [remote rejected] ... cannot > lock ref 'refs/notes/commits': is at f3648f50bb but expected 47686bf473
See https://github.com/LadybirdBrowser/ladybird/actions/runs/10054314539
So this change makes the call to “git push” for notes not return 0 even if it fails — because it’s not actually a fatal error when it happens, and not something we need to stop and fix. Instead, it fixes itself.
Specifically: If one CI job for a PR merge/push to master generates some notes but fails to push them to the origin, the notes don’t get dropped on the floor and lost.
Instead, the notes-generator tool looks at the entire history; and if it finds commits that don’t have notes — even if those commits …
> CI: Make notes-push workflow return zero even when “git push” fails

- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
In `PaintableBox::set_scroll_offset()` the scrollport size was measured by `content_size()` instead of `absolute_padding_box_rect()`.
Fixes #788
> LibWeb: Use absolute padding box to calculate max scroll offset

- Tests/LibWeb/Text/expected/canvas/invalid-font-property.txt
- Tests/LibWeb/Text/input/canvas/invalid-font-property.html
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.h
Checking that the string parsed for the `font` property is not enough, the spec also wants to rule out CSS-wide keywords like `inherit`. The simplest way to do so is to check if it's a ShorthandStyleValue, which also rules out use of `var()`; this matches other browsers' behaviour.
The newly-added test would previously crash, and now doesn't. :^)
> LibWeb: Check CanvasTextDrawingStyles.font assignment is valid

- Userland/Services/WebContent/PageClient.cpp
We don't want to set the intrinsic Console object's client to non-top- level clients, created for e.g. SVG elements or subframes. We also want to make sure the Console client is updated if the top-level document has changed.
Fixes #782
> WebContent: Limit the Console client to the top-level navigable client

- Tests/LibWeb/Layout/expected/host-pseudo-class-basic.txt
- Tests/LibWeb/Layout/input/host-pseudo-class-basic.html
- Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/CSS/SelectorEngine.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/ParentNode.cpp
The `:host` family of pseudo class selectors select the shadow host element when matching against a rule from within the element's shadow tree.
This is a bit convoluted due to the fact that the document-level `StyleComputer` keeps track of *all* style rules, and not just the document-level ones.
In the future, we should refactor style storage so that shadow roots have their own style scope, and we can simplify a lot of this.
Visual progression on many sites, for example https://reddit.com
Before:
After:
> LibWeb: Implement :host and :host(<compound-selector>) selector matching

- Ladybird/Qt/InspectorWidget.cpp
- Ladybird/Qt/WebContentView.h
> UI/Qt: Don't crash when launching Inspector with Qt networking enabled

- Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Userland/Libraries/LibJS/Tests/for-loop-per-iteration-env-bug.js
If the current block has already been terminated, we should just skip creating a per-iteration environment.
> LibJS: Fix crash in bytecode generator on https://twinings.co.uk/

- Userland/Libraries/LibWeb/Painting/DisplayList.cpp
- Userland/Libraries/LibWeb/Painting/DisplayList.h
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.h
CommandResult was needed by LibGfx display list player that could have failed to allocate a temporary bitmap for painting a stacking context with CSS transforms. This is no longer an issue with Skia painter, so we can delete CommandResult::SkipStackingContext handling path.
> LibWeb: Remove stacking context painting failure handling

- Userland/Services/WebContent/PageClient.cpp
This reverts commit 758f4887bc1a2bbbf111fb3bee120e491322ba32.
This commit was causing ASAN to complain about a use-after-poison, see https://github.com/LadybirdBrowser/ladybird/issues/809
> Revert "WebContent: Limit the Console client to the top-level navigable client"

- Userland/Libraries/LibWeb/Painting/DisplayList.cpp
- Userland/Libraries/LibWeb/Painting/DisplayList.h
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.h
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
Some steps that are no longer needed after LibGfx and LibAccelGfx painters are gone.
> LibWeb: Remove unused code from DisplayList and DisplayListPlayer

- Userland/Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
implement step 11 in the specification for [`construct the entry list`](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-the-form-data-set) in the html specs
> LibWeb: Bring 'construct_entry_list' closer to specs

- Userland/Libraries/LibWasm/Opcode.h
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Types.h
Instead of multiple loops and multiple vectors, parse Wasm expressions in a simple loop. This gets us from ~450ms to instantiate spidermonkey to ~280ms.
> LibWasm: Flatten instructions in one continuous loop during parsing

- Tests/LibWeb/Layout/expected/grid/fit-content-1.txt
- Tests/LibWeb/Layout/expected/grid/fit-content-2.txt
- Tests/LibWeb/Layout/input/grid/fit-content-1.html
- Tests/LibWeb/Layout/input/grid/fit-content-2.html
- Userland/Libraries/LibWeb/CSS/GridTrackSize.cpp
- Userland/Libraries/LibWeb/CSS/GridTrackSize.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.h
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Before([tweakers.net](https://tweakers.net)):
After:
Before(fit-content-2 test):
After:
> LibWeb: Support grid template function fit-content

- Tests/LibWeb/Text/expected/DOM/Document-createElementNS-uppercase.txt
- Tests/LibWeb/Text/input/DOM/Document-createElementNS-uppercase.html
- Userland/Libraries/LibWeb/DOM/ElementFactory.cpp
Previously, when creating a HTML element with `document.createElementNS()`  we would convert the given local name to lowercase before deciding which element type to return. We now no longer perform this lower case conversion, so if an uppercase local name is provided, an element of type `HTMLUnknownElement` will be returned. This aligns our implementation with the specification.
Fixes: http://wpt.live/dom/nodes/Document-createElementNS.html
> LibWeb: Make `document.createElementNS()` case-sensitive

- Tests/LibWeb/Text/expected/DOM/CDATASection-cloneNode.txt
- Tests/LibWeb/Text/expected/DOM/Range-containing-CDATASection.txt
- Tests/LibWeb/Text/input/DOM/CDATASection-cloneNode.html
- Tests/LibWeb/Text/input/DOM/Range-containing-CDATASection.html
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
This PR includes a few fixes to `DOM::Node` that I came across while investigating some unrelated WPT failures.
This fixes a fair number of WPT ranges tests: https://wpt.live/dom/ranges.
Before:
Ran 38 tests finished in 81.2 seconds.
• 23 ran as expected. 0 tests skipped.
• 5 tests had errors unexpectedly
• 10 tests had unexpected subtest results
After:
Ran 38 tests finished in 149.6 seconds.
• 31 ran as expected. 0 tests skipped.
• 5 tests had errors unexpectedly
• 2 tests had unexpected subtest results
> LibWeb: A few more `DOM::Node` fixes

- Tests/LibWeb/Text/expected/HTML/HTMLSelectElement-options-available-after-add.txt
- Tests/LibWeb/Text/expected/HTML/HTMLSelectElement-options-available-at-load.txt
- Tests/LibWeb/Text/input/HTML/HTMLSelectElement-options-available-after-add.html
- Tests/LibWeb/Text/input/HTML/HTMLSelectElement-options-available-at-load.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
`value` and `selectedOptions` fields of a `<select>` element are expected to have values immediately after a new `<option>` is added or when any script is executed on the page load.
This PR includes two separate changes:
- Update selectedness of the first inserted option if there were no other options, and also update the current displayed value in the `<select>` element. This makes the first example in #795 to start working.
- Schedule a form_associated_element_was_inserted task on a micro task queue. This seems to fix the case when the elements are already statically defined in the page HTML code, see the second example in #795.
[Example](https://syscalls.mebeim.net/?table=x86/64/x64/latest) of a real web page which starts to load after with this change.
Fixes #795
> LibWeb: Fix <select> element behavior when its changed from JavaScript

- Tests/LibWeb/Layout/expected/block-and-inline/relpos-inline-element-js-offsets.txt
- Tests/LibWeb/Text/expected/DOM/Offset-of-empty-inline-element.txt
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
We now follow the rules from the spec more closely, along with an unspecified quirk for when the offsetParent is a non-positioned body element. (Spec bug linked in a comment.)
This fixes a whole bunch of css-flexbox tests on WPT, which already had correct layout, but the reported metrics from JS API were wrong.
> LibWeb: Make offsetTop and offsetLeft behave more like other browsers

- Userland/Libraries/LibThreading/BackgroundAction.cpp
This prevents a crash in ImageDecoder when it's closed before any image decoding requests have been made.
cc @AtkinsSJ
> LibThreading: Guard closing the background thread on the thread existing

- Userland/Libraries/LibWebView/ViewImplementation.cpp
Not sure if this is overkill at this point — since people running Ladybird know about the repo and know enough to build from the sources, etc.
But who knows, it may help to get a few more people filing good issues who might not have otherwise.
At least it doesn’t seem especially annoying or harmful.
Anyway, I don’t feel strongly about — so no worries if this is just closed without merging. It’s just an idea.
> LibWebView: Emit “submit an issue” suggestion when Ladybird crashes

- Tests/LibWeb/Text/expected/DOM/Node-nodeName.txt
- Tests/LibWeb/Text/input/DOM/Node-nodeName.html
- Userland/Libraries/LibWeb/DOM/DocumentType.h
This aligns our implementation with the specification.
Fixes the following WPT tests:
http://wpt.live/dom/nodes/Node-nodeName.html
http://wpt.live/dom/nodes/DOMImplementation-createDocumentType.html
> LibWeb: Make `DocumentType::node_name()` return `DocumentType::name()`

- Tests/LibWeb/Text/expected/HTML/HTMLMediaElement-addTextTrack.txt
- Tests/LibWeb/Text/input/HTML/HTMLMediaElement-addTextTrack.html
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
- Userland/Libraries/LibWeb/HTML/TextTrack.cpp
- Userland/Libraries/LibWeb/HTML/TextTrack.h
- Userland/Libraries/LibWeb/HTML/TextTrack.idl
Removes some noise from the console when browsing bbc.co.uk :^)
> LibWeb/HTML: Implement HTMLMediaElement.addTextTrack

- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/HTML/Scripting/Environments.h
This should resolve all known FIXMEs related to the fetch record and fetch group concepts.
> LibWeb: Append fetch record to client's fetch group when request is a subresource

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
- Tests/LibWeb/Layout/expected/css-counters/basic.txt
- Tests/LibWeb/Layout/expected/css-counters/counters-function.txt
- Tests/LibWeb/Layout/expected/css-counters/hidden-elements.txt
- Tests/LibWeb/Layout/input/css-counters/basic.html
- Tests/LibWeb/Layout/input/css-counters/counters-function.html
- Tests/LibWeb/Layout/input/css-counters/hidden-elements.html
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/CSSNumericType.cpp
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/CountersSet.cpp
- Userland/Libraries/LibWeb/CSS/CountersSet.h
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/CSS/StyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/CounterDefinitionsStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CounterDefinitionsStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/CounterStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CounterStyleValue.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Some screenshots:
The main limitation here is that pseudo-elements can't modify counter values. I repeatedly banged into walls while trying to make that work. There's probably a way (I mean, the other browsers have done it, and I don't think Firefox is capable of warping reality) but I'll leave it for now and hopefully have some kind of epiphany. :sweat_smile:
> LibWeb: First pass at CSS counters

- Tests/LibWeb/Text/expected/HTML/submit-button-click-when-disabled.txt
- Tests/LibWeb/Text/input/HTML/submit-button-click-when-disabled.html
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
Fixes an infinite reload loop on some of the dom/events/ tests in WPT.
> LibWeb: Don't proceed with Element.click() on disabled form controls

- Userland/Libraries/LibWeb/Animations/AnimationEffect.cpp
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Userland/Libraries/LibWeb/CSS/FontFace.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Helpers.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.h
- Userland/Libraries/LibWeb/CSS/SyntaxHighlighter/SyntaxHighlighter.cpp
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasFillStrokeStyles.h
- Userland/Libraries/LibWeb/HTML/SourceSet.cpp
This was only ErrorOr in order to propagate tiny OOMs when tokenizing.
> LibWeb/CSS: Make CSS Parser construction infallible

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
It turns out we were already generating all the necessary include statements, and we can simply remove all this goofy code soup that uses the C preprocessor to speculatively look for include files.
> LibWeb: Stop trying to guess include paths in IDL codegen

- .github/workflows/lagom-template.yml
Enabling the plugins makes the job take ~1h even for small changes.
> CI: Only run clang plugins workflow on pushes to master

- AK/LEB128.h
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Types.h
Speeds up spidermonkey.wasm instantiation by around 110ms (280ms -> 170ms).
> LibWasm: Small optimizations pack

- Userland/Libraries/LibLine/Editor.cpp
- Userland/Libraries/LibLine/Editor.h
- Userland/Libraries/LibLine/InternalFunctions.cpp
- Userland/Libraries/LibLine/KeyCallbackMachine.cpp
- Userland/Utilities/js.cpp
Apparently this is common in the js repl world.
Fixes #743.
> Utilities/js: Make it possible to exit via two consecutive ^C's

- Tests/LibWeb/Text/expected/css/custom-ident-parsing.txt
- Tests/LibWeb/Text/input/css/custom-ident-parsing.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
These have a few rules that we didn't follow in most cases:
- CSS-wide keywords are not allowed. (inherit, initial, etc)
- `default` is not allowed.
- The above and any other disallowed identifiers must be tested case-insensitively.
This introduces a `parse_custom_ident_value()` method, which takes a list of disallowed identifier names, and handles the above rules.
> LibWeb/CSS: Parse custom-idents more consistently

- AK/SIMDExtras.h
- Meta/Lagom/CMakeLists.txt
Since the Wasm runtime should be fully spec-compliant, we want to make sure that the spec-tests always pass.
We don't have full spec-compliance on gcc ladybird, but this PR will at least help to see the failures in CI.
> Meta: No longer ignore `test-wasm` results during testing

- Userland/Libraries/LibGfx/Font/Font.cpp
- Userland/Libraries/LibGfx/Font/Font.h
- Userland/Libraries/LibGfx/Font/OpenType/Typeface.cpp
- Userland/Libraries/LibGfx/Font/OpenType/Typeface.h
- Userland/Libraries/LibGfx/Font/ScaledFont.cpp
- Userland/Libraries/LibGfx/Font/ScaledFont.h
- Userland/Libraries/LibGfx/Font/Typeface.h
- Userland/Libraries/LibGfx/Painter.cpp
- Userland/Libraries/LibGfx/Painter.h
No longer needed after switching to Skia.
> LibGfx: Remove code responsible for glyph rasterization

- Tests/LibWeb/Text/expected/DOM/Node-lookupPrefix.txt
- Tests/LibWeb/Text/input/DOM/Node-lookupPrefix.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/DOM/Node.h
- Userland/Libraries/LibWeb/DOM/Node.idl
Adds https://dom.spec.whatwg.org/#dom-node-lookupprefix alongside some tests.
This passes 10 of the 11 cases in the Web Platform Tests: https://wpt.live/dom/nodes/Node-lookupPrefix.xhtml. Case 9 fails due to #840.
> LibWeb/DOM: Implement Node.lookupPrefix

- Ladybird/Qt/Application.cpp
- Ladybird/Qt/Application.h
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
While running WPT tests, I noticed that the size of newly opened browser windows could be affected by tests that opened popup windows.
Tested with the following steps:
1. Open Ladybird
2. Click: Debug -> Block Pop-ups
3. Open Inspector
4. Enter the following into the console: `window.open("", "", "width=100, height=100")`
5. Close the main window
6. Close the popup window
7. Reopen Ladybird
The size of the new Ladybird window should not be the size of the popup window.
This matches the behavior of other browsers.
> UI/Qt: Don't save size and location of popup windows on exit

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Userland/Libraries/LibWasm/AbstractMachine/Configuration.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Printer/Printer.cpp
- Userland/Libraries/LibWasm/Printer/Printer.h
- Userland/Libraries/LibWasm/Types.h
`Module::functions` created clones of all of the functions in the module. It provided a _slightly_ better API, but ended up costing around 40ms when instantiating spidermonkey.
This brings us from 180ms -> 140ms when instantiating spidermonkey.
> LibWasm: Remove `Module::functions`

- Userland/Libraries/LibHTTP/Job.cpp
- Userland/Services/RequestServer/ConnectionCache.h
- Userland/Services/RequestServer/ConnectionFromClient.cpp
- Userland/Services/RequestServer/ConnectionFromClient.h
- Userland/Services/RequestServer/HttpCommon.h
- Userland/Services/RequestServer/HttpRequest.h
- Userland/Services/RequestServer/HttpsRequest.h
- Userland/Services/RequestServer/Request.h
That usually happens in "exceptional" states when the client exits unexpectedly (crash, force quit mid-load, etc), leading to the job flush timer firing and attempting to write to a nonexistent object (the client).
This commit makes RS simply cancel such jobs; cancelled jobs in this state simply go away instead of sending notifications around.
> RequestServer+LibHTTP: Cancel requests on client exit

- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
While working on this section of code, I noticed some older names were still being used. This just brings them up to date and fixes a couple moves.
> LibWeb: Fix some typos with text clips

- Tests/LibWeb/Text/expected/Worker/Worker-location.txt
- Tests/LibWeb/Text/input/Worker/Worker-location.html
- Tests/LibWeb/Text/input/Worker/Worker-location.js
- Userland/Libraries/LibWeb/HTML/WorkerLocation.cpp
- Userland/Libraries/LibWeb/HTML/WorkerLocation.h
This fixes: https://wpt.live/workers/WorkerLocation.htm and 15 other similar tests which previously timed out.
> LibWeb: Set correct prototype for `WorkerLocation`

- Meta/gn/secondary/Userland/Libraries/LibWeb/WebAudio/BUILD.gn
- Meta/gn/secondary/Userland/Libraries/LibWeb/idl_files.gni
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/WebAudio/AudioBufferSourceNode.cpp
- Userland/Libraries/LibWeb/WebAudio/AudioBufferSourceNode.h
- Userland/Libraries/LibWeb/WebAudio/AudioBufferSourceNode.idl
- Userland/Libraries/LibWeb/WebAudio/AudioDestinationNode.cpp
- Userland/Libraries/LibWeb/WebAudio/AudioDestinationNode.h
- Userland/Libraries/LibWeb/WebAudio/AudioDestinationNode.idl
- Userland/Libraries/LibWeb/WebAudio/AudioNode.cpp
- Userland/Libraries/LibWeb/WebAudio/AudioNode.h
- Userland/Libraries/LibWeb/WebAudio/AudioNode.idl
- Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.cpp
- Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.h
- Userland/Libraries/LibWeb/WebAudio/BiquadFilterNode.cpp
- Userland/Libraries/LibWeb/WebAudio/BiquadFilterNode.h
- Userland/Libraries/LibWeb/WebAudio/BiquadFilterNode.idl
- Userland/Libraries/LibWeb/WebAudio/GainNode.cpp
- Userland/Libraries/LibWeb/WebAudio/GainNode.h
This gets http://www.puzzlescript.net/ fully working 🥳 (well except audio :sweat_smile: also `https` doesn't work and the codemirror editor is a little buggy) in Ladybird!
This includes the [editor](https://www.puzzlescript.net/editor.html), games in the [gallery](http://www.puzzlescript.net/Gallery/index.html), and puzzlescript games on [itch.io](https://itch.io/games/tag-puzzlescript) (excluding some of the ones based on puzzlescript forks).
I forgot to pull and accidentally redid most of https://github.com/LadybirdBrowser/ladybird/pull/800 hopefully I rebased correctly
> More WebAudio Stubbing

- Documentation/Troubleshooting.md
I ran into this message when running a Qt-chrome build on macOS — related to https://github.com/LadybirdBrowser/ladybird/pull/843, so I could make Sam a screenshot of the UI from the build.
And I assumed at first that the warning must have been indicating the build was broken, and I wasted some time trying to figure out how to fix it.
But it turns out that the message doesn’t really indicate anything’s broken. It’s a non-problem. So, let’s add it to the docs so that we can help other people avoid unnecessarily wasting time on it, the way I did.
> Documentation: Add info on macOS Qt X11R6 linking warning (non-problem)

- Userland/Libraries/LibWeb/HTML/DOMStringList.cpp
- Userland/Libraries/LibWeb/HTML/DOMStringList.h
- is_supported_property_index() no longer needs to be overridden
- item_value() now returns Optional
Fixes CI!
> LibWeb: Update DOMStringList to match PlatformObject changes

- Tests/LibWeb/Layout/expected/css-counters/counters-function-single-argument.txt
- Tests/LibWeb/Layout/input/css-counters/counters-function-single-argument.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
> LibWeb/CSS: Treat counters() function with 1 argument as invalid

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
- Userland/Libraries/LibWeb/Painting/BorderRadiusCornerClipper.h
- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/DisplayList.cpp
- Userland/Libraries/LibWeb/Painting/DisplayList.h
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.h
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.h
- Userland/Libraries/LibWeb/Painting/PaintContext.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
Contrary to LibGfx, where corner clipping was implemented by sampling and blitting pixels under corners into a temporary bitmap, Skia allows us to simply apply a mask. As a result, we no longer need the BlitCornerClipping command, which has become a no-op.
- SampleUnderCorners is renamed to AddRoundedRectClip
- The optimization that skipped unnecessary blit and sample commands has been removed. However, this should not result in a performance regression because Skia seems to perform mask rasterization lazily.
> LibWeb: Delete BlitCornerClipping display list command

- Tests/LibWeb/Text/expected/css/update-pseudo-elements-on-hover.txt
- Tests/LibWeb/Text/input/css/update-pseudo-elements-on-hover.html
- Userland/Libraries/LibWeb/CSS/StyleInvalidation.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
[Peek 2024-07-29 16-03 acid2 nose.webm](https://github.com/user-attachments/assets/1af5c9b2-b374-4237-b2a9-a71fb11ae300)
Previously, pseudo-elements would not update their style (or whether they exist) unless something else invalidated the layout tree. This PR makes us invalidate the layout tree if a pseudo-element might change, which fixes it. (We might want to be more judicious with invalidating it in future, though right now that would involve doubling-up the pseudo-element style computation.)
> LibWeb: Update pseudo-elements on hover, fixing Acid2 nose

- Userland/Services/RequestServer/ConnectionCache.h
- Userland/Services/RequestServer/ConnectionFromClient.cpp
This was some nonsense code left in by mistake, ref commit: 4211639e455c8f58f23304be5312ad48a76e401a
Fixes #904.
> RequestServer: Actually hold on to the preload job until it's done

- Userland/Libraries/LibWeb/WebAssembly/Table.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
Return `null` instead, as per the specification.
> LibWeb: No longer return `undefined` on null table entry in Wasm API

- AK/Utf16View.cpp
- AK/Utf16View.h
- Tests/AK/TestUtf16.cpp
- Userland/Libraries/LibWeb/DOM/CharacterData.h
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
In a benchmark of computing the length of a very large text node, this is 3.5x faster.
> AK+LibWeb: Avoid allocating UTF-16 strings only the UTF-16 length is needed

- Userland/Libraries/LibWeb/CSS/StyleInvalidation.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
Main changes are to compute pseudo-element styles when their parent element's style is computed; save that on the element; invalidate based on the difference between the new and old style; and then use the saved style when constructing the layout tree instead of computing style there.
It greatly reduces the amount of extra layout-invalidation caused by #888.
> LibWeb: Be smarter about pseudo-element style invalidation

- Userland/Libraries/LibCore/System.cpp
- Userland/Libraries/LibWebView/ChromeProcess.cpp
If `setrlimit` fails, let's just report the error rather than failing to start the browser at all.
> LibCore+LibWebView: Use Error::from_syscall to report get/setrlimit errors, and make non-fatal

- Tests/LibWeb/Ref/reference/scrollable-contains-table-ref.html
- Tests/LibWeb/Ref/scrollable-contains-table.html
- Userland/Libraries/LibWeb/Painting/Paintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Moves paint_table_borders() call into PaintableBox::paint() to make scroll offset and clip rectangle of enclosing scrollable be applied in ::before_paint().
> LibWeb: Apply scroll offset and clip rectangle to table borders

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
We don't want to set the intrinsic Console object's client to non-top-level clients, created for e.g. subframes. We also want to make sure the Console client is updated if the top-level document has changed.
Fixes #782. Both the second and fourth commits actually individually fix the issue, as the document causing the crash is a temporary document for parsing HTML fragments.
This is a re-land of #787. The issue was that nothing was visiting the console client we were later trying to set as the top-level client.
> LibWeb+WebContent: Limit the Console client to the top-level navigable client

- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
This change disables caching for 301, 302, 303, 307, and 308 responses. Fixes https://github.com/LadybirdBrowser/ladybird/issues/863
Not sure if this is the best solution — I mean, just making redirects uncacheable from the get-go — but if it’s suboptimal, I’m happy to try refining the patch further in any way needed.
> LibWeb/Fetch: Don’t cache redirects

- Userland/Libraries/LibWeb/HTML/MessagePort.cpp
Previously, the fact that this wasn't accounted for could lead to a crash when large messages were received.
This fixes:  https://wpt.live/workers/semantics/interface-objects/002.worker.html  and https://wpt.live/dom/events/AddEventListenerOptions-signal.any.worker.html (and probably others).
> LibWeb: Account for header size when reading MessagePort message payload

- Userland/Libraries/LibJS/Runtime/Intl/Locale.cpp
- Userland/Libraries/LibJS/Runtime/Intl/Locale.h
- Userland/Libraries/LibJS/Runtime/Intl/LocaleConstructor.cpp
- Userland/Libraries/LibJS/Runtime/Intl/LocalePrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/Intl/Locale/Locale.prototype.firstDayOfWeek.js
This is a normative change in the Intl Locale Info proposal. See:
https://github.com/tc39/proposal-intl-locale-info/commit/5cb45fd
https://github.com/tc39/proposal-intl-locale-info/commit/6d80e69
https://github.com/tc39/proposal-intl-locale-info/commit/04039b8
test262 diff:
```
Diff Tests:
test/intl402/Locale/constructor-options-firstDayOfWeek-valid.js ❌ -> ✅
test/intl402/Locale/prototype/firstDayOfWeek/valid-id.js        ❌ -> ✅
test/intl402/Locale/prototype/firstDayOfWeek/valid-options.js   ❌ -> ✅
```
(We now pass all tests under `test/intl402/Locale`)
> LibJS: Change Intl.Locale.prototype.firstDayOfWeek to be a string

- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h
The user is not required to keep the object alive, this commit makes it so the lifetime of these functions is extended to match the Wasm module it is imported into.
Fixes the crash in #907.
> LibWeb: Keep Wasm-imported functions alive

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/input-selection-start-selection-end.txt
- Tests/LibWeb/Text/input/input-selection-start-selection-end.html
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Get the functionality we already have working in HTMLTextAreaElement put into a common place for use in HTMLInputElement.
> BindingsGenerator+HTML: Partially implement HTMLInputElement's selection{Start,End}

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
- Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Printer/Printer.cpp
- Userland/Libraries/LibWasm/Types.h
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
- Userland/Utilities/wasm.cpp
Remove `for_each_section_of_type` in favor of making the module's sections defined as distinct fields. This means it is no longer possible to have two of the same section (which is invalid in WebAssembly, for anything other than custom sections). We previously didn't account for this behavior because the Wasm testsuite only checks that we don't have duplicate start sections (which we handled in the validator phase).
This also makes `Module` a little bit easier to work with, since we no longer need to wrap everything in `for_each_section_of_type`.
> LibWasm: Clean up module sections API

- Tests/LibWeb/Ref/reference/scrollable-contains-rotated-boxes-ref.html
- Tests/LibWeb/Ref/scrollable-contains-rotated-boxes.html
- Userland/Libraries/LibWeb/Layout/Node.h
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.cpp
- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Overflow clipping is currently implemented as:
1. Create clip frame for each box with hidden overflow
2. Calculate clip rect for each clip frame by intersecting padding boxes
of all boxes with hidden overflow in containing block chain
3. Assign enclosing clip frame (closest clip frame in containing block
chain) to each PaintableBox
4. Apply clip rect of enclosing clip frame in Paintable::before_paint()
It breaks when any CSS transform other than simple translation is lying
between box with hidden overflow and a clipped box, because clip
rectangle will be applied when transform has already changed.
The fix is implemented by relying on the following rule:
"For elements whose layout is governed by the CSS box model, any value
other than none for the transform also causes the element to …
> LibWeb: Fix overflow clip when "complicated" CSS transform is used

- Ladybird/HelperProcess.cpp
- Ladybird/ImageDecoder/main.cpp
- Ladybird/RequestServer/main.cpp
- Ladybird/WebWorker/main.cpp
- Userland/Libraries/LibWebView/Application.cpp
- Userland/Libraries/LibWebView/Options.h
This removes the `--debug-web-content` and `--enable-callgrind-profiling` flags, and replaces them with `--debug-process=<process-name>` and `--profile-process=<process-name>` flags. For example:
ladybird --debug-process=WebContent
ladybird --debug-process=RequestServer
ladybird --profile-process=WebContent
ladybird --profile-process=RequestServer
This allows attaching gdb to and profiling any helper process.
> LibWebView+UI: Allow debugging and profiling any helper process

- Ladybird/WebDriver/main.cpp
- Userland/Services/WebDriver/main.cpp
Previously, the incorrect name for this argument  was being used when attempting to launch `headless-browser`.
> WebDriver: Use correct WebDriver IPC path argument name

- Ladybird/HelperProcess.cpp
- Ladybird/WebContent/main.cpp
- Ladybird/WebDriver/main.cpp
- Userland/Libraries/LibWebView/Application.cpp
- Userland/Libraries/LibWebView/Options.h
This option forces Skia to use its CPU backend even when the GPU is available. This improves speed and stability when running Web Platform Tests.
As part of this PR, I've also removed the `--use-skia-painting` option from `WebContent`, as it was was no longer being used anywhere.
> LibWebView+WebContent+WebDriver: Add a `--force-cpu-painting` option

- Userland/Libraries/LibWeb/Animations/Animatable.cpp
- Userland/Libraries/LibWeb/Animations/Animatable.h
- Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Fixes the bug when animation does not run at all if an element has a pseudo-element, because both of them use the same cache.
> LibWeb: Add slots for pseudo-elements animation cache in Animatable

- Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWeb/UIEvents/KeyCode.h
- Userland/Libraries/LibWeb/UIEvents/MouseEvent.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
Completely unrelated to any videos that may have been released today :wink: 
The spec does not define activation behavior of ctrl/cmd clicks, so we have to go a bit ad-hoc here. When an anchor element is clicked with the cmd (on macOS) or ctrl (on other platforms) modifier pressed, we will skip activation of that element and pass the event on to the chrome. We still dispatch the event to allow scripts to cancel the event.
> LibWeb+WebContent: Support ctrl/cmd-clicking a link to open it in a new tab

- Base/res/ladybird/inspector.js
Previously, the legacy `-webkit-foo` properties would all be top of the list, when they are generally not useful to inspect. Instead, put them at the bottom, so that users can still see them if they want to, but they're not in the way.
> LibWebView: Sort vendor-prefixed properties last in the inspector

- Base/res/ladybird/inspector.css
- Base/res/ladybird/inspector.js
Currently, the feel of scrolling containers in the Inspector is a bit awkward. We make the entire split-view container scrollable, then we absolutely position the tab control buttons to force them to not scroll. The result is that the scroll bar is painted over the tab controls, and the tab content that we actually want to scroll has to scroll under the tab controls. This never looked quite right.
It was basically:
<div tab-container> 
<div tab-controls /> 
<div tab-content /> 
</div>
This patch moves the "scrollability" to just the tab content. We then don't need to go out of our way to ensure only the content is actually scrollable.
So we now have:
<div tab-container> 
<div tab-controls /> 
<div tab-content /> 
</div>
Before:
After:
> LibWebView: Improve scrolling of Inspector content containers

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Text.h
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
- Userland/Libraries/LibWeb/Page/EditEventHandler.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Navigables are re-used for navigations within the same tab. Its current ownership of the cursor position is a bit ad-hoc, so nothing in the spec indicates when to reset the cursor, nor do we manually do so. So when a cursor update happens on one page, that cursor is retained on the next page.
Instead, let's have the document own the cursor. Each navigation results in a new document, thus we don't need to worry about resetting cursors.
This also makes many of the callsites feel nicer. We were previously often going from the node, to the document, to the navigable, to the cursor. This patch removes the navigable hop.
This should fix the currently flaky input-selection-start-selection-end.html test. The test and the code it tests are actually fine, but were affected by the navigable's cursor …
> LibWeb: Move the navigable's cursor position to be owned by the document

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
To avoid expensive lookups, we now cache a weak pointer from document to the last known node navigable. Before using the cache, we validate that the document is still the navigable's active document.
> LibWeb: Cache the Document's node navigable when possible

- Tests/LibWeb/Ref/reference/text-overflow.html
- Tests/LibWeb/Ref/text-overflow.html
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Enums.json
- Userland/Libraries/LibWeb/CSS/Identifiers.json
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
This patch adds support for the text-overflow property.
All the neccessary plumbing throughout the CSS landscape is done and then the conditional display of ellipses (...) is implemented in TextNode.
Top: text-overflow: clip
Bottom: text-overflow: ellipsis
> CSS: Add support for text-overflow property

- Tests/LibWeb/Text/expected/quirks-mode-case-insensitive-class-selector.txt
- Tests/LibWeb/Text/input/quirks-mode-case-insensitive-class-selector.html
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
This align our implementation with the CSSWG Selectors Level 4 specification.
The relevant part of the specification is here: https://drafts.csswg.org/selectors-4/#class-html
> When matching against a document which is in [quirks mode](https://dom.spec.whatwg.org/#concept-document-quirks), class names must be matched [ASCII case-insensitively](https://infra.spec.whatwg.org/#ascii-case-insensitive); class selectors are otherwise case-sensitive, only matching class names they are [identical to](https://infra.spec.whatwg.org/#string-is).
> LibWeb: Match class selectors case insensitively in quirks mode

- Tests/LibWeb/Text/data/bad.xml
- Tests/LibWeb/Text/expected/XML/error-page.txt
- Userland/Libraries/LibXML/Parser/Parser.cpp
- Userland/Libraries/LibXML/Parser/Parser.h
This makes it much easier to see where parsing errors occur in XML documents.
Found while investigating a parse error in: https://wpt.live/dom/nodes/ParentNode-querySelector-All-xht.xht
> LibXML: Include line and column numbers in parse error messages

- Tests/LibWeb/Ref/text-overflow.html
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Fixes out of bound access to glyph run when `last_glyph_index` is 0.
Fixes crashing on https://github.com/LadybirdBrowser/ladybird/pulls
> LibWeb: Fix OOB access in "text-overflow: ellipsis" clip

- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Follow-on from #499 to also account for placeholder styles
> LibWeb: Also invalidate placeholder style on focus change

- Tests/LibWeb/Text/expected/DOM/getElementsByClassName-multiple.txt
- Tests/LibWeb/Text/input/DOM/getElementsByClassName-multiple.html
- Userland/Libraries/LibWeb/DOM/ParentNode.cpp
This regressed in 0fceede029e :sweat_smile: 
Fixes the following WPT tests:
https://wpt.live/dom/nodes/getElementsByClassName-09.htm
https://wpt.live/dom/nodes/getElementsByClassName-26.htm
https://wpt.live/dom/nodes/getElementsByClassName-27.htm
https://wpt.live/dom/nodes/getElementsByClassName-28.htm
All of the getElementsByClassName WPT tests now pass.
> LibWeb: Ensure `ParentNode.getElementsByClassName()` matches all classes

- Tests/LibWeb/Text/expected/css/revert-all.txt
- Tests/LibWeb/Text/input/css/revert-all.html
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
Not every value in a StyleProperties will be non-null by the time we perform `revert`, so let's make a specialized function for reverting a property instead of using the path that requires the value to be non-null.
> LibWeb: Don't crash on CSS `all: revert`

- Tests/LibURL/TestURL.cpp
- Userland/Libraries/LibURL/Parser.cpp
We were previously not checking for C0 control, U+0025 (%), or U+007F DELETE.
This makes another good set of URL tests in WPT pass :^)
> LibURL: Validate for invalid _domain_ code points for non-opaque domains

- Tests/LibWeb/Text/expected/css/CSSStyleDeclaration-modify-computed.txt
- Tests/LibWeb/Text/input/css/CSSStyleDeclaration-modify-computed.html
- Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.h
Previously, calling `setProperty` or `removeProperty` from JS on a CSSStyleDeclaration returned from `getComputedStyle()` would return null. We now return a NoModificationAllowedError instead, which aligns our implementation with the specification.
Makes the following WPT test pass:  http://wpt.live/css/cssom/computed-style-set-property.html
> LibWeb: Return error on modification of a computed CSS style declaration

- Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp
Fixes for web platform tests:
- http://wpt.live/fetch/api/request/request-headers.any.html
- http://wpt.live/fetch/api/basic/request-forbidden-headers.any.html
> LibWeb/Fetch: Add missing forbidden header name & correct check

- Tests/LibWeb/Text/expected/CSSOMView/getClientRects-in-detached-document.txt
- Tests/LibWeb/Text/input/CSSOMView/getClientRects-in-detached-document.html
- Userland/Libraries/LibWeb/DOM/Element.cpp
I previously believed there was no way a detached document should have layout information, but it turns out there is a way: getComputedStyle().
So we need to account for cases where we have a layout node, but no navigable, since that is a state we can get into at this moment.
Fixes #354
> LibWeb: Don't crash on getClientRects() in document without navigable

- Documentation/AdvancedBuildInstructions.md
- Meta/configure-clangd.sh
Add a simple shell script to update the local clangd configuration according to the type of build selected by the user.
> Meta: Script to configure clangd according to build type

- Tests/LibWeb/Text/expected/HTML/HTMLTrackElement-readyState-attribute.txt
- Tests/LibWeb/Text/input/HTML/HTMLTrackElement-readyState-attribute.html
- Userland/Libraries/LibWeb/HTML/HTMLTrackElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTrackElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl
Follow-up to https://github.com/LadybirdBrowser/ladybird/commit/ff08c2f735e938c8280089eca690fd5e65d017c1, as I realised I missed it :)
> LibWeb: Implement HTMLTrackElement.readyState

- Userland/Libraries/LibHTTP/HttpRequest.cpp
This was a goof in cc557323326ba55514ef2a8a6e0efd7f09330f06 which resulted in the URL path getting double percent encoded. Since the path already comes out percent encoded following the rules in the URL spec - we don't need to percent encode again.
Fixes: #978
> LibHTTP: Don't double percent encode path in HTTPRequst::to_raw_request

- Tests/LibWeb/Ref/reference/scrollable-contains-box-with-gradient-background-ref.html
- Tests/LibWeb/Ref/scrollable-contains-box-with-gradient-background.html
- Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.h
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
- Userland/Libraries/LibWeb/Painting/InlinePaintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/PaintableFragment.h
This change fixes layering violation by moving to_px() calls to happen before display list recording. Also it should make display list recording a bit faster by resolving background properties beforehand.
> LibWeb: Resolve background size and offset only after style invalidation

- Tests/LibWeb/Ref/inline-block-with-css-background.html
- Tests/LibWeb/Ref/reference/inline-block-with-css-background-ref.html
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
Fixes regression introduced by f574e2b03ab3c9c55a74a86435efeab179a4caa9
> LibWeb: Use padding box to get background rect for inline paintable

- Tests/LibWeb/Ref/background-clip-text-inside-scrollable.html
- Tests/LibWeb/Ref/reference/background-clip-text-inside-scrollable-ref.html
- Userland/Libraries/LibWeb/CSS/StyleValues/AbstractImageStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/ConicGradientStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/ConicGradientStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/LinearGradientStyleValue.h
- Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/RadialGradientStyleValue.h
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/DisplayList.cpp
- Userland/Libraries/LibWeb/Painting/DisplayList.h
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.h
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.h
Instead of carrying the display list for a mask in each command that
might potentially be affected by "background-clip: text", this change
introduces a new AddMask command that is applied once for all
background layers within one box.
The new AddMask command includes a rectangle for the mask destination
that is translated by the corresponding scroll offset.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/857
> LibWeb: Fix "background-clip: text" for elements nested in scrollable

- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
once I decided https://github.com/LadybirdBrowser/ladybird/pull/988 is good to go I almost immediately found two little issues.
> LibWeb: Skip AddMask in display list player if destination rect is empty

- Tests/LibWeb/Text/expected/HTML/HTMLTableCellElement-cellIndex-attribute.txt
- Tests/LibWeb/Text/input/HTML/HTMLTableCellElement-cellIndex-attribute.html
- Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.idl
See:
- http://wpt.live/html/semantics/tabular-data/attributes-common-to-td-and-th-elements/cellIndex.html
> LibWeb: Implement HTMLTableCellElement.cellIndex

- AK/CMakeLists.txt
- Userland/Libraries/LibGfx/CMakeLists.txt
The script pulls in a dependency on the `yaml` python package. Instead of updating all the docs and CI jobs to account for this, let's guard calling the script behind our experimental flag instead.
> AK+LibGfx: Only generate clang module map if ENABLE_SWIFT

- Base/res/html/misc/pseudo-elements.html
- Tests/LibWeb/Text/expected/css/getComputedStyle-pseudo-element.txt
- Tests/LibWeb/Text/input/css/getComputedStyle-pseudo-element.html
- Userland/Libraries/LibWeb/CSS/Parser/Helpers.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.h
- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Node.cpp
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Services/WebContent/ConnectionFromClient.cpp
At some point `getComputedStyle()` gained a second parameter for the name of a pseudo-element to get style for. We previously ignored that completely, but now we don't! :tada:
As a side feature, the resolved style now also shows up in the inspector.
As a side-side feature, I fixed a bug where the inspector wouldn't show pseudo-elements at all if their parent had no other children.
Several parts of this are hacky and temporary, just because I didn't want to get too sidetracked. :sweat_smile: Our `CSSStyleDeclaration` classes need some reworking to match the spec.
I'm bad at figuring out what WPT is doing, but this test in particular got some points:
`css/cssom/getComputedStyle-pseudo.html`
Before: 2 Pass. 15 Fail. 9 Optional Feature Unsupported
After: 12 Pass. 5 Fail. 9 Optional Feature …
> Implement getComputedStyle() for pseudo-elements

- Tests/LibWeb/Text/expected/hit_testing/stacking-context-inside-scrollable-box.txt
- Tests/LibWeb/Text/input/hit_testing/stacking-context-inside-scrollable-box.html
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.h
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Fixes a bug when stacking contexts nested inside scrollable box are treated as fixed positioned during hit-testing.
> LibWeb: Adjust stacking context position by scroll offset in hit-testing

- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.h
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
Previously it was accounted for by LibGfx while applying scale transformation, but is no longer needed for Skia.
> LibWeb: Remove unused image-rendering param for stacking context

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
These have no declared constructor, so apple clang and clang clang seem to disagree on some versions.
> LibWasm: Use braces to initialize Reference::Foo classes

- Tests/LibWeb/Layout/expected/srcset-sizes-crash.txt
- Tests/LibWeb/Layout/input/srcset-sizes-crash.html
- Userland/Libraries/LibWeb/HTML/SourceSet.cpp
Fixes 4 crashing tests in: https://wpt.live/html/semantics/embedded-content/the-img-element/sizes, meaning we now pass 672 more subtests.
> LibWeb: Avoid division by zero in SourceSet width descriptor calculation

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
`m_needs_repaint = true` is not enough because it doesn't schedule
repaint of a parent navigable.
Fixes the bug when an iframe is not repainted after scrolling.
> LibWeb: Call set_needs_display() if navigable is scrolled or resized

- Tests/LibWeb/Text/expected/HTML/a-element-set-protocol-on-href.txt
- Tests/LibWeb/Text/input/HTML/a-element-set-protocol-on-href.html
- Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
We completely missed this step, which made setters not actually do anything!
Fixes 336 test failures on:
https://wpt.live/url/url-setters-a-area.window.html
> LibWeb: Actually perform "update the href steps"

- AK/TypeCasts.h
- Userland/Libraries/LibWeb/DOM/ShadowRoot.cpp
- Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
This fixes a compilation failure with GCC 13.2.0 and later.
> AK+LibWeb: Don't verify_cast where input and output types are the same 

- Meta/Lagom/Tools/CodeGenerators/LibTextCodec/GenerateEncodingIndexes.cpp
- Tests/LibTextCodec/CMakeLists.txt
- Tests/LibTextCodec/TestTextEncoders.cpp
- Userland/Libraries/LibTextCodec/CMakeLists.txt
- Userland/Libraries/LibTextCodec/Encoder.cpp
- Userland/Libraries/LibTextCodec/Encoder.h
- Userland/Libraries/LibURL/CMakeLists.txt
- Userland/Libraries/LibURL/Parser.cpp
- Userland/Libraries/LibURL/Parser.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
- Userland/Libraries/LibWeb/DOMURL/DOMURL.h
- Userland/Libraries/LibWeb/DOMURL/URLSearchParams.cpp
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
This pull request adresses the issue https://github.com/LadybirdBrowser/ladybird/issues/824
This passes most of the WPT encoding/legacy-mb-* tests, but it’s still not 100%.
It’s also pretty slow, doing a linear search of the lookup tables. It would be much better if we had some kind of sorted reverse lookup table, that we could then binary search. But I don't know if that's really necessary for the moment.
> LibTextCodec: Implement legacy encoders

- Userland/Libraries/LibJS/Console.cpp
Fixes the discrepancy between calling `console.count()` and `console.count(undefined)`. I changed the common function that checks whether argument exists by also checking if the first argument is not `undefined`. So, this change affects:
- `console.time`, `console.timeEnd` and `console.timeLog`
- `console.count` and `console.countReset`
Now, in all of the functions above, `console.x()` yields the same result as `console.count(undefined)`
- https://staging.wpt.fyi/results/console/console-count-logging.html?product=ladybird
> LibJS: Treat passing undefined as no argument for console labels

- Userland/Libraries/LibWeb/Layout/LineBox.cpp
This PR stops the cursor from disappearing while typing trailing spaces in a text input box.
Before:
[before.webm](https://github.com/user-attachments/assets/92be5acb-3c39-4957-9c6f-49d1622ea3f5)
After:
[after.webm](https://github.com/user-attachments/assets/f634fba4-f0db-4fb5-b67b-e032de98745f)
> LibWeb: Skip trim trailing whitespace if user is typing

- Tests/LibWeb/Layout/expected/flex/flex-item-on-row-with-intrinsic-size.txt
- Tests/LibWeb/Layout/input/flex/flex-item-on-row-with-intrinsic-size.html
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/ImageBox.cpp
We were stretching flex items with an intrinsic aspect ratio, even if we had an intrinsic width or height available. This fixes the icons in the footer of Ladybird.org.
Ladybird.org before | Ladybird.org after
:---: | :---:
> LibWeb: Account for intrinsic width or height in flex base size

- Userland/Libraries/LibWebView/InspectorClient.cpp
This early exit prevents to show the current DOM in the inspector, when the inspector was already opened.
Fixes #990
> LibWebView: Remove early exit in `InspectorClient::inspect()`

- Userland/Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
- Userland/Libraries/LibWeb/CSS/Parser/MediaParsing.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
The end goal is to consistently use TokenStream everywhere, so that mistakes are harder to make and easier to spot. (Such as not consuming all tokens, or skipping one accidentally.) The ones here aren't that exciting, but there are some harder ones left and my brain wasn't up to those today. :sweat_smile: 
And as a tangent, split up the unwieldy `convert_to_rule()` function into one per rule, and add some documentation to them.
> LibWeb/CSS: Use TokenStream in more places

- Userland/Services/WebContent/WebDriverConnection.cpp
This PR adds timeouts to some WebDriver client methods that the specification says should time out if they are not completed within a certain time.
This prevents some hangs that I had seen when running WPT, although it doesn't address the root cause of the issue that is causing the timeouts.
> WebContent: Add timeouts to some WebDriver client methods

- Tests/LibWeb/Ref/iframe-contains-scrollable-box.html
- Tests/LibWeb/Ref/reference/iframe-contains-scrollable-box-ref.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/DisplayList.cpp
- Userland/Libraries/LibWeb/Painting/DisplayList.h
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.h
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.h
- Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
- Userland/Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
While introducing clip and scroll frame trees, I made a mistake by assuming that the paintable tree includes boxes from nested navigables. Therefore, this comment in the code was incorrect, and clip/scroll frames were simply not assigned for iframes:
```
// NOTE: We only need to refresh the scroll state for traversables
//       because they are responsible for tracking the state of all
//       nested navigables.
```
As a result, anything with "overflow: scroll" is currently not scrollable inside an iframe
This change fixes that by ensuring clip and scroll frames are assigned and refreshed for each navigable. To achieve this, I had to modify the display list building process to record a separate display list for each navigable. This is necessary because scroll frame ids are local to a …
> LibWeb: Create clip and scroll frame trees separately for each navigable

- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Types.h
There are (currently) no spec-tests ensuring that section ordering is enforced, but it _is_ a part of the spec. A pull request to add this to the specification testsuite has been opened at WebAssembly/spec#1775.
> LibWasm: Ensure correct section ordering when parsing binary modules

- AK/String.cpp
- AK/String.h
- Tests/AK/TestString.cpp
- Tests/LibWeb/Text/expected/URL/search-params-with-invalid-utf8.txt
- Tests/LibWeb/Text/expected/URL/search-params-with-plus-in-value.txt
- Tests/LibWeb/Text/input/URL/search-params-with-invalid-utf8.html
- Tests/LibWeb/Text/input/URL/search-params-with-plus-in-value.html
- Userland/Libraries/LibURL/Parser.cpp
- Userland/Libraries/LibURL/URL.cpp
- Userland/Libraries/LibURL/URL.h
- Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
- Userland/Libraries/LibWeb/DOMURL/URLSearchParams.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
- Userland/Libraries/LibWeb/ReferrerPolicy/AbstractOperations.cpp
- Userland/Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Fixes a crash running https://wpt.live/url/urlencoded-parser.any.html
Which, along with the fix cherry-picked here from https://github.com/LadybirdBrowser/ladybird/pull/878 that I just today noticed (important to also prevent conflicts), makes all of the tests from that link pass.
> LibWeb: Actually run UTF-8 decode without BOM for URLSearchParams

- Userland/Services/WebContent/WebDriverConnection.cpp
The timers added previously in #1021 had no effect, as they were never started.
> WebContent: Actually start WebDriver timeout timers

- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/StackingContext.cpp
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
This change causes the viewport to be treated as a "scroll frame," similar to how it already works for boxes with "overflow: scroll." This means that, instead of encoding the viewport translation into a display list, the items will be assigned the scroll frame id of the viewport and then shifted by the scroll offset before execution. In the future it will allow us to reuse a display list for repainting if only scroll offset has changed.
As a side effect, it also removes the need for special handling of "position: fixed" because compensating for the viewport offset while painting or hit-testing is no longer necessary. Instead, anything contained within a "position: fixed" element is simply not assigned a scroll frame id, which means it is not shifted by the scroll offset.
> LibWeb: Unify scroll handling between viewport and scrollable boxes

- Tests/LibWeb/Text/expected/console/console-to-string-tag.txt
- Tests/LibWeb/Text/input/console/console-to-string-tag.html
- Userland/Libraries/LibJS/Runtime/ConsoleObject.cpp
Added configurable `Symbol.toStringTag` property to `console` whose value is "console"
- https://staging.wpt.fyi/results/console/console-namespace-object-class-string.any.html?product=ladybird
- https://staging.wpt.fyi/results/console/console-namespace-object-class-string.any.worker.html?product=ladybird
> LibJS: Set configurable toStringTag property for console

- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.h
- Userland/Libraries/LibWeb/HTML/NavigatorBeacon.cpp
This is defined as 64 KiB in the fetch spec.
See:
- https://wpt.live/beacon/beacon-basic.https.window.html
> LibWeb: Use keepalive maximum size in NavigatorBeacon

- Ladybird/Qt/Tab.cpp
It now just opens a new tab, without changing the current tab.
> Ladybird/Qt: Don't change to new tab with 'Open in New Tab'

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Userland/Libraries/LibWeb/Painting/ClipFrame.cpp
- Userland/Libraries/LibWeb/Painting/ClipFrame.h
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.h
- Userland/Libraries/LibWeb/Painting/Command.h
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.h
- Userland/Libraries/LibWeb/Painting/InlinePaintable.cpp
- Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/ScrollFrame.h
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Before this change AddClipRect was a "special" because it didn't respect scroll frame offset and was meant to be recorded using viewport-relative coordinates. The motivation behind this was to record a "final" clip rectangle computed by intersecting all clip rectangles used by a clip frame. The disadvantage of this approach is that it blocks us from implementing an optimisation to reuse display list if the only change is in the scroll offset, because any scroll offset change leads to invalidating all AddClipRect items within a list.
This change aligns AddClipRect with the rest of display list items by making it account for scroll frame offset. It required discontinuing the recording of the intersection of all clip rectangles within a clip frame and instead producing an AddClipRect for …
> LibWeb: Make AddClipRect display list item account for scroll offset

- Meta/CMake/skia.cmake
Commit 35392d4d28bd129ae936bdf470e7d58807a4b10c (#845) moved the `target_*_directories()` calls (or rather their `include()`) before the target declaration, so they fail because of the undefined target. We can fix the problem by using global `*_directories()` instead.
> CMake: Fix invalid target when using system skia

- Tests/LibWeb/Text/expected/console/console-prototype.txt
- Tests/LibWeb/Text/input/console/console-prototype.html
- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Runtime/ConsoleObject.cpp
- Userland/Libraries/LibJS/Runtime/ConsoleObjectPrototype.cpp
- Userland/Libraries/LibJS/Runtime/ConsoleObjectPrototype.h
According to [W3C spec](https://console.spec.whatwg.org/#console-namespace), the global console object's prototype must be an empty object and the prototype's prototype must be `Object.prototype`
> For historical web-compatibility reasons, the [namespace object](https://webidl.spec.whatwg.org/#dfn-namespace-object) for [console](https://console.spec.whatwg.org/#namespacedef-console) must have as its [[Prototype]] an empty object, created as if by [ObjectCreate](https://tc39.github.io/ecma262/#sec-objectcreate)([%ObjectPrototype%](https://tc39.github.io/ecma262/#sec-properties-of-the-object-prototype-object)), instead of [%ObjectPrototype%](https://tc39.github.io/ecma262/#sec-properties-of-the-object-prototype-object).
So, I am creating a custom prototype for the console that is empty and …
> LibJS: Set custom prototype for console object

- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
This change makes `document.createElement('audio').preload = 'auto'` work as expected; except for the actual preloading logic that is.
> LibWeb: Add HTMLMediaElement.preload attribute

- Documentation/RunningTests.md
- Meta/WPT.sh
This PR adds a script that can run the Web Platform Tests and compare different test runs.
I'm fairly sure this won't work on MacOS in its current state because it doesn't use the correct paths for the Ladybird or WebDriver binaries.
> Meta: Add a script to run the Web Platform tests locally

- AK/Span.h
- Tests/AK/TestSpan.cpp
- Tests/AK/TestStringFloatingPointConversions.cpp
- Userland/Libraries/LibTest/Macros.h
Currently, the following test case will actually copy both `a` and `b` when the test macro is expanded:
```c++
ByteBuffer a = { some large buffer };
ByteBuffer b = { some other buffer };
EXPECT_EQ(a, b);
```
While this is obviously inefficient, the main motivator here is that clangd loudly complains about these needless copies :upside_down_face:
> AK+LibTest: Define test expectation macros without copying the input values

- Tests/LibWeb/Text/expected/link-element-media-change-off.txt
- Tests/LibWeb/Text/expected/link-element-media-change.txt
- Tests/LibWeb/Text/input/link-element-media-change-off.html
- Tests/LibWeb/Text/input/link-element-media-change.html
- Userland/Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Userland/Libraries/LibWeb/CSS/CSSStyleSheet.h
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Should fix #1032 
I'm not sure what the expected value is for `MediaList::matches` without first calling evaluate, but for now I've emulated the previous behaviour
> LibWeb: Update stylesheet media value when changing link media attribute

- Tests/LibWeb/Text/expected/URL/set-href-with-valid-hostname-but-invalid-port.txt
- Tests/LibWeb/Text/input/URL/set-href-with-valid-hostname-but-invalid-port.html
- Userland/Libraries/LibURL/Parser.cpp
- Userland/Libraries/LibURL/Parser.h
- Userland/Libraries/LibWeb/DOMURL/DOMURL.cpp
- Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
- Userland/Libraries/LibWeb/HTML/Location.cpp
If given, the URL spec expects the input URL to be manipulated on the fly as it is being parsed, and may ignore any errors thrown by the URL parser.
Previously, we were not exactly following the specs assumption here which resulted in us needed to make awkward copies of the URL in these situations.
For most cases this is not an issue. But it does cause problems for situations where URL parsing would result in a failure (which is ignored by the caller), and the URL is _partially_ updated while parsing.
Such a situation can occur when setting the host of an href alongside a port number which is not valid. It is expected that this situation will result in the host being updates - but not the port number.
Adjust the URL parser API so that it mutates the URL given (if any), and adjust the …
> LibURL+LibWeb: Pass a mutable reference to URL parser

- Tests/LibWeb/Layout/expected/css-dir-selector.txt
- Tests/LibWeb/Layout/expected/writing-modes-direction-flex.txt
- Tests/LibWeb/Layout/expected/writing-modes-direction-inline.txt
- Tests/LibWeb/Layout/input/writing-modes-direction-flex.html
- Tests/LibWeb/Layout/input/writing-modes-direction-inline.html
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Enums.json
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
- Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
This makes a start on issue https://github.com/LadybirdBrowser/ladybird/issues/862, it now renders most of the nav bar in the correct order.
> LibWeb: Begin support for direction property

- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
If a HTTP 401 response we get does not contain a `WWW-Authenticate` header, we should not trigger the logic to ask the user for credentials and retry the request.
This part is hinted at in a TODO / 'Needs testing' remark in the spec but needs to be fleshed out. Raised an upstream issue to do so:
https://github.com/whatwg/fetch/issues/1766
This fixes login forms triggering an infinite fetch loop when providing incorrect credentials.
PR #357 has a similar change but went stale-ish since last month, so this supersedes it. @vicr123 I'll gladly mention you as co-author if you'd like!
> LibWeb: Check presence of `WWW-Authenticate` header in fetch response

- Userland/Libraries/LibJS/Runtime/Date.cpp
- Userland/Libraries/LibJS/Runtime/Intl/DurationFormat.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Userland/Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
- Userland/Libraries/LibJS/Tests/builtins/Intl/DurationFormat/DurationFormat.prototype.format.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.from.js
- Userland/Libraries/LibJS/Tests/builtins/Temporal/TimeZone/TimeZone.js
test262 diff:
```
Diff Tests:
+57 ✅    -57 ❌
test/built-ins/Temporal/Duration/compare/argument-duration-out-of-range.js                                                  ❌ -> ✅
test/built-ins/Temporal/Duration/compare/duration-out-of-range-added-to-relativeto.js                                       ❌ -> ✅
test/built-ins/Temporal/Duration/from/argument-duration-max.js                                                              ✅ -> ❌
test/built-ins/Temporal/Duration/from/argument-duration-out-of-range.js                                                     ❌ -> ✅
test/built-ins/Temporal/Duration/max.js                                                                                     ✅ -> ❌
test/built-ins/Temporal/Duration/out-of-range.js …
```
> LibJS: A collection of Intl.DurationFormat and related areas spec updates

- Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
This change causes HTTP status codes to be set on cached HTTP responses.
Otherwise, without this change, no status codes at all are set on cached HTTP responses — which causes all cached responses to default to being loaded/served with a 200 status code. And as a result of that, if the cached response is from a 30x redirect, then without this change, when that cached 30x response is loaded, we don’t follow the redirect — because we see a 200 status, rather than the expected/original 30x.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/863. Note that this change also reverts the temporary workaround added in https://github.com/LadybirdBrowser/ladybird/commit/f735c464d3f (https://github.com/LadybirdBrowser/ladybird/pull/899).
> LibWeb/Fetch: Set HTTP status code on cached responses

- Tests/LibWeb/Ref/clip-border-radius-with-css-transform.html
- Tests/LibWeb/Ref/reference/clip-border-radius-with-css-transform-ref.html
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Modifies a loop that collects clip rectangles to stop once a box with a
CSS transform is encountered, as its clip still needs to be considered.
> LibWeb: Fix clip for boxes nested into a stacking context with transform

- Tests/LibWeb/Text/expected/focus-events.txt
- Tests/LibWeb/Text/input/focus-events.html
- Userland/Libraries/LibWeb/HTML/Focus.cpp
- Userland/Libraries/LibWeb/UIEvents/FocusEvent.cpp
- Userland/Libraries/LibWeb/UIEvents/FocusEvent.h
We weren't setting the focus event's composed flag and view field correctly.
> LibWeb: Implement the "fire a focus event" spec

- Tests/LibWeb/Text/expected/HTML/invalid-url-attribute-values.txt
- Tests/LibWeb/Text/input/HTML/invalid-url-attribute-values.html
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.cpp
This modifies `HTMLImageElement::current_src()` and `HTMLObjectElement::data()` so that they return the empty string if they are backed by a URL which is invalid.
There are probably other attributes where the same issue is still present.
Fixes 181 subtests in: https://wpt.live/html/semantics/embedded-content/the-img-element/srcset/parse-a-srcset-attribute.html
> LibWeb: Return empty string if URL attribute is invalid

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/Painting/ClipFrame.cpp
- Userland/Libraries/LibWeb/Painting/ClipFrame.h
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.h
- Userland/Libraries/LibWeb/Painting/Paintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.h
After https://github.com/LadybirdBrowser/ladybird/commit/d0da377767a9ca1245e8b505a53ab8969aef8e64 clip frame state is no longer depends on scroll state, so it could be calculated only once for each layout invalidation.
> LibWeb: Remove ViewportPaintable::refresh_clip_frames()

- Userland/Libraries/LibJS/Runtime/Intl/Collator.cpp
- Userland/Libraries/LibJS/Runtime/Intl/Collator.h
- Userland/Libraries/LibJS/Runtime/Intl/CollatorCompareFunction.cpp
- Userland/Libraries/LibJS/Runtime/Intl/CollatorCompareFunction.h
- Userland/Libraries/LibJS/Runtime/Intl/CollatorConstructor.cpp
- Userland/Libraries/LibJS/Runtime/StringPrototype.cpp
- Userland/Libraries/LibJS/Tests/builtins/Intl/Collator/Collator.prototype.compare.js
- Userland/Libraries/LibJS/Tests/builtins/Intl/Collator/Collator.prototype.resolvedOptions.js
- Userland/Libraries/LibJS/Tests/builtins/String/String.prototype.localeCompare.js
- Userland/Libraries/LibUnicode/CMakeLists.txt
- Userland/Libraries/LibUnicode/Collator.cpp
- Userland/Libraries/LibUnicode/Collator.h
We were never able to implement anything other than a basic, locale-unaware collator with the JSON export of the CLDR as it did not have collation data. We can now use ICU to implement collation.
test262 diff:
```
Diff Tests:
+8 ✅    -8 ❌
test/built-ins/String/prototype/localeCompare/15.5.4.9_CE.js                    ❌ -> ✅
test/intl402/Collator/prototype/compare/canonically-equivalent-strings.js       ❌ -> ✅
test/intl402/Collator/prototype/compare/ignorePunctuation.js                    ❌ -> ✅
test/intl402/Collator/prototype/compare/non-normative-basic.js                  ❌ -> ✅
test/intl402/Collator/prototype/compare/non-normative-sensitivity.js            ❌ -> ✅
test/intl402/Collator/prototype/resolvedOptions/ignorePunctuation-default.js    ❌ -> ✅
test/intl402/Collator/usage-de.js …
```
> LibJS+LibUnicode: Fully implement Intl.Collator with ICU

- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
This brings back the old behaviour of Value::to<short>() (and other similar calls), which WASI depends on.
To make sure all similar issues are caught in the future, this commit also introduces an static assertion in Value::to().
> LibWasm: Allow all Value::to<Integral>() calls

- Tests/LibWeb/Layout/expected/crash-tests/html-with-only-a-template-tag.txt
- Tests/LibWeb/Layout/input/crash-tests/html-with-only-a-template-tag.html
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
This appears to have been a bug in the spec which was later corrected - so to fix the crash we can simply remove this assertion.
Fixes: #868
> LibWeb: Handle cases with <template> on the HTML parsing stack

- Tests/LibWeb/Text/expected/HTML/Location-protocol-setter.txt
- Tests/LibWeb/Text/input/HTML/Location-protocol-setter.html
- Userland/Libraries/LibWeb/HTML/Location.cpp
Unfortunately, I don't think it's possible to write a test for anything other than the error case, as a HTTP(S) protocol has to be used.
Fixes 47 subtests in: https://wpt.live/html/browsers/history/the-location-interface/location-protocol-setter.html
> LibWeb: Implement the setter for `location.protocol`

- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
This is an omission I noticed while browsing some code :^)
See:
- https://html.spec.whatwg.org/multipage/parsing.html#special
> LibWeb/HTML: MathML's <ms> is a special tag

- Documentation/RunningTests.md
- Meta/WPT.sh
This PR makes the necessary changes to allow the `WPT.sh` to run on MacOS. 
I've also added a check to ensure the necessary hostnames are present in `/etc/hosts`, as this wasn't checked previously.
> Meta: Make `WPT.sh` script compatible with MacOS

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/input-image.txt
- Tests/LibWeb/Text/expected/usvstring-url-reflection.txt
- Tests/LibWeb/Text/expected/video-canceled-load.txt
- Tests/LibWeb/Text/expected/video-failed-load.txt
- Tests/LibWeb/Text/input/input-image.html
- Tests/LibWeb/Text/input/usvstring-url-reflection.html
- Tests/LibWeb/Text/input/video-canceled-load.html
- Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLEmbedElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLFrameElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLObjectElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLScriptElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLSourceElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLTrackElement.idl
This PR changes some IDL attribute return types to USVString, where the specification says that's what should be used and updates the bindings generator to ensure that reflected USVString attributes behave correctly.
USVString attributes that represent a URL are now explicitly marked with the `URL` extended attribute, as the specification says that they are supposed to behave differently to attributes that don't represent a URL.
Fixes 5 subtests on: http://wpt.live/html/dom/usvstring-reflection.https.html
> LibWeb: Change IDL attribute type to USVString where applicable

- Tests/LibWeb/Text/expected/usvstring-url-reflection.txt
- Tests/LibWeb/Text/input/usvstring-url-reflection.html
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
I noticed that #1059 didn't add URL reflection to the `HTMLImageElement.lowsrc` property (https://html.spec.whatwg.org/multipage/obsolete.html#dom-img-lowsrc)
I found it strange that the [WPT idlharness](https://wpt.live/html/dom/idlharness.https.html?include=HTMLImage.*) already passes but it is in the HTML obsolete spec
> LibWeb: Add URL reflection to obsolete HTMLImageElement lowsrc property

- Documentation/GettingStartedContributing.md
Now that results are available on the main wpt.fyi site, let's point there instead :^)
> Documentation: Update wpt.fyi URL in getting started contributing guide

- .github/workflows/lagom-template.yml
- AK/CMakeLists.txt
- AK/Iterator.h
- Meta/CMake/Swift/swift-settings.cmake
- Meta/CMake/utils.cmake
- Tests/AK/CMakeLists.txt
- Tests/AK/TestAKBindings.swift
- Tests/AK/TestArray.cpp
- Tests/AK/TestFixedArray.cpp
- Tests/AK/TestSpan.cpp
- Tests/AK/TestStringView.cpp
- Tests/AK/TestVector.cpp
Conform SimpleIterator to the random access iterator requirements by pulling in some of the STL. The result is that our iterator is now STL Approved ™️ and our containers can be auto-conformed to Swift protocols.
Also Add a test that swift interop properties are present for containers
> AK: Conform SimpleIterator to std requirements, interop test

- Userland/Libraries/LibJS/Runtime/IteratorHelper.cpp
- Userland/Libraries/LibJS/Runtime/IteratorHelper.h
- Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp
- Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/HTML/NavigableContainer.cpp
- Userland/Libraries/LibWeb/HTML/NavigableContainer.h
- Userland/Libraries/LibWeb/HTML/Navigation.cpp
- Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.cpp
- Userland/Libraries/LibWeb/HTML/SessionHistoryTraversalQueue.h
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Userland/Libraries/LibWeb/HTML/TraversableNavigable.h
- Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp
- Userland/Libraries/LibWeb/Streams/ReadableStreamDefaultReader.h
Further removing our usage of SafeFunction - the remaining use cases being left _mostly_ in ResourceLoader / EventLoop / Timers.
> LibJS+LibWeb: Port some functions from SafeFunction to HeapFunction

- Meta/Lagom/CMakeLists.txt
- Meta/gn/secondary/Tests/BUILD.gn
- Tests/LibThreading/CMakeLists.txt
- Tests/LibThreading/TestThreadPool.cpp
- Userland/Libraries/LibThreading/ThreadPool.h
This PR first aims to fix race conditions in `ThreadPool` involving deadlocks waiting on `m_work_available` and `m_work_done` condition variables. 
Second, it updates the "busy section" as indicated by the `m_busy_count` variable to avoid an early return from `wait_for_all` and a potential underflow of `m_busy_count`. 
Lastly, the `LibThreading` tests are enabled and a test for deadlocks is added for `ThreadPool`.
The individual commit messages provide further detail for the individual changes.
> LibThreading: Resolve race conditions in ThreadPool

- Tests/LibWeb/Text/expected/HTML/HTMLProgressElement-set-attributes.txt
- Tests/LibWeb/Text/input/HTML/HTMLProgressElement-set-attributes.html
- Userland/Libraries/LibWeb/HTML/HTMLProgressElement.cpp
Previously, 0 was returned if `HTMLProgressElement.max` was set to a negative value.
Fixes:  http://wpt.live/html/semantics/forms/the-progress-element/progress.html
> LibWeb: Limit `HTMLProgressElement.max` to positive values

- Tests/LibWeb/Text/expected/css/attribute-selector-case-sensitivity.txt
- Tests/LibWeb/Text/input/css/attribute-selector-case-sensitivity.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
- Userland/Libraries/LibWeb/HTML/AttributeNames.h
The values of attribute selectors are now compared case insensitively by default if the attribute's document is not a HTML document, or the element is not in the HTML namespace.
Fixes: https://wpt.live/html/semantics/selectors/case-sensitivity/values.window.html
> LibWeb: Match attribute selectors case insensitively in XML documents 

- Userland/Libraries/LibWeb/HTML/Canvas/CanvasFilters.idl
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasShadowStyles.idl
- Userland/Libraries/LibWeb/HTML/Canvas/CanvasUserInterface.idl
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
- Userland/Libraries/LibWeb/WebGL/WebGLRenderingContext.idl
- Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextBase.idl
- Userland/Libraries/LibWeb/WebGL/WebGLRenderingContextOverloads.idl
More work towards [GH-24168](https://github.com/SerenityOS/serenity/issues/24168) (yet again 😅)
Knocks quite a bit from https://idl-compare.pages.dev/ :^)
> LibWeb: Stub missing includes for CanvasRenderingContext2D and WebGLRenderingContext

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp
- Userland/Libraries/LibWeb/HTML/BrowsingContext.h
- Userland/Libraries/LibWeb/HTML/CrossOrigin/Reporting.cpp
- Userland/Libraries/LibWeb/MixedContent/AbstractOperations.cpp
I made these changes a week ago and stopped after trying to figure out issues caused by `BrowsingContext::is_top_level` for hours, but I figured it's better to just put a FIXME as the scope these changes already got a bit large. I don't think (but don't remember) if the `coop-check-access-report` commit is necessary for the main changes.
`BrowsingContext::m_parent` has been removed from the spec, and previously `m_parent` was always null.
`BrowsingContext::is_top_level` was already always returning true before because of that, and the updated spec algorithm causes assertions to fail.
This fixes the following example:
```html
<a href="https://ladybird.org" target="test">a
<iframe name="test">
```
clicking the link twice no longer causes it to open in a new tab.
Edit: Retested on master …
> Fix `<a target="name">` not always opening in `<iframe name="name">`

- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
This gives us free devirtualization of some hot calls inside the bytecode interpreter. Most notably the did_trap() checks.
Modest performance improvement on the https://figma.com/ landing page.
> LibWasm: Make BytecodeInterpreter overrides final

- Ladybird/AppKit/UI/LadybirdWebView.mm
Before this change, we were passing CGColorSpaceCreateDeviceRGB() to CGImageCreate(), causing the system to assume that the image data is in a device-specific RGB space without any color profile adjustments.
If your monitor is more vibrant than the assumed profile (for example, a wide-gamut display), colors may appear over-saturated as there's no correction applied for how the display actually renders those colors.
We now pass CGColorSpaceCreateWithName(kCGColorSpaceSRGB) instead, which makes colors look the same in Ladybird as in other browsers. :^)
> Ladybird/AppKit: Use sRGB color space when blitting web content

- Userland/Libraries/LibWeb/HTML/History.cpp
This updates the spec comments and removes a FIXME. Functionally, this doesn't change anything as a fix was already in place.
See:
- https://github.com/whatwg/html/commit/89a387c
- https://github.com/whatwg/html/issues/10551
> LibWeb/HTML: Update "can have its URL rewritten" for spec changes

- Ladybird/Qt/LocationEdit.cpp
Cursor in `LocationEdit` (Address bar) did not return to front after loading - because of that long URLs would hide the domain (location).
Before:  
`SetCursorPosition()` needed two calls as with only one in `highlight_location` block it would still default to the end after load. 
After:  
https://github.com/user-attachments/assets/02bb89b1-ae87-4fbd-88fb-c346ca7a9574
> UI/Qt: Fix long URLs showing the end instead of domain

- Ladybird/Qt/WebContentView.cpp
This is a follow up to GH-1111 to reflect the new signatures that these functions have.
> Ladybird/Qt: Rename convert functions to reflect their new types

- Tests/LibWeb/Text/expected/HTML/HTMLInputElement-invalid-time-digits.txt
- Tests/LibWeb/Text/input/HTML/HTMLInputElement-invalid-time-digits.html
- Userland/Libraries/LibWeb/HTML/Dates.cpp
This prevents a crash in the following WPT tests:
* http://wpt.live/html/semantics/forms/the-input-element/time.html 
* http://wpt.live/html/semantics/forms/the-input-element/time-2.html
> LibWeb: Don't crash when parsing `HTMLInputElement` invalid time values

- .github/actions/setup/action.yml
The latest XCode beta version seems to have changed twice in quick succession.
Is there a better way to do this?
> CI: Update MacOS runner XCode version (again)

- Tests/LibWeb/Text/expected/HTML/Location-search-setter.txt
- Tests/LibWeb/Text/input/HTML/Location-search-setter.html
- Userland/Libraries/LibWeb/HTML/Location.cpp
This commit implements the setter for `location.search`, allowing updates to the query string of the URL.
> LibWeb: Add setter implementation for `location.search`

- Tests/LibWeb/Layout/expected/flex/intrinsic-cross-size-contribution-with-main-size-constraint.txt
- Tests/LibWeb/Layout/input/flex/intrinsic-cross-size-contribution-with-main-size-constraint.html
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
When determining the intrinsic cross size contribution of a flex item with a preferred aspect ratio, we have to account for any min/max constraints in the main axis.
> LibWeb: Adjust flex item intrinsic contributions through aspect ratio

- Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
If the document is disconnected from the navigable by the time a favicon decode completes successfully, we don't want to show the favicon for whatever document is now loaded in the navigable.
Fix this by deferring getting the navigable until after the decode has completed.
> LibWeb: Handle document/navigable disconnection during favicon decode

- Tests/LibWasm/test-wasm.cpp
- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
- Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Userland/Libraries/LibWasm/Parser/Parser.cpp
- Userland/Libraries/LibWasm/Types.h
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h
- Userland/Utilities/wasm.cpp
Prior to funcref, a partial chunk of an invalid module was never needed, but funcref allows a partially instantiated module to modify imported tables with references to its own functions, which means we need to keep the second module alive while that function reference is present within the imported table.
This was tested by the spectests, but very rarely caught as our GC does not behave particularly predictably, making it so the offending module remains in memory just long enough to let the tests pass.
This commit makes it so all function references keep their respective modules alive.
> LibWasm+LibWeb+test-wasm: Refcount Wasm::Module for function references

- Tests/LibWeb/Text/expected/css/small-aspect-ratio.txt
- Tests/LibWeb/Text/input/css/small-aspect-ratio.html
- Userland/Libraries/LibWeb/Layout/Box.cpp
- Userland/Libraries/LibWeb/PixelUnits.h
Previously, a crash would occur in the if `CSSPixelFraction` was given a denominator value less than the resolution of `CSSPixels` (1/64).
We now divide both parts of the ratio by the denominator in this case.
Fixes:
* http://wpt.live/css/css-sizing/aspect-ratio/small-aspect-ratio-crash.html
* http://wpt.live/css/css-sizing/aspect-ratio/fractional-aspect-ratio.html
> LibWeb: Don't crash when converting small `CSS::Ratio` to `CSSPixelFraction`

- Tests/LibWeb/Layout/expected/svg/natural-width-from-svg-attributes.txt
- Tests/LibWeb/Layout/input/svg/natural-width-from-svg-attributes.html
- Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp
- Userland/Libraries/LibWeb/SVG/SVGSVGElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGSVGElement.h
We were incorrectly looking at the CSS computed values for width and height to determine the natural size of <svg> root elements. This meant that elements where the attribute and computed value were different values would end up with incorrect natural size.
Visual progression on https://hemnet.se/
Before:
After:
> LibWeb: Derive SVG root's natural size from width/height attributes

- Userland/Libraries/LibWeb/HTML/HTMLButtonElement.h
- Userland/Libraries/LibWeb/HTML/HTMLElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
Previously, only DOM nodes with `is_editable()` allowed selection via the mouse. This had the unwanted consequence, that read-only input/textarea elements did not allow selection.
Now, `EventHandler::handle_mousedown()` asks the node's non-shadow parent element over the new virtual method `is_child_node_selectable()`, if selection of the node is allowed.
This method is overridden for `HTMLButtonElement` and `HTMLInputElement`, to disallow selection of buttons and placeholders.
Fixes #579
Superseeds https://github.com/LadybirdBrowser/ladybird/pull/604
> LibWeb: Change where content selection via mouse is allowed

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/HTML/data-transfer.txt
- Tests/LibWeb/Text/input/HTML/data-transfer.html
- Userland/Libraries/LibWeb/HTML/DataTransferItem.cpp
- Userland/Libraries/LibWeb/HTML/DataTransferItem.h
- Userland/Libraries/LibWeb/HTML/DataTransferItem.idl
`getAsFile` is used on imgur after drag-and-dropping an image onto its page. This PR also includes `getAsString` as it's closely related and was the last prototype left for `DataTransferItem`.
https://github.com/user-attachments/assets/3f0fbbf2-d117-4441-9fb7-0e134504b052
> LibWeb: Implement `DataTransferItem.prototype.getAsFile()` and `DataTransferItem.prototype.getAsString()`

- Userland/Libraries/LibWeb/FileAPI/Blob.cpp
- Userland/Libraries/LibWeb/FileAPI/Blob.h
- Userland/Libraries/LibWeb/FileAPI/Blob.idl
This pull requests updates Blob.slice to follow the new spec steps, and adds the `[Clamp]` extended attribute to it's arguments to fix http://wpt.live/FileAPI/blob/Blob-slice-overflow.any.html.
> LibWeb/FileAPI: Blob.slice fix & spec update

- Userland/Libraries/LibWebView/SearchEngine.cpp
This pull request adds the Kagi search engine as a selectable option on the Settings > Search Engine menu.
> LibWebView: Add Kagi as a search engine to the list of selectable search engines

- Tests/LibWeb/Ref/inline-visibility-hidden.html
- Tests/LibWeb/Ref/reference/inline-visibility-hidden-ref.html
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
We *could* even skip creating a paintable for hidden nodes, but that means that dynamic updates to the CSS visibility property would require mutating the paint tree, so let's keep it simple for now.
> LibWeb: Don't paint text fragments with CSS visibility:hidden

- AK/AK+Swift.swift
- AK/CMakeLists.txt
- Meta/CMake/Swift/GenerateSwiftHeader.cmake
- Meta/CMake/collections.cmake
- Meta/CMake/lagom_install_options.cmake
- Meta/CMake/patches/git-patch.cmake
- Meta/CMake/patches/swift-collections/0001-CMake-Remove-top-level-binary-module-locations.patch
- Userland/Libraries/LibGfx/CMakeLists.txt
- Userland/Libraries/LibGfx/Color.cpp
- Userland/Libraries/LibGfx/Color.swift
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.swift
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizerHelpers.cpp
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizerHelpers.h
It doesn't do much yet, the fun part was the scaffolding.
We can now more naturally construct Swift.String from AK.StringView and AK.String
The swift-collections library is added as a dependency we can use, via FetchContent.
Depends on #1130
> LibWeb: Add an HTML tokenizer re-implementation in swift 

- Tests/LibCore/TestLibCoreDateTime.cpp
- Tests/LibCore/TestLibCoreFileWatcher.cpp
- Tests/LibJS/test-js.cpp
- Tests/LibUnicode/TestTimeZone.cpp
- Userland/Libraries/LibCore/CMakeLists.txt
- Userland/Libraries/LibCore/FileWatcher.h
- Userland/Libraries/LibCore/FileWatcherLinux.cpp
- Userland/Libraries/LibCore/FileWatcherMacOS.mm
- Userland/Libraries/LibCore/Forward.h
- Userland/Libraries/LibCore/TimeZoneWatcher.h
- Userland/Libraries/LibCore/TimeZoneWatcherLinux.cpp
- Userland/Libraries/LibCore/TimeZoneWatcherMacOS.mm
- Userland/Libraries/LibCore/TimeZoneWatcherUnimplemented.cpp
- Userland/Libraries/LibUnicode/TimeZone.cpp
- Userland/Libraries/LibUnicode/TimeZone.h
- Userland/Libraries/LibWebView/Application.cpp
- Userland/Libraries/LibWebView/Application.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
- Userland/Services/WebContent/ConnectionFromClient.h
- Userland/Services/WebContent/WebContentServer.ipc
Getting the system time zone from disk can be expensive when it is hammered frequently by web pages. We can instead cache the time zone, and only go to disk after we detect a system time zone change.
This contains a handful of fixes to `Core::FileWatcher` to be able to monitor symbolic links (/etc/localtime is usually a link). Then creates a platform-dependent time zone watcher to monitor for time zone changes from the OS, and IPC to propagate that notification over to WebContent.
The following benchmark previously took ~0.8s on Linux and ~2.5s on macOS, and now takes 0ms on both:
```c++
BENCHMARK_CASE(bench_current_time_zone)
{
for (size_t i = 0; i < 100'000; ++i)
(void)Unicode::current_time_zone();
}
```
And a small demo showing we respond to time zone changes: …
> LibCore+LibTimeZone+LibWebView: Create a system time zone cache

- Tests/LibWeb/Text/expected/HTML/HTMLInputElement-cloning-steps.txt
- Tests/LibWeb/Text/expected/HTML/HTMLTextAreaElement-cloning-steps.txt
- Tests/LibWeb/Text/input/HTML/HTMLInputElement-cloning-steps.html
- Tests/LibWeb/Text/input/HTML/HTMLTextAreaElement-cloning-steps.html
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Fixes:
*  https://wpt.live/html/semantics/forms/the-input-element/clone.html
*  http://wpt.live/html/semantics/forms/the-textarea-element/cloning-steps.html
> LibWeb: Implement cloning steps for `HTMLInputElement` and `HTMLTextAreaElement`

- Tests/LibWeb/Text/expected/ShadowDOM/css-hover-shadow-dom.txt
- Tests/LibWeb/Text/input/ShadowDOM/css-hover-shadow-dom.html
- Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp
Before this change, :hover wouldn't match anything outside the shadow boundary when hovering elements inside a shadow tree. This was most noticeable when hovering the text inside an input element and hover styles disappearing from the hosting input element itself.
> LibWeb: Make CSS :hover selector match shadow-inclusive ancestors

- Ladybird/ImageCodecPlugin.cpp
This also eliminates the clang-tidy warning _“Std::move of the const expression has no effect”._
> Ladybird: Remove unnecessary copy of decoded images

- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Userland/Libraries/LibWeb/CSS/ComputedValues.h
- Userland/Libraries/LibWeb/CSS/Enums.json
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Properties.json
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
- Userland/Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
Adds support for parsing `column-span`, `column-width`, and `columns` CSS properties.
Passes additional tests found here:
https://wpt.live/css/css-multicol/parsing/column-span-valid.html
https://wpt.live/css/css-multicol/parsing/column-span-invalid.html
https://wpt.live/css/css-multicol/parsing/column-span-computed.html
https://wpt.live/css/css-multicol/parsing/column-width-valid.html
https://wpt.live/css/css-multicol/parsing/column-width-invalid.html
https://wpt.live/css/css-multicol/parsing/column-width-computed.html
https://wpt.live/css/css-multicol/parsing/columns-valid.html
https://wpt.live/css/css-multicol/parsing/columns-invalid.html
Note: most of the computed tests are still failing due to serialization of the `calc` function being not finished yet.
> LibWeb: Support parsing multicol CSS properties

- Tests/LibWeb/Layout/expected/block-and-inline/inline-block-vertical-align-middle.txt
- Tests/LibWeb/Layout/input/block-and-inline/inline-block-vertical-align-middle.html
- Userland/Libraries/LibWeb/Layout/LineBuilder.cpp
This makes inline icons pop into the right place on https://ahrefs.com/
Before:
After:
> LibWeb: Implement `vertical-align: middle` correctly for atomic inlines

- Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp
I was testing if my webapp URCL Explorer works [URCL Explorer](https://bramotte.github.io/urcl-explorer/old.html?srcurl=examples/urcl/prime-sieve32.urcl) which is a VM for URCL, to my surprise quite a lot of it already works, except for some IO and the WebAssembly JIT compiler.
Turns I used multiple return values in my WASM function, so with this fix the WebAssembly JIT now works.
> LibWeb: Handle multiple result values for WebAssembly functions

- Userland/Libraries/LibUnicode/TimeZone.cpp
- Userland/Libraries/LibUnicode/TimeZone.h
Added this during development while testing some callers, but forgot to remove it before opening a PR.
> LibUnicode: Remove unused time zone cache option

- Userland/Libraries/LibWeb/HTML/HTMLButtonElement.h
- Userland/Libraries/LibWeb/HTML/HTMLElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
This reverts commit 6c9adf3dbc641445a03da9cd1083f89c911504be.
This change breaks e.g. typing into the search box on google.com and comment boxes on github.com.
> Revert "LibWeb: Change where content selection via mouse is allowed"

- Tests/ClangPlugins/CMakeLists.txt
We globally export std::move and std::forward in StdLibExtraDetails.h.
> ClangPlugins: Add -Wno-unqualified-std-cast-call to test compile options

- .github/workflows/clang-plugins.yml
- .github/workflows/lagom-template.yml
The plugins build that runs on master currently uses the same ccache key as non-plugin builds in PRs. This means all clang PR builds are not able to use ccache.
Move the plugins build to a separate job. This job also has sanitizers disabled to make the plugins build quicker.
> CI: Move the clang-plugins-enabled build to a separate job

- AK/AK+Swift.swift
- AK/CMakeLists.txt
- Meta/CMake/Swift/swift-settings.cmake
- Meta/CMake/code_generators.cmake
- Meta/CMake/skia.cmake
- Meta/generate_clang_module_map.py
- Tests/LibWeb/TestHTMLTokenizerSwift.swift
- Tests/LibWeb/TestLibWebSwiftBindings.swift
- Userland/Libraries/LibGfx/CMakeLists.txt
- Userland/Libraries/LibGfx/Color.cpp
- Userland/Libraries/LibGfx/Color.swift
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/HTML/Parser/HTMLToken.swift
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.swift
At the same time, simplify CMakeLists magic for libraries that want to
include Swift code in the library. The Lib-less name of the library is
now always the module name for the library with any Swift additions,
extensions, etc. All vfs overlays now live in a common location to make
finding them easier from CMake functions. A new pattern is needed for
the Lib-less modules to re-export their Cxx counterparts.
Another commit simplifies the CMake magic required to link Skia.
> Meta+Libraries+AK: Append Cxx to imported library module names in swift 

- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
Previously, the conversion assumed that the supplied timeout was in seconds rather than milliseconds.
I found this issue while investigating a timeout that occurs while waiting for `execute_async_script()`  to complete. Unfortunately, this doesn't solve that issue :^(
> LibWeb: Correctly test if WebDriver ExecuteScript timeout is reached

- Tests/LibWeb/TestNumbers.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/Numbers.cpp
- Userland/Libraries/LibWeb/HTML/Numbers.h
This change adds checking for the following spec requirements:
- `<input type=number>`: [If the value of the element is not a valid floating-point number, then set it to the empty string](https://html.spec.whatwg.org/#number-state-(type=number):value-sanitization-algorithm)
- `<input type=range>`: [If the value of the element is not a valid floating-point number, then set it to the best representation, as a floating-point number, of the default value](https://html.spec.whatwg.org/#range-state-(type=range):value-sanitization-algorithm)
That is, it adds checking that `HTMLInputElement.value` is what the spec defines as a “valid floating-point number” when the `type` attribute for the `HTMLInputElement` is either `number` or `range`.
This change causes Ladybird to pass all the failing tests …
> Add “valid floating-point number” for HTMLInputElement.value

- Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
Adjust the translation from Gfx::ScalingMode to Skia SkFilterMode, so
that CSS::ImageRendering::Pixelated will result in
SkFilterMode::kNearest.
Before:
ScalingMode::SmoothPixels -> kLinear
After:
ScalingMode::SmoothPixels -> kNearest
Fixes #1170
Supersedes https://github.com/LadybirdBrowser/ladybird/pull/1171
Idea given by @gmta in https://github.com/LadybirdBrowser/ladybird/pull/1171#pullrequestreview-2262653188
> LibWeb: Use nearest-neighbor scaling for ScalingMode::SmoothPixels

- Meta/CMake/FindSwiftTesting.cmake
- Meta/CMake/Swift/swift-settings.cmake
- Meta/CMake/patches/swift-testing/0001-CMake-Allow-ExternalProjects-to-use-console-with-Nin.patch
- Tests/AK/CMakeLists.txt
- Tests/LibWeb/CMakeLists.txt
- Tests/LibWeb/TestHTMLTokenizerSwift.swift
- Tests/LibWeb/TestLibWebSwiftBindings.swift
- Tests/Resources/SwiftTestMain.swift
Add the upcoming standard swift-testing library as a dependency.
In theory, this library will be included in the swift toolchain. Until that plan is finalized and stabilized for both Linux and macOS, pull it from GitHub using FetchContent.
The Testing.framework shipped with Xcode 16 Beta 5 links against libraries in /usr/lib/swift that only exist in the Developer/ and toolchain sections of the Xcode app, and not on my macOS installation. It also doesn't seem to be added to the rpath of our applications, as it lives in the Xcode Developer directories instead of in the system path. As such, we'll keep building it for macOS from source until the swift-testing maintainers come up with a good way to use the library from CMake, as the current focus is the Swift Package Manager.
The …
> Tests: Convert Swift tests to use Testing module where possible

- Tests/LibWeb/Text/expected/HTML/set-innerHTML-inside-iframe-srcdoc-document.txt
- Tests/LibWeb/Text/input/HTML/set-innerHTML-inside-iframe-srcdoc-document.html
- Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
In particular, there was an assertion failure due to the temporary parser document's "about base URL" being empty when trying to "parse a URL" during parsing.
We fix this by copying the context element's document's about base URL to the temporary parsing document while parsing a fragment.
This fixes a crash when loading search results on https://amazon.com/
> LibWeb: Fix crash when setting innerHTML inside iframe srcdoc document

- AK/AK+Swift.swift
- Tests/LibWeb/TestHTMLTokenizerSwift.swift
- Userland/Libraries/LibGfx/Color.swift
- Userland/Libraries/LibWeb/HTML/Parser/HTMLToken.swift
- Userland/Libraries/LibWeb/HTML/Parser/HTMLTokenizer.swift
And add tests! This implementation closely follows the current C++
implementation, replacing macros and gotos with a slightly more
complex state machine. It's very possible that an async version that
yields tokens on "emit" would be even simpler, but let's get this
one working first :).
> LibWeb: Implement the Data state for the Swift tokenizer 

- Tests/LibWeb/Layout/expected/grid/grid-placement-shorthand-single-custom-ident.txt
- Tests/LibWeb/Layout/input/grid/grid-placement-shorthand-single-custom-ident.html
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
According to [the specs](https://www.w3.org/TR/css-grid-2/#placement-shorthands) when setting the 'grid-row' and 'grid-column' shorthand CSS property to a single `<custom-ident>` value, both 'grid-row-start'/'grid-column-start' and 'grid-row-end'/'grid-column-end' should be set to that `<custom-ident>`.
This PR ensures this behaviour. It also adds a layout regression test.
The difference can be seen on the [homepage of the Guardian](https://www.theguardian.com/europe) in the two screenshots below. :)
> LibWeb/CSS: Set correct longhand values when using grid-placement shorthand

- Userland/Libraries/LibWeb/SVG/SVGImageElement.h
Fixes the clang plugin failure mentioned here: https://github.com/LadybirdBrowser/ladybird/pull/1198#issuecomment-2317126132
> LibWeb: Use the correct base class in for SVGImageElement

- Userland/Libraries/LibJS/Heap/BlockAllocator.cpp
- Userland/Libraries/LibJS/Heap/HeapBlock.cpp
- Userland/Libraries/LibJS/Heap/Internals.h
Before this change, we were hard-coding 4 KiB. This meant that systems with a 16 KiB native page size were wasting 12 KiB per HeapBlock on nothing, leading to worse locality and more mmap/madvise churn.
We now query the system page size on startup and use that as the HeapBlock size.
The only downside here is that some of the pointer math for finding the base of a HeapBlock now has to use a runtime computed value instead of a compile time constant. But that's a small price to pay for what we get.
> LibJS: Use the system native page size as the HeapBlock::block_size

- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Modification to insure that the thumb size never goes below a minimum.  This is intended to address issue 1166.
> Sets A Minimum Thumb Size

- Userland/Libraries/LibWeb/SVG/SVGImageElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGImageElement.h
This PR adds animation support to SVG `<image>` tags. The performance is currently not the best when many images are displayed. The code looks very similar to the animation code in `HTMLImageElement` - this code should probably be shared.
Example:
https://github.com/user-attachments/assets/51a57a6a-63a8-405a-be5f-2de01d829f80
> LibWeb: Support animations in embedded SVG images

- Tests/LibWeb/Ref/position-sticky-bottom.html
- Tests/LibWeb/Ref/position-sticky-left.html
- Tests/LibWeb/Ref/position-sticky-right.html
- Tests/LibWeb/Ref/position-sticky-should-stay-within-containing-block.html
- Tests/LibWeb/Ref/position-sticky-top.html
- Tests/LibWeb/Ref/reference/position-sticky-bottom-ref.html
- Tests/LibWeb/Ref/reference/position-sticky-left-ref.html
- Tests/LibWeb/Ref/reference/position-sticky-right-ref.html
- Tests/LibWeb/Ref/reference/position-sticky-should-stay-within-containing-block-ref.html
- Tests/LibWeb/Ref/reference/position-sticky-top-ref.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.cpp
- Userland/Libraries/LibWeb/Layout/Node.cpp
- Userland/Libraries/LibWeb/Layout/Node.h
- Userland/Libraries/LibWeb/Painting/ClipFrame.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.h
- Userland/Libraries/LibWeb/Painting/DisplayList.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
- Userland/Libraries/LibWeb/Painting/ScrollFrame.h
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.h
Sticky positioning is implemented by modifying the algorithm for
assigning and refreshing scroll frames. Now, elements with
"position: sticky" are assigned their own scroll frame, and their
position is refreshed independently from regular scroll boxes.
Refreshing the scroll offsets for sticky boxes does not require display
list invalidation.
A separate hash map is used for the scroll frames of sticky boxes. This
is necessary because a single paintable box can have two scroll frames
if it 1) has "position: sticky" and 2) contains scrollable overflow.
> LibWeb: Add "position: sticky" support

- AK/Base64.cpp
- Toolchain/BuildVcpkg.sh
- vcpkg.json
The main goal here is to now hopefully be able to fully implement the Uint8Array base64 proposal.
> AK+Meta: Update simdutf to version 5.3.4, make use of new Base64URL option

- Tests/LibWeb/Layout/expected/grid/restart-fr-algorithm-if-less-than-base-size.txt
- Tests/LibWeb/Layout/input/grid/restart-fr-algorithm-if-less-than-base-size.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Implements:
"If the product of the hypothetical fr size and a flexible track’s flex factor is less than the track’s base size, restart this algorithm treating all such tracks as inflexible."
Fixes https://github.com/LadybirdBrowser/ladybird/issues/1211
> LibWeb: Implement missing step in GFC fr size calculation

- Tests/LibWeb/Text/expected/DOM/FormAssociatedElement-setRangeText.txt
- Tests/LibWeb/Text/input/DOM/FormAssociatedElement-setRangeText.html
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
This method replaces range of text in its respective element with a new string.
Relevant WPT test: http://wpt.live/html/semantics/forms/textfieldselection/textfieldselection-setRangeText.html
Not all subtests are currently passing for the above test. I believe this is because the document cursor gets set to the wrong position meaning `selectionStart` and `selectionEnd` may report the incorrect values, depending on the selection mode used.
> LibWeb: Implement setRangeText for input and textarea elements

- Base/res/ladybird/inspector.js
- Tests/LibWeb/Text/expected/DOM/FormAssociatedElement-selection-type-change.txt
- Tests/LibWeb/Text/expected/DOM/FormAssociatedElement-selection.txt
- Tests/LibWeb/Text/input/DOM/FormAssociatedElement-selection-type-change.html
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.h
- Userland/Libraries/LibWeb/Internals/Internals.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.h
This adds the following behavior for the DOM node/attribute editor in the Inspector:
* If the user double clicks on an attribute name, the name is selected.
* If the user double clicks on an attribute value, the value text (sans the surrounding quotes) is selected.
* Otherwise, double clicks select the entire text range.
https://github.com/user-attachments/assets/d504e178-50b8-4234-9008-90322ea9c3d9
> LibWeb+LibWebView: Auto-select subtext when editing DOM nodes/attributes

- Tests/LibWeb/Ref/reference/scrollable-content-inside-fixed-position-box-ref.html
- Tests/LibWeb/Ref/scrollable-content-inside-fixed-position-box.html
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Scroll offset of body does not affect position of fixed elements, so nearest scrollable lookup should early return from ancestor scrollable lookup loop once "position: fixed" box is encountered.
Fixes regression introduced in 866608532a743df9e3d10c0dae9aacd7d0b89ce6
> LibWeb: Account for fixed position in nearest scrollable ancestor lookup

- Documentation/Browser/Patterns.md
This change adds documentation on using the `rebaseline-libweb-test` script to regenerate the expectations file for a `LibWeb/Text/input` test.
> Documentation: Explain how to use the rebaseline-libweb-test script

- Tests/LibWeb/Layout/input/overflow-with-padding.html
The test happened to pass anyway because `visible` is the default value.
> Tests/LibWeb: Correct typo in "overflow: visible"

- Userland/Libraries/LibWeb/HTML/HTMLTableCellElement.idl
This small update fixes a number of tests in https://wpt.live/html/dom/reflection-tabular.html, increasing the number of passing tests from 5930 to 6086/6116.
> LibWeb: Add `scope` attribute to HTMLTableCellElement

- Tests/LibWeb/Text/expected/element-get-bounding-client-rect-of-sticky.txt
- Tests/LibWeb/Text/input/element-get-bounding-client-rect-of-sticky.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Element.cpp
Use offset from ScrollFrame which is an actual value a box is shifted by while painting.
Also change `update_paint_and_hit_testing_properties_if_needed()` to refresh scroll frames state, because `getBoundingClientRect()` now depends on them.
Fixes wrong file tree sidebar location and excessive layout invalidations caused by some miscalculation on JS-side when wrong bounding client rect is provided on Github PR pages like https://github.com/LadybirdBrowser/ladybird/pull/1232/files
> LibWeb: Fix getBoundingClientRect() for elements with "position: sticky"

- Userland/Libraries/LibJS/Lexer.cpp
- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Parser.h
- Userland/Libraries/LibJS/Token.h
By checking the lengths and then looking directly at the bytes, the
generated code becomes a lot nicer.
This gives a 1.23x speedup when parsing the JS from https://x.com
+ two small improvements that I ran across while investigating this
> LibJS: Make JS lexer handle 2 and 3 character tokens faster

- Tests/LibWeb/Layout/expected/flex/flex-column-reverse-constrained-wrap.txt
- Tests/LibWeb/Layout/expected/flex/flex-constrained-wrap-reverse.txt
- Tests/LibWeb/Layout/expected/flex/flex-row-reverse-constrained-wrap.txt
- Tests/LibWeb/Layout/input/flex/flex-column-reverse-constrained-wrap.html
- Tests/LibWeb/Layout/input/flex/flex-constrained-wrap-reverse.html
- Tests/LibWeb/Layout/input/flex/flex-row-reverse-constrained-wrap.html
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
When either `row-reverse` or `column-reverse` was set along with `flex-wrap: wrap`. The order of every item was being reversed, instead of just each line:
Now it only reverses the line:
This PR also implements the `flex-wrap: wrap-reverse`. It reverses the order of flex lines, and swaps the cross-start and cross-end directions. (https://drafts.csswg.org/css-flexbox/#flex-wrap-property)
> LibWeb: Fix behavior of reverse wrapping flex containers

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Range.cpp
- Userland/Libraries/LibWeb/Forward.h
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/HTML/Navigable.h
- Userland/Libraries/LibWeb/InvalidateDisplayList.h
- Userland/Libraries/LibWeb/Painting/Paintable.cpp
- Userland/Libraries/LibWeb/Painting/Paintable.h
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
Previously, content wasn't always redrawn when a repaint was necessary. This PR fixes the following issues
* The media now repainted when its state changes
* The cursor is redrawn when moved
* Animated images are repainted when their animation state changes
Example from: https://en.wikipedia.org/wiki/File:United_States_Navy_Band_-_Amhr%C3%A1n_na_bhFiann.ogg
NOTE: I had to disable scripts to get this page to work correctly.
Before:
https://github.com/user-attachments/assets/e532c8c0-5737-42a0-8792-1bc8c0e25fb3
After:
https://github.com/user-attachments/assets/bd9fc5ea-7153-46f4-9323-51c4f94b5dea
Fixes: #1256
> LibWeb: Invalidate the display list when calling `set_needs_display()`

- Tests/LibWeb/Text/expected/synthetic-event-constructor-istrusted-check.txt
- Tests/LibWeb/Text/input/synthetic-event-constructor-istrusted-check.html
- Userland/Libraries/LibWeb/DOM/Event.cpp
This change ensures that when then the code corresponding to the “create an event” operation at https://dom.spec.whatwg.org/#concept-event-create is called, the event’s `isTrusted` is set to true — as the spec requires.
That causes the failures for the following WPT tests to pass:
- https://wpt.fyi/results/html/semantics/forms/the-input-element/checkbox.html?run_id=5080423051034624
- https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element/dialog-close.html?run_id=5080423051034624
…and there are likely a number of similar WPT tests that hit this same code path which this commit will cause to be changed to passes.
Otherwise, without this change, the “create event” implementation doesn’t conform to the spec requirements – nor behave interoperably with other existing …
> LibWeb: Make “create an event” set the event’s isTrusted to true

- Userland/Libraries/LibWeb/SVG/SVGImageElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGImageElement.h
This allows us to remove an otherwise unnecessary `DocumentObserver` that was previously being used.
> LibWeb: Relayout document when SVG image is successfully loaded

- Tests/LibWeb/Ref/reference/sticky-box-with-percentage-insets-ref.html
- Tests/LibWeb/Ref/sticky-box-with-percentage-insets.html
- Userland/Libraries/LibWeb/Layout/LayoutState.cpp
Reading of https://drafts.csswg.org/css-position revealed I was wrong assuming sticky insets need to be resolved relative to containing block.
> LibWeb: Resolve "position: sticky" insets relative to scrollport

- Tests/LibWeb/Text/expected/collapse-selection-inside-shadow-root.txt
- Tests/LibWeb/Text/input/collapse-selection-inside-shadow-root.html
- Userland/Libraries/LibWeb/Selection/Selection.cpp
The [most recent working draft](https://www.w3.org/TR/2023/WD-selection-api-20230516/#dom-selection-collapse) has a different step 3. This PR updates the implemented algorithm to match it.
> LibWeb: Update `Selection.collapse` algorithm

- AK/Base64.cpp
- AK/Base64.h
- Tests/AK/TestBase64.cpp
- Tests/LibJS/test-js.cpp
- Userland/Libraries/LibJS/CMakeLists.txt
- Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h
- Userland/Libraries/LibJS/Runtime/TypedArray.cpp
- Userland/Libraries/LibJS/Runtime/Uint8Array.cpp
- Userland/Libraries/LibJS/Runtime/Uint8Array.h
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.fromBase64.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.fromHex.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.prototype.setFromBase64.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.prototype.setFromHex.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.prototype.toBase64.js
- Userland/Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.prototype.toHex.js
test262 diff (we pass all of the `Uint8Array` tests):
```
Diff Tests:
+56 ✅    -56 ❌
Diff Tests:
test/built-ins/Uint8Array/fromBase64/alphabet.js                         ❌ -> ✅
test/built-ins/Uint8Array/fromBase64/descriptor.js                       ❌ -> ✅
test/built-ins/Uint8Array/fromBase64/ignores-receiver.js                 ❌ -> ✅
test/built-ins/Uint8Array/fromBase64/illegal-characters.js               ❌ -> ✅
test/built-ins/Uint8Array/fromBase64/last-chunk-handling.js              ❌ -> ✅
test/built-ins/Uint8Array/fromBase64/length.js                           ❌ -> ✅
test/built-ins/Uint8Array/fromBase64/name.js                             ❌ -> ✅
test/built-ins/Uint8Array/fromBase64/nonconstructor.js                   ❌ -> ✅
test/built-ins/Uint8Array/fromBase64/option-coercion.js …
```
> LibJS: Implement the Uint8Array to/from base64 proposal

- Tests/LibJS/test-js.cpp
- Userland/Libraries/LibJS/Runtime/Date.cpp
- Userland/Libraries/LibJS/Runtime/Date.h
- Userland/Libraries/LibJS/Runtime/DatePrototype.cpp
- Userland/Libraries/LibUnicode/DateTimeFormat.cpp
- Userland/Libraries/LibUnicode/ICU.cpp
- Userland/Libraries/LibUnicode/ICU.h
- Userland/Libraries/LibUnicode/TimeZone.cpp
- Userland/Libraries/LibUnicode/TimeZone.h
- Userland/Services/WebContent/ConnectionFromClient.cpp
* Cache the resolved system time zone identifier
* Avoid needless BigInt conversions
Using the following benchmark:
```c++
BENCHMARK_CASE(foo)
{
for (size_t i = 0; i < 1'000'000; ++i)
(void)JS::local_time(0);
}
```
These patches reduce the runtime from 2.5s to 1.2s on my machine. So, still room on the table for more improvements, but these are some low hanging fruit.
> LibJS: A couple LocalTime optimizations

- Ladybird/AppKit/Application/Application.mm
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/Qt/Application.cpp
- Ladybird/Qt/Application.h
- Ladybird/Qt/Tab.cpp
- Userland/Libraries/LibWebView/Application.cpp
- Userland/Libraries/LibWebView/Application.h
- Userland/Libraries/LibWebView/InspectorClient.cpp
- Userland/Libraries/LibWebView/ViewImplementation.cpp
If the Downloads directory exists, we will use it (note that this will respect the `XDG_DOWNLOAD_DIR` environment variable).
Otherwise, we will ask the UI layer to retrieve a download directory from the user. This directory is not saved, so it will be re-prompted every time. Once a proper settings UI is complete, we will of course integrate with that for persistent settings.
Fixes #780, fixes #854
> LibWebView+UI: Request users for a download directory if `~/Downloads` does not exist

- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
Add an enum and warn when setting to sync/async.
This is used by https://maps.google.com/
Making sure the decoding happen at the right time is a little bit beyond my current understanding, but happy to try implementing that if someone can point me in the right direction.
> HTMLImageElement: Improve decoding stub

- Userland/Libraries/LibWebView/SourceHighlighter.cpp
When we want to inject a CSS counter for a line, we need to be sure to handle if we had previously opened a styled span for the current source substring. For example, if we see a new line in the middle of a comment, we will have previously opened the following tag:
<span class="comment">
So when injecting a new line and the <span class="line"> element (for CSS counters), we need to close the previous span and insert a newly opened tag to continue using the style.
Before:
After:
Fixes #1243
> LibWebView: Properly handle new lines inside styled view-source elements

- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMediaElement.h
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
If a key is pressed when the media player is in focus, which causes the media player to perform some action, that key event is no longer propagated further.
> LibWeb: Don't propagate key events that are handled by the media player

- Tests/LibWeb/Layout/expected/grid/min-height-from-text.txt
- Tests/LibWeb/Layout/input/grid/min-height-from-text.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
This addresses issue https://github.com/LadybirdBrowser/ladybird/issues/1177
When computing the min size, `should_treat_max_width_as_none` was always being called regardless of the dimension. This PR uses the appropriate one for the dimension.
> LibWeb: Fix grid min height not being computed correctly when a max width was set

- Ladybird/AppKit/UI/Event.mm
- Userland/Libraries/LibWeb/HTML/Navigable.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
When an editable node is focused and one of the arrow/home/end keys are
pressed while shift is held, we will now create or update the document's
selection. There is a bit of nuance to the behavior here, which matches
how the cursor behaves in other engines.
We will of course want to abstract this in the future to extend any non-
editable node text selections. This also does not implement holding ctrl
to jump by word, rather than grapheme.
https://github.com/user-attachments/assets/e23405e2-1eb0-4085-ac40-2dec4493f919
> LibWeb: Selection improvements for editable text nodes

- Tests/LibWeb/Ref/reference/transform-box-ref.html
- Tests/LibWeb/Ref/transform-box.html
- Userland/Libraries/LibWeb/CSS/Transformation.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
- Userland/Libraries/LibWeb/Painting/PaintableBox.h
This fixes issue https://github.com/LadybirdBrowser/ladybird/issues/1269
The content box was always being used to resolve transform length percentages, instead of the transform box. This PR factors out computing the transform box from `PaintableBox::resolve_paint_properties`. So that `Transformation::to_matrix` can use it, as its reference box.
> LibWeb: Use transform-box for resolving percentage transform values

- Userland/Libraries/LibWeb/Painting/PaintableBox.cpp
Slight regression from #1184. If an overflown box had a height less than the hard-coded minimum scrollbar length, we would paint the scrollbar past the end of the box:
This reduces the minimum scrollbar size, and limits it to the height/width of the box:
Firefox actually seems to hide the scrollbar if the box is less than 40px. I haven't done that here, to err on the side of at least indicating that the box is scrollable.
> LibWeb: Limit the minimum scrollbar size to the overflown box's size

- Ladybird/AppKit/Application/ApplicationDelegate.h
- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/main.mm
- Ladybird/Qt/Application.cpp
- Ladybird/Qt/Application.h
- Ladybird/Qt/BrowserWindow.cpp
- Ladybird/Qt/BrowserWindow.h
- Ladybird/Qt/main.cpp
- Userland/Libraries/LibWebView/Application.cpp
- Userland/Libraries/LibWebView/Application.h
- Userland/Utilities/headless-browser.cpp
The main motivator here was noticing that `--disable-sql-database` did not work with AppKit. Rather than re-implementing this there, move ownership of these classes to `WebView::Application`, so that each UI does not need to individually worry about it.
> LibWebView+UI: Move the database and cookie jar to WebView::Application

- Userland/Libraries/LibUnicode/CharacterTypes.cpp
- Userland/Libraries/LibUnicode/CharacterTypes.h
- Userland/Libraries/LibWeb/DOM/CharacterData.cpp
- Userland/Libraries/LibWeb/DOM/CharacterData.h
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/DOM/Document.h
- Userland/Libraries/LibWeb/DOM/Position.cpp
- Userland/Libraries/LibWeb/DOM/Position.h
- Userland/Libraries/LibWeb/Page/EditEventHandler.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
- Userland/Libraries/LibWeb/UIEvents/KeyCode.h
This supports using the ctrl+arrow keys on Linux and option+arrow keys on macOS to jump by word in text nodes (as well as holding shift to select the jumped word).
https://github.com/user-attachments/assets/e107ecdc-e6ae-4ef9-a0c8-120f6f8f3062
> LibWeb: Support jumping across word boundaries in text nodes

- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.h
- Userland/Services/WebContent/WebDriverConnection.cpp
This change updates `ExecuteScript::execute_script()` and `ExecuteScript::execute_script()` to bring their behavior in line with each other and the current specification text.
Instances of the variable `timeout` have also been renamed to `timeout_ms`, for clarity.
Unfortunately, this doesn't seem to have any affect on the number of timeouts we're currently seeing :^(
> LibWeb/WebDriver: Align execute script methods with the specification

- Tests/LibWeb/Text/expected/aria-attribute-reflection.txt
- Tests/LibWeb/Text/input/aria-attribute-reflection.html
- Userland/Libraries/LibWeb/ARIA/ARIAMixin.idl
This change makes the `aria-relevant` content attribute and the `ariaRelevant` IDL/DOM attribute reflect — which makes the Ladybird behavior interoperable with the implemented behavior in other existing engines.
Otherwise, without this change, Ladybird fails the relevant test case in https://wpt.fyi/results/html/dom/aria-attribute-reflection.html — which other existing engines all pass.
Note that at https://w3c.github.io/aria/#ARIAMixin the `ARIAMixin` IDL definition in the current ARIA spec actually lacks the `ariaRelevant` attribute — but I’ve raised https://github.com/w3c/aria/pull/2326 to get that fixed.
And note that this change doesn’t actually add support for the `aria-relevant` — because we _already_ have support for it; the only thing that was missing was that it wasn’t in our …
> LibWeb: Make aria-relevant and ariaRelevant reflect

- Tests/LibWeb/Text/expected/aria-attribute-reflection.txt
- Tests/LibWeb/Text/input/aria-attribute-reflection.html
Now we that we (again) have emoji being rendered as expected, one possible good internal use is: adding colored indicators in test cases.
This change adds green and red pass/fail emoji indicators to an in-tree test — to make it easier to manually scan through the test results and quickly see which cases are passing, and which are failing.
Output looks like this:
> Tests: Add some colorful pass/fail emoji to a test case

- Tests/LibWeb/TestConfig.ini
These frequently time out on macOS CI.
> LibWeb: Disable worker-blob and worker-location tests for now

- Base/res/ladybird/inspector.css
- Base/res/ladybird/inspector.html
- Base/res/ladybird/inspector.js
- Ladybird/AppKit/UI/Inspector.mm
- Ladybird/Qt/InspectorWidget.cpp
- Ladybird/Qt/InspectorWidget.h
- Ladybird/cmake/ResourceFiles.cmake
- Userland/Libraries/LibWeb/Internals/Inspector.cpp
- Userland/Libraries/LibWeb/Internals/Inspector.h
- Userland/Libraries/LibWeb/Internals/Inspector.idl
- Userland/Libraries/LibWeb/Page/Page.h
- Userland/Libraries/LibWebView/CookieJar.cpp
- Userland/Libraries/LibWebView/InspectorClient.cpp
- Userland/Libraries/LibWebView/InspectorClient.h
- Userland/Libraries/LibWebView/ViewImplementation.h
- Userland/Libraries/LibWebView/WebContentClient.cpp
- Userland/Libraries/LibWebView/WebContentClient.h
- Userland/Services/WebContent/PageClient.cpp
- Userland/Services/WebContent/PageClient.h
- Userland/Services/WebContent/WebContentClient.ipc
This adds a storage tab which contains just a cookie viewer for now. In the future, storage like Local Storage and Indexed DB can be added here as well.
https://github.com/user-attachments/assets/07d318b4-0139-493a-8da4-fae83a75f86d
> LibWebView: Add a storage tab to the Inspector to manage cookies

- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/TabController.h
- Ladybird/AppKit/UI/TabController.mm
- Ladybird/Qt/BrowserWindow.cpp
- Userland/Libraries/LibWebView/Application.cpp
- Userland/Libraries/LibWebView/Options.h
This makes the "Enable Scripting" checkbox in the Debug menu unchecked by default.
> UI: Add a `--disable-scripting` option to disable scripting by default

- Userland/Libraries/LibWeb/CSS/CSSLayerBlockRule.cpp
- Userland/Libraries/LibWeb/CSS/CSSLayerStatementRule.cpp
- Userland/Libraries/LibWeb/CSS/CSSRule.cpp
- Userland/Libraries/LibWeb/CSS/CSSRule.h
This makes cascade layer filtering take <2% of CPU time when loading https://vercel.com instead of 30%.
> LibWeb: Cache the qualified layer name in CSSRule

- Tests/LibWeb/Text/expected/SVG/getBBox-outermost-svg-element-crash.txt
- Tests/LibWeb/Text/input/SVG/getBBox-outermost-svg-element-crash.html
- Userland/Libraries/LibWeb/SVG/SVGElement.cpp
- Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
Previously, doing this would cause a crash, as we assumed that the caller always had a parent `SVGSVGElement`. We now return an empty `DOMRect` in this case. This matches the behavior of other browsers.
Fixes #739
> LibWeb: Don't crash when calling getBBox() on the outermost SVG element

- Base/res/ladybird/inspector.css
- Ladybird/AppKit/UI/TabController.mm
- Userland/Libraries/LibWeb/HTML/HTMLSelectElement.cpp
- Userland/Libraries/LibWebView/Native.css
\+ a build fix for a compiler error I just started getting on macOS
> LibWeb+LibWebView: Some native coloring for widgets used on the inspector

- Tests/LibWeb/Text/expected/HTML/HTMLFormElement-action.txt
- Tests/LibWeb/Text/expected/HTML/formAction-attribute.txt
- Tests/LibWeb/Text/input/HTML/HTMLFormElement-action.html
- Tests/LibWeb/Text/input/HTML/formAction-attribute.html
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h
- Userland/Libraries/LibWeb/HTML/HTMLButtonElement.idl
- Userland/Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl
Also implement the `formAction` attribute for `HTMLInputElement`.
Fixes the following web platform tests
* https://wpt.live/html/semantics/forms/attributes-common-to-form-controls/formaction.html
* https://wpt.live/html/semantics/forms/attributes-common-to-form-controls/formAction_document_address.html
> LibWeb: Return document URL if formAction attribute is missing or empty

- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
1. Place the cursor where the user clicked when an editable text node is focused:
https://github.com/user-attachments/assets/0ac98c62-0cd9-4f36-bd23-f5efe386afeb
2. Allow using shift + arrow/home/end keys to modify selections of non-editable text nodes
https://github.com/user-attachments/assets/d3440c4a-20c4-4cc9-be9e-101293ac7818
> LibWeb: A couple cursor + selection quality of life improvements

- Tests/LibWeb/rebaseline-libweb-test
This change enables using the `rebaseline-libweb-test` script with Debug and Sanitizer builds — and allows specifying which build to use when using `rebaseline-libweb-test` to generate new test-expectations files.
The mechanism used is to check the BUILD_PRESET environment variable.
Otherwise, without this change, there’s no way to use the `rebaseline-libweb-test` script with Debug and Sanitizer builds — except by manually hacking the script locally to hardcode a directory name.
If this seems too hacky/kludgy and it’d seem better to instead add a new command-line option (rather than relying on an environment variable), I could update the patch to do it that way instead.
> Tests: Allow specifying a build preset for rebaseline-libweb-test

- Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Userland/Libraries/LibJS/Runtime/NativeFunction.cpp
- Userland/Libraries/LibJS/Tests/regress/bogus-program-counter.js
This didn't make any sense, and was already handled by pushing a new execution context anyway.
By simply removing these bogus lines of code, we fix a bug where throwing inside a function whose bytecode was shorter than the calling function would crash trying to generate an Error stack trace (because the bytecode offset we were trying to symbolicate was actually from the longer caller function, and not valid in the callee function.)
This makes --log-all-js-exceptions less crash prone and more helpful.
Supersedes #816 
Note: I reduced this by painstakingly shaving down the minified JavaScript from https://rauchg.com/ until I had a simplified repro 😅
> LibJS: Don't copy current program counter into new execution contexts

- Userland/Libraries/LibGfx/FontCascadeList.h
Getting the first font in a font cascade list with an empty font list results in an OOTB index error. If the font list is empty, the last resort font should be returned instead.
This fixes an error when loading https://vut.cz
> LibWeb: Consider last resort font in font list

- Userland/Libraries/LibGfx/Font/TypefaceSkia.cpp
The "include/" #include prefix is not used anywhere else in the codebase, and does not work with distro packages.
(For some reason both variants work with vcpkg skia)
> LibGfx: Fix inconsistent skia includes

- Userland/Libraries/LibJS/Parser.cpp
- Userland/Libraries/LibJS/Tests/regress/allow-await-in-a-func-def-assigned-to-default-param.js
Fixes a bug when "'Await' expression is not allowed in formal parameters of an async function" is thrown for "await" encountered in a function definition assigned to a default function parameter.
Fixes loading of https://excalidraw.com/
> LibJS: Reset in_formal_parameter_context after entering a new function

- Userland/Libraries/LibJS/Runtime/DateConstructor.cpp
- Userland/Libraries/LibJS/Runtime/VM.cpp
- Userland/Libraries/LibJS/Runtime/VM.h
- Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
- Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp
Used on https://rauchg.com
Before:
After:
> LibJS: Add "month day, year" support to Date.parse

- Tests/LibWeb/Text/expected/HTML/HTMLInputElement-select-crash.txt
- Tests/LibWeb/Text/input/HTML/HTMLInputElement-select-crash.html
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Fixes: http://wpt.live/html/semantics/forms/textfieldselection/selection.html
> LibWeb: Don't attempt to set selection if control has no selectable text

- Tests/LibWeb/Layout/expected/grid/fit-content-2.txt
- Tests/LibWeb/Layout/expected/grid/fit-content-3.txt
- Tests/LibWeb/Layout/input/grid/fit-content-3.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Fixes implementation of the following line from the spec: "However, limit the growth of any fit-content() tracks by their fit-content() argument."
Now we correctly apply a limit to increased growth limit rather than to the planned increase.
Change in "Tests/LibWeb/Layout/input/grid/fit-content-2.html" is a progression and "Item as wide as the content." is actually as wide as a content.
> LibWeb: Clamp growth limit after adding planned increase in GFC

- Userland/Libraries/LibWeb/CSS/Selector.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Basically:
- Allow immediate child (>) combinator to get quickly rejected by the ancestor filter.
- Bucket div#foo and div.foo as ID/class respectively, rather than as tag(div)
- Bucket :is(.foo) and :where(.foo) as class rules rather than as generic rules
Average full style update times on my machine:
- https://vercel.com 470ms -> 240ms
- https://tailwindcss.com 1400ms -> 350ms
> LibWeb: Some juicy speedups for selector matching on vercel.com and Tailwind CSS sites in general

- Tests/LibWeb/Text/expected/DOM/AbortSignal-any-crash.txt
- Tests/LibWeb/Text/input/DOM/AbortSignal-any-crash.html
- Userland/Libraries/LibWeb/DOM/AbortSignal.cpp
Previously, there was a bug in the specification that would cause an assertion failure, due to the abort event being fired before all dependent signals were aborted.
Relevant WHATWG issue: https://github.com/whatwg/dom/issues/1293
Fixes: https://wpt.live/dom/abort/crashtests/any-on-abort.html
> LibWeb: Abort dependent signals before firing abort event

- Userland/Libraries/LibWeb/WebDriver/Client.cpp
- Userland/Libraries/LibWeb/WebDriver/Client.h
- Userland/Services/WebContent/WebDriverClient.ipc
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
- Userland/Services/WebDriver/Client.cpp
- Userland/Services/WebDriver/Client.h
For issue #1040
Following the structure of the ReleaseActions endpoints, define analogous classes and methods for PerformActions
> WebDriver: Add boilerplate for endpoint 15.7 Perform Actions

- Tests/LibWeb/Text/expected/getComputedStyle-grid-template-rows-columns.txt
- Tests/LibWeb/Text/input/getComputedStyle-grid-template-rows-columns.html
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
If grid-template-rows or grid-template-columns queried for a box that is not a grid container, the result should be computed value instead of null.
Fixes crashing in inspector.
> LibWeb: Return computed grid-template-rows/columns if there's no used

- Meta/ladybird.sh
- Meta/shell_include.sh
CMake reads CMakePresets.json, which is before it reads CMakeLists.txt. 
This causes CMake Error: Unrecognized "version" field #980. 
Fix is to check CMake version in ladybird.sh itself.
> Meta: Check for CMake version in ladybird.sh

- Tests/LibWeb/Layout/expected/grid/fixed-tracks-followed-by-repeat-auto-fill.txt
- Tests/LibWeb/Layout/input/grid/fixed-tracks-followed-by-repeat-auto-fill.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Fixes crashing in
https://wpt.live/css/css-grid/grid-definition/grid-auto-fit-columns-001.html
> LibWeb: Fix wrong assumption that repeat() is always first track [GFC]

- Userland/Libraries/LibWeb/ARIA/ARIAMixin.idl
This change adds the `[CEReactions]` attributes to all ARIA attributes in the ARIAMixin WebIDL — as required by the WebIDL in the current spec at https://w3c.github.io/aria/#ARIAMixin, and by the WPT test case at http://wpt.live/custom-elements/reactions/AriaMixin-string-attributes.html, and as implemented in other existing engines.
Otherwise, without this change, Ladybird doesn’t conform to the current spec, fails all those tests, and isn’t interoperable with other engines.
Note that this change causes Ladybird to pass 78 tests at https://wpt.fyi/results/custom-elements/reactions/AriaMixin-string-attributes.html?product=ladybird which it has been failing. The reason we don’t yet pass all 88 of those tests there is: there are 5 attributes which were added to the ARIA spec after our …
> LibWeb: Add CEReactions to all IDL for all ARIA attributes

- Userland/Libraries/LibWeb/ARIA/ARIAMixin.idl
Also, remove blank lines. (https://w3c.github.io/aria/#ARIAMixin source doesn’t have any blank lines, and it’s not clear that the blank lines in ours follow any intended structure/logic.)
> LibWeb: Replace tabs with 4 spaces in ARIAMixin.idl

- Ladybird/Qt/LocationEdit.cpp
Previously, right clicking highlighted text in the location bar would cause the current selection to be lost.
> UI/Qt: Don't change LocationEdit cursor position on right click

- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Skia is more permissive when it comes to font loading, compared to our own OpenType implementation, which it has superseded, parsing an invalid TTF does not result in an error but rather produces a font that is incorrectly displayed. This change updates the FontLoader to address this behavior and to stop attempting to parse a font as a last resort when format detection has failed.
Fixes regression on x.com when text is not displayed introduced in a9d5a99568b41c83d724a9d8f81c1fdfe10a830e
> LibWeb: Do not try to load a font if format detection has failed

- Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-justify-content.txt
- Tests/LibWeb/Layout/expected/flex/justify-content-1.txt
- Tests/LibWeb/Layout/expected/flex/justify-content-with-margin-auto-child.txt
- Tests/LibWeb/Layout/expected/grid/justify-content.txt
- Tests/LibWeb/Layout/expected/grid/justify-items.txt
- Tests/LibWeb/Layout/expected/grid/justify-self.txt
- Tests/LibWeb/Layout/input/flex/abspos-flex-child-static-position-with-justify-content.html
- Tests/LibWeb/Layout/input/flex/justify-content-1.html
- Tests/LibWeb/Layout/input/flex/justify-content-with-margin-auto-child.html
- Tests/LibWeb/Layout/input/grid/justify-content.html
- Tests/LibWeb/Layout/input/grid/justify-items.html
- Tests/LibWeb/Layout/input/grid/justify-self.html
- Userland/Libraries/LibWeb/CSS/Enums.json
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
These will need to be updated once we have support for writing modes, especially in grid contexts where `left`/`right` are currently equivalent to `start`/`end`.
> LibWeb: Implement justify-*: left/right

- Userland/Libraries/LibWebView/SearchEngine.cpp
This pull request will add the scientific browser Google Scholar to the list of search engines which you can select in the settings menu.
> LibWebView: Add GoogleScholar search engine to the list of selectable search engines

- AK/CopyOnWrite.h
- Userland/Libraries/LibURL/URL.h
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.cpp
- Userland/Libraries/LibWeb/CSS/StyleProperties.h
This makes the way we've implemented the CSS `revert` keyword a lot less expensive.
Until now, we were making a deep copy of all property values at the start of each cascade origin. (Those are the values that `revert` would bring us back to if encountered.)
With this patch, the revert property set becomes a shallow copy, and we only clone the property set if the cascade ends up writing something.
This knocks a 5% profile item down to 1.3% on https://tailwindcss.com
> LibWeb: Make CSS::StyleProperties copy-on-write internally

- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Once we know the final value of the `content` property for a pseudo-element, we can bail early if the value is `none` or `normal` (note that `normal` only applies to `::before` and `::after`).
In those cases, no pseudo-element will be generated, so everything that follows in StyleComputer would be wasted work.
This noticeably improves performance on many pages, such as https://tailwindcss.com/ where style updates go from 360ms -> 250ms.
> LibWeb: Bail early from doomed pseudo-element style computation

- Tests/LibWeb/Text/expected/HTML/HTMLInputElement-radio-groups.txt
- Tests/LibWeb/Text/input/HTML/HTMLInputElement-radio-groups.html
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
Previously, we were searching for other radio buttons from the document root, rather than the element root.
Fixes 2 subtests in the following test: https://wpt.live/html/semantics/forms/the-input-element/radio.html
> LibWeb: Don't group radio buttons from different trees together

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.h
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.h
- Userland/Libraries/LibWeb/Layout/SVGFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/SVGFormattingContext.h
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
Absolutely positioned boxes do not affect the size of the formatting
context they belong to, so it's safe to skip their layout entirely
when calculating intrinsic size.
> LibWeb: Skip abspos boxes layout in intrinsic sizing mode

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSKeyword.cpp
- Tests/LibWeb/Text/expected/css/revert-layer.txt
- Tests/LibWeb/Text/input/css/revert-layer.html
- Userland/Libraries/LibWeb/CSS/CSSStyleValue.h
- Userland/Libraries/LibWeb/CSS/Keywords.json
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CSSKeywordValue.h
With the introduction of the cascade layer, the 5th CSS-wide keyword, `revert-layer`, has been added.
> LibWeb/CSS: Implement revert-layer

- Tests/LibWeb/Layout/expected/abspos-box-with-replaced-element.txt
- Tests/LibWeb/Layout/expected/flex/abspos-flex-child-static-position-with-justify-content.txt
- Tests/LibWeb/Layout/expected/flex/abspos-flex-child-with-percentage-height.txt
- Tests/LibWeb/Layout/expected/grid/abspos-with-grid-container-as-parent.txt
- Tests/LibWeb/Layout/input/flex/abspos-flex-child-with-percentage-height.html
- Tests/LibWeb/Layout/input/grid/abspos-with-grid-container-as-parent.html
- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
- Userland/Libraries/LibWeb/Layout/Box.cpp
- Userland/Libraries/LibWeb/Layout/Box.h
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.h
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.h
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/LayoutState.h
Before this change, a formatting context was responsible for layout of absolutely positioned boxes whose FC root box was their parent (either directly or indirectly). This only worked correctly when the containing block of the absolutely positioned child did not escape the FC root. This is because the width and height of an absolutely positioned box are resolved based on the size of its containing block, so we needed to ensure that the containing block's layout was completed before laying out an absolutely positioned box.
With this change, the layout of absolutely positioned boxes is delayed until the FC responsible for the containing block's layout is complete. This has affected the way we calculate the static position. It is no longer possible to ask the FC for a box's static position, …
> LibWeb: Make FC of containing block responsible for abspos layout

- Userland/Libraries/LibWeb/DOM/Document.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.cpp
- Userland/Libraries/LibWeb/Painting/ClippableAndScrollable.h
- Userland/Libraries/LibWeb/Painting/DisplayList.cpp
- Userland/Libraries/LibWeb/Painting/ScrollFrame.h
- Userland/Libraries/LibWeb/Painting/ViewportPaintable.cpp
Calculating cumulative scroll offset is visible in profiles on very large pages, so let's add a simple caching for it.
>  LibWeb: Add a cache for ScrollFrame::cumulative_offset()

- Meta/gn/secondary/Userland/Libraries/LibWeb/CSS/BUILD.gn
- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp
- Userland/Libraries/LibWeb/CSS/Parser/Parser.h
- Userland/Libraries/LibWeb/CSS/Sizing.cpp
- Userland/Libraries/LibWeb/CSS/Sizing.h
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLImageElement.h
- Userland/Libraries/LibWeb/HTML/SourceSet.cpp
- Userland/Libraries/LibWeb/HTML/SourceSet.h
- Userland/Libraries/LibWeb/Painting/BackgroundPainting.cpp
Noticed our spec comments didn't match the current spec, so this updates a few algorithms related to the `sizes` attribute. (Yay spec comments!)
Also, because it's what led me to investigate `sizes` in the first place: skip the algorithm entirely when the attribute is empty, so that we don't get useless parse errors spamming the console.
http://wpt.live/html/semantics/embedded-content/the-img-element/sizes/parse-a-sizes-attribute-standards-mode.html passes now, and didn't before, but that might be a fluke? It's hard to tell because a few of these `sizes`-related WPT tests are flakey.
> LibWeb: Update "parse a sizes attribute" and related algorithms

- Tests/LibWeb/Text/expected/DOM/FormAssociatedElement-selection.txt
- Tests/LibWeb/Text/input/DOM/FormAssociatedElement-selection.html
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Userland/Libraries/LibWeb/HTML/FormAssociatedElement.h
- Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Userland/Libraries/LibWeb/Page/EventHandler.cpp
Fixes #1339.
- `{HTMLTextAreaElement, HTMLInputElement}::set_value` now uses `set_the_selection_range` instead of `set_cursor_position`.
- `{HTMLTextAreaElement, HTMLInputElement}::selection_was_changed` now only moves the cursor if the node is already focused.
- The `FormAssociatedElement-selection` test now waits for all selection events.
- `FormAssociatedTextControlElement::set_the_selection_range` no longer skips sending events for empty selections (this was unnecessary and didn't match other browsers).
> LibWeb: Don't move focus when setting input value

- Tests/LibWeb/Layout/expected/grid/abspos-item-with-grid-area-and-percentage-size.txt
- Tests/LibWeb/Layout/input/grid/abspos-item-with-grid-area-and-percentage-size.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.h
Fixes incorrect percentage length resolution for abspos boxes contained by a grid.
> LibWeb: Use grid area as available size for abspos contained in GFC

- Tests/LibWeb/Layout/expected/grid/item-with-percentage-max-width.txt
- Tests/LibWeb/Layout/expected/grid/min-max-content.txt
- Tests/LibWeb/Layout/input/grid/item-with-percentage-max-width.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Change try_compute_width() to check whether min-width/max-width or width is auto instead of always using `computed_values.width()`.
`grid/min-max-content.html` test is affected but it's progression.
> LibWeb: Fix min-width and max-width resolution for grid items

- Userland/Libraries/LibWeb/HTML/HTMLMetaElement.cpp
- Userland/Libraries/LibWeb/HTML/HTMLMetaElement.h
The mapping from string keyword to state enum was incorrect, meaning the FIXME for unimplemented states was never printed.
This PR also includes branches for states which do not require any handling on insertion, most notably "content-type", which is already handled in the HTML parser.
> LibWeb: Improve handling of http-equiv pragmas

- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
Use this cached pointer to the containing block's used values when obviously possible. This avoids a hash lookup each time, and these hash lookups do show up in profiles.
> LibWeb: Use LayoutState::UsedValues::containing_block_used_values() more

- Tests/LibWeb/Layout/expected/table/abspos-pseudo-element-inside-table.txt
- Tests/LibWeb/Layout/input/table/abspos-pseudo-element-inside-table.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/TableFormattingContext.h
TFC is not aware of how to correctly calculate a static position for abspos boxes, but assigning (0, 0) is better than crashing during abspos item layout.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/1382
>  LibWeb: Assign static position for abspos boxes nested into TFC

- Meta/WPT.sh
This change allows the user to specify the format of the log file to be generated by the `WPT.sh` script. Multiple logging arguments may now be specified.
The supported logging arguments are: `--log-raw`, `--log-unittest`, `--log-xunit`, `--log-html`, `--log-mach`, `--log-tbpl`, `--log-grouped`, `--log-chromium`, `--log-wptreport` and `--log-wptscreenshot`. These arguments act the same as the equivalent arguments supported by `wpt run`.
The short `--log` argument may also be used as an alias for `--log-raw`.
> Meta: Support all available logging formats in WPT.sh script

- Userland/Libraries/LibWeb/CMakeLists.txt
- Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp
- Userland/Libraries/LibWeb/WebDriver/ElementReference.h
- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp
- Userland/Libraries/LibWeb/WebDriver/ExecuteScript.h
- Userland/Services/WebContent/WebDriverClient.ipc
- Userland/Services/WebContent/WebDriverConnection.cpp
- Userland/Services/WebContent/WebDriverConnection.h
- Userland/Services/WebDriver/Session.cpp
The main thing we were missing is the `switch-to-frame` endpoint. However, that requires a whole lot of tracking of the currently active browsing context in WebDriver. We previously performed all actions on the original page's top-level BC, but now track and use the BC set by the `switch-to-window` and `switch-to-frame` endpoints.
With these patches, the cookie tests run, but do not pass. The tests expect nameless cookies to be supported, which is not allowed by the current official cookie RFC. However, other browsers support this, and there is a [draft RFC](https://datatracker.ietf.org/doc/draft-ietf-httpbis-rfc6265bis/) which specs this reality.
So this PR contains just the changes needed to make the cookie tests stop timing out, which will hopefully make more tests run as well. I'll …
> WebDriver: Features and fixes needed to run the cookie tests

- Userland/Libraries/LibGfx/TextLayout.cpp
- Userland/Libraries/LibGfx/TextLayout.h
- Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Userland/Libraries/LibWeb/Layout/InlineLevelIterator.cpp
- Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
All places where text shaping happens, the callback is used to simply append a glyph into the end of glyphs vector. This change removes the callback parameter and makes the text shaping function return a glyph run.
> LibGfx+LibWeb: Simplify text shaping API by removing per glyph callback

- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
compute_width() could never be invoked for abspos boxes because they are skipped during normal layout and processed in
parent_context_did_dimension_child_root_box()
> LibWeb: Remove unreachable abspos width calculation in BFC

- Tests/LibWeb/Layout/expected/grid/abspos-item-with-grid-area-and-percentage-size-2.txt
- Tests/LibWeb/Layout/input/grid/abspos-item-with-grid-area-and-percentage-size-2.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Although the parameter is named "available size," it is always supposed
to represent the containing block size whenever it has a definite value.
Therefore, it is possible to simply use this value instead of performing
a containing block lookup.
This change actually improves correctness for grid items whose
containing block is defined by the grid area, as
`Node::containing_block()` does not account for this.
> LibWeb: Use available size in calculate_inner_height()

- Tests/LibWeb/Layout/expected/grid/abspos-item-with-grid-area-aligned-in-center.txt
- Tests/LibWeb/Layout/input/grid/abspos-item-with-grid-area-aligned-in-center.html
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
Fixes yet another case of GFC bug, where Node::containing_block() should not be used for grid items, because their containing block is grid area which is not represented in layout tree.
> LibWeb: Use grid area size for abspos grid items alignment

- Tests/LibWeb/Layout/expected/block-and-inline/abspos-with-percentage-padding.txt
- Tests/LibWeb/Layout/expected/grid/abspos-item-with-percentage-padding.txt
- Tests/LibWeb/Layout/input/block-and-inline/abspos-with-percentage-padding.html
- Tests/LibWeb/Layout/input/grid/abspos-item-with-percentage-padding.html
- Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp
The `calculate_inner_width()` and `calculate_inner_height()` resolve percentage paddings using the width returned by
`containing_block_width_for()`. However, this function does not account for grids where the containing block is defined by the grid area to which an item belongs.
This change fixes the issue by modifying `calculate_inner_width()` and `calculate_inner_height()` to use the already resolved paddings from the layout state. Corresponding changes ensure that paddings are resolved and saved in the state before box-sizing is handled.
As a side effect, this change also improves abspos layout for BFC where now paddings are resolved using padding box of containing block instead of content box of containing block.
> LibWeb: Fix "box-sizing: border-box" resolution for abspos items

- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.h
Before this change, each BFC child that established an FC root was laid out at least twice: the first time to perform a normal layout, and the second time to perform an intrinsic layout to determine the automatic content height. With this change, we avoid the second run by querying the formatting context for the height it used after performing the normal layout.
> LibWeb: Avoid layout run to calculate auto height of FC child in BFC

- Tests/LibWeb/Layout/expected/css-round-function-with-percentage-value.txt
- Tests/LibWeb/Layout/input/css-round-function-with-percentage-value.html
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Userland/Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Function is defined as `round(<rounding-strategy>?, A, B?)`
With this change resolved type is `typeof(resolve(A))`, instead of `typeof(A)`.
For example `round(up, 20%, 1px)` with 200px percentage basis is now correctly resolved in 40px instead of 40%.
Progress on https://www.notion.so/ landing page.
Before:
After:
> LibWeb: Use correct resolved type for round() CSS function

- Userland/Libraries/LibWeb/Layout/BlockFormattingContext.cpp
...because calculate_inner_width() assumes layout state has resolved paddings that could be used to account for "box-sizing: border-box".
Fixes regression introduced in 5f74da6ae8ad470ad0ce325f570faa97292384ba
> LibWeb: Resolve floating box's paddings before width calculation

- Tests/LibWeb/Text/expected/Worker/Worker-crypto.txt
- Tests/LibWeb/Text/input/Worker/Worker-crypto.html
- Tests/LibWeb/Text/input/Worker/worker-crypto.js
- Userland/Libraries/LibWeb/HTML/Window.cpp
- Userland/Libraries/LibWeb/HTML/Window.h
- Userland/Libraries/LibWeb/HTML/Window.idl
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
- Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.idl
This change moves the `crypto()` getter from `Window` to `WorkerOrWindowGlobalScope`. This aligns our implementation with the WebCrypto specification.
This prevents 52 WPT tests in the `WebCryptoAPI` directory from timing out when this change is put on top of #1416.
> LibWeb: Expose `crypto` object to workers

- Ladybird/AppKit/Application/ApplicationDelegate.h
- Ladybird/AppKit/Application/ApplicationDelegate.mm
- Ladybird/AppKit/UI/LadybirdWebView.h
- Ladybird/AppKit/UI/LadybirdWebView.mm
- Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp
- Ladybird/AppKit/UI/LadybirdWebViewBridge.h
- Ladybird/AppKit/UI/Tab.h
- Ladybird/AppKit/UI/Tab.mm
- Ladybird/AppKit/UI/TabController.h
- Ladybird/AppKit/UI/TabController.mm
This has been implemented in Qt for quite some time. This patch adds the
same feature to AppKit. This is needed to run many WPT subtests with the
AppKit chrome. This is also needed to handle `window.open`, `target=_blank`
link clicks, etc.
Fixes #1386 
One such WPT test that requires this is:
```bash
» ./Meta/WPT.sh run --log-mach results.log /cookies/domain/domain-attribute-idn-host.sub.https.html
Running 1 tests in web-platform-tests
Ran 1 tests finished in 4.2 seconds.
• 1 ran as expected. 0 tests skipped.
```
https://github.com/user-attachments/assets/3fa11469-fd84-4f6e-8386-c60c118164f9
> UI/AppKit: Implement opening child web views from e.g. `window.open`

- Tests/LibWeb/rebaseline-libweb-test
At least on my Linux machine using zsh, this line was interpreted as
`( cd "$build_dir" || echo ... ) && exit 1`
instead of the intended
`cd "$build_dir" || ( echo ... && exit 1 )`
...meaning that it always exited regardless of whether it found the build dir or not. So, let's make the intended precedence explicit.
> Tests: Make rebaseline's build-dir check unambiguous

- Userland/Libraries/LibWeb/DOM/Element.cpp
- Userland/Libraries/LibWeb/DOM/Element.h
- Userland/Libraries/LibWeb/DOM/Text.cpp
- Userland/Libraries/LibWeb/DOM/Text.h
This is to match https://github.com/whatwg/html/pull/10561, but also includes the previous changes made in https://github.com/whatwg/html/pull/9796 which we hadn't implemented.
> LibWeb: Update "compute the auto directionality" algorithm to match spec

- Tests/LibWeb/Layout/expected/svg/abspos-svg-polygon.txt
- Tests/LibWeb/Layout/input/svg/abspos-svg-polygon.html
- Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Currently we are crashing in `verify_cast<BlockContainer>(box)` on attempt to create BFC for SVG box.
> LibWeb: Print FIXME instead of crashing in abspos SVG element layout

- Tests/LibWeb/Text/expected/css/getComputedStyle-no-paintable.txt
- Tests/LibWeb/Text/input/css/getComputedStyle-no-paintable.html
- Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Previously, attempting to get the computed value for a grid-template-rows or grid-template-columns property would cause a crash if the element had no associated paintable.
This fixes a crash in the inspector that I saw when clicking on a `<br>` tag.
> LibWeb: Don't crash when resolving style of grid template properties
