Tests/LibWeb/TestConfig.ini
Ref https://github.com/LadybirdWebBrowser/ladybird/issues/19
=> Test: Skip flakey Text/input/WebAnimations/misc/DocumentTimeline test

Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Equivalent of Serenity PR: https://github.com/SerenityOS/serenity/pull/24537
The spec and implementation's comments had diverged a little, this brings them in line :)
=> LibWeb/Fetch: Update "HTTP fetch" algorithm to latest spec comments

Meta/gn/secondary/Userland/Libraries/LibWeb/Fetch/Infrastructure/BUILD.gn, Tests/LibWeb/Text/expected/HTML/crossOrigin-attribute.txt, Tests/LibWeb/Text/expected/HTML/img-element-fetch-priority.txt, Tests/LibWeb/Text/input/HTML/crossOrigin-attribute.html, Tests/LibWeb/Text/input/HTML/img-element-fetch-priority.html, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.h, Userland/Libraries/LibWeb/Fetch/Infrastructure/NetworkPartitionKey.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/NetworkPartitionKey.h, Userland/Libraries/LibWeb/HTML/AttributeNames.h, Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.idl, Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLScriptElement.idl, Userland/Libraries/LibWeb/HTML/Scripting/Fetching.idl
Original Serenity PR: https://github.com/SerenityOS/serenity/pull/24491
=> Implement HTML{Image,Script,Link}.fetchPriority

Meta/CMake/ca_certificates_data.cmake, Meta/CMake/public_suffix.cmake
This should make it possible to do a fully offline build.
=> Meta: ENABLE_NETWORK_DOWNLOADS for ca_certificates and public_suffix

Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLImageElement.h, Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl
Implements enough of HTMLImageElement::decode for it to not break websites and actually load an image :)
=> LibWeb: Implement HTMLImageElement::decode with a few FIXMEs

Meta/Lagom/CMakeLists.txt, Userland/Libraries/LibCore/Environment.cpp, Userland/Libraries/LibCore/System.h, Userland/Libraries/LibJS/Heap/BlockAllocator.cpp
https://github.com/SerenityOS/serenity/pull/24273
https://github.com/SerenityOS/serenity/issues/23375
=> LibCore: Port BSD Fixes from serenity

Meta/gn/secondary/Userland/Libraries/LibWeb/BUILD.gn, Meta/gn/secondary/Userland/Libraries/LibWeb/MixedContent/BUILD.gn, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/MixedContent/AbstractOperations.cpp, Userland/Libraries/LibWeb/MixedContent/AbstractOperations.h
Original Serenity PR: https://github.com/SerenityOS/serenity/pull/24479
=> LibWeb: Implement Mixed Content spec

Tests/LibWeb/Text/expected/HTML/script-element-referrer-policy.txt, Tests/LibWeb/Text/input/HTML/script-element-referrer-policy.html, Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h, Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.idl, Userland/Libraries/LibWeb/HTML/HTMLAreaElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLAreaElement.h, Userland/Libraries/LibWeb/HTML/HTMLAreaElement.idl, Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp, Userland/Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.h, Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLIFrameElement.idl, Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.idl, Userland/Libraries/LibWeb/HTML/HTMLScriptElement.idl, Userland/Libraries/LibWeb/ReferrerPolicy/AbstractOperations.cpp, Userland/Libraries/LibWeb/ReferrerPolicy/AbstractOperations.h
Original Serenity PR: https://github.com/SerenityOS/serenity/pull/24500
=> LibWeb: Implement referrerPolicy attributes

Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp, Userland/Libraries/LibWeb/CSS/FontFaceSet.h, Userland/Libraries/LibWeb/CSS/FontFaceSet.idl, Userland/Libraries/LibWeb/HTML/EventNames.h
Serenity PR: https://github.com/SerenityOS/serenity/pull/24540
=> LibWeb/CSS: Make FontFaceSet extend EventTarget & implement event handlers

.github/actions/setup/action.yml, .github/workflows/libjs-test262.yml, Documentation/AdvancedBuildInstructions.md, Meta/generate-libwasm-spec-test.py
Pulled from https://github.com/SerenityOS/serenity/pull/24502. At this point, all the crashing spec-tests have been fixed (I hope), so I just need to add SIMD support.
Edit:
Just kidding, apparently there's a spec test that doesn't pass through ubsan
=> LibWasm: Generate all spec-tests properly

Userland/Libraries/LibWasm/AbstractMachine/Validator.cpp, Userland/Libraries/LibWasm/AbstractMachine/Validator.h, Userland/Libraries/LibWasm/Parser/Parser.cpp
Just a small pack of validator fixes. This gets [binary.wast](https://github.com/WebAssembly/testsuite/blob/main/binary.wast) to fully pass! Let me know if you want me to squash these small commits into one larger one.
=> LibWasm: Some small and miscellaneous validator fixes

Ladybird/AppKit/UI/LadybirdWebView.h, Ladybird/AppKit/UI/LadybirdWebView.mm, Ladybird/AppKit/UI/SearchPanel.h, Ladybird/AppKit/UI/SearchPanel.mm, Ladybird/AppKit/UI/Tab.mm
=> UI/AppKit: Display query results on the find-in-page panel

Tests/LibWeb/Text/expected/css/cssFloat-property.txt, Tests/LibWeb/Text/expected/css/keyframes-css-rules.txt, Tests/LibWeb/Text/expected/css/style-declaration-parent-rule.txt, Tests/LibWeb/Text/input/css/cssFloat-property.html, Tests/LibWeb/Text/input/css/keyframes-css-rules.html, Tests/LibWeb/Text/input/css/style-declaration-parent-rule.html, Userland/Libraries/LibWeb/CSS/CSSKeyframeRule.cpp, Userland/Libraries/LibWeb/CSS/CSSKeyframeRule.h, Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.cpp, Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.h, Userland/Libraries/LibWeb/CSS/CSSKeyframesRule.idl, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.h, Userland/Libraries/LibWeb/CSS/CSSStyleDeclaration.idl, Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp, Userland/Libraries/LibWeb/CSS/Parser/Parser.cpp, Userland/Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp
Went down some rabbit holes prompted by FIXME log messages when loading NeoGAF for some other bug report. :)
=> LibWeb: A handful of CSSOM web compatibility fixes

Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp, Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
All the `table*.wast` test files fully pass now!
=> LibWasm: Implement rest of table instructions

Userland/Libraries/LibWeb/Painting/CommandExecutorSkia.cpp
=> LibWeb: A bunch of Skia-painter fixes

Userland/Libraries/LibWeb/CSS/MediaQuery.cpp, Userland/Libraries/LibWeb/CSS/MediaQuery.h, Userland/Libraries/LibWeb/HTML/EventNames.h, Userland/Libraries/LibWeb/HTML/HTMLStyleElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLStyleElement.h, Userland/Libraries/LibWeb/HTML/HTMLStyleElement.idl, Userland/Libraries/LibWeb/IndexedDB/IDBOpenDBRequest.cpp, Userland/Libraries/LibWeb/IndexedDB/IDBOpenDBRequest.h, Userland/Libraries/LibWeb/IndexedDB/IDBOpenDBRequest.idl, Userland/Libraries/LibWeb/IndexedDB/IDBRequest.cpp, Userland/Libraries/LibWeb/IndexedDB/IDBRequest.h, Userland/Libraries/LibWeb/IndexedDB/IDBRequest.idl
This pull request resolves 6 FIXMEs in the project :^)
=> LibWeb: Some FIXME hunting :^)

Userland/Libraries/LibWeb/HTML/Navigation.cpp
See:
- https://github.com/whatwg/html/pull/10393
=> LibWeb: Don't set hashChange for classic history navigate events

Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
Overflows are no longer possible. With this, I'm fairly confident that the memory instructions are pretty much fully spec-compliant. The only memory-related tests that are failing now are ones that ensure we don't allow multiple memories. Not really sure what to do about those (other than skip) because we support the multi-memory proposal.
=> LibWasm: Check source and destination offsets in `memory.init`

Userland/Libraries/LibWeb/Page/Page.cpp
Prior to this change, our find in page function always highlighted the first match whenever the query was updated. After this change the current match index is set such that it is the first match to occur after the end of the current selection.
This means the current match position is not lost if the user modifies their existing query.
This matches the behavior of find in page in other browsers.
Note: I've made it so that the first match is returned if there is no active query. This matches the behavior of Firefox, but not Chrome. I did this solely because it felt slightly nicer to me to start from the beginning when entering a fresh query (plus Chrome highlights all matches by default, so this behavior is maybe not so necessary for them :shrug:) .
Before: …
=> LibWeb: Base the current find in page position on the current selection

AK/OwnPtr.h, Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp, Userland/Libraries/LibCore/ThreadEventQueue.cpp
Cherry-pick from https://github.com/SerenityOS/serenity/pull/24513 and https://github.com/SerenityOS/serenity/pull/24586
=> LibCore+LibIPC: Cherry-pick some LibCore and LibIPC fixes from serenity

Userland/Libraries/LibIPC/Connection.cpp, Userland/Libraries/LibIPC/Connection.h, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Services/WebWorker/ConnectionFromClient.cpp
=> LibIPC: Mixed bag of small cleanups

Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp, Userland/Libraries/LibWeb/Painting/Command.h, Userland/Libraries/LibWeb/Painting/DisplayListPlayerCPU.cpp, Userland/Libraries/LibWeb/Painting/DisplayListPlayerGPU.cpp, Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp, Userland/Libraries/LibWeb/Painting/DisplayListRecorder.cpp
One actual fix for paths rendering and a couple of small cosmetic changes.
=> LibWeb: A pack of small Skia painter improvements

.devcontainer/features/ladybird/install.sh
=> Meta: Update devcontainer install script with new deps

Ladybird/Android/BuildLagomTools.sh, Ladybird/Android/src/main/cpp/ALooperEventLoopImplementation.cpp, Ladybird/Android/src/main/java/org/serenityos/ladybird/LadybirdServiceConnection.kt, Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp
This PR has a fix that makes Android builds more stable
It also has fixes warning and usage of deprecated functions
=> Android: Stability fixes and other minor ones

Userland/Utilities/headless-browser.cpp
Useful to check what ref-tests are currently broken with Skia painter.
=> headless-browser: Add CLI argument to enable Skia painter

Ladybird/AppKit/Application/ApplicationDelegate.mm, Ladybird/AppKit/UI/TabController.h, Ladybird/AppKit/UI/TabController.mm
This is my first time using working with the AppKit codebase, hopefully I've made all the changes I need to :)
cc @trflynn89
=> Ladybird/AppKit: Add actions to set navigator compatibility mode

Tests/LibWeb/Text/expected/SVG/svg-className-attribute.txt, Tests/LibWeb/Text/input/SVG/svg-className-attribute.html, Userland/Libraries/LibWeb/HTML/MessageEvent.cpp, Userland/Libraries/LibWeb/HTML/MessageEvent.h, Userland/Libraries/LibWeb/HTML/MessageEvent.idl, Userland/Libraries/LibWeb/SVG/AttributeNames.cpp, Userland/Libraries/LibWeb/SVG/AttributeNames.h, Userland/Libraries/LibWeb/SVG/SVGElement.cpp, Userland/Libraries/LibWeb/SVG/SVGElement.h, Userland/Libraries/LibWeb/SVG/SVGElement.idl, Userland/Libraries/LibWeb/SVG/SVGGeometryElement.idl
Some missing attributes I found tonight :^)
=> LibWeb: MessageEvent.initMessageEvent & SVGElement attributes

Documentation/BuildInstructionsLadybird.md
The flake no longer has the ladybird attribute
=> Meta: Docs: Update Nix dev-shell commands

Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp, Userland/Libraries/LibWeb/Crypto/KeyAlgorithms.cpp
Implementation of the big-endian branches for the functions marked as little endian only in `LibWeb/Crypto`.
=> LibWeb: Implement CryptoAlgorithms and KeyAlgorithms for big-endian systems

Userland/Libraries/LibWeb/CSS/Default.css
=> LibWeb: Define width for -webkit-slider-runnable-track

Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
...and radial gradient bug fix.
=> LibWeb: Basic conic gradient support in Skia painter

Meta/ladybird.sh
Also set ASAN/UBSAN_OPTIONS environment variables when running with the Sanitizer build preset.
=> Meta: Set proper BUILD_DIR for different build presets in ladybird.sh

Meta/generate-libwasm-spec-test.py
`linking.wast` has an unusual pattern for invoke commands, which is now accounted-for. Also, special unicode characters are now properly serialized in JavaScript as string literals (this is only relevant for `names.wast`).
**The spec testsuite now fully passes for non-SIMD tests** (on my machine)! Technically there are three failing tests left, but they're all related to checking that we don't allow multiple memory instances (which we support because of the multi-memory proposal). This can be remedied by either ignoring those tests or gating multi-memories behind a flag.
=> LibWasm: Fix spec-test gen for inline commands and special characters

Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
Progress on Tests/LibWeb/Ref/svg-gradient-spreadMethod.html
=> LibWeb: Support SVG gradient spread mode in Skia painter

Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
This fixed the issue https://github.com/LadybirdBrowser/ladybird/issues/573 dashed and dotted borders now render correctly in Skia.
=> LibWeb: Draw dashed and dotted lines in Skia painter

Userland/Libraries/LibJS/CMakeLists.txt, Userland/Libraries/LibJS/Runtime/AbstractOperations.h, Userland/Libraries/LibJS/Runtime/KeyedCollections.cpp, Userland/Libraries/LibJS/Runtime/KeyedCollections.h, Userland/Libraries/LibJS/Runtime/MapPrototype.cpp, Userland/Libraries/LibJS/Runtime/Set.cpp, Userland/Libraries/LibJS/Runtime/Set.h, Userland/Libraries/LibJS/Runtime/SetPrototype.cpp, Userland/Libraries/LibJS/Runtime/SetPrototype.h, Userland/Libraries/LibJS/Runtime/ValueTraits.h
It is now Stage 4 and has been merged into the main ECMA-262 spec:
https://github.com/tc39/ecma262/commit/a78d504
No test262 diff (we already passed every Set test).
=> LibJS: Update specification steps for the Set Methods proposal

Userland/Libraries/LibWeb/HTML/AttributeNames.h, Userland/Libraries/LibWeb/HTML/HTMLFrameElement.idl, Userland/Libraries/LibWeb/HTML/HTMLMarqueeElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLMarqueeElement.h, Userland/Libraries/LibWeb/HTML/HTMLMarqueeElement.idl
Some work on https://wpt.live/html/dom/reflection-obsolete.html.
=> LibWeb: Implement some obsolete attributes

Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
Progress on Tests/Ref/css-gradients.html
=> LibWeb: Support radial gradient with asymmetrical size in Skia painter

Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
Progress on Tests/Ref/css-gradients.html
=> LibWeb: Add support for repeating radial gradient in Skia painter

Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
Progress on Tests/LibWeb/Ref/css-gradients.html
=> LibWeb: Gradient fixes for Skia painter

Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp, Userland/Libraries/LibWeb/Painting/PaintStyle.h
Fixes:
Tests/LibWeb/Ref/svg-gradient-spreadMethod.html
Tests/LibWeb/Ref/svg-radialGradient.html
=> LibWeb: Support SVGRadialGradientPaintStyle in Skia painter

Tests/LibWeb/Text/expected/HTML/relList-attribute.txt, Tests/LibWeb/Text/expected/SVG/svg-ownerSVGElement-attribute.txt, Tests/LibWeb/Text/input/HTML/relList-attribute.html, Tests/LibWeb/Text/input/SVG/svg-ownerSVGElement-attribute.html, Userland/Libraries/LibWeb/SVG/SVGAElement.cpp, Userland/Libraries/LibWeb/SVG/SVGAElement.h, Userland/Libraries/LibWeb/SVG/SVGAElement.idl, Userland/Libraries/LibWeb/SVG/SVGElement.cpp, Userland/Libraries/LibWeb/SVG/SVGElement.h, Userland/Libraries/LibWeb/SVG/SVGElement.idl, Userland/Libraries/LibWeb/SVG/SVGGradientElement.cpp, Userland/Libraries/LibWeb/SVG/SVGGradientElement.h, Userland/Libraries/LibWeb/SVG/SVGGradientElement.idl, Userland/Libraries/LibWeb/SVG/SVGScriptElement.cpp, Userland/Libraries/LibWeb/SVG/SVGScriptElement.h, Userland/Libraries/LibWeb/SVG/SVGScriptElement.idl
=> LibWeb/SVG: SVGElement.ownerSVGElement, SVGAElement.* attributes, SVGURIReference includes

Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
This change fixes the rest of regressions in
Tests/LibWeb/Ref/css-gradients.html
=> LibWeb: Use premultiplied alpha for gradient interpolation in Skia

Tests/LibWeb/Layout/expected/block-and-inline/abspos-with-insets-and-auto-margins.txt, Tests/LibWeb/Layout/input/block-and-inline/abspos-with-insets-and-auto-margins.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp
Fixes https://github.com/LadybirdBrowser/ladybird/issues/712
=> LibWeb: Subtract left inset from size_available_for_margins for abspos

Tests/LibWeb/Text/expected/DOM/CharacterData-replaceData-break-surrogate-pair.txt, Tests/LibWeb/Text/expected/DOM/DOMStringMap-setter-with-invalid-name.txt, Tests/LibWeb/Text/expected/HTML/maxed-out-dimension-value.txt, Tests/LibWeb/Text/expected/HTML/short-legacy-color-value.txt, Tests/LibWeb/Text/expected/Selection-setBaseAndExtent-without-common-root.txt, Tests/LibWeb/Text/input/DOM/CharacterData-replaceData-break-surrogate-pair.html, Tests/LibWeb/Text/input/DOM/DOMStringMap-setter-with-invalid-name.html, Tests/LibWeb/Text/input/HTML/maxed-out-dimension-value.html, Tests/LibWeb/Text/input/HTML/short-legacy-color-value.html, Tests/LibWeb/Text/input/Selection-setBaseAndExtent-without-common-root.html, Userland/Libraries/LibWeb/DOM/CharacterData.cpp, Userland/Libraries/LibWeb/HTML/DOMStringMap.cpp, Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp, Userland/Libraries/LibWeb/Selection/Selection.cpp
=> LibWeb: Fix 5 random bugs found by fuzzing with Domato

Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp, Userland/Libraries/LibWasm/AbstractMachine/Operators.h
46 failing tests left to go on my machine! We also no longer have any unimplemented instructions.
=> LibWasm: Implement the rest of the SIMD operations

Userland/Libraries/LibWeb/CSS/Parser/Tokenizer.cpp, Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
To reproduce suffering: use the SingleFile extension in another browser to create a local copy of reddit.com. Then open it with Ladybird.
There is just so much CSS and HTML. I get roughly 120 MiB worth.
Here are some little patches I did to knock out a couple hot items in the profile.
=> LibWeb: Mixed bag of little optimizations to make loading canned Reddit less painful

Tests/LibWeb/Text/expected/DOM/Text-wholeText.txt, Tests/LibWeb/Text/input/DOM/Text-wholeText.html, Userland/Libraries/LibWeb/DOM/Text.cpp, Userland/Libraries/LibWeb/DOM/Text.h, Userland/Libraries/LibWeb/DOM/Text.idl
As stated, adds [Text.wholeText](https://dom.spec.whatwg.org/#dom-text-wholetext)
Passes: http://wpt.live/dom/nodes/Text-wholeText.html
=> LibWeb: Implement Text.wholeText

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchRecord.cpp, Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchRecord.h, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/HTML/Scripting/Environments.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Environments.h
Implement 'fetch records' and 'fetch group' concepts from the fech specs:
https://fetch.spec.whatwg.org/#concept-fetch-record
=> LibWeb/Fetch: Implement fetch record and fetch group

.mailmap, Ladybird/CMakeLists.txt, Ladybird/Info.plist, Ladybird/MachPortServer.cpp
Also add my new email to the mailmap
=> Ladybird: Update macOS bundle and Mach server to use ladybird.org namespace.

Tests/LibWeb/Layout/expected/svg/svg-viewbox-zero-width.txt, Tests/LibWeb/Layout/input/svg/svg-viewbox-zero-width.html, Tests/LibWeb/Text/expected/Element-scrollby-negative-scroll-offset-crash.txt, Tests/LibWeb/Text/expected/SVG/svg-getbbox-transform-with-no-inverse.txt, Tests/LibWeb/Text/input/Element-scrollby-negative-scroll-offset-crash.html, Tests/LibWeb/Text/input/SVG/svg-getbbox-transform-with-no-inverse.html, Userland/Libraries/LibWeb/Layout/SVGSVGBox.cpp, Userland/Libraries/LibWeb/Painting/PaintableBox.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
This PR fixes a few crashes found via DOM fuzzing with [Domato](https://github.com/googleprojectzero/domato).
=> LibWeb: Fix a few crashes found by Domato

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/HTML/Navigable.cpp, Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
Update `update_for_history_step_application` to meet some of the specs changes introduced in https://github.com/whatwg/html/pull/9856 and in https://github.com/whatwg/html/pull/9990
Fixes #740
=> LibWeb: Update 'update_for_history_step_application' to meet new specs

.mailmap
=> Meta: Update mailmap with my new ladybird.org email address

.github/actions/setup/action.yml, Documentation/BuildInstructionsLadybird.md
I accidentally nuked my OS, and came across some missing things in our Ubuntu package list. Namely pkg-config, but also that we should recommend PulseAudio over Qt6's media.
=> CI+Documentation: A couple system package updates

Userland/Libraries/LibGfx/ImageFormats/JPEGXLLoader.cpp
=> LibGfx/JPEGXL: Support animated images

Userland/Libraries/LibWeb/WebIDL/OverloadResolution.cpp
Per https://discord.com/channels/1247070541085671459/1247090119442173963/1262343020179750952
@kalenikaliaksandr
This PR branch also includes a minor code-streamlining change (suggested by clangd).
Relates to #801.
=> LibWeb: WebIDL::OverloadResolution::resolve_overload, add dbgln FIXMEs

Tests/LibWeb/Text/expected/Element-toggleAttribute-invalid-name.txt, Tests/LibWeb/Text/input/Element-toggleAttribute-invalid-name.html, Userland/Libraries/LibWeb/DOM/Element.cpp
This resolves a test in https://wpt.live/dom/nodes/attributes.html.
=> LibWeb/DOM: Check if name is valid in Element.toggleAttribute

Ladybird/Qt/BrowserWindow.cpp, Ladybird/Qt/Settings.cpp, Ladybird/Qt/Settings.h, Ladybird/Qt/SettingsDialog.cpp, Ladybird/Qt/SettingsDialog.h, Ladybird/Qt/Tab.cpp, Ladybird/Qt/Tab.h, Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Userland/Libraries/LibWeb/HTML/NavigatorLanguage.h, Userland/Libraries/LibWeb/Loader/ResourceLoader.cpp, Userland/Libraries/LibWeb/Loader/ResourceLoader.h, Userland/Libraries/LibWebView/ViewImplementation.cpp, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Services/WebContent/ConnectionFromClient.cpp, Userland/Services/WebContent/ConnectionFromClient.h, Userland/Services/WebContent/WebContentServer.ipc
This should have a nicer UI when the settings is made platform-agnostic :^)
=> LibWeb: Make preferred languages configurable

Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp, Userland/Libraries/LibWeb/Bindings/PlatformObject.h, Userland/Libraries/LibWeb/DOM/HTMLCollection.cpp, Userland/Libraries/LibWeb/DOM/HTMLCollection.h
This makes https://wpt.fyi/ load today instead of tomorrow, although there's a lot of room for improvement still.
=> LibWeb: Cache name->element mappings in HTMLCollection

Userland/Libraries/LibWebView/SourceHighlighter.cpp
The behavior chosen here (fixed-width counters, alignment, etc.) matches Firefox.
=> LibWebView: Insert line numbers before each line in about:srcdoc

Tests/LibWeb/Text/expected/unclosed-body-element.txt, Tests/LibWeb/Text/expected/unclosed-html-element.txt, Tests/LibWeb/Text/input/unclosed-body-element.html, Tests/LibWeb/Text/input/unclosed-html-element.html, Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp, Userland/Libraries/LibWebView/InspectorClient.cpp, Userland/Services/WebContent/ConnectionFromClient.cpp
=> LibWeb+LibWebView+WebContent: Some fixes for attributes with `<` in their names

Userland/Libraries/LibURL/Parser.cpp, Userland/Libraries/LibURL/URL.cpp, Userland/Libraries/LibURL/URL.h, Userland/Libraries/LibWeb/Animations/KeyframeEffect.cpp, Userland/Libraries/LibWeb/CSS/Angle.cpp, Userland/Libraries/LibWeb/CSS/Angle.h, Userland/Libraries/LibWeb/CSS/Frequency.cpp, Userland/Libraries/LibWeb/CSS/Frequency.h, Userland/Libraries/LibWeb/CSS/Length.cpp, Userland/Libraries/LibWeb/CSS/Length.h, Userland/Libraries/LibWeb/CSS/PercentageOr.cpp, Userland/Libraries/LibWeb/CSS/PercentageOr.h, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/CSS/Time.cpp, Userland/Libraries/LibWeb/CSS/Time.h, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/HTML/HTMLBodyElement.cpp, Userland/Services/WebContent/ConnectionFromClient.cpp
=> LibWeb+LibURL: Handful of patches to make CSS data structures use way less memory

Tests/LibWeb/Text/expected/HTML/script-async-attribute.txt, Tests/LibWeb/Text/input/HTML/script-async-attribute.html, Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLScriptElement.h
See:
- http://wpt.live/html/semantics/scripting-1/the-script-element/async_001.htm
=> LibWeb: Script force async flag should default to true

Userland/Libraries/LibWeb/HighResolutionTime/Performance.cpp
=> LibWeb/HighResolutionTime: Add missing visit to Performance

Tests/LibWasm/test-wasm.cpp, Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp, Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h, Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp, Userland/Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h, Userland/Libraries/LibWasm/AbstractMachine/Configuration.cpp, Userland/Libraries/LibWasm/AbstractMachine/Configuration.h, Userland/Libraries/LibWasm/Printer/Printer.cpp, Userland/Libraries/LibWasm/Printer/Printer.h, Userland/Libraries/LibWasm/WASI/Wasi.cpp, Userland/Libraries/LibWeb/WebAssembly/Table.cpp, Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp, Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h, Userland/Utilities/wasm.cpp
=> LibWasm: Bytecode interpreter performance pack

Tests/LibWeb/Ref/reference/scrollable-contains-iframe-ref.html, Tests/LibWeb/Ref/scrollable-contains-iframe.html, Userland/Libraries/LibWeb/Painting/NestedBrowsingContextPaintable.cpp
Fixes iframe painting when they are nested into a scrollable box.
=> LibWeb: Apply enclosing scroll frame offset to iframe's position

Base/res/ladybird/inspector.css, Base/res/ladybird/inspector.js, Userland/Libraries/LibGfx/FontCascadeList.h, Userland/Libraries/LibWebView/InspectorClient.cpp, Userland/Libraries/LibWebView/ViewImplementation.h, Userland/Libraries/LibWebView/WebContentClient.cpp, Userland/Libraries/LibWebView/WebContentClient.h, Userland/Services/WebContent/ConnectionFromClient.cpp, Userland/Services/WebContent/WebContentClient.ipc
This PR adds a "Fonts" tab to the inspector.
Also the CSS regarding the inspector is cleaned up a bit.
=> Inspector: Add Fonts tab

Userland/Libraries/LibWebView/SearchEngine.cpp
This pull request adds Ecosia as a built-in search engine.
=> LibWebView: Add Ecosia search engine

AK/String.cpp, AK/String.h, Tests/AK/TestString.cpp, Userland/Libraries/LibTextCodec/Decoder.cpp, Userland/Libraries/LibWeb/DOMURL/URLSearchParams.cpp
See discussion from: https://discord.com/channels/1247070541085671459/1247090064480014443/1271987969103892500
=> AK+LibTextCodec: Add fast-path in from_utf8_with_replacement_character, use in LibTextCodec

Userland/Libraries/LibWeb/HTML/AttributeNames.h, Userland/Libraries/LibWeb/HTML/HTMLFrameElement.idl, Userland/Libraries/LibWeb/HTML/HTMLImageElement.idl, Userland/Libraries/LibWeb/HTML/HTMLObjectElement.idl
See individual commits for specifics
=> LibWeb: Some small obsolete IDL property changes

Tests/LibWeb/Text/expected/base/link-element-base.txt, Tests/LibWeb/Text/input/base/link-element-base.html, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp
=> LibWeb: Use base URL for link loading

Userland/Libraries/LibWeb/HTML/HTMLFormElement.idl, Userland/Libraries/LibWeb/HTML/HTMLInputElement.idl, Userland/Libraries/LibWeb/HTML/HTMLSelectElement.idl, Userland/Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
https://wpt.live/html/dom/idlharness.https.html?include=HTMLForm.*
from 4 fails -> 2 fails
=> LibWeb: Add autocomplete property

Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp, Userland/Libraries/LibWeb/HTML/HTMLScriptElement.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Fetching.h, Userland/Libraries/LibWeb/HTML/Scripting/ImportMap.cpp, Userland/Libraries/LibWeb/HTML/Scripting/ImportMap.h
I wrote this a while ago, and never made a PR - not entirely sure why, but better late than never :^)
See:
- https://github.com/whatwg/html/commit/b2fdca1
- http://wpt.live/import-maps/static-integrity.html
=> LibWeb: Support SRI for import maps

Userland/Libraries/LibJS/Print.cpp, Userland/Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp, Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormat.h, Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp, Userland/Libraries/LibJS/Runtime/Intl/DateTimeFormatPrototype.cpp, Userland/Libraries/LibJS/Runtime/Intl/DisplayNamesConstructor.cpp, Userland/Libraries/LibJS/Runtime/Intl/ListFormat.cpp, Userland/Libraries/LibJS/Runtime/Intl/LocaleConstructor.cpp, Userland/Libraries/LibJS/Runtime/Intl/NumberFormatConstructor.cpp, Userland/Libraries/LibJS/Runtime/Intl/NumberFormatConstructor.h, Userland/Libraries/LibJS/Runtime/Intl/PluralRulesConstructor.cpp, Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormat.cpp, Userland/Libraries/LibJS/Runtime/Intl/RelativeTimeFormatConstructor.cpp, Userland/Libraries/LibJS/Runtime/Intl/SegmenterConstructor.cpp, Userland/Libraries/LibJS/Runtime/StringPrototype.cpp, Userland/Libraries/LibUnicode/DateTimeFormat.h
Minor editorial updates from the ECMA-402 spec. No functional change.
=> LibJS+LibUnicode: Update some constructor and AO spec steps

Tests/LibWeb/Text/expected/URL/search-params-strip-trailing-spaces-from-opaque-url.txt, Tests/LibWeb/Text/expected/URL/url-search-params-sort-utf16-code-units.txt, Tests/LibWeb/Text/input/URL/search-params-strip-trailing-spaces-from-opaque-url.html, Tests/LibWeb/Text/input/URL/url-search-params-sort-utf16-code-units.html, Userland/Libraries/LibWeb/DOMURL/URLSearchParams.cpp
Making two more of the URL WPT tests pass all subtests. See commits for details.
=> LibWeb: Two more fixes for WPT URL test cases

Userland/Libraries/LibWeb/HTML/EventSource.cpp
=> LibWeb: Fix handling of SSEs split across chunks

Documentation/CodingStyle.md, Documentation/GettingStartedContributing.md, Documentation/Patterns.md, Documentation/SmartPointers.md, README.md
This document aims to be a begginer-friendly summary of the existing contribution requirements for Ladybird, intended to be linked to new-comers.
Relies on LadybirdBrowser/ladybird.org#71
=> Documentation: Add a getting started contributing guide

Tests/LibWeb/Text/expected/Wasm/WebAssembly-grow.txt, Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp, Userland/Libraries/LibWasm/AbstractMachine/AbstractMachine.h, Userland/Libraries/LibWasm/AbstractMachine/Configuration.cpp, Userland/Libraries/LibWasm/WASI/Wasi.cpp, Userland/Libraries/LibWeb/WebAssembly/Table.cpp, Userland/Libraries/LibWeb/WebAssembly/WebAssembly.cpp, Userland/Libraries/LibWeb/WebAssembly/WebAssembly.h, Userland/Libraries/LibWeb/WebIDL/AbstractOperations.cpp, Userland/Utilities/wasm.cpp
Every important Table-related test passes now!
=> LibWeb/WebAssembly: Improve the spec-compliance of the Table JS API

Tests/LibWeb/Layout/expected/svg/inline-svg-with-zero-intrinsic-size-and-no-viewbox.txt, Userland/Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp, Userland/Services/WebContent/PageClient.cpp
=> LibWeb: Couple small fixes to avoid unnecessary repaints

Userland/Libraries/LibJS/Lexer.cpp, Userland/Libraries/LibJS/Runtime/ArrayBuffer.cpp, Userland/Libraries/LibJS/Runtime/ArrayBuffer.h, Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.cpp, Userland/Libraries/LibJS/Runtime/ArrayBufferPrototype.h, Userland/Libraries/LibJS/Runtime/TypedArray.h, Userland/Libraries/LibJS/Runtime/VM.cpp
=> LibJS: Update spec steps/links for merged stage 4 proposals

Userland/Libraries/LibGfx/CMakeLists.txt
Compare with https://github.com/LadybirdBrowser/ladybird/blob/2f3128333dcd5a781f35272800631d6cf03803ad/Userland/Libraries/LibWeb/CMakeLists.txt#L780
=> LibGfx: Fix build with system skia

Userland/Libraries/LibWeb/XHR/FormData.idl
See:
- http://wpt.live/fetch/api/response/response-init-contenttype.any.worker.html
=> LibWeb/XHR: Expose FormData to Worker

Userland/Libraries/LibJS/Runtime/IteratorHelper.h, Userland/Libraries/LibJS/Runtime/IteratorHelperPrototype.cpp, Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp
Missed these from a few months ago. No test262 diff.
=> LibJS: A couple editorial updates to the Iterator Helpers proposal

Ladybird/AppKit/UI/LadybirdWebViewBridge.cpp, Ladybird/AppKit/UI/TabController.mm, Ladybird/Qt/BrowserWindow.cpp, Userland/Libraries/LibWebView/Application.cpp, Userland/Libraries/LibWebView/Options.h, Userland/Libraries/LibWebView/UserAgent.cpp, Userland/Libraries/LibWebView/UserAgent.h
Found myself wanting this when working on Google Lens, instead of having to navigate to the menu every time I launched the browser
=> LibWebView+UI: Add a command line option to set the User-Agent override

Ladybird/Qt/TabBar.cpp, Ladybird/WebContent/main.cpp
=> UI+WebContent: A fix & workaround for Intel macOS 

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/HTML/AbstractWorker.cpp, Userland/Libraries/LibWeb/HTML/AbstractWorker.h, Userland/Libraries/LibWeb/HTML/AbstractWorker.idl, Userland/Libraries/LibWeb/HTML/Worker.h, Userland/Libraries/LibWeb/HTML/Worker.idl
This effectively implements Worker.onerror, and in future SharedWorker.onerror.
=> LibWeb: Implement AbstractWorker

Ladybird/Android/src/main/cpp/ImageDecoderService.cpp, Ladybird/Android/src/main/cpp/LadybirdActivity.cpp, Ladybird/Android/src/main/cpp/LadybirdServiceBaseJNI.cpp, Ladybird/Android/src/main/cpp/RequestServerService.cpp, Ladybird/Android/src/main/cpp/TimerExecutorService.cpp, Ladybird/Android/src/main/cpp/WebContentServiceJNI.cpp, Ladybird/Android/src/main/cpp/WebViewImplementationNativeJNI.cpp, Meta/CMake/Findlibjxl.cmake, Userland/Libraries/LibAudio/PlaybackStreamOboe.cpp, Userland/Libraries/LibAudio/PlaybackStreamOboe.h, Userland/Libraries/LibGfx/CMakeLists.txt, Userland/Libraries/LibGfx/Font/TypefaceSkia.cpp
This PR enables to compile Ladybird successfully for Android.
Findlibjxl.cmake was taken from SDL_image and altered to include its license.
=> Android: Fix compiling

Tests/LibWeb/Ref/input-background.html, Tests/LibWeb/Ref/reference/input-background.html, Userland/Libraries/LibWeb/CSS/Default.css
Sites seem to assume this happens, for example the search bar on walmart.com
=> LibWeb: Add background color to input fields

Userland/Libraries/LibGfx/Font/Font.h, Userland/Libraries/LibGfx/Font/OpenType/Typeface.cpp, Userland/Libraries/LibGfx/Font/OpenType/Typeface.h, Userland/Libraries/LibGfx/Font/ScaledFont.cpp, Userland/Libraries/LibGfx/Font/ScaledFont.h, Userland/Libraries/LibGfx/Font/Typeface.h, Userland/Libraries/LibGfx/TextLayout.cpp, Userland/Libraries/LibGfx/TextLayout.h, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
=> LibGfx+LibWeb: Use harfbuzz to measure text width

Userland/Libraries/LibWeb/Painting/MediaPaintable.cpp
Previously, using the mouse to interact with the media player wouldn't work as expected if the page had been scrolled vertically or horizontally.
=> LibWeb: Account for scroll offset when interacting with media controls

Userland/Libraries/LibGfx/Bitmap.h, Userland/Libraries/LibWeb/DOM/Element.cpp, Userland/Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
=> Two small speed-ups for vercel.com

Userland/Libraries/LibWeb/MathML/MathMLElement.idl
Just a small addition, knocking one more thing off https://idl-compare.pages.dev/ :^)
=> LibWeb: MathMLElement includes ElementCSSInlineStyle

Userland/Libraries/LibWeb/CSS/CSSRule.cpp, Userland/Libraries/LibWeb/CSS/CSSRule.h, Userland/Libraries/LibWeb/CSS/CSSStyleRule.cpp, Userland/Libraries/LibWeb/CSS/CSSStyleRule.h, Userland/Libraries/LibWeb/CSS/SelectorEngine.cpp, Userland/Libraries/LibWeb/CSS/SelectorEngine.h, Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h
See individual commits.
Style updates on https://vercel.com/ are down from ~250ms to ~210ms on my machine. More work needed.
=> LibWeb: More work on making style updates faster

Userland/Libraries/LibGfx/Font/TypefaceSkia.cpp, Userland/Libraries/LibGfx/Font/TypefaceSkia.h
Two simple caches for a bit over 10% speed-up :)
=> LibGfx: Cache some things in TypefaceSkia for big speedups on tailwindcss.com

Documentation/Browser/CSSGeneratedFiles.md, Documentation/README.md
A lot of this stuff only makes sense in my head so let's fix that by actually documenting it! :^)
=> Documentation: Document the CSS JSON files and what they do

Tests/LibWeb/Layout/expected/abspos-box-with-replaced-element.txt
Updates expectation file for test that has been affected by 6199870528b4f8ebc697afaf3c3a335ab397ad9c
=> Tests/Layout: Update expectation for abspos-box-with-replaced-element

Userland/Libraries/LibWeb/UIEvents/KeyCode.h
I did this to respond to the issue #974.
I changed the other keys to not have problems with two keys having the same keycode.
=> LibWeb: Defined all the keycodes

Userland/Libraries/LibIPC/Message.cpp
This fixes a large number of timeouts in WPT tests using workers where a large amount of data is transferred. For example: http://wpt.live/encoding/textdecoder-fatal-single-byte.any.worker.html  (and many others)
=> LibIPC: Wait until socket is writable when transferring IPC messages

Userland/Services/RequestServer/ConnectionFromClient.cpp
=> RequestServer: Two small CURL-related fixes

Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
...instead of directly mutating Gfx::Bitmap.
This change is preparation for using GPU-backend for canvas painting where direct mutating of backing storage that bypasses painter is no longer possible.
=> LibWeb: Use Gfx::Painter in CanvasRenderingContext2D::get_image_data()

Userland/Libraries/LibIPC/Connection.cpp
=> LibIPC: Handle spurious wake-ups on the send queue thread

Userland/Services/WebContent/WebDriverConnection.cpp
Fill in a few lines from the spec :^)
=> WebDriver: Implement Switch To Frame for null ID

Tests/LibWeb/Layout/expected/grid/abspos-item-with-padding.txt, Tests/LibWeb/Layout/expected/grid/inline-abspos-item.txt, Tests/LibWeb/Layout/input/grid/abspos-item-with-padding.html, Tests/LibWeb/Layout/input/grid/inline-abspos-item.html, Userland/Libraries/LibWeb/Layout/FormattingContext.cpp, Userland/Libraries/LibWeb/Layout/GridFormattingContext.cpp, Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Fixes reductions made from https://wpt.live/css/css-grid/abspos/positioned-grid-descendants-001.html
=> LibWeb: Couple GFC and IFC fixes for abspos boxes

Userland/Libraries/LibWeb/CSS/StyleComputer.cpp, Userland/Libraries/LibWeb/CSS/StyleComputer.h, Userland/Libraries/LibWeb/DOM/Node.cpp, Userland/Libraries/LibWeb/DOM/Node.h, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLLinkElement.h
See individual commits.
Loading https://github.com/LadybirdBrowser/ladybird
Before: 12s
After: 8.5s
=> LibWeb: Various style/layout invalidation avoidance

Tests/LibWeb/Text/expected/regress/console-log-bogus-formatting-specifier.txt, Tests/LibWeb/Text/input/regress/console-log-bogus-formatting-specifier.html, Userland/Libraries/LibJS/Console.cpp, Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp, Userland/Libraries/LibWeb/HTML/BrowsingContext.h, Userland/Libraries/LibWeb/HTML/Navigable.cpp
Wasn't particularly hard :^)
https://v0.dev/
=> LibJS+LibWeb: Make v0.dev usable in Ladybird

AK/JsonParser.cpp, Tests/AK/TestJSON.cpp, Userland/Libraries/LibWeb/WebDriver/Client.cpp, Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp, Userland/Libraries/LibWeb/WebDriver/ElementReference.h, Userland/Services/WebContent/WebDriverConnection.cpp
Found these issues while working on the Perform Actions endpoint. Rather than growing that branch to a large number of commits, I pulled these out since they're generally useful.
=> AK+LibWeb: A mix of bug fixes and performance improvements for WebDriver

Userland/Libraries/LibWeb/CSS/FontFace.h, Userland/Libraries/LibWeb/CSS/FontFaceSet.cpp, Userland/Libraries/LibWeb/CSS/FontFaceSet.h
There is still some work to do with some of the underying methods called inside this method (e.g is_css_connected) but this is a start.
=> LibWeb/CSS: Implement add for FontFaceSet

Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp, Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebContent/WebDriverConnection.h, Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Client.h, Userland/Services/WebDriver/Session.cpp, Userland/Services/WebDriver/Session.h
A few more fixes for issues found while running Perform Actions tests
=> LibWeb+WebContent+WebDriver: A few more misc WebDriver fixes

Userland/Libraries/LibWeb/HTML/Navigation.cpp
Applies changes in https://github.com/whatwg/html/pull/10658 and also whichever previous change split the step for firing the navigateerror into two parts.
=> LibWeb/HTML: Re-order promise resolution to match spec

Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/UIEvents/MouseButton.h, Userland/Libraries/LibWeb/UIEvents/MouseEvent.cpp, Userland/Libraries/LibWeb/WebDriver/Actions.cpp, Userland/Libraries/LibWeb/WebDriver/Actions.h, Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp, Userland/Libraries/LibWeb/WebDriver/ElementReference.h, Userland/Libraries/LibWeb/WebDriver/InputSource.cpp, Userland/Libraries/LibWeb/WebDriver/InputSource.h, Userland/Libraries/LibWeb/WebDriver/InputState.cpp, Userland/Libraries/LibWeb/WebDriver/InputState.h, Userland/Libraries/LibWeb/WebDriver/Properties.h, Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebContent/WebDriverConnection.h, Userland/Services/WebContent/WebDriverServer.ipc, Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Session.cpp, Userland/Services/WebDriver/Session.h, Userland/Services/WebDriver/WebContentConnection.cpp, Userland/Services/WebDriver/WebContentConnection.h
This implements:
* Parsing and validation of all action types
* Execution of mouse move/down/up actions
* The Perform Actions and Release Actions endpoints that interact with those actions
=> WebDriver: Begin implementing the Perform Actions and Release Actions endpoints

.github/actions/setup/action.yml, .github/workflows/ci.yml, .github/workflows/ladybird-js-artifacts.yml, .github/workflows/lint-commits.yml
* Stop using Xcode beta
* Upgrade to Ubuntu 24
=> CI: Miscellaneous bookkeeping

Tests/LibWeb/TestMimeSniff.cpp, Userland/Libraries/LibWeb/MimeSniff/Resource.cpp
The spec added the xml and html checks to the beginning of the MIME type sniffing algorithm and removed sniffing resource feeds.
Related spec change: https://github.com/whatwg/mimesniff/commit/b47be44aba066f3ef03864d9ed24eb8c7b533758
=> LibWeb/MimeSniff: Update the MIME type sniffing algo to meet specs

Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Fetching.cpp, Userland/Libraries/LibWeb/HTML/Scripting/Fetching.h
=> LibWeb: Update spec comments for HostLoadImportedModule

.github/actions/setup/action.yml
Homebrew has disabled the pyyaml package for some reason.
=> CI: Install pyyaml from pip

Userland/Libraries/LibWeb/HTML/NavigatorID.cpp
These are logged ~1000 times on fast.com.
=> LibWeb: Remove debug spam from Navigator methods

Ladybird/CMakeLists.txt, Ladybird/WebContent/CMakeLists.txt, Ladybird/WebWorker/CMakeLists.txt
* Remove unused Qt::Network linkages
* Remove unused WPT test target
=> UI/Qt: A bit of CMake cleanup

Userland/Libraries/LibWeb/WebAudio/AudioBufferSourceNode.h, Userland/Libraries/LibWeb/WebAudio/AudioDestinationNode.cpp, Userland/Libraries/LibWeb/WebAudio/AudioDestinationNode.h, Userland/Libraries/LibWeb/WebAudio/AudioNode.cpp, Userland/Libraries/LibWeb/WebAudio/AudioNode.h, Userland/Libraries/LibWeb/WebAudio/BaseAudioContext.h, Userland/Libraries/LibWeb/WebAudio/BiquadFilterNode.h, Userland/Libraries/LibWeb/WebAudio/DynamicsCompressorNode.h, Userland/Libraries/LibWeb/WebAudio/GainNode.h, Userland/Libraries/LibWeb/WebAudio/OscillatorNode.h
Came across these FIXMEs while working on https://zty.pe/ compatibility.
=> LibWeb: Implement AudioNode.numberOfInputs/Outputs and .channelCount

Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt, Userland/Libraries/LibWeb/CSS/ComputedValues.h, Userland/Libraries/LibWeb/CSS/Enums.json, Userland/Libraries/LibWeb/CSS/Keywords.json, Userland/Libraries/LibWeb/CSS/Properties.json, Userland/Libraries/LibWeb/CSS/StyleProperties.cpp, Userland/Libraries/LibWeb/CSS/StyleProperties.h, Userland/Libraries/LibWeb/Layout/Node.cpp, Userland/Libraries/LibWeb/Painting/SVGPathPaintable.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.cpp, Userland/Libraries/LibWeb/SVG/SVGGraphicsElement.h
SVGGraphicsElement then goes ahead and does nothing with it for now.
=> LibWeb: Add stroke-linecap attribute and plumb it to SVGGraphicsElement

Tests/LibWeb/Text/expected/reset-input-element.txt, Tests/LibWeb/Text/input/reset-input-element.html, Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp
This fixes WPT html/semantics/forms/resetting-a-form/reset-form.html. I added a test based on the WPT test, but simpler.
=> LibWeb: Implement activation behavior on input[type=reset]

Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLInputElement.h, Userland/Libraries/LibWeb/WebDriver/Actions.cpp, Userland/Libraries/LibWeb/WebDriver/Actions.h, Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp, Userland/Libraries/LibWeb/WebDriver/ElementReference.h, Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebDriver/Client.cpp, Userland/Services/WebDriver/Session.cpp, Userland/Services/WebDriver/Session.h
https://github.com/user-attachments/assets/1abc1bd6-2d04-47be-b3aa-3e036c4ee410
=> LibWeb: Begin implementing the Element Send Keys endpoint

Userland/Libraries/LibJS/Print.cpp
Printing the whole array causes wpt [console/console-log-large-array.any.html](https://wpt.fyi/results/console/console-log-large-array.any.html?product=ladybird) to crash. 
This limits logged arrays to 100 elements and truncates the rest with ...
The runtime of the test on my machine went from 25 seconds down to 7.
The 100 is an arbitrary selected number so if you have a better solution I am happy to change it.
=> LibJS: Do not print large arrays

Userland/Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
If the image data to decode is incomplete, e.g. a corrupt image missing its last scanlines the decoder would previously keep looping for ever. By breaking out of the loop if no more scanlines were produced we can at least display the partial image up to that point.
=> JPEGLoader: Fix infinite loop on incomplete data

Userland/Libraries/LibWebView/SearchEngine.cpp
#690 has not been touched in almost 3 months and it could not be merged because the commit message did not follow the code submission policy. This pull request has the same changes made in #690, except the commit message now follows the code submission policy.
Closes #690
=> LibWebView: Add Startpage search engine

Userland/Libraries/LibWeb/Selection/Selection.cpp, Userland/Libraries/LibWeb/Selection/Selection.h, Userland/Libraries/LibWeb/Selection/Selection.idl
At least 464 new passing subtests in the WPT selection directory.
=> LibWeb: Various WPT selection fixes

Userland/Libraries/LibWeb/DOM/AbortController.idl, Userland/Libraries/LibWeb/DOM/AbortSignal.idl, Userland/Libraries/LibWeb/DOM/CustomEvent.idl, Userland/Libraries/LibWeb/DOM/DOMImplementation.idl, Userland/Libraries/LibWeb/DOM/Event.cpp, Userland/Libraries/LibWeb/DOM/Event.h, Userland/Libraries/LibWeb/DOM/Event.idl, Userland/Libraries/LibWeb/DOM/EventTarget.idl, Userland/Libraries/LibWeb/DOM/HTMLCollection.idl, Userland/Libraries/LibWeb/DOM/MutationObserver.idl, Userland/Libraries/LibWeb/DOM/MutationRecord.idl, Userland/Libraries/LibWeb/DOM/NamedNodeMap.idl, Userland/Libraries/LibWeb/DOM/Node.idl, Userland/Libraries/LibWeb/DOM/NodeIterator.idl, Userland/Libraries/LibWeb/DOM/Range.idl, Userland/Libraries/LibWeb/DOM/StaticRange.idl, Userland/Libraries/LibWeb/DOM/TreeWalker.idl, Userland/Libraries/LibWeb/DOM/XMLDocument.idl
I noticed some of these were running behind the upstream spec.
=> LibWeb: Update DOM IDL specs

Userland/Libraries/LibJS/Runtime/DateConstructor.cpp, Userland/Libraries/LibJS/Tests/builtins/Date/Date.parse.js
Seen on https://www.skaping.com/valloire/galibier.
=> LibJS: Support date strings of the form "Wed Apr 17 2019 23:08:53""

Tests/LibWeb/Text/expected/FileAPI/filereader-events.txt, Tests/LibWeb/Text/input/FileAPI/filereader-events.html, Userland/Libraries/LibWeb/FileAPI/FileReader.cpp
Fixes wpt/FileAPI/reading-data-section/filereader_events.any.html :)
=> LibWeb: Make FileReader fire progress event

AK/CMakeLists.txt, AK/Platform.h, AK/Time.cpp, AK/Time.h
=> AK: Fix build errors on Windows

Userland/Libraries/LibJS/Bytecode/Interpreter.cpp, Userland/Libraries/LibJS/Runtime/Object.cpp
1.25x speed-up on this microbenchmark:
let o = { get x() { return 1; } };
for (let i = 0; i < 10_000_000; ++i)
o.x;
I looked into this because I noticed getter invocation when profiling long-running WPT tests. We already had the mechanism for non-getter properties, and the change to support getters turned out to be trivial.
=> LibJS: Allow GetById to cache getters

Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp, Userland/Libraries/LibWeb/WebDriver/ElementReference.h, Userland/Services/WebContent/PageClient.cpp, Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebContent/WebDriverConnection.h
Things I've been meaning to clean up for a short while.
=> LibWeb: A few minor WebDriver cleanups

Userland/Libraries/LibWeb/HTML/Window.cpp, Userland/Libraries/LibWeb/HTML/Window.h, Userland/Services/WebContent/WebDriverConnection.cpp
We were returning the handle of the already opened window, rather than the handle of the window we just opened.
=> LibWeb+WebContent: Return the handle of the newly opened window from New Window

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Fixes https://github.com/LadybirdBrowser/ladybird/issues/1890
=> LibWeb/Meta: Only generate the invalid value default if we didnt generate the missing value default

Userland/Libraries/LibWeb/Layout/ReplacedBox.h
Tiny cleanup while researching other things.
=> LibWeb: Remove unused members from ReplacedBox

Tests/LibRegex/Regex.cpp, Userland/Libraries/LibRegex/RegexOptimizer.cpp
cc @trflynn89, you can have your gift back.
=> LibRegex: Don't blindly accept inverted charclasses for atomic rewrite

Userland/Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
Specifically, the spec changes that I brought about :nerd_face: 
This PR:
- Removes a dead variable
- Removes dead writes
As such, there is no opportunity for new tests.
=> LibWeb: Update WebCrypto to recent spec changes

Userland/Libraries/LibJS/Bytecode/ASTCodegen.cpp
If statements without an else clause generated jumps to the next instruction, this commit fixes the if statement generation so that it dosen't produce them anymore.
This is an example of JS code that generates the useless jumps
(a => if(a){}) ();
=> LibJS: Don't generate useless jumps for if statement

Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.cpp, Userland/Libraries/LibWeb/HTML/HTMLAnchorElement.h
Required for Pixedit.
Ref: #102
=> LibWeb/HTML: Implement download attribute

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/Worker/Worker-postMessage-transfer.txt, Tests/LibWeb/Text/input/Worker/Worker-postMessage-transfer.html, Userland/Libraries/LibWeb/HTML/DedicatedWorkerGlobalScope.cpp, Userland/Libraries/LibWeb/HTML/DedicatedWorkerGlobalScope.h, Userland/Libraries/LibWeb/HTML/DedicatedWorkerGlobalScope.idl, Userland/Libraries/LibWeb/HTML/MessagePort.idl, Userland/Libraries/LibWeb/HTML/ServiceWorker.idl, Userland/Libraries/LibWeb/HTML/Worker.cpp, Userland/Libraries/LibWeb/HTML/Worker.h, Userland/Libraries/LibWeb/HTML/Worker.idl, Userland/Libraries/LibWeb/WebIDL/OverloadResolution.cpp, Userland/Libraries/LibWeb/WebIDL/OverloadResolution.h
This fixes loading MDN in ladybird :^)
E.g on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
=> LibWeb: Implement overload resolution for Objects, implement Worker.postMessage(msg, transfer)

Tests/LibWeb/Text/expected/DOM/domparser-parsefromstring-doctype-publicid.txt, Tests/LibWeb/Text/expected/DOM/domparser-parsefromstring-doctype-systemid.txt, Tests/LibWeb/Text/input/DOM/domparser-parsefromstring-doctype-publicid.html, Tests/LibWeb/Text/input/DOM/domparser-parsefromstring-doctype-systemid.html, Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.cpp, Userland/Libraries/LibWeb/XML/XMLDocumentBuilder.h, Userland/Libraries/LibXML/Parser/Parser.cpp, Userland/Libraries/LibXML/Parser/Parser.h
This fixes at least one WPT test under /domparsing
=> LibXML: Set the doctype when parsing via Parser::parse_with_listener

Userland/Libraries/LibWeb/Bindings/PlatformObject.cpp, Userland/Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp, Userland/Libraries/LibWeb/HTML/HTMLCanvasElement.cpp, Userland/Libraries/LibWeb/HTML/StructuredSerialize.cpp, Userland/Libraries/LibWeb/Streams/AbstractOperations.cpp
More high-octane thrills as I change some spec comments. :sunglasses:
I've left WebIDL alone for now, as the spec differences are more significant.
=> LibWeb: Update spec comments using "Type(Foo)" -> "is a Foo"

Userland/Libraries/LibUnicode/Segmenter.cpp, Userland/Libraries/LibUnicode/Segmenter.h, Userland/Libraries/LibWeb/DOM/EditingHostManager.cpp, Userland/Libraries/LibWeb/DOM/EditingHostManager.h, Userland/Libraries/LibWeb/Forward.h, Userland/Libraries/LibWeb/HTML/FormAssociatedElement.cpp, Userland/Libraries/LibWeb/Painting/PaintableFragment.cpp
Addresses a part of feedback from @trflynn89 on https://github.com/LadybirdBrowser/ladybird/pull/2024
There are more issues to fix but I will do them in a separate PR.
=> LibWeb: Post #2024 cleanup

Ladybird/HelperProcess.cpp, Ladybird/WebContent/main.cpp, Userland/Libraries/LibJS/Console.cpp, Userland/Libraries/LibJS/Runtime/Array.cpp, Userland/Libraries/LibJS/Runtime/Array.h, Userland/Libraries/LibJS/Runtime/IteratorPrototype.cpp, Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/HTML/MessageEvent.cpp, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp, Userland/Libraries/LibWeb/ResizeObserver/ResizeObserver.cpp, Userland/Libraries/LibWeb/ResizeObserver/ResizeObserver.h, Userland/Libraries/LibWeb/ResizeObserver/ResizeObserverEntry.cpp, Userland/Libraries/LibWebView/Application.cpp, Userland/Libraries/LibWebView/Options.h
For reference, `headless-browser --run-tests Tests/LibWeb -g` took ~40 minutes on my mac and the following tests timed out:
```
Ref/iframe-contains-scrollable-box.html
Text/input/wpt-import/accname/name/comp_embedded_control.html
Text/input/wpt-import/css/css-flexbox/abspos/flex-abspos-staticpos-align-content-001.html
Text/input/wpt-import/css/css-flexbox/abspos/flex-abspos-staticpos-align-self-001.html
Text/input/wpt-import/css/css-flexbox/abspos/flex-abspos-staticpos-align-self-002.html
Text/input/wpt-import/css/css-flexbox/abspos/flex-abspos-staticpos-align-self-003.html
Text/input/wpt-import/css/css-flexbox/abspos/flex-abspos-staticpos-align-self-004.html
Text/input/wpt-import/css/css-flexbox/abspos/flex-abspos-staticpos-align-self-005.html …
```
=> LibWebView: Add a browser flag to collect garbage after each allocation, and fix GC issues

Meta/import-wpt-test.py
This change switches the `Meta/import-wpt-test.py` script to using the standard html.parser module rather than BeautifulSoup.
Otherwise, without this change, when a contributor first tries to run the script, if they don’t have BeautifulSoup installed, it will fail.
Note that this patch also includes an unrelated small change that switches to using `os.path.normpath` — rather than `Path.absolute()` — to “normalize” the destination names of the downloaded test files.
The `html.parser` API is cruder than the BeautifulSoup API, but switching to it isn’t really a readability/maintainability loss; it doesn’t make the code any more verbose/longer — and in fact this change cuts the total length of the script by 1 line.
=> Meta: Make import-wpt-test.py use html.parser, not BeautifulSoup

Documentation/BuildInstructionsLadybird.md
Credit to Nico for pointing this out!
=> Documentation: Add note about making the macOS terminal a developer tool

Tests/LibWeb/Text/expected/select-text.txt, Tests/LibWeb/Text/input/select-text.html, Userland/Libraries/LibWeb/DOM/EditingHostManager.cpp, Userland/Libraries/LibWeb/Internals/Internals.cpp, Userland/Libraries/LibWeb/Internals/Internals.h, Userland/Libraries/LibWeb/Internals/Internals.idl, Userland/Libraries/LibWeb/Page/EventHandler.cpp, Userland/Libraries/LibWeb/Selection/Selection.cpp, Userland/Libraries/LibWeb/Selection/Selection.h
...using keyboard.
Fixes regression introduced in https://github.com/LadybirdBrowser/ladybird/commit/a8077f79cc65a37f82078a6249f161e469e96c3a
=> LibWeb: Fix ability to modify selection outside of input

Tests/LibWeb/Text/expected/wpt-import/streams/readable-byte-streams/tee.any.txt, Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/tee.any.html, Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/tee.any.js, Tests/LibWeb/Text/input/wpt-import/streams/resources/recording-streams.js, Tests/LibWeb/Text/input/wpt-import/streams/resources/rs-test-templates.js, Tests/LibWeb/Text/input/wpt-import/streams/resources/rs-utils.js, Tests/LibWeb/Text/input/wpt-import/streams/resources/test-utils.js, Userland/Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
This fixes a crash seen running stream tests.
=> LibWeb: Push a temporary execution context for setTimeout

Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp
Also sorts their defines by spec order
=> LibWeb: Add FIXME for missing SubtleCrypto algorithms

AK/JsonArray.h, Userland/Libraries/LibWeb/CMakeLists.txt, Userland/Libraries/LibWeb/WebDriver/Actions.h, Userland/Libraries/LibWeb/WebDriver/Contexts.cpp, Userland/Libraries/LibWeb/WebDriver/Contexts.h, Userland/Libraries/LibWeb/WebDriver/ElementReference.cpp, Userland/Libraries/LibWeb/WebDriver/ElementReference.h, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.cpp, Userland/Libraries/LibWeb/WebDriver/ExecuteScript.h, Userland/Libraries/LibWeb/WebDriver/JSON.cpp, Userland/Libraries/LibWeb/WebDriver/JSON.h, Userland/Services/WebContent/WebDriverConnection.cpp, Userland/Services/WebContent/WebDriverConnection.h
Resolves some long-standing FIXMEs around WebDriver script execution.
=> LibWeb+WebContent: Fully implement JSON cloning and deserialization

Userland/Services/RequestServer/ConnectionFromClient.cpp
=> RequestServer: Implement preconnect for CreateConnection cache level

Tests/LibWeb/TestConfig.ini
This has been consistently timing-out on CI.
=> Tests: Skip flakey `css/cubic-bezier-infinite-slope-crash.html` test

Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp, Userland/Libraries/LibGfx/ImageFormats/PNGLoader.h
Some minor improvements while working on fixing a WPT case:
* Use libpng's signature verification
* Improved, descriptive error handling
=> LibGfx: PNG decoding improvements

Userland/Libraries/LibGfx/ImageFormats/PNGLoader.cpp
This fixes 3/4 of the remaining test failures in wpt/png/apng. Also, about half of the APNG files on
https://commons.wikimedia.org/wiki/Category:Animated_PNG_files used to be broken, and they all seem to work properly now :^)
I also refactored the code to be (at least to me) simpler and more similar to what the spec describes. As a nice side effect, there are now fewer lines of code than before.
Lastly, I replaced DeprecatedPainter with Painter.
=> LibGfx: Support APNG more completely

CONTRIBUTING.md
Given matching (reverse-matching?) discussions in the scope of SerenityOS, I feel like this might be a good thing to do.
That said, I never did much regarding the browser parts anyways, so in the end it will most likely be somewhat of a noop anyways. Is that what this so called memory optimization is?
Obviously, if there is anything to discuss where my input might be needed, feel free to tag me. See you around!
=> Meta: Step down myself from maintainers

Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Document-createProcessingInstruction-xhtml.txt, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Document-createProcessingInstruction.txt, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Document-createProcessingInstruction-xhtml.xhtml, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Document-createProcessingInstruction.html, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Document-createProcessingInstruction.js, Userland/Libraries/LibWeb/DOM/Document.cpp
Passes 16 tests in http://wpt.live/dom/nodes/Document-createProcessingInstruction-xhtml.xhtml and https://wpt.live/dom/nodes/Document-createProcessingInstruction.html
=> LibWeb: Reject invalid processing instructions

Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.h, Userland/Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.idl, Userland/Libraries/LibWeb/HTML/Canvas/CanvasState.h, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Userland/Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
Not used for painting yet, but adds a FIXME for what's missing.
Also tweak some existing spec comments minorly.
---
Similar to #275.
=> LibWeb: Plumbing for lineCap, lineJoin, miterLimit, lineDashOffset

Userland/Libraries/LibWeb/DOM/Range.cpp
Corresponds to https://github.com/whatwg/html/pull/10732
=> LibWeb/DOM: Update a spec comment in Range::create_contextual_fragment()

Userland/Libraries/LibWeb/DOM/Document.cpp, Userland/Libraries/LibWeb/DOM/Document.h, Userland/Libraries/LibWeb/HTML/Navigable.cpp, Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp
cc: @shannonbooth as you reported a spec bug that https://github.com/whatwg/html/pull/10704 fixed.
=> LibWeb: Update history steps to match recent spec changes

Tests/LibWeb/Ref/input/wpt-import/css/css-color/lab-001.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/lch-001.html, Tests/LibWeb/Ref/input/wpt-import/css/css-color/xyz-d50-001.html
Specifically, they are related to parsing the `lab()`, `lch()` and `color(xyz-d50 ...)` color functions.
=> Tests: Import WPT tests from css-color

Userland/Libraries/LibJS/Runtime/CommonPropertyNames.h, Userland/Libraries/LibJS/Runtime/ErrorConstructor.cpp, Userland/Libraries/LibJS/Runtime/ErrorConstructor.h, Userland/Libraries/LibJS/Runtime/Value.cpp, Userland/Libraries/LibJS/Runtime/Value.h, Userland/Libraries/LibJS/Tests/builtins/Error/Error.isError.js
Implementing the stage 2.7 proposal:
https://github.com/tc39/proposal-is-error
=> LibJS: Implement Error.isError

AK/StackInfo.cpp, Libraries/LibCore/ThreadEventQueue.cpp, Libraries/LibJS/AST.cpp, Libraries/LibJS/Runtime/ClassFieldDefinition.h, Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp, Libraries/LibJS/Runtime/Object.cpp, Services/WebContent/ConnectionFromClient.cpp, UI/AppKit/Interface/TabController.mm
There are still some hefty leaks to track down, but here's a first cut of some stuff I found. :)
=> Mixed bag of GC leak fixes and improvements for Speedometer

Libraries/LibWeb/CSS/ComputedValues.h, Libraries/LibWeb/CSS/StyleProperties.cpp, Libraries/LibWeb/HTML/HTMLSelectElement.cpp, Libraries/LibWeb/HTML/SelectItem.cpp, Libraries/LibWeb/HTML/SelectItem.h, Libraries/LibWeb/Painting/Command.h, Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp, Libraries/LibWeb/Painting/DisplayListRecorder.cpp
This PR rearranges some of the structs to use less memory on 64-bit systems
=> Rearrange structs

Libraries/LibJS/Heap/GCPtr.h, Libraries/LibJS/Heap/Heap.cpp, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/Loader/ResourceLoader.cpp, Libraries/LibWeb/Loader/ResourceLoader.h, Meta/Lagom/ClangPlugins/LibJSGCPluginAction.cpp
With these fixes, GC heap size at the end of 1 run goes from 540MB to 80MB on my machine. :)
=> More GC fixes for Speedometer

Tests/LibWeb/TestConfig.ini
Occasionally seeing this time out.
=> LibWeb: Disable HTTP server test

Tests/LibWeb/TestConfig.ini
=> Tests: Skip flaky text-as-flexitem-size test

Libraries/LibWeb/Bindings/OptionConstructor.cpp, Libraries/LibWeb/HTML/HTMLOptionElement.cpp, Libraries/LibWeb/HTML/HTMLOptionElement.h, Libraries/LibWeb/HTML/HTMLOptionElement.idl, Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-option-element/option-element-constructor.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-option-element/option-label.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-option-element/option-text-recurse.txt
See individual commits, fixes various WPT tests :)
=> Small bag of HTMLOptionElement fixes

Libraries/LibWeb/Crypto/SubtleCrypto.cpp
Our spec issue got resolved, including a bonus fix!
See: https://github.com/w3c/webcrypto/pull/384
=> LibWeb: Update spec implementation for SubtleCrypto.deriveKey()

AK/StringView.h, AK/Utf8View.h, Tests/AK/TestStringView.cpp, Tests/AK/TestUtf8.cpp
Explanations in the commit messages. I am deep in the yaks with this.
Oh and the splitting is used in some code I'm working on, I just don't think that'll be finished for a while and this is a self-contained change.
=> AK: Add Utf8View splitting; fix a StringView comparison bug

Libraries/LibWeb/CMakeLists.txt, Meta/CMake/libweb_generators.cmake, Meta/CMake/utils.cmake
A shot in the dark to try and fix CI: https://github.com/LadybirdBrowser/ladybird/actions/runs/11857444468/job/33045830292
=> LibWeb: Include GeneratedCSSStyleProperties.idl in GENERATED_SOURCES

Libraries/LibWeb/HTML/Window.cpp
This adapts to the latest HTML spec which fixed the issue we had reported of:
https://github.com/whatwg/html/commit/316b83
=> LibWeb: Change URL parsing sequence for window open steps

Libraries/LibJS/Runtime/ShadowRealmConstructor.cpp, Libraries/LibJS/Runtime/VM.cpp
The proposed changes have been merged into the proposal with:
https://github.com/tc39/proposal-shadowrealm/commit/f20d02
=> LibJS: Align spec comments for ShadowRealm for HostInitializeShadowRealm

Services/RequestServer/ConnectionFromClient.cpp
libcurl will automatically set the Content-Type header when using the CURLOPT_POSTFIELDS option to "application/x-www-form-urlencoded".
See: https://curl.se/libcurl/c/CURLOPT_POSTFIELDS.html
The following WPT cases now pass (8 tests):
http://wpt.live/xhr/send-blob-with-no-mime-type.html
=> RequestServer: Clear "Content-Type" header when one isn't provided

Libraries/LibWeb/HTML/HTMLFieldSetElement.cpp, Libraries/LibWeb/HTML/HTMLFieldSetElement.h, Libraries/LibWeb/HTML/HTMLLegendElement.cpp, Libraries/LibWeb/HTML/HTMLLegendElement.h, Libraries/LibWeb/Layout/FieldSetBox.cpp, Libraries/LibWeb/Layout/FieldSetBox.h, Libraries/LibWeb/Layout/LegendBox.cpp, Libraries/LibWeb/Layout/LegendBox.h
=> LibWeb: Use GC namespace in LegendBox and FieldSetBox

Tests/LibWeb/Text/expected/WebAnimations/misc/steps-serialization.txt
Fixes failing test introduced by b342758dbf8d1138353db89708964e75b9128400
=> Tests/LibWeb: Rebaseline WebAnimations/misc/steps-serialization.html

Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWeb/DOM/Node.h, Libraries/LibWeb/XML/XMLDocumentBuilder.cpp, Libraries/LibWeb/XML/XMLDocumentBuilder.h, Libraries/LibXML/Parser/Parser.cpp, Libraries/LibXML/Parser/Parser.h, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Node-nodeName-xhtml.txt, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Node-normalize.txt, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Node-replaceChild.txt, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Node-nodeName-xhtml.xhtml, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Node-normalize.html, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Node-replaceChild.html, Tests/LibWeb/Text/input/wpt-import/dom/nodes/pre-insertion-validation-notfound.js
Couple more things I found by opening random WPT tests :^)
=> More random DOM fixes

Libraries/LibWeb/Fetch/Fetching/Fetching.cpp, Libraries/LibWeb/Fetch/Infrastructure/HTTP.h, Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp, Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.h, Libraries/LibWeb/XHR/XMLHttpRequest.cpp, Tests/LibWeb/Text/expected/wpt-import/xhr/blob-range.any.txt, Tests/LibWeb/Text/input/wpt-import/xhr/blob-range.any.html, Tests/LibWeb/Text/input/wpt-import/xhr/blob-range.any.js
Now passing eleven new WPT test cases here: http://wpt.live/xhr/blob-range.any.html
=> LibWeb: Implement blob range spec and fix XHR header bug

Libraries/LibFileSystem/FileSystem.cpp
This reverts part of  b3c253e50fe630bdf6907fd0641c58975cbcebc5
=> LibFileSystem: Fix Windows build

.github/workflows/lagom-template.yml
Fixes #2479
Likely broke with #1717
=> CI: Use correct path to upload ref test dumps

Libraries/LibWeb/WebIDL/OverloadResolution.cpp, Tests/LibWeb/Text/expected/wpt-import/webmessaging/Channel_postMessage_clone_port_error.any.txt, Tests/LibWeb/Text/input/wpt-import/webmessaging/Channel_postMessage_clone_port_error.any.html, Tests/LibWeb/Text/input/wpt-import/webmessaging/Channel_postMessage_clone_port_error.any.js
=> LibWeb: Implement overload resolution for sequence types

Libraries/LibCore/ElapsedTimer.h, Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp, Services/RequestServer/ConnectionFromClient.cpp
This follows FIXME in the code.
=> LibCore: Remove deprecated ElapsedTimer::elapsed()

Libraries/LibWeb/Bindings/Serializable.h, Libraries/LibWeb/Crypto/CryptoKey.cpp, Libraries/LibWeb/Fetch/Infrastructure/FetchController.cpp, Libraries/LibWeb/Fetch/Infrastructure/FetchController.h, Libraries/LibWeb/FileAPI/File.cpp, Libraries/LibWeb/FileAPI/FileList.cpp, Libraries/LibWeb/Geometry/DOMQuad.cpp, Libraries/LibWeb/HTML/StructuredSerialize.cpp, Libraries/LibWeb/HTML/StructuredSerialize.h, Libraries/LibWeb/HTML/StructuredSerializeTypes.h, Libraries/LibWeb/Streams/ReadableStream.cpp, Libraries/LibWeb/WebIDL/DOMException.cpp, Libraries/LibWeb/WebIDL/DOMException.h, Tests/LibWeb/Text/expected/Fetch/fetch-controller-abort.txt, Tests/LibWeb/Text/expected/HTML/StructuredClone-serializable-objects.txt, Tests/LibWeb/Text/input/Fetch/fetch-controller-abort.html, Tests/LibWeb/Text/input/HTML/StructuredClone-serializable-objects.html
=> LibWeb: Add serialization and deserilization steps to DOMException + Implement FetchController::abort()

Libraries/LibWeb/FileAPI/Blob.cpp
TemporaryExecutionContext has support to prepare for callbacks so we can use it here now instead of setting this up manually.
=> LibWeb: Switch to using TemporaryExecutionContext

Libraries/LibDNS/Resolver.h, Services/RequestServer/ConnectionFromClient.cpp
...and make sure it will eventually complete (or fail) by adding a timeout retry sequence.
Fixes an issue where RequestServer would stick around after exit, waiting for piled up DNS requests for a long time.
=> RequestServer+LibDNS: Don't .await() the DNS lookup promise

Libraries/LibWeb/CMakeLists.txt, Libraries/LibWeb/IndexedDB/IDBFactory.cpp, Libraries/LibWeb/IndexedDB/IDBFactory.h, Libraries/LibWeb/IndexedDB/IDBFactory.idl, Libraries/LibWeb/IndexedDB/Internal/Algorithms.cpp, Libraries/LibWeb/IndexedDB/Internal/Algorithms.h, Libraries/LibWeb/IndexedDB/Internal/Key.cpp, Libraries/LibWeb/IndexedDB/Internal/Key.h, Libraries/LibWeb/Infra/Strings.cpp, Libraries/LibWeb/Infra/Strings.h, Tests/LibWeb/Text/expected/wpt-import/IndexedDB/idbfactory_cmp.txt, Tests/LibWeb/Text/expected/wpt-import/IndexedDB/idbfactory_cmp2.txt, Tests/LibWeb/Text/expected/wpt-import/IndexedDB/idbfactory_cmp3.txt, Tests/LibWeb/Text/expected/wpt-import/IndexedDB/idbfactory_cmp4.txt, Tests/LibWeb/Text/expected/wpt-import/IndexedDB/keyorder.txt, Tests/LibWeb/Text/input/wpt-import/IndexedDB/idbfactory_cmp.htm, Tests/LibWeb/Text/input/wpt-import/IndexedDB/idbfactory_cmp2.htm, Tests/LibWeb/Text/input/wpt-import/IndexedDB/idbfactory_cmp3.htm, Tests/LibWeb/Text/input/wpt-import/IndexedDB/idbfactory_cmp4.htm, Tests/LibWeb/Text/input/wpt-import/IndexedDB/keyorder.htm, Tests/LibWeb/Text/input/wpt-import/IndexedDB/resources/support.js
100% passing on
https://wpt.live/IndexedDB/idbfactory_cmp.htm
https://wpt.live/IndexedDB/idbfactory_cmp2.htm
https://wpt.live/IndexedDB/idbfactory_cmp3.htm
https://wpt.live/IndexedDB/idbfactory_cmp4.htm
=> LibWeb: Implement IDBFactory::cmp

Tests/LibCore/TestLibCoreFileWatcher.cpp
This test could fail when `/tmp/testfile` already exists.
There also shouldn't be a need to wait so long for this test,
except for on MacOS, where the `FileWatcher` implementation is
apparently less reliable.
=> Tests: Make `TestLibCoreFileWatcher` more reliable

Libraries/LibWeb/Streams/AbstractOperations.cpp
Our bug report has been resolved in the same way we had already applied a fix (just with some asserts added) with:
https://github.com/whatwg/streams/commit/86d07e
=> LibWeb/Streams: Update comments for resolved spec bug

Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
=> LibWeb: Remove a misleading duplicate comment in HTMLParser

Libraries/LibWeb/Editing/CommandNames.cpp
Was introduced in https://github.com/LadybirdBrowser/ladybird/pull/2655
=> LibWeb/Editing: Fix small copy-paste error

Libraries/LibDNS/Resolver.h
Fixes an issue with unfinished requests being evicted, leading to requests never finishing.
=> LibDNS: Don't purge lookup entries that are not yet fully resolved

Libraries/LibDNS/Resolver.h, Services/RequestServer/ConnectionFromClient.cpp
=> LibDNS+RequestServer: Miscellaneous fixes and cleanup

Libraries/LibWeb/Bindings/MainThreadVM.cpp, Tests/LibWeb/Text/expected/HTML/ModuleLoading/import-inside-of-a-module.txt, Tests/LibWeb/Text/input/HTML/ModuleLoading/import-in-a-module.js, Tests/LibWeb/Text/input/HTML/ModuleLoading/import-inside-of-a-module.html
Fixes: #2676
Regression from 5af613aa657ebc03b93891c955f4ee62eaef7e53
=> LibWeb: Ensure requests modules is not empty before indexing into it

Tests/LibWeb/Text/expected/wpt-import/dom/events/Event-constants.txt, Tests/LibWeb/Text/input/wpt-import/dom/constants.js
I reimported and rebaselined it using the latest version of our WPT importer. Now it passes.
Original import at aa9ed71ff34
=> Tests: Reimport Event-constants WPT

Libraries/LibWeb/IndexedDB/IDBRequest.idl, Tests/LibWeb/Text/expected/wpt-import/IndexedDB/idbfactory_open.any.txt
Removes fixme introduced in bfa330914d1
@shannonbooth I would be happy to know the reason for this FIXME and if it's safe to remove it
=> LibWeb: Remove IDBRequest.idl FIXME

Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
`AsyncBlockStart` was still doing a `DisposeResources` call as specified in older drafts of the `explicit-resource-management` proposal, but the latest draft no longer does this, and it is causing crashes when combined with the `array-from-async` proposal.
47161/48623 ( 96.99%) [ ✅ 47161 ❌ 1235  ⚠️ 2     ⚙️ 112   💥️ 85    📝 28    ] 
47208/48623 ( 97.09%) [ ✅ 47208 ❌ 1239  ⚠️ 2     ⚙️ 112   💥️ 34    📝 28    ]
=> LibJS: Align `AsyncBlockStart` with the latest drafts

Libraries/LibWeb/Editing/Commands.cpp, Libraries/LibWeb/Editing/Commands.h, Libraries/LibWeb/Editing/Internal/Algorithms.cpp, Libraries/LibWeb/Editing/Internal/Algorithms.h, Tests/LibWeb/Text/expected/Editing/execCommand-insertParagraph.txt, Tests/LibWeb/Text/input/Editing/execCommand-insertParagraph.html
At least 1045 additional WPT passes in `editing`!
=> LibWeb: Implement document.execCommand("insertParagraph")

Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h, Libraries/LibWeb/HTML/Canvas/CanvasPathDrawingStyles.h
I have tried benchmarking, it looks like this provides no noticeable difference on my system, but it's still a nice-to-have I guess.
=> Random move goodies

AK/Assertions.h, AK/Badge.h, AK/Concepts.h, AK/JsonArray.h, AK/NonnullRawPtr.h, AK/StdLibExtraDetails.h, AK/Try.h, Libraries/LibJS/Runtime/Completion.h, Meta/lint-ci.sh
Many of these are only needed for #2442, but they're improvements nonetheless.
=> Random goodie-bag of improvements

Tests/LibWeb/Ref/input/css-keyframe-invalid-transform-should-not-render.html
This increases the animation length on this test as it has been failing for me locally.
=> Tests: Make test less flaky

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp
Fixes https://github.com/LadybirdBrowser/ladybird/issues/2759
=> CodeGenerators: Implement getParameter() according to the WebGL spec

Libraries/LibWeb/WebGL/WebGLRenderingContextBase.idl, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp
With this change we have enough WebGL support to display demos on https://ciechanow.ski/lights-and-shadows/ but most of them are not redering correctly yet.
=> LibWeb/WebGL: Implement getShaderInfoLog()

Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/Navigable.h, Libraries/LibWeb/HTML/Window.cpp, Libraries/LibWeb/HTML/Window.h, Libraries/LibWeb/HTML/Window.idl, Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/expected/wpt-import/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/aborted-parser.window.txt, Tests/LibWeb/Text/input/wpt-import/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/aborted-parser.window.html, Tests/LibWeb/Text/input/wpt-import/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/aborted-parser.window.js, Tests/LibWeb/Text/input/wpt-import/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/resources/aborted-parser-async-frame.html, Tests/LibWeb/Text/input/wpt-import/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/resources/aborted-parser-frame.html
Fixes a handful of timeouts on WPT.
=> LibWeb: Implement window.stop()

Libraries/LibWeb/WebGL/WebGLRenderingContextBase.idl, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp
- isContextLost()
- bindAttribLocation()
- getProgramInfoLog()
=> Implement a bit more WebGL calls

Libraries/LibURL/Host.cpp, Libraries/LibURL/Parser.cpp, Libraries/LibURL/URL.cpp, Libraries/LibUnicode/IDNA.cpp, Libraries/LibUnicode/IDNA.h
No new WPT test changes or fixes associated with the IDNA normative changes, but this keeps us up to date with the spec.
=> LibURL: Catch up to some normative and editorial spec changes

Libraries/LibCore/Process.cpp, Libraries/LibCore/Process.h, Libraries/LibWeb/Internals/Internals.cpp, Libraries/LibWeb/Internals/Internals.h, Libraries/LibWeb/Internals/Internals.idl, Libraries/LibWebView/Application.h, Libraries/LibWebView/HelperProcess.cpp, Libraries/LibWebView/Options.h, Services/WebContent/main.cpp, Tests/LibWeb/Fixtures/http-test-server.py, Tests/LibWeb/TestConfig.ini, Tests/LibWeb/Text/input/include.js, UI/Headless/Application.cpp, UI/Headless/Fixture.cpp, UI/Headless/Fixture.h
=> Refactor HTTP echo server, test internals plumbing

Tests/LibWeb/Fixtures/http-test-server.py, Tests/LibWeb/Text/expected/http-reason-phrase-propagation.txt, Tests/LibWeb/Text/input/http-reason-phrase-propagation.html
=> Tests/LibWeb: Add test for propagation of custom HTTP reason phrase, and other goodies

Libraries/LibCore/CMakeLists.txt
This commit conditionally includes the correct implementation file.
=> LibCore: Add ProcessWindows.cpp to CMakeLists

Libraries/LibWeb/Forward.h, Libraries/LibWeb/WebGL/WebGL2RenderingContextBase.idl, Libraries/LibWeb/WebGL/WebGL2RenderingContextOverloads.idl, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp
With this change we can render a triangle using WebGL 2!
=> Implement a bit more WebGL 2 calls

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp
...and delete some unnecessary code.
=> Use snake case for function params in generated WebGL code

AK/BumpAllocator.h
Ports BumpAllocator.h to Windows using VirtualAlloc, a Windows API. This is done to avoid additional dependecies for AK.
=> AK: Port BumpAllocator.h to Windows

Libraries/LibWeb/CSS/ComputedValues.h
=> ComputedValues.h: minor optimizations

Libraries/LibWeb/Editing/Commands.cpp, Libraries/LibWeb/Editing/Commands.h, Tests/LibWeb/Text/expected/Editing/execCommand-insertLinebreak.txt, Tests/LibWeb/Text/input/Editing/execCommand-insertLinebreak.html
Adds an additional 1095 WPT passes in `editing`.
=> LibWeb: Implement document.execCommand('insertLinebreak')

Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp, Libraries/LibJS/Runtime/Temporal/TimeZone.cpp, Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
=> LibJS: More Temporal editorial updates

Libraries/LibWeb/Selection/Selection.cpp
=> LibWeb: Update spec steps in Selection.collapse() and .selectAllChildren()

Documentation/AdvancedBuildInstructions.md
This change updates the (advanced) build docs to explain how to do a Debug build with the CXX `-O0` option set — which tells the compiler to build with no optimizations at all.
Otherwise, Debug builds use the `-Og` option — which, when trying to check frame variables in a debugger can result in an error of this form:
> error: Couldn't look up symbols: __ZN2AK6Detail10StringBaseD2Ev
> Hint: The expression tried to call a function that is not present in the target, perhaps because it was optimized out by the compiler.
This is an alternative to https://github.com/LadybirdBrowser/ladybird/pull/2186 and https://github.com/LadybirdBrowser/ladybird/pull/2190.
=> Docs: Explain how to do Debug builds without optimizations on

Tests/LibWeb/Text/expected/wpt-import/html-aam/names.txt, Tests/LibWeb/Text/expected/wpt-import/html-aam/roles-generic.txt, Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/menu-roles.txt, Tests/LibWeb/Text/input/wpt-import/html-aam/names.html, Tests/LibWeb/Text/input/wpt-import/html-aam/roles-generic.html, Tests/LibWeb/Text/input/wpt-import/wai-aria/role/menu-roles.html
We’re passing all the tests in this patch on trunk — so let’s go ahead and welcome them into our regression-testing garden.
Reviewers: Note that this is 100% tests-only — no code changes to review.
=> Tests: Import some ARIA and HTML-AAM (regression) tests (no code)

Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLElement.h, Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/popover-beforetoggle-opening-event.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/togglePopover.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/toggleevent-interface.txt, Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/popover-beforetoggle-opening-event.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/toggleevent-interface.html
Implement popover beforetoggle and toggle events
=> LibWeb: Implement popover beforetoggle and toggle events

Tests/LibJS/test262-runner.cpp
For example, for the following `includes` line in a test262 file:
```js
includes: [sm/non262-TypedArray-shell.js, sm/non262.js]
```
We currently parse and execute each file in this list as its own script,
in the order they appear in the list.
Tests have recently been imported test262 from SpiderMonkey which fail
with this behavior. In the above example, if the first script references
some function from the second script, we will currently fail to execute
that harness file.
This patch changes our behavior to concatenate all harness files into a
single script, which satisfies the behavior required by these new tests.
This is how test262.fyi and other test262 runners already behave.
test262 diff:
```
Diff Tests:
+61 ✅    -31 ❌    -30 ⚙
test/staging/sm/Math/20.2.2.ToNumber.js …
```
=> LibJS: Concatenate all included test262 harness files to a single script

Libraries/LibWeb/HTML/HTMLIFrameElement.cpp, Libraries/LibWeb/HTML/HTMLIFrameElement.h, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/insertion-removing-steps/Node-appendChild-script-and-iframe.tentative.txt, Tests/LibWeb/Text/input/wpt-import/dom/nodes/insertion-removing-steps/Node-appendChild-script-and-iframe.tentative.html
See: https://github.com/whatwg/html/commit/c8ec987d1
=> LibWeb/HTML: Use DOM's post-connection steps for iframe elements

Libraries/LibWeb/IndexedDB/IDBFactory.cpp, Libraries/LibWeb/IndexedDB/IDBFactory.h, Libraries/LibWeb/IndexedDB/IDBFactory.idl, Libraries/LibWeb/IndexedDB/IDBRequest.h, Libraries/LibWeb/IndexedDB/IDBTransaction.cpp, Libraries/LibWeb/IndexedDB/IDBTransaction.h, Libraries/LibWeb/IndexedDB/IDBTransaction.idl, Libraries/LibWeb/IndexedDB/Internal/Algorithms.cpp, Libraries/LibWeb/IndexedDB/Internal/Algorithms.h, Libraries/LibWeb/IndexedDB/Internal/Database.h, Tests/LibWeb/Text/expected/wpt-import/IndexedDB/idbfactory_open.any.txt
[wpt.live/IndexedDB/idbfactory_open.any.html](https://wpt.live/IndexedDB/idbfactory_open.any.html)
Old stats:
passes: 23/29
fails: 6/29
New stats:
passes: 27/29
fails: 2/29
=> LibWeb: Even more progress on IndexedDB 

Libraries/LibWeb/Animations/AnimationEffect.cpp
Copies https://github.com/LadybirdBrowser/ladybird/pull/1372, but I rebased it on master and linted it so CI should be fine
=> LibWeb/CSS: Refactor phase() method to reduce redundancy

Libraries/LibWeb/HTML/ErrorEvent.cpp, Libraries/LibWeb/HTML/ErrorEvent.h, Tests/LibWeb/Text/expected/wpt-import/html/webappapis/scripting/processing-model-2/addEventListener.txt, Tests/LibWeb/Text/input/wpt-import/html/webappapis/scripting/processing-model-2/addEventListener.html
=> LibWeb/HTML: Make ErrorEvent::create a trusted event

Libraries/LibWeb/Crypto/CryptoBindings.cpp
We do not concern ourselves with small OOM handling any longer. But the main point of this patch is that we are for some reason getting a build error with clang-19 here about ignoring a `nodiscard` return type inside `JsonArray::try_for_each`:
```
In file included from Libraries/LibWeb/Crypto/CryptoBindings.cpp:8:
In file included from AK/JsonObject.h:15:
AK/JsonArray.h:94:13: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
94 |             TRY(callback(value));
|             ^~~~~~~~~~~~~~~~~~~~
AK/Try.h:36:9: note: expanded from macro 'TRY'
36 |         _temporary_result.release_value();                                                           \
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
=> LibWeb: Do not worry about small OOM in JsonWebKey::parse

Libraries/LibWeb/HTML/Window.cpp, Tests/LibWeb/Text/expected/HTML/Window-open-blob-url-without-blob-entry.txt, Tests/LibWeb/Text/input/HTML/Window-open-blob-url-without-blob-entry.html
See: https://github.com/whatwg/html/pull/10847
=> LibWeb/HTML: Add null handling for "get noopener for window open"

Documentation/BuildInstructionsLadybird.md, flake.lock, flake.nix, shell.nix
Applys 4d7b7178f9d50fff97101ea18277ebc9b60e2c7c to the skia used by the devshell
=> Flake/devshell: Port skia skcms fix from local vcpkg overlay

Libraries/LibWeb/Bindings/AudioConstructor.cpp, Libraries/LibWeb/Bindings/ImageConstructor.cpp, Libraries/LibWeb/Bindings/OptionConstructor.cpp, Libraries/LibWeb/DOM/Attr.cpp, Libraries/LibWeb/DOM/DOMImplementation.cpp, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Element.cpp, Libraries/LibWeb/DOM/Range.cpp, Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Libraries/LibWeb/HTML/HTMLTableRowElement.cpp, Libraries/LibWeb/HTML/HTMLTableSectionElement.cpp, Libraries/LibWeb/HTML/Parser/HTMLParser.cpp, Libraries/LibWeb/HTML/Window.h, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
This is basically all just comment changes - the code difference is minimal.
=> LibWeb: Update to match recent HTML spec changes

Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWeb/DOM/Node.h, Libraries/LibWeb/TreeNode.h
* Clean up unused methods in Node and TreeNode
* Resolve a performance FIXME in Node::is_equal_node()
=> LibWeb: Two small DOM::Node improvements

AK/QuickSort.h, Libraries/LibRegex/RegexMatcher.cpp, Libraries/LibRegex/RegexParser.cpp, Libraries/LibTLS/Handshake.cpp, Libraries/LibWeb/HTML/NavigateEvent.cpp, Libraries/LibWeb/HTML/SyntaxHighlighter/SyntaxHighlighter.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp, Tests/LibWeb/CMakeLists.txt, Tests/LibWeb/TestCSSInheritedProperty.cpp
I wrote these being half asleep, please be careful with merging
=> Some minor improvements here and there

Libraries/LibWeb/XHR/FormData.cpp, Libraries/LibWeb/XHR/FormData.h, Libraries/LibWeb/XHR/FormData.idl, Tests/LibWeb/Text/expected/wpt-import/xhr/formdata/constructor-submitter.txt, Tests/LibWeb/Text/input/wpt-import/xhr/formdata/constructor-submitter.html
This makes some progress on http://wpt.live/xhr/formdata/constructor-submitter.html
However, WPT.sh fails to import that test..
=> LibWeb: Update FormData constructor to reflect the spec

shell.nix
The list now includes:
- clang-tools: For clangd and clang-format
- pre-commit: For the pre-commit hooks
- prettier: For web-related formatting
=> Flake/devshell: Add more useful packages

Libraries/LibWeb/HTML/HTMLCanvasElement.cpp, Libraries/LibWeb/HTML/HTMLCanvasElement.h, Tests/LibWeb/Text/expected/canvas-changed-width-attribute.txt, Tests/LibWeb/Text/input/canvas-changed-width-attribute.html
Fixes a crash on https://desmos.com/.
=> LibWeb: Notify canvas context when width or height attribute is changed

Libraries/LibWeb/DOM/Document.cpp, Tests/LibWeb/Text/expected/wpt-import/css/css-transitions/CSSTransition-effect.tentative.txt, Tests/LibWeb/Text/input/wpt-import/css/css-transitions/CSSTransition-effect.tentative.html, Tests/LibWeb/Text/input/wpt-import/css/css-transitions/support/helper.js
Fixes a crash on:
- css/css-transitions/CSSTransition-effect.tentative.html
=> LibWeb/DOM: Don't assume that Animations have an associated effect

Libraries/LibWeb/Animations/AnimationTimeline.cpp, Libraries/LibWeb/DOM/Document.cpp, Tests/LibWeb/Text/expected/wpt-import/css/css-animations/CSSAnimation-effect.tentative.txt, Tests/LibWeb/Text/input/wpt-import/css/css-animations/CSSAnimation-effect.tentative.html, Tests/LibWeb/Text/input/wpt-import/css/css-animations/support/testcommon.js
Specifically, this makes this test pass (and imports it):
- css/css-animations/CSSAnimation-effect.tentative.html
=> LibWeb/DOM+Animations: Fix some animations-related crashes

Libraries/LibWeb/Painting/PaintableBox.cpp
In particular:
- Don't compute DOM node editability if we don't need it. This was 22% of CPU time when scrolling on Wikipedia.
- Defer inversion of transformed coordinates until we actually need them, after we've performed early returns.
=> LibWeb: Reorder some checks in PaintableWithLines::hit_test for speed

Libraries/LibWeb/CMakeLists.txt, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/Forward.h, Libraries/LibWeb/HTML/MessagePort.cpp, Libraries/LibWeb/HTML/MessagePort.h, Libraries/LibWeb/HTML/Storage.cpp, Libraries/LibWeb/HTML/Storage.h, Libraries/LibWeb/HTML/TraversableNavigable.h, Libraries/LibWeb/HTML/Window.cpp, Libraries/LibWeb/StorageAPI/StorageBottle.cpp, Libraries/LibWeb/StorageAPI/StorageBottle.h, Libraries/LibWeb/StorageAPI/StorageEndpoint.cpp, Libraries/LibWeb/StorageAPI/StorageEndpoint.h, Libraries/LibWeb/StorageAPI/StorageShed.cpp, Libraries/LibWeb/StorageAPI/StorageShed.h, Libraries/LibWeb/StorageAPI/StorageShelf.cpp, Libraries/LibWeb/StorageAPI/StorageShelf.h, Libraries/LibWeb/StorageAPI/StorageType.h, Tests/LibWeb/Text/expected/wpt-import/webstorage/event_session_storagearea.txt, Tests/LibWeb/Text/expected/wpt-import/webstorage/storage_local_setitem_quotaexceedederr.window.txt, Tests/LibWeb/Text/expected/wpt-import/webstorage/storage_session_setitem_quotaexceedederr.window.txt, Tests/LibWeb/Text/input/wpt-import/webstorage/event_session_storagearea.html, Tests/LibWeb/Text/input/wpt-import/webstorage/resources/session_set_item_iframe.html, Tests/LibWeb/Text/input/wpt-import/webstorage/storage_local_setitem_quotaexceedederr.window.html, Tests/LibWeb/Text/input/wpt-import/webstorage/storage_session_setitem_quotaexceedederr.window.html
See commits for details. Sitting ontop of https://github.com/LadybirdBrowser/ladybird/pull/3016.
=> LibWeb/HTML: Implement storage broadcast events and create storage per document

Libraries/LibWeb/WebAudio/BaseAudioContext.cpp, Libraries/LibWeb/WebAudio/BaseAudioContext.h, Libraries/LibWeb/WebAudio/BaseAudioContext.idl, Libraries/LibWeb/WebAudio/PeriodicWave.cpp, Libraries/LibWeb/WebAudio/PeriodicWave.h, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-periodicwave-interface/periodicWave.txt, Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-periodicwave-interface/periodicWave.html
This makes all increases the number of passing subtests in: http://wpt.live/webaudio/the-audio-api/the-periodicwave-interface/periodicWave.html.
=> LibWeb/WebAudio: Implement `PeriodicWave` constructor

Libraries/LibWeb/WebDriver/Actions.cpp, Libraries/LibWeb/WebDriver/Actions.h, Services/WebContent/WebDriverConnection.cpp
=> LibWeb/WebDriver: Use action queues for undo actions

Documentation/GettingStartedContributing.md
As many other projects, Ladybird has more than a few TODO and FIXME comments sprinkled throughout the codebase. These can be a great inspiration or starting point for contributors looking for work, so we mention them in the docs on contributing to the project.
=> Documentation: Mention TODOs and FIXMEs as potential sources of work

Libraries/LibWeb/HTML/ErrorEvent.h, Libraries/LibWeb/HTML/ErrorEvent.idl, Tests/LibWeb/Text/expected/wpt-import/html/webappapis/scripting/events/event-handler-processing-algorithm-error/document-synthetic-errorevent.txt, Tests/LibWeb/Text/input/wpt-import/html/webappapis/scripting/events/event-handler-processing-algorithm-error/document-synthetic-errorevent.html
This was a change in the HTML spec, see:
https://github.com/whatwg/html/commit/032523196
=> LibWeb/HTML: Default ErrorEvent error to undefined

Libraries/LibWebView/CookieJar.cpp, Libraries/LibWebView/CookieJar.h, UI/Qt/BrowserWindow.cpp
=> LibWebView+UI/Qt: Add option to remove all cookies

vcpkg.json
Resolves https://github.com/LadybirdBrowser/ladybird/issues/2257
It's fine for me locally on a Mac, let's check other platforms on the CI
=> Meta: Update ffmpeg to 7.1

Libraries/LibWeb/HTML/Storage.cpp
See: https://github.com/whatwg/html/commit/8d2829a
=> LibWeb/HTML: Update editorial spec comments for Storage

Libraries/LibWeb/WebAudio/AudioContext.cpp, Libraries/LibWeb/WebAudio/AudioDestinationNode.cpp, Libraries/LibWeb/WebAudio/AudioDestinationNode.h, Libraries/LibWeb/WebAudio/AudioNode.cpp, Libraries/LibWeb/WebAudio/AudioNode.h, Libraries/LibWeb/WebAudio/BaseAudioContext.cpp, Libraries/LibWeb/WebAudio/BaseAudioContext.h, Libraries/LibWeb/WebAudio/OfflineAudioContext.cpp, Libraries/LibWeb/WebAudio/OfflineAudioContext.h, Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-offlineaudiocontext-interface/ctor-offlineaudiocontext.txt, Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-offlineaudiocontext-interface/ctor-offlineaudiocontext.html
This fixes all subtests in: http://wpt.live/webaudio/the-audio-api/the-offlineaudiocontext-interface/ctor-offlineaudiocontext.html
=> LibWeb: Initialize `OfflineAudioContext` with correct defaults

Libraries/LibWeb/WebAudio/AudioBufferSourceNode.cpp, Libraries/LibWeb/WebAudio/AudioBufferSourceNode.h, Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-audiobuffersourcenode-interface/ctor-audiobuffersource.txt, Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-audiobuffersourcenode-interface/ctor-audiobuffersource.html
This fixes all subtests in: http://wpt.live/webaudio/the-audio-api/the-audiobuffersourcenode-interface/ctor-audiobuffersource.html
=> LibWeb: Initialize `AudioBufferSourceNode` with correct defaults

Libraries/LibWeb/WebGL/OpenGLContext.cpp, Libraries/LibWeb/WebGL/OpenGLContext.h, Libraries/LibWeb/WebGL/WebGL2RenderingContext.cpp, Libraries/LibWeb/WebGL/WebGL2RenderingContextBase.idl, Libraries/LibWeb/WebGL/WebGL2RenderingContextOverloads.idl, Libraries/LibWeb/WebGL/WebGLRenderingContext.cpp, Libraries/LibWeb/WebGL/WebGLRenderingContextBase.h, Libraries/LibWeb/WebGL/WebGLRenderingContextBase.idl, Libraries/LibWeb/WebGL/WebGLRenderingContextOverloads.idl, Libraries/LibWeb/WebIDL/Buffers.cpp, Libraries/LibWeb/WebIDL/Buffers.h, Libraries/LibWeb/WebIDL/OverloadResolution.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp
This is enough for Unity Web games to start working! (Note that this video is fairly compressed to fit inside GitHub's file size limit :^))
https://github.com/user-attachments/assets/c3f767f0-1e58-4ff1-8958-7aed32f402aa
=> LibWeb/WebGL: Implement more function calls, fix uniforms being incorrectly discarded when using offsets

AK/ScopeGuard.h
Brought to you by a significant amount of pain and suffering, which this would have prevented.
=> AK: Make ScopeGuard and ArmedScopeGuard [[nodiscard]]

UI/AppKit/Application/ApplicationDelegate.mm
This was already available in QT chrome.
=> UI/AppKit: Add debug menu item to clear all cookies

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/URL/url-search-params-iterator-iterator.txt, Tests/LibWeb/Text/expected/wpt-import/webidl/ecmascript-binding/default-iterator-object.txt, Tests/LibWeb/Text/input/wpt-import/webidl/ecmascript-binding/default-iterator-object.html
Fixes: http://wpt.live/webidl/ecmascript-binding/default-iterator-object.html
=> IDLGenerators: Set Iterator `@@toStringTag` with correct descriptor

AK/Format.cpp
=> AK: Show executable name in rich debug format on Windows

Libraries/LibJS/Runtime/DateConstructor.cpp, Libraries/LibJS/Tests/builtins/Date/Date.parse.js
This was getting called on abc.com
=> LibJS: Parse dates like "Wednesday, Jan 15, 2025"

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp
=> LibWeb/WebGL2: Implement two more getParameter() calls

Libraries/LibWeb/CSS/Interpolation.cpp
Assuming all calculations produce `<length-percentage>` is a very bad assumption, and was causing crashes on https://ai.cloudflare.com/
This is a temporary fix, as I think removing the separate `Transform` and `TransformValue` types entirely would be better, but that's going to take me a bit longer.
=> LibWeb/CSS: Properly classify calculations inside transform functions

AK/COWVector.h, Libraries/LibRegex/RegexMatch.h, Libraries/LibRegex/RegexMatcher.cpp, Tests/LibRegex/Regex.cpp
Fixes #2622
TODO:
- ~~tests~~
- ?
=> LibRegex: Don't repeat forks

Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOMURL/DOMURL.cpp, Libraries/LibWeb/DOMURL/DOMURL.h, Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp, Libraries/LibWeb/Fetch/Request.cpp, Libraries/LibWeb/Fetch/Response.cpp, Libraries/LibWeb/FileAPI/BlobURLStore.cpp, Libraries/LibWeb/FileAPI/BlobURLStore.h, Libraries/LibWeb/HTML/HTMLLinkElement.cpp, Libraries/LibWeb/HTML/Scripting/Environments.cpp, Libraries/LibWeb/HTML/Scripting/Fetching.cpp, Libraries/LibWeb/HTML/Scripting/ImportMap.cpp, Libraries/LibWeb/HTML/Window.cpp, Libraries/LibWeb/Internals/Internals.cpp, Libraries/LibWeb/ServiceWorker/Job.cpp, Libraries/LibWeb/ServiceWorker/ServiceWorkerContainer.cpp, Libraries/LibWeb/ServiceWorker/ServiceWorkerContainer.h, Libraries/LibWeb/WebSockets/WebSocket.cpp, Libraries/LibWeb/XHR/XMLHttpRequest.cpp, Libraries/LibWebView/SourceHighlighter.cpp
Continuing the effort to remove the awkward validity state of URL::URL
=> LibWeb: Port DOMURL::parse to return an Optional<URL::URL>

Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLElement.h, Libraries/LibWeb/HTML/HTMLElement.idl, Tests/LibWeb/Text/expected/wpt-import/html/editing/the-hidden-attribute/hidden-idl.txt, Tests/LibWeb/Text/input/wpt-import/html/editing/the-hidden-attribute/hidden-idl.html
Follow-ups will implement the actual behaviour.
=> LibWeb: Implement hidden="until-found" IDL support

Libraries/LibWebView/URL.cpp
If Ctrl is pressed when a string is entered into the location bar and that string doesn't contain a valid TLD, ".com" is added to that string.
Previously, only a small, fixed set of TLDs was checked. We now use the public suffix list to determine if the given address contains a valid TLD.
=> LibWebView: Don't add '.com' to valid TLD when Ctrl is pressed

Libraries/LibWeb/CSS/StyleComputer.cpp, Libraries/LibWeb/CSS/StyleComputer.h, Libraries/LibWeb/DOM/Document.cpp
More tricks to keep shaving away at loading times for https://wpt.fyi/
=> More speedups for wpt.fyi

Libraries/LibWeb/CSS/SelectorEngine.cpp, Libraries/LibWeb/CSS/StyleComputer.cpp, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/HTML/HTMLBodyElement.cpp, Libraries/LibWeb/HTML/HTMLFormElement.cpp, Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp, Libraries/LibWeb/HTML/HTMLImageElement.cpp, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLLinkElement.cpp, Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Libraries/LibWeb/HTML/HTMLObjectElement.cpp, Libraries/LibWeb/HTML/HTMLScriptElement.cpp, Libraries/LibWeb/HTML/HTMLTableCellElement.cpp, Libraries/LibWeb/HTML/HTMLTableElement.cpp, Libraries/LibWeb/HTML/HTMLTableRowElement.cpp, Libraries/LibWeb/HTML/HTMLTableSectionElement.cpp, Libraries/LibWeb/HTML/HTMLVideoElement.cpp, Libraries/LibWeb/HTML/NavigableContainer.cpp, Libraries/LibWeb/HTML/Window.cpp, Libraries/LibWeb/Page/EventHandler.cpp, Libraries/LibWeb/SVG/SVGGradientElement.cpp, Libraries/LibWeb/SVG/SVGImageElement.cpp, Libraries/LibWeb/SVG/SVGImageElement.h, Libraries/LibWeb/SVG/SVGScriptElement.cpp, Services/WebContent/ConnectionFromClient.cpp
This ports two more APIs away from URL::is_valid.
=> LibWeb: Port Document encoding_parse_url and parse_url to Optional<URL>

Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
Quick Temporal catchup while I'm sitting at an airport
=> LibJS: Simplify ParseTemporalCalendarString

Libraries/LibCrypto/Curves/SECPxxxr1.h
It may happen that the scalars used by SECPxxxr1 turn out to be slightly smaller than their actual size when serialized to `UnsignedBigInteger`, especially for P521. Handle this case by serializing zeros instead of failing.
Originally discovered as a flaky WPT test (`Text/input/wpt-import/WebCryptoAPI/generateKey/successes_ECDH.https.any.html`) by @gmta.
Context: https://discordapp.com/channels/1247070541085671459/1247090166909374474/1334070624557207594
=> LibCrypto: Always handle `SECPxxxr1` scalars with leading zeros

Libraries/LibWeb/DOM/DOMTokenList.cpp, Libraries/LibWeb/DOM/EventDispatcher.cpp, Libraries/LibWeb/DOM/NamedNodeMap.cpp, Libraries/LibWeb/DOM/Node.cpp
Corresponds to https://github.com/whatwg/dom/pull/1347
=> LibWeb: Initialize clearTargets in event dispatch correctly

Libraries/LibWeb/FileAPI/FileReader.cpp, Libraries/LibWeb/FileAPI/FileReader.h, Tests/LibWeb/Text/expected/wpt-import/FileAPI/reading-data-section/FileReader-multiple-reads.any.txt, Tests/LibWeb/Text/input/wpt-import/FileAPI/reading-data-section/FileReader-multiple-reads.any.html, Tests/LibWeb/Text/input/wpt-import/FileAPI/reading-data-section/FileReader-multiple-reads.any.js
This fixes a timeout for the included WPT test.
=> LibWeb/FileAPI: Implement aborting a FileReader read

Libraries/LibWeb/HTML/HTMLAnchorElement.h, Libraries/LibWeb/HTML/HTMLAreaElement.h, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLElement.h, Libraries/LibWeb/HTML/HTMLFormElement.cpp, Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp, Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.h
Came across these while updating a separate spec change. I don't know when these changes were made.
=> LibWeb/HTML: Bring some URL-related methods up to spec

Libraries/LibWeb/Layout/Node.cpp, Tests/LibWeb/Crash/Layout/style-propagation-for-long-continuation-chain.html
Fixes the extremely slow loading of https://yzy-sply.com.
=> LibWeb: Prevent very slow continuation node style propagation

Libraries/LibWeb/HTML/HTMLSelectElement.cpp, Libraries/LibWeb/HTML/HTMLSelectElement.h, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-closest.txt, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-closest.html
This fixes a regression in https://wpt.live/dom/nodes/Element-closest.html
=> LibWeb: Ensure selected options collection is created prior to access

Libraries/LibWeb/CSS/StyleInvalidationData.cpp, Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/SVG/SVGAElement.cpp
=> Use invalidation sets for more pseudo classes

Libraries/LibWeb/DOM/Element.cpp, Tests/LibWeb/Crash/CSS/link-pseudo-class-invalidation.html
=> LibWeb: Do includes_properties_from_invalidation_set() for :link & co

Documentation/AddNewIDLFile.md
Taken from [this message on Discord](https://discord.com/channels/1247070541085671459/1247090064480014443/1308884324380184699).
=> Meta: Clarify what IDL files need adding to idl_files.cmake

Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/Navigable.h
Corresponds to https://github.com/whatwg/html/commit/304782ca5746f22fa5092e3b21235c06bdb8503d
=> LibWeb: Fix CSP navigation request blocking

Libraries/LibWeb/HTML/FormAssociatedElement.cpp, Libraries/LibWeb/HTML/HTMLButtonElement.cpp
Corresponds to https://github.com/whatwg/html/commit/69110cba0793ccc2f0c0eb1abcbf6a0701221a9c
=> LibWeb/HTML: Update submit-button-related spec text

Libraries/LibWeb/CSS/MediaQueryList.cpp, Libraries/LibWeb/CSS/MediaQueryList.h, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/HTML/NavigableContainer.cpp, Tests/LibWeb/Layout/expected/misc/create-iframes-using-innerhtml.txt, Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/MediaQueryList-change-event-matches-value.txt, Tests/LibWeb/Text/expected/wpt-import/css/mediaqueries/media-query-matches-in-iframe.txt, Tests/LibWeb/Text/input/wpt-import/css/mediaqueries/media-query-matches-in-iframe.html
tl;dr media query lists inside iframes now update and respond to iframe size changes, and more.
=> Some improvements to make media queries responsive to viewport changes

Libraries/LibJS/Runtime/DateConstructor.cpp, Libraries/LibJS/Tests/builtins/Date/Date.parse.js
Courtesy of [vimeo.com](https://vimeo.com/)
=> LibJS: Parse dates like "Jan 15, 2025"

Libraries/LibGfx/SkiaUtils.h
Same as #1328 / 7af940dab3b7153110ed5d8ab1457109604c74cd
Fixes #3539
=> LibGfx: Fix skia include

Services/WebContent/WebDriverConnection.cpp
This was missed in commit 2583996e183f6ce9d47769965b8ae2b25932b93e. WPT recently began testing for this.
This fixes ~450 `/webdriver` (regressed) subtests.
=> WebContent: Annotate unexpected alert open errors for WebDriver

Services/RequestServer/ConnectionFromClient.cpp
curl was omitting headers with empty values from requests. We have to specify these headers with a different syntax in the curl options when we want to send them as empty values.
Fixes 10 of the failing WPT tests here: https://wpt.fyi/results/xhr/setrequestheader-content-type.htm?label=master&product=ladybird
=> RequestServer: Send empty headers in requests

Services/WebDriver/Client.cpp
Fixes `/webdriver/tests/classic/status/status.py`.
=> WebDriver: Correctly report the client's readiness state

Libraries/LibWeb/HTML/FormAssociatedElement.cpp, Libraries/LibWeb/HTML/FormAssociatedElement.h, Libraries/LibWeb/HTML/HTMLButtonElement.idl, Libraries/LibWeb/HTML/HTMLFieldSetElement.idl, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLInputElement.h, Libraries/LibWeb/HTML/HTMLObjectElement.idl, Libraries/LibWeb/HTML/HTMLOutputElement.idl, Libraries/LibWeb/HTML/HTMLSelectElement.idl, Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp, Libraries/LibWeb/HTML/HTMLTextAreaElement.h, Tests/LibWeb/Text/expected/wpt-import/html/semantics/embedded-content/the-object-element/object-setcustomvalidity.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-button-element/button-setcustomvalidity.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/input-setcustomvalidity.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-output-element/output-setcustomvalidity.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-select-element/select-setcustomvalidity.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-textarea-element/textarea-setcustomvalidity.txt, Tests/LibWeb/Text/input/wpt-import/html/semantics/embedded-content/the-object-element/object-setcustomvalidity.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-button-element/button-setcustomvalidity.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/input-setcustomvalidity.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-output-element/output-setcustomvalidity.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-textarea-element/textarea-setcustomvalidity.html
Opening this as a draft for now since I think the WPT tests will require #3583 to be merged first to pass.
=> LibWeb: Implement setCustomValidity IDL attribute

Libraries/LibWeb/EncryptedMediaExtensions/EncryptedMediaExtensions.h, Libraries/LibWeb/EncryptedMediaExtensions/EncryptedMediaExtensions.idl, Libraries/LibWeb/Forward.h, Libraries/LibWeb/HTML/EventLoop/Task.h, Libraries/LibWeb/MediaCapabilitiesAPI/MediaCapabilities.cpp, Libraries/LibWeb/MediaCapabilitiesAPI/MediaCapabilities.h, Libraries/LibWeb/MediaCapabilitiesAPI/MediaCapabilities.idl, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp, Tests/LibWeb/Text/expected/wpt-import/media-capabilities/decodingInfo.any.txt, Tests/LibWeb/Text/input/wpt-import/media-capabilities/decodingInfo.any.html, Tests/LibWeb/Text/input/wpt-import/media-capabilities/decodingInfo.any.js
This is why Youtube videos currently tell us that our browser can't play them.
To be fair, even with this in place, I don't think we can play them yet, since whatever Youtube does next causes ladybird to have a very bad time.
But it's one step closer.
=> LibWeb: Implement MediaCapabilities.decodingInfo()

Libraries/LibCore/MimeData.cpp, Libraries/LibIPC/Decoder.cpp, Libraries/LibURL/URL.cpp, Libraries/LibWeb/Bindings/MainThreadVM.cpp, Libraries/LibWeb/CSS/CSSStyleSheet.cpp, Libraries/LibWeb/HTML/EventSource.cpp, Libraries/LibWeb/HTML/History.cpp, Libraries/LibWeb/HTML/Location.cpp, Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/Navigation.cpp, Libraries/LibWeb/HTML/Scripting/Environments.cpp, Libraries/LibWeb/HTML/Scripting/Environments.h, Libraries/LibWeb/HTML/Scripting/Fetching.cpp, Libraries/LibWeb/HTML/Scripting/ImportMap.cpp, Libraries/LibWeb/HTML/Scripting/Script.cpp, Libraries/LibWeb/HTML/Scripting/Script.h, Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp, Libraries/LibWeb/HTML/Worker.cpp, Libraries/LibWeb/HTML/WorkerGlobalScope.cpp, Libraries/LibWeb/Loader/ProxyMappings.cpp, Libraries/LibWeb/PermissionsPolicy/AutoplayAllowlist.cpp, Libraries/LibWeb/SVG/SVGUseElement.cpp, Libraries/LibWeb/ServiceWorker/ServiceWorkerContainer.cpp, Libraries/LibWeb/WebDriver/Proxy.cpp, Libraries/LibWebView/URL.cpp, Services/RequestServer/ConnectionFromClient.cpp, Services/WebContent/WebDriverConnection.cpp, Tests/LibURL/TestURL.cpp, Tests/LibWeb/TestFetchURL.cpp, Utilities/xml.cpp
Leaving only 14 more callers of `URL::is_valid`
=> LibURL+Everywhere: Further progress towards removal of URL valid state

Libraries/LibWeb/HTML/AttributeNames.h, Libraries/LibWeb/HTML/Canvas/CanvasImageData.idl, Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Libraries/LibWeb/HTML/HTMLButtonElement.cpp, Libraries/LibWeb/HTML/HTMLButtonElement.h, Libraries/LibWeb/HTML/HTMLButtonElement.idl, Libraries/LibWeb/HTML/HTMLDialogElement.cpp, Libraries/LibWeb/HTML/Navigation.cpp, Tests/LibWeb/Text/expected/wpt-import/html/semantics/the-button-element/command-and-commandfor/button-type-reflection.txt, Tests/LibWeb/Text/input/wpt-import/html/semantics/the-button-element/command-and-commandfor/button-type-reflection.html
These are mostly really minor. The only significant one is the HTMLButtonElement change.
=> LibWeb/HTML: Another batch of HTML spec changes

Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/NamedNodeMap.cpp, Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWeb/DOM/Node.h, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/attributes-namednodemap-cross-document.window.txt, Tests/LibWeb/Text/input/wpt-import/dom/nodes/attributes-namednodemap-cross-document.window.html, Tests/LibWeb/Text/input/wpt-import/dom/nodes/attributes-namednodemap-cross-document.window.js
Corresponds to https://github.com/whatwg/dom/commit/b64559cc085fe43791f3f386b5a049993b40ec96
=> LibWeb/DOM: Update an attribute's node document

Libraries/LibWeb/HTML/CrossOrigin/OpenerPolicy.h
Add noopener-allow-popups value to Opener Policy #1690
=> Add noopener-allow-popups value to Opener Policy

Libraries/LibWeb/HTML/HTMLButtonElement.cpp, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/button-type-popovertarget.txt, Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/input-type-popovertarget.txt, Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/button-type-popovertarget.html, Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/input-type-popovertarget.html
This PR implements changes from https://github.com/whatwg/html/pull/11053.
=> LibWeb: Update button/input activation behaviour to match spec

Libraries/LibWeb/HTML/Navigable.cpp, Tests/LibWeb/Assets/blank.html, Tests/LibWeb/Crash/HTML/navigate-navigable-without-active-window.html
Fixes https://github.com/LadybirdBrowser/ladybird/issues/3733
=> LibWeb: Check if navigable has active window before navigating

Libraries/LibWeb/IndexedDB/IDBFactory.cpp
ref. https://github.com/w3c/IndexedDB/pull/441
=> LibWeb/IDB: Update spec comment with latest changes

Libraries/LibURL/Pattern/Pattern.cpp, Libraries/LibURL/Pattern/Pattern.h, Libraries/LibURL/Pattern/PatternError.h, Libraries/LibWeb/URLPattern/URLPattern.cpp, Libraries/LibWeb/URLPattern/URLPattern.h, Libraries/LibWeb/URLPattern/URLPattern.idl
Put the scaffolding in place for compiling the pattern strings.
=> LibWeb+LibURL: Implement remaining IDL for URLPattern

Libraries/LibWeb/HTML/ImageData.cpp, Libraries/LibWeb/HTML/ImageData.h, Libraries/LibWeb/HTML/ImageData.idl
=> LibWeb/HTML: Implement ImageData initialization closer to spec

Libraries/LibWeb/Loader/ContentFilter.cpp, Libraries/LibWeb/Loader/ContentFilter.h, Services/WebContent/ConnectionFromClient.cpp, UI/Qt/BrowserWindow.cpp, UI/Qt/BrowserWindow.h, UI/Qt/Tab.cpp, UI/Qt/Tab.h
=> WebContent+UI/Qt+LibWeb: Add option to toggle content filtering and fix a capitalization error

Libraries/LibDevTools/Actors/WalkerActor.cpp, Libraries/LibDevTools/DevToolsDelegate.h, Libraries/LibWebView/Application.cpp, Libraries/LibWebView/Application.h, Libraries/LibWebView/InspectorClient.cpp, Libraries/LibWebView/ViewImplementation.cpp, Libraries/LibWebView/ViewImplementation.h, Libraries/LibWebView/WebContentClient.cpp, Services/WebContent/ConnectionFromClient.cpp, Services/WebContent/ConnectionFromClient.h, Services/WebContent/WebContentServer.ipc
A couple of low-hanging fruit for DevTools
https://github.com/user-attachments/assets/ea79420a-e7ac-43ca-abcf-9c0a1244460c
=> LibDevTools: Implement editing HTML and moving DOM nodes

Libraries/LibWeb/IndexedDB/IDBFactory.cpp, Libraries/LibWeb/IndexedDB/IDBFactory.h, Libraries/LibWeb/IndexedDB/IDBFactory.idl, Libraries/LibWeb/IndexedDB/Internal/Database.cpp, Libraries/LibWeb/IndexedDB/Internal/Database.h
Fixes 4/5 tests on https://wpt.live/IndexedDB/get-databases.any.html
Possible spec bug for test 5.. https://github.com/w3c/IndexedDB/issues/442
=> LibWeb/IDB: Implement IDBFactory::databases()

Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/Scripting/Environments.cpp, Libraries/LibWeb/HTML/Scripting/Environments.h, Services/WebWorker/DedicatedWorkerHost.cpp
Resolves a small number of FIXMEs in navigables code.
=> LibWeb: Implement environment discarding steps

Libraries/LibWeb/CSS/Default.css, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/HTML/Canvas/CanvasTextDrawingStyles.idl, Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Libraries/LibWeb/HTML/HTMLDialogElement.cpp, Libraries/LibWeb/HTML/HTMLIFrameElement.cpp, Libraries/LibWeb/HTML/HTMLIFrameElement.h, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLOrSVGElement.cpp, Libraries/LibWeb/HTML/Parser/HTMLParser.cpp, Libraries/LibWeb/HTML/Window.cpp
Details are in the individual commits.
=> LibWeb: Some mixed HTML spec updates

Libraries/LibWeb/Layout/FormattingContext.cpp, Libraries/LibWeb/Layout/FormattingContext.h, Libraries/LibWeb/Layout/GridFormattingContext.cpp, Tests/LibWeb/Layout/expected/grid/image-with-percentage-width-and-auto-height.txt, Tests/LibWeb/Layout/expected/grid/item-with-min-content-width.txt, Tests/LibWeb/Layout/expected/inline-flex-with-aspect-ratio.txt, Tests/LibWeb/Layout/input/grid/image-with-percentage-width-and-auto-height.html, Tests/LibWeb/Layout/input/grid/item-with-min-content-width.html
Fixes https://github.com/LadybirdBrowser/ladybird/issues/2276
=> LibWeb: Resolve "height: auto" using preferred aspect ratio if possible

Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Corresponds to https://github.com/w3c/csswg-drafts/commit/9beaea1f2a23d935a28aef8882bfea5519e1cfde
=> LibWeb: Make non-replaced flex items make use of transferred size

Libraries/LibWeb/Layout/GridFormattingContext.cpp, Tests/LibWeb/Layout/expected/grid/clamp-content-based-minimum-size-by-limited-max-track-size.txt, Tests/LibWeb/Layout/input/grid/clamp-content-based-minimum-size-by-limited-max-track-size.html
Progress on https://wpt.live/css/css-grid/grid-items/grid-minimum-size-grid-items-022.html
=> LibWeb: Clamp content-based minimum size by limited max track size [GFC]

Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
Corresponds to https://github.com/w3c/csswg-drafts/commit/f952e97da9fa75a3d283c61febc8173e3926f48e
=> LibWeb/CSS: Allow bare zero for gradient angles

Libraries/LibWeb/HTML/HTMLSourceElement.cpp
Corresponds to https://github.com/whatwg/html/commit/be5f269ca89278bb23801d584ea8ee43bbf6449b
We don't yet implement "moving steps" so that's left for when we do.
=> LibWeb/HTML: Fix source insertion/removal steps

Libraries/LibWeb/CSS/CSSImportRule.cpp, Libraries/LibWeb/CSS/CSSImportRule.h, Libraries/LibWeb/CSS/CSSImportRule.idl, Libraries/LibWeb/CSS/Parser/Parser.cpp, Libraries/LibWeb/CSS/Parser/RuleParsing.cpp, Libraries/LibWeb/CSS/Supports.cpp, Tests/LibWeb/Ref/expected/wpt-import/css/css-cascade/reference/ref-filled-green-100px-square.xht, Tests/LibWeb/Ref/input/wpt-import/css/css-cascade/import-conditional-002.html, Tests/LibWeb/Ref/input/wpt-import/css/css-cascade/support/test-green.css, Tests/LibWeb/Ref/input/wpt-import/css/css-cascade/support/test-red.css, Tests/LibWeb/Text/expected/css/CSSImportRule-supportsText.txt, Tests/LibWeb/Text/input/css/CSSImportRule-supportsText.html
This indicates the features the browser must support for the given stylesheet to be fetched.
=> LibWeb: Implement import at-rule supports conditions

Libraries/LibJS/Bytecode/Executable.h, Libraries/LibJS/Bytecode/Generator.cpp, Libraries/LibJS/Bytecode/Interpreter.cpp, Libraries/LibJS/Forward.h, Libraries/LibJS/Module.cpp, Libraries/LibJS/Module.h, Libraries/LibJS/Runtime/ModuleEnvironment.cpp, Libraries/LibJS/Runtime/ModuleNamespaceObject.cpp, Libraries/LibJS/Tests/builtins/Proxy/iterate-over-proxy.js
Here's a whole bunch of things I worked on while trying to get https://demo.immich.app/ to reasonable performance.
We are still far from reasonable performance.
=> Mixed bag of LibJS optimizations

Libraries/LibJS/Bytecode/ASTCodegen.cpp, Libraries/LibJS/Bytecode/Generator.cpp
See individual commits. Still not fast enough on https://demo.immich.app/ but moving forward.
=> Two more LibJS optimizations

Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Jpegs with YCCK color space were peviously treated as CMYK.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/3873
=> LibGfx: Add support for YCCK jpeg files

Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLObjectElement.cpp, Libraries/LibWeb/Painting/StackingContext.cpp, Libraries/LibWeb/SVG/SVGGraphicsElement.cpp
=> Some work-avoiding patches for layout & painting

Documentation/CSSGeneratedFiles.md, Libraries/LibWeb/Animations/KeyframeEffect.cpp, Libraries/LibWeb/CSS/Parser/Parser.h, Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp, Libraries/LibWeb/CSS/Parser/ValueParsing.cpp, Libraries/LibWeb/CSS/PseudoElements.json, Libraries/LibWeb/CSS/Selector.cpp, Libraries/LibWeb/CSS/Selector.h, Libraries/LibWeb/Dump.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoElement.cpp
cc: @Psychpsyo - Hopefully this is what you need for #4055. Let me know if anything needs changing.
=> LibWeb/CSS: Implement parsing for functional pseudo-elements

Libraries/LibWeb/CSS/Parser/ValueParsing.cpp, Tests/LibWeb/Layout/expected/grid/auto-fit-is-invalid-when-min-and-max-are-both-not-definite.txt, Tests/LibWeb/Layout/input/grid/auto-fit-is-invalid-when-min-and-max-are-both-not-definite.html
...should be treated as invalid value.
=> LibWeb: Repeat grid track sizing with minmax where both are not definite

Libraries/LibWeb/Painting/DisplayList.cpp
=> LibWeb: Change while to for loop

Libraries/LibJS/Bytecode/ASTCodegen.cpp
`!0` and `!1` are very common patterns in minified JavaScript, and we should figure out that they're constants. :^)
=> LibJS: Constant-fold unary expressions

UI/AppKit/Application/ApplicationDelegate.mm
This mirrors the shortcut we have in our Qt UI.
=> UI: Add Cmd+U as a shortcut for "View Source" to AppKit

Libraries/LibJS/Runtime/BigIntObject.h, Libraries/LibJS/Runtime/BooleanObject.h, Libraries/LibJS/Runtime/Date.h, Libraries/LibJS/Runtime/Error.h, Libraries/LibJS/Runtime/NumberObject.h, Libraries/LibJS/Runtime/Object.h, Libraries/LibJS/Runtime/PropertyKey.h, Libraries/LibJS/Runtime/RegExpObject.h, Libraries/LibWeb/CSS/Parser/Helpers.cpp, Libraries/LibWeb/CSS/Parser/Parser.cpp, Libraries/LibWeb/CSS/Parser/Parser.h, Libraries/LibWeb/CSS/StyleComputer.cpp, Libraries/LibWeb/DOM/Element.cpp, Libraries/LibWeb/DOM/Element.h, Libraries/LibWeb/HTML/HTMLInputElement.cpp
Bag of things I made while profiling Speedometer 2.1
=> Some speedy speedups for Speedometer

Libraries/LibWeb/Layout/BlockFormattingContext.h, Libraries/LibWeb/Layout/LineBuilder.cpp
...with a loop through already inserted floating boxes that probes potential insertion points on their edges.
Makes www.nyan.cat go faster.
=> LibWeb: Replace 1px iteration in y_for_float_to_be_inserted_here()

Libraries/LibWebView/ViewImplementation.cpp
Cleans up and fixes #4032
adds a new look to the error page
=> UI: Fix new error page

Libraries/LibWeb/CSS/CSSStyleProperties.cpp, Libraries/LibWeb/CSS/CSSStyleValue.h, Libraries/LibWeb/CSS/Serialize.cpp, Libraries/LibWeb/CSS/Serialize.h, Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp, Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSStyleProperties.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GeneratorUtil.h
These are standalone so here's a small PR.
=> LibWeb: Misc changes in prep for descriptor parsing

Libraries/LibDevTools/Actors/FrameActor.cpp, Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp, Libraries/LibWebView/Application.cpp, Libraries/LibWebView/ConsoleOutput.cpp, Libraries/LibWebView/ConsoleOutput.h, Libraries/LibWebView/ViewImplementation.h, Libraries/LibWebView/WebContentClient.cpp, Libraries/LibWebView/WebContentClient.h, Services/WebContent/DevToolsConsoleClient.cpp, Services/WebContent/PageClient.cpp, Services/WebContent/PageClient.h, Services/WebContent/WebContentClient.ipc
From the following test page:
```html
<script>
function foo() {
console.log("hi");
badreference;
}
function bar() {
foo();
}
function baz() {
bar();
}
baz();
</script>
```
=> LibDevTools+LibWebView+WebContent: Report exceptions to DevTools

Libraries/LibJS/AST.cpp, Libraries/LibJS/AST.h, Libraries/LibJS/Bytecode/Generator.cpp, Libraries/LibJS/Forward.h, Libraries/LibJS/Parser.cpp, Libraries/LibJS/Runtime/AbstractOperations.cpp, Libraries/LibJS/Runtime/AbstractOperations.h, Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp, Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h, Libraries/LibJS/Runtime/FunctionObject.h, Libraries/LibJS/Runtime/Intrinsics.cpp, Libraries/LibJS/Runtime/Intrinsics.h, Libraries/LibJS/Runtime/StringOrSymbol.h, Libraries/LibJS/SourceTextModule.cpp
=> Various things to make JavaScript function instantiation cheaper

Libraries/LibJS/AST.h, Libraries/LibJS/Bytecode/ASTCodegen.cpp, Libraries/LibJS/Bytecode/Generator.cpp, Libraries/LibJS/Bytecode/IdentifierTable.h, Libraries/LibJS/Bytecode/Operand.h, Libraries/LibJS/Parser.cpp, Libraries/LibJS/Parser.h
Continuing to work on Uber Eats performance so we can order more food..
=> More JS optimizations inspired by Uber Eats

Libraries/LibGfx/Font/UnicodeRange.h, Libraries/LibWeb/CMakeLists.txt, Libraries/LibWeb/CSS/CSSStyleValue.cpp, Libraries/LibWeb/CSS/CSSStyleValue.h, Libraries/LibWeb/CSS/Parser/Parser.h, Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp, Libraries/LibWeb/CSS/Parser/Types.cpp, Libraries/LibWeb/CSS/Parser/Types.h, Libraries/LibWeb/CSS/Parser/ValueParsing.cpp, Libraries/LibWeb/CSS/StyleValues/UnicodeRangeStyleValue.cpp, Libraries/LibWeb/CSS/StyleValues/UnicodeRangeStyleValue.h, Libraries/LibWeb/Forward.h
More things that can exist separately.
=> LibWeb+LibGfx: Descriptor-parsing prep part 2

Libraries/LibWeb/HTML/HTMLFontElement.cpp, Tests/LibWeb/Ref/expected/HTML/HTMLFontElement-face-attribute-ref.html, Tests/LibWeb/Ref/input/HTML/HTMLFontElement-face-attribute.html, Tests/LibWeb/Text/expected/Editing/execCommand-fontName.txt
Fixes font selection on https://stagsnet.net/
=> LibWeb: Apply HTMLFontElement's face attribute's presentational hint

Libraries/LibWeb/ContentSecurityPolicy/BlockingAlgorithms.cpp, Libraries/LibWeb/ContentSecurityPolicy/BlockingAlgorithms.h, Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveOperations.cpp, Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveOperations.h, Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/NavigationParams.cpp, Libraries/LibWeb/HTML/NavigationParams.h
Part 6 of splitting up https://github.com/LadybirdBrowser/ladybird/pull/2854
=> LibWeb: Enforce Content Security Policy on navigation request/response

Libraries/LibWeb/HTML/RenderingThread.cpp, Libraries/LibWeb/HTML/RenderingThread.h, Libraries/LibWeb/HTML/TraversableNavigable.cpp, Libraries/LibWeb/HTML/TraversableNavigable.h, Libraries/LibWeb/Painting/DisplayList.cpp, Services/WebContent/PageClient.cpp
=> Couple of minor improvements for display list execution

Libraries/LibGC/Cell.h, Libraries/LibJS/Bytecode/Builtins.h, Libraries/LibJS/Bytecode/Interpreter.cpp, Libraries/LibJS/Bytecode/Op.h, Libraries/LibJS/Runtime/MathObject.cpp, Libraries/LibJS/Runtime/MathObject.h
Just some obvious things. Very noisy but looks like ~1% on my machine.
=> Handful of little LibJS optimizations from looking at JetStream

.github/actions/setup/action.yml, Meta/CMake/vcpkg/generate_vcpkg_toolchain_variables.cmake, Toolchain/BuildVcpkg.py, vcpkg.json
Revert a bunch of "temporary" workarounds while we're at it.
=> Meta: Update vcpkg to hopefully fix cmake 4.x issues

Libraries/LibWeb/Layout/GridFormattingContext.cpp, Libraries/LibWeb/Layout/GridFormattingContext.h, Tests/LibWeb/Layout/expected/grid/line-based-placement-named-lines-with-span-negative.txt, Tests/LibWeb/Layout/expected/grid/line-based-placement-named-lines-with-span.txt, Tests/LibWeb/Layout/expected/grid/line-based-with-repeat.txt, Tests/LibWeb/Layout/input/grid/line-based-placement-named-lines-with-span-negative.html, Tests/LibWeb/Layout/input/grid/line-based-placement-named-lines-with-span.html, Tests/LibWeb/Layout/input/grid/line-based-with-repeat.html
Relates to the first two issues of #3795
=> LibWeb: Fix grid placement with named lines

AK/Find.h, Base/res/ladybird/about-pages/settings.html, Libraries/LibWeb/WebDriver/Actions.cpp, Libraries/LibWebView/Autocomplete.cpp, Libraries/LibWebView/SearchEngine.cpp, Libraries/LibWebView/SearchEngine.h, Libraries/LibWebView/Settings.cpp, Libraries/LibWebView/Settings.h, Libraries/LibWebView/URL.cpp, Libraries/LibWebView/URL.h, Libraries/LibWebView/WebUI/SettingsUI.cpp, Libraries/LibWebView/WebUI/SettingsUI.h, Tests/AK/TestFind.cpp, Tests/LibWebView/TestWebViewURL.cpp, UI/AppKit/Interface/LadybirdWebView.mm, UI/AppKit/Interface/TabController.mm, UI/Qt/LocationEdit.cpp, UI/Qt/Tab.cpp
https://github.com/user-attachments/assets/89d08c5c-b307-4227-a6e1-d8eb62750e24
=> LibWebView: Support custom search engines

Libraries/LibRegex/RegexByteCode.cpp, Libraries/LibRegex/RegexByteCode.h, Libraries/LibRegex/RegexDebug.h, Libraries/LibRegex/RegexOptimizer.cpp, Tests/LibRegex/Regex.cpp
What's that? monthly regex bugfix subscription? whoa!
=> LibRegex: Fix a couple more boogs

AK/FlyString.h, AK/String.h, AK/Utf16View.h, Libraries/LibJS/Runtime/FunctionObject.cpp, Libraries/LibJS/Runtime/FunctionObject.h, Libraries/LibJS/Runtime/Intrinsics.cpp, Libraries/LibJS/Runtime/Intrinsics.h, Libraries/LibJS/Runtime/NativeFunction.cpp, Libraries/LibJS/Runtime/NativeFunction.h, Libraries/LibJS/Runtime/Object.cpp
Just continuing to grind away things from the Speedometer 2.1 profile.
=> More LibJS/AK things for Speedometer 2.1

Libraries/LibJS/AST.cpp, Libraries/LibJS/Bytecode/Interpreter.cpp, Libraries/LibJS/Runtime/BoundFunction.cpp, Libraries/LibJS/Runtime/BoundFunction.h, Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h, Libraries/LibJS/Runtime/FunctionObject.h, Libraries/LibJS/Runtime/FunctionPrototype.h, Libraries/LibJS/Runtime/NativeFunction.h, Libraries/LibJS/Runtime/ProxyObject.cpp, Libraries/LibJS/Runtime/ProxyObject.h, Libraries/LibJS/Runtime/WrappedFunction.h, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/DOM/ShadowRoot.h
=> Two little optimizations for Speedometer 2.1

Libraries/LibWeb/DOM/DocumentLoading.cpp, Libraries/LibWeb/DOM/Element.cpp, Libraries/LibWeb/HTML/Dates.cpp, Libraries/LibWeb/HTML/EventSource.cpp, Libraries/LibWeb/HTML/HTMLLinkElement.cpp, Libraries/LibWeb/HTML/HTMLMediaElement.cpp, Libraries/LibWeb/HTML/Parser/HTMLEncodingDetection.cpp, Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp, Libraries/LibWeb/HTML/Scripting/Fetching.cpp, Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp, Libraries/LibWeb/Page/DragAndDropEventHandler.cpp
Corresponds to https://github.com/whatwg/html/commit/285a58bf30eed08a5dd10f74a7d217fc59431999
=> LibWeb: Correct some spec typos

Libraries/LibWeb/CSS/Default.css, Libraries/LibWeb/CSS/PseudoElements.json, Libraries/LibWeb/HTML/HTMLInputElement.cpp, Libraries/LibWeb/HTML/HTMLMeterElement.cpp, Libraries/LibWeb/HTML/HTMLProgressElement.cpp
Corresponds to https://github.com/w3c/csswg-drafts/commit/9549bb8951dc46e3a4a09b79c117966eb1687c13
=> LibWeb: Add slider- prefix to slider pseudo-element names

Libraries/LibJS/Runtime/Array.h, Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp, Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h, Libraries/LibJS/Runtime/Object.h, Libraries/LibJS/Runtime/PrimitiveString.cpp, Libraries/LibJS/Runtime/PrimitiveString.h, Libraries/LibJS/Runtime/VM.cpp, Libraries/LibJS/Runtime/Value.cpp
=> Pack of small LibJS things for Speedometer 2.1

Libraries/LibGfx/PaintingSurface.cpp
With this change we ensure that Skia surfaces are allowed to be created or destroyed only by one thread at a time. Not enforcing this before resulted in "Single owner failure." assertion crashes in debug mode on pages with canvas elements.
=> LibGfx: Make Skia surface construction/destruction thread-safe

Libraries/LibJS/Runtime/AbstractOperations.cpp, Libraries/LibJS/Runtime/Intrinsics.cpp, Libraries/LibJS/Runtime/Intrinsics.h, Libraries/LibJS/Runtime/ObjectPrototype.cpp, Libraries/LibJS/Runtime/VM.cpp, Libraries/LibJS/Runtime/VM.h, Libraries/LibJS/Runtime/Value.cpp
=> Two LibJS optimizations for Speedometer2.1/EmberJS-Debug-TodoMVC

Libraries/LibWeb/XHR/ProgressEvent.h, Libraries/LibWeb/XHR/ProgressEvent.idl, Libraries/LibWeb/XHR/XMLHttpRequest.cpp, Tests/LibWeb/Text/expected/wpt-import/xhr/progressevent-constructor.txt, Tests/LibWeb/Text/input/wpt-import/xhr/progressevent-constructor.html
Minor improvements to follow spec more closely.
=> LibWeb XHR improvements

Documentation/FAQ.md
See https://github.com/LadybirdBrowser/ladybird/issues/3846#issuecomment-2706906572. I don’t feel strongly about whether this merits inclusion in the FAQ, but it came up on Discord today — and seems to come up often enough — that maybe it’s worth having something specific for it in the FAQ.
Just cribbed the answer from https://github.com/LadybirdBrowser/ladybird/issues/3846#issuecomment-2706906572.
=> FAQ: Add question and answer about ad blocker

Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/DOM/Document.idl, Libraries/LibWeb/HTML/HTMLOrSVGElement.cpp, Libraries/LibWeb/HTML/HTMLOrSVGElement.h, Libraries/LibWeb/HTML/History.cpp, Libraries/LibWeb/HTML/History.h, Libraries/LibWeb/HTML/Navigation.cpp, Libraries/LibWeb/HTML/Window.cpp
=> LibWeb: HTML spec updates

Libraries/LibGfx/TextLayout.cpp, Libraries/LibJS/Runtime/AbstractOperations.cpp, Libraries/LibJS/Runtime/ArgumentsObject.cpp, Libraries/LibJS/Runtime/Intrinsics.cpp, Libraries/LibJS/Runtime/Intrinsics.h, Libraries/LibWeb/CSS/StyleSheetList.cpp, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/Layout/BlockFormattingContext.cpp, Libraries/LibWeb/Layout/Node.cpp, Libraries/LibWeb/Layout/Node.h
See individual commits. Nothing mind-blowing, just grinding away at all the small things in the profile.
=> Another bag of Speedometer improvements

Libraries/LibWeb/ServiceWorker/Job.cpp, Libraries/LibWeb/ServiceWorker/Registration.h, Libraries/LibWeb/ServiceWorker/ServiceWorkerRecord.h
A very minor amount of progress towards ServiceWorker support
=> LibWeb/ServiceWorker: Add some more plumbing for ServiceWorker update algorithm

Libraries/LibWeb/DOM/Element.cpp, Libraries/LibWeb/HTML/Window.cpp, Libraries/LibWeb/Layout/FlexFormattingContext.cpp, Libraries/LibWeb/Painting/PaintableBox.cpp, Libraries/LibWeb/Painting/PaintableBox.h
Turns out we were doing more layout work than necessary! See individual commits.
=> More layout work avoidance for Speedometer

Base/res/ladybird/about-pages/settings.html, Libraries/LibWebView/Application.cpp, Libraries/LibWebView/Application.h, Libraries/LibWebView/HelperProcess.cpp, Libraries/LibWebView/Options.h, Libraries/LibWebView/Settings.cpp, Libraries/LibWebView/Settings.h, Libraries/LibWebView/WebUI/SettingsUI.cpp, Libraries/LibWebView/WebUI/SettingsUI.h, Services/RequestServer/ConnectionFromClient.cpp, Services/RequestServer/ConnectionFromClient.h, Services/RequestServer/RequestServer.ipc
TLDR: ![image](https://github.com/user-attachments/assets/073fa588-e73f-4628-b98c-4e04fd7c1671)
=> LibWebView+RequestServer: Add some UI for DNS settings

Libraries/LibWeb/HTML/Location.cpp, Libraries/LibWeb/HTML/Location.h, Tests/LibWeb/Text/expected/wpt-import/html/browsers/history/the-location-interface/location_hash_set_empty_string.txt, Tests/LibWeb/Text/input/wpt-import/html/browsers/history/the-location-interface/location_hash_set_empty_string.html
Along with an update to spec comments & WPT test import for an open PR to the HTML spec & WPT.
=> LibWeb/HTML: Implement more of the Location interface

Libraries/LibWeb/IndexedDB/IDBFactory.cpp, Libraries/LibWeb/IndexedDB/Internal/Algorithms.cpp
Addresses the changes in https://github.com/w3c/IndexedDB/pull/447 and https://github.com/w3c/IndexedDB/pull/448
=> LibWeb/IDB: Small editorial changes

Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp, Tests/LibWeb/Text/expected/wpt-import/css/css-values/minmax-length-invalid.txt, Tests/LibWeb/Text/input/wpt-import/css/css-values/minmax-length-invalid.html
=> LibWeb: Don't assume calc() simplification worked on invalid tree

Libraries/LibJS/Parser.cpp
Previously we blocked using locals for function arguments whenever `arguments` was mentioned in function body, however, this is not necessary in strict mode, where mutations to the arguments object are not reflected in the function arguments and vice versa.
=> LibJS: Allow using locals if `arguments` is used in strict mode

Libraries/LibJS/Bytecode/ASTCodegen.cpp, Libraries/LibJS/Bytecode/Register.h
=> Two tiny LibJS things I had lying around

Libraries/LibJS/Bytecode/Interpreter.cpp, Libraries/LibJS/Runtime/NumberPrototype.cpp, Libraries/LibJS/Runtime/Object.cpp, Libraries/LibJS/Runtime/ProxyObject.cpp
See commits. 1.23x + 1.19x speedup on MicroBench/for-in-indexed-properties.js
=> Two LibJS speedups for for..in iteration

Libraries/LibJS/Bytecode/Interpreter.cpp
Even though this code was already optimized to re-use a single result object, returning { value, done } directly in output parameters still provides a substantial speedup.
1.21x speedup on MicroBench/for-in-indexed-properties.js
=> LibJS: Teach for..in iterator to use IteratorNextUnpack optimization

Libraries/LibJS/Bytecode/Interpreter.cpp
We were spending a lot of time removing each property name from the iterator's underlying HashMap while iterating over it. This wasn't actually necessary, so let's stop doing it and instead just iterate over the property names with a stored HashTable iterator.
1.10x speedup on MicroBench/for-in-indexed-properties.js
=> LibJS: Don't incrementally delete PropertyNameIterator while iterating

Documentation/EditorConfiguration/CLionConfiguration.md, Documentation/EditorConfiguration/VSCodeConfiguration.md
- Update debug description for debugging on Linux with VSCode
- Update build paths in documentation
=> Documentation: Update VSCodeConfiguration.md

Libraries/LibWeb/CSS/Fetch.cpp
Similar to other ad-hoc behavior in this method, we need to handle requests which are not associated with a style sheet. For example:
```html
<script>
const element = document.createElement('div');
element.style['background'] = 'url(https://foo.com/img.png)';
document.body.appendChild(element);
</script>
```
Will not be associated with a style sheet.
This is needed to ensure we fire a `PerformanceResourceTiming` event for this resource load. This is not currently testable in CI, as this event is also gated by HTTP/S requests.
This fixes the first subtest of https://wpt.fyi/results/css/fetching/fetch-resources.sub.html?label=master&label=experimental&product=ladybird&aligned. We then time out on the second subtest because we don't yet implement `shape-outside`, thus don't fetch the URL …
=> LibWeb: Set the initiator type for script-initiated CSS requests

UI/Qt/BrowserWindow.cpp
=> UI/Qt: Add Ctrl-R shortcut for page Reload

Meta/WPT.sh, Meta/watch_wpt_progress.sh
This is the "intended" way of parallelism with wpt, but instead of requiring N different systems (or VMs), this does it all on one system with the power of namespaces.
(Behaviour on systems that do not support network namespaces should be the same as it was before)
=> Meta: Make WPT.sh run nproc/2 testrunners in parallel

Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/TraversableNavigable.h
Corresponds to https://github.com/whatwg/html/commit/d7fc63a84acbaff464ed40353f14d4ee010c8749
=> LibWeb/HTML: Update "is script closable" to current spec

UI/AppKit/Interface/LadybirdWebView.mm, UI/AppKit/Interface/TabController.mm
See individual commits for information.
=> UI/AppKit: Two small macOS chrome fixes

Meta/WPT.sh
This restores the behaviour from before adding parallel instance support.
cc @gmta, thanks for boog report :)
=> Meta: Make WPT.sh log args relative to cwd as of script invocation

AK/Error.cpp, AK/Error.h, AK/Hex.cpp, AK/MemoryStream.cpp, AK/MemoryStream.h, AK/Stream.cpp, AK/StringView.h, Libraries/LibCore/Directory.cpp, Libraries/LibCore/LocalServer.cpp, Libraries/LibCore/Process.cpp, Libraries/LibCore/System.cpp, Libraries/LibCore/SystemWindows.cpp, Libraries/LibFileSystem/FileSystem.cpp, Libraries/LibIPC/TransportSocket.cpp, Tests/LibCore/TestLibCoreStream.cpp
Mostly clean up of artifacts from SerenityOS that don't make much sense in Ladybird.
=> AK: Some error cleanup

.devcontainer/devcontainer.json, .devcontainer/features/ladybird/devcontainer-feature.json, .github/actions/setup/action.yml, .github/workflows/js-benchmarks.yml, .github/workflows/libjs-test262.yml
=> CI: Manually add apt repo for llvm 20 to all relevant jobs

Libraries/LibWeb/IndexedDB/IDBFactory.cpp, Libraries/LibWeb/IndexedDB/Internal/Algorithms.cpp, Libraries/LibWeb/IndexedDB/Internal/Algorithms.h
Corresponds to https://github.com/w3c/IndexedDB/pull/456 and https://github.com/w3c/IndexedDB/pull/457
=> LibWeb/IDB: Spec updates

Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp, Libraries/LibWeb/CSS/Selector.cpp, Libraries/LibWeb/CSS/Selector.h, Libraries/LibWeb/CSS/SelectorEngine.cpp, Libraries/LibWeb/Dump.cpp, Tests/LibWeb/Text/expected/css/parse-dir-selector.txt, Tests/LibWeb/Text/expected/wpt-import/css/selectors/dir-selector-querySelector.txt, Tests/LibWeb/Text/expected/wpt-import/css/selectors/parsing/parse-has.txt, Tests/LibWeb/Text/expected/wpt-import/css/selectors/parsing/parse-is-where.txt, Tests/LibWeb/Text/expected/wpt-import/css/selectors/parsing/parse-not.txt, Tests/LibWeb/Text/input/css/parse-dir-selector.html, Tests/LibWeb/Text/input/wpt-import/css/selectors/parsing/parse-has.html, Tests/LibWeb/Text/input/wpt-import/css/selectors/parsing/parse-is-where.html, Tests/LibWeb/Text/input/wpt-import/css/selectors/parsing/parse-not.html
Gets us 32 WPT passes, though a few of those are from a test I've submitted to WPT that isn't merged yet. :sweat_smile:
=> LibWeb/CSS: Fix some pseudo-class selector-parsing/serialization bugs

AK/Utf16View.cpp, AK/Utf16View.h, Libraries/LibJS/Runtime/Value.cpp, Libraries/LibJS/Tests/builtins/String/String.js, Libraries/LibWeb/Infra/Strings.cpp
Instead of code points.
No change to test262
=> LibJS: Implement 'less than' for a String over code units

AK/Function.h
Previously, heap-allocated `CallableWrapper` objects were destroyed in a very roundabout way: `AK::Function` would call a virtual `destroy()` method, which then invoked delete manually. This was unnecessary, since `CallableWrapper` already has a virtual destructor — deleting it through a `CallableWrapperBase*` correctly calls the closure's destructor.
This fixes GCC `-Wfree-nonheap-object` false positive warnings (#4721) and coincidentally removes 8 KB of vtable entries (and the corresponding relative relocations) from LibJS.
=> AK: Replace `CallableWrapper::destroy()` with a destructor

Libraries/LibWeb/Editing/Internal/Algorithms.cpp
We have implemented all commands in the editing spec that potentially reference one another, so we can now rely on the fact that any command that gets passed to these methods has a definition. User-provided commands still get checked by means of `queryCommandSupported()` and friends.
No functional changes.
=> LibWeb: Resolve editing FIXMEs related to unimplemented commands

Libraries/LibWeb/HTML/HTMLButtonElement.cpp, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
See individual commit descriptions.
=> A few tiny spec updates

.github/workflows/lint-code.yml, .ycm_extra_conf.py, Libraries/LibGfx/TIFFGenerator.py, Meta/check-html-doctype.py, Meta/check-idl-files.py, Meta/check-newlines-at-eof.py, Meta/check-style.py, Meta/embed_as_string.py, Meta/generate-libwasm-spec-test.py, Meta/generate_clang_module_map.py, Meta/gn/build/download_file.py, Meta/gn/build/extract_archive_contents.py, Meta/gn/build/install_vcpkg.py, Meta/gn/build/run_compiled_binary.py, Meta/gn/build/write_cmake_config.py, Meta/import-wpt-test.py, Meta/lint-python.sh, Tests/ClangPlugins/lit.cfg.py, Tests/LibWeb/add_libweb_test.py, Toolchain/BuildVcpkg.py, pyproject.toml
I did this as 2 commits to make it easier to review, like we typically do with clang-format updates - the first commit is the switch to black, the second commit runs the formatter.
=> Meta: Lint python files with black

Libraries/LibJS/Bytecode/ASTCodegen.cpp, Libraries/LibJS/Bytecode/Generator.cpp, Libraries/LibJS/Bytecode/Generator.h, Libraries/LibJS/Bytecode/Interpreter.cpp, Libraries/LibJS/Bytecode/Op.h, Libraries/LibJS/Runtime/NativeFunction.cpp, Libraries/LibJS/Runtime/VM.cpp, Libraries/LibJS/Runtime/VM.h
A small bag of changes that I've accumulated poking around the interpreter.
=> LibJS: Miscellaneous interpreter tweaks

Libraries/LibWeb/DOM/Element.cpp, Libraries/LibWeb/DOM/Element.h, Libraries/LibWeb/HTML/AttributeNames.h, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLElement.h, Libraries/LibWeb/HTML/HTMLElement.idl, Tests/LibWeb/Text/expected/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-007.txt, Tests/LibWeb/Text/expected/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-008.txt, Tests/LibWeb/Text/expected/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-009.txt, Tests/LibWeb/Text/expected/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-010.txt, Tests/LibWeb/Text/expected/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-011.txt, Tests/LibWeb/Text/expected/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-012.txt, Tests/LibWeb/Text/expected/wpt-import/html/dom/elements/global-attributes/translate-enumerated-ascii-case-insensitive.txt, Tests/LibWeb/Text/expected/wpt-import/html/dom/elements/global-attributes/translate-inherit-no-parent-element.txt, Tests/LibWeb/Text/expected/wpt-import/html/dom/elements/global-attributes/translate-non-html-translation-mode.txt, Tests/LibWeb/Text/input/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-007.html, Tests/LibWeb/Text/input/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-008.html, Tests/LibWeb/Text/input/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-009.html, Tests/LibWeb/Text/input/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-010.html, Tests/LibWeb/Text/input/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-011.html, Tests/LibWeb/Text/input/wpt-import/html/dom/elements/global-attributes/the-translate-attribute-012.html, Tests/LibWeb/Text/input/wpt-import/html/dom/elements/global-attributes/translate-enumerated-ascii-case-insensitive.html, Tests/LibWeb/Text/input/wpt-import/html/dom/elements/global-attributes/translate-inherit-no-parent-element.html, Tests/LibWeb/Text/input/wpt-import/html/dom/elements/global-attributes/translate-non-html-translation-mode.html
Gains us 15 more WPT subtest passes: https://wpt.fyi/results/html/dom/elements/global-attributes/
=> LibWeb: Implement the translate attribute

vcpkg.json
I was actually looking to update simdutf to 7.1.0, but ran into a bug upstream that caused new failures (I've opened an issue for simdutf for this). In the meantime, we haven't updated many of our packages in a while, so I've included everything *except* simdutf here.
=> Meta: vcpkg updates

Libraries/LibCore/SharedCircularQueue.h
This fixes two race conditions and ASAN crashes in the test for the same.
The first comes from destroying the internals struct, which was previously using the standard, thread-unsafe RefCounted CRTP. The second is from destroying the name, which is secretly another RefCounted object, in a thread-unsafe manner.
=> LibCore: Atomically ref-count SharedSingleProducerCircularQueue guts

Services/RequestServer/ConnectionFromClient.cpp
...to become writable.
Solves triangular deadlock problem that happened in the following case (copied from https://github.com/LadybirdBrowser/ladybird/issues/1816):
- The WebContent process is spinning on `send_sync_but_allow_failure` waiting for the UI process to respond
- The UI process is spinning on `send_sync_but_allow_failure`, waiting for RequestServer to respond
- RequestServer is stuck in this loop, trying to write to the WebContent's socket file (when I attach to RS, we are always in the sched_yield call, so we're spinning on EAGAIN).
For me the issue was reliably reproducible on Google Maps and with this change we no longer deadlock there.
=> RequestServer: Use write notifier instead of busy waiting for socket

Libraries/LibWeb/WebGL/OpenGLContext.cpp, Libraries/LibWeb/WebGL/WebGLProgram.h
Couple useful commits from https://github.com/LadybirdBrowser/ladybird/pull/4056 that could be merged independently
=> LibWeb/WebGL: Useful changes from angle-metal branch

Libraries/LibJS/Bytecode/Builtins.h, Libraries/LibJS/Bytecode/Interpreter.cpp, Libraries/LibJS/Runtime/MathObject.cpp, Libraries/LibJS/Runtime/MathObject.h
Improves performance on https://pierre.co/
=> LibJS: Use CallBuiltin for trigonometric functions

Meta/ladybird.py
This affords us some API symmetry with ladybird.sh.
=> Meta: Change the ladybird.py target to be a positional argument

Libraries/LibWeb/HTML/CrossOrigin/Reporting.cpp, Libraries/LibWeb/HTML/CrossOrigin/Reporting.h, Libraries/LibWeb/HTML/Window.cpp, Libraries/LibWeb/HTML/WindowProxy.cpp
Let's avoid some verification failures I hit while browsing around on the web.
=> Two little stability fixes

UI/Headless/Application.cpp
Especially on new setups, it is handy for `headless-browser --run-tests` to "just work". Anyone using `ladybird.py` will have `LADYBIRD_SOURCE_DIR` set in their environment already.
=> headless-browser: Allow running LibWeb tests without specifying a path

Tests/CMakeLists.txt, Tests/LibURL/TestURL.cpp
=> Tests/LibURL: Port to Windows

Services/RequestServer/ConnectionFromClient.cpp
Without these fixes, RequestServer was likely to crash if the client crashed (e.g. WebContent). This was because there was no error handling for when writing to the client failed.
This is particularly an issue because RequestServer has shared instances, so it would then crash every other client of RequestServer. Then, because another RequestServer instance is not currently spun up, it becomes impossible to start any clients that need a RequestServer instance. Recreating a RequestServer should also be handled, but that's not in the scope of this change.
We can tell curl that we failed to write data to the client and that the request should be aborted by returning `CURL_WRITEFUNC_ERROR` from the write callback.
It is also possible for requests to be destroyed with buffered data, which is …
=> RequestServer: Handle client disappearance more gracefully

Libraries/LibWeb/CSS/GridTrackSize.cpp, Libraries/LibWeb/CSS/GridTrackSize.h, Libraries/LibWeb/Layout/GridFormattingContext.cpp
=> LibWeb: Use variant to represent CSS::ExplicitGridTrack

Libraries/LibCore/AnonymousBuffer.cpp, Libraries/LibCore/AnonymousBuffer.h, Libraries/LibCore/DateTime.h, Libraries/LibCore/File.h, Libraries/LibCore/Forward.h, Libraries/LibCore/MappedFile.cpp, Libraries/LibCore/Proxy.h, Libraries/LibIPC/Decoder.h, Libraries/LibIPC/Encoder.h, Libraries/LibIPC/File.h
=> Remove dependencies on LibIPC from LibCore

Libraries/LibGfx/ColorSpace.cpp
Fixes #4968.
Fixes color rendering for PNG images using ICC v2 profiles with CIE Lightness curves.
Previously `SkColorSpace::Make` was returning `null` when trying to create a color space from this profile. Now, we use `skcms_ApproximateCurve`, which approximates table based curves. We only use it when SkColorSpace::Make fails, so all other cases remain unaffected.
I'm not sure how to add a test for this though.  It's possible to verify the fix by visiting [url](https://svgees.us/PNG/iCCP/tests/iCCP-v2-CIE-Lstar.html) from the issue, but I can't test it in TestImageDecoder since we only have a bitmap with raw pixel values there.
=> LibGfx: Fix incorrect colors in PNG images with CIE L* ICC profiles

Libraries/LibCore/EventLoopImplementationUnix.cpp, Libraries/LibCore/File.cpp, Libraries/LibGfx/ImageFormats/TIFFLoader.cpp, Libraries/LibJS/Parser.cpp, Libraries/LibJS/Runtime/Completion.cpp, Libraries/LibJS/Runtime/Date.cpp, Libraries/LibJS/SourceCode.cpp, Libraries/LibJS/Tests/builtins/AsyncGenerator/AsyncGenerator.prototype.next.js, Libraries/LibJS/Tests/using-declaration.js, Libraries/LibMedia/FFmpeg/FFmpegVideoDecoder.cpp, Libraries/LibUnicode/DateTimeFormat.cpp, Libraries/LibWasm/Parser/Parser.cpp
This is my last PR of this kind.
Please consider using https://github.com/crate-ci/typos
=> Everywhere: Fix typos - act III

Libraries/LibWeb/CSS/Parser/Parser.cpp, Libraries/LibWeb/CSS/Parser/RuleParsing.cpp, Libraries/LibWeb/CSS/Parser/Types.h, Tests/LibWeb/Ref/expected/wpt-import/css/css-namespaces/reference/ref-lime-5.xml, Tests/LibWeb/Ref/input/wpt-import/css/css-namespaces/syntax-013.xml, Tests/LibWeb/Text/expected/css/CSSRule-type.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-cascade/parsing/layer.txt, Tests/LibWeb/Text/input/wpt-import/css/css-cascade/parsing/layer.html
Fixes at least 10 WPT subtests
=> LibWeb: Distinguish between empty block at-rules and statement at-rules

Libraries/LibWeb/CSS/Interpolation.cpp, Libraries/LibWeb/CSS/Parser/ValueParsing.cpp, Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h, Libraries/LibWeb/DOM/Node.cpp, Libraries/LibWeb/DOM/Node.h, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLElement.h, Libraries/LibWeb/HTML/HTMLElement.idl
The HTMLElement changes are the only interesting ones.
=> LibWeb: Some (mostly CSS) spec changes

AK/Format.h, Tests/AK/TestFormat.cpp
This was missing and I wanted it for some debugging, so now it exists.
=> AK: Add a Formatter for Checked

Libraries/LibCore/SocketWindows.cpp
CancelIo introduces a race condition: if data arrives between calls to WSARecv and CancelIo it will be lost.
See also: https://vstinner.github.io/asyncio-proactor-wsarecv-cancellation-data-loss.html
=> LibCore: Fix race condition in PosixSocketHelper::read on Windows

AK/CMakeLists.txt, AK/Demangle.h, AK/DemangleWindows.cpp, Tests/AK/CMakeLists.txt, Tests/AK/TestDelayLoadWindows.cpp, Tests/AK/TestDemangle.cpp
This implements demangle() using Windows API. Also some rudimentary test is provided.
=> AK: Resolve FIXME in Windows implementation of demangle()

Libraries/LibWeb/HTML/HTMLElement.cpp
Spec PR: https://github.com/whatwg/html/pull/11253
=> LibWeb: Remove some popover AD-HOC comments

Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp, Tests/LibWeb/Text/expected/wpt-import/css/css-easing/linear-timing-functions-output.txt, Tests/LibWeb/Text/input/wpt-import/css/css-easing/linear-timing-functions-output.html, Tests/LibWeb/Text/input/wpt-import/css/css-easing/testcommon.js
=> LibWeb/CSS: Fix reference bug when canonicalizing linear easing stops

Tests/LibWeb/Text/input/selection-over-multiple-code-units.html
Draft while I relentlessly hammer CI to see if the flakiness disappears.
=> Tests: Force layout in test to prevent flakiness

Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp, Libraries/LibWeb/HTML/Scripting/Environments.cpp, Libraries/LibWeb/HTML/Scripting/Environments.h
Fixes: https://github.com/LadybirdBrowser/ladybird/issues/4652 (I hope!)
=> LibWeb/HTML: Iterate safely in perform_a_microtask_checkpoint() 

.github/actions/cache-restore/action.yml, .github/actions/cache-save/action.yml
These got removed by accident.
=> CI: Restore cache action checks on `inputs.ccache_path`

vcpkg.json
Fixes dav1d fetch error when building Ladybird.
=> Meta: Update vcpkg to latest master

Libraries/LibWeb/HTML/HTMLElement.cpp
When expanding "required line breaks", we now write directly into the final StringBuilder instead of doing a pass of Vector remove/insert operations first.
This removes a hot profile item on https://serpapi.com/
=> LibWeb: Avoid expensive Vector::insert() in innerText & outerText

Libraries/LibWeb/CSS/Parser/Parser.cpp, Tests/LibWeb/Ref/expected/wpt-import/css/css-conditional/at-supports-038.html, Tests/LibWeb/Ref/expected/wpt-import/css/css-conditional/at-supports-039.html, Tests/LibWeb/Ref/input/wpt-import/css/css-conditional/at-supports-038.html, Tests/LibWeb/Ref/input/wpt-import/css/css-conditional/at-supports-039.html
Gains us a couple more WPT tests.
=> LibWeb: Disallow trailing tokens in @supports(<declaration>)

Tests/LibWeb/Text/expected/wpt-import/wasm/jsapi/global/constructor.any.txt, Tests/LibWeb/Text/input/wpt-import/resources/testharness.js
This ensures that our test output looks the same as that shown in the WPT runner.
In reality, this only affected the output of 1 test that we currently import.
=> Tests: Update WPT `testharness.js` to the most recent version

Meta/check-html-doctype.py
No more making layout tests without doctypes.
=> Meta: Enforce doctypes on layout tests

Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/offsetParent_element_test.txt, Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/scrollParent-shadow-tree.txt, Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/scrollParent.txt, Tests/LibWeb/Text/input/wpt-import/css/cssom-view/offsetParent_element_test.html, Tests/LibWeb/Text/input/wpt-import/css/cssom-view/scrollParent-shadow-tree.html, Tests/LibWeb/Text/input/wpt-import/css/cssom-view/scrollParent.html
These didn't exist when #5113 was merged, but now they do. Our pass rate isn't great but there are several FIXMEs which could be to blame.
=> Tests: Import tests for scrollParent() and offsetParent()

Libraries/LibRegex/RegexByteCode.h, Libraries/LibRegex/RegexMatcher.cpp, Libraries/LibRegex/RegexOptimizer.cpp
=> LibRegex: Some fixes

Libraries/LibWeb/CSS/Parser/Parser.h, Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-shorthand-serialization.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-shorthand.txt
=> LibWeb: Set grid-auto-* to initial values when parsing `grid-template`

Libraries/LibCore/Promise.h, Libraries/LibDNS/Resolver.h, Utilities/dns.cpp
=> DNS: no more weird questions

Libraries/LibWeb/Painting/ShadowPainting.cpp
~text-shadow was being offset to the left by a margin derived from both sides of blur radius instead of just the left side.~
Was not an issue with the margin being wrong, but rather appeared that way on my computer, having a high DPI screen. Now, this should fix the bug which appears when zoomed.
Ive added a FIXME as while the behaviour is improved and seems perfect for integer value scales, there are still sometimes small incorrect offsets.
Correct:
Before:
After:
Slight error mentioned:
=> LibWeb: Fix text-shadow position being incorrectly scaled with non 100% zoom or high DPI monitors

Documentation/DevTools.md, Libraries/LibDevTools/Actors/PageStyleActor.cpp, Libraries/LibDevTools/Actors/WalkerActor.cpp, Libraries/LibWebView/Application.cpp, Libraries/LibWebView/Options.h, UI/AppKit/Application/ApplicationDelegate.mm, UI/Qt/BrowserWindow.cpp
=> LibDevTools: Support inspecting pseudo element properties

Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
This is part 1 of my follow-ups to https://github.com/LadybirdBrowser/ladybird/pull/3011 and what I subsequently wrote about in [Slightly better named character reference tokenization than Chrome, Safari, and Firefox](https://www.ryanliptak.com/blog/better-named-character-reference-tokenization/) (for this PR, see [this section in particular](https://www.ryanliptak.com/blog/better-named-character-reference-tokenization/#a-benefit-of-the-lookahead-strategy)). I'll have another PR soon to improve the DAFSA implementation.
---
When there is an active insertion point, it's necessary to tokenize code-point-by-code-point to handle the case of `document.write` being used to insert a named character reference one code point at a time (see …
=> LibWeb/HTML: Use lookahead when possible for named character references

Libraries/LibURL/Parser.cpp
URL parsing is expected to take place on well formed unicode strings. Had been putting it off for a while, but let's get it out of the way.
Makes us pass all URL WPT test cases with the exception of the shadow realm IDL harness.
=> LibURL: Convert to scalar string before URL parsing

Services/WebContent/ConnectionFromClient.cpp
Pseudo elements are only dumped if they have computed style.
Custom properties are only dumped on their originating element, because of how we currently store them.
=> WebContent: Include pseudo-elements and custom properties in styles dump

CMakePresets.json
Addresses [this discussion](https://discord.com/channels/1247070541085671459/1306918361732616212/1387463356419543080)
=> CMake: Improve preset display names and descriptions

Libraries/LibWeb/DOM/Document.cpp, Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Document-createEvent.https.txt, Tests/LibWeb/Text/input/wpt-import/dom/nodes/Document-createEvent.https.html
Some low hanging fruit I noticed when investigating an issue we have with storage event
=> LibWeb/DOM: Add StorageEvent and DragEvent to Document.createEvent

Libraries/LibWeb/CSS/CSSMediaRule.h, Libraries/LibWeb/CSS/CSSMediaRule.idl, Libraries/LibWeb/CSS/CSSSupportsRule.h, Libraries/LibWeb/CSS/CSSSupportsRule.idl, Tests/LibWeb/Text/expected/wpt-import/css/css-conditional/idlharness.txt, Tests/LibWeb/Text/input/wpt-import/css/css-conditional/idlharness.html, Tests/LibWeb/Text/input/wpt-import/interfaces/css-conditional.idl, Tests/LibWeb/Text/input/wpt-import/resources/idlharness.js
=> LibWeb: Add matches attribute to CSSSupportsRule & CSSMediaRule

Libraries/LibWeb/DOM/ShadowRoot.h, Tests/LibWeb/Text/expected/wpt-import/css/cssom/CSSStyleSheet-constructable.txt, Tests/LibWeb/Text/input/wpt-import/css/cssom/CSSStyleSheet-constructable.html
Fixes a crash in wpt.live/css/cssom/CSSStyleSheet-constructable.html
=> LibWeb: Include own shadow root in for_each_shadow_including_descendant

Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/Forward.h, Libraries/LibWeb/HTML/Navigable.cpp, Libraries/LibWeb/HTML/Navigable.h, Libraries/LibWeb/HTML/RenderingThread.cpp, Libraries/LibWeb/HTML/RenderingThread.h, Libraries/LibWeb/HTML/TraversableNavigable.h, Libraries/LibWeb/Painting/BackgroundPainting.cpp, Libraries/LibWeb/Painting/BackingStoreManager.cpp, Libraries/LibWeb/Painting/BackingStoreManager.h, Libraries/LibWeb/Painting/CanvasPaintable.cpp, Libraries/LibWeb/Painting/Command.h, Libraries/LibWeb/Painting/DisplayListPlayerSkia.h, Libraries/LibWeb/Painting/DisplayListRecorder.cpp, Libraries/LibWeb/Painting/DisplayListRecorder.h, Libraries/LibWeb/Painting/NavigableContainerViewportPaintable.cpp, Libraries/LibWeb/Painting/StackingContext.cpp
With this change number of recompiled files after modification of `Command.h` goes down from >1000 to <100.
=> LibWeb: Rearrange code such that a lot less files include `Command.h`

Libraries/LibWeb/SVG/SVGGeometryElement.cpp, Libraries/LibWeb/SVG/SVGGeometryElement.h, Libraries/LibWeb/SVG/SVGGeometryElement.idl, Tests/LibWeb/Text/expected/wpt-import/svg/idlharness.window.txt, Tests/LibWeb/Text/expected/wpt-import/svg/shapes/line-pathLength.txt, Tests/LibWeb/Text/input/wpt-import/svg/shapes/line-pathLength.svg
=> LibWeb: Implement the `SVGGeometryElement.pathLength` attribute

Libraries/LibRegex/RegexByteCode.cpp, Libraries/LibRegex/RegexByteCode.h, Libraries/LibRegex/RegexMatcher.cpp, Libraries/LibRegex/RegexOptimizer.cpp, Libraries/LibRegex/RegexParser.h, Tests/LibRegex/TestRegex.cpp
=> LibRegex: Account for uppercase characters in insensitive patterns

Libraries/LibWeb/Layout/Node.cpp, Libraries/LibWeb/Layout/SVGFormattingContext.cpp, Tests/LibWeb/Layout/expected/svg/foreignObject-with-abspos-descendant.txt, Tests/LibWeb/Layout/expected/svg/svg-nested-svg-display-block.txt, Tests/LibWeb/Layout/input/svg/svg-nested-svg-display-block.html
See individual commits. Two problems down, many problems to go!
=> Two more SVG fixes for Discord

Tests/LibWeb/Layout/expected/table/th-default-text-align.txt
Needed after edca2ab66676bb2ea2f983a3f63c0898daf3e843.
=> Tests: Rebaseline Layout/input/table/th-default-text-align.html

Libraries/LibWeb/DOM/Node.cpp
`if (invalidation_set.needs_invalidate_whole_subtree())` branch in the end of the function was always false.
=> LibWeb: Delete unreachable code in `Node::invalidate_style()`

Libraries/LibWeb/CSS/CSSStyleProperties.cpp, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp, Tests/LibWeb/Text/expected/css/serialize-shorthand-with-conflicting-logical-alias.txt, Tests/LibWeb/Text/expected/wpt-import/css/cssom/cssstyledeclaration-setter-logical.txt, Tests/LibWeb/Text/input/css/serialize-shorthand-with-conflicting-logical-alias.html, Tests/LibWeb/Text/input/wpt-import/css/cssom/cssstyledeclaration-setter-logical.html
Builds on the work @AtkinsSJ did in #5287 around defining logical property groups to tick off a couple of FIXMEs we have around that concept.
See individual commits for more details.
Gains us a grand total of 1 new WPT pass.
=> LibWeb: Respect logical property groups

Libraries/LibWeb/CMakeLists.txt, Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveFactory.cpp, Libraries/LibWeb/ContentSecurityPolicy/Directives/StyleSourceAttributeDirective.cpp, Libraries/LibWeb/ContentSecurityPolicy/Directives/StyleSourceAttributeDirective.h, Libraries/LibWeb/ContentSecurityPolicy/Directives/StyleSourceDirective.cpp, Libraries/LibWeb/ContentSecurityPolicy/Directives/StyleSourceDirective.h, Libraries/LibWeb/ContentSecurityPolicy/Directives/StyleSourceElementDirective.cpp, Libraries/LibWeb/ContentSecurityPolicy/Directives/StyleSourceElementDirective.h, Libraries/LibWeb/DOM/StyleElementUtils.cpp, Libraries/LibWeb/Forward.h
Part 12 of splitting up https://github.com/LadybirdBrowser/ladybird/pull/2854
After scripts comes stylesheets :^)
=> LibWeb/CSP: Implement the style-src(-{attr,elem}) directives

Libraries/LibWeb/CMakeLists.txt, Libraries/LibWeb/ContentSecurityPolicy/Directives/ChildSourceDirective.cpp, Libraries/LibWeb/ContentSecurityPolicy/Directives/ChildSourceDirective.h, Libraries/LibWeb/ContentSecurityPolicy/Directives/DefaultSourceDirective.cpp, Libraries/LibWeb/ContentSecurityPolicy/Directives/DefaultSourceDirective.h, Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveFactory.cpp, Libraries/LibWeb/ContentSecurityPolicy/Directives/WorkerSourceDirective.cpp, Libraries/LibWeb/ContentSecurityPolicy/Directives/WorkerSourceDirective.h, Libraries/LibWeb/Forward.h
Part 13 of splitting up https://github.com/LadybirdBrowser/ladybird/pull/2854
=> LibWeb/CSP: Implement the worker-src, default-src, child-src directives

Libraries/LibWeb/CSS/Parser/Parser.cpp, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp, Tests/LibWeb/Crash/JS/draw-from-offscreen-canvas.html, Tests/LibWeb/Crash/wpt-import/html/semantics/popovers/popover-root-crash.html, Tests/LibWeb/Text/expected/wpt-import/css/css-variables/variable-definition.txt, Tests/LibWeb/Text/input/wpt-import/css/css-variables/variable-definition.html
I may add more commits tomorrow
=> Various crash fixes

Libraries/LibWeb/CSS/StyleValues/CursorStyleValue.cpp, Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/Painting/BackgroundPainting.cpp, Libraries/LibWeb/Painting/Command.cpp, Libraries/LibWeb/Painting/DisplayList.h, Libraries/LibWeb/Painting/DisplayListRecorder.cpp, Libraries/LibWeb/Painting/DisplayListRecorder.h, Libraries/LibWeb/Painting/PaintableBox.cpp, Libraries/LibWeb/Painting/SVGMaskable.cpp, Libraries/LibWeb/Painting/StackingContext.cpp, Tests/LibWeb/Text/expected/display_list/simple-overflow-hidden.txt
=> Minor stylistic changes in rendering code

Libraries/LibWeb/DOM/Document.cpp, Libraries/LibWeb/DOM/Document.h, Libraries/LibWeb/ResizeObserver/ResizeObserver.cpp, Libraries/LibWeb/ResizeObserver/ResizeObserver.h
=> Fix some GC leaks on Discord

Libraries/LibWeb/MimeSniff/Resource.cpp, Tests/LibWeb/TestMimeSniff.cpp
See https://github.com/whatwg/mimesniff/pull/144/files.
=> LibWeb/MimeSniff: Update Rar signature to match spec

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
This fixes a bug when trying to generate code for a function that returns a IDL dictionary with optional members.
Found while implementing the WebSerial `getInfo()` [method](https://wicg.github.io/serial/#getinfo-method).
As discussed on Discord: https://discord.com/channels/1247070541085671459/1247090119442173963/1402283999967182989
=> LibWeb: Fix IDL codegen for dictionary return type with optional members

Meta/find_compiler.py, Meta/ladybird.py
Got tired of looking up the command line flags :)
=> Meta: Add a ladybird.py command to profile a process

UI/Qt/Tab.cpp
=> UI/Qt: Add Alt+D as a shortcut to focus the location editor

AK/ConstrainedStream.cpp, AK/ConstrainedStream.h, AK/DoublyLinkedList.h, AK/Forward.h, AK/LEB128.h, AK/MemoryStream.cpp, AK/MemoryStream.h, AK/Stream.cpp, AK/Stream.h, AK/Vector.h, Libraries/LibJS/Runtime/Value.cpp, Libraries/LibWasm/AbstractMachine/AbstractMachine.h, Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp, Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h, Libraries/LibWasm/AbstractMachine/Configuration.cpp, Libraries/LibWasm/AbstractMachine/Configuration.h, Libraries/LibWasm/AbstractMachine/Validator.cpp, Libraries/LibWasm/AbstractMachine/Validator.h, Libraries/LibWasm/Opcode.h, Libraries/LibWasm/Parser/Parser.cpp, Libraries/LibWasm/Printer/Printer.cpp, Libraries/LibWasm/Types.h, Libraries/LibWeb/WebAssembly/WebAssembly.cpp, Libraries/LibWeb/WebAssembly/WebAssembly.h, Meta/find_compiler.py, Tests/AK/TestDoublyLinkedList.cpp, Tests/AK/TestVector.cpp, Utilities/wasm.cpp
See final few commits for perf stats.
=> LibWasm: Let's do some performance work

Services/WebContent/WebDriverConnection.cpp
Regressed in c57975c9fdb98e03da0f8098c324577f8ecc753c, oops!
=> WebContent: Correct StyleValue.h include

Services/RequestServer/ConnectionFromClient.cpp
=> RequestServer: small improvements

Libraries/LibURL/URL.cpp, Libraries/LibURL/URL.h, Libraries/LibWeb/CookieStore/CookieStore.cpp
Each commit matches a normative change commit in https://github.com/whatwg/cookiestore.
=> LibWeb: Catch up to a couple of normative changes in CookieStore

.devcontainer/features/ladybird/install-ubuntu.sh, Documentation/BuildInstructionsLadybird.md
=> Documentation: Add `libdrm-dev` to Ubuntu/Debian build instructions

Libraries/LibGfx/VulkanContext.cpp, Libraries/LibWeb/WebGL/OpenGLContext.cpp
Fixes little code style issues overlooked in PR review.
=> Follow up on #5864: minor style changes

Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp, Libraries/LibWeb/WebIDL/DOMException.h
=> LibWeb: some goodies in CryptoAlgorithms and an unused import removal

Libraries/LibWeb/CSS/StyleInvalidation.cpp, Libraries/LibWeb/DOM/Element.cpp
See individual commits for details - fixes #5945
=> LibWeb: Don't consider null -> null as a change for invalidation

Libraries/LibWeb/Animations/KeyframeEffect.cpp, Libraries/LibWeb/CSS/StyleComputer.cpp, Libraries/LibWeb/CSS/StyleComputer.h, Tests/LibWeb/Crash/CSS/animated-revert-shorthand.html, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/background-color-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/background-position-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/background-position-origin-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/background-position-x-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/background-position-y-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/background-size-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/border-color-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/border-image-outset-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/border-image-width-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/border-width-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/animations/box-shadow-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-masking/animations/clip-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-masking/animations/mask-position-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/animation/aspect-ratio-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/animation/width-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-tables/animations/border-spacing-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-transforms/animation/rotate-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-transforms/animation/scale-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-transforms/animation/translate-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-transitions/animations/text-shadow-interpolation.txt, Tests/LibWeb/Text/expected/wpt-import/css/filter-effects/animation/backdrop-filter-interpolation-001.txt, Tests/LibWeb/Text/expected/wpt-import/css/filter-effects/animation/filter-interpolation-001.txt
A couple of improvements to how we compute keyframe properties - see individual commits for details.
Gains us 234 new WPT passes in tree (with presumably more out of tree).
=> LibWeb: Improvements to computing keyframe properties

Libraries/LibWeb/HTML/AttributeNames.h, Libraries/LibWeb/HTML/FormAssociatedElement.h, Libraries/LibWeb/HTML/HTMLButtonElement.h, Libraries/LibWeb/HTML/HTMLElement.cpp, Libraries/LibWeb/HTML/HTMLElement.h, Libraries/LibWeb/HTML/HTMLElement.idl, Libraries/LibWeb/HTML/HTMLFieldSetElement.h, Libraries/LibWeb/HTML/HTMLInputElement.h, Libraries/LibWeb/HTML/HTMLOutputElement.h, Libraries/LibWeb/HTML/HTMLSelectElement.h, Libraries/LibWeb/HTML/HTMLTextAreaElement.h, Tests/LibWeb/Text/expected/wpt-import/html/editing/editing-0/autocapitalization/autocapitalize.txt, Tests/LibWeb/Text/expected/wpt-import/html/editing/editing-0/autocorrection/autocorrection.txt, Tests/LibWeb/Text/expected/wpt-import/html/editing/editing-0/spelling-and-grammar-checking/spellcheck-enumerated-ascii-case-insensitive.txt, Tests/LibWeb/Text/expected/wpt-import/html/editing/editing-0/spelling-and-grammar-checking/user-interaction-editing-spellcheck.txt, Tests/LibWeb/Text/expected/wpt-import/html/editing/editing-0/writing-suggestions/writingsuggestions.txt, Tests/LibWeb/Text/input/wpt-import/html/editing/editing-0/autocapitalization/autocapitalize.html, Tests/LibWeb/Text/input/wpt-import/html/editing/editing-0/autocorrection/autocorrection.html, Tests/LibWeb/Text/input/wpt-import/html/editing/editing-0/spelling-and-grammar-checking/spellcheck-enumerated-ascii-case-insensitive.html, Tests/LibWeb/Text/input/wpt-import/html/editing/editing-0/spelling-and-grammar-checking/user-interaction-editing-spellcheck.html, Tests/LibWeb/Text/input/wpt-import/html/editing/editing-0/writing-suggestions/writingsuggestions.html
Implements the `spellcheck`, `writingSuggestions`, `autocapitalize` and `autocorrect` attributes.
Gains us a few more WPT tests.
=> LibWeb: Implement editing attributes

Libraries/LibWeb/Layout/LayoutState.cpp, Libraries/LibWeb/Painting/Paintable.cpp
A couple of small changes I made while trying to debug an issue.
=> LibWeb: Misc. cleanup of LayoutState

Tests/LibWeb/test-web/Fuzzy.cpp, Tests/LibWeb/test-web/TestWebView.cpp
=> Tests/LibWeb: Two small test-web fixes

Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp, Libraries/LibWeb/CSS/Properties.json, Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp, Tests/LibWeb/Text/expected/css/set-style-declaration-shorthand.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/parsing/border-shorthand.txt, Tests/LibWeb/Text/expected/wpt-import/css/cssom/border-shorthand-serialization.txt, Tests/LibWeb/Text/expected/wpt-import/css/cssom/shorthand-values.txt, Tests/LibWeb/Text/input/wpt-import/css/css-backgrounds/parsing/border-shorthand.html
=> LibWeb: Reset border-image to initial value when using border 

Tests/LibWeb/Text/expected/wpt-import/css/css-typed-om/idlharness.txt, Tests/LibWeb/Text/input/wpt-import/interfaces/css-typed-om.idl, Tests/LibWeb/Text/input/wpt-import/interfaces/geometry.idl, Tests/LibWeb/Text/input/wpt-import/interfaces/mathml-core.idl
Import the missing WPT idl files so that the css/css-typed-om/idlharness.html test can run locally.
=> Tests: Fix the typed-om idlharness test

Libraries/LibWeb/CSS/LogicalPropertyGroups.json, Libraries/LibWeb/CSS/Properties.json, Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp, Tests/LibWeb/Text/expected/css/CSSStyleDeclaration-has-indexed-property-getter.txt, Tests/LibWeb/Text/expected/css/CSSStyleProperties-all-supported-properties-and-default-values.txt, Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-cascade/all-prop-revert-layer.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-overflow/logical-overflow-001.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-overflow/overflow-shorthand-002.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-overflow/parsing/overflow-invalid.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-overflow/parsing/overflow-valid.txt, Tests/LibWeb/Text/input/wpt-import/css/css-overflow/logical-overflow-001.html, Tests/LibWeb/Text/input/wpt-import/css/css-overflow/overflow-shorthand-002.html, Tests/LibWeb/Text/input/wpt-import/css/css-overflow/parsing/overflow-invalid.html, Tests/LibWeb/Text/input/wpt-import/css/css-overflow/parsing/overflow-valid.html
Gains us 17 WPT subtests in the `css/css-overflow` directory.
=> Add the `overflow-inline` and `overflow-block` properties

Tests/LibWeb/Layout/expected/empty-editable-shows-cursor.txt
Somehow this went out of sync between it running on CI and getting merged.
=> Tests: Update empty-editable-shows-cursor expectation file

Libraries/LibWeb/CSS/Serialize.cpp, Tests/LibWeb/Text/expected/css/custom-property-computed-value.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-values/attr-all-types.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-values/attr-null-namespace.txt, Tests/LibWeb/Text/expected/wpt-import/css/css-variables/variable-substitution-variable-declaration.txt, Tests/LibWeb/Text/input/wpt-import/css/css-variables/variable-substitution-variable-declaration.html
=> LibWeb: Collapse & trim whitespace when serializing UnresolvedStyleValue

Documentation/GettingStartedContributing.md
The standard workflow for working with forks is to clone the fork and add the main repository as upstream. Also recommend using git switch instead of checkout.
=> Docs: Recommend the standard git workflow

Libraries/LibWeb/WebGL/WebGL2RenderingContextBase.idl, Libraries/LibWeb/WebGL/WebGL2RenderingContextImpl.cpp, Libraries/LibWeb/WebGL/WebGL2RenderingContextImpl.h, Libraries/LibWeb/WebGL/WebGLRenderingContextBase.h, Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Same fix as d54cab60 but applied for Uint32List.
=> LibWeb/WebGL: Define Uint32List exactly like in the spec

Libraries/LibWeb/DOM/Element.cpp, Libraries/LibWeb/Layout/LayoutState.cpp, Libraries/LibWeb/Page/EventHandler.cpp, Libraries/LibWeb/Painting/PaintableBox.cpp, Libraries/LibWeb/Painting/PaintableBox.h
Before:
https://github.com/user-attachments/assets/9a0a1d4c-81c5-44b8-a467-2ef151aeabc7
https://github.com/user-attachments/assets/85f4db76-2fdd-4227-a01e-40fa405615e2
After:
https://github.com/user-attachments/assets/69020df0-12fd-4a83-bb45-6f7ef1905d3d
https://github.com/user-attachments/assets/79a3a0a1-1d61-4054-a8aa-713b819c9097
=> LibWeb: Don't handle scroll if scroll is not updated

Libraries/LibJS/Bytecode/IdentifierTable.h, Libraries/LibJS/Bytecode/Interpreter.cpp, Libraries/LibJS/Bytecode/Interpreter.h
=> Two little JS perf things

Libraries/LibIPC/Connection.cpp
When a site continuously generates a large number of events, shutdown of IPC transport can be missed, leading to a run away WebContent process and large memory consumption.
Got a report in #4988 where WebContent process would cause a huge memory leak if Ladybird process is stopped (e.g. pressing the X on corner of Window).   So the problem is that this site hltv.org is causing WebContent process to handle a large number of ReadyToPaint events and Ladybird is responding with the DidPaint event.  Code handling the event messages will not call shutdown if the queue is not empty.  If events arrive quickly and continuously, the shutdown may not happen.
Haven't nailed down the memory leak yet, but suspect that the outgoing queue to the Ladybird process is filling up due to nothing there to …
=> LibIPC: Shutdown IPC event handler when transport is lost
