Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/wpt-import/fetch/api/headers/headers-basic.any.txt
Tests/LibWeb/Text/expected/wpt-import/fetch/api/headers/headers-record.any.txt
Tests/LibWeb/Text/input/wpt-import/fetch/api/headers/headers-basic.any.html
Tests/LibWeb/Text/input/wpt-import/fetch/api/headers/headers-basic.any.js
Tests/LibWeb/Text/input/wpt-import/fetch/api/headers/headers-record.any.html
Tests/LibWeb/Text/input/wpt-import/fetch/api/headers/headers-record.any.js

The WebIDL for the `Headers` constructor specifies that the `init` parameter is optional and must be of type `HeadersInit`. While the parameter can be omitted (or explicitly set to `undefined`), `null` is not a valid value.
This change fixes at least 2 "Create headers with null should throw"
WPT subtests which I have imported in this patch.

LibWeb: Throw TypeError for `new Headers(null)`

---

Libraries/LibWeb/WebAssembly/Memory.cpp
Tests/LibWeb/Text/expected/Wasm/WebAssembly-grow-hook.txt
Tests/LibWeb/Text/input/Wasm/WebAssembly-grow-hook.html

Previously it would only register the hook for JavaScript constructed Memory objects. This allows Ruffle to load again.
https://github.com/user-attachments/assets/1c6c75ff-3bb5-4fc3-94cd-89f9a1a5eb3b
(The logo on their homepage is a SWF of their logo running in Ruffle :^))

LibWeb: Register Wasm memory grow hook in constructor of Memory objects

---

Libraries/LibWeb/ARIA/Roles.cpp

* https://wpt.fyi/results/wai-aria/role/menu-roles.html?product=ladybird&product=chrome&q=aria
* https://www.w3.org/TR/wai-aria-1.2/#widget_roles
Add missing `menuitemradio` widget role to the list.
Make sure that correct accessibility role is set but running test DOM locally and verifying with build-in inspector.

LibWeb/ARIA: Add missing `menuitemradio` widget role

---

Libraries/LibWeb/WebIDL/AbstractOperations.cpp

We are currently returning LibJS's invalid code point message, but not formatting it with the bad value. So we get something like:
Unhandled JavaScript exception: [TypeError] Invalid code point {},
must be an integer no less than 0 and no greater than 0x10FFFF
So not only is the error unformatted, but it's inaccurate; in this case, the byte cannot be larger than 255.

LibWeb: Return a better error message for invalid byte strings

---

Libraries/LibWeb/Internals/Internals.cpp
Libraries/LibWeb/Internals/Internals.h
Libraries/LibWeb/Internals/Internals.idl
Libraries/LibWeb/Page/Page.h
Libraries/LibWeb/SVG/SVGDecodedImageData.h
Libraries/LibWebView/HelperProcess.cpp
Libraries/LibWebView/Options.h
Services/WebContent/PageClient.cpp
Services/WebContent/PageClient.h
Services/WebContent/main.cpp
Services/WebWorker/PageHost.h
Tests/LibWeb/Text/expected/Internals/headless.txt
Tests/LibWeb/Text/input/Internals/headless.html
Tests/LibWeb/Text/input/wpt-import/resources/testharness.js
UI/Headless/Application.cpp

This PR adds an `internals.headless` attribute that returns true if the browser is running headlessly and uses it to determine whether imported WPT test output should be shown.
Previously, imported WPT tests didn't display any output if the internals object was exposed. This change adds the condition that the browser must also be running headlessly for test output to not be displayed.
This can be useful when debugging imported WPT tests in cases where the internals object needs to be exposed.

Tests: Don't display imported WPT test output if browser is headless 

---

Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/HTML/EventSource.cpp
Libraries/LibWeb/HTML/HTMLBodyElement.cpp
Libraries/LibWeb/HTML/HTMLFormElement.cpp
Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Libraries/LibWeb/HTML/HTMLObjectElement.h
Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
Libraries/LibWeb/HTML/HTMLTableElement.cpp
Libraries/LibWeb/HTML/HTMLTableRowElement.cpp
Libraries/LibWeb/HTML/HTMLTableSectionElement.cpp
Libraries/LibWeb/HTML/Location.cpp
Libraries/LibWeb/HTML/Scripting/Environments.cpp
Libraries/LibWeb/HTML/Scripting/Environments.h
Libraries/LibWeb/HTML/Window.cpp
Libraries/LibWeb/HTML/Worker.cpp
Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
Libraries/LibWeb/Page/EventHandler.cpp
Libraries/LibWeb/SVG/SVGGradientElement.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Services/WebContent/ConnectionFromClient.cpp
Tests/LibWeb/Text/input/object-with-unsupported-type-in-data-attribute.html

This eliminates the use of `ResourceLoader` in `HTMLObjectElement`. The spec steps around fetching have been slightly updated since we've last looked at this, so those are updated here.
Ref #2634

LibWeb: Use Fetch to retrieve HTMLObjectElement data URLs

---

Libraries/LibGfx/ImageFormats/PNGLoader.cpp

Before, libpng would use its own internal logging mechanism to print non-fatal errors and warnings to stdout/stderr. This made it confusing when trying to search the Ladybird codebase for those messages as they didn't exist.
This commit uses `png_set_error_fn` from libpng to redirect those messages to our own custom logging functions instead.
cc: @LucasChollet

LibGfx: Redirect PNG errors and warnings to our own logging functions

---

Tests/LibWeb/Text/expected/wpt-import/infrastructure/testdriver/click.txt
Tests/LibWeb/Text/expected/wpt-import/infrastructure/testdriver/send_keys.txt
Tests/LibWeb/Text/input/wpt-import/infrastructure/testdriver/click.html
Tests/LibWeb/Text/input/wpt-import/infrastructure/testdriver/send_keys.html
Tests/LibWeb/Text/input/wpt-import/resources/testdriver-vendor.js
Tests/LibWeb/Text/input/wpt-import/resources/testdriver.js

WPT provides `testdriver-vendor.js`, where you can put vendor specific implementations of functions called by `testdriver`.
This PR moves functions that were previously patched in `testdriver.js` to `testdriver-vendor.js` and adds vendor specific implementations of `click()` and `send_keys()`, which are implemented using methods from `Internals`.

Tests: Add Ladybird specific testdriver functions

---

Meta/WPT.sh

Also add a `WPT.sh list-tests` command, which outputs all the tests that would run for a given set of directories - this is now used by `WPT.sh import`.

Meta: Add the ability to import entire test directories with `WPT.sh`

---

Libraries/LibWeb/Fetch/Response.cpp
Tests/LibWeb/Text/expected/wpt-import/fetch/api/response/response-error.any.txt
Tests/LibWeb/Text/input/wpt-import/fetch/api/response/response-error.any.html
Tests/LibWeb/Text/input/wpt-import/fetch/api/response/response-error.any.js

Implemented validation to ensure `statusText` matches the `reason-phrase` token production.
This change fixes a WPT subtest which I have imported.

LibWeb: Add statusText validation for Response constructor

---

Libraries/LibWeb/Fetch/Headers.cpp
Libraries/LibWeb/Fetch/HeadersIterator.cpp
Tests/LibWeb/Text/expected/Fetch/fetch-headers-non-ascii.txt
Tests/LibWeb/Text/expected/wpt-import/fetch/api/headers/headers-normalize.any.txt
Tests/LibWeb/Text/input/Fetch/fetch-headers-non-ascii.html
Tests/LibWeb/Text/input/wpt-import/fetch/api/headers/headers-normalize.any.html
Tests/LibWeb/Text/input/wpt-import/fetch/api/headers/headers-normalize.any.js

Ensure the Headers object's associated header list is ISO-8859-1 encoded
when set using `Infra::isomorphic_encode` and correctly decoded using
`Infra::isomorphic_decode`.
Follow-up of https://github.com/LadybirdBrowser/ladybird/pull/1893

LibWeb: Ensure Headers API can handle non-ascii characters

---

Libraries/LibWeb/HTML/HTMLLIElement.h
Tests/LibWeb/Text/expected/wpt-import/html-aam/roles-generic.tentative.txt
Tests/LibWeb/Text/input/wpt-import/html-aam/roles-generic.tentative.html

This change makes Ladybird conform to the current requirements at https://w3c.github.io/core-aam/#roleMappingComputedRole in the “Core Accessibility API Mappings” spec for the case of “orphaned” `li` elements; that is, any `li` element which doesn’t have `role=list` ancestor.
The core-aam spec requires that in such cases, the `li` element must not be assigned the `listitem` role but instead must be treated as if it had no role at all.
This change gets us 100% passing the https://wpt.fyi/results/html-aam/roles-generic.tentative.html?product=ladybird test.

LibWeb: Assign “orphaned” li elements the default ARIA role “none”

---

Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
Tests/LibWeb/Text/expected/wpt-import/html-aam/table-roles.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/table-roles.txt
Tests/LibWeb/Text/input/wpt-import/html-aam/table-roles.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/table-roles.html

This change aligns the default roles for `th` and `td` elements with the requirements in the HTML-AAM spec, and with the corresponding WPT tests at https://wpt.fyi/results/html-aam/table-roles.html, and with the behavior in other engines.
Otherwise, without this change, the default role values computed for `th` and `td` elements in some cases don’t match the behavior in other engines, and don’t match the expected results for the corresponding WPT tests.
This change gets us passing 100% of the subtests in the `table-roles.html` test at https://wpt.fyi/results/html-aam?product=ladybird

LibWeb: Align default “th” and “td” roles with HTML-AAM spec and tests

---

Libraries/LibWeb/ARIA/AriaRoles.json
Libraries/LibWeb/ARIA/RoleType.cpp
Libraries/LibWeb/ARIA/Roles.cpp
Libraries/LibWeb/ARIA/Roles.h
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/roles.txt

> [!NOTE]
> This PR currently includes a cherry-pick of the d0938d32ad1 commit from https://github.com/LadybirdBrowser/ladybird/pull/2843 — just for convenience so that we can have all PASSES for the expectations for all subtests in the relevant imported WPT test.
…but the d5c210b62fb commit here that adds support for the `suggestion` ARIA role can be reviewed separately here without needing to (re)review here that other commit from https://github.com/LadybirdBrowser/ladybird/pull/2843.
After https://github.com/LadybirdBrowser/ladybird/pull/2843 is merged, I can just rebase this PR branch.
Anyway, after the d5c210b62fb change here, and the d0938d32ad1 change from #2843, we’ll be passing 100% of the subtests in the `roles.html` test at …

LibWeb: Add support for the “suggestion” ARIA role

---

.github/actions/setup/action.yml

What `latest-stable` means exactly also depends on the image version we're running the workflow on, and unfortunately this can vary wildly between GitHub runners.
Fixate the version to 16.1 for now. This version will need to be updated as soon as we want to increase the minimum supported compiler version.
This should improve cache coherency between different workflow runs.

CI: Select Xcode 16.1 explicitly instead of `latest-stable`

---

Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp

This removes the spoofed return values for AES GCM, introduced by @stelar7 in #2085.
It is incredibly dangerous to pretend that something is encrypted, even if the buffer is just zeros, but that's exactly what Ladybird currently does. Some consequences might be data loss, websites having to do Internet-Explorer-ish workarounds for Ladybird, or Ladybird getting a reputation for not just being incomplete (which is perfectly forgivable), but actively harmful.
All this can be easily avoided by just doing the obvious and honest thing: raising a `NotSupportedError`.
When I started this PR, I originally wanted to implement AES-GCM properly, but never actually finished it. I assume that stelar7 had the same good intention, and something got in the way.
Since apparently noone is in the process of …

WebCrypto: Unspoof correctness of AES-GSM encryption/decryption

---

AK/NonnullOwnPtr.h
AK/NonnullRefPtr.h

With Swift interop, we already require latest Xcode versions, that do not need these workarounds
Ref https://github.com/llvm/llvm-project/issues/54040

AK: Remove clang-specific templates

---

Libraries/LibGfx/Bitmap.h
Libraries/LibGfx/PaintStyle.h

This ensures some compile-time assertions (all possible color storage formats are implemented) and fixes
> FIXME: There's a lot of inaccurately named functions in the Color class right now (RGBA vs BGRA).

LibGfx: Unify bitmap set_pixel() using templates

---

Libraries/LibWeb/HTML/HTMLElement.cpp

These were converted to lambdas in
6b921e91d4ce4791c67bf467a2ba519b8e3ca88b
But I merged fcf6cc27f2cf0c0d0d3c5bae353e348771d5fb98 without checking that the code had responded to the change.

LibWeb: Fix compile error for popover element internal lambdas

---

CMakeLists.txt
Meta/CMake/vcpkg/generate_vcpkg_toolchain_variables.cmake

Reference #2149
I'd rather not close that issue until there's a patchelf patch that fixes the underlying inconsistency.

CMake: Add workaround for binutils+patchelf incompatability

---

Libraries/LibWeb/Page/EventHandler.cpp
Tests/LibWeb/Text/expected/CSSOMView/mouse-event-offset-values.txt
Tests/LibWeb/Text/input/CSSOMView/mouse-event-offset-values.html

That is what the spec calls it, at least.
In code, this manifests as making the offset very aware of the element's transform cause the click position comes relative to the viewport, not the transformed element.
IMPORTANT:
For this to give the correct numbers, #2364 needs to be merged first to fix all the other issues that MouseEvent positions have.

LibWeb: Make MouseEvent.offsetX/Y ignore transforms

---

Libraries/LibWeb/CSS/Default.css
Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/HTML/AttributeNames.cpp
Libraries/LibWeb/HTML/AttributeNames.h
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.idl
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/wpt-import/html-aam/roles-dynamic-switch.tentative.window.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/input-type-checkbox-switch.tentative.window.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/selectors/pseudo-classes/input-checkbox-switch.tentative.window.txt
Tests/LibWeb/Text/input/wpt-import/html-aam/roles-dynamic-switch.tentative.window.html
Tests/LibWeb/Text/input/wpt-import/html-aam/roles-dynamic-switch.tentative.window.js
Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/input-type-checkbox-switch.tentative.window.html
Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/input-type-checkbox-switch.tentative.window.js
Tests/LibWeb/Text/input/wpt-import/html/semantics/selectors/pseudo-classes/input-checkbox-switch.tentative.window.html
Tests/LibWeb/Text/input/wpt-import/html/semantics/selectors/pseudo-classes/input-checkbox-switch.tentative.window.js

In conformance with the requirements of the spec PR at https://github.com/whatwg/html/pull/9546, this change adds support for the `switch` attribute for `type=checkbox` `input` elements — which is shipping in Safari (since Safari 17.4). This change also implements support for exposing it to AT users with `role=switch`.
For more info, see https://webkit.org/blog/15054/an-html-switch-control/ and for demos, see the “Native switch (unstyled)” and “Basic styled switch” demos at https://webkit.org/demos/html-switch/. (The other demos there rely 100% on CSS restyling that I think would likely not fully work as expected cross-browser as currently written — in _any_ other browser that might implement `switch`).
Web developers have been creating custom switch controls with CSS for a long time now …

LibWeb: Implement <input type=checkbox switch> experimentally

---

Libraries/LibWeb/Layout/SVGFormattingContext.cpp
Tests/LibWeb/Layout/expected/svg/standalone-h.txt
Tests/LibWeb/Layout/expected/svg/standalone-vb-h.txt
Tests/LibWeb/Layout/expected/svg/standalone-vb-w.txt
Tests/LibWeb/Layout/expected/svg/standalone-vb-wh.txt
Tests/LibWeb/Layout/expected/svg/standalone-vb.txt
Tests/LibWeb/Layout/expected/svg/standalone-w.txt
Tests/LibWeb/Layout/expected/svg/standalone-wh.txt
Tests/LibWeb/Layout/expected/svg/standalone.txt
Tests/LibWeb/Layout/input/svg/standalone-h.svg
Tests/LibWeb/Layout/input/svg/standalone-vb-h.svg
Tests/LibWeb/Layout/input/svg/standalone-vb-w.svg
Tests/LibWeb/Layout/input/svg/standalone-vb-wh.svg
Tests/LibWeb/Layout/input/svg/standalone-vb.svg
Tests/LibWeb/Layout/input/svg/standalone-w.svg
Tests/LibWeb/Layout/input/svg/standalone-wh.svg
Tests/LibWeb/Layout/input/svg/standalone.svg

Fixes #2668 
Before:  standalone SVG documents were stretched to fit the agent
viewport, ignoring specified width / height attributes.
After this: SVG documents with specified width/height attributes are
laid out respecting these attributes.
Regarding layout of standalone SVG documents, this brings Ladybird to:
- parity with Chromium (131.0.6778.85)
- almost parity with Firefox (129.0.2) -- difference not material

LibWeb: Layout standalone SVG document with specified dimensions

---

Libraries/LibJS/Runtime/AtomicsObject.cpp
Libraries/LibJS/Tests/builtins/Atomics/Atomics.compareExchange.js

This defers accessing TA internal slots until we know we have a valid, attached TA. Our implementation has assertions that guard against this.
Fixes a crash in the following test262 test:
```
test/staging/sm/Atomics/detached-buffers.js            💥 -> ✅
```

LibJS: Avoid internal assertion accessing detached TA internal slots

---

Libraries/LibWeb/CSS/Parser/RuleParsing.cpp

Seems like we don't have a CI run with all the debug macros enabled any more. Don't know if we want that.

LibWeb/CSS: Add missing parameter to CSSStyleValue::to_string() calls

---

Libraries/LibWeb/Forward.h
Libraries/LibWeb/WebGL/Types.h
Libraries/LibWeb/WebGL/WebGL2RenderingContextBase.idl
Libraries/LibWeb/WebGL/WebGL2RenderingContextOverloads.idl
Libraries/LibWeb/WebGL/WebGLSync.cpp
Libraries/LibWeb/WebGL/WebGLSync.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp

This is enough to make Unity Web reach the main loop, but sadly not enough for it to progress and render the first frame, either crashing with a Wasm OOB error (e.g. with https://3di70r.itch.io/crusty-proto) or infinitely looping and allocating a _lot_ of memory (e.g. with https://scottts.itch.io/different-strokes). Please note that the validation for these will likely need another look over.

LibWeb: Implement a whole bunch of WebGL2 calls and parameters

---

Libraries/LibGC/Heap.cpp

Speeds up the append_gc_graph function by preallocating space. This change reduces the time taken to dump the GC graph by 4% on about:blank on my m1 MacBook Air 
Benchmark:
```diff
diff --git a/Services/WebContent/ConnectionFromClient.cpp b/Services/WebContent/ConnectionFromClient.cpp
index 03944c68bc..e65c2f4d10 100644
--- a/Services/WebContent/ConnectionFromClient.cpp
+++ b/Services/WebContent/ConnectionFromClient.cpp
@@ -933,10 +933,17 @@ static void append_paint_tree(Web::Page& page, StringBuilder& builder)
Web::dump_tree(builder, *layout_root->first_paintable());
}
+#include <LibCore/ElapsedTimer.h>
+
static void append_gc_graph(StringBuilder& builder)
{
+    Core::ElapsedTimer timer;
+    timer.start();
auto gc_graph = Web::Bindings::main_thread_vm().heap().dump_graph();
+    auto …
```

LibGC: Preallocate space before dumping GC graph

---

Libraries/LibJS/Bytecode/Generator.cpp
Libraries/LibJS/Tests/operators/delete-basic.js

Even though calling delete on a super property will ultimately throw a ReferenceError, we must return the allocated register for the result of the delete operation (which would normally be a boolean). If the delete operation is used in a return statement, the bytecode generator for the return statement must be able to assume the statement had some output.
test262 diff:
```
test/staging/sm/class/superElemDelete.js  💥 -> ❌
test/staging/sm/class/superPropDelete.js  💥 -> ✅
```
We fail `superElemDelete.js` because in an expression like this:
```js
const key = {};
delete super[key];
```
We call `ToPropertyKey` on `key` before throwing for the invalid `super` deletion, in `delete_by_value_with_this`. We will likely need to change `Reference` to support holding onto the property key as a `Value` …

LibJS: Return the allocated dst register from deleting super properties

---

Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/HTML/FormAssociatedElement.h
Libraries/LibWeb/HTML/HTMLButtonElement.cpp
Libraries/LibWeb/HTML/HTMLButtonElement.h
Libraries/LibWeb/HTML/HTMLImageElement.cpp
Libraries/LibWeb/HTML/HTMLImageElement.h
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.h
Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Libraries/LibWeb/HTML/HTMLObjectElement.h
Libraries/LibWeb/HTML/HTMLOutputElement.cpp
Libraries/LibWeb/HTML/HTMLOutputElement.h
Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Libraries/LibWeb/HTML/PopoverInvokerElement.cpp
Libraries/LibWeb/HTML/PopoverInvokerElement.h
Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/popovertarget-reflection.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/popovertarget-reflection.html

PopoverInvokerElement's explicitly set attr-element should be set to null whenever the value of the `popovertarget` content attribute is changed.
NOTE: Since this should be done for all Element reflected targets, it may be worth investigating if this could be implemented in the IDL code generator.
Fixes: https://wpt.live/html/semantics/popovers/popovertarget-reflection.html

LibWeb: Implement `PopoverInvokerElement` attribute change steps

---

Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp
Libraries/LibGfx/ImageFormats/TinyVGLoader.h
Libraries/LibGfx/VectorGraphic.cpp
Libraries/LibGfx/VectorGraphic.h
UI/Qt/TVGIconEngine.cpp

This helps us with non-uniform scales, and makes things simple

LibGfx: Let Painter care about TinyVG transforms

---

Libraries/LibWeb/Fetch/Response.cpp
Tests/LibWeb/Text/expected/wpt-import/fetch/api/response/response-init-001.any.txt
Tests/LibWeb/Text/input/wpt-import/fetch/api/response/response-init-001.any.html
Tests/LibWeb/Text/input/wpt-import/fetch/api/response/response-init-001.any.js

This change fixed a WPT subtest which I also imported.

LibWeb: Fix is_valid_status_text to handle UTF-8 correctly

---

Libraries/LibGfx/Quad.h
Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Tests/LibGfx/CMakeLists.txt
Tests/LibGfx/TestQuad.cpp

Copies https://github.com/LadybirdBrowser/ladybird/pull/938
I
1) Removed documentation commit (shellcheck thing was totally unrelated)
2) Rebased on master and tested
3) Cleaned up/resolved CMakeLists.txt conflict
4) Added a commit to remove unnecessary include
Please note that `Quad::bounding_rect()` is never used outside the newly introduced test, and contains() is only ever used in a recursive function `SVGPathPaintable::hit_test()`

LibGfx: Implement even-odd method for Quad::contains() and add tests

---

Libraries/LibWeb/HTML/FormAssociatedElement.cpp

Previously, modifying any selection within a text control (a textarea or input element) would cause any previous selection to also be modified.
Fixes: #2797

LibWeb: Collapse selection when selecting text inside a text control

---

Libraries/LibWeb/Fetch/FetchMethod.cpp
Libraries/LibWeb/Fetch/Infrastructure/FetchController.cpp
Libraries/LibWeb/Fetch/Infrastructure/FetchController.h

This PR improves fetch so that the reason for an abort is returned and the request/response streams are properly handled.

LibWeb/Fetch: Improve aborting fetch

---

Tests/LibWeb/Text/expected/wpt-import/html-aam/fragile/area-role.txt
Tests/LibWeb/Text/expected/wpt-import/html-aam/fragile/optgroup-role.txt
Tests/LibWeb/Text/input/wpt-import/html-aam/fragile/area-role.html
Tests/LibWeb/Text/input/wpt-import/html-aam/fragile/optgroup-role.html

This change imports the remaining HTML-AAM tests from WPT that haven’t yet been imported in any previous PRs — giving us complete in-tree regression-testing coverage for all available WPT tests for the requirements in the HTML-AAM spec.
Reviewers: This change is tests-only, no code changes.

Tests: Import remaining HTML-AAM tests (no code)

---

Libraries/LibWeb/Painting/ImagePaintable.cpp
Tests/LibWeb/Ref/expected/object-fit-scale-down-ref.html
Tests/LibWeb/Ref/input/object-fit-scale-down.html

The `scale-down`  option for the `object-fit` property was previously unimplemented and was incorrectly treated as `objeect-fit: none`.
None of the related WPTs can be imported for this fix. They all still fail for the following unrelated reasons (or pass even though they should't):
* The tests use a dashed border. There seems to be a bug where the borders are rendered differently between the test and the ref page.
* The images are rendered with off-by-one errors in various places, presumably caused by rounding errors/inconsistencies.
Note that as per the `FIXME` comment, the scaling behavior is still not correct when e.g. changing zoom. This however was already the case in the existing code.

LibWeb: Add support for `object-fit: scale-down`

---

Libraries/LibWeb/HTML/HTMLElement.cpp
Libraries/LibWeb/HTML/HTMLElement.h

Auto popovers now correctly establish a close watcher when shown.
This means popovers now correctly close with an escape key press.
Also correctly hide open popovers when removed from the document.

LibWeb: Implement popover's close watcher

---

Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.cpp
Libraries/LibWeb/Fetch/Infrastructure/HTTP/Headers.h
Libraries/LibWeb/Infra/Strings.cpp
Tests/LibWeb/Text/expected/http-non-ascii-content-type.txt
Tests/LibWeb/Text/input/http-non-ascii-content-type.html

isomorphic encoding a value that has already been encoded will result in garbage data. `response_headers` is already encoded in ISO-8859-1, we cannot use `from_string_pair`, as it calls `isomorphic_decode`.
Follow-up of https://github.com/LadybirdBrowser/ladybird/pull/1893

LibWeb: Avoid re-encoding response headers

---

.github/workflows/merge-conflict-labeler.yml

This action adds and removes the new "conflicts" label to indicate whether a pull request is in need of conflict resolution. This both automatically informs the author of the PR that this is the case, if they have notifications enabled that is, and makes for an easier evaluation of the PR queue.
The automatic labeler runs:
* when `master` is updated;
* when a PR is (re)opened;
* when a PR's branch is updated.

CI: Automatically label PRs with merge conflicts

---

.github/workflows/ci.yml
.github/workflows/ladybird-js-artifacts.yml
.github/workflows/libjs-test262.yml
.github/workflows/lint-code.yml
.github/workflows/lint-commits.yml
.github/workflows/nightly-android.yml

* GitHub's required checks (that we enabled yesterday) stay in a "pending" state when using `paths-ignore`, so work around this.
* Remove `always()` from conditionals if a job has no dependencies and/or should be cancelable.
* Instead of matching a branch inside the `if` conditional for a job, move it to the `on` section of the workflow.
One side effect of this setup is that the "checks" section of a PR always displays the new "CI / path-changes" job that needs to be run for every PR, regardless of the changed paths.

CI: Make required checks work with ignored paths, remove `always()` and refactor branch matching

---

Libraries/LibWeb/CSS/Parser/Dimension.h
Libraries/LibWeb/CSS/Parser/Parser.cpp
Libraries/LibWeb/CSS/Parser/Parser.h
Libraries/LibWeb/CSS/StyleValues/CSSMathValue.cpp
Libraries/LibWeb/CSS/StyleValues/CSSMathValue.h

Previously we created a tree of CalculationNodes with dummy
UnparsedCalculationNode children, and then swapped those with the real
children. This matched the spec closely but had the unfortunate
downside that CalculationNodes couldn't be immutable, and couldn't know
their properties at construct-time. UnparsedCalculationNode is also a
footgun, as if it gets left in the tree accidentally we would VERIFY().
So instead, let's parse the calc() tree into an intermediate format, and
then convert each node in that tree, depth-first, into its
corresponding CalculationNode. This means each CalculationNode knows
what its children are when it is constructed, and they never change.
Apart from deleting UnparsedCalculationNode, we can also get rid of the
for_each_child_node() method that was only used …

LibWeb/CSS: Parse calc() as intermediate types instead of UnparsedCalculationNode

---

UI/Headless/HeadlessWebView.cpp

Without this, a crashing ref test is able to take down the entire process because of the `VERIFY(!m_pending_screenshot);` in `take_screenshot()`. The dialog/prompt fields were not causing crashes but clearing them feels more hygienic.

UI/Headless: Clear pending data when a test completes

---

Libraries/LibWeb/WebGL/WebGL2RenderingContext.h
Libraries/LibWeb/WebGL/WebGLBuffer.cpp
Libraries/LibWeb/WebGL/WebGLBuffer.h
Libraries/LibWeb/WebGL/WebGLFramebuffer.cpp
Libraries/LibWeb/WebGL/WebGLFramebuffer.h
Libraries/LibWeb/WebGL/WebGLObject.cpp
Libraries/LibWeb/WebGL/WebGLObject.h
Libraries/LibWeb/WebGL/WebGLProgram.cpp
Libraries/LibWeb/WebGL/WebGLProgram.h
Libraries/LibWeb/WebGL/WebGLQuery.cpp
Libraries/LibWeb/WebGL/WebGLQuery.h
Libraries/LibWeb/WebGL/WebGLRenderbuffer.cpp
Libraries/LibWeb/WebGL/WebGLRenderbuffer.h
Libraries/LibWeb/WebGL/WebGLRenderingContext.h
Libraries/LibWeb/WebGL/WebGLRenderingContextBase.h
Libraries/LibWeb/WebGL/WebGLSampler.cpp
Libraries/LibWeb/WebGL/WebGLSampler.h
Libraries/LibWeb/WebGL/WebGLShader.cpp
Libraries/LibWeb/WebGL/WebGLShader.h
Libraries/LibWeb/WebGL/WebGLSync.cpp
Libraries/LibWeb/WebGL/WebGLSync.h
Libraries/LibWeb/WebGL/WebGLTexture.cpp
Libraries/LibWeb/WebGL/WebGLTexture.h
Libraries/LibWeb/WebGL/WebGLTransformFeedback.cpp
Libraries/LibWeb/WebGL/WebGLTransformFeedback.h
Libraries/LibWeb/WebGL/WebGLVertexArrayObject.cpp
Libraries/LibWeb/WebGL/WebGLVertexArrayObject.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp

Also with these changes WebGL object visit a context they belong too.This way we could be sure that context object won't be deallocated
before any of the objects that belong to it.
Having a context pointer is also going to be used in upcoming changes
to generate an INVALID_OPERATION error if an object does not belong to
the context it's being used in.

LibWeb: Save WebGL context pointer in WebGLObject

---

Libraries/LibWeb/Bindings/MainThreadVM.cpp
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
Libraries/LibWeb/HTML/UniversalGlobalScope.cpp
Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Libraries/LibWeb/ResizeObserver/ResizeObserver.cpp
Libraries/LibWeb/WebIDL/AbstractOperations.cpp
Libraries/LibWeb/WebIDL/AbstractOperations.h
Tests/LibWeb/Text/expected/wpt-import/custom-elements/cross-realm-callback-report-exception.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/MutationObserver-cross-realm-callback-report-exception.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/embedded-content/the-canvas-element/toBlob-cross-realm-callback-report-exception.txt
Tests/LibWeb/Text/expected/wpt-import/html/webappapis/microtask-queuing/queue-microtask-cross-realm-callback-report-exception.txt
Tests/LibWeb/Text/expected/wpt-import/html/webappapis/timers/setinterval-cross-realm-callback-report-exception.txt
Tests/LibWeb/Text/expected/wpt-import/html/webappapis/timers/settimeout-cross-realm-callback-report-exception.txt
Tests/LibWeb/Text/expected/wpt-import/intersection-observer/callback-cross-realm-report-exception.txt
Tests/LibWeb/Text/expected/wpt-import/resize-observer/callback-cross-realm-report-exception.txt
Tests/LibWeb/Text/input/wpt-import/custom-elements/cross-realm-callback-report-exception.html
Tests/LibWeb/Text/input/wpt-import/dom/nodes/MutationObserver-cross-realm-callback-report-exception.html
Tests/LibWeb/Text/input/wpt-import/html/semantics/embedded-content/the-canvas-element/toBlob-cross-realm-callback-report-exception.html
Tests/LibWeb/Text/input/wpt-import/html/webappapis/microtask-queuing/queue-microtask-cross-realm-callback-report-exception.html
Tests/LibWeb/Text/input/wpt-import/html/webappapis/timers/setinterval-cross-realm-callback-report-exception.html
Tests/LibWeb/Text/input/wpt-import/html/webappapis/timers/settimeout-cross-realm-callback-report-exception.html
Tests/LibWeb/Text/input/wpt-import/intersection-observer/callback-cross-realm-report-exception.html
Tests/LibWeb/Text/input/wpt-import/resize-observer/callback-cross-realm-report-exception.html

This fixes a number of WPT tests, which expect an error to be reported if an exception is thrown in the timer callback.
Seven tests related to exception reporting, which were previously failing have been imported.

LibWeb: Make `WebIDL::invoke_callback()` report exceptions in various places

---

Libraries/LibGfx/BitmapSequence.cpp
Libraries/LibGfx/ImageFormats/PNGLoader.cpp
Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
Tests/LibWeb/Text/expected/HTML/png-without-IDAT-should-still-load.txt
Tests/LibWeb/Text/input/HTML/png-without-IDAT-should-still-load.html

This matches the behavior of other browsers, and is something that Cloudflare Turnstile checks for.
Also stop silently ignoring un-encodable IPC messages. I spent a lot of time being confused by this 😅

LibGfx+IPCCompiler: Treat PNG files with invalid frame data as transparent

---

Libraries/LibWeb/Internals/Internals.cpp
Libraries/LibWeb/Internals/Internals.h
Libraries/LibWeb/Internals/Internals.idl
Libraries/LibWeb/Page/Page.h
Libraries/LibWebView/ViewImplementation.h
Libraries/LibWebView/WebContentClient.cpp
Libraries/LibWebView/WebContentClient.h
Services/WebContent/PageClient.cpp
Services/WebContent/PageClient.h
Services/WebContent/WebContentClient.ipc
Tests/LibWeb/TestConfig.ini
Tests/LibWeb/Text/input/wpt-import/resources/testharness.js
UI/Headless/Test.cpp

This is implemented for WPT's `<meta name=timeout content=long>`, but we could always use this if particular home-grown tests take slightly too long for our default timeout.
This should solve the issue I was seeing in #2966, where `Text/input/wpt-import/html/rendering/pixel-length-attributes.html`  (which is a user of that meta tag) would intermittently time out.
Also, I've re-enabled the tests from #2792 as they all use the meta tag. Hopefully they'll now not time out!

headless-browser: Let tests configure a custom timeout

---

Libraries/LibCrypto/PK/RSA.cpp

Ensure `m1` becomes greater than `m2` even when smaller by more than one `p`. Since the next operations on `m1` are modulus `p` we can add it as many times as it's needed.
Crash observed in CI: https://github.com/LadybirdBrowser/ladybird/actions/runs/12390873867/job/34586824843#step:17:257

LibCrypto: Ensure RSA decryption with CRT works for all inputs

---

Libraries/LibWeb/Animations/Animatable.cpp
Libraries/LibWeb/CSS/Selector.h
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/DOM/Element.cpp
Tests/LibWeb/Text/expected/css/unknown-pseudo-elements-crash.txt
Tests/LibWeb/Text/input/css/unknown-pseudo-elements-crash.html

Their are some special values for CSS::Selector::PseudoElement::Type which are after `KnownPseudoElementCount` and therefore not present in various arrays of pseudo elements, this leads to some errors, if a type after `KnownPseudoElementCount` is used without checking first. This adds explicit checks to all usages
Possible related PR #1362
Fixes #2904 
[dashdot](https://github.com/MauriceNino/dashdot) uses react and [simplebar-react](https://www.npmjs.com/package/simplebar-react) which internally does some compatibility checks for 
```js
getComputedStyle(el, "::-webkit-scrollbar").display
```
(where `el` is any element)
and that crashes, as per #2904

LibWeb: Handle special cases of PseudoElement::Type correctly

---

Libraries/LibCrypto/BigInt/SignedBigInteger.h
Tests/LibCrypto/TestBigInteger.cpp

In particular, if given a value of -2147483648, we would invoke signed integer overflow (which is UB).

LibCrypto: Protect the SignedBigInteger ctor against integer overflow

---

Meta/CMake/common_compile_options.cmake
Tests/LibCrypto/TestRSA.cpp

This pull request removes the use of variable length arrays from Tests/LibCrypto/TestRSA.cpp and enables warnings when using VLAs.

Meta+Tests: Remove last use of VLAs and enable warning for them

---

Libraries/LibCore/EventLoopImplementationWindows.cpp

Replaces the use of a variable length array with a vector. Adds maybe_unused to unimplemented function signatures to allow for compilation.

LibCore: Fix compilation of EventLoopImplementationWindows.cpp

---

Libraries/LibWeb/ARIA/ARIAMixin.cpp
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/synonym-roles.txt
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/synonym-roles.html

This change does replacement of ARIA roles that have newer synonyms.
There are a number of newer ARIA roles that are synonyms for older roles. https://wpt.fyi/results/wai-aria/role/synonym-roles.html has a number of subtests which expect that when retrieving the value of an explicitly-specified role attribute, if the value is one of the older role values, implementations must replace that with its newer synonym.

LibWeb: Replace ARIA “synonym” roles with their preferred synonyms

---

Libraries/LibCore/Process.cpp
UI/Headless/Fixture.cpp

This change fixes a crash I saw locally where `headless-browser` would always crash with the following error just prior to exit:
```
VERIFICATION FAILED: !_temporary_result.is_error() at /home/tim/repos/ladybird/UI/Headless/Fixture.cpp:83
/home/tim/repos/ladybird/Build/release/lib/liblagom-ak.so.0(ak_verification_failed+0xef) [0x7032bd52790f]
/home/tim/repos/ladybird/Build/release/bin/headless-browser(+0x143e0) [0x56277a50a3e0]
/home/tim/repos/ladybird/Build/release/bin/headless-browser(+0x12658) [0x56277a508658]
/home/tim/repos/ladybird/Build/release/bin/headless-browser(+0x127f9) [0x56277a5087f9]
/home/tim/repos/ladybird/Build/release/bin/headless-browser(+0x268ee) [0x56277a51c8ee]
/home/tim/repos/ladybird/Build/release/bin/headless-browser(+0x27542) [0x56277a51d542] …
```

LibWeb: Don't try to wait for HTTP server to exit if kill call fails

---

Libraries/LibWeb/Bindings/PlatformObject.cpp
Tests/LibWeb/Text/expected/htmlcollection-property-set-existing.txt
Tests/LibWeb/Text/expected/wpt-import/dom/collections/HTMLCollection-supported-property-names.txt
Tests/LibWeb/Text/input/htmlcollection-property-set-existing.html
Tests/LibWeb/Text/input/wpt-import/dom/collections/HTMLCollection-supported-property-names.html

PlatformObjects with named properties does not qualify as 'has own property' just by virtue of a named property existing.
This fixes at least one WPT test, which is imported.

LibWeb: PlatformObject::DefineOwnProperty fix 'has own property' check

---

Libraries/LibWeb/Page/EventHandler.cpp
Tests/LibWeb/Text/expected/CSSOMView/mouse-event-transformed-pseudoelement-crash.txt
Tests/LibWeb/Text/input/CSSOMView/mouse-event-transformed-pseudoelement-crash.html

Fixes #2985.
This avoids a crash.

LibWeb: Use paintables when calculating mouse event offset

---

Libraries/LibWeb/CSS/StyleComputer.cpp

start_loading_next_url() is a no-op if there's a pending resource load, but not if that resource load has successfully loaded already. There is a delay between the font resource loading, and it being processed into a vector font. Calling font_with_point_size() in that gap would previously erase the previously-loaded font, if the font had multiple URLs to choose from.
This fixes the icon font on mods.factorio.com :^)

LibWeb/CSS: Don't overwrite active font load when requesting a pt size

---

Libraries/LibGfx/PaintingSurface.cpp
Libraries/LibGfx/PaintingSurface.h
Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
Libraries/LibWeb/WebGL/OpenGLContext.cpp

By doing that we eliminate the need for the vertical flip flag.
As a side effect it fixes the bug when doing:
`canvasContext2d.drawImage(canvasWithWebGLContext, 0, 0);` produced a flipped image because we didn't account for different origin while serializing PaintingSurface into Gfx::Bitmap.
Visual progress on https://ciechanow.ski/curves-and-surfaces/

LibGfx+LibWeb: Specify bottom left origin for WebGL's PaintingSurface

---

Meta/WPT.sh
Services/WebDriver/main.cpp

This forwards the `debug-process` option to the browser process launched by WebDriver.
Unfortunately, the option must be formatted with a space between the option and the argument name, as `WPT.sh` doesn't understand arguments separated with an `=`.

Meta+WebDriver: Add a `--debug-process` option to `WPT.sh`

---

Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Libraries/LibWeb/DOM/AbstractRange.h
Libraries/LibWeb/DOM/Range.cpp
Libraries/LibWeb/DOM/Range.h
Libraries/LibWeb/Editing/Commands.cpp
Libraries/LibWeb/Editing/Commands.h
Libraries/LibWeb/Editing/Internal/Algorithms.cpp
Libraries/LibWeb/Editing/Internal/Algorithms.h
Libraries/LibWeb/Selection/Selection.cpp
Tests/LibWeb/Text/expected/selection-collapseToEnd.txt
Tests/LibWeb/Text/input/selection-collapseToEnd.html

No new commands, but improvements to the existing commands and algorithms. Also squashes a particularly nasty bug in `Selection::collapse_to_end/start()`.
Measured locally:
* WPT `editing`: ~369 new subtest passes
* WPT `selection`: ~10 new subtest passes

LibWeb: Assortment of Editing API related fixes and improvements

---

Libraries/LibWeb/WebAssembly/WebAssembly.cpp
Libraries/LibWeb/WebAssembly/WebAssembly.h

Previously this was proxying the call through javascript, which lead to unexpected crashes when functions returned things that js-api did not like.
This commit also adds in the spec comments and fixes a few inaccuracies that were present in the process.

LibWeb/WebAssembly: Use wasm funcaddr of exported functions on import

---

Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/CSS/CSSImportRule.cpp
Libraries/LibWeb/CSS/CSSImportRule.h
Libraries/LibWeb/CSS/Fetch.cpp
Libraries/LibWeb/CSS/Fetch.h
Libraries/LibWeb/CSS/StyleSheet.h
Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp
Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h
Libraries/LibWeb/WebAssembly/WebAssembly.cpp

Contributes to #2634.
This "fetch a style resource" algorithm is used in a few places - notably font loading. But this is what I had time for before being off work for a week. :^)
There are a few areas here left as FIXMEs, mostly related to other parts of the code needing refactoring. (*cough* CSS parser entry points *cough*) But also the whole "load event" stuff, and storing things as URLs too early, and however we're supposed to get a content-type from a Fetch Response.
But yeah, it's Fetch-ified, and nothing seems broken! :tada:

LibWeb: Use Fetch for CSS `@import` rules

---

Meta/import-wpt-test.py

Previously, the WPT importer would fail to import files with link tags that didn't have a `rel` attribute.
Found while attempting to import: https://wpt.live/xhr/formdata/constructor-submitter.html

Meta: Ensure `rel` attribute exists before querying its value

---

Libraries/LibWeb/DOM/Node.cpp
Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_tooltip.tentative.txt
Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_tooltip.txt
Tests/LibWeb/Text/input/wpt-import/accname/name/comp_tooltip.html
Tests/LibWeb/Text/input/wpt-import/accname/name/comp_tooltip.tentative.html

The https://wpt.fyi/results/accname/name/comp_tooltip.tentative.html test was recently added by moving an existing subtest out from the test at https://wpt.fyi/results/accname/name/comp_tooltip.html, and changing the test expectations to match the HTML-AAM spec requirements at https://w3c.github.io/html-aam/#img-element-accessible-name-computation.
See https://github.com/web-platform-tests/wpt/pull/49552.
So this code change updates Ladybird to match the updated WPT test expectations — and to match the existing HTML-AAM spec requirements.

LibWeb: Align accname alt-vs-title behavior w/ HTML-AAM spec & WPT tests

---

Libraries/LibWeb/Animations/KeyframeEffect.cpp
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h

When an element's `style` attribute is changed, we now mark the element for style update, but we don't do the same to all of its descendants.
Instead, we mark descendants as "needs inherited style update", which only goes through properties that were inherited from another element and updates those.
This means we don't run selector matching at all for all those descendants, drastically reducing the workload.

Add lightweight inheritance-only style updates, and use them for style attribute mutation

---

Tests/LibWeb/TestConfig.ini

Since 8e34efd4b533bf8c6aee660b0383e3eb73f3d5be, these files are detected by the runner and already skipped.

Tests/LibWeb: Remove some support files from TestConfig.ini

---

Libraries/LibCrypto/CMakeLists.txt
Libraries/LibCrypto/Curves/Ed25519.cpp
Libraries/LibCrypto/Curves/SECPxxxr1.h
Libraries/LibCrypto/Curves/X25519.cpp
Libraries/LibCrypto/Curves/X448.cpp
Libraries/LibCrypto/NumberTheory/ModularFunctions.cpp
Libraries/LibCrypto/PK/RSA.cpp
Libraries/LibCrypto/SecureRandom.cpp
Libraries/LibCrypto/SecureRandom.h
Libraries/LibTLS/Handshake.cpp
Libraries/LibTLS/HandshakeClient.cpp
Libraries/LibTLS/Record.cpp
Libraries/LibWeb/Crypto/Crypto.cpp
Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
Libraries/LibWebSocket/WebSocket.cpp
Meta/gn/secondary/Userland/Libraries/LibCrypto/BUILD.gn

See commits. Depends on #2989 to pull in OpenSSL.

LibCrypto: Add `SecureRandom` to generate cryptographically secure random values

---

Libraries/LibWeb/CSS/MediaQueryListEvent.cpp
Libraries/LibWeb/CSS/MediaQueryListEvent.h
Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/MediaQueryList-addListener-handleEvent.txt
Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/MediaQueryList-addListener-removeListener.txt
Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/MediaQueryList-extends-EventTarget.txt
Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/MediaQueryListEvent.txt

Otherwise, if not implemented, `MediaQueryListEvent::create()` would result in a call to `DOM::Event::create()`. This issue exists here: https://github.com/LadybirdBrowser/ladybird/blob/673537b26bbc239bdaf4d8026d916fea020bc1a0/Libraries/LibWeb/DOM/Document.cpp#L2865

LibWeb/CSS: Create a MediaQueryListEvent when calling MQLE::create()

---

Libraries/LibWeb/SVG/SVGElement.cpp
Libraries/LibWeb/SVG/SVGElement.h
Tests/LibWeb/Text/expected/wpt-import/svg-aam/role/roles.txt
Tests/LibWeb/Text/input/wpt-import/svg-aam/role/roles.html

This change adds support for computing default ARIA roles for (selected) SVG elements, per the requirements in the SVG Accessibility API Mappings spec at https://w3c.github.io/svg-aam/#mapping_role_table.
This only computes roles for the elements which are covered in the WPT test at https://wpt.fyi/results/svg-aam/role/roles.html — that is, the `a`, `g`, and `image` elements.

LibWeb: Compute default ARIA roles for SVG elements

---

Libraries/LibMedia/Audio/PlaybackStream.cpp
Libraries/LibMedia/Audio/PlaybackStreamAudioUnit.cpp
Libraries/LibMedia/Audio/PlaybackStreamOboe.cpp
Libraries/LibMedia/Audio/PlaybackStreamPulseAudio.cpp
Libraries/LibMedia/CMakeLists.txt
Meta/CMake/audio.cmake
Meta/CMake/pulseaudio.cmake
Services/WebContent/CMakeLists.txt
Services/WebContent/main.cpp
Tests/LibMedia/CMakeLists.txt
Tests/LibMedia/TestPlaybackStream.cpp
vcpkg.json

The goal here is to ensure we check for audio backends in a way that
makes sense. On macOS, let's just always use Audio Unit (and thus avoid
any checks for Pulse, to reduce needless/confusing build log noise). We
will also only use the Qt audio backend if no other backend was found,
rather than only checking for Pulse.

Meta: Consolidate checking for the system audio backend

---

Libraries/LibWeb/Compression/DecompressionStream.cpp
Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
Libraries/LibWeb/FileAPI/Blob.cpp
Libraries/LibWeb/FileAPI/FileReader.cpp
Libraries/LibWeb/Streams/AbstractOperations.cpp
Libraries/LibWeb/Streams/AbstractOperations.h
Libraries/LibWeb/Streams/ReadableStream.cpp
Libraries/LibWeb/Streams/ReadableStream.h
Libraries/LibWeb/Streams/TransformStream.cpp
Libraries/LibWeb/Streams/TransformStream.h

This reads a bit nicer, and follows the streams spec pattern on
performing operations on a stream outside of the streams spec.
Noticed as part of investigating improving the implementation of ReadableStreamPipeTo to make it less crashy and correct (notably, started out of making signal a `JS::Value` instead of `Optional<JS::Value>` in that AO)

LibWeb: Use helper methods on stream instances instead of directly invoking AOs

---

Libraries/LibWeb/DOM/EventHandler.idl
Libraries/LibWeb/HTML/AttributeNames.h
Libraries/LibWeb/HTML/EventNames.h
Libraries/LibWeb/HTML/GlobalEventHandlers.h
Libraries/LibWeb/HTML/WindowEventHandlers.h

LibWeb: Add missing attributes in Event Handlers

---

Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/HTML/HTMLIFrameElement.cpp

If there are no :defined pseudo-class selectors anywhere in the
document, we don't have to invalidate style at all when an element's
custom element state changes.

LibWeb: Skip unneeded style invalidation on custom element state change

---

Libraries/LibWeb/CSS/SelectorEngine.cpp
Tests/LibWeb/Text/expected/non-html-mixed-case-element-name-selector-matching.txt
Tests/LibWeb/Text/input/non-html-mixed-case-element-name-selector-matching.html

This change fixes selector matching for non-HTML elements that have mixed-case names — such as the SVG `foreignObject` element.
Otherwise, without this change, attempting to use a selector to match such an element — e.g., `document.querySelector("foreignObject")` — fails.

LibWeb: Fix selector matching for non-HTML mixed-case element names

---

Libraries/LibWeb/Fetch/Fetching/Fetching.cpp

One day we'll have an eviction strategy, too, but for now let's not allow these to get collected.

LibWeb: Protect HTTP cache entries from garbage collector

---

Services/RequestServer/ConnectionFromClient.cpp

Otherwise we may leak all kinds of things inside CURL.

RequestServer: Clean up the CURLM "multi handle" when client drops

---

Libraries/LibWeb/Fetch/Fetching/Fetching.cpp

Otherwise we will fully read from the cached response and invalidate it's stream, invalidating it for the next time it is read from. Fixes a crash when reloading linegoup.lol after two reloads.

LibWeb/Fetch: Return a cloned cached response body

---

Libraries/LibCore/EventReceiver.h

This removes a race in ImageDecoder's `make_decode_image_job()`, where the ref count of `this` is mutated from separate threads in the callbacks.
ASAN tipped me off about this:
```
/Users/kling/src/ladybird/AK/RefCounted.h:59:37: runtime error: downcast of address 0x613000000740 which does not point to an object of type 'const Core::EventReceiver'
0x613000000740: note: object has invalid vptr
00 00 00 00  77 04 00 00 00 00 00 00  00 00 00 00 be be be be  00 00 00 00 00 00 00 00  00 00 00 00
^~~~~~~~~~~~~~~~~~~~~~~
invalid vptr
#0 0x10010376c in AK::RefCounted<Core::EventReceiver>::unref() const RefCounted.h:59
#1 0x100133a6c in AK::ErrorOr<AK::NonnullRefPtr<Core::EventReceiver>, AK::Error>::~ErrorOr() Error.h:129
#2 0x100133800 in Core::Promise<AK::NonnullRefPtr<Core::EventReceiver>, …
```

LibCore: Make EventReceiver ref counting use atomics

---

Libraries/LibJS/Parser.cpp
Libraries/LibJS/Tests/object-basic.js

This fixes JS exceptions thrown on https://locals.com/site/discover and allows the page to load.
No test262 or test262-parser-tests diff.
Before:
After:

LibJS: A couple of parser fixes related to `async` functions as object properties

---

Libraries/LibWeb/DOM/Node.cpp
Tests/LibWeb/Text/expected/wpt-import/accname/name/comp_host_language_label.txt
Tests/LibWeb/Text/input/wpt-import/accname/name/comp_host_language_label.html

This change ensures that when an accessible name is computed from multiple labels, the parts computed from each label are separated by spaces. Otherwise, without this change, the parts are run together in the accessible name, with no space in between.

LibWeb: Space-separate parts of multi-label accessible names

---

Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/HTML/CustomElements/CustomElementDefinition.cpp
Libraries/LibWeb/HTML/CustomElements/CustomElementDefinition.h
Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp

1. Stop using `GC::Root` in member variables, since that usually creates a realm leak.
2. Stop putting `OrderedHashMap<FlyString, GC::Ptr>` on the stack while setting these up, since that won't protect the objects from GC.

LibWeb: Make CustomElementDefinition relationship with GC more sane

---

Libraries/LibWeb/Selection/Selection.cpp

Copies https://github.com/LadybirdBrowser/ladybird/pull/1767
I rebased on master and rebaselined a failing test 
P. S. Reverted the test
CC @kalenikaliaksandr as the one actually writing the final code and @gmta as the one who knows the most about Selection API

LibWeb: Selection::getRangeAt handle focus and anchor

---

Libraries/LibWeb/DOM/Text.cpp
Libraries/LibWeb/DOM/Text.h

This is a leftover from an earlier implementation of text input.

LibWeb: Remove unused pointer from DOM::Text to its "owner" element

---

Libraries/LibWeb/ARIA/AriaRoles.json
Libraries/LibWeb/ARIA/RoleType.cpp
Libraries/LibWeb/ARIA/Roles.cpp
Libraries/LibWeb/ARIA/Roles.h
Libraries/LibWeb/SVG/SVGElement.cpp
Tests/LibWeb/Text/expected/wpt-import/graphics-aria/graphics-roles.txt
Tests/LibWeb/Text/expected/wpt-import/svg-aam/role/roles-generic.txt
Tests/LibWeb/Text/input/wpt-import/graphics-aria/graphics-roles.html
Tests/LibWeb/Text/input/wpt-import/svg-aam/role/roles-generic.html

This change includes two commits:
- 86c439fb478dfbf23c545d8c60f5864548b6df88 Add support for the `graphics-document`, `graphics-object`, and `graphics-symbol` roles from the WAI-ARIA Graphics Module spec at https://w3c.github.io/graphics-aria/#role_definitions.
- 6d810196608a8dc42a2b6df0702b4a7d82c1052e Compute roles for SVG elements that default to the `graphics-symbol` role, and compute the role for the SVG `foreignObject` element.

LibWeb: Add support for ARIA Graphics roles, and compute roles for SVG graphics-symbol elements and foreignObject

---

Libraries/LibWeb/Geometry/DOMMatrixReadOnly.cpp
Tests/LibWeb/Text/expected/wpt-import/css/geometry/DOMMatrix-001.txt
Tests/LibWeb/Text/input/wpt-import/css/geometry/DOMMatrix-001.html
Tests/LibWeb/Text/input/wpt-import/css/geometry/support/dommatrix-test-util.js

This implementation leads to passing more WPT tests. Relevant test imported in this PR.

LibWeb/Geometry: Implement "other than none" keyword check in DOMMatrix init

---

Libraries/LibWeb/HTML/Location.cpp
Tests/LibWeb/Text/expected/wpt-import/html/browsers/browsing-the-web/history-traversal/hash-empty-string.txt
Tests/LibWeb/Text/input/wpt-import/html/browsers/browsing-the-web/history-traversal/hash-empty-string.html

This update fixes all tests in https://wpt.live/html/browsers/browsing-the-web/history-traversal/hash-empty-string.html
Note: I was unable to import the test using the WPT import script due to an issue that resulted in an empty expected text file.

LibWeb/HTML: Fix URL fragment comparison triggering unwanted events

---

Libraries/LibWeb/ARIA/Roles.cpp
Libraries/LibWeb/ARIA/Roles.h

If we use the correct string for "switch", the special handling is not necessary after 8961d5d2ce32876c42449256964e742df582a889.

LibWeb: Remove special handling for the ARIA "switch" role

---

Libraries/LibWeb/HTML/PopoverInvokerElement.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp

This change updates the bindings generator for the case defined at https://html.spec.whatwg.org/#reflecting-content-attributes-in-idl-attributes:element; that is, the case _“If a reflected IDL attribute has the type T?, where T is either Element or an interface that inherits from Element”_.
The change “normalizes” the generator behavior for that case — such that the generated code expects a getter with a name of the form used in other cases; e.g., `popover_target_element()`.
Otherwise, without this change, the generator expects a name of the form `get_popover_target_element()` for that case.

LibWeb: Normalize getter name for reflected “Element?” IDL types

---

Meta/WPT.sh

Previously, running `WPT.sh compare foo.log` would fail because the log file name was included in the list of test paths.

Meta: Construct test list after parsing other arguments in `WPT.sh`

---

Meta/import-wpt-test.py

Previously attempting to import files with a `src` that had a leading `/` would fail.
Found while trying to import: https://wpt.live/wasm/jsapi/global/constructor.any.html
CC: @ADKaster

Meta: Strip extraneous slashes from file paths in the WPT importer

---

Tests/LibWeb/TestConfig.ini
UI/Headless/Test.cpp

With this change, we now ignore files imported from WPT if they are in the root `common` directory, or any directory named `resources`. This matches the behavior of the WPT test harness.

Headless ignore wpt support files

---

Meta/WPT.sh

The output of `WPT.sh list-tests` includes test variants, which vary only by their query string. Since we don't care about this when importing tests, ignore any query strings and ensure duplicates are removed from the given test paths.
I've also included a commit to ensure we don't swallow the output of the python importer script.
Fixes: #2976

Meta: Strip query string from WPT test variants before importing them

---

Libraries/LibWeb/HTML/FormAssociatedElement.cpp
Libraries/LibWeb/HTML/FormAssociatedElement.h
Libraries/LibWeb/HTML/HTMLInputElement.idl
Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
Libraries/LibWeb/Painting/PaintableFragment.cpp
Tests/LibWeb/Text/expected/HTMLInputElement-edit-value.txt
Tests/LibWeb/Text/input/HTMLInputElement-edit-value.html

Previously, the`HTMLInputElement.selectinStart` and `HTMLInputElement.selectionEnd` IDL setters, and the `setRangeText()` IDL method were used when updating an input's value on keyboard input. These methods can't be used for this purpose, since selection doesn't apply to email type inputs. Therefore, this change introduces internal-use only methods that don't check whether selection applies to the given input.
Fixes #3054

LibWeb: Allow keyboard input to alter email inputs

---

Libraries/LibWeb/DOM/Document.cpp
Tests/LibWeb/Text/expected/wpt-import/css/css-animations/animationevent-types.txt
Tests/LibWeb/Text/input/wpt-import/css/css-animations/animationevent-types.html

This makes all three subtests from this test to pass:
- css/css-animations/animationevent-types.html

LibWeb/DOM: Convert elapsedTime to seconds when firing AnimationEvents

---

Libraries/LibWeb/CSS/Parser/Parser.cpp
Tests/LibWeb/Text/expected/background-style-declaration-cssText-crash.txt
Tests/LibWeb/Text/input/background-style-declaration-cssText-crash.html

Fixes a crash when loading https://www.lottielab.com/.
My assumption in `ShorthandStyleValue::to_string` that `background-position` would always be a shorthand was false, because the parser outputs a `PositionStyleValue` which is exposed by `document.styleSheets[0].cssRules[0].cssText`.
An alternative solution would be to change the parser to output a `ShorthandStyleValue` for `background-position`, but I'm not convinced it's any cleaner.

LibWeb: Handle non-shorthand background position when serializing

---

Libraries/LibWeb/CSS/CSSNumericType.cpp
Tests/LibWeb/Ref/expected/wpt-import/css/css-values/reference/all-green.html
Tests/LibWeb/Ref/input/wpt-import/css/css-values/max-unitless-zero-invalid.html

This is a third attempt at fixing #3050 (see also #3069 and #3080).
Our code was incorrectly counting null "percentage" values as non-zero, fixing this is sufficient to prevent the crash in all cases without needing to introduce ad-hoc behaviour. This is sufficient because a present-and-non-zero "percentage" exponent and a non-null percent hint are mutually exclusive.
Turns out this wasn't a spec bug, just a boring ladybug.

LibWeb: Check if types have a present and nonzero percentage value

---

Libraries/LibWeb/ARIA/ARIAMixin.idl
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/wpt-import/html/dom/aria-element-reflection.txt
Tests/LibWeb/Text/input/wpt-import/html/dom/aria-element-reflection.html

This change makes updates to support the `ariaActiveDescendantElement` IDL attribute, including changes to the  `IDLGenerators.cpp` code to handle reflected non-`HTML::AttributeNames` content-attribute names, and to handle such names as-is — including names with dashes — and to make it handle the _“If reflectedTarget's explicitly set attr-element is a descendant of any of element's shadow-including ancestors”_ step from the _“If a reflected IDL attribute has the type T?, where T is either Element or an interface that inherits from Element”_ case in the HTML spec at https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflecting-content-attributes-in-idl-attributes:explicitly-set-attr-element
This change gets up passing all the `ariaActiveDescendantElement`-related subtests in …

LibWeb: Support the ariaActiveDescendantElement IDL attribute

---

Libraries/LibWeb/CSS/ComputedProperties.cpp
Libraries/LibWeb/CSS/ComputedProperties.h
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/Layout/ImageBox.cpp
Libraries/LibWeb/Painting/ImagePaintable.cpp
Libraries/LibWeb/Painting/PaintableBox.cpp
Libraries/LibWeb/Platform/FontPlugin.h
Libraries/LibWebView/Plugins/FontPlugin.cpp
Libraries/LibWebView/Plugins/FontPlugin.h
Tests/LibWeb/Layout/expected/non-existing-font-family.txt
Tests/LibWeb/Layout/input/non-existing-font-family.html

This change fixes a bug where, if a non-existent font family is specified in
CSS, whitespaces would be rendered using the emoji font, while letters
would use the default font. This issue occurred because the font was
resolved separately for each code point. Since the emoji font was listed
before the default font, it was chosen for whitespace characters due to
its inclusion of whitespace glyphs (at least in the Apple Color Emoji
font on macOS). This change resolves the issue by placing the default
font before the emoji font in the list.
This change fixes the same issue as https://github.com/LadybirdBrowser/ladybird/pull/2955 but I also made default font respect specified size and added a comment to clarify why default font has to be both inserted in font list and used as a last resort …

LibWeb: Insert default font in font list before emoji font

---

Libraries/LibJS/Bytecode/Interpreter.cpp
Libraries/LibJS/Runtime/AbstractOperations.cpp
Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
Libraries/LibJS/Runtime/AsyncGenerator.cpp
Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Libraries/LibJS/Runtime/GeneratorObject.cpp
Libraries/LibJS/Runtime/NativeFunction.cpp
Libraries/LibJS/SourceTextModule.cpp
Libraries/LibJS/SyntheticModule.cpp

From what I understand, the suspension steps are not required now, or in the future for our implementation, or any other. The intent is already implemented in the spec pushing on another execution context to the stack and leaving the running execution context as-is.
The resume steps are a slightly different story as there is some subtle behavior which the spec is trying to convey where some custom logic may need to be done when one execution context changes from one to another. It may be worth implementing those steps at a later point in time so that this behavior is a bit easier to follow in those cases.
To make the situation more confusing - from what I can gather from the spec, not all cases that the spec mentions resume actually means anything normative. Resume is only _actually_ …

LibJS: Remove unneeded FIXMEs for suspending an execution context

---

Libraries/LibJS/Module.cpp

It turns out that the FIXME which we had left unimplemented is actually a spec bug.
Noticed during my on-and-off attempts of debugging crashes to do with module loading.

LibJS: Adjust FIXME for an incorrect assertion in GetModuleNamespace

---

AK/Time.cpp
AK/Windows.h
Libraries/LibCore/CMakeLists.txt
Libraries/LibCore/EventLoopImplementationWindows.cpp

Use <AK/windows.h> instead of windows.h/winsock2.h to avoid timeval-related errors.

AK: Simplify usage of windows.h and winsock2.h

---

Libraries/LibGC/Heap.cpp
Libraries/LibGC/Heap.h
Libraries/LibGC/RootVector.cpp

In #3048 `MarkedVector` was renamed to `RootVector`, but some related symbols were missed. This commit corrects this.

LibGC: Rename remaining occurrence of marked vector

---

Libraries/LibWeb/FileAPI/FileReader.cpp
Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Libraries/LibWeb/XHR/XMLHttpRequest.cpp

This a requirement from the ECMA-262 spec.

LibWeb/HTML: Assert microtasks invoked on empty execution context stack

---

Libraries/LibWeb/CSS/StyleComputer.cpp

Some websites (Reddit, for example) create lots of temporary documents for fragment parsing. Before this change, we had to build a rule cache for these documents just to determine whether there are :has, :defined, or attribute selectors, while it should be safe to simply return `false` right away.

LibWeb/CSS: Skip build of rule cache for inactive documents

---

Libraries/LibWeb/WebAudio/AudioBufferSourceNode.cpp
Libraries/LibWeb/WebAudio/AudioBufferSourceNode.h
Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-channels.txt
Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-channels.html

This fixes the remaining subtests in http://wpt.live/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-channels.html, which has now been imported.

LibWeb: Flesh out AudioBufferSourceNode buffer setter steps

---

Tests/LibWeb/Text/input/include.js
Tests/LibWeb/Text/input/wpt-import/resources/testharness.js

Previously, some tests would fail to display any output if the internals object was not exposed, which can hinder the ability to view tests in browsers other than Ladybird.
Tests which make use of the HTTP echo server will now complain with a descriptive error message if the internals object is not exposed.

Tests: Check internals object is exposed before use

---

UI/Qt/BrowserWindow.cpp
UI/Qt/InspectorWidget.cpp
UI/Qt/InspectorWidget.h
UI/Qt/Tab.cpp
UI/Qt/Tab.h

This brings keyboard shortcuts for the inspector up with common convention in FF and Chrome: Ctrl+Shift+C now also opens the inspector, and F12, Ctrl+W, and Ctrl+Shift+I now close the inspector when the inspector window is focused.
Resolves #972

Inspector+UI: Close inspector with shortcuts

---

Libraries/LibCore/DateTime.h

So we don't have to dig in the parser's code

LibWeb: Add documentation to the date parser format

---

Libraries/LibWeb/Infra/Strings.cpp

I pre-emptively [suggested](https://github.com/LadybirdBrowser/ladybird/pull/2890#issuecomment-2540606951) this VERIFY could be uncommented in #2890.
We're still doing something wrong to let non-latin-1 codepoints through, causing this check to fail when loading an article on https://cnn.com/ (as showcased in the December update video, oops!).

LibWeb: Revert addition of VERIFY call to isomorphic-decode

---

Libraries/LibJS/Runtime/DateConstructor.cpp
Libraries/LibJS/Tests/builtins/Date/Date.parse.js

This was getting spammed in the console by a website in the wild.
Unfortunately I've forgotten what website I was browsing at the time😅

LibJS: Parse dates like "2025-01-02 14:00:00+0000"

---

Libraries/LibWeb/WebAudio/OscillatorNode.cpp
Libraries/LibWeb/WebAudio/OscillatorNode.h
Libraries/LibWeb/WebAudio/OscillatorNode.idl
Tests/LibWeb/Text/expected/WebAudio/OscillatorNode.txt
Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-oscillatornode-interface/ctor-oscillator.txt
Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-oscillatornode-interface/ctor-oscillator.html

This PR ensures that the `OscillatorNode` constructor is initialized with the correct default options, implements the `detune` attribute and the `setPeriodicWave()` method.
This fixes all subtests in: http://wpt.live/webaudio/the-audio-api/the-oscillatornode-interface/ctor-oscillator.html

LibWeb: Make OscillatorNode constructor spec-compliant

---

Libraries/LibWeb/HTML/HTMLOptionElement.cpp
Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Libraries/LibWeb/HTML/HTMLSelectElement.h
Tests/LibWeb/Ref/expected/select-option-use-label.html
Tests/LibWeb/Ref/input/select-option-use-label.html

This is just #2384 again, since the bot closed it and it seems impossible to re-open without mucking around with the git history.
Relevant spec:
https://html.spec.whatwg.org/#the-select-element-2
"An [option](https://html.spec.whatwg.org/#the-option-element) element is expected to be rendered by displaying the element's [label](https://html.spec.whatwg.org/#concept-option-label), indented under its [optgroup](https://html.spec.whatwg.org/#the-optgroup-element) element if it has one."
I'm also opening a bug report for the ``FIXME:`` I've added along the way.

LibWeb: Make select element use option's label, not text content

---

Libraries/LibWeb/Layout/AudioBox.cpp
Libraries/LibWeb/Layout/AudioBox.h
Libraries/LibWeb/Painting/AudioPaintable.cpp
Tests/LibWeb/Layout/expected/hide-audio-based-on-controls.txt
Tests/LibWeb/Layout/input/hide-audio-based-on-controls.html

When an audio element has no controls attribute, it should not render at all and take up no space.
Fixes a layout issue on my friend's website :)

LibWeb: Hide audio element when controls is not set

---

Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp

This gets rid of some FIXMEs related to viewport proximity and relevancy to the user in the [update the rendering](https://html.spec.whatwg.org/#update-the-rendering) algorithm.
I know there is no tests, but I tried some of the relevant WPT tests for the new sections and none of them are passing yet so I assume there is other code missing elsewhere that would need to actually make use of the element's proximity to the viewport. (beyond just setting it in this one place.)
So I don't think there is any sensible tests that can be written for these two functions on their own.

LibWeb: Implement some viewport proximity features

---

Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h

Main difference is that a chunk of the "clone a node" steps are pulled out into a "clone a single node" algorithm.
Reflects these spec PRs:
https://github.com/whatwg/dom/pull/1332
https://github.com/whatwg/dom/pull/1334
Though this code is quite old so there may also be older spec changes included here.

LibWeb/DOM: Update node cloning to latest spec

---

Libraries/LibWeb/CSS/FontFace.cpp
Libraries/LibWeb/CSS/FontFace.h

I don't see a reason to have both `FontFace::load()` and `FontFace::load_font_source()` when they do essentially the same thing and the spec seems to suggest that if the browser were to arbitrarily call into this on its own, it should be executing all the steps anyways.

LibWeb: Remove unneeded spec deviation from font loading

---

Libraries/LibWeb/DOM/Element.cpp

The "strictly split" infra algorithm feels like an inefficient way of doing basically what our existing split() does, except working with code points instead of bytes. It didn't seem worth it to implement now.

LibWeb/DOM: Update validate_and_extract to latest spec

---

Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
Tests/LibWeb/Text/expected/css/singular-percentage-calc-crash.txt
Tests/LibWeb/Text/input/css/singular-percentage-calc-crash.html

Fixes #3006 , (relates to) #648
From some analysis, it seems as if this issue only occurs with a only percentages in a `calc`.
- `calc(10%)` crashes.
- `calc(10% + 10%)` crashes.
- `calc(10% + 0px)` doesn't crash.
- `calc(10vw)` doesn't crash.
The `resolve` function returns a `Length` in the general case, but returns a `Percentage` if only percentages are provided.
As a sanity check, I looked at the code before it was changed (commit before change was [here](https://github.com/LadybirdBrowser/ladybird/commit/8d40550478b213bceb1b95f44197df5b8e02fb8a)), and it only handled the case of percentages and lengths, as I do in this commit.
The old code being:
```cpp
Optional<Length> CalculatedStyleValue::resolve_length_percentage(Length::ResolutionContext const& resolution_context, Length const& …
```

LibWeb/CSS: Fix crash resolving `calc` with only percentages

---

AK/BitmapView.h
Libraries/LibWeb/CSS/ComputedProperties.h
Libraries/LibWeb/CSS/Selector.cpp
Libraries/LibWeb/CSS/Selector.h
Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/CSS/SelectorEngine.h
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/ParentNode.cpp

Instead of recalculating styles for all nodes in the common ancestor of the new and old hovered nodes' subtrees, this change introduces the following approach:
- While calculating ComputedProperties, a flag is saved if any rule applied to an element is affected by the hover state during the execution of SelectorEngine::matches().
- When the hovered element changes, styles are marked for recalculation only if the flag saved in ComputedProperties indicates that the element could be affected by the hover state.

LibWeb: Optimize :hover style invalidation

---

Libraries/LibWeb/Animations/KeyframeEffect.cpp

It is possible to skip inherited style recalculation for children if parent's recalculation does not cause any changes.
Improves performance on Github where we could avoid dozens of inherited style calculations that do not produce any visible changes.

LibWeb: Optimize inherited style update caused by animation

---

Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h
Libraries/LibWeb/HTML/HTMLOptionElement.cpp

When setting the textContent of an element with no children to null or the empty string, nothing happens. Even so, we were still invalidating style, layout and collections, causing pointless churn.
Skipping invalidation in this case also revealed that we were missing invalidation when changing the selected state of HTMLOptionElement. This was all caught by existing tests already in-tree. :^)

LibWeb: Avoid invalidation on .textContent setter no-op

---

Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLOrSVGElement.cpp
Libraries/LibWeb/HTML/HTMLScriptElement.cpp
Libraries/LibWeb/HTML/HTMLScriptElement.h
Libraries/LibWeb/HTML/HTMLTemplateElement.cpp
Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp

The spec changed for these, but I also noticed we weren't calling the base method, and that HTMLScriptElement didn't have one at all. So that's all sorted.

LibWeb/HTML: Update/add "cloning steps" algorithms

---

Libraries/LibWeb/DOM/SelectionchangeEventDispatching.h

This was a typo in the spec itself, which has since been fixed.

LibWeb: Fix `selectionchange` typo

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h

With this change we skip all :hover selectors that don't belong to a "style scope" (document or shadow root) of old/new hovered node.

LibWeb: Optimize hover style invalidation for shadow trees

---

Libraries/LibWeb/FileAPI/Blob.cpp

This is indeed a spec bug, and has been raised upstream to the FileAPI spec.

LibWeb/FileAPI: Update FIXME to point to spec bug

---

Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.h

Fixes the default button text on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit

LibWeb: Provide default text for Reset and Submit buttons

---

Libraries/LibWeb/CSS/CSSTransition.cpp
Tests/LibWeb/Text/expected/wpt-import/css/css-transitions/CSSTransition-effect.tentative.txt

Fixes a crash on https://neal.fun/ (and another website I forgot (and a single WPT subtest ??)).
It's difficult to consistently reproduce the crash in a test since it seems to depend on precise timing when interrupting a transition.

LibWeb: Avoid crash from zero-duration transitions

---

Libraries/LibWeb/HTML/Parser/HTMLParser.cpp

This PR adds spec links to all HTML parser insertion mode handling methods.

LibWeb: Add missing spec links to HTML parser

---

Libraries/LibWeb/CSS/CSSNumericType.cpp
Libraries/LibWeb/CSS/CSSNumericType.h
Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
Libraries/LibWeb/CSS/Parser/Parser.cpp
Libraries/LibWeb/CSS/Parser/Parser.h
Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h

The main purpose of this is to split apart how we parse `calc()` and dimensions, so that we determine which property we're parsing for *before* parsing the value, instead of after. This is necessary for knowing what type percentages in `calc()` should resolve to, when in a shorthand property - because it depends which longhand we're parsing the `calc()` for.
`parse_dimension[_value]()` is the main culprit there, and I generally think it was a mistake. It made sense back before we started parsing types intentionally (as in, "I want a length, so try parsing a length") but now that we do that, it's unnecessary to try parsing a dimension token as a `<resolution>` when we only care about `<angle>`s, for example. I've removed its use from everywhere except for `parse_grid_size()` which needs a …

LibWeb/CSS: Preparation for calc() contexts

---

Libraries/LibWeb/CSS/ComputedProperties.cpp
Libraries/LibWeb/CSS/ComputedProperties.h
Libraries/LibWeb/CSS/ComputedValues.h
Libraries/LibWeb/CSS/Enums.json
Libraries/LibWeb/CSS/Properties.json
Libraries/LibWeb/Layout/Node.cpp
Libraries/LibWeb/Layout/Node.h
Libraries/LibWeb/Page/EventHandler.cpp
Libraries/LibWeb/Painting/ViewportPaintable.cpp
Tests/LibWeb/Text/expected/wpt-import/css/css-ui/parsing/user-select-valid.txt
Tests/LibWeb/Text/input/wpt-import/css/css-ui/parsing/user-select-valid.html

This implements all values of user-select.
Some things to note:
1. There is no tests yet. It is 2am and I'm just opening this PR for now so that the code can at least be looked at. I will add tests tomorrow.
2. I've modified the steps in `ViewportPaintable::recompute_selection_states()` to support cases where the end container of the range includes the start container, as this is now a possibility due to how `user-select: all` and `user-select: contain` have been implemented. (Example for `contain`: If the user's selection overshoots the end of the `contain` element, it is clamped back into said element by making that element the end container of the selection and setting the end index to its length.)
3. Elements with `user-select: none` are included in a selection if it spans across the …

LibWeb: Implement user-select

---

Libraries/LibJS/Runtime/DateConstructor.cpp
Libraries/LibJS/Tests/builtins/Date/Date.parse.js

Seen on [https://amazon.fr](https://amazon.fr).

LibJS: Support date strings of the form "Thu, 09 Jan 2025 23:00:00"

---

Libraries/LibWeb/WebAudio/BiquadFilterNode.cpp
Libraries/LibWeb/WebAudio/BiquadFilterNode.h
Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-audioparam-interface/audioparam-nominal-range.txt
Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-audioparam-interface/audioparam-nominal-range.html

This increases the number of subtest passes in: http://wpt.live/webaudio/the-audio-api/the-audioparam-interface/audioparam-nominal-range.html

LibWeb: Use correct ranges for `BiquadFilterNode` parameters

---

AK/GenericShorthands.h
Meta/gn/secondary/Tests/AK/BUILD.gn
Tests/AK/CMakeLists.txt
Tests/AK/TestGenericShorthands.cpp

This was mentioned [in Discord](https://discord.com/channels/1247070541085671459/1247090154141646871/1319698940001648650):
> here's an observation: I think first_is_one_of() will copy all the arguments. that doesn't seem optimal! (same for that entire family of helpers)
With that in mind, this PR:
1. adds tests for AK/GenericShorthands which had none so far
2. optimizes the functions in AK/GenericShorthands by switching from pass-by-value to forwarding references

AK: Optimize performance in GenericShorthands by using forwarding references

---

Libraries/LibWeb/DOM/Range.cpp

This accurately reflects the spec it's implementing. This algorithm is used in 5 spots in the spec but the old buggy behavior was never triggered:
* In both ::extract() and ::clone_the_contents(), invocations to this method are guarded by a check to see if the start node is the inclusive ancestor of the end node, or vice versa - effectively resulting in the inequality checks to be accidentally correct.
* In ::surround_contents(), we forego the usage of this algorithm as stated in the spec, and instead use a correct and more optimized version that simply compares the start and end nodes.
A lot of words to say: no functional changes :^)

LibWeb: Update implementation of Range::partially_contains_node()

---

Libraries/LibWeb/ARIA/ARIAMixin.cpp
Libraries/LibWeb/ARIA/ARIAMixin.h
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h
Libraries/LibWeb/HTML/HTMLElement.cpp
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/fallback-roles.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/form-roles.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/grid-roles.tentative.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/list-roles.tentative.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/listbox-roles.tentative.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/menu-roles.tentative.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/region-roles.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/role_none_conflict_resolution.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/tab-roles.tentative.txt
Tests/LibWeb/Text/expected/wpt-import/wai-aria/role/tree-roles.tentative.txt
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/fallback-roles.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/form-roles.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/grid-roles.tentative.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/list-roles.tentative.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/listbox-roles.tentative.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/menu-roles.tentative.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/region-roles.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/role_none_conflict_resolution.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/tab-roles.tentative.html
Tests/LibWeb/Text/input/wpt-import/wai-aria/role/tree-roles.tentative.html

This change includes six commits:
- 02d18109a1621869ba5eca0070c158d493f066b0 LibWeb: Ignore “orphaned” ARIA roles
- fe2408c44b324ca69c3070cf60b52c7c19e4660d LibWeb: Ignore name-required landmark roles which lack accessible names
- c8f4f7fe33a27a4a02256ed263db44df63c896f1 LibWeb: Ignore role=none for focusable & has-global-ARIA-attribute cases
- d1cbc22cc08276c7c6d48e1367467d6ecec26d78 LibWeb: Return true for is_focusable() elements with non-null tabindex
- 42d1663e11bf00a27de34c62f8d53be9f16c3221 LibWeb: Allow accessible-name computation to skip role-attribute lookup
- f571b7c9d4722ac4717a052c851e05cc1d52ecf2 LibWeb: Add a to_element function to ARIAMixin

LibWeb: Ignore: “orphaned” ARIA roles, landmark roles which lack required names, role=none for focusable or has-global-ARIA-attribute elements

---

Libraries/LibThreading/Mutex.h
Libraries/LibWeb/HTML/Scripting/TemporaryExecutionContext.h

Inspired by #3197. 
Adding `[[nodiscard]]` makes not naming these objects a compile error.

LibWeb+LibThreading: Make MutexLocker and TemporaryExecutionContext [[nodiscard]]

---

Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp

Previously, <a> elements were frequently invalidated because `set_the_url()` was called by `reinitialize_url()`, which is a preparation step in every HTMLHyperlinkElementUtils function. As a result, styles were unnecessarily invalidated each time any of these functions were invoked without changing the URL.

LibWeb: Invalidate style if url changed in HTMLHyperlinkElementUtils

---

Libraries/LibWeb/Animations/KeyframeEffect.cpp

Makes some pages on Github faster as previously we had to update animation for elements in not connected shadow trees.

LibWeb: Skip keyframe animation update if target element isn't connected

---

Libraries/LibWeb/DOM/AdoptedStyleSheets.cpp
Libraries/LibWeb/WebIDL/ObservableArray.cpp
Libraries/LibWeb/WebIDL/ObservableArray.h

Add missing unloading step that we do for regular style sheets but mistakenly missed for adopted style sheets.

LibWeb: Unload fonts when adopted style sheet is removed

---

Libraries/LibWeb/WebAudio/AudioBufferSourceNode.cpp
Libraries/LibWeb/WebAudio/AudioScheduledSourceNode.cpp
Libraries/LibWeb/WebAudio/AudioScheduledSourceNode.h
Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-basic.txt
Tests/LibWeb/Text/input/wpt-import/webaudio/resources/start-stop-exceptions.js
Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-basic.html

This adds parameter validation to all `AudioScheduledSourceNode` `start()` and `stop()` methods.
This fixes all subtests in: http://wpt.live/webaudio/the-audio-api/the-audiobuffersourcenode-interface/audiobuffersource-basic.html

LibWeb: Validate parameters for source node start() and stop() methods

---

Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
Tests/LibWeb/Text/expected/wpt-import/html/syntax/parsing/html5lib_comments01.txt

This fixes the 1 remaining failing subtest in http://wpt.live/html/syntax/parsing/html5lib_comments01.html

LibWeb: Emit comment token for unterminated bogus comments on EOF

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/DOM/DocumentLoading.cpp
Libraries/LibWeb/DOM/DocumentLoading.h
Libraries/LibWeb/DOM/Node.h
Libraries/LibWeb/HTML/HTMLIFrameElement.h
Libraries/LibWeb/HTML/Navigable.cpp
Libraries/LibWeb/HTML/Navigable.h
Libraries/LibWeb/HTML/NavigationParams.h
Libraries/LibWeb/HTML/TraversableNavigable.cpp
Libraries/LibWeb/HTML/TraversableNavigable.h

This is the second part of implementing the changes in https://github.com/whatwg/html/pull/10818
I noticed while doing that, that the spec numbers weren't lining up. So I then updated the spec steps, and filled in a couple of FIXMEs we had there.
For the first time in over a month, I have zero spec changes in my GitHub notifications. :tada:

LibWeb: Bring navigables code closer to spec

---

Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Libraries/LibWeb/NavigationTiming/PerformanceTiming.cpp
Libraries/LibWeb/NavigationTiming/PerformanceTiming.h
Tests/LibWeb/Text/expected/wpt-import/user-timing/measure_associated_with_navigation_timing.txt
Tests/LibWeb/Text/input/wpt-import/common/performance-timeline-utils.js
Tests/LibWeb/Text/input/wpt-import/user-timing/measure_associated_with_navigation_timing.html
Tests/LibWeb/Text/input/wpt-import/user-timing/resources/webperftestharness.js
Tests/LibWeb/Text/input/wpt-import/user-timing/resources/webperftestharnessextension.js

Previously, the PerformanceTiming interface returned 0 for all properties.
We now also wait until `DocumentReadyState` is set to complete before detaching the HTML parser from the document. This fixes an issue where the DOM complete time was never being set.
This fixes all but 1 subtest in:  http://wpt.live/user-timing/measure_associated_with_navigation_timing.html, which previously threw an unexpected exception.

LibWeb: Use DocumentLoadTimingInfo values in PerformanceTiming interface

---

Libraries/LibURL/Parser.cpp
Libraries/LibURL/Parser.h
Libraries/LibURL/URL.cpp
Libraries/LibWeb/CSS/Fetch.cpp
Libraries/LibWeb/DOMURL/DOMURL.cpp
Libraries/LibWeb/HTML/Location.cpp
Libraries/LibWeb/HTML/NavigatorBeacon.cpp
Tests/LibURL/TestURL.cpp
Utilities/xml.cpp

URL::basic_parse has a subtle bug where the resulting URL is not set to valid when StateOveride is provided and the URL parser early returns a valid URL.
This has not surfaced as a problem so far, as the only users of the state override API provide an already valid URL buffer and also ignore the result of basic parsing with a state override.
However, this bug surfaces implementing the URL pattern spec, which as part of URL canonicalization:
* Provides a dummy (invalid!) URL record
* Basic URL parses that URL with state override
* Checks the result of the URL parser to validate the URL
While we could set URL validity on every early return of the URL parser during state override, it has been a long standing FIXME around the code to try and remove the awkward validity state of the URL class. …

LibURL+LibWeb: Make URL::basic_parse return an Optional<URL>

---

Libraries/LibWeb/Bindings/MainThreadVM.cpp
Libraries/LibWeb/Bindings/MainThreadVM.h
Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/MutationObserver.cpp
Libraries/LibWeb/Forward.h
Libraries/LibWeb/HTML/CustomElements/CustomElementReactionsStack.h
Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Libraries/LibWeb/HTML/Scripting/Agent.cpp
Libraries/LibWeb/HTML/Scripting/Agent.h
Libraries/LibWeb/HTML/Scripting/Environments.cpp
Libraries/LibWeb/HTML/Scripting/Environments.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp

This makes it more convenient to use the 'relvant agent' concept,
instead of the awkward dynamic casts we needed to do for every call
site.
mutation_observers is also changed to hold a GC::Root instead of raw
GC::Ptr. Somehow this was not causing problems before, but trips up CI
after these changes. (was never getting visited)

LibWeb: Return a representation of an 'Agent' in 'relevant agent'

---

Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWebView/InspectorClient.cpp

Only HTML elements are case-insensitive.
This fixes things like SVG's `<foreignObject>` being displayed as "&lt;foreignobject&gt;":

LibWebView: Fix capitalization in devtools

---

Libraries/LibWeb/DOM/Attr.cpp
Libraries/LibWeb/DOM/Attr.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h
Libraries/LibWeb/HTML/HTMLElement.cpp
Libraries/LibWeb/HTML/HTMLElement.h
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.h
Libraries/LibWeb/HTML/HTMLOrSVGElement.cpp
Libraries/LibWeb/HTML/HTMLOrSVGElement.h
Libraries/LibWeb/HTML/HTMLScriptElement.cpp
Libraries/LibWeb/HTML/HTMLScriptElement.h
Libraries/LibWeb/HTML/HTMLTemplateElement.cpp
Libraries/LibWeb/HTML/HTMLTemplateElement.h
Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Libraries/LibWeb/MathML/MathMLElement.cpp
Libraries/LibWeb/MathML/MathMLElement.h
Libraries/LibWeb/SVG/SVGElement.cpp
Libraries/LibWeb/SVG/SVGElement.h
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Node-cloneNode-svg.txt
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Node-cloneNode-svg.html

Previously, the namespace of the attributes on the cloned element was not being set.
Fixes: http://wpt.live/dom/nodes/Node-cloneNode-svg.html

LibWeb: Clone all attribute properties when cloning a single node

---

Libraries/LibWeb/DOM/ElementFactory.cpp

This takes care of the spec assert that used to be a FIXME.

LibWeb: Verify element namespace in DOM::create_element()

---

Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.cpp
Libraries/LibWeb/HTML/CustomElements/CustomElementRegistry.h
Libraries/LibWeb/HTML/Window.cpp
Libraries/LibWeb/HTML/Window.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp

This can only ever be undefined, and no other JS value, so it makes more sense to use Empty here instead.
Fixes 1 of ~5 issues seen in the URLPattern IDL, though this one is the only one which hasn't been causing compile errors and was more just of a FIXME.

LibWeb/Bindings: Generate undefined in a union as 'Empty'

---

Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
Tests/LibWeb/Text/expected/HTML/WindowOrWorkerGlobalScope-reportError.txt
Tests/LibWeb/Text/expected/wpt-import/html/webappapis/scripting/reporterror.any.txt
Tests/LibWeb/Text/input/wpt-import/html/webappapis/scripting/reporterror.any.html
Tests/LibWeb/Text/input/wpt-import/html/webappapis/scripting/reporterror.any.js

Instead of always reporting a colno and lineno of zero try and use the values from the Error object that may be provided, falling back to the source location of the invocation if not provided. We can definitely improve the reporting even more, but this is a start!
Also update this function to latest spec while we're in the area.

LibWeb/HTML: Include better information in 'report an exception' event

---

Libraries/LibWeb/Page/EventHandler.cpp
Libraries/LibWeb/Page/Page.h
Libraries/LibWebView/ViewImplementation.h
Libraries/LibWebView/WebContentClient.cpp
Libraries/LibWebView/WebContentClient.h
Services/WebContent/PageClient.cpp
Services/WebContent/PageClient.h
Services/WebContent/WebContentClient.ipc
UI/AppKit/Interface/LadybirdWebView.mm
UI/Qt/Tab.cpp
UI/Qt/Tab.h

Fixes #2785.
The "Copy Image" option is disabled on unloaded or invalid images.

UI: Prevent crash when right clicking on an unloaded image

---

Libraries/LibWeb/DOM/Document.cpp
Tests/LibWeb/Text/expected/theme-color-crash.txt
Tests/LibWeb/Text/input/theme-color-crash.html

LibWeb: Check for missing node or invalid query in obtain_theme_color

---

Libraries/LibWeb/DOM/ElementFactory.cpp
Tests/LibWeb/Text/expected/wpt-import/custom-elements/parser/parser-fallsback-to-unknown-element.txt
Tests/LibWeb/Text/input/wpt-import/custom-elements/parser/parser-fallsback-to-unknown-element.html

Previously, a crash would occur when attempting to throw an error in this case because the method used to create the exception tried to get the current realm from the execution context stack, which is empty. The realm is now passed explicitly when constructing the error, avoiding the crash.
Fixes: http://wpt.live/custom-elements/parser/parser-fallsback-to-unknown-element.html

LibWeb: Don't crash when upgrading custom element with a bad constructor

---

Libraries/LibWeb/CSS/CSSNumericType.cpp
Libraries/LibWeb/CSS/CSSNumericType.h
Libraries/LibWeb/CSS/Interpolation.cpp
Libraries/LibWeb/CSS/Interpolation.h
Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
Libraries/LibWeb/CSS/Parser/Parser.cpp
Libraries/LibWeb/CSS/Parser/Parser.h
Libraries/LibWeb/CSS/Parser/ParsingContext.h
Libraries/LibWeb/CSS/Properties.json
Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.h
Libraries/LibWeb/CSS/StyleValues/EdgeStyleValue.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMathFunctions.cpp

The old way, where we had a single variable storing what property we're currently parsing, was not enough for what we actually need. It ignored longhands, as well as CSS functions, which can affect things like whether quirks are allowed or what a percentage should resolve as.
So this PR replaces that with a stack of `ValueParsingContext`s, which we push and pop as parsing progresses. This means handling quirks more correctly, being more accurate with what type percentages resolve as inside a calculation, and resolving some FIXMEs in `CSSNumericType` to do with checking what types it matches.
There are very likely some properties and functions that still need marking with what they resolve percentages as. `transform` and the `*-gradient()` functions showed up when my changes broke tests, …

LibWeb/CSS: Let calc() know its context

---

Libraries/LibWeb/CSS/SelectorEngine.cpp
Tests/LibWeb/Ref/expected/css-tag-selector-case-sensitivity-html.html
Tests/LibWeb/Ref/expected/css-tag-selector-case-sensitivity-svg.html
Tests/LibWeb/Ref/expected/css-tag-selector-case-sensitivity-xhtml.xhtml
Tests/LibWeb/Ref/input/css-tag-selector-case-sensitivity-html.html
Tests/LibWeb/Ref/input/css-tag-selector-case-sensitivity-svg.html
Tests/LibWeb/Ref/input/css-tag-selector-case-sensitivity-xhtml.xhtml

For things like tag names, the [CSS spec](https://drafts.csswg.org/selectors-4/#case-sensitive) defers whether or not they are case-sensitive to the specifications these names come from.
In HTML, tag names are case-insensitive, but in SVG they are case-sensitive.
I'm not sure which of the two MathML falls under, but I also don't think we currently support that.
The test uses foreignObject, cause selecting those by tag name was impossible before this fix.

LibWeb: Fix CSS tag seletor case sensitivity for SVG elements

---

Documentation/Testing.md
Tests/LibWeb/add_libweb_test.py

This is a modification of #1703, with a few changes:
- Update the file locations for ref/screenshot tests
- Support creating ref/screenshot tests in subdirectories
- Move the docs changes into the separate `Testing.md` file
- Merged the two commits together
My Python skills are lacking but it all seems to work as it's supposed to.

LibWeb: Update add_libweb_test.py to support Screenshot, Ref, and Layout (rescue of #1703)

---

.github/workflows/ci.yml

Originally we used the `paths-ignore` feature to skip the Lagom jobs if no source code was changed. Afterwards, we enabled the 'required checks' feature to prevent merging pull requests that have failing checks. Unfortunately, marking a check as required means it always needs to be successfully executed, even if a conditional caused it to be skipped.
By using the `paths-filter` action we were able to add the conditional to the job instead, theoretically causing the 'required checks' feature to start working again for documentation-only changes. As it turns out, not the job, but the steps should get the new conditionals.
As that requires adding an `if` to every individual step and the conditional execution has caused enough headaches since its introduction, let's remove it for now and take …

CI: Remove conditional execution based on changed paths

---

Libraries/LibWeb/CSS/CSSStyleRule.cpp
Libraries/LibWeb/CSS/CSSStyleSheet.cpp
Libraries/LibWeb/CSS/CSSStyleSheet.h
Libraries/LibWeb/CSS/StyleSheetList.cpp
Libraries/LibWeb/DOM/AdoptedStyleSheets.cpp
Libraries/LibWeb/DOM/AdoptedStyleSheets.h
Libraries/LibWeb/DOM/ShadowRoot.cpp
Tests/LibWeb/Text/expected/css/insert-rule-in-adopted-style-sheet.txt
Tests/LibWeb/Text/input/css/insert-rule-in-adopted-style-sheet.html

Invalidaiton for adopted style sheets was broken because we had an assumption that "active" style sheet is always attached to StyleSheetList which is not true for adopted style sheets. This change addresses that by keeping track of all documents/shadow roots that own a style sheet and notifying them about invalidation instead of going through the StyleSheetList.

LibWeb: Fix insert/delete rule invalidation for adopted style sheets

---

Libraries/LibWeb/Painting/Command.h
Tests/LibWeb/Ref/expected/clip-path-scrolling.html
Tests/LibWeb/Ref/input/clip-path-scrolling.html

This fixes all the previews on https://www.newgrounds.com/games getting cut off once you start scrolling.

LibWeb: Fix CSS clip-path ignoring scroll position

---

Libraries/LibWeb/HTML/HTMLSelectElement.cpp

This makes it go right below the select element, so it does not cover it up anymore:

LibWeb: Improve <select> dropdown position

---

Libraries/LibWeb/HTML/HTMLLIElement.h
Libraries/LibWeb/HTML/HTMLOListElement.h
Libraries/LibWeb/HTML/HTMLSummaryElement.cpp

These cannot possibly throw an exception because the attribute names are already known to be valid.
Just a very, very minor thing I came across while working in related area.

LibWeb: Mark a few calls to set_attribute as infallible

---

Libraries/LibWeb/Painting/PaintableBox.cpp
Libraries/LibWeb/Painting/PaintableBox.h
Libraries/LibWebView/Application.cpp
Libraries/LibWebView/HelperProcess.cpp
Libraries/LibWebView/Options.h
Services/WebContent/main.cpp
Services/WebDriver/main.cpp

This PR adds a `--disable-scrollbar-painting` option, which stops the scrollbars of viewport paintables from being painted. This option is then used by WebDriver when launching the browser.
This gives us 115 additional WPT passes.

WebContent+LibWeb: Add an option to disable painting viewport scrollbars

---

Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Libraries/LibWeb/XHR/XMLHttpRequest.h
Tests/LibWeb/Text/expected/XHR/XMLHttpRequest-response-header-decoding.txt
Tests/LibWeb/Text/input/XHR/XMLHttpRequest-response-header-decoding.html

Fixes a crash on:
https://wpt.live/html/browsers/browsing-the-web/navigating-across-documents/refresh/subresource.any.html

LibWeb/XHR: Isomorphic decode accessing XMLHttpRequest response headers

---

Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/ParentNode-querySelector-All.txt
Tests/LibWeb/Text/expected/wpt-import/url/data-uri-fragment.txt
Tests/LibWeb/Text/input/wpt-import/url/data-uri-fragment.html

Otherwise nowhere ends up scrolling to the fragment specified by the
fragment in document's URL. This fixes ladybird scrolling to the
correct location in the document when navigating to a link that
has a fragment, e.g:
https://html.spec.whatwg.org/multipage/browsing-the-web.html#try-to-scroll-to-the-fragment
As well as use of the :target selector.

LibWeb/HTML: Scroll to the fragment before loading the document

---

ISSUES.md

This PR updates the `ISSUES.md` file to include information about the `--enable-idl-tracing` flag. This switch helped me resolve issue #2936, and I believe that if it were included in the Issues guidelines, it would assist others in similar situations.
This change aims to help contributors more effectively debug issues and provide better test cases when reporting bugs.
If this is not the right place for this information, please feel free to comment.

Docs: Add info about --enable-idl-tracing flag

---

Libraries/LibWeb/HTML/HTMLMediaElement.h
Libraries/LibWeb/HTML/HTMLTrackElement.cpp
Libraries/LibWeb/HTML/HTMLTrackElement.h
Tests/LibWeb/Text/expected/wpt-import/html/semantics/embedded-content/media-elements/track/track-element/track-load-error-readyState.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/embedded-content/media-elements/track/track-element/track-load-error-readyState.html

This commit begins to implement the track processing model. When the `src` attribute is updated, we now fetch the given source file. Currently, we always fire an `error` event once fetching is completed, as we don't support processing the fetched data.
WPT results when running `./Meta/WPT.sh run html/semantics/embedded-content/media-elements/track/track-element/ `
Before:
```
Ran 141 tests finished in 80.8 seconds.
• 8 ran as expected. 0 tests skipped.
• 3 tests crashed unexpectedly
• 100 tests timed out unexpectedly
• 124 tests had unexpected subtest results
```
After:
```
Ran 141 tests finished in 61.0 seconds.
• 9 ran as expected. 0 tests skipped.
• 1 tests crashed unexpectedly
• 52 tests timed out unexpectedly
• 124 tests had unexpected subtest results
```

LibWeb: Fetch source file when HTMLTrackElement src attribute changes

---

Libraries/LibWeb/WebAudio/AudioContext.cpp
Libraries/LibWeb/WebAudio/AudioContext.h
Libraries/LibWeb/WebAudio/BaseAudioContext.cpp
Libraries/LibWeb/WebAudio/BaseAudioContext.h
Libraries/LibWeb/WebAudio/OfflineAudioContext.cpp
Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-audiocontext-interface/audiocontextoptions.txt
Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-audiocontext-interface/audiocontextoptions.html

This PR updates the spec steps for the `AudioContext` and `OfflineAudioContext` constructors.
While working on this I found a few minor inconsistencies, which I believe are (minor) spec issues:
* The `AudioContext` spec steps don't mention validating the given sample rate. The `/webaudio/the-audio-api/the-audiocontext-interface/audiocontextoptions.html` test expects this parameter to be validated.
* The spec only mentions validating `OfflineAudioContext` parameters for the constructor that takes individual arguments - not the constructor that takes an `OfflineAudioContextOptions` object.
* The `AudioContext` steps don't include a step to "Determine the `[[render quantum size]]`". We don't currently implement this, so it's not currently a problem for us.
* The `OfflineAudioContext` …

LibWeb: Align AudioContext constructors with current specification steps

---

Libraries/LibUnicode/Segmenter.cpp
Libraries/LibWeb/DOM/InputEventsTarget.h
Tests/LibUnicode/TestSegmenter.cpp

In the UTF-8 implementation, this prevents out-of-bounds access of the
underlying text data, as the ICU macro would essentially do something
akin to `text[text.length()]`.
The UTF-16 implementation already checks for out-of-bounds, but would
previously return 0. We now return an empty Optional in both impls. This
doesn't affect LibJS (the user of the UTF-16 impl), as it already does
bounds checking before invoking LibUnicode APIs.
Fixes #3269

LibUnicode: Consistently reject out-of-bounds segmenter indices

---

.github/workflows/stale.yml

Elevated permissions are required to do so. Contributors can create a new pull request based on their branch instead. There has been some confusion around the wording of this message lately, so let's change it.

CI: Do not insinuate PRs can be reopened in stalebot's close message

---

Libraries/LibJS/Runtime/Intl/DateTimeFormat.cpp
Libraries/LibJS/Runtime/Temporal/ISO8601.cpp
Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
Libraries/LibJS/Runtime/Temporal/PlainDateTimePrototype.cpp
Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.prototype.total.js
Libraries/LibJS/Tests/builtins/Temporal/PlainDateTime/PlainDateTime.prototype.with.js

The first 2 commits are recent editorial changes to the spec. The last 2 commits fix errors caught by recently added test262 tests.
test262 diff:
```
+16 ✅    -13 ❌    -3 💥
test/built-ins/Temporal/Duration/prototype/total/throws-if-date-time-invalid-with-plaindate-relative.js         💥 -> ✅
test/built-ins/Temporal/Duration/prototype/total/throws-if-date-time-invalid-with-zoneddatetime-relative.js     💥 -> ✅
test/built-ins/Temporal/PlainDate/prototype/since/throws-if-rounded-date-outside-valid-iso-range.js             ❌ -> ✅
test/built-ins/Temporal/PlainDate/prototype/until/throws-if-rounded-date-outside-valid-iso-range.js             ❌ -> ✅
test/built-ins/Temporal/PlainDateTime/prototype/since/throws-if-rounded-date-outside-valid-iso-range.js         ❌ -> ✅ …
```

LibJS: Temporal editorials and bug fixes

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/HTML/Navigable.cpp
Libraries/LibWeb/HTML/Navigable.h
Libraries/LibWeb/HTML/NavigableContainer.cpp
Libraries/LibWeb/HTML/Navigation.cpp
Libraries/LibWeb/HTML/TraversableNavigable.cpp
Libraries/LibWeb/WebDriver/Contexts.cpp
Services/WebContent/WebDriverConnection.cpp

The use of this HashMap looks very spooky, but let's at least use finalize when cleaning them up on destruction to make things slightly less dangerous looking.

LibWeb: Use finalize for cleaning up all navigables

---

Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Tests/LibWeb/Layout/expected/flex-justify-end-gap.txt
Tests/LibWeb/Layout/input/flex-justify-end-gap.html

`place_item` was always adding a gap after every placed element. Which means there was an extra gap between last item and container side when `justify-content: flex-end;` is used.
Fixes #3272

LibWeb: Don't add extra gap when placing flex items

---

Libraries/LibJS/Parser.cpp
Libraries/LibJS/Tests/var-scoping.js

Previously it only deoptimized the parent scope if the current scope contains direct eval, which is incorrect because code ran in direct eval mode has access to the entire scope chain it was executed in. The fix is to also propagate direct eval's presence if the current scope is marked as being screwed by direct eval.
This fixes Google's botguard failing to complete on Google sign in, as it tried to access local variables outside of a direct parent function with eval, causing it throw "unhandled" exceptions. Unhandled is in quotes because their bytecode VM _technically_ caught it, but it was considered an unhandled exception. This was determined by removing get optimizations and then adding debug output for every get operation. Using this, I noticed that for these errors, it would access …

LibJS: Propagate direct eval presence if the current scope is screwed

---

Libraries/LibJS/Bytecode/ASTCodegen.cpp
Libraries/LibJS/Tests/tagged-template-literals.js

Required by creepjs, which does Date().split\` \`[3] to get the current year.

LibJS: Use correct this value for tagged template literals with members

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp

This also fixes GLfloat and GLboolean to use their appropriate glGet functions.

LibWeb/WebGL2: Implement a bunch of parameters read by CreepJS

---

Libraries/LibWeb/Streams/AbstractOperations.cpp
Libraries/LibWeb/Streams/AbstractOperations.h
Libraries/LibWeb/Streams/ReadableByteStreamController.cpp
Libraries/LibWeb/Streams/ReadableByteStreamController.h

While PendingPullIntos are typically visted by their controller there were some cases that we were removing those references from the controller and storing them in a SinglyLinkedList on the stack which is not safe.
Instead, make PendingPullInto a GC::Cell type, which also allows us to remove an awkward copy of the struct where the underlying reference was previously being destroyed.
Fixes #3286.

LibWeb/Streams: Ensure pending pull into's objects are visited by GC

---

Libraries/LibWeb/SVG/SVGUseElement.cpp
Tests/LibWeb/Text/expected/layout-tree-update/svg-use-invalidation-1.txt
Tests/LibWeb/Text/input/layout-tree-update/svg-use-invalidation-1.html

This is sub-optimal but let's rebuild the whole tree for now, since this case gets quite complicated and there are more valuable things to chase after first.

LibWeb: Invalidate entire layout tree on SVG <use> clone instantiation

---

Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Tests/LibWeb/Layout/data/svg-with-id.svg
Tests/LibWeb/Layout/expected/svg/svg-use-element-crashtest.txt
Tests/LibWeb/Layout/input/svg/svg-use-element-crashtest.html

We were previously crashing when invoking 'scroll to the fragment' on such documents as it was unable to find the active document. This is as a result of our AD-HOC implementation not setting up the document fully to mark it is active before running the parser.
Fixes a crash on https://tweakers.net.

LibWeb/SVG: Fix crash when SVG use element is used on an external SVG

---

Libraries/LibWeb/SVG/SVGImageElement.cpp
Tests/LibWeb/Ref/expected/svg-image-in-iframe-ref.html
Tests/LibWeb/Ref/input/svg-image-in-iframe.html

This fixes an issue where an SVGImageElement, whose source was a relative URL would not load inside an iframe.

LibWeb: Resolve `SVGImageElement` source URL correctly

---

Libraries/LibWeb/HTML/HTMLOptionElement.cpp
Libraries/LibWeb/HTML/HTMLOptionElement.h

..and when the label attribute or text is changed (but that didn't fit in the message)
Partially fixes #2385 (and fixes the real world example provided in the issue).
A fully correct implementation would also need to update the label if any text descendants are changed.

LibWeb: Update the select label when option's children are changed

---

Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/CSS/InvalidationSet.cpp
Libraries/LibWeb/CSS/InvalidationSet.h
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/CSS/StyleInvalidationData.cpp
Libraries/LibWeb/CSS/StyleInvalidationData.h
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h

Implements idea described in
https://docs.google.com/document/d/1vEW86DaeVs4uQzNFI5R-_xS9TcS1Cs_EUsHRSgCHGu8
Invalidation sets are used to reduce the number of elements marked for style recalculation by collecting metadata from style rules about the dependencies between properties that could affect an element’s style.
Currently, this optimization is only applied to style invalidation triggered by class list mutations on an element.

LibWeb: Use invalidation sets to reduce style recalculation

---

Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Tests/LibWeb/Text/expected/alert.txt
Tests/LibWeb/Text/input/alert.html
UI/Headless/Test.cpp

For example, running `alert(1)` will pause the event loop, during which time no JavaScript should execute. This patch extends this disruption to microtasks. This avoids a crash inside the microtask executor, which asserts the JS execution context stack is empty.
This makes us behave the same as Firefox in the following page:
```html
<script>
queueMicrotask(() => {
console.log("inside microtask");
});
alert("hi");
</script>
```
Before the aforementioned assertion was added, we would execute that microtask before showing the alert. Firefox does not do this, and now we don't either.
WPT of `/webdriver/tests/classic` before:
```
web-platform-test
~~~~~~~~~~~~~~~~~
Ran 3617 checks (3423 subtests, 194 tests)
Expected results: 2253
Unexpected results: 1364
subtest: 1364 (996 error, 368 fail)
``` …

LibWeb: Do not run microtasks when the event loop is paused

---

Libraries/LibWeb/HTML/MessagePort.cpp
Libraries/LibWeb/HTML/MessagePort.h
Libraries/LibWeb/HTML/Window.cpp

I've been trying to implement transferable streams for a bit, and have half working implementation with the additional changes of:
Implementing the transferable streams AOs:  https://github.com/shannonbooth/ladybird/commit/77c937a498743d018a30d6c0e225f180796546f7
And using those AOs to make ReadableStream transferable: https://github.com/shannonbooth/ladybird/commit/5c5f2503661f240521724c92e7c022700b3583ff (very similar diff needed for WritableStream)
I've been debugging some issues in MessagePort / Pipe implementation which are causing some issues with that implementation causing timeouts / messages to not be received on the other end of the message port. In the meantime, this upstreams a portion of the changes from that branch.

LibWeb/HTML: Upstream some changes from transferable streams branch

---

Libraries/LibXML/Parser/Parser.cpp
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/DocumentType-literal-xhtml.txt
Tests/LibWeb/Text/input/wpt-import/dom/nodes/DocumentType-literal-xhtml.xhtml

Fixes Wtp Test dom/nodes/DocumentType-literal-xhtml.xhtml using value() instead of release_value() avoid regression on html/the-xhtml-syntax/parsing-xhtml-documents

LibXml: Notify listener as soon as doctype is parsed

---

Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Tests/LibWeb/Text/expected/link-changed-rel.txt
Tests/LibWeb/Text/input/link-changed-rel.html

LibWeb: Only reload link on rel change if it became a stylesheet

---

UI/Qt/LocationEdit.cpp

I constantly use this functionality in mainstream browsers where a '.com' gets automatically added to the URL if you to CTRL+Return in the URL bar. I've seen it's not implemented here so I've added it.

UI/Qt: Add '.com' to the URL if CTRL is held while pressing Return

---

Libraries/LibWeb/Layout/TreeBuilder.cpp
Tests/LibWeb/Layout/expected/layout-tree-update/simple-update-inside-svg-subtree.txt
Tests/LibWeb/Layout/input/layout-tree-update/simple-update-inside-svg-subtree.html

We were incorrectly always appending to the nearest ancestor in the partial update case, even when the node was eligible for replacement.

LibWeb: Allow partial update of SVG subtrees in layout tree

---

Libraries/LibWeb/SVG/SVGSVGElement.idl
Tests/LibWeb/Text/expected/SVG/svg-svg-getElementById.txt
Tests/LibWeb/Text/input/SVG/svg-svg-getElementById.html

This is wrong in the spec, and there's already a bug open.

LibWeb: Make SVGSVGElement.getElementById() return Element? (nullable)

---

Libraries/LibWeb/Editing/ExecCommand.cpp
Tests/LibWeb/Text/expected/Editing/execCommand-selectAll.txt
Tests/LibWeb/Text/input/Editing/execCommand-selectAll.html

Disable the command if no selection is available. This is a spec bug:
https://github.com/w3c/editing/issues/475
Fixes #3325

LibWeb: Require existing Selection for `.execCommand("selectAll")`

---

AK/TypeCasts.h
Libraries/LibJS/CyclicModule.cpp
Libraries/LibJS/CyclicModule.h
Libraries/LibJS/Module.cpp
Libraries/LibJS/Parser.cpp
Libraries/LibJS/Parser.h
Libraries/LibJS/Runtime/AbstractOperations.cpp
Libraries/LibJS/Runtime/VM.cpp
Libraries/LibJS/Tests/modules/basic-modules.js
Libraries/LibJS/Tests/modules/import-with-assertions.mjs
Libraries/LibJS/Tests/modules/import-with-attributes.mjs
Libraries/LibJS/Tests/modules/json-module.mjs
Libraries/LibJS/Tests/modules/json-modules.js

A few fixes for import assertions and JSON modules.
test262 diff:
```
+17 ✅    -6 ❌    -11 💥
test/language/import/import-attributes/json-extensibility-array.js                    ❌ -> ✅
test/language/import/import-attributes/json-extensibility-object.js                   ❌ -> ✅
test/language/import/import-attributes/json-value-array.js                            ❌ -> ✅
test/language/import/import-attributes/json-value-boolean.js                          ❌ -> ✅
test/language/import/import-attributes/json-value-null.js                             ❌ -> ✅
test/language/import/import-attributes/json-value-number.js                           ❌ -> ✅
test/language/import/import-attributes/json-value-object.js                           ❌ -> ✅ …
```

LibJS: A small `import` goodie bag

---

Libraries/LibWeb/Layout/Node.cpp
Tests/LibWeb/Ref/input/wpt-import/css/css-tables/absolute-tables-006.html
Tests/LibWeb/Text/expected/abspos-child-inside-abspos-table.txt
Tests/LibWeb/Text/input/abspos-child-inside-abspos-table.html

When an element is displayed as table, an anonymous table wrapper box needs to be created for it. Among others, the position property of the table element is then applied to the anonymous table wrapper box instead. If the table happens to be positioned absolutely, the table wrapper box may become the containing block for absolutely positioned elements inside the table.
In the original code however, anonymous layout nodes were excluded from becoming the containing block for an absolutely positioned element. Because of this, the containing block was calculated to be the first suitable parent block of the table wrapper box.
This incorrect containing block would result in a crash later on when trying to size the absolutely positioned element inside the table. To prevent this crash, the …

LibWeb: Accept TableWrapper as containing block for abspos items

---

Libraries/LibGC/RootVector.h
Libraries/LibWeb/HTML/HTMLFormElement.cpp
Tests/LibWeb/Crash/HTML/reset-form-iteration.html

DOM structure may change during reset algorithm invocation, which may lead to form controls being unregistered.

LibWeb: Iterate over a copy of associated form controls in form.reset()

---

Libraries/LibURL/Host.cpp
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/HTML/Navigable.cpp
Libraries/LibWeb/HTML/Navigable.h

This is a partial implementation of the changes in https://github.com/whatwg/html/pull/10818
I don't know if the ad-hoc change in Host is because of a spec bug, or just our implementation being wrong. (I suspect the latter.) Maybe `localhost` should fail the `Host::is_domain()` call, but the spec is pretty vague.

LibWeb/HTML: Update some navigables code to current spec

---

Libraries/LibWeb/Editing/Commands.cpp
Libraries/LibWeb/Editing/ExecCommand.cpp

This arguably improves readability in a couple of places. No functional changes.

LibWeb: Use `as_if` in Editing API where useful

---

Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/Editing/Commands.cpp
Libraries/LibWeb/Editing/ExecCommand.cpp
Libraries/LibWeb/Editing/Internal/Algorithms.cpp
Tests/LibWeb/Text/expected/Editing/execCommand-selectAll.txt
Tests/LibWeb/Text/expected/wpt-import/editing/other/non-html-document.txt
Tests/LibWeb/Text/input/Editing/execCommand-selectAll.html
Tests/LibWeb/Text/input/wpt-import/editing/other/non-html-document.html

This is not directly mentioned in the Editing API spec, but all major browsers do this and there is a WPT for this behavior.
Relevant WPT commit: https://github.com/web-platform-tests/wpt/commit/853867249cae98f2f4b2d208d83bb2ee791a8ac6

LibWeb: Disallow Editing API calls on non-HTML documents

---

Libraries/LibIPC/Decoder.cpp
Libraries/LibIPC/Encoder.cpp
Libraries/LibURL/URL.cpp
Libraries/LibURL/URL.h
Libraries/LibWeb/DOMURL/DOMURL.cpp
Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Libraries/LibWeb/FileAPI/BlobURLStore.cpp
Libraries/LibWeb/FileAPI/BlobURLStore.h
Libraries/LibWeb/HTML/Window.cpp
Libraries/LibWeb/StorageAPI/StorageKey.cpp
Libraries/LibWeb/StorageAPI/StorageKey.h
Tests/LibWeb/Text/expected/FileAPI/Blob-partitioning.txt
Tests/LibWeb/Text/input/FileAPI/Blob-partitioning.html

This was a security mechanism introduced in the fetch spec, with
supporting AOs added to the FileAPI spec.

LibWeb: Partition Blob URL fetches by Storage Key

---

Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Libraries/LibWeb/Layout/BlockFormattingContext.h

Fixes #3318 (or at least helps a lot)
Here's a performance comparison measured using
`hyperfine "Build/release/bin/headless-browser --dump-layout-tree /tmp/test.html"` with the example in #3318.
I'm not 100% confident about when (and how) the cached value is invalidated, the invalidation in `place_block_level_element_in_normal_flow_vertically` was done to fix the only regression I could find after running every single WPT test containing the string `float:`.

LibWeb: Cache the margin box rect for floating boxes

---

Libraries/LibWeb/DOM/Element.cpp

Use invalidation sets for presentational hint attribute invalidation
instead of falling back to full descendants and siblings invalidation.
The only difference for presentational hint attributes is that we always
have to invalidate the style of element itself.

Optimize style invalidation for presentational hint attributes

---

Libraries/LibWeb/HTML/Navigable.cpp
Libraries/LibWeb/Page/EventHandler.cpp

When right-clicking on iframes or interacting with &lt;select&gt; elements inside of iframes, the position of the popup used to be too far up and to the right.
This fixes that.
I've also added a fixme since iframes with CSS transforms applied are still not accounted for.

LibWeb: Fix context menu and select dropdown position in iframe

---

UI/Qt/InspectorWidget.cpp

This fixes an issue where it was impossible to paste text into inspector console input. Copying still doesn't work correctly — an empty string is being copied. But it matches the behavior of a regular browser window, so I assume it's a separate issue.
Fixes #2606

UI/Qt: Add copy/paste/select actions to the InspectorWidget

---

Libraries/LibJS/Runtime/Intrinsics.cpp
Libraries/LibJS/Runtime/Intrinsics.h
Libraries/LibJS/Runtime/StringPrototype.cpp

In the very common case that no special constructor options are provided for the Intl.Collator when calling localeCompare() on a string, we can cache and reuse a default-constructed Intl.Collator, saving lots of time and space.
This shaves a fair bit of load time off of https://wpt.fyi/ where they use Array.prototype.sort() and localeCompare() to sort a big JSON thing.
Time spent in sort():
- Before: 1656 ms
- After: 135 ms

LibJS: Cache the Intl.Collator in String.prototype.localeCompare()

---

Libraries/LibWeb/WebIDL/DOMException.h
Libraries/LibWeb/WebIDL/ExceptionOr.h

This adds formatters for `WebIDL::Exception`, `WebIDL::SimpleException` and `WebIDL::DOMException`. These are useful for displaying the content of errors when debugging.

LibWeb: Add formatters for WebIDL exception types

---

.clang-tidy

This change causes the `readability-implicit-bool-conversion` check to be completely skipped by clang-tidy.
We have many places in the existing code where we’re doing implicit conversions to booleans — not just for pointers (which our clang-tidy config already has an exception for), but also for integers and for other types as well.
Given that, the readability-implicit-bool-conversion generates a lot of unwelcome/distracting noise with our existing code.

Meta: Disable clang-tidy “implicit-bool-conversion” check

---

AK/JsonValue.cpp
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Node.cpp

Let's do a lot less work in StyleComputer on the WPT dashboard at https://wpt.fyi/
See individual commits.
Bonus: Remove some unnecessary copying in the AK::JsonValue constructors that was costing us a ton of time.

More juicy speed-ups for wpt.fyi

---

Libraries/LibWeb/DOM/AbstractRange.h
Libraries/LibWeb/DOM/CharacterData.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/DOM/MutationObserver.h
Libraries/LibWeb/Editing/Commands.cpp
Libraries/LibWeb/Editing/Commands.h
Libraries/LibWeb/Editing/ExecCommand.cpp
Libraries/LibWeb/Selection/Selection.cpp
Tests/LibWeb/Text/expected/Editing/execCommand-backColor.txt
Tests/LibWeb/Text/expected/Editing/execCommand-insertText.txt
Tests/LibWeb/Text/expected/Editing/execCommand-no-recursion.txt
Tests/LibWeb/Text/input/Editing/execCommand-backColor.html
Tests/LibWeb/Text/input/Editing/execCommand-insertText.html
Tests/LibWeb/Text/input/Editing/execCommand-no-recursion.html

Editing commands now fire the `input` event. Comes with a random selection of fixes.
New WPT passes:
* `editing/event.html`: +56
* `editing/other`: +42
* `editing/plaintext-only`: +10
* `editing/run`: +98

LibWeb: Editing improvements

---

Libraries/LibWeb/HTML/CloseWatcher.cpp
Libraries/LibWeb/HTML/CloseWatcherManager.cpp
Libraries/LibWeb/HTML/HTMLDialogElement.cpp
Libraries/LibWeb/HTML/HTMLDialogElement.h
Libraries/LibWeb/HTML/HTMLDialogElement.idl
Libraries/LibWeb/HTML/HTMLElement.cpp

Lots of spec changes recently to close watchers, dialogs and popovers. In preparation for supporting dialog light dismiss, dialog.requestClose() and popover=hint  this PR updates the various spec comments.

LibWeb: Update spec comments for dialog, popover and close watcher

---

Libraries/LibWeb/CSS/StyleInvalidationData.cpp
Libraries/LibWeb/CSS/StyleInvalidationData.h
Meta/check-newlines-at-eof.py
Tests/LibWeb/Ref/input/wpt-import/css/selectors/invalidation/nth-child-of-ids-without-empty-text-node.html

For all invalidation properties nested into nth-child argument list we need to invalidate whole subtree to make sure style of sibling elements will be recalculated.

Fix underinvalidation of :nth-child using invalidation sets

---

Libraries/LibWeb/CSS/StyleInvalidationData.cpp
Libraries/LibWeb/DOM/Element.cpp
Tests/LibWeb/Text/expected/invalidate-style-of-element-with-placeholder-shown-used-on-nested-element.txt
Tests/LibWeb/Text/input/invalidate-style-of-element-with-placeholder-shown-used-on-nested-element.html

...for :placeholder-shown pseudo-class.

Add missing handler in affected_by_invalidation_property()

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h

Instead of traversing the entire DOM subtrees and marking nodes for style update, this patch adds a new mechanism where we can mark a subtree root as "entire subtree needs style update".
A new pass in Document::update_style() then takes care of coalescing all these invalidations in a single traversal of the DOM.
This shaves *minutes* of loading time off of https://wpt.fyi/ subpages.

LibWeb: Coalesce entire-subtree style invalidations

---

Libraries/LibWeb/DOM/Element.cpp
Tests/LibWeb/Text/expected/invlidate-properties-with-relative-units-in-inherited-style-update.txt
Tests/LibWeb/Text/input/invlidate-properties-with-relative-units-in-inherited-style-update.html

Properties with relative units has to be recomputed in inherited style update as they depend on the parent's style.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/3364

LibWeb: Recompute relative units in Element::recompute_inherited_style()

---

Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Libraries/LibWeb/Layout/LayoutState.cpp
Libraries/LibWeb/Layout/LayoutState.h
Tests/LibWeb/Layout/expected/block-and-inline/float-vertical-offset-by-preceding-float.txt
Tests/LibWeb/Layout/input/block-and-inline/float-vertical-offset-by-preceding-float.html

See commit messages for details.
Fixes the layout for https://tweakers.net/info/over-tweakers/:
|---|---|
| ![Screenshot_20250127_122044](https://github.com/user-attachments/assets/64e9a926-169a-4a97-87db-63e97e657cf2) | ![Screenshot_20250127_122017](https://github.com/user-attachments/assets/25f18555-943f-4bea-986d-d88daf2ff8c5) |

LibWeb: Fix vertical float positioning when pushing a new float against the edge

---

Libraries/LibWeb/Animations/KeyframeEffect.cpp
Libraries/LibWeb/CSS/CSSStyleValue.cpp
Libraries/LibWeb/CSS/FontFaceSet.cpp
Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/CSS/StyleInvalidation.cpp
Libraries/LibWeb/CSS/StyleValues/BorderRadiusStyleValue.cpp
Libraries/LibWeb/CSS/StyleValues/CSSColorValue.cpp
Libraries/LibWeb/CSS/StyleValues/CSSKeywordValue.h
Libraries/LibWeb/CSS/StyleValues/CSSRGB.cpp
Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp

This means we only need to consider rules from the document and the
current shadow root, instead of the document and *every* shadow root.
Dramatically reduces the amount of rules processed on many pages.
Shaves 2.5 seconds of load time off of https://wpt.fyi/ :^)
+ 2 bonus commits for more speedups on the same page..

LibWeb: Segregate StyleComputer rule caches per Document-or-ShadowRoot + 2 smol speedups

---

Libraries/LibWeb/Animations/DocumentTimeline.cpp
Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp

Previously, we were generating timestamps relative to the current time of the monotonic clock. We now generate timestamps relative to the event loop's last render opportunity time, per the spec.
Doing this allows us to move around on Google Street View :^)
https://github.com/user-attachments/assets/390eb536-1749-4522-9349-4d0c3d502c2d

LibWeb: Generate correct timestamp values when updating animations

---

Libraries/LibWeb/CSS/Parser/Parser.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h
Tests/LibWeb/Text/expected/css/CSSStyleDeclaration-custom-properties-2.txt
Tests/LibWeb/Text/input/css/CSSStyleDeclaration-custom-properties-2.html

We have an optimization that allows us to invalidate only the style of the element itself and mark descendants for inherited properties update when the "style" attribute changes (unless there are any CSS rules that use the "style" attribute, then we also invalidate all descendants that might be affected by those rules). This optimization was not taking into account that when the inline style has custom properties, we also need to invalidate all descendants whose style might be affected by them.
This change fixes this bug by saving a flag in Element that indicates whether its style depends on any custom properties and then invalidating all descendants with this flag set when the "style" attribute changes. Unlike font relative lengths invalidation, for elements that depend on custom …

LibWeb: Fix underinvalidation when inline style has custom properties

---

Libraries/LibWeb/FileAPI/FileReader.cpp
Tests/LibWeb/Text/expected/wpt-import/FileAPI/reading-data-section/filereader_readAsBinaryString.any.txt
Tests/LibWeb/Text/input/wpt-import/FileAPI/reading-data-section/filereader_readAsBinaryString.any.html
Tests/LibWeb/Text/input/wpt-import/FileAPI/reading-data-section/filereader_readAsBinaryString.any.js

See also https://github.com/LadybirdBrowser/ladybird/pull/3144

LibWeb/FileAPI: Implement FileReader readAsBinaryString

---

Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/DOM/Document.cpp

Instead of allocating 3 vectors with size equal to the number of
elements potentially affected by hover:
- for the elements themselves
- for selector match state of each element before hovered node change
- for selector match state of each element after hovered node change
now we allocate none of them, but mark element for style recalculation
as we traverse the tree.

LibWeb: Reduce memory usage in hover style invalidation

---

Libraries/LibWeb/WebGL/WebGLRenderingContextBase.idl

Used by d3wasm for effects that use the current framebuffer as the texture, such as screen wipes.

LibWeb/WebGL: Implement copyTex(Sub)Image2D

---

Libraries/LibWeb/DOM/Document.cpp

The VisualViewport resize event is used on x.com to determine the layout to use on resize.

LibWeb: Mark the Window resize event as trusted and fire resize event at VisualViewport

---

Libraries/LibWeb/CSS/InvalidationSet.cpp
Libraries/LibWeb/CSS/InvalidationSet.h
Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/CSS/SelectorEngine.h
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleInvalidationData.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h

Prior to this change, we invalidated all elements in the document if it
used any selectors with :has(). This change aims to improve that by
applying a combination of techniques:
- Collect metadata for each element if it was matched against a selector
with :has() in the subject position. This is needed to invalidate all
elements that could be affected by selectors like `div:has(.a:empty)`
because they are not covered by the invalidation sets.
- Use invalidation sets to invalidate elements that are affected by
selectors with :has() in a non-subject position.
Selectors like `.a:has(.b) + .c` still cause whole-document invalidation
because invalidation sets cover only descendants, not siblings. As a
result, there is no performance improvement on github.com due to this
limitation. However, …

LibWeb: Use invalidation sets for :has() invalidation 

---

Libraries/LibWeb/DOM/ElementFactory.cpp

Now that we have implemented most of the element types, this dbgln is a lot less useful for detecting issues on live sites, and is in my experience more likely to log cases that are not a FIXME. It also cleans up some of the log spam from running tests.

LibWeb/DOM: Remove FIXME dbgln about unknown element name creation

---

Tests/LibWeb/TestConfig.ini

These were introduced in 67ed6768313 and fail for half of the time on my machine.

Tests: Disable flaky ref-tests for now

---

Libraries/LibWeb/CSS/Parser/Parser.cpp

This greatly reduces the amount of log spam on certain websites.
Specifically, cnn.com would spam this a lot, due to having `border-width: none`, which is invalid. And it ends up parsing that repeatedly because it's used in a custom property, which is used in multiple places:
```css
.something {
--theme-header__dropdown-border-width: none;
border-width: var(--theme-header__dropdown-border-width);
}
```

LibWeb/CSS: Hide "No property (from N properties) matched foo" message

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h

...until Document::update_style(). This allows to avoid doing full document DOM tree traversal on each Node::invalidate_style() call.
Fixes performance regression on wpt.fyi

LibWeb: Postpone invalidating style of elements affected by :has()

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/HTML/Scripting/WindowEnvironmentSettingsObject.cpp
Libraries/LibWeb/HighResolutionTime/TimeOrigin.cpp
Tests/LibWeb/TestConfig.ini
Tests/LibWeb/Text/expected/wpt-import/dom/events/Event-timestamp-safe-resolution.txt
Tests/LibWeb/Text/expected/wpt-import/hr-time/timing-attack.txt
Tests/LibWeb/Text/input/PerformanceObserver/PerformanceObserver_basic.html
Tests/LibWeb/Text/input/wpt-import/hr-time/resources/timing-attack.js
Tests/LibWeb/Text/input/wpt-import/hr-time/timing-attack.html

Several interfaces that return a high resolution time require that time to be coarsened, in order to prevent timing attacks. This implementation simply reduces the resolution of the returned timestamp to the minimum values given in the specification. Further work may be needed to make our implementation more robust to the kind of attacks that this mechanism is designed to prevent.
Fixes several WPT tests in the `/hr-time` directory that rely on reduced time resolution.

LibWeb: Implement basic high resolution time coarsening

---

Libraries/LibWeb/HTML/Focus.cpp
Tests/LibWeb/Text/expected/focus-chain.txt
Tests/LibWeb/Text/expected/wpt-import/dom/events/shadow-relatedTarget.txt
Tests/LibWeb/Text/input/focus-chain.html

The focus chain always consists of newly created GC::Root objects, so the condition always produced `false`. The fix is to use GC::Root's overloaded operator== method, which compares the pointers of the stored type.
This fixes Figma dropdowns and context menus instantly disappearing upon opening them. This is because they become focused when they insert them. Because of this bug, it would fire blur events all the way up to and including the window. Figma listens for the blur event on the window, and when received, it will instantly hide dropdowns and context menus. The intention behind this seems to be hiding them when the user clicks off the browser window, or switches tab.

LibWeb: Don't compare the focus chain's GC::Root contents by reference

---

Libraries/LibWeb/Layout/FormattingContext.cpp
Tests/LibWeb/Layout/expected/abspos-non-bfc-root-with-min-height-constraint.txt
Tests/LibWeb/Layout/input/abspos-non-bfc-root-with-min-height-constraint.html

BFC roots behave differently in that their height is computed twice, before and after inside layout, since automatic height depends on the results of inside layout. Other formatting contexts only require the "before" pass, and so we can treat their content sizes as definite before proceeding with inside layout.
This makes https://play.tailwind.com/ look beautiful. :^)
Before:
After:

LibWeb: Ensure size constraints apply to non-BFC-root abspos boxes

---

Libraries/LibWeb/Fetch/Fetching/Fetching.cpp

This also fixes it looking at the request's current URL origin instead of the request's actual origin.

LibWeb: Set Sec-Fetch-Site header to same-site where appropriate

---

Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.h
Libraries/LibJS/Runtime/Completion.cpp

This has no functional difference as run_queued_promise jobs does nothing when LibWeb is used as it has a different implementation of enqueuing and running promise jobs. But this change makes it more obvious that run_queued_promise jobs does nothing when there is an embedder, and adjusts the comment to reflect what the code is actually achieving.

LibJS: Only run queued promise jobs if there is no embedder

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/HTML/HTMLButtonElement.cpp
Libraries/LibWeb/HTML/HTMLElement.cpp
Libraries/LibWeb/HTML/HTMLElement.h
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.h
Libraries/LibWeb/HTML/HTMLInputElement.idl
Libraries/LibWeb/HTML/PopoverInvokerElement.cpp
Libraries/LibWeb/HTML/PopoverInvokerElement.h
Libraries/LibWeb/Layout/TreeBuilder.cpp
Tests/LibWeb/Layout/expected/popovertarget-button.txt
Tests/LibWeb/Layout/input/popovertarget-button.html
Tests/LibWeb/Text/expected/popover-crashes.txt
Tests/LibWeb/Text/input/popover-crashes.html

The first commit is based on whatwg/html#9457 and prevents a crash when removing a visible popover.
That spec PR hasn't been merged yet and is currently slightly outdated, but the changes are spread throughout the code so I'm not sure what the best place to add a `FIXME`/`AD-HOC` would be.
The second commit implements `popovertarget` buttons (and includes a change to top layer elements to prevent a crash when hiding and showing a popover in the same frame).
This PR also fixes 29 crashing tests and gains at least 1656 new subtest passes.
(I may start a followup PR to update and implement the remaining parts of the popover spec)

LibWeb: Prevent a popover crash and implement popovertarget

---

Libraries/LibWeb/HTML/CloseWatcher.cpp
Libraries/LibWeb/HTML/CloseWatcher.h
Libraries/LibWeb/HTML/CloseWatcher.idl
Libraries/LibWeb/HTML/CloseWatcherManager.cpp
Libraries/LibWeb/HTML/HTMLDialogElement.cpp
Libraries/LibWeb/HTML/HTMLDialogElement.h
Libraries/LibWeb/HTML/HTMLDialogElement.idl
Libraries/LibWeb/HTML/HTMLElement.cpp

Depends on #3354 
See https://html.spec.whatwg.org/multipage/interaction.html#dom-closewatcher-requestclose
Can manually test using https://wpt.live/html/semantics/interactive-elements/the-dialog-element/dialog-requestclose.html where it passes all tests.
If I import the test it's flaky and sometimes fails on test runner.

LibWeb: Implement dialog.requestClose()

---

Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/Painting/PaintableBox.cpp
Libraries/LibWeb/Painting/PaintableBox.h
Libraries/LibWeb/Painting/ViewportPaintable.cpp
Tests/LibWeb/Text/expected/scroll-by-dispatching-wheel-event-on-overflow-scroll-without-scrollable-overflow.txt
Tests/LibWeb/Text/input/scroll-by-dispatching-wheel-event-on-overflow-scroll-without-scrollable-overflow.html

Allow wheel event to be consumed by a `overflow: scroll` box only if it
has content that overflows a scrollport.
This fixes the timing issue in the
`Text/input/scroll-window-using-wheel-event.html` test, where a `<body>`
element with `overflow: scroll` was incorrectly consuming wheel events
that should have propagated to the window.

Fix unnecessary wheel event consumption with overflow: scroll

---

Libraries/LibWeb/Fetch/Body.cpp
Libraries/LibWeb/Fetch/Body.h

This patch synchronizes changes from whatwg/fetch#1569 and resolves a related FIXME: "Refactor this to the new version of the spec introduced with whatwg/fetch@464326e.”

LibWeb/Fetch: Sync with spec update (whatwg/fetch#1569)

---

Services/WebWorker/main.cpp

This was causing WPT tests using Workers to time out.
This reverts commit a1cf5271c29f2ec0cfc1c53067b624e5ccbd15a0.

Revert "WebWorker: Prefer the default EventLoopManager over Qt's specialization"

---

Libraries/LibWeb/Page/EventHandler.cpp
Tests/LibWeb/Text/expected/UIEvents/KeyEvent-keypress.txt
Tests/LibWeb/Text/input/UIEvents/KeyEvent-keypress.html

For web compat and interop with other engines, this change makes us fire `keypress` events for the <kbd>Enter</kbd> key and for the combination of the <kbd>Enter</kbd> key with the <kbd>Shift</kbd> or <kbd>Ctrl</kbd> keys — despite the fact the UI Events spec states at https://w3c.github.io/uievents/#event-type-keypress it must be fired _“if and only if that key normally produces a character value”._
See https://github.com/w3c/uievents/issues/183#issuecomment-448091687 and https://github.com/w3c/uievents/issues/266#issuecomment-1887917756.
Otherwise, without this change, Ladybird won’t work as expected in (the likely very many) existing web applications that use the `keypress` events to check for <kbd>Enter</kbd> key presses.
For example, without this change, Ladybird doesn’t work as …

LibWeb: Fire keypress event for Enter, Shift+Enter, and Ctrl+Enter keys

---

Libraries/LibGfx/PaintingSurface.cpp
Libraries/LibGfx/PaintingSurface.h
Libraries/LibGfx/SkiaBackendContext.cpp
Libraries/LibGfx/SkiaBackendContext.h
Libraries/LibGfx/VulkanContext.h
Libraries/LibWeb/HTML/Navigable.h
Libraries/LibWeb/HTML/TraversableNavigable.cpp
Libraries/LibWeb/HTML/TraversableNavigable.h
Libraries/LibWeb/Painting/BackingStore.h
Libraries/LibWeb/Painting/DisplayList.cpp
Libraries/LibWeb/Painting/DisplayList.h
Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
Libraries/LibWeb/Painting/DisplayListPlayerSkia.h
Libraries/LibWeb/Painting/SVGMaskable.cpp
Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Libraries/LibWeb/WebDriver/Screenshot.cpp
Services/WebContent/BackingStoreManager.h

This effectively changes two things about how we allocate and use surfaces:
* No longer do we create a Vulkan/Metal context per `TraversableNavigable`; it is now cached on a process level.
* Instead of creating a `PaintingSurface` (and calling into Skia) for every paint call, do it once for every unique backing bitmap that's passed in by caching them inside `TraversableNavigable`.
This has improved loading https://tweakers.net for me significantly since it uses multiple navigables on their homepage;
| Backend | Before | After |
|---|---|---|
| Vulkan | 7.5s | 3.5s |
| Metal | 2.9s | 3.0s |
Above measurements were made by repeatedly loading the website and measuring how long it took between the first draw call and the page "settling in". There doesn't seem to be a significant effect on the …

LibGfx+LibWeb: Reuse graphics contexts and surfaces as much as possible

---

Libraries/LibWeb/Painting/PaintableBox.cpp
Libraries/LibWeb/Painting/PaintableFragment.h
Libraries/LibWeb/Painting/TextPaintable.cpp
Tests/LibWeb/Text/expected/hit_testing/pointer-events.txt
Tests/LibWeb/Text/input/hit_testing/pointer-events.html

Fixes a crash when hovering on some images on https://tweakers.net.

LibWeb: Ignore fragments with pointer-events: none in hit-testing

---

AK/TypeCasts.h
Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Libraries/LibWeb/HTML/StructuredSerialize.cpp

This means that if `is<OutputType>(x)` is true, that `as_if<OutputType>(x)` should always succeed.
I've also included a commit to use the new `as_if()` functionality to avoid a double dynamic cast in a few places.

AK+LibWeb: Allow `as` and `as_if` to perform dynamic cast when necessary 

---

Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Tests/LibWeb/Text/expected/link-re-enable-crash.txt
Tests/LibWeb/Text/input/link-re-enable-crash.html

This fixes a crash when enabling or disabling an already disabled link element. 
Fixes a crash when changing mdbook themes. (e.g. on https://doc.rust-lang.org/stable/book/)

LibWeb: Clear stylesheet pointer when disabling link element

---

Libraries/LibRegex/RegexOptimizer.cpp
Tests/LibRegex/Regex.cpp

LibRegex: Take trailing inversion state into account in block comparison

---

Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Tests/LibWeb/Text/expected/wpt-import/css/css-animations/display-none-prevents-starting-in-subtree.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-display/animations/display-interpolation.txt
Tests/LibWeb/Text/input/wpt-import/css/css-animations/display-none-prevents-starting-in-subtree.html

No parent's paintable means animation is nested in a node with `display: none`, so it's safe to skip animation update that won't be visible.
This change improves perfomance on YouTube homepage where we had to invalidate layout on every frame because of animation on `width` property nested in a `display: none` node.

LibWeb: Skip animation update when target's parent has no paintable

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Libraries/LibWeb/HTML/Navigable.cpp
Libraries/LibWeb/HTML/Navigable.h
Libraries/LibWeb/HTML/TraversableNavigable.cpp
Libraries/LibWeb/HTML/TraversableNavigable.h
Services/WebContent/ConnectionFromClient.cpp
Services/WebContent/PageClient.cpp

Before this change, `m_needs_repaint` was reset in `Document::record_display_list()` only when the cached display list was absent. This meant that if the last triggered repaint used the cached display list, we would keep repainting indefinitely until the display list was invalidated (We schedule a task that checks if repainting is required 60/s).
This change also moves `m_needs_repaint` from Document to TraversableNavigable as we only ever need to repaint a document that belongs to traversable.

LibWeb: Fix infinite repaint loop when cached display list is used

---

Libraries/LibWeb/DOM/Document.cpp

This is "update document for history step application" but that's too long for the commit title. :^)
No code changes, just adding more FIXME comments for the new steps. (And indented step 7's substeps for clarity.)
Corresponds to https://github.com/whatwg/html/pull/10910

LibWeb/DOM: Add spec steps for WebDriver BiDi to document history algo

---

Libraries/LibWeb/Bindings/MainThreadVM.cpp
Libraries/LibWeb/DOM/AbortSignal.cpp
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/EventDispatcher.cpp
Libraries/LibWeb/HTML/EventSource.cpp
Libraries/LibWeb/HTML/Scripting/ClassicScript.cpp
Libraries/LibWeb/HighResolutionTime/Performance.cpp
Libraries/LibWeb/PerformanceTimeline/PerformanceObserver.cpp
Libraries/LibWeb/WebIDL/AbstractOperations.cpp
Libraries/LibWeb/WebSockets/WebSocket.cpp

This just makes the code slightly less verbose.
No functional changes.

LibWeb: Use `as` to cast global object to WindowOrWorkerGlobalScopeMixin

---

Services/RequestServer/ConnectionFromClient.cpp

Before, if something went wrong with DNS lookup and there were unrelated records (i.e. not A or AAAA) then we would still attempt to build a resolve list. This resulted in curl errors related to the option itself and displayed as "unknown network error" to the user.

RequestServer: Check for empty list of IP addresses in DNS result

---

Libraries/LibWeb/CSS/Selector.cpp
Libraries/LibWeb/CSS/Selector.h
Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/CSS/SelectorEngine.h
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/DOM/Document.cpp

Before this change, checking if fast selector matching could be used was only enabled in style recalculation and hover invalidation. With this change it's enabled for all callers of SelectorEngine::matches() by default. This way APIs like `Element::matches()` and `Document::querySelector()` could take advantage of this optimization.

LibWeb: Use fast CSS selector matching in default matches() code path

---

Libraries/LibWeb/Layout/TreeBuilder.cpp
Libraries/LibWeb/Layout/TreeBuilder.h
Tests/LibWeb/Layout/expected/block-and-inline/button-with-abspos-pseudo-element.txt
Tests/LibWeb/Layout/expected/block-and-inline/button-with-after-pseudo.txt
Tests/LibWeb/Layout/expected/block-and-inline/button-with-before-pseudo.txt
Tests/LibWeb/Layout/expected/button-with-before-and-after-pseudo-elements.txt
Tests/LibWeb/Layout/input/button-with-before-and-after-pseudo-elements.html

This was mainly a matter of deferring the wrapping of the button's children until after its internal layout tree has been constructed. That way we don't lose any pseudo elements spawned along the way.
Visual progression on https://blt.se/ cookie banners.
Before:
After:

LibWeb: Support both ::before/::after pseudo elements on button elements

---

Libraries/LibWeb/DOM/Document.cpp

This ad-hoc code informs the client of a potentially changed page title. But because we always update the title element (either the SVG or HTML title) the client was already informed, causing the code to run twice.

LibWeb: Prevent double page title update in DOM::Document

---

Libraries/LibWeb/DOM/EventTarget.cpp
Tests/LibWeb/Text/expected/wpt-import/html/browsers/browsing-the-web/unloading-documents/beforeunload-canceling.txt
Tests/LibWeb/Text/input/wpt-import/html/browsers/browsing-the-web/unloading-documents/beforeunload-canceling.html
Tests/LibWeb/Text/input/wpt-import/html/browsers/browsing-the-web/unloading-documents/support/beforeunload-canceling-1.html

It handles the spec note to not set a event as `canceled`, if it has the type "beforeunload".
Also add the tests for [beforeunload-canceling.html](https://wpt.live/html/browsers/browsing-the-web/unloading-documents/beforeunload-canceling.html)

LibWeb: Check if event is not "beforeunload" before cancelling

---

Libraries/LibWeb/HTML/HTMLDialogElement.cpp
Tests/LibWeb/Crash/wpt-import/html/semantics/interactive-elements/the-dialog-element/dialog-requestclose-crash.html

The spec previously asserted that close watcher was not null.
This could lead to a crash in some situations,
so instead we skip to close the dialog.

LibWeb: Fix dialog.requestClose() crash

---

Libraries/LibWeb/HTML/Navigable.cpp
Libraries/LibWeb/HTML/Navigable.h
Libraries/LibWeb/HTML/NavigateEvent.cpp
Libraries/LibWeb/HTML/NavigateEvent.h
Libraries/LibWeb/HTML/NavigateEvent.idl
Libraries/LibWeb/HTML/Navigation.cpp
Libraries/LibWeb/HTML/Navigation.h
Tests/LibWeb/Text/input/wpt-import/navigation-api/navigate-event/event-constructor.html

Corresponds to https://github.com/whatwg/html/pull/10898
This is with https://github.com/whatwg/html/pull/10971 also applied - the original PR missed `sourceElement` from the `NavigateEventInit` dictionary.
I've also updated the imported WPT test as it's been recently changed to account for 10898 being merged.

LibWeb: Add NavigateEvent.sourceElement

---

Libraries/LibWeb/DOM/ElementFactory.cpp
Tests/LibWeb/Text/expected/wpt-import/custom-elements/builtin-coverage.txt
Tests/LibWeb/Text/expected/wpt-import/custom-elements/cross-realm-callback-report-exception.txt
Tests/LibWeb/Text/input/wpt-import/custom-elements/builtin-coverage.html

Fixes: http://wpt.live/custom-elements/builtin-coverage.html

LibWeb: Some fixes for constructing customized built-in elements

---

Tests/LibWeb/TestConfig.ini

It is causing whatever test that follows to time out very consistently.

LibWeb: Disable the beforeunload-canceling test for now

---

Libraries/LibCore/ArgsParser.cpp
Libraries/LibTest/JavaScriptTestRunnerMain.cpp
Libraries/LibTest/TestRunner.h
UI/Headless/Application.cpp
UI/Headless/Application.h
UI/Headless/Test.cpp

A test path is now included if it matches any of the given globs.

headless-browser: Allow the `-f` argument to be used multiple times

---

Libraries/LibJS/Runtime/Completion.h
Libraries/LibJS/Runtime/Intrinsics.cpp
Libraries/LibJS/Runtime/Intrinsics.h
Libraries/LibJS/Runtime/PromiseJobs.cpp
Libraries/LibJS/Runtime/Realm.cpp
Libraries/LibJS/Runtime/TypedArray.h
Libraries/LibJS/Tests/runtime-error-call-stack-size.js

The promise job's fulfillment / rejection handlers may push an execution
context onto the VM, which will throw an internal error if our ad-hoc
call stack size limit has been reached. Thus, we cannot blindly VERIFY
that the result of invoking these handlers is non-abrupt.
This patch will propagate any internal error forward, and retains the
condition that any other error type is not thrown.
Fixes #3449
(The first couple commits are to remove the last users of `MUST_OR_THROW_OOM` so that it may be repurposed for use in the actual fix).

LibJS: Handle call stack limit exceptions in NewPromiseReactionJob

---

Libraries/LibWeb/Animations/Animation.cpp
Libraries/LibWeb/Animations/KeyframeEffect.cpp
Libraries/LibWeb/DOM/Document.cpp

Animation should trigger repaint only if it's required by animated style update.

LibWeb: Change animation to schedule repaint only when necessary

---

Libraries/LibWeb/CSS/Parser/Tokenizer.cpp
Tests/LibWeb/Text/expected/css/getComputedStyle-url-var-serialization.txt
Tests/LibWeb/Text/input/css/getComputedStyle-url-var-serialization.html

Used by chess.com, where it stores URLs to assets in CSS URL variables. It then receives the value of them with getComputedStyle() and then getPropertyValue(). With this, it trims off the url('') wrapper with a simple slice(5, -2). Since we didn't preserve the opening quotation, it would slice off the `h` in `https` instead of the quotation.

LibWeb: Preserve opening quotation in string token original source text

---

Libraries/LibWeb/CSS/ComputedProperties.cpp
Libraries/LibWeb/CSS/ComputedProperties.h
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Libraries/LibWeb/Layout/Node.cpp

We have a lot of methods here which return `Optional<SomeKindOfEnum>` which can never actually fail, they'll always return a value. This is because even though `keyword_to_foo()` returns `Optional`, we've rejected all the invalid values at parse time. This lets us simplify the code a bit.

LibWeb: De-Optional ComputedProperties

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Libraries/LibWeb/HTML/HTMLElement.cpp
Libraries/LibWeb/HTML/HTMLElement.h
Libraries/LibWeb/HTML/HTMLScriptElement.cpp
Libraries/LibWeb/HTML/HTMLScriptElement.h

This change implements enough spec steps to block rendering until execution of sync scripts inserted from HTML parser is complete.

LibWeb: Start implementing render-blocking mechanism from HTML spec

---

Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Libraries/LibWeb/Layout/FormattingContext.cpp
Libraries/LibWeb/Layout/LayoutState.cpp
Libraries/LibWeb/Layout/LayoutState.h
Libraries/LibWeb/PixelUnits.h
Tests/LibWeb/Crash/CSS/height-calc-infinity-result.html
Tests/LibWeb/Crash/CSS/width-calc-infinity-result.html

We've historically asserted that no "saturated" size values end up as final metrics for boxes in layout. This always had a chance of producing false positives, since you can trivially create extremely large boxes with CSS.
The reason we had those assertions was to catch bugs in our own engine code where we'd incorrectly end up with non-finite values in layout algorithms. At this point, we've found and fixed all known bugs of that nature, and what remains are a bunch of false positives on pages that create very large scrollable areas, iframes etc.
So, let's change it! We now clamp content width and height of boxes to 17895700 pixels, apparently the same cap as Firefox uses.
There's also the issue of calc() being able to produce non-finite values. Note that we don't clamp the result of …

LibWeb: Clamp layout content sizes to a max value instead of crashing

---

Tests/LibWeb/Text/input/include.js

This catches errors that occur within async tests so that we fail faster
rather than timing out due to `done()` not being called.
We use `Promise.resolve()` because `f` isn't guaranteed to be an async
function.

Tests/LibWeb: Finish async test when an error is caught

---

flake.lock
shell.nix

This just brings the nixpkgs fix to the devshell.
As said https://github.com/LadybirdBrowser/ladybird/issues/371#issuecomment-2621455684, this is probably an issue with the nix libGL package or libglvnd? Im not sure

Nix: Fix OpenGL linking issue in the devshell

---

Libraries/LibWeb/HTML/HTMLInputElement.cpp
Tests/LibWeb/Text/expected/wpt-import/dom/events/Event-dispatch-click.txt

This PR checks if input is disabled before sending event.
WPT result when running: ` ./Meta/WPT.sh run dom/events/Event-dispatch-click.html`
Before
```sh
Ran 1 tests finished in 1.5 seconds.
• 0 ran as expected. 0 tests skipped.
• 1 tests had unexpected subtest results
```
After
```sh
Ran 1 tests finished in 1.3 seconds.
• 1 ran as expected. 0 tests skipped.
```

LibWeb: Check if input is disabled before submit event to form

---

Libraries/LibJS/Runtime/DateConstructor.cpp
Libraries/LibJS/Tests/builtins/Date/Date.parse.js

Apple Maps uses this date format.

LibJS: Parse dates like "1 Jan 2001 00:00:00 GMT"

---

Meta/CMake/vcpkg/overlay-ports/skia/portfile.cmake

Fixes this Skia build error on Windows: https://github.com/microsoft/vcpkg/issues/43192

Meta/CMake: Use standard attribute syntax in skia/portfile.cmake

---

Meta/CMake/vcpkg/overlay-ports/icu/portfile.cmake

icu 75.x and higher requires C++17. This change is pulled from an abandoned PR to uprev vcpkg's version to 75. Presumably the flags should be set upstream as well in their configure.ac

Meta: Pass C11 and C++17 flags to icu build on Windows

---

Libraries/LibCore/SocketAddress.h
Libraries/LibCore/SocketAddressWindows.h

Including winsock2.h in a header file is undesirable for architectural reasons, so I pulled the needed types from ws2def.h and ws2ipdef.h into a separate header.
Files inaddr.h and afunix.h are tiny and can be included directly. They each define a single struct (`in_addr` and `sockaddr_un` respectively).
I removed the `#if (_WIN32_WINNT < 0x0600)` code because it is not relevant for us. It is [intended](https://learn.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt) for Windows XP/Windows Server 2003 and earlier, but Ladybird doesn't support 32-bit, and 64-bit Windows XP is very rare.

LibCore: Fix SocketAddress.h compilation errors on Windows

---

AK/Error.cpp
AK/Error.h
AK/Types.h
Libraries/LibCore/AnonymousBufferWindows.cpp
Libraries/LibCore/EventLoopImplementationWindows.cpp
Libraries/LibCore/ProcessWindows.cpp
Libraries/LibCore/System.cpp
Libraries/LibCore/System.h
Libraries/LibCore/SystemWindows.cpp

This PR replaces #2946. It is a prerequisite for [LibIPC](https://github.com/LadybirdBrowser/ladybird/pull/2643).
Before porting LibIPC we used CRT file descriptors for files/directories/sockets and file mapping handle (cast to int) for AnonymousBuffer.
When porting LibIPC it became apparent that System::dup and System::close need to be able to work with all types of objects mentioned above.
To address this problem I created #2946 which took a safe route: it allowed to coexist CRT fds and handles by using sign bit to distinguish between them.
Also I realized that [CRT fds are better not be used for sockets](https://github.com/LadybirdBrowser/ladybird/pull/2643#issuecomment-2547541084).
I was already on edge about #2946 when I wrote it. The solution seemed a bit too convoluted for the …

LibCore: Consistently treat file descriptors as handles on Windows

---

Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/WebDriver/Capabilities.cpp
Libraries/LibWeb/WebDriver/Capabilities.h
Libraries/LibWeb/WebDriver/UserPrompt.cpp
Libraries/LibWeb/WebDriver/UserPrompt.h
Services/WebContent/WebDriverClient.ipc
Services/WebContent/WebDriverConnection.cpp
Services/WebContent/WebDriverConnection.h
Services/WebDriver/Client.cpp
Services/WebDriver/Client.h
Services/WebDriver/Session.cpp
Services/WebDriver/Session.h

WebDriver script authors may now provide either:
* A user prompt handler configuration to be used for all prompt types.
* A set of per-prompt-type user prompt handlers.
This also paves the way for interaction with the beforeunload prompt, though we do not yet support that feature in LibWeb.
This fixes ~35 subtests under `/webdriver/tests/classic/perform_actions/user_prompts.py` and `/webdriver/tests/classic/new_session/unhandled_prompt_behavior.py`.

LibWeb+WebContent+WebDriver: Allow specifying multiple prompt handlers

---

Libraries/LibJS/Runtime/Intl/DurationFormat.cpp

This is an editorial change in the Intl.DurationFormat proposal. See:
https://github.com/tc39/proposal-intl-duration-format/commit/cdef892

LibJS: Remove errant invocation to FormatNumericUnits

---

Libraries/LibWeb/Layout/TreeBuilder.cpp
Tests/LibWeb/Crash/wpt-import/css/css-contain/quote-scoping-shadow-dom-crash.html
Tests/LibWeb/Ref/expected/wpt-import/css/css-contain/reference/quote-scoping-001-ref.html
Tests/LibWeb/Ref/expected/wpt-import/css/css-contain/reference/quote-scoping-002-ref.html
Tests/LibWeb/Ref/expected/wpt-import/css/css-contain/reference/quote-scoping-003-ref.html
Tests/LibWeb/Ref/expected/wpt-import/css/css-contain/reference/quote-scoping-empty-style-boundaries-ref.html
Tests/LibWeb/Ref/expected/wpt-import/css/css-contain/reference/quote-scoping-invalidation-001-ref.html
Tests/LibWeb/Ref/expected/wpt-import/css/css-contain/reference/quote-scoping-invalidation-002-ref.html
Tests/LibWeb/Ref/expected/wpt-import/css/css-contain/reference/quote-scoping-invalidation-003-ref.html
Tests/LibWeb/Ref/expected/wpt-import/css/css-contain/reference/quote-scoping-invalidation-004-ref.html
Tests/LibWeb/Ref/input/wpt-import/css/css-contain/quote-scoping-001.html
Tests/LibWeb/Ref/input/wpt-import/css/css-contain/quote-scoping-002.html
Tests/LibWeb/Ref/input/wpt-import/css/css-contain/quote-scoping-003.html
Tests/LibWeb/Ref/input/wpt-import/css/css-contain/quote-scoping-004.html
Tests/LibWeb/Ref/input/wpt-import/css/css-contain/quote-scoping-empty-style-boundaries.html
Tests/LibWeb/Ref/input/wpt-import/css/css-contain/quote-scoping-invalidation-001.html
Tests/LibWeb/Ref/input/wpt-import/css/css-contain/quote-scoping-invalidation-002.html
Tests/LibWeb/Ref/input/wpt-import/css/css-contain/quote-scoping-invalidation-003.html
Tests/LibWeb/Ref/input/wpt-import/css/css-contain/quote-scoping-invalidation-004.html

This makes it so that the effects of the 'content' property’s 'open-quote', 'close-quote', 'no-open-quote' and 'no-close-quote' are scoped to an element’s sub-tree if it has style containment, as demanded by the spec.
I've imported the 10 additional web platform tests that this makes us pass.

LibWeb: Make style containment influence quotes

---

Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/CSS/StyleInvalidationData.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h
Tests/LibWeb/TestConfig.ini

With this change, siblings of an inserted node are no longer invalidated
unless the insertion could potentially affect their style. By
"potentially affected," we mean elements that are evaluated against the
following selectors during matching:
- Sibling combinators (+ or ~)
- Pseudo-classes :first-child and :last-child
- Pseudo-classes :nth-child, :nth-last-child, :nth-of-type, and
:nth-last-of-type

LibWeb: Optimize style invalidation caused by DOM structural changes

---

Libraries/LibWeb/DOM/Node.cpp

By moving layout tree invalidation into post connection hook in
https://github.com/LadybirdBrowser/ladybird/commit/f7a3f785a84632116c290e84907654a575d558bc we no longer invalidate layout tree of the parent of inserted
node. Likely that's the reason why newly imported tests for css
containment invalidation are flaky.

LibWeb: Move layout tree invalidation back in `Node::insert_before()`

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/namespace-objects-default-property-attributes.txt
Tests/LibWeb/Text/input/namespace-objects-default-property-attributes.html

This matches the prototype attributes.
Used by https://chatgpt.com/, where it runs this code:
```js
CSS.supports('animation-timeline: --works')
```
If this returns false, it will attempt to polyfill Animation Timeline and override CSS.supports to support Animation Timeline properties.

LibWeb: Make namespace attributes writable and configurable by default

---

Meta/CMake/vcpkg/generate_vcpkg_toolchain_variables.cmake

Adds simple vcpkg triplet detection on Windows. This allows for the configure step to succeed.

Meta: Add vcpkg triplet detection for Windows

---

Tests/LibWeb/Text/expected/wpt-import/custom-elements/upgrading.txt
Tests/LibWeb/Text/input/wpt-import/custom-elements/resources/empty-html-document.html

Which was causing tests to fail in our WPT import.

Tests/LibWeb: Add missing empty html document resource for test

---

AK/FlyString.h
Libraries/LibWeb/Editing/ExecCommand.cpp
Tests/LibWeb/Text/expected/Editing/execCommand-case-insensitivity.txt
Tests/LibWeb/Text/input/Editing/execCommand-case-insensitivity.html

This fixes ~80 WPT subtests in `editing`.

 LibWeb: Treat `execCommand` command names as case insensitive

---

Libraries/LibJS/Runtime/RegExpLegacyStaticProperties.cpp
Libraries/LibJS/Runtime/RegExpLegacyStaticProperties.h

These properties are always substrings of the RegExp input string, and so we can store them as views and lazily construct strings if they're actually accessed (which most of the time they aren't).
This avoids a bunch of unnecessary memory copying, saving roughly 2.1 seconds per iteration of Speedometer.

LibJS: Allocate RegExp.{lastMatch,leftContext,rightContext} lazily

---

Libraries/LibWeb/WebAudio/AudioBuffer.cpp
Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-audiobuffer-interface/audiobuffer-copy-channel.txt
Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-audiobuffer-interface/audiobuffer-copy-channel.html

The spec steps for `copyFromChannel()` or `copyToChannel()` don't explicitly prohibit this, but the [acquire the content]( https://webaudio.github.io/web-audio-api/#acquire-the-content) steps are used to prevent altering the data of an active buffer - using a shared buffer circumvents this mechanism.
Relevant issue: https://github.com/WebAudio/web-audio-api/issues/2565

LibWeb: Prevent AudioBuffer data being copied to or from a shared buffer

---

Libraries/LibWeb/Page/Page.cpp
Tests/LibWeb/Text/expected/HTML/Window-find-clear-selection.txt
Tests/LibWeb/Text/input/HTML/Window-find-clear-selection.html

Previously, if the user made a find-in-page query, then cleared the selection made by that query, subsequent queries would inadvertently advance to the next match instead of reselecting the first match.

LibWeb: Reset find-in-page index if selection is cleared

---

Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
Tests/LibWeb/Text/expected/wpt-import/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/quirks.window.txt
Tests/LibWeb/Text/input/wpt-import/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/quirks.window.html
Tests/LibWeb/Text/input/wpt-import/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/quirks.window.js

This fixes a crash in the included test that regressed in 0adf261, and is hit by the following HTML:
```html
<body></body>
<script>
const frame = document.body.appendChild(document.createElement("iframe"));
frame.contentDocument.open();
const child = frame.contentDocument.createElement("html")
const html = frame.contentDocument.appendChild(child);
frame.contentDocument.close();
</script>
```
I am not 100% sure this is fully the correct fix and there are other cases which would not work properly. But it's definitely an improvement to make the confuisingly named 'insert_an_eof' function of the tokenizer actually do something.

LibWeb/HTML: Bail from HTML parsing when EOF hit on document.close

---

Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/CSS/StyleInvalidationData.cpp
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h

The current implementation of `:has()` style invalidation is divided into two cases:
- When used in subject position (e.g., `.a:has(.b)`).
- When in a non-subject position (e.g., `.a > .b:has(.c)`).
This change focuses on improving the first case. For non-subject usage, we still perform a full tree traversal and invalidate all elements affected by the `:has()` pseudo-class invalidation set.
We already optimize subject `:has()` invalidations by limiting invalidated elements to ones that were tested against `has()` selectors during selector matching. However, selectors like `div:has(.a)` currently cause every div element in the document to be invalidated. By modifying the invalidation traversal to consider only ancestor nodes (and, optionally, their siblings), we can drastically reduce the …

LibWeb: Narrow `:has()` style invalidation to ancestor nodes

---

Libraries/LibWeb/Layout/FlexFormattingContext.cpp

This was an old hack from before we understood how and when to resolve percentages in flex layout. Removing it should not change anything, but it does avoid a lot of redundant layout work on many pages.

LibWeb: Remove unnecessary re-measurement of cross sizes in flex layout

---

Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h

Moves pseudo class matching helpers into Element methods, so they don't have to be duplicated between SelectorEngine and function that checks if element is included in invalidation set.

LibWeb: Deduplicate code for pseudo class selector matching

---

Libraries/LibWeb/DOM/Document.cpp
Tests/LibWeb/Text/expected/wpt-import/html/browsers/browsing-the-web/scroll-to-fragid/fragment-and-encoding-2.txt
Tests/LibWeb/Text/expected/wpt-import/html/browsers/browsing-the-web/scroll-to-fragid/fragment-and-encoding.txt
Tests/LibWeb/Text/expected/wpt-import/html/browsers/browsing-the-web/scroll-to-fragid/scroll-frag-non-utf8-encoded-document.txt
Tests/LibWeb/Text/input/wpt-import/html/browsers/browsing-the-web/scroll-to-fragid/fragment-and-encoding-2.html
Tests/LibWeb/Text/input/wpt-import/html/browsers/browsing-the-web/scroll-to-fragid/fragment-and-encoding.html
Tests/LibWeb/Text/input/wpt-import/html/browsers/browsing-the-web/scroll-to-fragid/scroll-frag-non-utf8-encoded-document.html

We were previously crashing instead of using the replacement
character on invalid bytes.

LibWeb/DOM: Add missing UTF-8 decode without BOM on fragment ID

---

Services/WebContent/WebDriverConnection.cpp
Services/WebContent/WebDriverConnection.h

Executing scripts via WebDriver has a bit of awkwardness around dealing with user dialogs that open during script execution. When this happens, we must return control back to the client immediately with a null response, while allowing the script to continue executing. When the script completes, we must then ignore its result.
We've previously handled this by tracking a boolean for the ongoing script execution, set to true when the script begins and false when it ends (either via normal script completion or the above dialog handling). However, this failed to handle the following scenario, running two scripts in a row:
```python
execute_script("alert('hi'); return 1;")
execute_script("return 2;")
```
The first script would execute and open a dialog, and thus return a null response to the …

WebContent: Track the ongoing script execution with an ID

---

Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Libraries/LibWeb/HTML/HTMLMediaElement.h
Libraries/LibWeb/HTML/HTMLMediaElement.idl
Tests/LibWeb/Text/expected/wpt-import/html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/embedded-content/media-elements/playing-the-media-resource/playbackRate.html

Implements the `playbackRate` and `defaultPlaybackRate` attributes of the HTMLMediaElement.
Note that currently, the only supported playbackRate is 1. Trying to set any others throws a "NotSupportedError" DOMException, as per [the spec](https://html.spec.whatwg.org/multipage/media.html#dom-media-playbackrate).
Somehow, this makes us pass the web platform test for this so I've imported that.
Mainly did this cause it continuously spams the console on Youtube videos so having a basic implementation will probably make debugging Youtube easier.

LibWeb: Implement playbackRate

---

Libraries/LibWeb/HTML/HTMLDialogElement.cpp
Libraries/LibWeb/HTML/HTMLDialogElement.h

Corresponds to https://github.com/whatwg/html/pull/10961

LibWeb/HTML: Extract dialog show_modal() into its own algorithm

---

Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/DOM/Node.h
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.h
Tests/LibWeb/Text/expected/wpt-import/css/selectors/open-pseudo.txt
Tests/LibWeb/Text/input/wpt-import/css/selectors/open-pseudo.html

This works when testing it manually, but I can't seem to figure out how to make an automated test for it unfortunately.
I've imported the existing WPT test for `:open` but it doesn't cover `<input>`, and possibly never will as the behaviour of different input types is largely UA-defined. We fail the subtest for `<select>` too, and that also works when done manually.

LibWeb: Make `:open` target color and file inputs with an open picker

---

Libraries/LibWeb/HTML/TraversableNavigable.cpp

This more directly catches the bug we have that causes this assertion to happen on certain sites and WPT tests.

LibWeb/HTML: Improve assertion for apply the history step mismatch

---

Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
Libraries/LibThreading/BackgroundAction.h
Services/ImageDecoder/ConnectionFromClient.cpp

We have to be careful to always destroy the jpeglib decompression struct
before returning from `JPEGLoadingContext::decode`. We were doing this in
jpeglib error handlers, but we have a couple of paths that bail from the
decoder via TRY. These paths were neither cleaning up memory nor setting
the image decoder to an error state.
So this patch sets up a scope guard to ensure we free the decompressor
upon exit from the function. And it delegates the responsibility of
setting the decoder state to the caller (of which there is only one),
to ensure all error paths result in an error state.
When loading a [test image](https://examplefile.com/image/jpg/100-mb-jpg) that we failed to decode, the memory use of ImageDecoder would previously rise to nearly 10GB and remain there:

ImageDecoder+LibThreading: Fix ImageDecoder memory leaks

---

Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/WebDriver/Capabilities.cpp
Libraries/LibWeb/WebDriver/Capabilities.h
Libraries/LibWeb/WebDriver/Proxy.cpp
Libraries/LibWeb/WebDriver/Proxy.h
Services/WebContent/WebDriverConnection.cpp
Services/WebDriver/Client.cpp
Services/WebDriver/Client.h
Services/WebDriver/Session.cpp
Services/WebDriver/Session.h

Fixes ~45 subtests under `/webdriver/tests/classic/new_session`. The remaining failures are, I think, invalid tests (I've opened an issue in the WPT repo already).

WebDriver: Miscellaneous fixes around session creation and capability validation

---

Libraries/LibURL/Pattern/Pattern.h
Libraries/LibWeb/Animations/AnimationEffect.idl
Libraries/LibWeb/Encoding/TextEncoder.idl
Libraries/LibWeb/HTML/Navigation.idl
Libraries/LibWeb/URLPattern/URLPattern.cpp
Libraries/LibWeb/URLPattern/URLPattern.h
Libraries/LibWeb/URLPattern/URLPattern.idl
Libraries/LibWeb/WebAudio/AudioContext.idl
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp

This fixes enough in the IDL generator to get the IDL for URLPattern.exec compiling, which is the bulky part of the interface.

LibURL+LibWeb: Add a stub for URLPattern.exec, along with some corresponding IDL generator fixes

---

AK/WeakPtr.h
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/DOM/Node.cpp

`invalidate_style()` already tries to avoid scheduling invalidation for
`:has()` by checking result of `may_have_has_selectors()`, but it might
still result in unnecessary work because `may_have_has_selectors()`
does not force building of rules cache. This change adds
`have_has_selectors()` that forces building of rules cache and is
invoked in `update_style()` to double-check whether we actually need to
process scheduled `:has()` invalidations.
This allows to skip ~100000 ancestor traversals on this WPT test:
https://wpt.live/html/select/options-length-too-large.html

LibWeb: Skip pending :has() invalidation if there is no :has()

---

Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl

We don't implement the affected algorithms, and so the only change to apply here is adding the dictionary member to IDL.
Corresponds to https://github.com/whatwg/html/commit/a5853ca8fa828ee9c13907146ee5fd118da56df2

LibWeb/HTML: Add CanvasColorType

---

AK/String.cpp
AK/String.h
Libraries/LibWeb/CSS/ComputedProperties.cpp
Libraries/LibWeb/CSS/ComputedValues.h
Libraries/LibWeb/CSS/Enums.json
Libraries/LibWeb/CSS/Properties.json
Libraries/LibWeb/CSS/StyleValues/CounterStyleValue.cpp
Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Libraries/LibWeb/Layout/ListItemMarkerBox.cpp
Libraries/LibWeb/Layout/ListItemMarkerBox.h
Libraries/LibWeb/Painting/MarkerPaintable.cpp
Tests/LibWeb/Ref/expected/wpt-import/css/css-lists/list-style-type-string-004-ref.html
Tests/LibWeb/Ref/input/wpt-import/css/css-lists/list-style-type-string-004.html

Fixes #3487.
We've long claimed to support this, but then silently ignored string values, until 4cb20635771a54f59cdb36616dbdcbd402ef080e which would not-so-silently crash instead. (Oops)
So, actually pass the string value along and use it in the list marker.
As part of this, rename our `list-style-type` enum to `counter-style-name-keyword`. This is an awkward name, attempting to be spec-based. (The spec says `<counter-style>`, which is either a `<counter-style-name>` or a function, and the `<counter-style-name>` is a `<custom-ident>` that also has a few predefined values. So this is the best I could come up with.)
Unfortunately only one WPT test for this passes - the others fail because we produce a different layout when text is in `::before` than when it's in `::marker`, and similar …

LibWeb: Implement `list-style-type: "string goes here";`

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h

This commit changes the strategy for updating inherited styles. Instead of marking all potentially affected nodes during style invalidation, the decision is now made on-the-fly during style recalculation. Child nodes will only have their inherited styles recalculated if their parent's properties have changed.
On Discord this allows to 1000x reduce number of nodes with recalculated inherited style.

LibWeb: Optimize inherited style update

---

Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Libraries/LibWeb/Layout/FlexFormattingContext.h
Libraries/LibWeb/Layout/GridFormattingContext.cpp
Libraries/LibWeb/Layout/GridFormattingContext.h
Libraries/LibWeb/Layout/LayoutState.h

The `get()` and `get_mutable()` APIs on `LayoutState::UsedValues` enable arbitrary access to the used values of any layout node during layout, even layout nodes outside the scope of the current formatting context.
To enable new layout optimizations like subtree layout caching, we need to stop having arbitrary dependencies between layout nodes.
This PR is one of many steps towards that goal. It doesn't go all the way, a lot more work will be required.

Reduce calls to LayoutState::UsedValues::get*()

---

Libraries/LibWeb/Crypto/SubtleCrypto.cpp
Libraries/LibWeb/Crypto/SubtleCrypto.h

All `SubtleCrypto` methods except `import_key` do not require `JS::ThrowCompletionOr` as they return only rejected promises.

LibWeb: Remove useless `JS::ThrowCompletionOr` return types in SubtleCrypto

---

Tests/LibWeb/TestConfig.ini

The WPT runner uses this mechanism to delay test completion. This is not supported by our runner and causes tests that use it to be flaky.

Tests: Skip tests that rely on the reftest-wait mechanism

---

Libraries/LibWasm/AbstractMachine/AbstractMachine.h
Libraries/LibWasm/CMakeLists.txt

After excluding Wasi.cpp on Windows I kept getting these link errors, but then they disappeared after I `touch`ed Forward.h.
```
lld-link : error : <root>: undefined symbol: class ValueType::ValueType Wasm::Wasi::ABI::CompatibleValueType<char> [E:\Users\stas\Projects\ladybird\lb\Build\release\Lagom\Libraries\LibWasm\LibWasm.vcxproj]
lld-link : error : <root>: undefined symbol: class ValueType::ValueType Wasm::Wasi::ABI::CompatibleValueType<short> [E:\Users\stas\Projects\ladybird\lb\Build\release\Lagom\Libraries\LibWasm\LibWasm.vcxproj]
lld-link : error : <root>: undefined symbol: class ValueType::ValueType Wasm::Wasi::ABI::CompatibleValueType<int> [E:\Users\stas\Projects\ladybird\lb\Build\release\Lagom\Libraries\LibWasm\LibWasm.vcxproj]
lld-link : error : <root>: undefined symbol: class …
```

LibWasm: Port to Windows

---

Libraries/LibWeb/HTML/HTMLSelectElement.cpp

This hides the items in a select's dropdown, if the related HTML elements have the hidden attribute set.
To my knowledge, there is no section in the spec that demands this specifically, but [the spec](https://html.spec.whatwg.org/#attr-hidden) says that "User agents should not render elements that are in the [hidden](https://html.spec.whatwg.org/#attr-hidden-hidden-state) state" and this behavior matches Firefox an Chrome.
Not sure how to test, given the inherent UI-ness of this.
Fixes a dropdown at https://battle.crossuniverse.net/deckMaker/

LibWeb: Hide hidden select children from dropdown

---

Libraries/LibWeb/DOM/Element.cpp
Services/WebContent/ConnectionFromClient.cpp

Fixes #2432.
Just to demonstrate, here's me inspecting a `::marker` with `color: orange` set on it, and seeing that show up in the inspector. (It's hard to see the actual orange colour because of the highlight but it is there I promise. :laughing: )
I believe `::marker` is the only generated pseudo-element that did not already have its computed style cached, so this shouldn't affect any other pseudo-elements. However, to avoid such crashes, I've changed the inspection code to print a debug message instead of trying to deref a null ComputedProperties pointer.

Make `::marker` pseudo-elements inspectable without crashing

---

Libraries/LibWeb/DOM/Node.cpp
Tests/LibWeb/Text/expected/css/invalidate-sibling-affected-by-has.txt
Tests/LibWeb/Text/input/css/invalidate-sibling-affected-by-has.html

Fixes underinvalidaiton of `:has()` selectors with sibling combinators.

LibWeb: Check all siblings in ancestors chain while invalidating :has()

---

Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Element.idl

Corresponds to https://github.com/w3c/csswg-drafts/pull/11673 , with the addition of the fixes in https://github.com/w3c/csswg-drafts/pull/11701
No observable changes as we still only support scrolling the viewport itself.

LibWeb/DOM: Add container option to scrollIntoView options

---

Libraries/LibWeb/DOM/Event.cpp

Corresponds to https://github.com/whatwg/dom/commit/cbf4c0d6b4fdb09372f170cfc152d2a160173474
The assert is a little different, because we do know it's an EventTarget pointer, but it could be null.

LibWeb/DOM: Assert that composed_path() currentTarget is non-null

---

Libraries/LibCore/ResourceImplementation.cpp
Libraries/LibCore/ResourceImplementationFile.cpp
Libraries/LibCore/System.h
Libraries/LibCore/SystemWindows.cpp
Libraries/LibFileSystem/CMakeLists.txt
Libraries/LibFileSystem/FileSystem.cpp
Libraries/LibWeb/HTML/MessagePort.cpp
Libraries/LibWeb/HTML/WorkerAgent.cpp

This fixes only errors in the code. CMakeLists.txt still has problems (it tries to compile Ladybird idl with MIDL compiler):
```
Build\release\Lagom\Libraries\LibWeb\CSS\GeneratedCSSStyleProperties.idl(2): error MIDL2025: syntax error : expecting { near "GeneratedCSSStyleProperties" [Build\release\Lagom\Libraries\LibWeb\LibWeb.vcxproj]
```

LibWeb: Port to Windows

---

Libraries/LibImageDecoderClient/Client.h
Libraries/LibRequests/RequestClient.h
Libraries/LibWebView/HelperProcess.cpp
Libraries/LibWebView/WebContentClient.h
Services/ImageDecoder/ConnectionFromClient.cpp
Services/ImageDecoder/ConnectionFromClient.h
Services/ImageDecoder/ImageDecoderServer.ipc
Services/RequestServer/ConnectionFromClient.cpp
Services/RequestServer/ConnectionFromClient.h
Services/RequestServer/RequestServer.ipc
Services/WebContent/ConnectionFromClient.cpp
Services/WebContent/ConnectionFromClient.h
Services/WebContent/WebContentServer.ipc
Services/WebContent/main.cpp

This is logically part of #2643. That PR is already big, so I decided to split this part of functionality into a separate PR.
Transport socket needs to know the pid of the process holding the other end of a socket pair to pass handles between processes. Both DuplicateHandle and WSADuplicateSocket require target process pid.
This PR implements only the minimal code required to run headless browser. It doesn't initialize WebDriver connection or connections in LibWeb.
IPC compiler doesn't support conditional compilation, so init_transport message is present on Linux too.
Note: [This method](https://stackoverflow.com/a/25431340) doesn't work because `dwOwningPid` is "The PID of the process that issued a context bind for this TCP connection" …

LibWebView+ImageDecoder+RequestServer+WebContent: Add init_transport

---

Base/res/ladybird/inspector.css
Base/res/ladybird/inspector.js
Libraries/LibWebView/InspectorClient.cpp

This adds a simple input above the properties table to filter them.
How it looks:
https://github.com/user-attachments/assets/f5f43194-de0e-4cee-93ec-47d4eedfdb04

Inspector: Add ability to filter css properties

---

Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h

Instead of checking all elements in a document for containment in `:has()` invalidation set, we could narrow this down to ancestors and ancestor siblings, like we already do for subject `:has()` invalidation.
This change brings great improvement on GitHub that has selectors with non-subject `:has()` and sibling combinators (e.g., `.a:has(.b) ~ .c`) which prior to this change meant style invalidation for whole document.

LibWeb: Avoid full tree traversal for non-subject `:has()` invalidation

---

Libraries/LibWeb/WebAudio/AnalyserNode.cpp
Tests/LibWeb/Crash/WebAudio/AnalyserNode-previous-block-initialization.html

Previously, we attempted to read from `m_previous_block` without initializing it to the correct size.

LibWeb: Initialize AnalyserNode previous block at construction time

---

Libraries/LibJS/Bytecode/Generator.cpp
Libraries/LibJS/Tests/classes/class-inheritance.js

This snippet crashes during bytecode generation due to `emit_super_reference` not correctly generating the reference record for the property access.
```js
class Foo {
constructor() {
super.bar += "1337";
}
}
new Foo();
```

LibJS: Fix bytecode generation for super property stores and loads

---

Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Libraries/LibWeb/HTML/EventLoop/EventLoop.h
Libraries/LibWeb/Page/InputEvent.h
Libraries/LibWeb/Page/Page.h
Libraries/LibWeb/SVG/SVGDecodedImageData.h
Services/WebContent/ConnectionFromClient.cpp
Services/WebContent/ConnectionFromClient.h
Services/WebContent/PageClient.cpp
Services/WebContent/PageClient.h
Services/WebWorker/PageHost.h

Our existing coalescing mechanism for input events didn't prevent multiple mousemove/mousewheel events from being processed between paint cycles. Since handling these events can trigger style & layout updates solely for hit-testing purposes, we might end up doing work that won't be observable by a user and could be avoided by shceduling input events processing to happen right before painting the next frame.

LibWeb: Schedule input event processing on HTML event loop

---

Libraries/LibWeb/HTML/Navigable.cpp

I have no idea how to test this, or what impact it has exactly, but it's definitely closer to what the spec asks us to do.

LibWeb: Fix steps for finding a navigable by target name

---

Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
Tests/LibWeb/Text/expected/css/var-uses-fallback-value-if-custom-property-is-empty.txt
Tests/LibWeb/Text/input/css/var-uses-fallback-value-if-custom-property-is-empty.html

If the expansion of a custom property in variable expansion returns tokens, then the custom property is not the initial guaranteed-invalid value.
If it didn't return any tokens, then it is the initial guaranteed-invalid value, and thus we should move on to the fallback value.
Makes Shopify checkout show the background colours, borders, skeletons, etc.
Before:
After:

LibWeb/CSS: Use fallback var() value if custom property is empty

---

Base/res/ladybird/inspector.css

IMO the default colors used by the dark color scheme do not look good in the Inspector window.
Before:
After:

Base: Revert usage of color-scheme in the Inspector

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/HTML/HTMLElement.cpp
Tests/LibWeb/Text/data/base/a-element-target-sub-alt.html
Tests/LibWeb/Text/data/base/a-element-target-sub-sub.html
Tests/LibWeb/Text/data/base/a-element-target-sub.html
Tests/LibWeb/Text/expected/base/a-element-target.txt
Tests/LibWeb/Text/input/base/a-element-target.html

This makes [johnvertisements](https://john.citrons.xyz/) work properly in ladybird.

LibWeb: Make a elements honor base element's target

---

Libraries/LibJS/Runtime/RegExpPrototype.cpp
Libraries/LibJS/Tests/builtins/RegExp/RegExp.js

If the regex always matches the input, even if it's past the end, then we need to stop execution of the regex when it's past the end. This corresponds to step 13.a and prevents it from infinitely looping.
Reduced from: https://github.com/Shopify/quilt/blob/d98672060fc724f3fe7af9a25a0845b8d7c0774a/packages/react-i18n/src/utilities/money.ts#L10-L14

LibJS: Stop executing successful regex if it's past the end of the input

---

Libraries/LibGfx/Rect.h
Libraries/LibWeb/DOM/Document.cpp
Tests/LibWeb/Text/expected/wpt-import/intersection-observer/edge-inclusive-intersection.txt
Tests/LibWeb/Text/input/wpt-import/intersection-observer/edge-inclusive-intersection.html
Tests/LibWeb/Text/input/wpt-import/intersection-observer/resources/intersection-observer-test-utils.js

This fixes an issue where 0x0 rectangles were not considered to be intersecting, even when they fell inside (or were adjacent to) the viewport.

LibWeb+LibGfx: Make IntersectionObserver checks edge-inclusive

---

Libraries/LibWeb/CSS/ComputedValues.h
Libraries/LibWeb/Layout/Node.cpp
Tests/LibWeb/Ref/expected/tables-width-z-index-ref.html
Tests/LibWeb/Ref/input/tables-with-z-index.html

When drawing a table, some of the CSS properties must be moved from the table grid box to an anonamyous table wrapper box. One of these properties is `position`. `z-index` however is not. This leads to the following behavior if a table has both `position` and `z-index`:
* The wrapper box has the `position`, but a `z-index` of `auto`.
* The grid box has the `z-index`, but `position: static`.
This effectively means that the `z-index` property is ignored since it has no effect on non-positioned elements. This behavior contradicts what other browsers do and causes layout issues on websites.
To align Ladybird behavior with other browser this commit also moves the `z-index` property to the wrapper box.
Fixes #3533.

LibWeb: Move `z-index` to table wrapper box

---

Services/RequestServer/ConnectionFromClient.cpp

Previously, we were passing in the serialized value which included square brackets but that isn't a valid IPV6 address.
Partially addresses #3596

RequestServer: Remove IPV6 bracket notation on host before resolving

---

CMakeLists.txt
Services/RequestServer/CMakeLists.txt
Services/WebContent/CMakeLists.txt
Services/WebDriver/CMakeLists.txt
Services/WebWorker/CMakeLists.txt
UI/CMakeLists.txt
UI/Headless/Test.cpp

I pulled a commit from https://github.com/LadybirdBrowser/ladybird/pull/3571 to fix OpenSSL linkage on Fedora. That change fixes two WebCryptoAPI tests on any distro that has disabled SHA-1 in the distro-provided OpenSSL library.
The second commit establishes that yes, Screenshot tests are only reproducible on x86_64 Linux. And probably only with glibc as well, though I'll wait for someone with Alpine to verify that.

Meta+UI: Some fixes for Fedora Asahi 41

---

Base/res/ladybird/inspector.css
Base/res/ladybird/inspector.js

A few tweaks to make the new filtering feature feel nicer to use:
- Keep property filter across tabs
- Do less work when filtering properties
- Preserve zebra-striping when hiding table rows
- Keep current property filter when switching selected node

Inspector: Improve property filtering

---

Libraries/LibWeb/CSS/ComputedProperties.cpp
Libraries/LibWeb/Page/EventHandler.cpp

Fixes #3567.
We don't support url/custom cursors, use the default instead of crashing. 
Also clean up a bit of dead code from when Cursor was optional.

LibWeb: Prevent crash with custom cursor

---

Libraries/LibIPC/Message.h
Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp

Previously, all IPC message structs would initialize their members with `{}` so that they would still have a value if the message was invalid. However, we don't ever construct invalid messages, so we can remove the code for constructing them and checking their validity; and then also remove this `{}` initialization. That means something like `Variant<int, String>` can now be sent over IPC.

IPCCompiler: Allow arguments that are not default-constructible

---

Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/Dump.cpp
Libraries/LibWeb/Layout/LayoutState.cpp
Libraries/LibWeb/Layout/Node.h
Libraries/LibWeb/Painting/BoxModelMetrics.cpp
Libraries/LibWeb/Painting/BoxModelMetrics.h
Libraries/LibWeb/Painting/PaintableBox.h
Services/WebContent/ConnectionFromClient.cpp

This was a weird case of layout results being stored in the layout tree instead of in the paint tree like everything else.

LibWeb: Store final box model metrics in paint tree, not layout tree

---

Libraries/LibWeb/Animations/KeyframeEffect.cpp
Libraries/LibWeb/DOM/Element.cpp

This allows to skip lots of unnecessary work required for animated style update.

Early return from style update when invalidations=none

---

Libraries/LibURL/CMakeLists.txt
Libraries/LibURL/Pattern/Component.h
Libraries/LibURL/Pattern/Pattern.cpp
Libraries/LibURL/Pattern/Pattern.h
Libraries/LibWeb/URLPattern/URLPattern.cpp
Libraries/LibWeb/URLPattern/URLPattern.h
Libraries/LibWeb/URLPattern/URLPattern.idl

This implements the simple getters of the URLPattern interface. Next steps after this are the actual meat of the URLPattern interface which are the two different parsers and the tokenizer which are needed to implement the constructor. From the constructed URLPattern a regex match can be made on a URL.

LibWeb+LibURL: Implement the simple IDL functions for URLPattern

---

Libraries/LibWeb/HTML/HTMLHRElement.cpp
Tests/LibWeb/Ref/expected/wpt-import/html/rendering/non-replaced-elements/the-hr-element-0/align-ref.html
Tests/LibWeb/Ref/expected/wpt-import/html/rendering/non-replaced-elements/the-hr-element-0/color-ref.html
Tests/LibWeb/Ref/input/wpt-import/html/rendering/non-replaced-elements/the-hr-element-0/align.html
Tests/LibWeb/Ref/input/wpt-import/html/rendering/non-replaced-elements/the-hr-element-0/color.html

This PR applies presentational hints for the `align`, `color` and `noshade` attributes of `HTMLHRElement`.
This fixes all remaining WPT tests in https://wpt.live/html/rendering/non-replaced-elements/the-hr-element-0/

Libweb: Apply some `HTMLHRElement` presentational hints

---

Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Libraries/LibWeb/HTML/HTMLMediaElement.h
Libraries/LibWeb/HTML/HTMLMediaElement.idl
Libraries/LibWeb/HTML/TimeRanges.cpp
Libraries/LibWeb/HTML/TimeRanges.h

This implements `HTMLMediaElement.seekable()`, all features of [TimeRanges](https://html.spec.whatwg.org/multipage/media.html#time-ranges), and a stub for `HTMLMediaElement.played()`.
Youtube tries to access all of these when loading a video, though I don't think this actually gets us closer to actually playing the video.
The [web platform test for this](https://wpt.live/media-source/mediasource-seekable.html) still fails for unrelated reasons, so I haven't imported it.

LibWeb: Implement more things needed for Youtube

---

Libraries/LibWeb/HTML/ValidityState.cpp
Tests/LibWeb/Crash/HTML/validity-attribute.html

Fixes a crash in: https://wpt.live/html/dom/idlharness.https.html?exclude=(Document\|Window|HTML.+)

LibWeb: Remove unintentional recursion in `ValidityState::valid`

---

Libraries/LibWeb/Layout/TreeBuilder.cpp
Tests/LibWeb/Ref/expected/block-element-inside-inline-element-ref.html
Tests/LibWeb/Ref/input/block-element-inside-inline-element.html

When restructuring inline nodes because of a block element insertion during the layout tree build, we might end up with a `display: contents` element in the ancestor stack that is not part of the actual layout tree, since it's never actually used as a parent for any node. Because we were only rewinding the ancestor stack with actual new layout nodes, it became corrupted and layout nodes were added to the wrong parent.
This new logic leaves the ancestor stack intact, only replacing layout nodes whenever a new one is created.
Fixes the sidebar on https://reddit.com.
Fixes #3590.

LibWeb: Retain `display: contents` in ancestor stack for continuations

---

Libraries/LibWeb/Layout/Node.cpp
Libraries/LibWeb/Layout/Node.h
Libraries/LibWeb/Layout/TreeBuilder.cpp
Tests/LibWeb/Crash/Layout/svg-box-no-inline-continuation.html
Tests/LibWeb/Layout/expected/svg/svg-foreign-object-with-block-element.txt
Tests/LibWeb/Layout/input/svg/svg-foreign-object-with-block-element.html

Fixes #3453 and #3395, both involving https://discord.com.

LibWeb: Resolve SVG issues with inline continuation

---

Libraries/LibCrypto/BigInt/Algorithms/BitwiseOperations.cpp
Libraries/LibCrypto/BigInt/Algorithms/UnsignedBigIntegerAlgorithms.h
Libraries/LibCrypto/BigInt/SignedBigInteger.cpp
Libraries/LibCrypto/BigInt/SignedBigInteger.h
Libraries/LibCrypto/BigInt/UnsignedBigInteger.cpp
Libraries/LibCrypto/BigInt/UnsignedBigInteger.h
Libraries/LibJS/Runtime/BigIntConstructor.cpp
Libraries/LibJS/Tests/builtins/BigInt/BigInt.asIntN.js
Libraries/LibJS/Tests/builtins/BigInt/BigInt.asUintN.js

`BigInt.asIntN` and `BigInt.asUintN` use both use `SignedBigInteger::shift_left` which is subject to allocation failures.
So the following crashes (On my machine):
```js
BigInt.asIntN(0x4000000000000, 1n);
```

LibJS+LIbCrypto: Propogate allocation errors in BigInt constructor functions

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Element.h

Instead of using `has_pseudo_elements()` that iterates over all pseudo elements, only check if `::before` or `::after` are present.
Before this change, `has_pseudo_elements()` was 10% of profiles on Discord while now it's 1-2%.

LibWeb: Optimize pseudo elements presence check in hover style update

---

Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/DOM/Document.cpp

Before this change, we did the following:
1. Created a bitmap with the matching state for each rule containing
`:hover`.
2. Changed the actively hovered element in the document.
3. Created another bitmap with the matching state for each rule
containing `:hover`.
With this change, we iterate rule by rule and compare the matching
state. This allows us to break early once we find the first rule whose
matching state changes after the hovered element update. Additionally,
this removes the need to allocate a bitmap.

Break early from rule testing in hover style invalidation

---

Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
Tests/LibWeb/Text/expected/wpt-import/xhr/formdata/constructor-formelement.txt
Tests/LibWeb/Text/input/wpt-import/xhr/formdata/constructor-formelement.html

This PR updates how FormData entry lists are constructed to comply with the spec. The method constructing an entry list did not call the spec-compliant `create_entry`, instead creating the `XHR::FormDataEntry` manually, resulting in entry names not being converted into scalar value strings as they should have been.
Fixes a WPT test! https://wpt.fyi/results/xhr/formdata/constructor-formelement.html

LibWeb: Use create_entry when constructing FormData entry list

---

Libraries/LibWeb/HTML/AttributeNames.h
Libraries/LibWeb/HTML/HTMLTableElement.cpp
Libraries/LibWeb/HTML/HTMLTableSectionElement.cpp
Tests/LibWeb/Ref/expected/wpt-import/html/rendering/non-replaced-elements/tables/table-bordercolor-001-ref.html
Tests/LibWeb/Ref/expected/wpt-import/html/rendering/non-replaced-elements/tables/table-row-group-height-ref.html
Tests/LibWeb/Ref/input/wpt-import/html/rendering/non-replaced-elements/tables/table-bordercolor-001.html
Tests/LibWeb/Ref/input/wpt-import/html/rendering/non-replaced-elements/tables/table-row-group-height.html

This PR applies the presentational hint for `HTMLTableElement`'s `bordercolor` attribute and `HTMLTableSectionElement`'s `height` attribute.

LibWeb: Apply a couple of presentational hints to table elements

---

Libraries/LibWeb/CSS/Selector.cpp
Libraries/LibWeb/CSS/Selector.h
Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/DOM/Document.cpp

If selector does not have any descendant combinators then we know for sure it won't be filtered out by ancestor filter, which means there is no need to check for it.
This change makes hover style invalidation go faster on Discord where with this change we spend 4-5% in `should_reject_with_ancestor_filter()` instead of 20%.

LibWeb: Skip quick selector rejection using ancestor filter if possible

---

Libraries/LibWeb/DOM/ElementFactory.cpp
Libraries/LibWeb/HTML/Parser/HTMLParser.cpp

Done while hunting for reasons why we fail the test in #3406, but not really related to that PR.
Not moving `is_value` may or may not have an actual effect - I'm not sure if moving an `Optional<bool>` actually renders that value invalid. But everything else should have no observable behaviour changes.

LibWeb: HTML spec comments and small fixes

---

Libraries/LibDNS/Resolver.h
Libraries/LibThreading/Mutex.h
Libraries/LibWebSocket/CMakeLists.txt
Libraries/LibWebSocket/ConnectionInfo.h
Libraries/LibWebSocket/Impl/WebSocketImpl.h
Libraries/LibWebSocket/WebSocket.cpp
Services/RequestServer/CMakeLists.txt
Services/RequestServer/ConnectionFromClient.cpp
Services/RequestServer/ConnectionFromClient.h
Services/RequestServer/WebSocketImplCurl.cpp
Services/RequestServer/WebSocketImplCurl.h
vcpkg.json

This results in the following diff on the `websockets` WPTs, as a bonus to the future cleanups I plan for LibWebSocket:
`master` (e1119023e9fca17dab51b35c7e63f25c2f87e63a)
```
Ran 758 tests finished in 676.1 seconds.
• 216 ran as expected. 0 tests skipped.
• 5 tests crashed unexpectedly
• 45 tests had errors unexpectedly
• 370 tests timed out unexpectedly
• 283 tests had unexpected subtest results
```
This Branch:
```
Ran 758 tests finished in 591.9 seconds.
• 244 ran as expected. 0 tests skipped.
• 5 tests crashed unexpectedly
• 45 tests had errors unexpectedly
• 313 tests timed out unexpectedly
• 256 tests had unexpected subtest results
```
Timeouts and unexpected subtest results -> as expected :D

LibWebSocket+RequestServer: Add a WebSocketImpl using libcurl 

---

Libraries/LibWeb/HTML/HTMLLIElement.cpp
Libraries/LibWeb/HTML/HTMLLIElement.h
Libraries/LibWeb/HTML/HTMLOListElement.cpp
Libraries/LibWeb/HTML/HTMLOListElement.h
Libraries/LibWeb/HTML/HTMLUListElement.cpp
Libraries/LibWeb/HTML/HTMLUListElement.h
Tests/LibWeb/Ref/expected/wpt-import/html/rendering/non-replaced-elements/lists/li-type-supported-ref.html
Tests/LibWeb/Ref/expected/wpt-import/html/rendering/non-replaced-elements/lists/ol-type-supported-ref.html
Tests/LibWeb/Ref/expected/wpt-import/html/rendering/non-replaced-elements/lists/ul-type-supported-ref.html
Tests/LibWeb/Ref/input/wpt-import/html/rendering/non-replaced-elements/lists/li-type-supported.html
Tests/LibWeb/Ref/input/wpt-import/html/rendering/non-replaced-elements/lists/ol-type-supported.html
Tests/LibWeb/Ref/input/wpt-import/html/rendering/non-replaced-elements/lists/ul-type-supported.html
Tests/LibWeb/Text/expected/wpt-import/html/rendering/non-replaced-elements/lists/lists-presentational-hints-ascii-case-insensitive.txt
Tests/LibWeb/Text/input/wpt-import/html/rendering/non-replaced-elements/lists/lists-presentational-hints-ascii-case-insensitive.html

This PR applies the appropriate presentational hints for the `type` attribute of `HTMLOListElement`, `HTMLUListElement` and `HTMLIElement`. This ensures that changing the `type` attribute renders the correct list type for these elements.

LibWeb: Apply `type` presentational hint to list elements

---

Libraries/LibWeb/ARIA/AriaRoles.json

So I did a complete audit (manually) of our `AriaRoles.json` file against every single one of the **Characteristics** tables in the ARIA spec — at, for example, https://w3c.github.io/aria/#application — and patched the  `AriaRoles.json` file to match the current data in the spec.
When I started on it, I had optimistically imagined I was only going to find a small number of differences between the file and the spec. But I ended up finding a lot more than a few.
Most of the changes are to match the **Supported States and Properties** and **Inherited States and Properties** data — but some changes are to match the **Name From** data and **Accessible Name Required** data.
I also intentionally removed all states and properties the **Characteristics** tables list as _“deprecated on this role in …

LibWeb: Sync AriaRoles.json w/ Characteristics data in current spec

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
.github/workflows/lagom-template.yml
.github/workflows/nightly-lagom.yml
CMakePresets.json
Libraries/LibMedia/CMakeLists.txt
Meta/shell_include.sh

Refactor the Lagom CI template a bit:
- Actually use the arch parameter again
- Pass build_preset from top level matrix instead of FUZZ/NO_FUZZ
Add a nightly job using the newly widely available ubuntu-24.04-arm runners (https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/)
- Disable wasm spec tests on this job, because wabt doesn't have an arm64 release
- Manually pass PKG_CONFIG_EXECUTABLE, otherwise we don't detect system libpulse-dev binaries.
- Set VCPKG_FORCE_SYSTEM_BINARIES=1 as explained in vcpkg docs, and so the vcpkg binary doesn't yell at us
Add 3 nightly jobs for Distribution_CI preset: macOS, x86_64 linux, arm64 linux.
Draft until the new jobs pass on my fork. Expected-to-pass run :tm: : …

CI: Add Nightly arm64 Linux job, and nightly distribution jobs

---

Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h
Libraries/LibWeb/HTML/Focus.cpp
Libraries/LibWeb/HTML/HTMLElement.cpp
Libraries/LibWeb/HTML/HTMLElement.h
Libraries/LibWeb/Layout/Viewport.cpp
Libraries/LibWeb/Painting/Paintable.cpp
Libraries/LibWeb/Painting/Paintable.h
Libraries/LibWeb/Painting/ViewportPaintable.cpp
Tests/LibWeb/Text/expected/HTML/Window-find-inert.txt
Tests/LibWeb/Text/expected/wpt-import/inert/inert-computed-style.txt
Tests/LibWeb/Text/expected/wpt-import/inert/inert-node-is-unfocusable.txt
Tests/LibWeb/Text/input/HTML/Window-find-inert.html
Tests/LibWeb/Text/input/wpt-import/inert/inert-computed-style.html
Tests/LibWeb/Text/input/wpt-import/inert/inert-node-is-unfocusable.html

When a HTML element has the `inert` attribute, that attribute and all of its flat-tree descendants now implement the behaviors specified in https://html.spec.whatwg.org/multipage/interaction.html#inert-subtrees, namely:
Inert elements are:
* Treated as not visible for hit-testing
* Not selectable
* Not editable
* Ignored by find-in-page queries

LibWeb: Implement inert subtree behaviors

---

Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Libraries/LibWeb/HTML/HTMLLinkElement.h
Tests/LibWeb/Ref/expected/wpt-import/html/semantics/document-metadata/the-link-element/link-type-attribute-ref.html
Tests/LibWeb/Ref/expected/wpt-import/html/semantics/links/linktypes/link-type-stylesheet/process-stylesheet-linked-resource-ascii-case-insensitive-ref.html
Tests/LibWeb/Ref/input/wpt-import/html/semantics/document-metadata/the-link-element/link-type-attribute.html
Tests/LibWeb/Ref/input/wpt-import/html/semantics/links/linktypes/link-type-stylesheet/process-stylesheet-linked-resource-ascii-case-insensitive.html
Tests/LibWeb/Ref/input/wpt-import/html/semantics/links/linktypes/link-type-stylesheet/support/process-stylesheet-linked-resource-ascii-case-insensitive-lower.css
Tests/LibWeb/Ref/input/wpt-import/html/semantics/links/linktypes/link-type-stylesheet/support/process-stylesheet-linked-resource-ascii-case-insensitive-mixed.css
Tests/LibWeb/Ref/input/wpt-import/html/semantics/links/linktypes/link-type-stylesheet/support/process-stylesheet-linked-resource-ascii-case-insensitive-other.css
Tests/LibWeb/Ref/input/wpt-import/html/semantics/links/linktypes/link-type-stylesheet/support/process-stylesheet-linked-resource-ascii-case-insensitive.css

Previously, the type attribute was ignored on link elements.

LibWeb: Use type attribute to determine `HTMLLinkElement` mime type

---

Libraries/LibWeb/HTML/HTMLTableCellElement.cpp
Tests/LibWeb/Ref/expected/wpt-import/html/rendering/non-replaced-elements/tables/table-cell-nowrap-with-fixed-width-ref.html
Tests/LibWeb/Ref/input/wpt-import/html/rendering/non-replaced-elements/tables/table-cell-nowrap-with-fixed-width.html

Fixes: https://wpt.live/html/rendering/non-replaced-elements/tables/table-cell-nowrap-with-fixed-width.html

LibWeb: Apply `nowrap` attribute as presentational hint

---

Libraries/LibWeb/CSS/StyleComputer.cpp
Libraries/LibWeb/CSS/StyleComputer.h
Libraries/LibWeb/DOM/Document.cpp

Analysis of selectors on modern websites shows that the `:hover`
pseudo-class is mostly used in the subject position within relatively
simple selectors like `.a:hover`. This suggests that we could greatly
benefit from segregating them by id/class/tag name, this way reducing
number of selectors tested during hover style invalidation.
With this change, hover invalidation on Discord goes down from 70ms to
3ms on my machine. I also tested GMail and GitHub where this change
shows nice 2x-3x speedup.

LibWeb: Bucket hover rules using RuleCache

---

Libraries/LibWeb/HTML/HTMLScriptElement.cpp
Tests/LibWeb/Text/expected/wpt-import/html/semantics/scripting-1/the-script-element/remove-src-attr-prepare-a-script.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/scripting-1/the-script-element/remove-src-attr-prepare-a-script.html

Fixes: https://wpt.live/html/semantics/scripting-1/the-script-element/remove-src-attr-prepare-a-script.html

LibWeb: Don't prepare script when src attribute is removed

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/wpt-import/custom-elements/upgrading/Node-cloneNode.txt
Tests/LibWeb/Text/expected/wpt-import/custom-elements/upgrading/upgrading-parser-created-element.txt
Tests/LibWeb/Text/input/wpt-import/custom-elements/upgrading/Node-cloneNode.html
Tests/LibWeb/Text/input/wpt-import/custom-elements/upgrading/upgrading-parser-created-element.html

Throwing a TypeError instead of an InvalidStateError DOMException follows the current specification steps.

IDLGenerators: Throw TypeError if custom element is already constructed

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSEnums.cpp

clang 18.1.8 was crashing during the build without this change.
Filed a bug report here:
https://github.com/llvm/llvm-project/issues/128359

CodeGenerators: Fix clang-18 crash by specifying types explicitly

---

Libraries/LibTLS/TLSv12.cpp
Libraries/LibTLS/TLSv12.h
Libraries/LibWebSocket/Impl/WebSocketImplSerenity.cpp
Services/RequestServer/ConnectionFromClient.cpp
Tests/LibDNS/TestDNSResolver.cpp
Utilities/dns.cpp

This PR contains various improvements to the error handling capabilities of the OpenSSL backend `TLSv12` implementation. Notably, it enforces the underlying socket to be initialized as blocking or non-blocking before the SSL handshake occurs and checks for fatal errors when the `on_ready_to_read` callback is called from the underlying socket.

LibTLS: Improve error handling

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/Fetch/request-constructor-does-not-throw-on-null-body-with-get-or-head-request.txt
Tests/LibWeb/Text/input/Fetch/request-constructor-does-not-throw-on-null-body-with-get-or-head-request.html

For these types, it would previously only accept `undefined` for the `null` state.
Fixes GET requests in the Turbo library always failing: https://github.com/hotwired/turbo/blob/9e057f284a60a9597446b258d562cebd55be71d7/src/http/fetch_request.js#L219-L220 https://github.com/hotwired/turbo/blob/9e057f284a60a9597446b258d562cebd55be71d7/src/http/fetch_request.js#L51-L64
This was found on https://www.fangamer.com/.

LibWeb: Allow null for optional, nullable, no default value union types

---

Libraries/LibWeb/HTML/Parser/HTMLEncodingDetection.cpp
Tests/LibWeb/Text/expected/document-computed-mimetype.txt
Tests/LibWeb/Text/input/document-computed-mimetype.html

The correct behavior is specified in the standard [here](https://encoding.spec.whatwg.org/#common-infrastructure-for-utf-16be-and-utf-16le). I believe the mistake was made when reading "If charset is UTF-16BE/LE, then set charset to UTF-8" in the standard document [here](https://html.spec.whatwg.org/multipage/parsing.html#documentEncoding).
Fixes 9 [WPT tests](https://wpt.fyi/results/dom/nodes/Document-characterSet-normalization-1.html?product=ladybird).
I had wanted to import the WPT test, but as the entire test takes >30s to run (on my machine), I don't think that's really wanted. I can, however, create a small test just for this case if you'd like, but feel like it's quite niche.

LibWeb/HTML: Fix UTF-16BE/LE not converting to UTF-8

---

Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Tests/LibWeb/Text/expected/wpt-import/css/compositing/canvas-composite-modes.txt
Tests/LibWeb/Text/input/wpt-import/css/compositing/canvas-composite-modes.html

This PR fixes two bugs that caused the canvas compositing WPT tests to fail:
1. The retrieved `globalCompositeOperation` no longer incorrectly contains quotes
2. The `globalAlpha` no longer gets applied to the bitmap generated in `getImageData`

LibWeb/Canvas: Improve results in canvas compositing WPT tests

---

Libraries/LibRegex/RegexOptimizer.cpp
Tests/LibRegex/Regex.cpp

use depth-first search in optimizer code bacause using breadth-first search generate a bug. Add test example in test lib.

LibRegex: Use depth-first search in regex optimizer

---

AK/Checked.h
Tests/AK/TestChecked.cpp

Adding an overflow'n `Checked<T>` to another `Checked<T>` causes a verification faliure when instead it should propogate m_overflow and allow the user to handle the overflow.
Meaning something like this crashes:
```js
let byte_offset = 0;
let length = 0x100000000;
new Uint32Array(new ArrayBuffer(), byte_offset, length);
```

AK/Checked: Dont verify overflow bit in lvalue operations

---

Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
Libraries/LibWeb/XML/XMLDocumentBuilder.h
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Document-constructor-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-childElement-null-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-childElementCount-dynamic-add-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-childElementCount-dynamic-remove-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-childElementCount-nochild-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-childElementCount-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-firstElementChild-entity.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-firstElementChild-namespace-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-firstElementChild-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-lastElementChild-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-nextElementSibling-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-previousElementSibling-svg.txt
Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Element-siblingElement-null-svg.txt
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Document-constructor-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-childElement-null-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-childElementCount-dynamic-add-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-childElementCount-dynamic-remove-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-childElementCount-nochild-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-childElementCount-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-firstElementChild-entity.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-firstElementChild-namespace-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-firstElementChild-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-lastElementChild-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-nextElementSibling-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-previousElementSibling-svg.svg
Tests/LibWeb/Text/input/wpt-import/dom/nodes/Element-siblingElement-null-svg.svg

Previously, any xmlns attributes with an associated prefix were ignored.
For example, the following source:
```xml
<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:h="http://www.w3.org/1999/xhtml">
<h:script src="this-should-load.js" />
</svg>
```
wouldn't previously load because we would incorrectly assume that the prefixed script tag was an `SVGScriptElement` - and these don't have a `src` attribute.
WPT SVG tests rely on this working correctly, so previously all WPT SVG tests that used `testharness.js` would fail.
Here are the results of running: `./Meta/WPT.sh run $(./Meta/WPT.sh list-tests | grep '.svg$')`
Before:
```
Ran 577 tests finished in 41.2 seconds.
• 135 ran as expected. 0 tests skipped.
• 2 tests crashed unexpectedly
• 200 tests had errors unexpectedly
• …
```

LibXML: Associate prefixed elements with the correct namespace

---

Libraries/LibWeb/HTML/FormAssociatedElement.cpp
Libraries/LibWeb/HTML/FormAssociatedElement.h
Libraries/LibWeb/HTML/HTMLFormElement.cpp
Libraries/LibWeb/HTML/HTMLFormElement.h
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-checkValidity.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-valueMissing.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/radio.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/constraints/form-validation-checkValidity.html

This PR implements some core parts of the HTML “constraint-validation API” (_aka_ “client-side form validation”):
- for the `form` element itself: the `HTMLFormElement::checkValidity` method
- the code for the shared requirements for the `checkValidity` method for individual form controls
The PR also implements all “suffering from being missing” constraints for `HTMLInputElement`.
This change gets us a number of new passes for some of the 130 subtests of the test at https://wpt.fyi/results/html/semantics/forms/constraints/form-validation-checkValidity.html?product=ladybird. We should be able to get to passing 100% of those subtests in subsequent PRs that fill out the remaining constraint checks from that spec (and that are already stubbed out in the code, from a previous PR).

Implement HTMLFormElement::checkValidity and all HTMLInputElement “suffering from being missing” constraints (client-side form validation)

---

Libraries/LibWeb/HTML/HTMLButtonElement.cpp
Libraries/LibWeb/HTML/HTMLButtonElement.h
Libraries/LibWeb/HTML/HTMLButtonElement.idl
Libraries/LibWeb/HTML/HTMLFieldSetElement.cpp
Libraries/LibWeb/HTML/HTMLFieldSetElement.h
Libraries/LibWeb/HTML/HTMLFieldSetElement.idl
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.h
Libraries/LibWeb/HTML/HTMLInputElement.idl
Libraries/LibWeb/HTML/HTMLObjectElement.cpp
Libraries/LibWeb/HTML/HTMLObjectElement.h
Libraries/LibWeb/HTML/HTMLObjectElement.idl
Libraries/LibWeb/HTML/HTMLOutputElement.cpp
Libraries/LibWeb/HTML/HTMLOutputElement.h
Libraries/LibWeb/HTML/HTMLOutputElement.idl
Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Libraries/LibWeb/HTML/HTMLSelectElement.h
Libraries/LibWeb/HTML/HTMLSelectElement.idl
Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-willValidate.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-select-element/select-willvalidate-readonly-attribute.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/constraints/form-validation-willValidate.html

This change — part of the HTML constraint-validation API (_aka_ “client-side form validation”) — implements the `willValidate` IDL/DOM attribute/property for all form controls that support it.
This gets us passing 100% of the subtests for the test at https://wpt.fyi/results/html/semantics/forms/constraints/form-validation-willValidate.html?product=ladybird

Implement the willValidate property for form controls (constraint-validation API)

---

Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-checkValidity.txt

This is a simple change that just un-stubs our implementation of the `checkValidity()` method for `HTMLTextAreaElement`.

LibWeb: Flip on checkValidity() for HTMLTextAreaElement

---

Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/HTML/AutocompleteElement.cpp
Libraries/LibWeb/HTML/AutocompleteElement.h
Libraries/LibWeb/HTML/HTMLInputElement.h
Libraries/LibWeb/HTML/HTMLInputElement.idl
Libraries/LibWeb/HTML/HTMLSelectElement.h
Libraries/LibWeb/HTML/HTMLSelectElement.idl
Libraries/LibWeb/HTML/HTMLTextAreaElement.h
Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-form-element/form-autocomplete.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-form-element/form-autocomplete.html

This PR implements proper support for the `autocomplete` attribute in `input`, `select` and `textarea` elements and imports the relevant WPT test.
This is a side quest for implementing [credentials support](https://w3c.github.io/webappsec-credential-management/#abstract-opdef-create-a-passwordcredential-from-an-htmlformelement).

LibWeb: Support `autocomplete` attribute on form elements

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.h
Libraries/LibWeb/WebSockets/WebSocket.cpp
Libraries/LibWeb/WebSockets/WebSocket.h

From the "LibWeb: Close WebSockets when document is unloaded" commit:
Previously, they would stay open for the entire WebContent lifetime,
or until the server closed the connection. This was particularly
noticeable on collaborative websites/games such as
https://jigsawpuzzles.io/, where the user using Ladybird would stick
around even after they had navigated away.

LibWeb: Implement the WebSocket garbage collection rules and close them on document unload

---

Documentation/CSSGeneratedFiles.md
Libraries/LibWeb/CSS/ComputedProperties.cpp
Libraries/LibWeb/CSS/Parser/Parser.h
Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
Libraries/LibWeb/CSS/Properties.json
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp

This eliminates the need for bespoke `view-transition-name` parsing code. This isn't the case for any other properties, but does mean that parsing `animation-name` is less reliant on the order we attempt parsing different types.

LibWeb/CSS: Move custom-ident blacklists into Properties.json

---

Documentation/CSSProperties.md
Documentation/README.md

I've been meaning to write this for ages. Hopefully it makes sense! Feedback welcome.

Documentation: Document how to add a new CSS property

---

Libraries/LibWeb/Layout/TableGrid.cpp
Tests/LibWeb/Ref/input/wpt-import/css/CSS2/tables/table-anonymous-objects-059.xht
Tests/LibWeb/Ref/input/wpt-import/css/CSS2/tables/table-anonymous-objects-060.xht

Before this change, we were always processing all row groups first, and then all rows. This led to incorrect table layouts when rows and row groups were encountered in anything but that order.

LibWeb: Handle interleaved table-row and table-row-group boxes

---

Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Libraries/LibWeb/HTML/HTMLSelectElement.h
Libraries/LibWeb/HTML/HTMLSelectElement.idl
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-checkValidity.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-select-element/select-validity.txt

This change adds an implementation of the `checkValidity()` method for `HTMLSelectElement`.
(We already have an implementation of the only check that’s required to be run when `checkValidity()` is called — a “suffering from being missing” check.)

LibWeb: Implement checkValidity() for HTMLSelectElement

---

Libraries/LibGfx/ColorSpace.cpp
Services/ImageDecoder/ConnectionFromClient.cpp

This adds all parameters supported by skia by default. Supporting the
other parameters would just be a matter of defining the constants, but
that's work for another time.
Related to #3498

LibGfx: Support more CICP configurations

---

Libraries/LibWeb/WebSockets/WebSocket.cpp

This fixes the WPT regressions seen in: https://wpt.fyi/results/websockets?diff&filter=ADC&run_id=5114993798545408&run_id=5116882309087232

LibWeb: Don't close websocket if already closed in `make_disappear()` AO

---

Libraries/LibWeb/CSS/CSSNumericType.cpp
Libraries/LibWeb/CSS/CSSStyleValue.cpp
Libraries/LibWeb/CSS/CSSStyleValue.h
Libraries/LibWeb/CSS/ComputedProperties.cpp
Libraries/LibWeb/CSS/Keywords.json
Libraries/LibWeb/CSS/Parser/Parser.h
Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
Libraries/LibWeb/CSS/Properties.json
Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Libraries/LibWeb/CSS/Size.cpp
Libraries/LibWeb/CSS/Size.h
Libraries/LibWeb/CSS/StyleValues/FitContentStyleValue.h
Libraries/LibWeb/Forward.h
Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/height-valid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/max-height-computed.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/max-height-valid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/max-width-computed.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/max-width-valid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/min-height-computed.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/min-height-valid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/min-width-computed.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/min-width-valid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-sizing/parsing/width-valid.txt

Before this change, we only parsed fit-content as a standalone keyword, but CSS-SIZING-3 added it as a function as well. I don't know of anything else in CSS that is overloaded like this, so it ends up looking a little awkward in the implementation.
Note that a lot of code had already been prepped for fit-content values to have an argument, we just weren't parsing it.

LibWeb: Parse CSS fit-content(<length-percentage>) values

---

Libraries/LibDevTools/Actors/PageStyleActor.cpp
Libraries/LibDevTools/Actors/PageStyleActor.h
Libraries/LibDevTools/DevToolsDelegate.h
Libraries/LibWebView/Application.cpp

LibDevTools was implicitly including generated IPC endpoints from LibWebView. This is not a dependency declared in the CMakeLists.txt. So updates to the IPC file might not have caused the endpoint header to be regenerated by the time LibDevTools is compiled, resulting in a build error.
This patch removes that implicit dependency entirely.

LibDevTools+LibWebView: Avoid dependence on LibWebView from LibDevTools

---

Libraries/LibWeb/DOM/EditingHostManager.h
Libraries/LibWeb/DOM/InputEventsTarget.h
Libraries/LibWeb/HTML/FormAssociatedElement.cpp
Libraries/LibWeb/HTML/FormAssociatedElement.h
Libraries/LibWeb/Page/EventHandler.cpp
Tests/LibWeb/Text/expected/UIEvents/gc-mouse-selection-target.txt
Tests/LibWeb/Text/input/UIEvents/gc-mouse-selection-target.html

We hold a raw pointer to the mouse selection target, which is a mixin-style class inherited only by `JS::Cell` classes. By not visiting this object, we sometime had a dangling reference to it after it had been garbage collected.
Fixes a crash seen in CI:
https://github.com/LadybirdBrowser/ladybird/actions/runs/13554607471/job/37886019271?pr=3710#step:17:2763
```
LibWeb/Page/EventHandler.cpp:775:66: runtime error: member call on address 0x7f6c672f3808 which does not point to an object of type 'InputEventsTarget'
```

LibWeb: Ensure EventHandler visits its mouse selection target

---

Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
Tests/LibWeb/Text/expected/css/fit-content-parsing-with-whitespace.txt
Tests/LibWeb/Text/input/css/fit-content-parsing-with-whitespace.html

I think I explained this poorly in https://github.com/LadybirdBrowser/ladybird/pull/3706#discussion_r1972060343 :sweat_smile: Note to self: Don't code-review in a rush.
Weirdly, WPT doesn't seem to test this, so I added a test myself. Without the change, the last 3 results print out "".

LibWeb/CSS: Allow whitespace inside fit-content() function

---

Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
Libraries/LibWeb/HTML/EventLoop/EventLoop.h
Libraries/LibWeb/HTML/EventLoop/TaskQueue.cpp

If event loop is already executing rendering task, we should not start the next rendering task until the current one is finished.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/3717

LibWeb: Don't take rendering task from queue while running rendering

---

Libraries/LibWeb/Layout/LayoutState.cpp
Libraries/LibWeb/Layout/LayoutState.h
Tests/LibWeb/Crash/Layout/display-inline-with-position-sticky.html

Before this change we were ignoring boxes with `display: inline` while assigning sticky insets. This was not correct because inline boxes are allowed to have sticky positioning.
Fixes:
https://github.com/LadybirdBrowser/ladybird/issues/3718 https://github.com/LadybirdBrowser/ladybird/issues/3507 https://github.com/LadybirdBrowser/ladybird/issues/3133
We don't match behavior of other engines when inline node is splitted between multiple lines, but still better than crashing

LibWeb: Assign sticky insets to Layout::InlineNode

---

Libraries/LibGC/Heap.cpp
Tests/LibWeb/Text/expected/WebSocket/WebSocket-gc.txt
Tests/LibWeb/Text/input/WebSocket/WebSocket-gc.html

Previously, we would only keep the cell that must survive alive, but none of it's edges.
This cropped up with a GC UAF in must_survive_garbage_collection of WebSocket in .NET's SignalR frontend implementation, where an out-of-scope WebSocket had it's underlying EventTarget properties garbage collected, and must_survive_garbage_collection read from the destroyed EventTarget properties.
See: https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/clients/ts/signalr/src/WebSocketTransport.ts#L81
Found on https://www.formula1.com/ during a live session.

LibGC: Visit the edges of the cells that must survive garbage collection

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Libraries/LibWeb/HTML/HTMLLinkElement.h
Libraries/LibWeb/HTML/Parser/HTMLParser.cpp

This commit implements the main "render blocking" behavior for link elements, drastically reducing the amount of FOUC (flash of unstyled content) we subject our users to.
The document will now block rendering until linked style sheets referenced by parser-created link elements have loaded (or failed).
Note that we don't yet extend the blocking period until "critical subresources" such as imported style sheets have been downloaded as well.
Before/after demo:
https://github.com/user-attachments/assets/227ef968-bc61-450d-bebc-6ebf0d08f343

LibWeb: Block rendering until linked stylesheets are loaded

---

Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.h
Libraries/LibWeb/HTML/HTMLInputElement.idl
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-checkValidity.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-patternMismatch.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/input-pattern-dynamic-value.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/pattern_attribute.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/selectors/pseudo-classes/valid-invalid.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/constraints/form-validation-validity-patternMismatch.html
Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/constraints/input-pattern-dynamic-value.html
Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/pattern_attribute.html

This gets us +127 WPT subtest passes in the `html/semantics/forms` and `html/dom` directories.
We're currently not passing tests that assume our regex is Unicode aware. I'm not sure if that's because of a problem with this PR or our regex implementation.

LibWeb: Implement the `HTMLInputElement` pattern attribute

---

Libraries/LibWeb/HTML/Scripting/Fetching.cpp
Libraries/LibWeb/HTML/UniversalGlobalScope.h
Libraries/LibWeb/HTML/Window.h
Tests/LibWeb/Text/input/Worker/worker.mjs

The import map is defined for all global objects, not just the window.
This also adds an import to the `Worker-module.html` test which causes the worker to crash and the test to time out without this change (although it is currently skipped due to being flaky on CI, you'll need to change `TestConfig.ini` to run it yourself).
This fix allows https://treecalcul.us/live/ to run without its worker crashing (although it's too slow to finish without timing out, maybe a potential js perf target?)

LibWeb: Prevent crash when loading module in worker

---

Libraries/LibCore/Socket.cpp
Libraries/LibCore/Socket.h
Libraries/LibDNS/Resolver.h

Previously, we only returned the first result that looked like an IPv6 or IPv4 address.
This cropped up when attempting to connect to https://cxbyte.me/ whilst IPv6 on the server wasn't working. Since we only returned the first result, which happened to be the IPv6 address, we wasn't able to connect.
Returning all results allows curl to attempt to connect to a different IP if one of them isn't working, and potentially make a successful connection.

LibCore: Don't discard subsequent results in Socket::resolve_host

---

vcpkg.json

The generic `ssl` feature selects Secure Transport on macOS, which is a deprecated library and support for it in curl is also deprecated and scheduled for removal after May 2025: https://daniel.haxx.se/blog/tag/securetransport/
Secure Transport is replaced by Network Framework, but as per the blog post above, there's no foreseeable future of curl supporting it.
With this information, we now explicitly use OpenSSL as the backend for curl, inline with the default choice for Linux.
This gives us some key benefits:
- A maintained and current TLS library
- TLS 1.0 and 1.1 is disabled by default
- TLS 1.3 is now available
- Modern cipher suites
- Removal of TLS_EMPTY_RENEGOTIATION_INFO_SCSV extension
- Opportunity to support HTTP/3 with nghttp3 and OpenSSL's QUIC support
- More extensions, key …

vcpkg: Explicitly use OpenSSL backend with curl

---

Libraries/LibJS/Tests/builtins/RegExp/RegExp.js
Libraries/LibRegex/RegexMatcher.cpp
Libraries/LibRegex/RegexOptimizer.cpp

Fixes /.../v not being interpreted as a unicode pattern.

LibRegex: Treat the UnicodeSets flag as Unicode

---

Libraries/LibWeb/DOM/Node.cpp

Instead of marking all nodes in the subtree for style recalculation, including subtrees of subsequent siblings, we can fall back to the default invalidation path, which is optimized to skip siblings unaffected by sibling selectors.
Makes scrolling on https://frame.work/pl/en/about go a lot smoother.

LibWeb: Optimize the case when invalidation set contains "whole subtree"

---

Libraries/LibWeb/HTML/HTMLTrackElement.cpp
Tests/LibWeb/Text/expected/wpt-import/html/semantics/embedded-content/media-elements/track/track-element/src-empty-string.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/embedded-content/media-elements/track/track-element/src-empty-string.html

Previously, we would hang while waiting for the track to load if the `src` attribute was not present or empty.
I've also removed an incorrect early return after the track element fetch request starts, which prevented subsequent algorithm steps from running.
Fixes: #3740

LibWeb: Fire error event if `HTMLTrackElement` src is empty on load

---

UI/AppKit/Interface/LadybirdWebView.mm

I tried building the project following the [build guide](https://github.com/LadybirdBrowser/ladybird/blob/master/Documentation/BuildInstructionsLadybird.md) to install all the dependencies for Mac and running:
```
CC=$(brew --prefix llvm)/bin/clang CXX=$(brew --prefix llvm)/bin/clang++ ./Meta/ladybird.sh run
```
That caused the build to fail with this message:
```
[2955/2963] Building CXX object UI/AppKit/CMakeFiles/ladybird_impl.dir/Interface/LadybirdWebView.mm.o
FAILED: UI/AppKit/CMakeFiles/ladybird_impl.dir/Interface/LadybirdWebView.mm.o
/opt/homebrew/bin/ccache /opt/homebrew/opt/llvm/bin/clang++  -I/Users/silvanocerza/workspace/ladybird -I/Users/silvanocerza/workspace/ladybird/Services -I/Users/silvanocerza/workspace/ladybird/Libraries …
```

Fix template keyword misuse causing Mac build failure

---

Documentation/DevTools.md

Typo "communcation" replaced with communication on line 52.

Documentation: Fix a typo on line 52 in Devtools.md

---

Libraries/LibUnicode/CMakeLists.txt

We upgraded to ICU 76 in 6a564376fc011167c90a4bd79b408f9a52684e0c. This CMakeLists.txt should have been updated to match.

LibUnicode: Specify ICU 76 in LibUnicode/CMakeLists.txt

---

Libraries/LibWeb/Painting/PaintableBox.cpp

In some cases, we might be hovering directly on an element scrollable e.g. horizontally, but we are scrolling vertically. In these cases, we need to delegate the scroll to the parent instead of stalling the user's scroll.
I found this on https://tidal.com. If you scroll a tiny bit down, you see a horizontal scroll element. Hovering on it prevents the user from scrolling further down.
I've tested this fix on tidal.com and it seems to work just fine. My mouse's horizontal scroll scrolls the horizontal element, while the vertical scrolls the webpage.

LibWeb: Don't handle scroll if no axes are accepted

---

Libraries/LibRegex/RegexByteCode.cpp
Tests/LibRegex/Regex.cpp

This makes patterns like `/(a?b??)*/` correctly match the string.
Issue was originally found in test262: [https://github.com/tc39/test262/blob/9d8efae5c2c1848b9c3362c4aa81dd360ff8d3a7/test/built-ins/RegExp/nullable-quantifier.js](https://github.com/tc39/test262/blob/9d8efae5c2c1848b9c3362c4aa81dd360ff8d3a7/test/built-ins/RegExp/nullable-quantifier.js)

LibRegex: Ensure nullable quantifiers backtrack when input remains

---

Libraries/LibJS/Runtime/GlobalObject.cpp
Libraries/LibJS/Tests/builtins/functions/parseFloat.js

`parseFloat(-0)` should return +0, but optimization that skips the string conversion for number values was causing -0 to be returned as-is.
Summary:
+2 ✅    -1 ❌    -1 💀   
Diff Tests:
test/built-ins/decodeURIComponent/S15.1.3.2_A2.5_T1.js 💀 -> ✅
test/built-ins/parseFloat/S15.1.2.3_A1_T2.js           ❌ -> ✅
test/staging/sm/Date/dst-offset-caching-1-of-8.js      💀 -> ✅
test/staging/sm/Date/dst-offset-caching-5-of-8.js      ✅ -> 💀

LibJS: Fix parseFloat(-0) returning -0 instead of +0

---

Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateWebGLRenderingContext.cpp

If location is null, the spec simply tells us to return and ignore the passed in data.
Fixes #3708.

LibWeb/WebGL: Return from uniform methods if location is null

---

Libraries/LibWeb/HTML/HTMLLinkElement.cpp

Note that "becomes browsing-context connected" is defined as:
> When the insertion steps are invoked with it as the argument and it is
> now browsing-context connected.
This fixes an issue where WPT editing tests would clone the entire DOM thousands of times and re-fetch all the linked CSS files once per clone.

LibWeb: Don't begin link element fetch until browsing-context connected

---

AK/Memory.h
Libraries/LibGfx/ImageFormats/GIFLoader.cpp

This commit removes the fast_u32_fill and fast_u32_copy, as they were only used in one place, and are not optimal.

AK: Remove fast_u32_xxx apis from Memory.h

---

Libraries/LibWeb/DOM/Document.cpp

Removes lots of completely unnecessary work, especially when animated property affects layout.

LibWeb: Don't invalidate style of finished animations

---

Libraries/LibWeb/Painting/StackingContext.cpp
Tests/LibWeb/Ref/expected/render-order-floating-replaced-ref.html
Tests/LibWeb/Ref/input/render-order-floating-replaced.html

Previously floating replaced elements were drawn incorrectly and also twice.
This was originally discovered because of the `css/css-images/object-fit-*` set of tests from the WPT suite. Those use dashed borders to draw floating replaced elements. The dashed borders use subpixel rendering, so rendering them twice made the borders darker than they were supposed to be. The tests themselves cannot be imported though because a) they either fail for  other, unrelated reasons, or b) they only pass because both test and ref page don't render the intended content yet.

LibWeb: Draw floating replaced elements more correctly

---

Libraries/LibWeb/DOM/Element.cpp
Tests/LibWeb/Text/expected/HTML/document-named-shenanigans.txt
Tests/LibWeb/Text/input/HTML/document-named-shenanigans.html

This fixes an issue where disconnected elements were incorrectly accessible as named properties on the document.

LibWeb: Only put connected elements into document's by-name-or-id cache

---

Libraries/LibIDL/IDLParser.cpp

This fixes two errors in the IDL generator
- A minor one:
If you write something similar to this:
```
typedef (A or
B or
// FIXME: C
// FIXME: D
) Something;
```
Or something where after the `or` there are only spaces (the comments are just for comparison).
You get this error: `Unimplemented type for idl_type_name_to_cpp_type: `
This error is really confusing, as the empty type isn't really visible. So it is better to report empty types in that scenario earlier.
Now you get a more reasonable error:
```
) Something;
^
<file>:<line> error: Type can't be an empty string
```
- And an actual one:
If you use the enum feature of the IDL, you also can specify strings that start with an invalid C++ identifier. An example would be #3788
```
enum OffscreenRenderingContextId { "2d", "bitmaprenderer", …
```

LibWeb: Fix some IDL generator errors

---

Libraries/LibWeb/Page/EventHandler.cpp

Previously, despite CTRL being held, the webpage elements such as checkboxes (if existing) could 'hijack' the CTRL+TAB keypress which disabled moving to the next tab.
Now, if CTRL is held, TAB and SHIFT+TAB keypresses are ignored, so that the default Qt's next/previous tab movements are applied.
Before:
[before.webm](https://github.com/user-attachments/assets/3b54cb6b-d112-4889-b788-4a7eee73fee9)
After:
[after.webm](https://github.com/user-attachments/assets/2ddc3e93-77f7-4d4f-9b5f-eb8eb0088e6b)

LibWeb: Fix moving through tabs with keyboard shortcuts

---

Documentation/EditorConfiguration/CLionConfiguration.md

The `Debug` profile is enabled by default and it must be unchecked in order for CLion to work properly.

Documentation: Add instructions to uncheck 'Enable profile' for Debug

---

Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/ContentSecurityPolicy/Directives/Directive.cpp
Libraries/LibWeb/ContentSecurityPolicy/Directives/Directive.h
Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveFactory.cpp
Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveFactory.h
Libraries/LibWeb/ContentSecurityPolicy/Directives/Names.cpp
Libraries/LibWeb/ContentSecurityPolicy/Directives/Names.h
Libraries/LibWeb/ContentSecurityPolicy/Directives/SerializedDirective.cpp
Libraries/LibWeb/ContentSecurityPolicy/Directives/SerializedDirective.h
Libraries/LibWeb/ContentSecurityPolicy/Policy.cpp
Libraries/LibWeb/ContentSecurityPolicy/Policy.h
Libraries/LibWeb/ContentSecurityPolicy/PolicyList.cpp
Libraries/LibWeb/ContentSecurityPolicy/PolicyList.h
Libraries/LibWeb/ContentSecurityPolicy/SerializedPolicy.cpp
Libraries/LibWeb/ContentSecurityPolicy/SerializedPolicy.h
Libraries/LibWeb/Forward.h
Libraries/LibWeb/HTML/PolicyContainers.cpp
Libraries/LibWeb/HTML/PolicyContainers.h
Libraries/LibWeb/HTML/SerializedPolicyContainer.cpp
Libraries/LibWeb/HTML/SerializedPolicyContainer.h

Part 2 of splitting up https://github.com/LadybirdBrowser/ladybird/pull/2854
---
These form the basis of Content Security Policy. A policy is a collection of directives that are parsed from either the Content-Security-Policy(-Report-Only) HTTP header, or the `<meta>` element.
The directives are what restrict the operations can be performed in the current global execution context. For example, "frame-ancestors: none" tells us to prevent the page from being loaded in an embedded context, such as `<iframe>`.
You can see it a bit like OpenBSD's pledge() functionality, but for the web platform: https://man.openbsd.org/pledge.2

LibWeb: Introduce Content Security Policy policies and directives

---

Libraries/LibWeb/CSS/MediaList.cpp
Libraries/LibWeb/CSS/MediaList.h
Libraries/LibWeb/CSS/StyleSheet.cpp
Libraries/LibWeb/DOM/Node.h
Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Libraries/LibWeb/HTML/HTMLLinkElement.h
Libraries/LibWeb/HTML/HTMLLinkElement.idl
Libraries/LibWeb/HTML/HTMLStyleElement.cpp
Libraries/LibWeb/HTML/HTMLStyleElement.h
Libraries/LibWeb/HTML/HTMLStyleElement.idl
Tests/LibWeb/Text/expected/wpt-import/html/semantics/document-metadata/the-style-element/style_media.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/document-metadata/the-style-element/style_media.html

This makes dynamic changes to a style sheet's media attribute actually take effect immediately.

LibWeb: Invalidate style (and rule cache) on MediaList changes

---

Libraries/LibWeb/HTML/HTMLInputElement.cpp
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-checkValidity.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-typeMismatch.txt

This change implements `HTMLInputElement` `type=url` constraint validation in such a way as to match the behavior in other existing engines — which is, however, very different from what the spec currently requires.
See https://github.com/whatwg/html/issues/11083 and see the additional test cases at https://github.com/web-platform-tests/wpt/pull/51011/files — and see Anne’s comment at https://github.com/web-platform-tests/wpt/pull/51011#issuecomment-2689983961.
For the record here: If we were to strictly implement the spec requirements as currently written, we’d end up reporting validation errors for a lot of cases that all other existing engines don’t report validation errors for. So, from a user point of view, it’d look to users as if our behavior is broken.
This therefore seems like a …

LibWeb: Implement HTMLInputElement type=url constraint validation

---

AK/Concepts.h
AK/JsonArray.h
Documentation/DevTools.md
Libraries/LibDevTools/Actors/FrameActor.cpp
Libraries/LibDevTools/Actors/FrameActor.h
Libraries/LibDevTools/DevToolsDelegate.h
Libraries/LibWebView/Application.cpp
Libraries/LibWebView/Application.h
Libraries/LibWebView/CMakeLists.txt
Libraries/LibWebView/ConsoleOutput.cpp
Libraries/LibWebView/ConsoleOutput.h
Libraries/LibWebView/Forward.h
Libraries/LibWebView/InspectorClient.cpp
Libraries/LibWebView/InspectorClient.h
Libraries/LibWebView/ViewImplementation.h
Libraries/LibWebView/WebContentClient.cpp
Libraries/LibWebView/WebContentClient.h
Services/WebContent/DevToolsConsoleClient.cpp
Services/WebContent/DevToolsConsoleClient.h
Services/WebContent/InspectorConsoleClient.cpp
Services/WebContent/InspectorConsoleClient.h
Services/WebContent/PageClient.cpp
Services/WebContent/PageClient.h
Services/WebContent/WebContentClient.ipc
Services/WebContent/WebContentConsoleClient.cpp
Services/WebContent/WebContentConsoleClient.h

This implements support for basic usage of `console.log` and friends. It does not implement `console.assert`, `console.trace`, `console.group`, etc.

LibDevTools: Implement basic support for console logging

---

Documentation/DevTools.md

For developing new LibDevTools features, it's easiest to snoop Firefox's communication on the DevTools port to see what messages are being sent.

Documentation: Describe how to sniff the DevTools protocol with Firefox

---

Libraries/LibJS/SyntaxHighlighter.cpp
Libraries/LibJS/Token.h
Libraries/LibWebView/SourceHighlighter.cpp

Trivia is whatever whitespace and comments appear before a token. Previously this was always given a TokenCategory of Invalid, so it would be displayed as an error in the view-source page, with red wiggly underlines. Instead, treat it as what it actually is: whitespace and comments!

LibJS+LibWebView: Treat trivia tokens as comments

---

Libraries/LibURL/URL.cpp
Libraries/LibURL/URL.h
Libraries/LibWeb/HTML/HTMLHyperlinkElementUtils.cpp
Libraries/LibWeb/HTML/HTMLImageElement.cpp
Libraries/LibWeb/HTML/HTMLImageElement.h
Libraries/LibWeb/HTML/HTMLTrackElement.cpp
Libraries/LibWeb/HTML/ImageRequest.cpp
Libraries/LibWeb/HTML/ImageRequest.h
Libraries/LibWeb/Loader/ResourceLoader.cpp
Libraries/LibWebView/InspectorClient.cpp
Libraries/LibWebView/SourceHighlighter.cpp
Libraries/LibWebView/SourceHighlighter.h
Meta/Lagom/Fuzzers/FuzzURL.cpp
UI/AppKit/Interface/LadybirdWebView.mm
UI/AppKit/main.mm
UI/Qt/BrowserWindow.cpp
UI/Qt/SettingsDialog.cpp
UI/Qt/StringUtils.cpp
UI/Qt/StringUtils.h
UI/Qt/Tab.cpp
UI/Qt/main.cpp

All URLs are now either constucted through the URL Parser or by
default constructing a URL, and setting each of the fields of that
URL manually. This makes it much more difficult to create invalid
URLs to enable removing it's valid state.

LibURL+LibWeb+UI: Remove the implicit URL constructors

---

Libraries/LibWeb/HTML/HTMLInputElement.cpp
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-checkValidity.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-typeMismatch.txt

This change implements `HTMLInputElement` `type=email` constraint validation in conformance with the current spec requirements (which happens to also produce behavior that’s interoperable with other existing engines).

LibWeb: Implement HTMLInputElement type=email constraint validation

---

Libraries/LibRegex/RegexParser.cpp
Libraries/LibRegex/RegexParser.h
Tests/LibRegex/Regex.cpp

Instead of tracking duplicate named capture groups across the entire expression, we now track them within each alternative. This allows us to match things correctly when we have duplicate named groups. 
We can pass a couple more tests by ensuring the groups are in the correct order, but I haven’t figured that out yet :^)
Summary:
+10 ✅    -10 ❌ 
Diff Tests:
test/annexB/built-ins/RegExp/prototype/compile/duplicate-named-capturing-groups-syntax.js ❌ -> ✅
test/built-ins/RegExp/duplicate-named-capturing-groups-syntax.js                          ❌ -> ✅
test/built-ins/RegExp/named-groups/duplicate-names-match-indices.js                       ❌ -> ✅
test/built-ins/RegExp/named-groups/duplicate-names-matchall.js                            ❌ -> ✅ …

LibRegex: Allow duplicate named capture groups in separate alternatives

---

Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Tests/LibWeb/Layout/expected/flex/align-center-margin.txt
Tests/LibWeb/Layout/input/flex/align-center-margin.html

LibWeb: Respect margin boxes when center-aligning flex items

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Node.cpp

This allows us to avoid a full layout tree rebuild after change of "display" property, which happens frequently in practice. It also allows us to avoid a full rebuild after DOM node insertion, since previously, computing styles for newly inserted nodes would trigger a complete layout tree rebuild.

LibWeb: Use partial layout tree rebuild in element's style invalidation

---

Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.h
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-checkValidity.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-rangeOverflow.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-rangeUnderflow.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/selectors/pseudo-classes/valid-invalid.txt

This change implements the requirements for the “suffering from an overflow” and “suffering from an underflow” algorithms for `HTMLInputElement` constraint validation.

LibWeb: Implement “suffering from overflow/underflow” for HTMLInputElement

---

Libraries/LibDevTools/Actors/FrameActor.cpp
Libraries/LibDevTools/Actors/HighlighterActor.cpp
Libraries/LibDevTools/Actors/NodeActor.cpp
Libraries/LibDevTools/Actors/NodeActor.h
Libraries/LibDevTools/Actors/PageStyleActor.cpp
Libraries/LibDevTools/Actors/WalkerActor.cpp
Libraries/LibDevTools/Actors/WalkerActor.h
Libraries/LibDevTools/DevToolsDelegate.h
Libraries/LibWeb/DOM/CharacterData.cpp
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h
Libraries/LibWeb/Page/Page.h
Libraries/LibWebView/Application.cpp
Libraries/LibWebView/Application.h
Libraries/LibWebView/CMakeLists.txt
Libraries/LibWebView/Forward.h
Libraries/LibWebView/Mutation.cpp
Libraries/LibWebView/Mutation.h
Libraries/LibWebView/ViewImplementation.cpp
Libraries/LibWebView/ViewImplementation.h
Libraries/LibWebView/WebContentClient.cpp
Libraries/LibWebView/WebContentClient.h
Services/WebContent/ConnectionFromClient.cpp
Services/WebContent/ConnectionFromClient.h
Services/WebContent/PageClient.cpp
Services/WebContent/PageClient.h
Services/WebContent/WebContentClient.ipc
Services/WebContent/WebContentServer.ipc

This first implements propagating DOM mutations from WebContent to LibDevTools. The DevTools protocol for mutations more or less mimics the `MutationObserver` API exactly.
Then this implements a handful of DOM editing requests.
https://github.com/user-attachments/assets/53456d68-82de-4a4d-af58-88b9524678f7
Yes, this is peak web design 🙃

LibDevTools: Implement DOM mutations and DOM editing requests

---

Libraries/LibWeb/Animations/KeyframeEffect.cpp
Libraries/LibWeb/DOM/CharacterData.cpp
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/DOM/Node.h
Libraries/LibWeb/HTML/HTMLImageElement.cpp
Libraries/LibWeb/HTML/HTMLVideoElement.cpp
Libraries/LibWeb/HTML/Navigable.cpp
Libraries/LibWeb/Layout/Box.h
Libraries/LibWeb/Layout/FormattingContext.cpp
Libraries/LibWeb/Layout/LayoutState.h
Libraries/LibWeb/SVG/SVGImageElement.cpp

12c6ac78e20904431372dec1e81f896807c9f35a with fixed mistake when cache slot is copied instead of being referenced:
```cpp
auto cache_slot =
box.cached_intrinsic_sizes().min_content_height.ensure(width);
```
while it should've been:
```cpp
auto& cache_slot =
box.cached_intrinsic_sizes().min_content_height.ensure(width);
```

LibWeb: Bring back cache of intrinsic sizes across layout runs

---

Libraries/LibWeb/CSS/Properties.json

If a CSS animation or transition was being used to manipulate a property that itself does not affect layout, we were still doing a full relayout whenever any animation or transition related property was changed.
As it turns out, we can just not do that, and we avoid a bunch of unnecessary layout work on many pages. When a layout-affecting property is being animated, the animation/transition update code takes care to invalidate layout as appropriate anyway!
This was very noticeable on GitHub, where moving the mouse cursor between "Issues" and "Pull requests" would trigger a full relayout every time. Now that doesn't happen, and it's much more responsive. :^)

LibWeb: Don't unconditionally relayout on animation/transition changes

---

Libraries/LibWeb/Animations/KeyframeEffect.cpp
Libraries/LibWeb/DOM/Document.h

It's possible to do a partial tree rebuild instead.

LibWeb: Don't drop layout tree in CSS animation invalidation

---

Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLInputElement.h
Libraries/LibWeb/HTML/HTMLInputElement.idl
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/input-list.txt
Tests/LibWeb/Text/expected/wpt-import/shadow-dom/input-element-list.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/input-list.html
Tests/LibWeb/Text/input/wpt-import/shadow-dom/input-element-list.html

This returns the `HTMLDataListElement` pointed to by the `list` content attribute.
This fixes 41 WPT subtests in the `shadow-dom` and `html/semantics/forms/the-input-element` directories.

LibWeb: Implement the `HTMLInputElement.list` attribute

---

Libraries/LibWeb/DOM/Node.cpp
Libraries/LibWeb/Layout/SVGFormattingContext.cpp

There is no need to invalidate siblings affected by these pseudo classes if invalidation reason is not insertion or removal of tree nodes.

Skip invalidating :first-child and :last-child if possible

---

Libraries/LibWeb/CSS/Parser/MediaParsing.cpp
Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-invalid-media-type-001.html

This fixes 7 WPT tests in the `css/mediaqueries` directory.

LibWeb: Treat media query with an invalid media type as invalid

---

Libraries/LibURL/URL.cpp

* Passes wpt tests which were failing after https://github.com/whatwg/url/commit/9bc33c39d4a6cd6a936ea7620b5a69f606ec0d4c.
* ex: http://wpt.live/url/url-constructor.any.worker.html?exclude=(file|javascript|mailto)

LibURL: Add U+005E (^) to path percent encoding list

---

Libraries/LibWeb/HTML/Dates.cpp
Libraries/LibWeb/HTML/Dates.h
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-checkValidity.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-rangeOverflow.txt
Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-rangeUnderflow.txt

This gets us passing 100% of the subtests in the test at https://wpt.fyi/results/html/semantics/forms/constraints/form-validation-checkValidity.html?product=ladybird

LibWeb: Implement string->number for type=datetime-local input elements

---

Libraries/LibWeb/CSS/Parser/Tokenizer.cpp
Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/reference/ref-green-background.xht
Tests/LibWeb/Ref/input/wpt-import/css/mediaqueries/mq-case-insensitive-001.html

Fixes 2 WPT tests that I could find. 
I'm not sure if it would be better to convert name to lower case at some earlier point during parsing.

LibWeb: Treat CSS at-rule names as case-insensitive

---

Libraries/LibWeb/HTML/Navigable.cpp

Feedback from #3862 
cc: @gmta

LibWeb/HTML: Remove `dbgln()` for invalid location_url to reduce spam

---

Tests/LibWeb/Text/input/WebSocket/WebSocket-gc.html
Tests/LibWeb/Text/input/WebSocket/echo.html

The public one at echo.websocket.org tends to be slow at times, frequently causing timeouts. Ideally we would run a local websocket server but for now we can make do with a self-hosted alternative.

Tests: Use own websocket echo server instead of websocket.org

---

Libraries/LibWeb/CSS/Selector.cpp
Libraries/LibWeb/CSS/Selector.h
Libraries/LibWeb/CSS/SelectorEngine.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Node.cpp

If an element is affected only by selectors using the direct sibling combinator `+`, we can calculate the maximum invalidation distance and use it to limit style invalidation. For example, the selector `.a + .b + .c` has a maximum invalidation distance of 2, meaning we can skip invalidating any element affected by this selector if it's more than two siblings away from the element that triggered the style invalidation.
This change results in visible performance improvement when hovering PR list on GitHub.

LibWeb: Limit sibling style invalidation by max distance

---

Libraries/LibWeb/Bindings/MainThreadVM.cpp
Libraries/LibWeb/DOM/Slottable.cpp
Libraries/LibWeb/HTML/Scripting/Agent.h
Tests/LibWeb/Text/expected/wpt-import/shadow-dom/slotchange-customelements.txt
Tests/LibWeb/Text/expected/wpt-import/shadow-dom/slotchange-event.txt
Tests/LibWeb/Text/input/wpt-import/shadow-dom/slotchange-customelements.html
Tests/LibWeb/Text/input/wpt-import/shadow-dom/slotchange-event.html

Extracted from my 'State-preserving atomic move integration' MR as this can be applied independently, and there are still some details like trying to not introduce a performance regression I am trying to figure out in that MR.

LibWeb: Fire slotchange events when a slot is changed

---

Libraries/LibWebView/Application.cpp
Libraries/LibWebView/HelperProcess.cpp
Libraries/LibWebView/Options.h
Libraries/LibWebView/SiteIsolation.cpp
Libraries/LibWebView/SiteIsolation.h
Services/WebContent/main.cpp
Services/WebDriver/main.cpp

We will need to update WebDriver to handle the switch of WebContent processes.

LibWebView+WebContent+WebDriver: Disable site isolation for WebDriver

---

Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
Tests/LibWeb/Text/expected/wpt-import/css/filter-effects/parsing/backdrop-filter-parsing-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/filter-effects/parsing/filter-parsing-invalid.txt
Tests/LibWeb/Text/input/wpt-import/css/filter-effects/parsing/backdrop-filter-parsing-invalid.html
Tests/LibWeb/Text/input/wpt-import/css/filter-effects/parsing/filter-parsing-invalid.html

This fixes 16 WPT subtests in the `css/filter-effects` directory.

LibWeb/CSS: Don't allow negative values in filter functions

---

Libraries/LibDevTools/Actor.cpp
Libraries/LibDevTools/Actor.h
Libraries/LibDevTools/Actors/CSSPropertiesActor.cpp
Libraries/LibDevTools/Actors/ConsoleActor.cpp
Libraries/LibDevTools/Actors/ConsoleActor.h
Libraries/LibDevTools/Actors/DeviceActor.cpp
Libraries/LibDevTools/Actors/FrameActor.cpp
Libraries/LibDevTools/Actors/HighlighterActor.cpp
Libraries/LibDevTools/Actors/InspectorActor.cpp
Libraries/LibDevTools/Actors/InspectorActor.h
Libraries/LibDevTools/Actors/LayoutInspectorActor.cpp
Libraries/LibDevTools/Actors/NodeActor.cpp
Libraries/LibDevTools/Actors/NodeActor.h
Libraries/LibDevTools/Actors/PageStyleActor.cpp
Libraries/LibDevTools/Actors/PageStyleActor.h
Libraries/LibDevTools/Actors/PreferenceActor.cpp
Libraries/LibDevTools/Actors/RootActor.cpp
Libraries/LibDevTools/Actors/TabActor.cpp
Libraries/LibDevTools/Actors/TargetConfigurationActor.cpp
Libraries/LibDevTools/Actors/ThreadConfigurationActor.cpp
Libraries/LibDevTools/Actors/WalkerActor.cpp
Libraries/LibDevTools/Actors/WatcherActor.cpp

Now that a good chunk of DevTools has been implemented, there's been some clear boilerplate forming for many request handlers. This PR is to reduce that.

LibDevTools: Some small refactoring to reduce boilerplate

---

Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
Tests/LibWeb/Text/expected/wpt-import/css/css-lists/parsing/counter-increment-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-lists/parsing/counter-reset-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-lists/parsing/counter-set-invalid.txt
Tests/LibWeb/Text/input/wpt-import/css/css-lists/parsing/counter-increment-invalid.html
Tests/LibWeb/Text/input/wpt-import/css/css-lists/parsing/counter-reset-invalid.html
Tests/LibWeb/Text/input/wpt-import/css/css-lists/parsing/counter-set-invalid.html

We now parse `<counter-name>` values as a `<custom-ident>`. This disallows `default` and CSS-wide keywords as counter names. The specification additionally disallows `none` as a counter name.

LibWeb/CSS: Disallow invalid `<counter-name>` values

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Document.h
Libraries/LibWeb/HTML/HTMLFormElement.cpp
Libraries/LibWeb/HTML/HTMLFormElement.h
Libraries/LibWeb/HTML/HTMLOrSVGElement.cpp
Libraries/LibWeb/HTML/Navigable.cpp
Libraries/LibWeb/HTML/Navigable.h
Libraries/LibWeb/HTML/PolicyContainers.cpp
Libraries/LibWeb/HTML/PolicyContainers.h
Libraries/LibWeb/HTML/TraversableNavigable.cpp
Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
Libraries/LibWeb/HTML/WorkerGlobalScope.h
Services/WebWorker/DedicatedWorkerHost.cpp
Tests/LibWeb/Text/expected/HTML/HTMLOrSVGElement-nonce.txt

Part 3 of splitting up https://github.com/LadybirdBrowser/ladybird/pull/2854
Namely:
- Only stash the nonce attribute's value if there is a CSP header
- Parse CSP from navigation/worker response
- Determine the correct CSP navigation type for form submission

LibWeb/CSP: Preparatory work for enforcing policies

---

Tests/LibWeb/TestConfig.ini

Disabling this test because it very often crashes on CI https://github.com/LadybirdBrowser/ladybird/issues/3894

Tests: Disable css-contain/contain-style-remove-element-crash.html

---

Libraries/LibMedia/Audio/FFmpegLoader.cpp
Libraries/LibMedia/Audio/FFmpegLoader.h
Libraries/LibMedia/CMakeLists.txt
Libraries/LibMedia/Containers/Matroska/MatroskaDemuxer.cpp
Libraries/LibMedia/Containers/Matroska/MatroskaDemuxer.h
Libraries/LibMedia/Demuxer.h
Libraries/LibMedia/FFmpeg/FFmpegDemuxer.cpp
Libraries/LibMedia/FFmpeg/FFmpegDemuxer.h
Libraries/LibMedia/FFmpeg/FFmpegDemuxerStub.cpp
Libraries/LibMedia/FFmpeg/FFmpegHelpers.h
Libraries/LibMedia/FFmpeg/FFmpegIOContext.cpp
Libraries/LibMedia/FFmpeg/FFmpegIOContext.h
Libraries/LibMedia/FFmpeg/FFmpegVideoDecoder.cpp
Libraries/LibMedia/PlaybackManager.cpp
Libraries/LibMedia/PlaybackManager.h
Libraries/LibMedia/Sample.h
Libraries/LibWeb/HTML/AudioTrack.cpp
Libraries/LibWeb/HTML/AudioTrack.h
Libraries/LibWeb/HTML/HTMLAudioElement.cpp
Libraries/LibWeb/HTML/HTMLVideoElement.cpp
Libraries/LibWeb/HTML/HTMLVideoElement.h

This acts as a drop-in replacement for our MatroskaDemuxer, giving us access to containers other than Matroska, with the biggest one being MP4.
Alongside this, since we already demux the audio with FFmpeg and create audio tracks regardless of media type, we can just play the audio tracks with the video element! However, audio/video sync is _not_ perfect, but that's not the goal of this PR :^)
For example, with MediaSource disabled (i.e. removing Window from the Exposed attribute on MediaSource and ManagedMediaSource), we can watch 360p h.264 mp4 YouTube videos!
https://github.com/user-attachments/assets/00cafce6-34fe-428b-9476-77ca33b21812
Note that there some improvements we could make here, e.g. dropping the MatroskaDemuxer and passing FFmpeg packets around directly, but that can be …

LibMedia+LibWeb: Demux videos with FFmpeg and play audio with videos

---

Libraries/LibWeb/ContentSecurityPolicy/PolicyList.cpp

It adds to much spam in test runner output.

LibWeb: Delete FIXME debug log in PolicyList

---

Libraries/LibWeb/Layout/LayoutState.cpp
Libraries/LibWeb/Layout/LayoutState.h

It's no longer needed after we moved intrinsic sizes cache into layout nodes.

LibWeb: Delete root pointer in LayoutState

---

Libraries/LibMedia/DecoderError.h
Libraries/LibMedia/PlaybackManager.cpp

This fixes WPT regression in the `html/dom` directory seen in this run: https://wpt.fyi/results/html/dom?diff&filter=ADC&run_id=4819693758316544&run_id=5104664167317504.

LibMedia: Popagate errors if demuxer creation fails

---

Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-area-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-column-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-row-invalid.txt

This PR ensures that invalid values for the `grid-row` and `grid-column` properties and their respective longhands are rejected.
This gives us +64 WPT subtest passes.

LibWeb/CSS: Reject invalid grid track placement property values

---

Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
Libraries/LibWeb/CSS/Properties.json
Tests/LibWeb/Text/expected/wpt-import/css/css-transitions/parsing/transition-duration-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-transitions/parsing/transition-invalid.txt
Tests/LibWeb/Text/input/wpt-import/css/css-transitions/parsing/transition-duration-invalid.html
Tests/LibWeb/Text/input/wpt-import/css/css-transitions/parsing/transition-invalid.html

This fixes 6 WPT subtests in `css/css-transitions`.

LibWeb/CSS: Reject invalid `transition` values

---

Libraries/LibDevTools/Actors/NodeActor.h
Libraries/LibDevTools/Actors/WalkerActor.cpp
Libraries/LibDevTools/Actors/WalkerActor.h

The `NodeIdentifier` struct essentially contains the DOM node ID within its WebContent process. These will repeat across multiple processes, thus we cannot use them to search for node actors in the global actor registry.
Instead, we can store a map of all node actors created by the walker itself. The `NodeIdentifier` is then appropriate for actor lookups on that map. This has the added benefit of not needing to search the entire actor registry many times while forming the DOM node caches.
This fix allows us to inspect multiple tabs at once.

LibDevTools: Ensure the walker actor only displays nodes it created

---

Libraries/LibRegex/RegexByteCode.cpp
Libraries/LibRegex/RegexByteCode.h
Tests/LibRegex/Regex.cpp

On lookahead body failure, we don’t reset the last saved status.
This can create problems with nested lookaheads. 
An example is provided in the test file.

LibRegex: LookAhead pop last saved on failure

---

Libraries/LibWeb/CSS/Parser/GradientParsing.cpp
Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
Libraries/LibWeb/CSS/Properties.json
Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/parsing/background-image-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/parsing/background-position-x-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/parsing/background-position-y-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/parsing/border-radius-invalid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/parsing/box-shadow-invalid.txt
Tests/LibWeb/Text/input/wpt-import/css/css-backgrounds/parsing/background-image-invalid.html
Tests/LibWeb/Text/input/wpt-import/css/css-backgrounds/parsing/background-position-x-invalid.html
Tests/LibWeb/Text/input/wpt-import/css/css-backgrounds/parsing/background-position-y-invalid.html
Tests/LibWeb/Text/input/wpt-import/css/css-backgrounds/parsing/border-radius-invalid.html
Tests/LibWeb/Text/input/wpt-import/css/css-backgrounds/parsing/box-shadow-invalid.html

Fixes 12 WPT subtests in the `css/css-backgrounds` directory.

LibWeb: Reject invalid CSS `background` property values

---

Libraries/LibWeb/Platform/AudioCodecPlugin.h
Libraries/LibWeb/Platform/AudioCodecPluginAgnostic.cpp

The plugin may go out of scope before the callbacks we've queued have fired. It is undefined behavior for these callbacks to access the plugin data after that has occurred.
This patch protects these callbacks with weak pointers. Note that the plugin is not ref-counted, so we cannot use `strong_ref` here.
Fixes #3933

LibWeb: Protect audio codec callbacks against its own destruction

---

Libraries/LibRegex/RegexByteCode.cpp
Libraries/LibRegex/RegexByteCode.h
Tests/LibRegex/Regex.cpp

This reverts commit f2678bfcb836c0b4e3339878c7883ca7aef57699.
This caused a WPT regression seen in this run: https://wpt.fyi/results/?diff&filter=ADC&run_id=5085544315092992&run_id=5190898705235968

Revert "LibRegex: Remove orphaned save points in nested LookAhead"

---

Libraries/LibCore/CMakeLists.txt
Libraries/LibCore/EventLoop.h
Libraries/LibCore/EventLoopExecutor.swift
Libraries/LibCore/EventSwift.h
Libraries/LibCore/EventSwift.mm
Meta/Lagom/CMakeLists.txt
Tests/LibCore/TestEventLoop.cpp
Tests/LibCore/TestEventLoop.h
Tests/LibCore/TestEventLoopActor.swift
Tests/LibCore/module.modulemap

Add a SerialExecutor (and TaskExecutor, same object) for interacting with Core::EventLoop from swift. It still has the assumption that the thread it is invoked from already has a Core::EventLoop existing for it, either on the stack or the heap. The tests create one on the heap for simplicity, but real application code will have it on the stack.
Also add an actor protocol that wraps the EventLoopExecutor, and a single actor for testing purposes. In the future we'll probably need an actor corresponding to the HTML event loop for submitting HTML tasks to, and perhaps a "main thread platform event loop" main/global actor as well. but those belong in LibWeb, not LibCore.

LibCore: Add swift bindings for EventLoop as an Executor and Actor

---

Libraries/LibWebView/SiteIsolation.cpp
Tests/LibWeb/Text/expected/HTML/javascript-navigation-stays-in-same-process.txt
Tests/LibWeb/Text/input/HTML/javascript-navigation-stays-in-same-process.html

JavaScript URLs run in the same document context the navigation was started in, so they're not eligible to be moved to a new WebContent process.
Fixes the "Login as demo user" link on https://demo.immich.app/

LibWebView: Keep javascript URL navigations in the same process

---

Libraries/LibWeb/Layout/LayoutState.cpp
Libraries/LibWeb/Painting/PaintableBox.cpp
Libraries/LibWeb/Painting/PaintableFragment.h
Libraries/LibWeb/Painting/TextPaintable.h

Fixes underinvalidation caused by resolving text-decoration-thickness during layout commit, while this property can be invalidated independently of layout.

LibWeb: Invalidate text-decoration-thickness as paint-only property

---

Toolchain/Nix/shell.nix

Fixes: #3896
The package prettier doesn't exist and is instead called nodePackages.prettier

Nix: Fix error 'Function called without required argument "prettier"'

---

Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLSelectElement.cpp

No behavior change, just updating spec comments and moving things around a little.
Actually making this properly match the spec is left as an exercise to the reader. We don't seem to follow it very closely currently, or at least the other locations where parts of the algorithm get implemented have no spec comments.

LibWeb/HTML: Add stub for WebDriver BiDi to intercept file dialogs

---

Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Libraries/LibWeb/HTML/HTMLLinkElement.h
Libraries/LibWeb/HTML/HTMLLinkElement.idl
Tests/LibWeb/Text/expected/css/HTMLLinkElement-sheet.txt
Tests/LibWeb/Text/input/css/HTMLLinkElement-sheet.html

This returns the link element's associated style sheet.

LibWeb: Implement the `HTMLLinkElement.sheet` attribute

---

Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Libraries/LibWeb/Layout/FlexFormattingContext.cpp
Libraries/LibWeb/Layout/FormattingContext.cpp
Libraries/LibWeb/Layout/GridFormattingContext.cpp
Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Libraries/LibWeb/Layout/LayoutState.h
Libraries/LibWeb/Layout/Node.cpp
Libraries/LibWeb/Layout/TableFormattingContext.cpp
Tests/LibWeb/Layout/expected/blockify-layout-internal-box-without-crashing.txt
Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/abspos/static-inside-inline-block-ref.html
Tests/LibWeb/Ref/input/wpt-import/css/CSS2/abspos/static-inside-inline-block.html

Continues #2583.
Sets inline block offsets in [InlineFormattingContext.cpp](https://github.com/LadybirdBrowser/ladybird/compare/master...stasoid:abspos?expand=1#diff-0da65fb31880577ee20998b781ee4ff026e523693a64730ea6878ffeb8cdf02a), but this is not enough. When static position rect is calculated during layout, not all ancestors of abspos box may have their offsets calculated yet ([more info here](https://github.com/LadybirdBrowser/ladybird/pull/2583#issuecomment-2507140272)). So now static position rect is calculated relative to static containing block during layout and calculation relative to actual containing block is postponed until [`FormattingContext::layout_absolutely_positioned_element`](https://github.com/LadybirdBrowser/ladybird/compare/master...stasoid:abspos?expand=1#diff-68eef5 …

LibWeb: Correctly calculate static position rect when absolutely positioned element is a descendant of inline-block

---

Libraries/LibRegex/RegexByteCode.cpp
Libraries/LibRegex/RegexByteCode.h
Tests/LibRegex/Regex.cpp

When a lookahead operation runs, it saves the current position. However, if that lookahead contains another lookahead and the nested one fails, the original implementation does not properly clean up the saved state from the nested lookahead.
This causes a misalignment in the save/restore stack.
I add a check to avoid empty vector error on consecutive lookhaead as shown in issue #3942

LibRegex: Remove orphaned save points in nested LookAhead

---

Libraries/LibWeb/SVG/SVGCircleElement.cpp
Tests/LibWeb/Crash/Layout/svg-circle-element-crash-no-layout-node.html

This is clearly not the correct fix, but instead of crashing let's log an error and bail.
Works around a crash seen on both:
* https://reddit.com
* https://www.w3.org/TR/web-animations-1 (#879)

LibWeb/SVG: Work around no layout node in SVGCircleElement::get_path

---

Libraries/LibWeb/CSS/ResolvedCSSStyleDeclaration.cpp
Tests/LibWeb/Text/expected/wpt-import/css/cssom/getComputedStyle-insets-absolute.txt
Tests/LibWeb/Text/expected/wpt-import/css/cssom/getComputedStyle-insets-relative.txt
Tests/LibWeb/Text/input/wpt-import/css/cssom/getComputedStyle-insets-absolute.html
Tests/LibWeb/Text/input/wpt-import/css/cssom/getComputedStyle-insets-relative.html
Tests/LibWeb/Text/input/wpt-import/css/cssom/support/getComputedStyle-insets.js

This improves the output of `getComputedStyle()` for the `top`, `bottom`, `left` and `right` properties, where the used value is now returned rather than the computed value, where applicable.
This fixes 290 WPT subtests in the `css/cssom` directory.

LibWeb: Calculate the correct resolved value for inset properties

---

Tests/LibWeb/TestConfig.ini

I just had this flake on me, and it's only been once, but given it uses a known-unimplemented mechanism it's bound to flake again in the future. IMO it's better to disable it.

Tests: Disable fDAT-inherits-cICP.html test that uses "reftest-wait"

---

Libraries/LibJS/Print.cpp
Libraries/LibJS/Runtime/Intl/AbstractOperations.cpp
Libraries/LibJS/Runtime/Intl/AbstractOperations.h
Libraries/LibJS/Runtime/Intl/DateTimeFormat.cpp
Libraries/LibJS/Runtime/Intl/DateTimeFormat.h
Libraries/LibJS/Runtime/Intl/DateTimeFormatConstructor.cpp
Libraries/LibJS/Runtime/Intl/DurationFormat.cpp
Libraries/LibJS/Runtime/Intl/DurationFormat.h
Libraries/LibJS/Runtime/Intl/DurationFormatConstructor.cpp
Libraries/LibJS/Runtime/Intl/DurationFormatPrototype.cpp
Libraries/LibJS/Runtime/Intl/ListFormatPrototype.cpp
Libraries/LibJS/Runtime/Intl/NumberFormatConstructor.cpp
Libraries/LibJS/Runtime/Intl/NumberFormatPrototype.cpp
Libraries/LibJS/Runtime/Intl/PluralRulesConstructor.cpp
Libraries/LibJS/Runtime/Intl/PluralRulesPrototype.cpp
Libraries/LibJS/Runtime/Intl/RelativeTimeFormatConstructor.cpp
Libraries/LibJS/Runtime/Intl/RelativeTimeFormatPrototype.cpp
Libraries/LibJS/Runtime/Intl/SegmenterPrototype.cpp
Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.format.js
Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatRange.js
Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatRangeToParts.js
Libraries/LibJS/Tests/builtins/Intl/DateTimeFormat/DateTimeFormat.prototype.formatToParts.js
Libraries/LibJS/Tests/builtins/Intl/NumberFormat/NumberFormat.prototype.resolvedOptions.js
Libraries/LibJS/Tests/builtins/Intl/RelativeTimeFormat/RelativeTimeFormat.prototype.format.js
Libraries/LibUnicode/DurationFormat.cpp
Libraries/LibUnicode/NumberFormat.cpp
Libraries/LibUnicode/NumberFormat.h

test262 diff:
```
test/intl402/NumberFormat/currency-digits-nonstandard-notation.js ❌ -> ✅
```
(which brings us back to 100% `Intl.NumberFormat` passing)

LibJS: A handful of Intl updates

---

Libraries/LibWeb/Page/EventHandler.cpp

On macOS, we should use the Cmd (Super) modifier key along with the arrow keys to scroll to the beginning/end of the document, or navigate back and forth in the history, rather than the Ctrl or Alt keys.

LibWeb: Use Super on macOS for page scroll/nav

---

Libraries/LibWeb/HTML/Storage.cpp
Tests/LibWeb/Text/data/local-storage-iframe.html
Tests/LibWeb/Text/expected/HTML/local-storage-usage-after-nav.txt
Tests/LibWeb/Text/input/HTML/local-storage-usage-after-nav.html

A `Storage` object may be created with an existing storage bottle. For example, if you navigate from site.com/page1 to site.com/page2, they will have different `localStorage` objects, but will use the same bottle for actual storage.
Previously, if page1 set some key/value item, we would initialize the byte count to 0 on page2 despite having a non-empty bottle. Thus, if page2 set a smaller value with the same key, we would overflow the computed byte count, and all subsequent writes would be rejected.
This was seen navigating from the chess.com home page to the daily puzzle page.

LibWeb: Initialize the Storage byte count upon creation

---

AK/Function.h
AK/Platform.h
AK/StdLibExtraDetails.h
AK/TypeCasts.h
Libraries/LibCore/CMakeLists.txt
Libraries/LibCore/EventSwift.mm
Meta/CMake/FindBlocksRuntime.cmake
Meta/CMake/Swift/InitializeSwift.cmake
Meta/CMake/common_options.cmake
Meta/Lagom/CMakeLists.txt
Tests/AK/CMakeLists.txt
Tests/AK/TestFunction.mm

With a bit of gnarly preprocessor and if constexpr magic, we can get this to work the same way-ish that libc++'s std::function handles block closures.
cc @bugaevc , in case you have any objective-c wisdom :)

AK: Support capturing Objective-C block closures in AK::Function

---

Tests/LibWeb/TestConfig.ini

259d39cb was not enough to make this test pass reliably, so let's disable it back for now.

Tests: Disable `css/css-lists/list-style-type-string-004.html`

---

Libraries/LibWeb/CSS/GridTrackPlacement.cpp
Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-area-computed.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-area-shorthand.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-area-valid.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-column-shortest-serialization.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-column-shorthand.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-row-shortest-serialization.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-row-shorthand.txt

This fixes 30 WPT subtests in the `css/css-grid` directory.

LibWeb: Use shortest serialization for `grid-row` and `grid-column` values

---

Libraries/LibWeb/HTML/Window.cpp

The spec PR for this is currently open at https://github.com/w3c/csswg-drafts/pull/11964.

LibWeb: Import typo fix from the spec

---

Libraries/LibWeb/Layout/GridFormattingContext.cpp
Tests/LibWeb/Layout/expected/grid/replaced-item-2.txt
Tests/LibWeb/Layout/input/grid/replaced-item-2.html
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-implies-size-change-013.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-implies-size-change-014.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-implies-size-change-015.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-implies-size-change-016.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-implies-size-change-031.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-implies-size-change-032.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-implies-size-change-033.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-implies-size-change-034.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-style-changes-005.txt
Tests/LibWeb/Text/expected/wpt-import/css/css-grid/alignment/grid-alignment-style-changes-006.txt

With this change we no longer stretch "width: auto" for replaced boxes and also use width calculation rules for block-level replaced elements, like suggested by the spec.

LibWeb/Layout: Improve grid item sizing for replaced boxes

---

Libraries/LibDevTools/Actors/FrameActor.cpp
Libraries/LibDevTools/Actors/PageStyleActor.cpp
Libraries/LibDevTools/Actors/PageStyleActor.h
Libraries/LibDevTools/DevToolsDelegate.h
Libraries/LibWebView/Application.cpp
Libraries/LibWebView/Application.h
Libraries/LibWebView/CMakeLists.txt
Libraries/LibWebView/DOMNodeProperties.cpp
Libraries/LibWebView/DOMNodeProperties.h
Libraries/LibWebView/Forward.h
Libraries/LibWebView/ViewImplementation.cpp
Libraries/LibWebView/ViewImplementation.h
Libraries/LibWebView/WebContentClient.cpp
Libraries/LibWebView/WebContentClient.h
Services/WebContent/ConnectionFromClient.cpp
Services/WebContent/ConnectionFromClient.h
Services/WebContent/WebContentClient.ipc
Services/WebContent/WebContentServer.ipc

When we inspect a DOM node, we currently serialize many properties for that node, including its layout, computed style, used fonts, etc. Now that we aren't piggy-backing on the Inspector interface, we can instead only serialize the specific information required by DevTools.

LibDevTools: Some post Inspector-removal cleanup

---

Libraries/LibCrypto/BigInt/Algorithms/BitwiseOperations.cpp
Libraries/LibCrypto/BigInt/Algorithms/UnsignedBigIntegerAlgorithms.h
Libraries/LibCrypto/BigInt/SignedBigInteger.cpp
Libraries/LibCrypto/BigInt/SignedBigInteger.h
Libraries/LibCrypto/BigInt/UnsignedBigInteger.cpp
Libraries/LibCrypto/BigInt/UnsignedBigInteger.h
Libraries/LibJS/Runtime/BigIntConstructor.cpp
Libraries/LibJS/Runtime/ErrorTypes.h
Libraries/LibJS/Tests/builtins/BigInt/BigInt.asIntN.js
Libraries/LibJS/Tests/builtins/BigInt/BigInt.asUintN.js

This speeds up expressions such as `BigInt.asIntN(0x4000000000000, 1n)` (https://github.com/LadybirdBrowser/ladybird/pull/3615), and those involving very large bigints. Instead of `modulo()` we just cut off high bits.

LibJS+LibCrypto: Use a bitwise approach for BigInt's as*IntN methods

---

AK/JsonParser.cpp
AK/JsonParser.h
AK/JsonValue.cpp
Libraries/LibWeb/WebDriver/Client.cpp
Meta/Lagom/Fuzzers/FuzzJsonParser.cpp
UI/Qt/AutoComplete.cpp
UI/Qt/AutoComplete.h

`JsonParser` only holds a view into the provided string, the caller must keep it alive. Though we can actually just use `JsonValue::from_string` here instead.
Fixes #4005

UI/Qt: Prevent UAF while parsing autocomplete response data

---

.github/workflows/ci.yml
.github/workflows/lint-code.yml
.github/workflows/lint-commits.yml

We can prevent running builds unnecessarily by requiring the linters to succeed first. If either the code or commit linter fails, it means the author of the PR needs to rework their branch and after pushing their changes, we need to do a full new CI run anyway.

CI: Only run builds after successful linting

---

.github/workflows/ci.yml

This requires us to always run the CI job and check the individual jobs' results, since only having `needs:` will not work when `lint_commits` is potentially skipped.
Should fix the red CI on master.

CI: Only run commit linter for pull requests, not pushes

---

UI/AppKit/Application/ApplicationDelegate.mm
UI/AppKit/Interface/InfoBar.h
UI/AppKit/Interface/InfoBar.mm
UI/Qt/BrowserWindow.cpp

The "disable DevTools" button looked like a "close this notification" button to me, and although a tooltip was set, it only showed up immediately on the AppKit UI and not the Qt version.
This makes the behavior of clicking the disable button a lot clearer by showing a button with "Disable" as its title.
CC @trflynn89

UI: Show "Disable" title in DevTools disable button

---

Libraries/LibJS/Bytecode/Interpreter.cpp
Libraries/LibJS/Tests/builtins/Proxy/for-in-iteration-traps.js

Before this change, we would enumerate all the keys with [[OwnPropertyKeys]], and then do [[GetOwnPropertyDescriptor]] twice for each key as we went through them.
We now only do one [[GetOwnPropertyDescriptor]] per key, which drastically reduces the number of proxy traps when those are involved. The new trap sequence matches what you get with V8, so I don't think anyone will be unpleasantly surprised here.
This reduces proxy thrashing on https://demo.immich.app/ considerably, but performance is still unreasonably bad.

LibJS: Reduce number of proxy traps called during for..in iteration

---

.github/workflows/ci.yml
.github/workflows/lint-code.yml
.github/workflows/lint-commits.yml

This reverts commits bf333eaea253ebf47c7d6192ff0c42e7a198d606 and 6f69a445bd3d2fd5bbd61b3b3cea47df18fa6242.
The commit linter needs to run on event `pull_request_target` to have access to its secret token, which means we cannot have a dependency on that job from another workflow that is run as a result of the `pull_request` event.
Additionally, the linters were no longer run for first-time contributors. This isn't a huge problem but it was nice that a preliminary check took place before running the full CI on their PRs.

Revert "CI: Only run builds after successful linting"

---

Libraries/LibWeb/CSS/ComputedProperties.cpp
Tests/LibWeb/Crash/CSS/table-border-spacing-calc.html

Previously, the browser would crash if the `border-spacing` property had 2 lengths and either one of these was set to a `calc()` value.

LibWeb: Don't crash when `border-spacing` is set to a `calc()` value

---

Libraries/LibWeb/Layout/GridFormattingContext.cpp
Libraries/LibWeb/Layout/GridFormattingContext.h

It was annoying to maintain two separate but almost identical functions
that gradually accumulated small differences over time. This change
replaces them with a single function that resolves either width or
height, depending on the specified dimension.

LibWeb: Unify grid item's width and height resolution in GFC

---

Libraries/LibWeb/Layout/FormattingContext.cpp
Tests/LibWeb/Layout/expected/block-and-inline/percentage-height-abspos-box-with-percentage-height-child.txt
Tests/LibWeb/Layout/input/block-and-inline/percentage-height-abspos-box-with-percentage-height-child.html

...boxes with non-auto height.
We know for sure that by the time we layout abspos boxes, their containing block has definite height, so it's possible to resolve non-auto heights and mark it as definite before doing inner layout.
Big step towards having reasonable performance on
https://demo.immich.app/photos because now we avoid a bunch of work initiated by mistakenly invoked intersection observer callbacks.

LibWeb: Mark height as definite before doing inner layout of abspos

---

Libraries/LibWeb/HTML/HTMLStyleElement.cpp
Libraries/LibWeb/HTML/HTMLStyleElement.h
Libraries/LibWeb/HTML/HTMLStyleElement.idl
Tests/LibWeb/Text/expected/wpt-import/html/semantics/document-metadata/the-style-element/style_media_change.txt
Tests/LibWeb/Text/input/wpt-import/html/semantics/document-metadata/the-style-element/style_media_change.html

Previously, we would only invalidate style when setting the `media` IDL attribute; changing the attribute via `setAttribute()` and `removeAttribute()` had no immediate effect.
I came across this while looking at: http://wpt.live/css/mediaqueries/test_media_queries.html. 
This change causes a regression of -70 subtests in this particular case :sob:. I believe this change makes things more correct though, as the media queries that this test dynamically generates weren't previously being evaluated.

LibWeb: Invalidate style when `media` content attribute changes

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Element.cpp
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/DOM/Element.idl
Libraries/LibWeb/DOM/Range.cpp
Libraries/LibWeb/HTML/HTMLInputElement.cpp
Libraries/LibWeb/HTML/HTMLSelectElement.cpp
Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp
Libraries/LibWeb/WebDriver/Actions.cpp
Libraries/LibWeb/WebDriver/ElementReference.cpp
Services/WebContent/WebDriverConnection.cpp
Services/WebContent/WebDriverConnection.h

Instead of bothering the GC heap with a bunch of DOMRect allocations, we can just pass around CSSPixelRect internally in many cases.
Before this change, we were generating so much DOMRect garbage that we had to do a garbage collection *every frame* on the Immich demo. This was due to the large number of intersection observers checked.
We still need to relax way more when idle, but for comparison, before this change, when doing nothing for 10 seconds on Immich, we'd spend 2.5 seconds updating intersection observers. After this change, we now spend 600 ms.

LibWeb: Avoid allocating DOMRect objects for internal engine use

---

Libraries/LibJS/Bytecode/Interpreter.cpp
Libraries/LibJS/Runtime/AsyncFromSyncIteratorPrototype.cpp
Libraries/LibJS/Runtime/Iterator.cpp
Libraries/LibJS/Runtime/Iterator.h
Libraries/LibJS/Runtime/Object.h
Libraries/LibJS/Runtime/Value.h

This shaves its size down from 104 bytes to 48 bytes, cutting GC pressure caused by this type in more than half.
Iteration helper objects are a major contributor to GC thrashing on https://demo.immich.app/

LibJS: Make IteratorRecord inherit from Cell, not Object

---

Libraries/LibWeb/DOM/Element.cpp
Tests/LibWeb/Text/expected/wpt-import/css/selectors/dir-pseudo-on-bdi-element.txt

This fixes three WPT test cases at html/dom/elements/global-attributes/dir-assorted.window.html

LibWeb: Update Element::directionality() for bdi elements to match spec

---

Libraries/LibCrypto/BigFraction/BigFraction.cpp
Libraries/LibCrypto/BigInt/Algorithms/BitwiseOperations.cpp
Libraries/LibCrypto/BigInt/Algorithms/GCD.cpp
Libraries/LibCrypto/BigInt/Algorithms/ModularInverse.cpp
Libraries/LibCrypto/BigInt/Algorithms/ModularPower.cpp
Libraries/LibCrypto/BigInt/Algorithms/Multiplication.cpp
Libraries/LibCrypto/BigInt/Algorithms/UnsignedBigIntegerAlgorithms.h
Libraries/LibCrypto/BigInt/UnsignedBigInteger.cpp
Libraries/LibCrypto/NumberTheory/ModularFunctions.cpp
Tests/LibCrypto/TestBigFraction.cpp
Tests/LibCrypto/TestBigInteger.cpp

Passes all Temporal tests in [test262](https://github.com/LadybirdBrowser/libjs-test262) (fixes #2639) :
1. Maybe shift left the numerator of a `BigFraction` so that its most significant bit is 64 bits left of that of the denominator.
2.  Divide numerator to denominator (`BigInteger::divide_by`).
3. Convert the quotient of the result to double (`BigInteger::to_double`).
- Add a "fake 1" to the quotient to simulate rounding effects by a non-zero remainder.
4. Shift back the result by reducing the exponent of the floating point representation.
Bonus:
- Extend `BigInteger::shift_right` to support multi-word shift (a waiting bug).
- Improve the efficiency of a number of operations by removing a copies and unnecessary intermediate variables.

LibCrypto: Improve precision of BigFraction::to_double

---

.github/workflows/js-benchmarks.yml

This is GitHub's default maximum. Prevents generating a warning on each workflow run.

CI: Reduce js-benchmarks artifact retention to 90 days

---

Libraries/LibWeb/Layout/GridFormattingContext.cpp
Tests/LibWeb/Layout/expected/grid/minmax-with-percentage-max.txt
Tests/LibWeb/Layout/input/grid/minmax-with-percentage-max.html

Fixes crashing when trying to get length from LengthPercentage with percentage value.

LibWeb: Don't assume length-percentage is always a length [GFC]

---

Libraries/LibJS/Runtime/PropertyKey.h
Libraries/LibJS/Runtime/Value.cpp

Previously, `String.prototype.split()` caused the construction of a temporary StringObject when a string primitive was passed as an argument, solely to perform a Symbol.split lookup. This change allows skipping that allocation by looking directly into the prototype of primitive values.
As a result, we can avoid ~200000 StringObject allocations in a single test from the Speedometer 2 benchmark.

LibJS: Skip allocation of temp object for primitive types in Value::get

---

Libraries/LibWeb/Animations/Animatable.cpp
Libraries/LibWeb/Animations/Animatable.h

Instead of reserving space for data required to run animations in every DOM element, we now allocate it lazily only if element actually has some animations. This allows us to save 336 bytes on non-animated DOM elements.

LibWeb: Lazily allocate data required to run CSS animations

---

Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
Libraries/LibJS/Tests/builtins/TypedArray/TypedArray.prototype.set.js

This ones a bit sneaky, the overflow happens before the `checked +=`

LibJS: Fix integer overflow in `target_offset` of `TypedArray.set()`

---

Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.h

This reduces the size of CubicBezier objects from 1592 bytes to 56 bytes.
Allocations of this object showed up when profiling Speedometer2.

LibWeb: Remove CubicBezier cached sample inline cache

---

Libraries/LibWeb/CSS/CSSFontFaceRule.cpp
Libraries/LibWeb/CSS/ParsedFontFace.h
Libraries/LibWeb/CSS/Parser/Parser.h
Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
Libraries/LibWeb/Dump.cpp

A couple of tweaks here, as preparation for parsing at-rule descriptors in a similar way to how we currently parse properties. The last commit also makes us parse and serialize `local(...)` sources more correctly, but I haven't checked if it helps on WPT.

LibWeb: Improve font property parsing

---

Libraries/LibWeb/Page/Page.cpp

Safari and WebKit don't apply these, while Firefox only applies the zoom level. This fixes https://x.com/ showing the tablet view.

LibWeb: Don't apply DPR or zoom level to screen.{width,height}

---

Meta/WPT.sh

On some macs, the default maximum number of file descriptors is 256. This quickly makes the WPT runner run out of descriptors, so let's check the active value and increase the soft limit if necessary.

Meta: Increase max open file descriptors in WPT.sh

---

AK/FlyString.cpp
AK/FlyString.h
AK/String.cpp
AK/String.h

This is to help recover some of the performance regression from no longer using DeprecatedFlyString (which was aggressively inlined.)

AK: Inline more of the String and FlyString member functions

---

Tests/LibWeb/TestConfig.ini

See https://github.com/LadybirdBrowser/ladybird/issues/3911. The `html/rendering/replaced-elements/svg-inline-sizing/svg-inline.html` WPT test is causing a hang/timeout that prevents being able to run the test suite to completion with Debug builds.

Tests: Skip the svg-inline-sizing/svg-inline.html WPT test for now

---

.github/workflows/js-benchmarks.yml

In practice this does not make a big difference, but technically it could happen that a second JS Repl artifact was built before the first JS Benchmarks job is executed. So make sure to filter on commit ID.

CI: Make JS Benchmarks use the JS repl from the job with the same commit

---

Libraries/LibWeb/Layout/FormattingContext.cpp
Libraries/LibWeb/Layout/LayoutState.cpp
Libraries/LibWeb/Layout/LayoutState.h
Tests/LibWeb/Layout/expected/grid/min-max-content.txt
Tests/LibWeb/Layout/expected/table/style-invalidation-propagation-to-table-wrapper.txt

It's safe to remove this pointer because intrinsic layout should never look up a box's state beyond its containing block.
This change affects the expectations of two layout tests, but both already differ slightly from other browsers, and the difference between expectations is less than 5px.

LibWeb: Delete parent state pointer in LayoutState

---

AK/StringData.h

Hopefully this will make GCC happier about building test262-runner and pals.

AK: Don't try to free(UINTPTR_MAX) in StringData::operator delete()

---

Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/Layout/Box.cpp
Libraries/LibWeb/Layout/Box.h

Allows us to avoid DOM node lookup whenever we need to query natural size of a box during layout.
Makes 3-4% of `Box::preferred_aspect_ratio()` go away from profiles on www.nyan.cat

LibWeb: Cache "has size containment" flag in Layout::Box

---

Libraries/LibWeb/Layout/LineBox.cpp
Libraries/LibWeb/Layout/LineBox.h
Libraries/LibWeb/Layout/LineBuilder.cpp
Tests/LibWeb/Layout/expected/block-and-inline/float-following-trailing-whitespace.txt
Tests/LibWeb/Layout/input/block-and-inline/float-following-trailing-whitespace.html

When generating line boxes, we place floats simultaneously with the other items on the same line. The CSS text spec requires us to trim the whitespace at the end of each line, but we only did so after laying out all the line boxes.
This changes the way we calculate the current line box width for floats by subtracting the amount of pixels that the current trailing whitespace is using.
Fixes #4050.

LibWeb: Exclude trailing whitespace from line width when placing floats

---

Base/res/ladybird/templates/error.html
Libraries/LibWebView/ViewImplementation.cpp

Co-authored-by: notnotnescap <97590612+nescapp@users.noreply.github.com>
- Changed the error page, so that it looks better feedback from discord and the artist ( https://github.com/LadybirdBrowser/ladybird/commit/96a5b97131ad4a3a422e0c3e784186f37d050e74 ) 
- Modified the error/crash page so it looks more in line with the 404 page and the brand guidelines.

UI: Changed the error page and modified the 404 page

---

Libraries/LibWeb/Painting/StackingContext.cpp
Tests/LibWeb/Ref/expected/scrolled-svg-path-with-transform.html
Tests/LibWeb/Ref/input/scrolled-svg-path-with-transform.html

Now we use `before_paint()` and `after_paint()` calls for SVG root box to make sure that both clip and scroll are applied.
Fixes painting of SVG arrows on www.ubereats.com

LibWeb: Fix scroll offset application for SVG root box

---

Meta/shell_include.sh

Busybox version of `sort` utility doesn't support `--version-sort` and `--check` CLI args, only their short alternatives (`-V` and `-c`, respectively). 
Use the short alternatives to gain the busybox compatibility.
Fixes #3884

make build script compatible with busybox

---

Meta/CMake/common_compile_options.cmake

Otherwise we get a ton of errors about unqualified calls to `move` from clangd.

Meta: Add -Wno-unqualified-std-cast-call to GCC compile flags

---

Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Tests/LibWeb/Layout/expected/block-and-inline/float-clear-simultaneously.txt
Tests/LibWeb/Layout/input/block-and-inline/float-clear-simultaneously.html

We used to always clear the side data after encountering a box with `clear: ..`, but this is not the right thing to do if that same box also has `float: ..` set. For example, with `clear: right` and `float: left` it might be that the next box still wants to clear the right side, and since the previous box is floating it did not push the next box down far enough to justify clearing the side data at that point.
This changes the logic to only clear the float side if the clearing box itself is not floating. We also no longer clear the opposite side after placing a floating box; that doesn't seem to be necessary anymore.
No WPT regressions (nor any improvements 😞) in `css/CSS2/floats` and `css/CSS2/floats-clear`.
Fixes #4102.

LibWeb: Do not clear float sides for floating boxes with `clear: ..`

---

Libraries/LibWeb/Layout/LineBuilder.cpp
Tests/LibWeb/Layout/expected/block-and-inline/float-initial-available-space-vs-height.txt
Tests/LibWeb/Layout/expected/block-and-inline/float-vertical-clearance-ignores-opposite-side.txt
Tests/LibWeb/Layout/input/block-and-inline/float-initial-available-space-vs-height.html
Tests/LibWeb/Layout/input/block-and-inline/float-vertical-clearance-ignores-opposite-side.html

Our recent change to get rid of the "move 1px at a time" algorithm in the float positioning logic introduced the issue that potentially intersecting float boxes were not evaluated in order anymore. This could result in float boxes being pushed down further than strictly necessary.
By finding the highest point we can move the floating box to and repeating the process until we're no longer intersecting any floating box, we also solve some edge cases like intersecting with very long floating boxes whose edges lay outside the current box' edges.
This is by no means the most efficient solution, but it is more correct than what we had until now.
Fixes #4110.

LibWeb: Fix and improve float positioning behavior

---

Libraries/LibJS/Bytecode/Generator.h
Libraries/LibJS/Bytecode/Interpreter.cpp
Libraries/LibJS/Tests/try-finally-break.js

This works because at the end of the finally block, a `ContinuePendingUnwind` is generated which copies the saved return value register into the return value register. In cases where `ContinuePendingUnwind` is not generated such as when there is a break statement in the finally block, the fonction will return undefined which is consistent with V8 and SpiderMonkey.
If you were to run this script before the fix:
```js
function foo() {
do {
try {
return "bar";
} finally {
break;
}
} while (true);
}
console.log(foo());
```
It would print `"bar"` on LibJS and `undefined` on other JS engines.
```shell
❯ node a.js
undefined
❯ js a.js
"bar"
```

LibJS: Avoid emptying the return value register in try/finally

---

Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Libraries/LibWeb/Layout/LineBox.cpp
Tests/LibWeb/Layout/expected/block-and-inline/float-clear-by-line-break.txt
Tests/LibWeb/Layout/input/block-and-inline/float-clear-by-line-break.html

We were introducing a line break and applying vertical clearance to the inline formatting context, but that vertical clearance only applied to new floating boxes. We should move the current block offset to the vertical clearance to make sure the next line box starts beyond the cleared floats.
There was a layout test for `<br>` with `clear: ..` set, but that test did not actually do anything - removing the `clear` property would result in the same layout. Replace that test with something that actually tests float clearing.
Relates to #4058.

LibWeb: Apply vertical clearance to next line after <br> with `clear:`

---

Libraries/LibWebView/HelperProcess.cpp
Services/WebWorker/main.cpp

The createImageBitmap API can programmatically decode arbitrary images from JS, and it's exposed in Workers, so they need an ImageDecoder instance.

LibWebView+WebWorker: Attach an image decoder to worker instances

---

Tests/LibWeb/Crash/JS/finalization-registry-basic.html

Print statements aren't necessary in crash tests and will cause a Javascript error when used.

Tests: Remove print statement from crash test

---

Libraries/LibWebView/URL.cpp
Tests/LibWebView/TestWebViewURL.cpp

With search enabled:
- For a single word that does not look like a url: search (fixes #142).
- If no suffix or a suffix that is not recognized: search (like Firefox).
In general:
- Respect the user's choice if they specified a scheme.
- Respect `localhost`.
- As before, add `file://` to filesystem files that exist.

LibWebView: Better integration of sanitize_url with search

---

Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Libraries/LibWeb/Layout/TreeBuilder.cpp
Tests/LibWeb/Layout/expected/block-and-inline/list-markers-intruded-by-float.txt
Tests/LibWeb/Layout/expected/details-closed.txt
Tests/LibWeb/Layout/expected/details-open.txt
Tests/LibWeb/Layout/expected/details-summary-default-ua-style.txt
Tests/LibWeb/Layout/expected/inside-list-item-content-offset.txt
Tests/LibWeb/Layout/expected/list-item-marker-pseudo-placement.txt
Tests/LibWeb/Layout/expected/ordered-list.txt
Tests/LibWeb/Layout/input/inside-list-item-content-offset.html
Tests/LibWeb/Layout/input/list-item-marker-pseudo-placement.html

- Fix `::marker` (pseudo element) placement in tree
- Fix `list-style-position: inside` overriding content offset

LibWeb: Fix a few list-item layout bugs

---

Libraries/LibWeb/IndexedDB/IDBDatabase.cpp

Prevents a crash because `ReadonlySpan.copy_to()` was trying to copy to an empty vector.
Fixes #4127.

LibWeb: Copy IDBDatabase object stores through `Vector(ReadonlySpan)`

---

Libraries/LibWeb/Layout/FormattingContext.cpp
Tests/LibWeb/Layout/expected/block-and-inline/aspect-ratio-but-width-and-height-are-auto.txt
Tests/LibWeb/Layout/input/block-and-inline/aspect-ratio-but-width-and-height-are-auto.html

Otherwise we apply `calculate_stretch_fit_width()` instead of calculating width based on the content inside the box, like other browsers do.

LibWeb: Size box as normal if it has aspect ration but auto sizes

---

Libraries/LibWeb/Layout/LineBuilder.cpp

Unfortunately, this doesn't work the citation links on Wikipedia :sob:, it also leads to selections looking slightly odd.
Leads to a visual improvement in: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup   
Before:
After:
and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sub
Before:
After:

LibWeb: Alter the baseline of text with `vertical-align` `super` and `sub`

---

Libraries/LibIDL/IDLParser.cpp
Libraries/LibIDL/Types.h
Libraries/LibWeb/DOM/Document.cpp
Libraries/LibWeb/DOM/Event.cpp
Libraries/LibWeb/HTML/Location.cpp
Libraries/LibWeb/HTML/Window.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Text/expected/DOM/Document-has-unforgeable-properties.txt
Tests/LibWeb/Text/expected/DOM/Event-has-unforgeable-properties.txt
Tests/LibWeb/Text/expected/HTML/Location-has-unforgeable-properties.txt
Tests/LibWeb/Text/expected/HTML/Window-has-unforgeable-properties.txt
Tests/LibWeb/Text/input/DOM/Document-has-unforgeable-properties.html
Tests/LibWeb/Text/input/DOM/Event-has-unforgeable-properties.html
Tests/LibWeb/Text/input/HTML/Location-has-unforgeable-properties.html
Tests/LibWeb/Text/input/HTML/Window-has-unforgeable-properties.html

Part 5 of splitting up https://github.com/LadybirdBrowser/ladybird/pull/2854
----
This fixes the frame-ancestors WPT tests from crashing when an iframe is blocked from loading. This is because it would get an undefined location.href from the cross-origin iframe, which causes a crash as it expects it to be there.

LibWeb: Implement the LegacyUnforgeable attribute

---

.github/workflows/js-artifacts.yml

It might be useful to have these artifacts, even for older commits. As an added bonus, this causes the JS benchmarks to run as well giving us more datapoints.

CI: Do not cancel in-progress JS artifact builds

---

Libraries/LibWeb/Layout/BlockFormattingContext.cpp
Tests/LibWeb/Layout/expected/block-and-inline/max-width-on-block-level-box-that-creates-fc.txt
Tests/LibWeb/Layout/input/block-and-inline/max-width-on-block-level-box-that-creates-fc.html

...for block level boxes. Otherwise we end up resolving auto width as
zero during intrinsic layout, which leads to incorrectly applied
max-width constraint.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4123

Respect min/max-content available size in auto width calculation

---

Libraries/LibWeb/DOM/DocumentLoading.cpp

Corresponds to https://github.com/whatwg/html/commit/2ab779b8e847fe132b4cf5ac3a2cb4ad2fdc4ef2
We don't implement most of what that touches, so the only actual change is a couple of words added here.

LibWeb/DOM: Update step 4 of load_document()

---

Libraries/LibJS/Bytecode/ASTCodegen.cpp
Libraries/LibJS/Bytecode/Generator.h

I noticed that around ~30% of `Mov` instructions generated are redundant because the source and the destination is the same `ScopedOperand`.
Here are some numbers I gathered:
ReactJS homepage: 1987/7352 = 27% redundancy
LibJS test suite: 1492/5026 = 30% redundancy
My theory is that it is due to this kind of successive calls:
```c++
auto dst = choose_dst(generator, preferred_dst);
auto lhs = TRY(m_lhs->generate_bytecode(generator, preferred_dst)).value();
generator.emit_mov(dst, lhs);
```
where `generate_bytecode` tries to put his output in `dst` and the `Mov` should act as a fallback (if I understand correctly).
To test my theory I added a preferred destination in another place where I saw the pattern above (in my subsequent commit).
The number of `Mov`s between scoped operands in LibJS …

LibJS: Optimize away Mov instructions when the source is the destination

---

Libraries/LibJS/Contrib/Test262/262Object.cpp
Libraries/LibJS/Contrib/Test262/GlobalObject.cpp
Libraries/LibJS/Runtime/AbstractOperations.cpp
Libraries/LibJS/Runtime/AggregateErrorConstructor.cpp
Libraries/LibJS/Runtime/DatePrototype.cpp
Libraries/LibJS/Runtime/NumberPrototype.cpp
Libraries/LibJS/Runtime/ObjectPrototype.cpp
Libraries/LibJS/Runtime/PrimitiveString.cpp
Libraries/LibJS/Runtime/PrimitiveString.h
Libraries/LibJS/Runtime/RegExpPrototype.cpp
Libraries/LibJS/Runtime/RegExpStringIteratorPrototype.cpp
Libraries/LibJS/Runtime/ShadowRealmPrototype.cpp
Libraries/LibJS/Runtime/VM.cpp
Libraries/LibJS/Runtime/VM.h
Libraries/LibJS/Runtime/Value.cpp
Libraries/LibJS/Runtime/ValueTraits.h
Libraries/LibWeb/HTML/Scripting/Fetching.cpp
Libraries/LibWeb/HTML/Scripting/Fetching.h
Libraries/LibWeb/HTML/Scripting/ImportMap.cpp
Services/WebContent/ConsoleGlobalEnvironmentExtensions.cpp
Tests/LibJS/test-js.cpp
Tests/LibWasm/test-wasm.cpp

PrimitiveString is now internally either UTF-8, UTF-16, or both. We no longer convert them to/from ByteString anywhere, nor does VM have a ByteString cache.

LibJS: Remove ByteString internals from PrimitiveString

---

Tests/LibCore/TestLibCoreFileWatcher.cpp

Increase the step timeouts on Linux from 50 to 75 milliseconds, since we're seeing the occasional timeout on CI. For macOS, we should probably be able to execute the tests a bit quicker than 500ms per step.

Tests: Update FileWatcher's test timeouts

---

Libraries/LibGC/Cell.h
Libraries/LibJS/Runtime/Object.h
Libraries/LibJS/Runtime/Shape.h
Libraries/LibWeb/HTML/BrowsingContext.h
Libraries/LibWeb/HTML/Navigable.h
Libraries/LibWeb/Painting/PaintableBox.h
Services/WebContent/WebContentConsoleClient.h

Previously, all `GC::Cell` derived classes were Weakable. Marking only those classes that require this functionality as Weakable allows us to reduce the memory footprint of some frequently used classes.

Everywhere: Mark `GC::Cell` derived classes as Weakable explicitly

---

Libraries/LibJS/Runtime/PrimitiveString.cpp
Libraries/LibJS/Runtime/PrimitiveString.h
Libraries/LibJS/Runtime/Utf16String.cpp
Libraries/LibJS/Runtime/Utf16String.h

By moving the LHS and RHS pointers used by rope strings into a RopeString subclass, we shrink PrimitiveString by 16 bytes. Most strings are not rope strings, so this ends up saving quite a bit of memory.
cc @tcl3

LibWeb: Make RopeString subclass so PrimitiveString can be smaller

---

Libraries/LibJS/Bytecode/ASTCodegen.cpp
Libraries/LibJS/Bytecode/Instruction.h
Libraries/LibJS/Bytecode/Interpreter.cpp
Libraries/LibJS/Bytecode/Op.h
Libraries/LibJS/CMakeLists.txt
Libraries/LibJS/Runtime/AsyncGenerator.cpp
Libraries/LibJS/Runtime/CommonPropertyNames.h
Libraries/LibJS/Runtime/CompletionCell.cpp
Libraries/LibJS/Runtime/CompletionCell.h
Libraries/LibJS/Runtime/GeneratorObject.cpp
Libraries/LibJS/Runtime/GeneratorResult.cpp
Libraries/LibJS/Runtime/GeneratorResult.h

Instead of returning internal generator results as ordinary JS::Objects with properties, we now use GeneratorResult and CompletionCell which both inherit from Cell directly and allow efficient access to state.
1.59x speedup on JetStream3/lazy-collections.js :^)
```
Suite       Test                                Speedup  Old (Mean ± Range)        New (Mean ± Range)
----------  --------------------------------  ---------  ------------------------  ------------------------
JetStream3  js-tokens.js                          1.004  25.770 ± 25.670 … 25.870  25.655 ± 25.640 … 25.670
JetStream3  lazy-collections.js                   1.592  2.810 ± 2.790 … 2.830     1.765 ± 1.760 … 1.770
JetStream3  raytrace-private-class-fields.js      1.012  9.750 ± 9.740 … 9.760     9.635 ± 9.390 … 9.880 …
```

LibJS: Make async functions & generators faster with helper types

---

Libraries/LibWeb/HTML/TraversableNavigable.cpp
Libraries/LibWeb/Painting/BackingStore.h
Libraries/LibWeb/WebDriver/Screenshot.cpp
Services/WebContent/BackingStoreManager.cpp
Services/WebContent/BackingStoreManager.h
Services/WebContent/PageClient.cpp

This is required to make sure rendering thread will keep backing stores alive in case backing stores reallocation happens during rasterization.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4164

LibWeb: Make BackingStore atomic ref-counted

---

Services/WebContent/BackingStoreManager.h
Services/WebContent/PageClient.cpp
Services/WebContent/PageClient.h
Tests/LibWeb/TestConfig.ini

This change allows us to overlap rasterization and rendering work across threads: while the rasterization thread processes frame N, the main thread can simultaneously work on producing the display list for frame N+1.

LibWeb: Allow working on N+1 frame while N is rasterizing

---

Libraries/LibWeb/Layout/InlineFormattingContext.cpp
Libraries/LibWeb/Layout/LineBuilder.cpp
Tests/LibWeb/Layout/expected/block-and-inline/float-intrusions-relative-coordinates.txt
Tests/LibWeb/Layout/input/block-and-inline/float-intrusions-relative-coordinates.html

We were accidentally providing it with absolute Y-coordinates, messing up stacked floating boxes that would otherwise intrude on each other.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4160.

LibWeb: Use relative coordinates for `available_space_for_line()` to determine float intrusions

---

Libraries/LibJS/Runtime/Iterator.h

By reordering the members, we take this from 40 bytes to 32 bytes.

LibJS: Make IteratorRecord slightly smaller

---

.github/actions/setup/action.yml

Many vcpkg dependencies do not work with CMake 4.x, which GitHub Actions now bundles by default. Install the latest 3.x from Kitware for now.

CI: Temporarily install CMake 3.x

---

UI/AppKit/Interface/LadybirdWebView.mm

This seems to have broken in some recent-ish AppKit update. When we add the status label to the view hierarchy / change its visibility state, the `NSApp` is resetting the cursor to the standard cursor. By overriding the `cursorUpdate` method to do nothing, we prevent this from happening.

UI/AppKit: Restore custom cursor shown on link hover

---

Libraries/LibJS/AST.cpp
Libraries/LibJS/AST.h
Libraries/LibJS/Runtime/ClassFieldDefinition.h
Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
Libraries/LibJS/Runtime/Object.cpp

If a class field initializer is just a simple literal, we can skip creating (and calling) a wrapper function for it entirely.
1.44x speedup on JetStream3/raytrace-private-class-fields.js
1.53x speedup on JetStream3/raytrace-public-class-fields.js
```
Suite       Test                                Speedup  Old (Mean ± Range)     New (Mean ± Range)
----------  --------------------------------  ---------  ---------------------  ---------------------
JetStream3  js-tokens.js                          0.988  9.400 ± 9.300 … 9.500  9.510 ± 9.510 … 9.510
JetStream3  lazy-collections.js                   1.018  1.705 ± 1.700 … 1.710  1.675 ± 1.670 … 1.680
JetStream3  raytrace-private-class-fields.js      1.443  8.860 ± 8.840 … 8.880  6.140 ± 6.140 … 6.140
JetStream3 …
```

LibJS: Elide function wrapper for class field literal initializers

---

Libraries/LibWeb/Fetch/FetchMethod.cpp
Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.cpp
Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h
Libraries/LibWeb/Fetch/Response.cpp
Libraries/LibWeb/HTML/HTMLMediaElement.cpp
Libraries/LibWeb/HTML/Navigable.cpp
Libraries/LibWeb/HTML/Navigable.h
Libraries/LibWeb/XHR/XMLHttpRequest.cpp
Services/WebWorker/DedicatedWorkerHost.cpp

This is very clearly a very dangerous API to have, and was causing a crash on Linux as a result of a stack use-after-free when visiting https://www.index.hr/.
Fixes #3901

LibWeb: Do not store network errors as a StringView

---

Libraries/LibWeb/CSS/CSSImportRule.cpp
Libraries/LibWeb/CSS/CSSImportRule.h
Libraries/LibWeb/CSS/CSSImportRule.idl
Libraries/LibWeb/CSS/Parser/Helpers.cpp
Libraries/LibWeb/CSS/Parser/Parser.cpp
Libraries/LibWeb/CSS/Parser/Parser.h
Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
Tests/LibWeb/Ref/input/wpt-import/css/css-cascade/import-conditional-001.html

With this PR, media queries can be included in import at-rules.

LibWeb/CSS: Support media queries in import rules

---

AK/IntrusiveRedBlackTree.h

IntrusiveRedBlackTree relies on a member pointer for accessing the value of a node. On windows member pointers can be of variable lenght, depending on the inheritance structure of the class. This commit casts the 4 byte member pointer, or rather offset to a full pointer type, so that the bit_cast to u8* works, as previously the source was smaller than the destination, which triggers a static_assert().

AK: Modify IntrusiveRedBlackTree for Windows

---

Libraries/LibWeb/HTML/History.cpp
Libraries/LibWeb/HTML/Parser/HTMLParser.cpp

Neither of these touches actual code. One is a FIXME and the other is an optional step we don't implement.

LibWeb/HTML: Update some HTML spec comments

---

Libraries/LibIPC/Connection.cpp
Libraries/LibIPC/Connection.h
Libraries/LibIPC/Decoder.h
Libraries/LibIPC/File.cpp
Libraries/LibIPC/Message.cpp
Libraries/LibIPC/Message.h
Libraries/LibIPC/TransportSocket.cpp
Libraries/LibIPC/TransportSocket.h
Libraries/LibIPC/UnprocessedFileDescriptors.h
Libraries/LibWeb/HTML/MessagePort.h
Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp

It turned out that some web applications want to send fairly large messages to WebWorker through IPC (for example, MapLibre GL sends ~1200KiB), which led to failures (at least on macOS) because buffer size of TransportSocket is limited to 128KiB. This change solves the problem by wrapping messages that exceed socket buffer size into another message that holds wrapped message content in shared memory.

LibWeb: Send IPC messages exceeding socket buffer through shared memory

---

Libraries/LibJS/Bytecode/ASTCodegen.cpp
Libraries/LibJS/Bytecode/Generator.cpp
Libraries/LibJS/Bytecode/Generator.h
Libraries/LibJS/Runtime/Value.cpp
Libraries/LibJS/Runtime/ValueInlines.h

Some easy changes for 1% improvement on JetStream and Octane. The rest look neutral.
```
Suite       Test                                   Speedup  Old (Mean ± Range)           New (Mean ± Range)
----------  -----------------------------------  ---------  ---------------------------  ---------------------------
SunSpider   3d-cube.js                               1      0.010 ± 0.010 … 0.010        0.010 ± 0.010 … 0.010
SunSpider   3d-morph.js                              1      0.020 ± 0.020 … 0.020        0.020 ± 0.020 … 0.020
SunSpider   3d-raytrace.js                           1      0.020 ± 0.020 … 0.020        0.020 ± 0.020 … 0.020
SunSpider   access-binary-trees.js                   1      0.030 ± 0.030 … 0.030        0.030 ± 0.030 … 0.030
SunSpider   access-fannkuch.js …
```

Some LibJS optimizations for JetStream and Octane

---

Libraries/LibGfx/SkiaBackendContext.h
Libraries/LibWeb/HTML/RenderingThread.cpp
Libraries/LibWeb/HTML/RenderingThread.h
Libraries/LibWeb/HTML/TraversableNavigable.cpp
Libraries/LibWeb/HTML/TraversableNavigable.h
Services/WebContent/PageClient.cpp

Skia has a check in debug mode to verify that surface is only used within one thread. Before this change we were violating this by allocating surfaces on the main thread while using and destructing them on the rendering thread.

LibWeb: Move painting surface allocation into rendering thread

---

AK/StringData.h

This was added to be used with `kfree_sized` when we construct a String from a `StringBuilder`. As of 53cac71cec7a71c204d4cd6b09876e6541808d60, it is unused, causing some compilers to raise a warning.
This reduces the size of `StringData` from 24 to 16 bytes.

AK: Remove unused capacity field from StringData

---

.github/actions/setup/action.yml
.github/workflows/lagom-template.yml
.github/workflows/nightly-lagom.yml
.gitignore
AK/Function.h
AK/Swift.h
Libraries/LibGC/CMakeLists.txt
Libraries/LibGC/Cell.h
Libraries/LibGC/Heap+Swift.swift
Libraries/LibJS/Runtime/Shape.h
Libraries/LibWeb/Bindings/PlatformObject.h
Libraries/LibWeb/CMakeLists.txt
Libraries/LibWeb/CSS/StyleInvalidation.h
Libraries/LibWeb/DOM/Element.h
Libraries/LibWeb/HTML/Parser/HTMLParser.h
Libraries/LibWeb/HTML/Parser/SpeculativeHTMLParser.swift
Libraries/LibWeb/Loader/FileRequest.h
Libraries/LibWeb/Painting/Paintable.h
Meta/CMake/FindSwiftTesting.cmake
Meta/CMake/Swift/swift-settings.cmake
Tests/LibGC/CMakeLists.txt
Tests/LibGC/TestGCBindings.swift
Tests/LibGC/TestInterop.cpp
Tests/LibGC/module.modulemap
Tests/LibWeb/CMakeLists.txt

Add the proper annotations for the Cell and Cell::Visitor classes to be
visible in Swift. This lets us remove some OpaquePointer shinangians in
the Swift bindings.
In the meantime, work around two swift issues:
Boolean bitfield fields are improperly imported:  https://github.com/swiftlang/swift/issues/80182
Imported derived classes cannot be cast to Base*: https://github.com/swiftlang/swift/issues/80231
There's another issue I worked around but haven't quite reported yet:
On GC::Cell::Visitor, we have these 4 methods:
```
void visit(Cell* cell);
void visit(Cell const* cell);
void visit(Cell& cell);
void visit(Cell const& cell);
```
The versions that take const& and const* are imported in an ambiguous way, and the compiler can't figure out which one to call when using a GC::Cell reference …

LibWeb+LibGC: Teach Swift about GC::Cell, and start writing a Swift class in LibWeb that is gc-allocated

---

Services/WebContent/ConnectionFromClient.cpp
Services/WebContent/ConnectionFromClient.h
Services/WebContent/main.cpp

This commit removes the unused m_heap member from ConnectionFromClient. This also works around an issue where some cmake version doesn't apply compiler options from within a subdirectory globally.

WebContent: Remove unused private member

---

Libraries/LibWeb/CSS/CSSStyleSheet.cpp
Meta/import-wpt-test.py
Tests/LibWeb/Text/expected/wpt-import/css/mediaqueries/test_media_queries.txt
Tests/LibWeb/Text/input/wpt-import/css/mediaqueries/support/media_queries_iframe.html
Tests/LibWeb/Text/input/wpt-import/css/mediaqueries/test_media_queries.html

This ensures that new media rules are always produce the correct result when evaluated.
This gives us +414 subtests for: http://wpt.live/css/mediaqueries/test_media_queries.html    
The test I've imported is a bit slow - it takes >1 second to run on my machine. I can replace this with my own, less extensive test if it proves problematic on CI.

LibWeb: Invalidate document style when media rules are changed 

---

AK/StringImpl.h
Libraries/LibIPC/Message.h
Libraries/LibJS/AST.h
Libraries/LibJS/Parser.cpp
Libraries/LibMedia/Color/ColorConverter.cpp
Libraries/LibMedia/Color/ColorConverter.h
Libraries/LibMedia/PlaybackManager.h
Libraries/LibTLS/TLSv12.cpp
Libraries/LibTLS/TLSv12.h
Libraries/LibWeb/IndexedDB/Internal/KeyGenerator.h
Libraries/LibWeb/ServiceWorker/Registration.h
Meta/Lagom/CMakeLists.txt
Meta/gn/build/BUILD.gn

This commit removes the -Wno-unusued-private-field flag, thus reenabling the warning. Unused field were either removed or marked [[maybe_unused]] when unsure.

Everywhere: Remove unused private fields

---

Libraries/LibWeb/Layout/FormattingContext.cpp
Libraries/LibWeb/Layout/FormattingContext.h
Libraries/LibWeb/Layout/LayoutState.h
Tests/LibWeb/Layout/expected/block-and-inline/float-inside-margin-auto-container.txt
Tests/LibWeb/Layout/input/block-and-inline/float-inside-margin-auto-container.html

When determining the content/margin box rects within their ancestor's coordinate space, we were returning early if the passed in values already belonged to the requested ancestor. Unfortunately, we had already applied the used values' offset to the rect, which is the offset to the ancestor's ancestor.
This simplifies the logic to always apply the rect offset after checking if we've reached the ancestor. Fixes determining float intrusions inside block elements with `margin: auto` set.
Fixes #4083.

LibWeb: Only apply box offset if the box is not already the ancestor

---

Libraries/LibJS/Tests/builtins/RegExp/RegExp.js
Libraries/LibRegex/RegexMatcher.cpp

Before, If the cache was empty we would try and evict non-existant entries and crash. So we should make sure that we don't saturate the cache with a single parse result.
Heres a way of triggering it from javascript:
```js
RegExp(new Uint8Array(0x40000));
```

LibRegex: Fix crash when parse result exceeds max cache size

---

Libraries/LibJS/Bytecode/Interpreter.cpp
Libraries/LibJS/Tests/regress/async-generator-function-set-completion-type.js

This recovers 38 tests in test262 that regressed in a0bb31f7a0e.
```
Summary:
Diff Tests:
+38 ✅    -38 ❌   
Diff Tests:
test/built-ins/AsyncFromSyncIteratorPrototype/return/iterator-result-poisoned-done.js               ❌ -> ✅
test/built-ins/AsyncFromSyncIteratorPrototype/return/iterator-result-poisoned-value.js              ❌ -> ✅
test/built-ins/AsyncFromSyncIteratorPrototype/return/iterator-result-unwrap-promise.js              ❌ -> ✅
test/built-ins/AsyncFromSyncIteratorPrototype/return/iterator-result.js                             ❌ -> ✅
test/built-ins/AsyncFromSyncIteratorPrototype/return/poisoned-get-return.js                         ❌ -> ✅
test/built-ins/AsyncFromSyncIteratorPrototype/return/poisoned-return.js                             ❌ -> ✅ …
```

Make SetCompletionType bytecode instruction actually set type

---

Libraries/LibJS/Parser.cpp
Libraries/LibJS/Tests/classes/class-static-initializers.js

The following code causes a memory corruption:
```js
function main() {
class C0 {
static {
let a0;
}
}
}
main()
```
This is because the variable `a0` is added to the `last_function_scope` here:
https://github.com/LadybirdBrowser/ladybird/blob/28d5d982ce1e53b78131b8c502333971af891fe7/Libraries/LibJS/Parser.cpp#L357-L373
However, since `last_function_scope` uses `m_function_parameters` to find a valid function scope, it misses the static class initializer and goes all the way up to `main`.
Crash for e73438e82c14c062bf6a8e725305a0fdfc02d336: 
```
=================================================================
==177126==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5060000026f8 at pc 0x7fd3e8092532 bp 0x7ffefdee43e0 sp 0x7ffefdee43d8
WRITE of size 8 at 0x5060000026f8 thread T0 …
```

LibJS: Fix memory corruption when using class static initializers

---

AK/IPv6Address.h
Services/RequestServer/ConnectionFromClient.cpp
Tests/AK/TestIPv6Address.cpp
vcpkg.json

After the upgrade to curl 8.13.0, the `CURLOPT_RESOLVE` option now
supports replacing IPv6 hosts. This allows us to navigate using the IPv6
address directly. Previously, you would see "an unexpected network
error occurred" message when attempting to do so.
Fixes #3596

Meta+RequestServer: Upgrade curl and fix navigating to IPv6 addresses directly
