- Libraries/LibJS/Bytecode/Interpreter.cpp
There is no realm when that call happens, use the same logic as the lines above to create an error from the VM alone.
A crash can be triggered with something like: 
```js
print(0) = 0
```
> LibJS: Remove invalid call to `realm()` on bytecode generator error

- Libraries/LibJS/CyclicModule.cpp
- Libraries/LibJS/Runtime/Completion.h
By specializing this template and using the special empty JS::Value as a marker for the `void` state, we shrink this very common class from 16 bytes to 8 bytes.
This allows bytecode instruction handlers to return their result in a single 64-bit register, allowing tighter code generation.
+ bonus commit adding a missing visit.
> LibJS: Shrink ThrowCompletionOr<void>

- Libraries/LibIPC/Connection.cpp
- Libraries/LibIPC/Connection.h
- Libraries/LibIPC/Message.cpp
- Libraries/LibIPC/Message.h
- Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
This change ensures that instead of immediately deallocating the message buffer after sending, we retain it in an acknowledgement wait queue until an acknowledgement is received from the peer. This is necessary to handle a behavior of the macOS kernel, which may prematurely garbage-collect file descriptors contained within the message buffer before the peer receives them.
The acknowledgement mechanism assumes messages are received in the same order they were sent so, each acknowledgement message simply indicates the count of successfully received messages, specifying how many entries can safely be removed from the acknowledgement wait queue.
> LibIPC+Meta: Keep message buffer alive until acknowledged by peer

- Libraries/LibWebView/URL.cpp
- Tests/LibWebView/TestWebViewURL.cpp
> LibWebView: Highlight `about:` and `data:` URL schemes

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Op.h
- Libraries/LibJS/Bytecode/Operand.h
- Libraries/LibJS/Bytecode/RegexTable.h
- Libraries/LibJS/Bytecode/StringTable.cpp
- Libraries/LibJS/Bytecode/StringTable.h
See individual commits. Solid progress on all benchmark as measured by my M3 MacBook Pro:
```
Suite       Test                                   Speedup  Old (Mean ± Range)           New (Mean ± Range)
----------  -----------------------------------  ---------  ---------------------------  ---------------------------
SunSpider   3d-cube.js                               1      0.010 ± 0.010 … 0.010        0.010 ± 0.010 … 0.010
SunSpider   3d-morph.js                              1      0.020 ± 0.020 … 0.020        0.020 ± 0.020 … 0.020
SunSpider   3d-raytrace.js                           1      0.020 ± 0.020 … 0.020        0.020 ± 0.020 … 0.020
SunSpider   access-binary-trees.js                   1      0.030 ± 0.030 … 0.030        0.030 ± 0.030 … 0.030
SunSpider   access-fannkuch.js …
```
> More work on making LibJS bytecode smaller

- Libraries/LibWeb/DOM/ParentNode.cpp
- Tests/LibWeb/Text/expected/DOM/getElementById-on-unconnected-shadow-tree.txt
- Tests/LibWeb/Text/input/DOM/getElementById-on-unconnected-shadow-tree.html
Fixes bug when we always return null from getElementById() on unconnected roots because id to element cache is only maintained for connected roots.
Fixes broken Perf-Dashboard suite in Speedometer 3.
> LibWeb: Limit usage of getElementById() cache to connected roots

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Runtime/Value.h
See individual commits. Strong results on my M3 MacBook Pro:
```
Suite       Test                                   Speedup  Old (Mean ± Range)           New (Mean ± Range)
----------  -----------------------------------  ---------  ---------------------------  ---------------------------
SunSpider   3d-cube.js                               1      0.010 ± 0.010 … 0.010        0.010 ± 0.010 … 0.010
SunSpider   3d-morph.js                              1      0.020 ± 0.020 … 0.020        0.020 ± 0.020 … 0.020
SunSpider   3d-raytrace.js                           1      0.020 ± 0.020 … 0.020        0.020 ± 0.020 … 0.020
SunSpider   access-binary-trees.js                   1      0.030 ± 0.030 … 0.030        0.030 ± 0.030 … 0.030
SunSpider   access-fannkuch.js                       1      0.020 …
```
> More LibJS interpreter optimizations

- Libraries/LibJS/Bytecode/Operand.h
It seems both aarch64 and x86_64 are extremely sensitive to the use of bitfields here. Unfortunately, aarch64 gains a huge speedup from them while x86_64 sees a very noticeable slowdown.
Since we're talking about 5%+ swings in both directions here, let's go for the best of both worlds and use ifdefs in the Operand memory layout.
> LibJS: Only use bitfields in Bytecode::Operand on aarch64

- AK/String.h
- AK/StringView.cpp
- AK/StringView.h
- Libraries/LibURL/Host.cpp
- Libraries/LibURL/Parser.cpp
- Libraries/LibURL/Pattern/String.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Policy.cpp
- Libraries/LibWeb/Fetch/Body.cpp
- Libraries/LibWebView/CookieJar.cpp
- Tests/AK/TestString.cpp
simdutf provides a vectorized ASCII validator, so let's use that instead of looping over strings manually.
> AK+LibURL+LibWeb: Use simdutf to validate ASCII strings

- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-fonts/parsing/font-face-src-local.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-fonts/test_font_family_parsing.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-fonts/test_font_family_parsing.html
This commit disallows "default" as a font-family name, when the name is not quoted because unquoted names are treated as custom-idents, for which the name "default" is not allowed.
This fixes 430 WPT subtests in the `css/css-fonts` directory.
> LibWeb: Disallow "default" as a `<family-name>` identifier

- Libraries/LibJS/Bytecode/Generator.cpp
- Libraries/LibJS/Tests/regress/super-length-crash.js
We cached the length identifier for GetLength, but not GetLengthWithThis. This caused an `has_value()` verification failure when accessing super.length. Found by Fuzzilli.
> LibJS: Cache length identifier for GetLengthWithThis

- Libraries/LibURL/Parser.cpp
- Libraries/LibURL/Pattern/Pattern.cpp
- Libraries/LibURL/Pattern/PatternParser.cpp
- Tests/LibWeb/Text/expected/wpt-import/urlpattern/urlpattern.any.txt
The remaining test failure is some weird issue with how LibRegexp is being invoked when performing a match, which results in an empty string being used for the regular expression group instead of undefined.
> LibURL/Pattern: Do not trim whitespace interpreting port

- Libraries/LibIPC/Connection.cpp
- Libraries/LibIPC/Connection.h
- Libraries/LibIPC/Message.cpp
- Libraries/LibIPC/TransportSocket.cpp
- Libraries/LibIPC/TransportSocket.h
- Libraries/LibWeb/HTML/MessagePort.cpp
- Libraries/LibWeb/HTML/MessagePort.h
With this change, the responsibility for prepending messages with their size and ensuring the entire message is received before returning it to the caller is moved to TransportSocket. This removes the need to duplicate this logic in both LibIPC and MessagePort.
Another advantage of reducing message granularity at IPC::Transport layer is that it will make it easier to support alternative transport implementations (like Mach ports, which unlike Unix domain sockets are not stream oriented).
> LibIPC: Make TransportSocket responsible for reading entire messages

- Libraries/LibIPC/TransportSocket.cpp
- Libraries/LibIPC/UnprocessedFileDescriptors.h
Fixes the bug when we try to read message payload without checking if we received enough bytes or file descriptors.
> LibIPC: Break from message parsing if whole message payload is not ready

- Libraries/LibWeb/CSS/CSSPropertyRule.cpp
- Libraries/LibWeb/CSS/CSSPropertyRule.h
- Libraries/LibWeb/CSS/Parser/DescriptorParsing.cpp
- Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
Also, make the `initial-value` descriptor a bit more correct.
> LibWeb/CSS: Use new descriptor parsing for `@property`

- Libraries/LibIPC/Connection.cpp
- Libraries/LibIPC/Connection.h
- Libraries/LibIPC/Message.cpp
- Libraries/LibIPC/Message.h
- Libraries/LibIPC/TransportSocket.cpp
- Libraries/LibIPC/TransportSocket.h
- Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
- Tests/LibWeb/Text/expected/Messaging/Messaging-post-channel-over-channel.txt
- Tests/LibWeb/Text/input/Messaging/Messaging-post-channel-over-channel.html
Reimplements c3121c9d at the transport layer, allowing us to solve the same problem once, in a single place, for both the LibIPC connection and MessagePort. This avoids exposing a workaround for a macOS specific Unix domain socket issue to higher abstraction layers.
> LibIPC: Move early fd deallocation workaround to the transport layer

- Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Tests/LibWeb/Text/expected/HTML/HTMLLinkElement-appends-and-removes-from-ShadowRoot-styleSheets.txt
- Tests/LibWeb/Text/input/HTML/HTMLLinkElement-appends-and-removes-from-ShadowRoot-styleSheets.html
We were handling removing the style sheet from the shadow root, but not appending to it. Fixing this also revealed a bug that a removed link element would always try to remove from the document's list, as the root is no longer the shadow root it's in. The fix is to use the passed in old root to remove the style sheet from.
Fixes the cookie banner on https://nos.nl/
Before:
After:
> LibWeb: Append style sheet to ShadowRoot's list if link el is in one

- Libraries/LibWeb/CSS/ComputedProperties.h
This shouldn't be const, and that means the two members don't have to be mutable.
> LibWeb/CSS: Const-correct ComputedProperties::set_computed_font_list()

- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Runtime/ValueInlines.h
- Libraries/LibWeb/Bindings/ImageConstructor.cpp
- Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
- Libraries/LibWeb/Crypto/SubtleCrypto.cpp
- Libraries/LibWeb/DOM/NodeIterator.cpp
- Libraries/LibWeb/DOM/TreeWalker.cpp
- Libraries/LibWeb/WebAssembly/WebAssembly.cpp
- Tests/LibWasm/test-wasm.cpp
See individual commits.
Nice benchmark results from my M3 MacBook Pro:
```
Suite       Test                                   Speedup  Old (Mean ± Range)           New (Mean ± Range)
----------  -----------------------------------  ---------  ---------------------------  ---------------------------
SunSpider   3d-cube.js                               1      0.010 ± 0.010 … 0.010        0.010 ± 0.010 … 0.010
SunSpider   3d-morph.js                              1      0.020 ± 0.020 … 0.020        0.020 ± 0.020 … 0.020
SunSpider   3d-raytrace.js                           1      0.020 ± 0.020 … 0.020        0.020 ± 0.020 … 0.020
SunSpider   access-binary-trees.js                   1      0.030 ± 0.030 … 0.030        0.030 ± 0.030 … 0.030
SunSpider   access-fannkuch.js                       1 …
```
> LibJS: ToInt32 speedups (especially if you have FJCVTZS!)

- Libraries/LibTest/TestSuite.cpp
- Libraries/LibTest/TestSuite.h
```console
Finished 37 tests and 0 benchmarks in 6ms (37ms tests, 0ms benchmarks, 18446744073709551585ms other).
All 37 tests passed.
```
(Im 80-90% sure I didnt wait 584942417.3550721 years for the test suite to finish :3)
> LibTest: Ensure `other` time statistic doesn't underflow

- Libraries/LibIPC/Connection.cpp
- Libraries/LibIPC/Connection.h
- Libraries/LibIPC/Decoder.h
- Libraries/LibIPC/Message.cpp
- Libraries/LibIPC/Message.h
- Libraries/LibIPC/TransportSocket.cpp
- Libraries/LibIPC/TransportSocket.h
- Libraries/LibIPC/UnprocessedFileDescriptors.h
- Libraries/LibWeb/HTML/MessagePort.cpp
- Libraries/LibWeb/HTML/MessagePort.h
- Meta/Lagom/Tools/CodeGenerators/IPCCompiler/main.cpp
…small chunks"
This reverts PR #4304 
This change caused a regression in [this WPT run](<https://wpt.fyi/results/?diff&filter=ADC&run_id=5159713182580736&run_id=5104108925353984>), particularly in the encoding tests.
> Revert "LibIPC: Change TransportSocket to write large messages in…"

- Libraries/LibCore/EventLoopImplementationWindows.cpp
Picture for commit "LibCore: Make single-shot timer objects manually reset on Windows":
<details>
<summary>Some useful logging capabilities</summary>
```cpp
// AK/Format.h
#define RED(str)     "\33[91m" str "\33[0m"
#define GREEN(str)   "\33[92m" str "\33[0m"
#define BLUE(str)    "\33[94m" str "\33[0m"
#define MAGENTA(str) "\33[95m" str "\33[0m"
#define CYAN(str)    "\33[96m" str "\33[0m"
#define DCYAN(str)   "\33[36m" str "\33[0m"
namespace AK { StringView process_name_for_logging(); }
template<typename... Parameters>
void pdbgln(const char* proc_name, CheckedFormatString<Parameters...>&& fmtstr, Parameters const&... parameters)
{
if (proc_name == AK::process_name_for_logging())
dbgln(move(fmtstr), parameters...);
}
```
</details>
> LibCore: Several bug fixes for EventLoopImplementationWindows

- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Libraries/LibWeb/Layout/FormattingContext.cpp
- Tests/LibWeb/Layout/expected/block-and-inline/float-with-negative-margins.txt
- Tests/LibWeb/Layout/input/block-and-inline/float-with-negative-margins.html
Negative margins are processed through the `offset` in layout state, and should not contribute to the margin box' rect's size or position.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4249.
> LibWeb: Fix handling floats with negative margins

- Tests/LibWeb/Text/expected/Messaging/Messaging-post-channel-over-channel.txt
- Tests/LibWeb/Text/input/Messaging/Messaging-post-channel-over-channel.html
When a message is posted to multiple ports at once, the order in which the callbacks for these messages are invoked is non-deterministic. To account for this, the test has been rewritten to accumulate logs for each port separately, and then print them grouped by port.
> Tests: Rearrange log order in Messaging-post-channel-over-channel.html

- Libraries/LibWeb/WebDriver/ExecuteScript.cpp
This resolves the remaining FIXMEs surrounding our use of promises in our WebDriver script executor. We don't quite pass everything related to promises yet, due to WPT using `await` in a couple of tests, which isn't handled by the spec yet.
`/webdriver/tests/classic/execute_script`
Before:
```
web-platform-test
~~~~~~~~~~~~~~~~~
Ran 134 checks (124 subtests, 10 tests)
Expected results: 121
Unexpected results: 13
test: 1 (1 timeout)
subtest: 12 (12 fail)
```
After:
```
web-platform-test
~~~~~~~~~~~~~~~~~
Ran 144 checks (134 subtests, 10 tests)
Expected results: 130
Unexpected results: 14
subtest: 14 (14 fail)
```
> LibWeb/WebDriver: A few promise-related fixes

- Libraries/LibUnicode/Segmenter.cpp
- Tests/LibUnicode/TestSegmenter.cpp
When the cursor was positioned at the end of text, attempting to move it left (using the left arrow key) would fail because align_boundary() was rejecting the end-of-text position as a valid boundary.
> LibUnicode: avoid rejecting end-of-text position as a valid boundary

- Libraries/LibWeb/DOM/Element.idl
Partly addresses #4302 - it removes the spam, but doesn't make panning actually work.
> LibWeb/DOM: Stub out Element pointerevents methods

- Libraries/LibWeb/CMakeLists.txt
- Libraries/LibWeb/CSS/StyleValues/CursorStyleValue.cpp
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/HTML/RenderingThread.cpp
- Libraries/LibWeb/HTML/RenderingThread.h
- Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Libraries/LibWeb/Painting/Command.h
- Libraries/LibWeb/Painting/DisplayList.cpp
- Libraries/LibWeb/Painting/DisplayList.h
- Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.h
- Libraries/LibWeb/Painting/NavigableContainerViewportPaintable.cpp
- Libraries/LibWeb/Painting/SVGMaskable.cpp
- Libraries/LibWeb/Painting/ScrollFrame.h
- Libraries/LibWeb/Painting/ScrollState.cpp
- Libraries/LibWeb/Painting/ScrollState.h
- Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
With this change we save a copy of of scroll state at the time of recording a display list, instead of actual ScrollState pointer that could be modifed by the main thread while display list is beings rasterized on the rendering thread, which leads to a frame painted with inconsistent scroll state.
> LibWeb: Save ScrollState snapshot in DisplayList to avoid race condition

- Meta/Lagom/BuildFuzzers.sh
This near enough matches what CI does to build fuzzers, with the differences being the explicit -GNinja and setting CMAKE_OSX_SYSROOT, as CMake 4 no longer does that for us.
> Meta: Use presets, chosen clang and explicit sysroot to build fuzzers

- Libraries/LibWeb/DOM/Element.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-box/inheritance.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-box/inheritance.html
Before this change, we'd skip storing the new ComputedProperties in Element::recompute_style() if there was no invalidation needed.
This caused us to lose the information about which properties are inherited and/or important (which is also carried by ComputedProperties, but doesn't affect invalidation).
Consequently, we'd then fail to recompute inherited styles, since that mechanism depends on this data.
The fix is simply to always store the new ComputedProperties.
> LibWeb: Always store ComputedProperties, even if no invalidations

- Toolchain/BuildVcpkg.py
- vcpkg.json
Includes a fix for vcpkg git commands not working in git versions below 2.35.
I'm not sure what the minimum version of git for ladybird is, but for vcpkg 2.7.4 should work again. For ladybird I've tested 2.34.1.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4331.
More info in #4333.
> Meta: Update vcpkg to latest master

- Libraries/LibWeb/DOM/EventTarget.cpp
EventTarget::dispatch_event, per comments, does ad-hoc solution for UA, and I don't know why it checks if `this` is window or `element`, but web platform tests would fail, because `this` would actually be a `Document` type.
The web platform test that would fail is for one of the `/fullscreen/api` tests.
> LibWeb: Set user activation for pointerdown/up

- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-stepMismatch.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/input-stepdown-weekmonth.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/input-stepdown.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/input-stepup-weekmonth.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/input-stepup.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/month.txt
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/constraints/form-validation-validity-stepMismatch.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/input-stepdown-weekmonth.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/input-stepdown.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/input-stepup-weekmonth.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/input-stepup.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/month.html
This change adds “default step” and “step scale factor” handling for all remaining `HTMLInputElement` input types for which the spec defines such and that we didn’t yet have handling for.
> LibWeb: Handle “default step”/“step scale factor” for more input types

- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
- Libraries/LibWeb/DOM/Element.idl
For real this time.
This makes panning the KendoReact map widget actually work: https://www.telerik.com/kendo-react-ui/components/map
Fixes #4302
> LibWeb/DOM: Actually stub out pointer-capture API

- Libraries/LibWeb/Streams/AbstractOperations.cpp
- Tests/LibWeb/Text/expected/wpt-import/streams/piping/then-interception.any.txt
- Tests/LibWeb/Text/input/wpt-import/streams/piping/then-interception.any.html
- Tests/LibWeb/Text/input/wpt-import/streams/piping/then-interception.any.js
The spec states:
Public API must not be used: while reading or writing, or performing
any of the operations below, the JavaScript-modifiable reader,
writer, and stream APIs (i.e. methods on the appropriate prototypes)
must not be used. Instead, the streams must be manipulated directly.
This migrates the default request request we were using to a custom read
request which does not involve extra promises.
I'm not sure about an analogous change with the way we write chunks to
the receiving end. There isn't a "WriteRequest" utility to be used here,
and no matter what AO we use, promises will be involved. Our current
implementation at least does not seem to affect any tests.
> LibWeb: Implement `ReadableStreamPipeTo` reads with less observability

- .github/actions/setup/action.yml
- .github/workflows/js-artifacts.yml
- .github/workflows/js-benchmarks.yml
We are running a self-hosted Mac mini runner that can pick up the macOS arm64 build of our JS repl and run that against [js-benchmarks](https://github.com/LadybirdBrowser/js-benchmarks/). This changes our CI so the `js-benchmarks.yml` workflow now also creates jobs based on a matrix, and adds macOS as a target.
> CI: Run js-benchmarks on macOS

- Libraries/LibWeb/HTML/ImageBitmap.cpp
- Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Libraries/LibWeb/HTML/StructuredSerialize.h
Previously we were using 0 for both unsupported type and MessagePort, which led to crashing on attempt to decode unsupported transfer type as MessagePort.
Fixes crashing on
https://docs.mapbox.com/mapbox-gl-js/clip-layer-building-demo.html
> LibWeb: Reserve zero for not supported transfer type

- Libraries/LibWeb/DOM/Document.cpp
- Tests/LibWeb/Text/expected/IntersectionObserver/box-without-layout-node-should-not-intersect.txt
- Tests/LibWeb/Text/input/IntersectionObserver/box-without-layout-node-should-not-intersect.html
Check if box has associated layout node is not mentioned in the spec, but it is required to match behavior of other browsers that do not invoke intersection observer steps for boxes without layout node.
> LibWeb: Ignore boxes without layout node in intersection observer steps

- AK/DisjointChunks.h
- Libraries/LibJS/Runtime/RegExpPrototype.cpp
- Libraries/LibRegex/RegexByteCode.cpp
- Libraries/LibRegex/RegexByteCode.h
- Libraries/LibRegex/RegexMatch.h
- Tests/LibRegex/Regex.cpp
Two main things here:
- First, get rid of non-trivial members in `regex::Match` so we can move it around with `memcpy()`
- Then, take advantage of the fact that bytecode is flattened by the time we're executing it, and don't create expensive `DisjointSpans` in `Opcode_Compare` execution.
Solid progression on RegExp-using benchmarks:
```
Suite       Test                              Speedup  Old (Mean ± Range)     New (Mean ± Range)
----------  ------------------------------  ---------  ---------------------  ---------------------
Octane      regexp.js                           1.075  17.085 ± 17.070 … 17.100  15.900 ± 15.840 … 15.960
RegExp      speedometer-jquery-regexp-1.js      1.094  2.795 ± 2.780 … 2.810     2.555 ± 2.550 … 2.560
```
> LibRegex: Some things to go faster!

- Libraries/LibWeb/Streams/AbstractOperations.cpp
- Tests/LibWeb/Text/expected/wpt-import/streams/writable-streams/close.any.txt
- Tests/LibWeb/Text/input/wpt-import/streams/writable-streams/close.any.html
- Tests/LibWeb/Text/input/wpt-import/streams/writable-streams/close.any.js
This widens the assertion from only checking if the WritableStream's state is Errored or Erroring to asserting that the WritableStream is not in a Writable state.
Aligns us with spec change: https://github.com/whatwg/streams/pull/1342
> LibWeb: Widen assertion to avoid accidentally writing to a closed stream

- Libraries/LibTLS/TLSv12.cpp
If we don't do this, then we endlessly spin trying to read data which ends up in a deadlock.
The description for SSL_ERROR_ZERO_RETURN states:
> The TLS/SSL connection has been closed. If the protocol version is SSL
> 3.0 or TLS 1.0, this result code is returned only if a closure alert
> has occurred in the protocol, i.e., if the connection has been closed
> cleanly. Note that in this case SSL_ERROR_ZERO_RETURN does not
> necessarily indicate that the underlying transport has been closed.
> LibTLS: Call `close()` when we receive `SSL_ERROR_ZERO_RETURN`

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Meta/check-idl-files.py
- Tests/LibWeb/Text/expected/wpt-import/streams/idlharness.any.txt
- Tests/LibWeb/Text/input/wpt-import/interfaces/dom.idl
- Tests/LibWeb/Text/input/wpt-import/interfaces/streams.idl
- Tests/LibWeb/Text/input/wpt-import/resources/WebIDLParser.js
- Tests/LibWeb/Text/input/wpt-import/resources/idlharness.js
- Tests/LibWeb/Text/input/wpt-import/streams/idlharness.any.html
- Tests/LibWeb/Text/input/wpt-import/streams/idlharness.any.js
If an attribute's getter were to throw an exception, we must instead return a rejected promise. We already supported this behavior for functions.
> LibWeb: Do not throw exceptions from Promise-type attributes

- Libraries/LibWeb/Streams/AbstractOperations.cpp
- Tests/LibWeb/Text/expected/wpt-import/streams/piping/general-addition.any.txt
- Tests/LibWeb/Text/input/wpt-import/streams/piping/general-addition.any.html
- Tests/LibWeb/Text/input/wpt-import/streams/piping/general-addition.any.js
I don't quite see what spec text requires this, but it is explicitly checked by WPT. We used to pass this test, but that regressed after commit https://github.com/LadybirdBrowser/ladybird/commit/3c6010c663dddb78aa84b85e7a27307c4841a9dd.
> LibWeb: Perform writes during ReadableStreamPipeTo asynchronously

- Libraries/LibWeb/Streams/AbstractOperations.cpp
- Tests/LibWeb/Text/expected/wpt-import/streams/readable-byte-streams/general.any.txt
- Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/general.any.html
- Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/general.any.js
- Tests/LibWeb/Text/input/wpt-import/streams/resources/rs-utils.js
This was causing us to hang on some BYOB tests. Fixes ~80 WPT tests.
`/streams/readable-byte-streams` before:
```
web-platform-test
~~~~~~~~~~~~~~~~~
Ran 594 checks (494 subtests, 100 tests)
Expected results: 434
Unexpected results: 160
test: 82 (70 error, 12 timeout)
subtest: 78 (2 fail, 74 notrun, 2 timeout)
```
after:
```
web-platform-test
~~~~~~~~~~~~~~~~~
Ran 594 checks (494 subtests, 100 tests)
Expected results: 512
Unexpected results: 82
test: 80 (70 error, 10 timeout)
subtest: 2 (2 fail)
```
> LibWeb: Unindent looping over a BYOB reader's pull-into requests

- Libraries/LibWeb/CSS/CSSImportRule.cpp
- Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Libraries/LibWeb/CSS/Parser/Helpers.cpp
- Libraries/LibWeb/CSS/Parser/Parser.cpp
- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/CSS/StyleSheetList.cpp
- Libraries/LibWeb/CSS/StyleSheetList.h
- Libraries/LibWeb/DOM/StyleElementUtils.cpp
- Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Tests/LibWeb/Layout/data/import-a.css
- Tests/LibWeb/Layout/data/import-b.css
- Tests/LibWeb/Layout/expected/import-from-linked-style-sheet.txt
- Tests/LibWeb/Layout/input/import-from-linked-style-sheet.html
Fixes #4334.
The bug was caused by not passing the URL to `parse_css_stylesheet()`. But I've then gone on to make that mistake harder to make by moving style sheet parsing into `StyleSheetList::create_a_css_style_sheet()`. The spec isn't clear but I think this is more correct too.
> LibWeb: Set location for linked stylesheets during parsing

- Libraries/LibWeb/CSS/CSSImportRule.cpp
- Libraries/LibWeb/CSS/CSSStyleRule.cpp
- Libraries/LibWeb/CSS/CSSStyleRule.h
- Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Libraries/LibWeb/CSS/CSSStyleSheet.h
- Libraries/LibWeb/CSS/CSSStyleValue.h
- Libraries/LibWeb/CSS/Fetch.cpp
- Libraries/LibWeb/CSS/Fetch.h
- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
- Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
- Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp
- Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.h
- Libraries/LibWeb/CSS/StyleValues/StyleValueList.cpp
- Libraries/LibWeb/CSS/StyleValues/StyleValueList.h
- Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Libraries/LibWeb/HTML/HTMLObjectElement.cpp
- Libraries/LibWeb/SVG/SVGUseElement.cpp
- Tests/LibWeb/Ref/data/checkerboard-background.css
- Tests/LibWeb/Ref/expected/css/images-load-relative-to-style-sheet-ref.html
- Tests/LibWeb/Ref/input/css/images-load-relative-to-imported-style-sheet.html
- Tests/LibWeb/Ref/input/css/images-load-relative-to-linked-style-sheet.html
Part 2 of the CSS `<url>` saga.
We stop absolutizing the URLs for ImageStyleValue during parsing, and instead make use of CSS::URL and the spec's "fetch an external image for a stylesheet" algorithm. I've come across (and reported) a couple of issues in the spec involving these fetch algorithms, and so the implementation is a bit ad-hoc, but I've tried to keep it as close as possible.
I'm not seeing any regressions, but I added a test for one hole in our coverage so there could be others.
> LibWeb/CSS: Fetch ImageStyleValues closer to spec

- .github/workflows/js-benchmarks.yml
Chaining workflows does not cause the subsequently spawned workflow runs to use the same event, but rather it uses the latest head SHA based on the branch it runs on. This would cause the JS benchmarks jobs to not be able to find artifacts (if a new JS repl workflow was started before the previous one could finish) and/or assign the wrong commit SHA to the benchmark results.
Since `github.event` contains information about the original workflow run that spawned the JS benchmarks jobs, we can take the commit SHA from there and use it to download the correct artifact.
> CI: Use workflow run's event commit SHA for JS benchmarks

- Libraries/LibWeb/CSS/Parser/DescriptorParsing.cpp
- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-fonts/parsing/font-face-src-format.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-fonts/parsing/font-face-src-list.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-fonts/parsing/font-face-src-tech.txt
Details in commits. This gets us 30 WPT subtests for our in-tree tests, and fixes the menubar icons on https://mdn-bcd-collector.gooborg.com/
> LibWeb/CSS: Parse font sources more correctly

- Libraries/LibWeb/Streams/AbstractOperations.cpp
- Tests/LibWeb/Text/expected/wpt-import/streams/readable-streams/global.txt
- Tests/LibWeb/Text/input/wpt-import/streams/readable-streams/global.html
There is an open issue to clarify exactly what realm is to be used when creating promises. There are surely many more places we will need to update to use the correct realm (which will be the realm of `this`'s relevant global object).
> LibWeb: Use the correct realm when initializing streams

- Libraries/LibWeb/Streams/AbstractOperations.cpp
- Libraries/LibWeb/WebIDL/AbstractOperations.cpp
- Libraries/LibWeb/WebIDL/AbstractOperations.h
- Tests/LibWeb/Text/expected/wpt-import/streams/readable-streams/tee.any.txt
- Tests/LibWeb/Text/input/wpt-import/streams/readable-streams/tee.any.html
- Tests/LibWeb/Text/input/wpt-import/streams/readable-streams/tee.any.js
In Streams, we were invoking callbacks that return a `JS::Promise` and turning them into a `WebIDL::Promise` resolved with the `JS::Promise` as its value. The problem here is when the `JS::Promise` was actually rejected - we are meant to have a rejected `WebIDL::Promise` as a result.
As it turns out, we can simply add an alternative `WebIDL::invoke_promise_callback` to handle this nuance. It will return a promise to us in the correct state so that Streams doesn't have to worry about it.
> LibWeb: Add a promise-based alternative to `WebIDL::invoke_callback` and use it in streams

- Libraries/LibWeb/Bindings/MainThreadVM.cpp
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/ElementFactory.cpp
- Libraries/LibWeb/DOM/EventDispatcher.cpp
- Libraries/LibWeb/DOM/EventTarget.cpp
- Libraries/LibWeb/DOM/NodeIterator.cpp
- Libraries/LibWeb/DOM/TreeWalker.cpp
- Libraries/LibWeb/HTML/DataTransferItem.cpp
- Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
- Libraries/LibWeb/HTML/Navigation.cpp
- Libraries/LibWeb/HTML/UniversalGlobalScope.cpp
- Libraries/LibWeb/HTML/Window.cpp
- Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Libraries/LibWeb/ResizeObserver/ResizeObserver.cpp
- Libraries/LibWeb/Streams/AbstractOperations.cpp
- Libraries/LibWeb/Streams/TransformStream.cpp
- Libraries/LibWeb/WebAudio/BaseAudioContext.cpp
- Libraries/LibWeb/WebIDL/AbstractOperations.cpp
- Libraries/LibWeb/WebIDL/AbstractOperations.h
These callbacks are evaluated synchronously via JS::Call. We do not need to construct an expensive `RootVector` container just to immediately invoke the callbacks.
Stylistically, this also helps indicate where the actual arguments start at the call sites, by wrapping the arguments in braces.
Noticed this while working on #4372.
> LibWeb: Do not create a RootVector to invoke IDL callbacks

- Libraries/LibWeb/Layout/TreeBuilder.cpp
- Tests/LibWeb/Layout/expected/layout-tree-update/dialog-backdrop-update.txt
- Tests/LibWeb/Layout/input/layout-tree-update/dialog-backdrop-update.html
> LibWeb: Only create backdrop when originating element is invalidated

- Libraries/LibWeb/Streams/AbstractOperations.cpp
- Tests/LibWeb/Text/expected/wpt-import/streams/transform-streams/cancel.any.txt
- Tests/LibWeb/Text/input/wpt-import/streams/transform-streams/cancel.any.html
- Tests/LibWeb/Text/input/wpt-import/streams/transform-streams/cancel.any.js
This was actually an older change to the Streams spec that we missed when we implemented TransformStreams. This fixes a crash in the imported WPT tests.
See: https://github.com/whatwg/streams/commit/007d729
> LibWeb: Update spec steps for closing TransformStreams

- Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Libraries/LibWeb/CSS/Parser/Parser.cpp
- Libraries/LibWeb/CSS/Parser/Parser.h
- Tests/LibWeb/Text/expected/wpt-import/css/cssom/CSSStyleSheet-constructable-baseURL.txt
- Tests/LibWeb/Text/input/wpt-import/css/cssom/CSSStyleSheet-constructable-baseURL.html
Previously, a crash would occur when fetching an image for a constructed stylesheet, which was not associated with any document.
This fixes a regression in: https://wpt.live/css/cssom/CSSStyleSheet-constructable-baseURL.html
> LibWeb: Don't construct stylesheet when modifying CSSStyleSheet rules

- Libraries/LibWebView/Autocomplete.cpp
- Libraries/LibWebView/Autocomplete.h
- Libraries/LibWebView/CMakeLists.txt
For example, Google uses ISO-8859-1 encoding. This patch allows us to decode such responses, falling back to UTF-8 if a Content-Type was not specified or could not be parsed. We should also now handle if decoding fails, rather than crashing inside `JsonParser`.
Fixes #4380.
> LibWebView: Respect autocomplete response Content-Encoding headers

- Documentation/DevTools.md
They have fixed the exception mentioned here, but the script still has trouble displaying all live-captured packets.
> Documentation: Remove now-obsolete patch from Servo's DevTools parser

- Libraries/LibWeb/HTML/MessagePort.cpp
- Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Libraries/LibWeb/HTML/StructuredSerialize.h
- Libraries/LibWeb/HTML/UniversalGlobalScope.cpp
- Libraries/LibWeb/HTML/Window.cpp
- Tests/LibWeb/Text/expected/wpt-import/streams/readable-byte-streams/enqueue-with-detached-buffer.any.txt
- Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/enqueue-with-detached-buffer.any.html
- Tests/LibWeb/Text/input/wpt-import/streams/readable-byte-streams/enqueue-with-detached-buffer.any.js
This is important, for example, to detach transferred array buffers.
~~Draft for now because I can't import an affected WPT test while wpt.live is down~~
> LibWeb: Use (de)serialization with transfer AOs for structured cloning

- Libraries/LibWeb/CSS/ComputedProperties.h
- Libraries/LibWeb/CSS/PseudoClassBitmap.h
- Libraries/LibWeb/CSS/Selector.cpp
- Libraries/LibWeb/CSS/Selector.h
- Libraries/LibWeb/CSS/SelectorEngine.cpp
- Libraries/LibWeb/CSS/SelectorEngine.h
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/CSS/StyleComputer.h
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
- Libraries/LibWeb/DOM/Node.h
- Libraries/LibWeb/HTML/HTMLDialogElement.cpp
- Libraries/LibWeb/HTML/HTMLDialogElement.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoClass.cpp
The main theme here is taking the clever tricks we did for `:hover` and generalizing them for `:active`, `:focus`, `:focus-within`, `:focus-visible`, `:target`, and `:target-within` as well.
This gives us roughly a 5% speed-up on Speedometer 3.
It also exposed some under-invalidation in `HTMLDialogElement`, which we take care of.
> Invalidate less style due to pseudo-class selectors on Speedometer 3

- Libraries/LibWeb/DOM/Element.cpp
- Tests/LibWeb/Crash/HTML/no-list-owner-custom-element.html
Fixes a crash when running Speedometer 3.0 as reduced in the included test case.
> LibWeb/HTML: Handle no parent element for Element::list_owner

- AK/COWVector.h
- Libraries/LibJS/Runtime/RegExpObject.h
- Libraries/LibJS/Runtime/RegExpPrototype.cpp
- Libraries/LibRegex/RegexByteCode.cpp
- Libraries/LibRegex/RegexDebug.h
- Libraries/LibRegex/RegexDefs.h
- Libraries/LibRegex/RegexMatch.h
- Libraries/LibRegex/RegexMatcher.cpp
- Libraries/LibRegex/RegexMatcher.h
- Libraries/LibRegex/RegexOptimizer.cpp
- Libraries/LibRegex/RegexOptions.h
- Libraries/LibRegex/RegexParser.cpp
- Libraries/LibRegex/RegexParser.h
- Libraries/LibURL/Pattern/Component.cpp
- Tests/LibRegex/Regex.cpp
The main workhorse of this nice PR is pulling out the first compare to apply outside the VM, this avoid setting up a bunch of state and allows the matcher to (relatively) quickly seek to a point where the pattern would at least have a chance of succeeding; this leads to a ~20% perf improvement on that one bad regex Andreas has been complaining about (but not in general, that's not measured here)
(p.s. my first PR from inside ladybird, be nice:)
> LibRegex: One more optimization for the performance gods

- Libraries/LibGC/RootVector.cpp
- Libraries/LibGC/RootVector.h
Rule of 5 - we were missing a move-assignment operator, thus all move assignments resulted in a copy.
> LibGC: Allow move-assigning `RootVector` instances

- Libraries/LibWeb/Encoding/TextEncoder.cpp
- Tests/LibWeb/Text/expected/wpt-import/encoding/encodeInto.any.txt
- Tests/LibWeb/Text/input/wpt-import/encoding/encodeInto.any.html
- Tests/LibWeb/Text/input/wpt-import/encoding/encodeInto.any.js
This handles the case where data is encoded into a detached buffer.
Some considerations:
1. The same bug might still exist at other places. Would it be better to let the internal buffer getter return an empty buffer instead of crashing?
2. I added a missing spec warning relating to shared buffers. Should I also add a fixme so that the implication of the warning is checked again in future?
> LibWeb: Prevent crash when encoding into detached buffer

- Libraries/LibCore/Proxy.h
- Libraries/LibURL/Parser.cpp
- Libraries/LibURL/URL.cpp
- Libraries/LibURL/URL.h
- Libraries/LibWeb/CSS/Parser/Parser.cpp
- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Libraries/LibWeb/Loader/LoadRequest.h
- Libraries/LibWeb/Loader/Resource.cpp
- Libraries/LibWeb/Loader/Resource.h
- Libraries/LibWeb/Loader/ResourceLoader.cpp
- Libraries/LibWebView/CookieJar.cpp
- Libraries/LibWebView/URL.cpp
- Tests/LibURL/TestURL.cpp
- UI/AppKit/Interface/Event.mm
- UI/Headless/Test.cpp
- UI/Headless/main.cpp
- Utilities/xml.cpp
This finally removes the URL validity state as we should never have a URL which is in an invalid state (which should be enforced by the URL parser).
> LibURL: Remove URL's valid state 

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/DOM/Element.h
- Libraries/LibWeb/DOM/StyleElementUtils.cpp
- Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Libraries/LibWeb/HTML/HTMLLinkElement.h
- Libraries/LibWeb/HTML/HTMLStyleElement.cpp
- Libraries/LibWeb/HTML/HTMLStyleElement.h
- Tests/LibWeb/Text/input/link-re-enable-crash.html
The basic idea is that style sheets can block script execution under some circumstances. With this commit, we now handle the simplest cases where a parser-inserted link element gets to download its style sheet before script execution continues.
This improves performance on Speedometer 3 where JavaScript APIs that depend on layout results (like Element.scrollIntoView()) would get called too early (before the relevant CSS was downloaded), and so we'd perform premature layout work. This work then had to be redone after downloading the CSS anyway, wasting time.
Note that our Text/input/link-re-enable-crash.html test had to be tweaked after these changes, since it relied on the old, incorrect, behavior where scripts would run before downloading CSS.
> LibWeb: Implement more of the "script-blocking style sheet" mechanism

- Libraries/LibRequests/NetworkError.h
- Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Services/RequestServer/ConnectionFromClient.cpp
This fixes the following WPT tests:
https://wpt.fyi/results/fetch/content-encoding/br/bad-br-body.https.any.html?product=ladybird
https://wpt.fyi/results/fetch/content-encoding/gzip/bad-gzip-body.any.html?product=ladybird
https://wpt.fyi/results/fetch/content-encoding/zstd/bad-zstd-body.https.any.html?product=ladybird
which unfortunately cannot be imported because they depend on a python web server.
Fixes #2927
> LibWeb+RequestServer: Handle WPT improperly closing TLS connections and handle errored responses better

- Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
This reverts commit 4d0301d2d2abae9b8e665fd49023eb4054d34eb7.
This caused /html/dom/reflection-embedded.html to massively regress.
> Revert "LibWeb: Mark body stream with a TypeError if the request failed"

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/wpt-import/webidl/ecmascript-binding/global-object-implicit-this-value.any.txt
- Tests/LibWeb/Text/input/wpt-import/webidl/ecmascript-binding/global-object-implicit-this-value.any.html
- Tests/LibWeb/Text/input/wpt-import/webidl/ecmascript-binding/global-object-implicit-this-value.any.js
We were missing the step to use realm's global object if thisValue was nullish. This is very trivial to fix, as `impl_this` already handles everything as it should, allowing us to also remove the special casing for WindowProxy.
> LibWeb/Bindings: Use realm's globalObject as thisValue if nullish

- Libraries/LibWeb/Layout/FlexFormattingContext.cpp
- Libraries/LibWeb/Layout/FlexFormattingContext.h
- Tests/LibWeb/Layout/expected/flex/flex-optimization-cases.txt
- Tests/LibWeb/Layout/input/flex/flex-optimization-cases.html
There's a specific (and thankfully very common!) scenario where we can actually skip calculating the automatic minimum size for flex items.
In single-line (no wrapping) flex containers, if the sum of all item flex base sizes is <= the flex container's main size, we know that none of the items will be shrunk by the layout algorithm.
And so for any flex item with definite main size AND automatic minimum main size, we can treat the automatic minimum size as 0.
> LibWeb: Avoid computing automatic minimum size for some flex items

- Libraries/LibWeb/HTML/BrowsingContext.cpp
- Libraries/LibWeb/HTML/Navigable.cpp
- Libraries/LibWeb/HTML/Scripting/Environments.cpp
- Libraries/LibWeb/HTML/Scripting/Environments.h
- Libraries/LibWeb/HTML/Scripting/SerializedEnvironmentSettingsObject.cpp
- Libraries/LibWeb/HTML/Scripting/SerializedEnvironmentSettingsObject.h
This is explicitly set to null for Workers.
Continues upstreaming some minor changes picked up slowly working toward implementing the ServiceWorker worker process.
> LibWeb/HTML: Make environments top level creation URL nullable

- Libraries/LibWeb/Painting/Command.h
- Libraries/LibWeb/Painting/DisplayList.cpp
- Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.h
- Libraries/LibWeb/Painting/PaintableBox.cpp
- Libraries/LibWeb/Painting/PaintableBox.h
- UI/Headless/Application.cpp
* Enlarge the scrollbar a bit upon hover. I was finding myself missing the scrollbar quite a bit when I clicked.
* Draw the scrollbar thumb outline a bit smoother.
* Draw a scrollbar gutter upon hover.
* Allow clicking in the gutter to scroll to that position.
https://github.com/user-attachments/assets/f949816e-039f-4242-b987-561b3281ca94
> LibWeb: Some scrollbar UX improvements

- Libraries/LibJS/Forward.h
- Libraries/LibJS/Runtime/Agent.cpp
- Libraries/LibJS/Runtime/Agent.h
- Libraries/LibJS/Runtime/AtomicsObject.cpp
- Libraries/LibJS/Runtime/Completion.cpp
- Libraries/LibJS/Runtime/VM.cpp
- Libraries/LibJS/Runtime/VM.h
- Libraries/LibWeb/Bindings/MainThreadVM.cpp
- Libraries/LibWeb/Bindings/MainThreadVM.h
- Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Libraries/LibWeb/HTML/Scripting/Agent.cpp
- Libraries/LibWeb/HTML/Scripting/Agent.h
- Tests/LibJS/test262-runner.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/webappapis/scripting/processing-model-2/integration-with-the-javascript-agent-formalism/requires-failure.https.any.txt
- Tests/LibWeb/Text/input/wpt-import/html/webappapis/scripting/processing-model-2/integration-with-the-javascript-agent-formalism/requires-failure.https.any.html
- Tests/LibWeb/Text/input/wpt-import/html/webappapis/scripting/processing-model-2/integration-with-the-javascript-agent-formalism/requires-failure.https.any.js
similar-origin window agents have the [[CanBlock]] flag set to false. Achieve this by hooking up JS's concept with an agent to HTML::Agent. For now, this is only hooked up to the similar-origin window agent case but should be extended to the other agent types in the future.
(aim is some more progress towards service workers)
> LibJS+LibWeb: Set [[CanBlock]] false to Agent for window agent

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Bytecode/Generator.cpp
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Parser.h
Local variables are faster to access and if all catch parameters are locals we can skip lexical environment allocation.
Small improvement in JetStream:
```
Suite       Test                Speedup  Old (Mean ± Range)           New (Mean ± Range)
----------  ----------------  ---------  ---------------------------  ---------------------------
JetStream   bigfib.cpp.js         0.996  6.905 ± 6.900 … 6.910        6.930 ± 6.920 … 6.940
JetStream   cdjs.js               1.01   6.450 ± 6.440 … 6.460        6.385 ± 6.360 … 6.410
JetStream   container.cpp.js      1.002  33.045 ± 32.960 … 33.130     32.990 ± 32.770 … 33.210
JetStream   dry.c.js              1.006  18.645 ± 18.290 … 19.000     18.530 ± 18.090 … 18.970
JetStream   float-mm.c.js         1.006  17.530 ± 17.450 … 17.610     17.425 ± …
```
> LibJS: Allow using local variable for catch parameters

- Toolchain/BuildVcpkg.py
Just so we only have to update one location when we update the baseline.
> Meta: Read vcpkg baseline revision from vcpkg.json

- AK/Concepts.h
- AK/FlyString.h
- AK/Noncopyable.h
- AK/Optional.h
- AK/StdLibExtraDetails.h
- AK/StdLibExtras.h
- AK/String.h
- AK/StringBase.h
- Libraries/LibJS/Runtime/Completion.h
- Libraries/LibJS/Runtime/Value.h
- Libraries/LibTest/Macros.h
- Libraries/LibWeb/Painting/PaintableBox.cpp
- Tests/AK/TestOptional.cpp
- Tests/ClangPlugins/CMakeLists.txt
Attempt 1: https://github.com/LadybirdBrowser/ladybird/pull/2455
Related SerenityOS PR: https://github.com/SerenityOS/serenity/pull/25740
> AK: Allow `Optional<T>` to be used in constant expressions

- AK/BigIntBase.h
- AK/Platform.h
This reverts commit 9d4dfc1061d9a1ac95654e4d5349d556aad71c5d.
As far as I know, we do not support apple clang 14 due to Swift interop requirements. If we still do, let's keep this PR around until we don't :)
> Revert "AK: Work around Apple Clang `__builtin_subc` codegen issue"

- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-color/parsing/color-valid-color-mix-function.txt
This amounts to replacing the "xyz" color space with "xyz-d65".
This fixes the remaining subtests in: https://wpt.live/css/css-color/parsing/color-valid-color-mix-function.html.
> LibWeb: Canonicalize color space when parsing `color-mix()` function

- Libraries/LibWeb/CMakeLists.txt
- Libraries/LibWeb/CSS/CSSFontFaceDescriptors.cpp
- Libraries/LibWeb/CSS/CSSGroupingRule.cpp
- Libraries/LibWeb/CSS/CSSRuleList.cpp
- Libraries/LibWeb/CSS/CSSRuleList.h
- Libraries/LibWeb/CSS/CSSStyleProperties.cpp
- Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Libraries/LibWeb/CSS/Parser/Helpers.cpp
- Libraries/LibWeb/CSS/Parser/MediaParsing.cpp
- Libraries/LibWeb/CSS/Parser/Parser.cpp
- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/CSS/Parser/RuleContext.cpp
- Libraries/LibWeb/CSS/Parser/RuleContext.h
- Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-conditional/js/conditional-CSSGroupingRule.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-nesting/nested-declarations-cssom.txt
The main part of this is updating our implementation to support nested declarations. But also, we now track the rule context (aka, the tree of CSSRules we're in) when parsing CSS set by JS. This definitely needs doing in more places, but for now, it fixes a few WPT subtests.
> LibWeb/CSS: Make `insertRule()` more accurate

- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Tests/LibWeb/Layout/expected/block-and-inline/float-clear-right-should-not-affect-inline-left.txt
- Tests/LibWeb/Layout/input/block-and-inline/float-clear-right-should-not-affect-inline-left.html
In https://github.com/LadybirdBrowser/ladybird/commit/15103d172c2a4279c611d8a9d6262e15d3a3351e we applied any remaining vertical float clearance to the BFC's current Y offset for the next block to layout, because a `<br style="clear: left">` could introduce clearance that would otherwise be ignored. However, a `<div>` that floats _and_ clears `right` also introduces this clearance and it is obvious that this should not push down any subsequent blocks to layout in the current BFC.
Turns out, we don't need this change anymore. Some other later change also fixed the underlying issue, and by getting rid of the original fix we can now render https://en.wikipedia.org/wiki/SerenityOS correctly again.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4418.
> LibWeb: Remove application of vertical float clearance to BFC's Y offset

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/wpt-import/wasm/jsapi/proto-from-ctor-realm.txt
- Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/proto-from-ctor-realm.html
- Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/wasm-module-builder.js
When playing games with cross-realm construction, we need to make sure
that any calls to ensure_web_prototype for LegacyNamespace objects use
the correctly namespaced prototype name.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4438
> LibWeb: Account for LegacyNamespace attribute in constructor generator

- AK/Utf16View.cpp
- AK/Utf16View.h
- Libraries/LibJS/Runtime/GlobalObject.cpp
- Libraries/LibJS/Runtime/RegExpObject.cpp
- Libraries/LibJS/Runtime/Utf16String.cpp
- Libraries/LibJS/Runtime/Utf16String.h
- Libraries/LibRegex/RegexMatch.h
- Libraries/LibWeb/DOM/CharacterData.cpp
- Libraries/LibWeb/DOMURL/URLSearchParams.cpp
- Libraries/LibWeb/SVG/SVGTextContentElement.cpp
- Tests/LibUnicode/TestSegmenter.cpp
For the slight cost of counting code points when converting between encodings and a teeny bit of memory, this commit adds a fast path for all-happy utf-16 substrings and code point operations.
This seems to be a significant chunk of time spent in many regex benchmarks.
js benchmarks for fun:
```
SunSpider   Total                0.982  2.190           2.230
Kraken      Total                0.953  34.653          36.347
Octane      Total                1.003  222.273         221.690
JetStream   Total                0.998  275.303         275.777
JetStream3  Total                0.638  29.243          45.803
All Suites  Total                0.969  563.663         581.847
```
> AK+Everywhere: Recognise that surrogates in utf16 aren't all that common

- Libraries/LibRegex/RegexByteCode.h
- Libraries/LibRegex/RegexMatcher.h
- Libraries/LibRegex/RegexOptimizer.cpp
Previously we were counting the total number of *nodes* in the tree for the chain cost, which greatly underestimated its cost when large bytecode entries were present,
This commit switches to estimating it using the total bytecode *size*, which is a closer value to the true cost than the tree node count.
This corresponds to a ~4x perf improvement on /<script|<style|<link/ in speedometer.
> LibRegex: Better estimate the cost of laying out alts as a chain

- Libraries/LibWeb/CSS/StyleComputer.cpp
This fixes a regression introduced by: #4387
Fixes a crash on: https://bbc.co.uk
I was able to reproduce the crash on `master` with the following test file by mousing over the red square:
```html
<style>
div {
width: 100px;
height: 100px;
background-color: red;
}
div:hover {
transition: none;
}
</style>
<div></div>
```
For some reason I can't recreate the crash using either `internals.moveMouseTo()` or `internals.hitTest()`.
> LibWeb: Don't crash when processing a transition with value `none`

- Libraries/LibRegex/RegexOptimizer.cpp
- Tests/LibRegex/Regex.cpp
Fixes a bunch of websites breaking because we now verify jump offsets by trying to remove 0-offset jumps.
This has been broken for a good while, it was just rare to see Repeat inside alternatives that lended themselves well to tree alts.
> LibRegex: Correctly calculate the target for Repeat in table alts

- Libraries/LibJS/Runtime/AbstractOperations.cpp
- Libraries/LibJS/Runtime/ProxyObject.cpp
- Libraries/LibJS/Runtime/ProxyObject.h
- Libraries/LibJS/Runtime/Value.cpp
This refactor is from two editorial changes to the spec from a while back.
https://github.com/tc39/ecma262/commit/44d1cae2b28f14b24f992b1db7c2fd3e9fc90c4f https://github.com/tc39/ecma262/commit/21ffeee8697e5d7c30871322608e57fe7bac509e
Found while trying to debug a crash in https://github.com/web-platform-tests/wpt/blob/master/wasm/jsapi/proto-from-ctor-realm.html (only in debug mode though :thonk:, in release mode we spin spin spin on a bogus HashTable lookup)
> LibJS: Add and use ValidateNonRevokedProxy AO

- Libraries/LibJS/CMakeLists.txt
- Libraries/LibJS/Runtime/CommonPropertyNames.h
- Libraries/LibJS/Runtime/ErrorTypes.h
- Libraries/LibJS/Runtime/JSONObject.cpp
- Libraries/LibJS/Runtime/JSONObject.h
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/RawJSONObject.cpp
- Libraries/LibJS/Runtime/RawJSONObject.h
- Libraries/LibJS/Tests/builtins/JSON/JSON.isRawJSON.js
- Libraries/LibJS/Tests/builtins/JSON/JSON.rawJSON.js
This pr implements `rawJSON` and `isRawJSON` functions from this proposal: [https://tc39.es/proposal-json-parse-with-source/](https://tc39.es/proposal-json-parse-with-source/)
These functions are now fully implemented, but they represent only a portion of the proposal. The remaining parts involve extending `JSON.parse` to expose source text access via [Parse Nodes](https://tc39.es/ecma262/#sec-syntactic-grammar) which our JSON parser doesn't currently produce. I’ll look into whether I can tackle that part too, but it seems pretty complex, so I decided to start with this smaller PR.
Summary:
+15 ✅    -15 ❌   
Diff Tests:
test/built-ins/JSON/isRawJSON/basic.js                           ❌ -> ✅
test/built-ins/JSON/isRawJSON/builtin.js                         ❌ -> ✅ …
> LibJS: Implement `rawJSON` and `isRawJSON`

- Libraries/LibWeb/Layout/TreeBuilder.cpp
- Tests/LibWeb/Layout/expected/block-and-inline/bfc-consider-all-currently-stacked-floats.txt
- Tests/LibWeb/Layout/expected/block-and-inline/clearfix.txt
- Tests/LibWeb/Layout/expected/block-and-inline/float-2.txt
- Tests/LibWeb/Layout/expected/block-and-inline/float-clear-by-line-break-followed-by-block.txt
- Tests/LibWeb/Layout/expected/block-and-inline/float-clear-right-should-not-affect-inline-left.txt
- Tests/LibWeb/Layout/expected/block-and-inline/float-vertical-offset-by-preceding-float.txt
- Tests/LibWeb/Layout/expected/block-and-inline/float-with-inline-contents-hoisted.txt
- Tests/LibWeb/Layout/expected/position-absolute-top-left.txt
- Tests/LibWeb/Layout/expected/resolve-height-of-containing-block.txt
- Tests/LibWeb/Layout/expected/set-margin-of-floating-box.txt
- Tests/LibWeb/Layout/expected/tab-size-spacing-001.txt
- Tests/LibWeb/Layout/input/block-and-inline/float-with-inline-contents-hoisted.html
- Tests/LibWeb/Text/expected/wpt-import/css/CSS2/floats/zero-space-between-floats-004.txt
Whenever we introduce a block element in a container that at that point has only had inline children, we create an anonymous wrapper for all the inline elements so we can keep the invariant that each container contains either inline or non-inline children. For some reason, we ignore all the out-of-flow nodes since they are layed out separately and it was thought that this shouldn't matter.
However, if we are dealing with inline blocks and floating blocks, the order of the inline contents _including_ out-of-flow nodes becomes very important: floating blocks need to take the order of nodes into account when positioning themselves.
Fix this by simply hoisting the out-of-flow nodes into the anonymous wrapper as well.
Fixes the order of blocks in #4212. The gap is still not present.
> LibWeb: Don't mess up the order of nodes when wrapping inline contents

- .github/actions/cache-restore/action.yml
- .github/actions/cache-save/action.yml
- .github/workflows/js-artifacts.yml
- .github/workflows/lagom-template.yml
- .github/workflows/nightly-android.yml
- CMakePresets.json
This is a workaround for the deprecation of the cache v1 REST API that was replaced with a new protobuf RPC based API this month. vcpkg was using the private cache backend API without the knowledge of the GitHub actions team, and was thus broken by the deprecation.
While we wait for Microsoft to talk to Microsoft to get this feature restored, we can use the raw actions/cache step to get almost the same cache behavior. The only difference is that the cache will be less fine grained than the per-package cache that VCPKG_BINARY_SOURCES of x-gha was giving us before.
re: https://github.com/LadybirdBrowser/ladybird/issues/4391
upstream: https://github.com/microsoft/vcpkg/issues/45073
> CI: Use a raw actions/cache step for vcpkg instead of the x-gha source

- Libraries/LibWeb/CSS/CSSNestedDeclarations.cpp
- Libraries/LibWeb/CSS/CSSNestedDeclarations.h
- Libraries/LibWeb/CSS/CSSNestedDeclarations.idl
We implement `CSSStyleProperties` so let's use it.
Not sure if there are any tests that rely on this, I just stumbled across this fixme.
> LibWeb: Return correct type from `CSSNestedDeclarations::style`

- Libraries/LibWeb/HTML/Location.cpp
This never worked properly when implemented as it would always throw an error for an invalid scheme on URL parsing.
Fixes at least some tests in:
https://wpt.live/html/browsers/history/the-location-interface/location-protocol-setter-non-broken.html
And all tests in:
https://wpt.live/html/browsers/history/the-location-interface/location-protocol-setter-non-broken-weird.html
And maybe tests in some other places too, but these are not imported as the tests are written with delays that makes them take a long time to run, and some of them rely on HTTP(s).
> LibWeb/HTML: Fix parsing of protocol in Location.protocol setter

- Libraries/LibWeb/Layout/LayoutState.cpp
- Tests/LibWeb/Text/expected/scrollable-viewport-with-position-fixed.txt
- Tests/LibWeb/Text/input/scrollable-viewport-with-position-fixed.html
Sometimes fixed positioned boxes would extend the viewport's scrollable overflow, which according to the spec should never happen. There are some nuances to this, such as properly determining the fixed positioning containing block for a fixed position box, but for now this prevents some pages from being overly scrollable.
Fixes horizontal scrollability of https://tweakers.net.
> LibWeb: Exclude fixed positioned boxes from scrollable overflow

- Libraries/LibWeb/ARIA/ARIAMixin.idl
- Libraries/LibWeb/CSS/CSSLayerStatementRule.idl
- Libraries/LibWeb/Clipboard/ClipboardItem.idl
- Libraries/LibWeb/HTML/DataTransfer.idl
- Libraries/LibWeb/HTML/MessageEvent.idl
- Libraries/LibWeb/HTML/NavigatorLanguage.idl
- Libraries/LibWeb/IntersectionObserver/IntersectionObserver.idl
- Libraries/LibWeb/PerformanceTimeline/PerformanceObserver.idl
- Libraries/LibWeb/ResizeObserver/ResizeObserverEntry.idl
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
A `FrozenArray` is simply a `sequence` whose integrity level is "frozen".
This doesn't seem to really affect tests, but I was tired of writing "FIXME: should be a FrozenArray" in IDL files 🙃
> LibWeb: Implement `FrozenArray` IDL attributes

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Bytecode/Executable.h
- Libraries/LibJS/Bytecode/Generator.cpp
- Libraries/LibJS/Bytecode/Generator.h
- Libraries/LibJS/Bytecode/Instruction.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Interpreter.h
- Libraries/LibJS/Bytecode/Op.h
- Libraries/LibJS/Bytecode/Operand.h
- Libraries/LibJS/Parser.cpp
This allows us to get rid of instructions that move arguments to locals
and allocate smaller JS::Value vector in ExecutionContext by reusing
slots that were already allocated for arguments.
With this change for following function:
```js
function f(x, y) {
return x + y;
}
```
we now produce following bytecode:
```
[   0]    0: Add dst:reg6, lhs:arg0, rhs:arg1
[  10]       Return value:reg6
```
instead of:
```
[   0]    0: GetArgument 0, dst:x~1
[  10]       GetArgument 1, dst:y~0
[  20]       Add dst:reg6, lhs:x~1, rhs:y~0
[  30]       Return value:reg6
```
```
Suite       Test                                   Speedup  Old (Mean ± Range)        New (Mean ± Range)
----------  -----------------------------------  ---------  ------------------------  ------------------------
Kraken …
```
> Skip allocating locals for arguments that allowed to be local

- Libraries/LibWeb/HTML/Navigable.cpp
- Libraries/LibWeb/HTML/NavigableContainer.cpp
We don't yet support out-of-process subframes. Explicitly disable even attempting to isolate subframes. Otherwise, navigating a subframe to a non-same-site URL would actually cause the top-level frame to navigate with our current implementation.
> LibWeb: Temporarily disable site isolation for subframes

- Libraries/LibJS/Runtime/Error.h
- Libraries/LibJS/Runtime/Object.h
- Meta/Lagom/CMakeLists.txt
Object defines an `is_error` virtual method to be overridden by Error for fast-is. This is the same name as the `Error.isError` constructor method. Rename the former to avoid conflicts, as GCC 15 just started warning on this.
Fixes #4486
> LibJS: Avoid naming conflict between Object's and Error's `is_error`

- Libraries/LibWeb/ARIA/ARIAMixin.cpp
- Libraries/LibWeb/ARIA/ARIAMixin.h
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/WebIDL/AbstractOperations.cpp
- Libraries/LibWeb/WebIDL/AbstractOperations.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/dom/aria-element-reflection.txt
For attributes like `Element.ariaControlsElements`, which are a reflection of `FrozenArray<Element>`, we must return the same `JS::Array` object every time the attribute is invoked - until its contents have changed. This patch implements caching of the reflected array in accordance with the spec.
> LibWeb: Implement caching of reflected element array attributes

- Libraries/LibRegex/RegexOptimizer.cpp
- Tests/LibRegex/Regex.cpp
> LibRegex: Use the right offset when patching jumps through fork-trees

- Libraries/LibJS/Runtime/Value.h
This is no longer used after 3cf5053.
> LibJS: Remove value_or from JS::Value

- Libraries/LibJS/Bytecode/Generator.cpp
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Runtime/AbstractOperations.cpp
- Libraries/LibJS/Runtime/BoundFunction.cpp
- Libraries/LibJS/Runtime/BoundFunction.h
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
- Libraries/LibJS/Runtime/ExecutionContext.h
- Libraries/LibJS/Runtime/FunctionObject.h
- Libraries/LibJS/Runtime/FunctionPrototype.cpp
- Libraries/LibJS/Runtime/FunctionPrototype.h
- Libraries/LibJS/Runtime/NativeFunction.cpp
- Libraries/LibJS/Runtime/NativeFunction.h
- Libraries/LibJS/Runtime/ProxyObject.cpp
- Libraries/LibJS/Runtime/ProxyObject.h
- Libraries/LibJS/Runtime/WrappedFunction.cpp
- Libraries/LibJS/Runtime/WrappedFunction.h
- Libraries/LibWeb/WebDriver/ExecuteScript.cpp
- Libraries/LibWeb/WebDriver/JSON.cpp
Instead of letting every [[Call]] implementation allocate an
ExecutionContext, we now make that a responsibility of the caller.
The main point of this exercise is to allow the Call instruction
to write function arguments directly into the callee ExecutionContext
instead of copying them later.
This makes function calls significantly faster:
- 10-20% faster on micro-benchmarks (depending on argument count)
- 4% speedup on Kraken
- 2% speedup on Octane
- 5% speedup on JetStream
```
Suite       Test                                   Speedup  Old (Mean ± Range)          New (Mean ± Range)
----------  -----------------------------------  ---------  --------------------------  ------------------------
SunSpider   3d-cube.js                               1      0.010 ± 0.010 … 0.010       0.010 ± …
```
> LibJS: Let invokers (callers) of [[Call]] allocate ExecutionContext

- Libraries/LibWeb/CSS/Interpolation.cpp
- Tests/LibWeb/Crash/wpt-import/css/css-values/animations/scale-interpolation-crash.html
The `x` and `y` values of the `scale` property are a `<length-percentage>`, but we previously only handled the case where they were `<number>` and crashed otherwise.
> LibWeb: Don't crash when interpolating non `<number>` scale values

- Libraries/LibWeb/CSS/SelectorEngine.cpp
- Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/selector/attribute-value-selector-009-ref.html
- Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/selector/attribute-value-selector-010-ref.html
- Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/selector/lang-pseudoclass-001-ref.html
- Tests/LibWeb/Ref/input/wpt-import/css/CSS2/selector/attribute-value-selector-009.xht
- Tests/LibWeb/Ref/input/wpt-import/css/CSS2/selector/attribute-value-selector-010.html
- Tests/LibWeb/Ref/input/wpt-import/css/CSS2/selector/lang-pseudoclass-001.html
- Tests/LibWeb/Ref/input/wpt-import/css/CSS2/selector/lang-pseudoclass-002.xht
This fixes all WPT tests in the `css/CSS2/selector` directory.
> LibWeb: Ensure `|=` value selector and `lang` pseudoclass correctly match language subcodes 

- Libraries/LibWeb/ContentSecurityPolicy/Directives/Directive.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/Directive.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveFactory.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveFactory.h
- Libraries/LibWeb/ContentSecurityPolicy/Policy.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Policy.h
- Libraries/LibWeb/ContentSecurityPolicy/PolicyList.cpp
- Libraries/LibWeb/ContentSecurityPolicy/PolicyList.h
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/DocumentLoading.h
- Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Libraries/LibWeb/HTML/BrowsingContext.cpp
- Libraries/LibWeb/HTML/Navigable.cpp
- Libraries/LibWeb/HTML/NavigationParams.h
- Libraries/LibWeb/HTML/PolicyContainers.cpp
- Libraries/LibWeb/HTML/PolicyContainers.h
- Libraries/LibWeb/HTML/Scripting/EnvironmentSettingsSnapshot.cpp
- Libraries/LibWeb/HTML/SourceSnapshotParams.h
- Libraries/LibWeb/HTML/WorkerGlobalScope.cpp
- Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
These are not associated with a javascript realm, so to avoid confusion about which realm these need to be created in, make all of these objects a GC::Cell, and deal with the fallout.
> LibWeb: Make a bunch of CSP classes not realm associated 

- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
Handful of simple little things that add up to a lot:
```
Suite       Test               Speedup  Old (Mean ± Range)     New (Mean ± Range)
----------  ---------------  ---------  ---------------------  ---------------------
MicroBench  call-00-args.js      1.048  1.730 ± 1.690 … 1.770  1.650 ± 1.620 … 1.680
MicroBench  call-01-args.js      1.024  1.730 ± 1.720 … 1.740  1.690 ± 1.680 … 1.700
MicroBench  call-02-args.js      1.035  1.760 ± 1.720 … 1.800  1.700 ± 1.700 … 1.700
MicroBench  call-03-args.js      1.061  1.750 ± 1.740 … 1.760  1.650 ± 1.630 … 1.670
MicroBench  call-04-args.js      1.038  1.760 ± 1.750 … 1.770  1.695 ± 1.680 … 1.710
MicroBench  call-16-args.js      1.069  1.940 ± 1.940 … 1.940  1.815 ± 1.800 … 1.830
MicroBench  call-32-args.js      1.072  2.240 ± 2.210 … 2.270 …
```
> More LibJS things to make function calls faster

- AK/NonnullRefPtr.h
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Libraries/LibJS/Runtime/VM.cpp
- Libraries/LibJS/Runtime/VM.h
Another handfull of small but helpful things.
```
Suite       Test               Speedup  Old (Mean ± Range)     New (Mean ± Range)
----------  ---------------  ---------  ---------------------  ---------------------
MicroBench  call-00-args.js      1.077  1.673 ± 1.620 … 1.730  1.553 ± 1.520 … 1.610
MicroBench  call-01-args.js      1.073  1.673 ± 1.610 … 1.750  1.560 ± 1.530 … 1.580
MicroBench  call-02-args.js      1.057  1.667 ± 1.590 … 1.720  1.577 ± 1.550 … 1.630
MicroBench  call-03-args.js      1.055  1.650 ± 1.610 … 1.730  1.563 ± 1.550 … 1.580
MicroBench  call-04-args.js      1.093  1.727 ± 1.690 … 1.800  1.580 ± 1.580 … 1.580
MicroBench  call-16-args.js      1.053  1.850 ± 1.810 … 1.900  1.757 ± 1.740 … 1.770
MicroBench  call-32-args.js      1.07   2.133 ± 2.060 … 2.230  1.993 ± …
```
> More shenanigans for JS call performance

- AK/String.cpp
Noticed while working on something else. Another small win could be adding a char overload to skip utf8 work for both starts_with and ends_with since that's the common case, but this is an improvement anyhow.
> AK: Don't iterate through entire String for String::ends_with

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Interpreter.h
- Libraries/LibJS/Runtime/ExecutionContext.h
- Libraries/LibJS/Runtime/VM.cpp
- Libraries/LibJS/Runtime/VM.h
- Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
This way it's always automatically correct, and we don't have to manually flush it in push_execution_context().
~7% speedup on the MicroBench/call* tests :^)
```
Suite       Test               Speedup  Old (Mean ± Range)     New (Mean ± Range)
----------  ---------------  ---------  ---------------------  ---------------------
MicroBench  call-00-args.js      1.059  1.553 ± 1.520 … 1.610  1.467 ± 1.420 … 1.500
MicroBench  call-01-args.js      1.056  1.560 ± 1.530 … 1.580  1.477 ± 1.430 … 1.540
MicroBench  call-02-args.js      1.097  1.577 ± 1.550 … 1.630  1.437 ± 1.430 … 1.440
MicroBench  call-03-args.js      1.073  1.563 ± 1.550 … 1.580  1.457 ± 1.450 … 1.470
MicroBench  call-04-args.js      1.075  1.580 ± 1.580 … 1.580  1.470 ± 1.460 … 1.480
MicroBench  call-16-args.js      1.076  1.757 …
```
> LibJS: Store bytecode VM program counter in ExecutionContext

- Libraries/LibWeb/HTML/HTMLStyleElement.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/document-metadata/the-style-element/style_type_change.txt
- Tests/LibWeb/Text/input/wpt-import/html/semantics/document-metadata/the-style-element/style_type_change.html
Fixes at least 2 WPT sub-tests.
Basically re-evaluates `update_a_style_block` when type attribute changes.
> LibWeb: Re-evaluate the style block when the type attribute changes

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Op.h
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
- Libraries/LibJS/Runtime/VM.cpp
- Libraries/LibJS/Runtime/VM.h
Funny how there's so much juice to squeeze out of this thing..
```
Suite       Test               Speedup  Old (Mean ± Range)     New (Mean ± Range)
----------  ---------------  ---------  ---------------------  ---------------------
MicroBench  call-00-args.js      1.019  1.443 ± 1.410 … 1.500  1.417 ± 1.370 … 1.490
MicroBench  call-01-args.js      1.024  1.440 ± 1.420 … 1.480  1.407 ± 1.380 … 1.450
MicroBench  call-02-args.js      1.052  1.477 ± 1.430 … 1.540  1.403 ± 1.390 … 1.430
MicroBench  call-03-args.js      1.04   1.487 ± 1.450 … 1.550  1.430 ± 1.400 … 1.490
MicroBench  call-04-args.js      1.054  1.503 ± 1.470 … 1.570  1.427 ± 1.420 … 1.430
MicroBench  call-16-args.js      1.027  1.663 ± 1.640 … 1.700  1.620 ± 1.590 … 1.670
MicroBench  call-32-args.js      1.038  1.923 ± 1.910 … …
```
> Even more LibJS shenanigans for faster calls

- Libraries/LibWeb/DOM/Document.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-transitions/events-001.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-transitions/properties-value-002.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-transitions/events-001.html
This fixes 645 subtests in the `css/css-transitions` directory.
> LibWeb: Set transition property name when firing transition events

- Libraries/LibGfx/PainterSkia.cpp
- Libraries/LibGfx/PaintingSurface.cpp
- Libraries/LibGfx/SkiaUtils.h
- Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
- Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
- Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
- Libraries/LibWeb/HTML/HTMLCanvasElement.h
- Libraries/LibWeb/WebDriver/Screenshot.cpp
- Tests/LibWeb/Ref/expected/wpt-import/html/canvas/element/manual/context-attributes/clearRect_alpha_false-ref.html
- Tests/LibWeb/Ref/input/wpt-import/html/canvas/element/manual/context-attributes/clearRect_alpha_false.html
There's still more needed for a full implementation, but this deals with parsing and returning the context's attributes and supporting the right clearing behavior for contexts created with `{"alpha": false}`.
Adds +20 WPT passes in `html/canvas/element`.
> LibWeb+LibGfx: Support `alpha` context attribute for CanvasRenderingContext2D

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Interpreter.h
- Libraries/LibJS/Bytecode/Op.h
- Libraries/LibJS/Forward.h
This is a simple trick to generate better native code for access to registers, locals, and constants. Before this change, each access had to first dereference the member pointer in Interpreter, and then get to the values. Now we always have a pointer directly to the values on hand.
Here's how it looks:
class StackFrame {
public:
Value get(Operand) const;
void set(Operand, Value);
private:
Value m_values[];
};
And we just place one of these as a window on top of the execution context's array of values (registers, locals, and constants).
```
Suite       Test                                   Speedup  Old (Mean ± Range)        New (Mean ± Range)
----------  -----------------------------------  ---------  ------------------------  ------------------------
SunSpider   3d-cube.js …
```
> LibJS: Add StackFrame to avoid indirection in VM register access

- Libraries/LibIPC/TransportSocket.cpp
- Libraries/LibWeb/HTML/RenderingThread.cpp
- Libraries/LibWeb/HTML/RenderingThread.h
Two fixes that came about by running `./Meta/ladybird.sh run headless-browser -R $PWD/Tests/LibWeb -f Text/input/HTML` over and over and seeing what was unhappy.
There's a new RequestServer 'EPIPE b/c WebContent disappeared when we had data for it in the queue' crash that comes about by fixing this, but a new crash is better than two old crashes, right? ...right?
> LibIPC+LibWeb: Fix some race conditions found cycling headless-browser a bunch

- Libraries/LibJS/Runtime/ArrayIterator.cpp
- Libraries/LibJS/Runtime/ArrayIterator.h
- Libraries/LibJS/Runtime/ArrayIteratorPrototype.cpp
- Libraries/LibJS/Runtime/RegExpStringIterator.cpp
- Libraries/LibJS/Runtime/RegExpStringIterator.h
- Libraries/LibJS/Runtime/RegExpStringIteratorPrototype.cpp
This is a normative change in the ECMA-262 spec. See: https://github.com/tc39/ecma262/commit/de62e8d
This did not actually seem to affect our implementation as we were not using generators here to begin with. So this patch is basically just adding spec comments.
> LibJS: Revert ArrayIterator and RegExpStringIterator to manual iterators

- Libraries/LibWeb/Fetch/Infrastructure/HTTP/Bodies.cpp
- Libraries/LibWeb/Streams/ReadableStream.cpp
- Libraries/LibWeb/Streams/ReadableStream.h
- Libraries/LibWeb/Streams/ReadableStreamDefaultReader.cpp
- Libraries/LibWeb/Streams/ReadableStreamDefaultReader.h
We currently store `Web::Fetch::Infrastructure::Response` objects in the HTTP cache. They are associated with their original realm, but when we use a cached response, we clone it into the target realm. For example, two `<iframe>` objects loading the same HTML will be in different realms.
When we clone the response, we must use the target realm throughout the entire cloning process. We neglected to do this for the cloned response body stream, which is cloned via teeing. The result was the the stream for the "cloned" response was created in the original realm, causing issues down the line when reading from that stream tried to handle read promises on behalf of the original realm. There are protections in place to prevent this from happening, and the cached response read would never …
> LibWeb: Use the correct target realm to tee a stream

- Libraries/LibWeb/CSS/ComputedValues.h
- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Libraries/LibWeb/CSS/StyleValues/URLStyleValue.h
- Libraries/LibWeb/HTML/CanvasPattern.cpp
- Libraries/LibWeb/Layout/Node.cpp
- Libraries/LibWeb/SVG/SVGGraphicsElement.h
- Libraries/LibWeb/SVG/SVGTextPathElement.cpp
- Libraries/LibWeb/WebAudio/AnalyserNode.cpp
With :sparkles: **_bonus_** :sparkles: typo fixes.
> LibWeb/CSS: Use CSS URLs for `<url>` and `<paint>` types

- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Bytecode/Instruction.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Op.h
- Libraries/LibJS/Forward.h
- Libraries/LibJS/Runtime/ArrayIterator.cpp
- Libraries/LibJS/Runtime/ArrayIterator.h
- Libraries/LibJS/Runtime/ArrayIteratorPrototype.cpp
- Libraries/LibJS/Runtime/Iterator.h
- Libraries/LibJS/Runtime/MapIterator.cpp
- Libraries/LibJS/Runtime/MapIterator.h
- Libraries/LibJS/Runtime/MapIteratorPrototype.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/SetIterator.cpp
- Libraries/LibJS/Runtime/SetIterator.h
- Libraries/LibJS/Runtime/SetIteratorPrototype.cpp
- Libraries/LibJS/Runtime/StringIterator.cpp
- Libraries/LibJS/Runtime/StringIterator.h
- Libraries/LibJS/Runtime/StringIteratorPrototype.cpp
Introduce special instruction for `for..of` and `for..in` loop that
skips `{ value, done }` result object allocation if iterator is builtin
(array, map, set, string). This reduces GC pressure significantly and
avoids extracting the `value` and `done` properties.
This change makes this micro benchmark 45% faster on my computer:
```js
const arr = new Array(10_000_000);
let counter = 0;
for (let _ of arr) {
counter++;
}
```
> Skip iterator result object allocation in for..of and for..in

- Services/RequestServer/ConnectionFromClient.cpp
- Services/RequestServer/WebSocketImplCurl.cpp
- Services/RequestServer/WebSocketImplCurl.h
The assertion in `WebSocketImplCurl::did_connect()` keeps failing for multiple websockets when loading `https://www.speedtest.net/` since commit 14ebcd4. This fixes that by checking and returning false if something went wrong and letting the caller function handle it.
Fixes: #3828
> RequestServer: Don't assert for socket fd not being CURL_SOCKET_BAD

- Libraries/LibWeb/Editing/Internal/Algorithms.cpp
- Tests/LibWeb/Text/expected/Editing/execCommand-insertLinebreak.txt
- Tests/LibWeb/Text/input/Editing/execCommand-insertLinebreak.html
The editing command that relies the most on this, `insertLinebreak`, did not perform a layout update after inserting a `<br>` which caused this algorithm to always return false. But instead of actually building the layout tree needlessly, we can check the DOM tree instead.
+53 new WPT passes in `editing/`.
> LibWeb: Do not rely on the layout tree for collapsed line breaks during editing

- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Bytecode/Instruction.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Op.h
...by avoiding `{ value, done }` iterator result value allocation. This change applies the same otimization 81b6a11 added for `for..in` and `for..of`.
Makes following micro benchmark go 22% faster on my computer:
```js
function f() {
const arr = [];
for (let i = 0; i < 10_000_000; i++) {
arr.push([i]);
}
let sum = 0;
for (let [i] of arr) {
sum += i;
}
}
f();
```
> LibJS: Optimize array destructuring assignment for builtin iterators

- Libraries/LibGC/Ptr.h
- Libraries/LibGC/Root.h
This is a copy of the Formatters we have for AK's pointer types.
It was annoying me having to type `.ptr()` whenever I wanted to `dbgln()` something.
> LibGC: Make GC::Ptr, GC::Ref, and GC::Root formattable

- Libraries/LibWeb/TreeNode.h
Using `as<T>` calls into `as_if<T>`, so let's just immediately use that for the "node of type" iterators. No functional changes.
> LibWeb: Use `as_if<T>` in TreeNode methods

- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/Transformation.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/geometry/DOMMatrix-001.txt
Here are two small CSS parser fixes that improve the DOMMatrix string constructor. It also fixes the last 4 fails on http://wpt.live/css/geometry/DOMMatrix-001.html
I've also rearranged the code in `Transformation.cpp` to be in the same order as the `TransformValue` variant
> LibWeb: Two DOMMatrix CSS parser fixes

- Base/res/ladybird/about-pages/about.html
Very small pr that adds the previous added internal pages to the `about:about` links overview page, because they where missing.
> Base: Add about:settings and about:processes to about:about page

- Libraries/LibWeb/CMakeLists.txt
- Libraries/LibWeb/Clipboard/Clipboard.cpp
- Libraries/LibWeb/Clipboard/Clipboard.h
- Libraries/LibWeb/Clipboard/Clipboard.idl
- Libraries/LibWeb/Clipboard/ClipboardItem.cpp
- Libraries/LibWeb/Clipboard/ClipboardItem.h
- Libraries/LibWeb/Clipboard/SystemClipboard.cpp
- Libraries/LibWeb/Clipboard/SystemClipboard.h
- Libraries/LibWeb/Forward.h
- Libraries/LibWeb/Page/Page.cpp
- Libraries/LibWeb/Page/Page.h
- Libraries/LibWebView/ViewImplementation.cpp
- Libraries/LibWebView/ViewImplementation.h
- Libraries/LibWebView/WebContentClient.cpp
- Libraries/LibWebView/WebContentClient.h
- Services/WebContent/ConnectionFromClient.cpp
- Services/WebContent/ConnectionFromClient.h
- Services/WebContent/PageClient.cpp
- Services/WebContent/PageClient.h
- Services/WebContent/WebContentClient.ipc
- Services/WebContent/WebContentServer.ipc
- UI/AppKit/Interface/LadybirdWebView.mm
- UI/AppKit/Utilities/Conversions.h
- UI/AppKit/Utilities/Conversions.mm
- UI/Headless/HeadlessWebView.cpp
- UI/Headless/HeadlessWebView.h
- UI/Qt/StringUtils.cpp
- UI/Qt/StringUtils.h
- UI/Qt/Tab.cpp
There's a healthy dose of spec bugs here, but this fleshes out `write`, `writeText`, and `read`. Fixes ~40 tests under https://wpt.fyi/results/clipboard-apis/.
These tests require both HTTPS (i.e. not file://) and WebDriver to work (i.e. can't even run them on wpt.live).
> LibWeb+UI: Implement remaining `navigator.clipboard` APIs

- Libraries/LibGfx/Font/Typeface.cpp
- Libraries/LibGfx/Font/Typeface.h
- Libraries/LibGfx/Font/WOFF/Loader.cpp
- Libraries/LibGfx/Font/WOFF/Loader.h
- Libraries/LibGfx/Font/WOFF2/Loader.cpp
- Libraries/LibGfx/Font/WOFF2/Loader.h
- Libraries/LibWeb/CSS/CSSFontFaceRule.cpp
- Libraries/LibWeb/CSS/CSSImportRule.cpp
- Libraries/LibWeb/CSS/Fetch.cpp
- Libraries/LibWeb/CSS/Fetch.h
- Libraries/LibWeb/CSS/FontFace.cpp
- Libraries/LibWeb/CSS/ParsedFontFace.cpp
- Libraries/LibWeb/CSS/ParsedFontFace.h
- Libraries/LibWeb/CSS/Parser/Parser.cpp
- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/CSS/StyleComputer.h
- Libraries/LibWeb/CSS/StyleSheetList.cpp
- Libraries/LibWeb/CSS/StyleValues/FontSourceStyleValue.cpp
- Libraries/LibWeb/CSS/StyleValues/FontSourceStyleValue.h
- Libraries/LibWeb/CSS/URL.h
- Libraries/LibWeb/DOM/StyleElementUtils.cpp
- Libraries/LibWeb/Dump.cpp
- Meta/Lagom/Fuzzers/FuzzWOFF.cpp
- Meta/Lagom/Fuzzers/FuzzWOFF2.cpp
- Tests/LibGfx/TestWOFF.cpp
- Tests/LibGfx/TestWOFF2.cpp
Fonts are the last place we were using the old, wrong, URL-resolution in the CSS parser. In order to fix that I also had to convert our font loader to use fetch, so that's another tick on the list in #2634!
> LibWeb: Load fonts with Fetch

- Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
This was corrected in https://github.com/w3c/csswg-drafts/commit/8bcf3ada9e8b732f93daee5749b46503017cc4bd
> LibWeb/CSS: Update spec comment in calc() simplification algorithm

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Runtime/PrimitiveString.cpp
- Libraries/LibJS/Runtime/PrimitiveString.h
- Libraries/LibJS/Runtime/StringObject.cpp
- Libraries/LibWeb/IndexedDB/Internal/Algorithms.cpp
I was investigating an optimization in this area, and while it didn't seem to have a noticable improvement, it still seems useful to apply this change I made while investigating the fast path.
> LibJS: Add and use PrimitiveString::length_in_utf16_code_units

- AK/Base64.cpp
- AK/Base64.h
- Libraries/LibJS/Runtime/Uint8Array.cpp
- Libraries/LibJS/Runtime/Uint8Array.h
- Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.fromBase64.js
- Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.prototype.setFromBase64.js
- vcpkg.json
We were previously unable to use simdutf for base64 decoding operations other than "loose". Upstream has added support for the "strict" and "stop-before-partial" operations, so let's make use of them!
> AK+LibJS: Use simdutf for all base64 operations

- AK/HashMap.h
- Libraries/LibGC/CMakeLists.txt
- Libraries/LibGC/Heap.cpp
- Libraries/LibGC/Heap.h
- Libraries/LibGC/HeapRoot.h
- Libraries/LibGC/RootHashMap.cpp
- Libraries/LibGC/RootHashMap.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
Before this change, we would call [[OwnPropertyKeys]] on the target
objects, then convert the returned keys from Value into PropertyKey.
Then, when actually iterating, we'd convert them back into Value again.
This was particularly costly for numeric property keys, since we had
to go through string-from-number construction.
Now, we simply keep the original values returned by [[OwnPropertyKeys]]
around and use them for the enumeration.
1.09x speedup on MicroBench/for-in-indexed-properties.js
1.01x speedup on MicroBench/for-in-named-properties.js
> LibJS: Avoid Value->PropertyKey->Value roundtrip in for..in iteration

- Libraries/LibJS/Runtime/RegExpPrototype.cpp
- Libraries/LibJS/Runtime/RegExpPrototype.h
- Libraries/LibJS/Runtime/RegExpStringIterator.cpp
- Libraries/LibJS/Runtime/RegExpStringIterator.h
- Libraries/LibJS/Runtime/RegExpStringIteratorPrototype.cpp
- Libraries/LibJS/Runtime/StringPrototype.cpp
PrimitiveString has an internal UTF-16 string cache anyway, and so this
actually avoids repeatedly converting between UTF-8 and UTF-16.
1.02x speedup on Octane/regexp.js
> LibJS: Use PrimitiveString more instead of Utf16String in RegExp/String code

- Libraries/LibJS/Bytecode/Generator.cpp
- Libraries/LibJS/Bytecode/Instruction.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Op.h
Before this change, setting a global would end up as SetLexicalBinding. That instruction always failed to cache the access if the global was a property of the global object.
1.14x speedup on Octane/earley-boyer.js
2.04x speedup on MicroBench/for-of.js
Note that MicroBench/for-of.js was more of a "set global" benchmark before this. After this change, it's actually a for..of benchmark. :^)
> LibJS: Add SetGlobal bytecode instruction for cached global writes

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Bytecode/Instruction.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Op.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Runtime/DeclarativeEnvironment.h
`var` bindings are never in the temporal dead zone (TDZ), and so we know accessing them will not throw.
We now take advantage of this by having a specialized environment binding value getter that doesn't check for exceptional cases.
1.08x speedup on JetStream.
```
Suite       Test                                   Speedup  Old (Mean ± Range)        New (Mean ± Range)
----------  -----------------------------------  ---------  ------------------------  ------------------------
SunSpider   3d-cube.js                               1      0.010 ± 0.010 … 0.010     0.010 ± 0.010 … 0.010
SunSpider   3d-morph.js                              1      0.010 ± 0.010 … 0.010     0.010 ± 0.010 … 0.010
SunSpider   3d-raytrace.js                           2      0.020 ± 0.020 … 0.020     0.010 ± 0.010 … …
```
> LibJS: Optimize reading known-to-be-initialized `var` bindings

- Tests/LibWeb/Layout/expected/svg/inline-svg-with-zero-intrinsic-size-and-no-viewbox.txt
- Tests/LibWeb/Layout/expected/svg/nested-viewports.txt
- Tests/LibWeb/Layout/expected/svg/svg-g-inside-g.txt
- Tests/LibWeb/Layout/expected/svg/svg-inside-svg-with-xy.txt
- Tests/LibWeb/Layout/expected/svg/svg-symbol-with-viewbox.txt
- Tests/LibWeb/Layout/expected/svg/svg-use-element-crashtest.txt
- Tests/LibWeb/Layout/expected/svg/svg-with-zero-sized-viewBox.txt
- Tests/LibWeb/Layout/expected/svg/text-fill-none.txt
- Tests/LibWeb/Layout/input/svg/inline-svg-with-zero-intrinsic-size-and-no-viewbox.html
- Tests/LibWeb/Layout/input/svg/nested-viewports.html
- Tests/LibWeb/Layout/input/svg/svg-different-types-of-opacity.html
- Tests/LibWeb/Layout/input/svg/svg-g-inside-g.html
- Tests/LibWeb/Layout/input/svg/svg-g-with-opacity.html
- Tests/LibWeb/Layout/input/svg/svg-inside-svg-with-xy.html
- Tests/LibWeb/Layout/input/svg/svg-symbol-with-viewbox.html
- Tests/LibWeb/Layout/input/svg/svg-use-element-crashtest.html
- Tests/LibWeb/Layout/input/svg/svg-with-zero-sized-viewBox.html
- Tests/LibWeb/Layout/input/svg/text-fill-none.html
This adds an html doctype to every SVG layout test that didn't have one and was in an HTML file.
None of these are supposed to be in quirks more from what I can tell.
The only thing that changed on all of them is that the HTML element is no longer 600 pixels tall, so none of the relevant SVG layout changed.
This is a step towards making the CI enforce the presence of these doctypes and I've decided to do them one directory at a time since it's more manageable that way.
> Meta: Add doctypes to all svg layout tests

- Libraries/LibWeb/ContentSecurityPolicy/Policy.cpp
- Libraries/LibWeb/Cookie/ParsedCookie.cpp
- Libraries/LibWeb/Infra/Strings.cpp
- Libraries/LibWeb/Infra/Strings.h
- Libraries/LibWeb/MimeSniff/MimeType.cpp
We have more optimized versions of these methods in AK.
> LibWeb: Remove Web::Infra ASCII case conversion methods

- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/Properties.json
- Tests/LibWeb/Text/expected/wpt-import/css/css-contain/parsing/contain-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-contain/parsing/contain-valid.txt
This makes us actually respect the grammar and nets us a couple extra WPT passes in the parsing section.
(any maybe others, if they use weird combinations of stuff)
We still struggle with preserving the order of stuff when serializing but I'll leave that for some other time.
> LibWeb: Improve parsing for the CSS contain property

- Libraries/LibJS/Module.cpp
- Libraries/LibJS/Module.h
This is a normative change in the ECMA-262 spec. See:
https://github.com/tc39/ecma262/commit/0fb1859
As noted in the PR for this change, this is not actually testable via either test262 or WPT.
> LibJS: Mark sync module evaluation promise as handled

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Runtime/ArgumentsObject.cpp
- Libraries/LibJS/Runtime/ArgumentsObject.h
- Libraries/LibJS/Runtime/ModuleNamespaceObject.cpp
- Libraries/LibJS/Runtime/ModuleNamespaceObject.h
- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/ProxyObject.cpp
- Libraries/LibJS/Runtime/ProxyObject.h
- Libraries/LibJS/Runtime/TypedArray.h
- Libraries/LibWeb/Bindings/PlatformObject.cpp
- Libraries/LibWeb/Bindings/PlatformObject.h
- Libraries/LibWeb/HTML/Location.cpp
- Libraries/LibWeb/HTML/Location.h
- Libraries/LibWeb/HTML/WindowProxy.cpp
- Libraries/LibWeb/HTML/WindowProxy.h
- Libraries/LibWeb/WebIDL/ObservableArray.cpp
- Libraries/LibWeb/WebIDL/ObservableArray.h
This is *extremely* common on the web, but barely shows up at all in JavaScript benchmarks.
A typical example is setting Element.innerHTML on a HTMLDivElement. HTMLDivElement doesn't have innerHTML, so it has to travel up the prototype chain until it finds it.
Before this change, we didn't cache this at all, so we had to travel the prototype chain every time a setter like this was used.
We now use the same mechanism we already had for GetBydId and cache PutById setter accesses in the prototype chain as well.
1.74x speedup on MicroBench/setter-in-prototype-chain.js
> LibJS: Cache PutById to setters in the prototype chain

- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/date.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/datetime-local-trailing-zeros.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/datetime-local.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/datetime-weekmonth.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/datetime.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/email.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/files.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/input-stepdown-02.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/number.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/password.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/range.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/required_attribute.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/time.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/url.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/week.txt
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/date.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/datetime-local-trailing-zeros.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/datetime-local.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/datetime-weekmonth.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/datetime.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/email.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/files.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/input-stepdown-02.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/number.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/password.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/range.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/required_attribute.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/time.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/url.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/the-input-element/week.html
Importing these tests now because they are for input-element types that have requirements related to the constraint-validation API — which we’ve been implementing recently.
This commit only imports tests, without any changes to our code.
> Tests: Add a bunch of input-element tests (tests only, no code)

- Libraries/LibJS/AST.cpp
- Libraries/LibJS/AST.h
- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Bytecode/Executable.h
- Libraries/LibJS/Bytecode/Generator.cpp
- Libraries/LibJS/Bytecode/Generator.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/LocalVariable.h
- Libraries/LibJS/Parser.cpp
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
- Libraries/LibJS/Runtime/FunctionObject.h
- Tests/LibWeb/Text/input/WebAnimations/animation-methods/persist.html
Error about not-initialized `x` variable access should be thrown for:
```js
function foo() {
x = 69;
let x;
}
foo();
```
Progress on test262:
```
Diff Tests:
test/staging/sm/expressions/optional-chain-tdz.js ❌ -> ✅
test/staging/sm/expressions/short-circuit-compound-assignment-tdz.js ❌ -> ✅
```
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4587
> Emit ThrowIfTDZ for identifiers used in assignment expressions

- Libraries/LibWeb/Painting/Command.h
This `translate_by` function is invoked with the cumulative scroll offset during display list execution. Applying the offset to the gutter was missed in 66e422b4f1d1bda1c328b99f964f3a8c2cb5d4b1.
Fixes #4603.
> LibWeb: Translate scrollbar gutters by the cumulative scroll offset

- Libraries/LibJS/Bytecode/Executable.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
Instead of monomorphic (1 shape), GetById* and PutById* inline caches are now polymorphic (4 shapes).
This improves inline cache hit rates greatly on most web JavaScript.
For example, Speedometer 2.1 sees 88% -> 97% cache hit rate improvement.
> Polymorphic inline caches for LibJS

- Libraries/LibWeb/Painting/PaintableBox.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/filter-effects/css-filters-opacity-hit-testing.txt
- Tests/LibWeb/Text/input/wpt-import/css/filter-effects/css-filters-opacity-hit-testing.html
This brings us in line with Chrome and Firefox, but I could not find a spec for it.
I did find https://github.com/w3c/csswg-drafts/issues/2325, about hit testing not being defined anywhere, so that might be why.
The test is imported manually by me since I don't think WPT covers this case yet, so I opened a PR there as well. (https://github.com/web-platform-tests/wpt/pull/52375)
I hope that's fine.
This fixes some sliders on https://streamcreatures.com but you can't see them yet because the login doesn't work in Ladybird.
> LibWeb: Make elements with 'opacity: 0' respond to hit-testing

- Libraries/LibWeb/Editing/Commands.cpp
Forgot to implement this part of the spec. Adds 177 new WPT passes in `editing`.
> LibWeb: Assign new wrapped node list to container for insertParagraph

- Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
Fixes linking of CanvasRenderingContext2D on some systems:
[2959/3075] Linking CXX shared library lib/liblagom-web.so.0.0.0
FAILED: lib/liblagom-web.so.0.0.0
: && /nix/store/f0m6caffiykyvsjim9376a3hx2yj2ghj-gcc-wrapper-14.2.1.20250322/bin/g++ -fPIC -O3 -DNDEBUG  -fstack-protector-strong -Wl,-z,defs -Wl,--no-undefined -Wl,--no-allow-shlib-undefined -Wl,--dependency-file=Lagom/Libraries/LibWeb/CMakeFiles/LibWeb.dir/link.d -shared -Wl,-soname,liblagom-web.so.0 -o lib/liblagom-web.so.0.0.0 @CMakeFiles/LibWeb.rsp && :
/nix/store/hzw38c3f7s0w200cgk9645z53al7k8lw-binutils-2.44/bin/ld: Lagom/Libraries/LibWeb/CMakeFiles/LibWeb.dir/HTML/CanvasRenderingContext2D.cpp.o: in function `Web::HTML::CanvasRenderingContext2D::context_attributes_from_options(JS::VM&, JS::Value) [clone .localalias]': …
> LibWeb/HTML: Add missing include to CanvasRenderingContext2D.cpp

- .devcontainer/features/ladybird/install-fedora.sh
- .devcontainer/fedora-ci/devcontainer.json
- Documentation/BuildInstructionsLadybird.md
The provided patchelf from vcpkg is only version 0.14.3, which is too
old to produce working binaries on Fedora 42. Using that old version
causes hard to debug issues where applications segfault during startup.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/2149
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4563
> Documentation: Add patchelf as a dependency for on Fedora

- Libraries/LibWasm/AbstractMachine/Validator.cpp
- Libraries/LibWeb/WebAssembly/WebAssembly.cpp
- Libraries/LibWeb/WebAssembly/WebAssembly.h
- Libraries/LibWeb/WebAssembly/WebAssembly.idl
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/namespace-objects-default-property-attributes.txt
- Tests/LibWeb/Text/expected/wpt-import/wasm/jsapi/proto-from-ctor-realm.txt
See second commit for details, these errors cannot be true native errors, but we can get quite close.
Note that some wpt failures still remain where e.g. an instance of CompileError is not `instanceof WebAssembly.CompileError` as we can't have that as an error prototype.
> LibWeb/Wasm+IDLGenerators: Define the silly "native" errors given in the wasm spec

- Documentation/AdvancedBuildInstructions.md
I arbitrarily listed the Ubuntu package name because that's probably the most common OS people are using, and I thought listing an example is better than not doing so.
> Documentation: Mention requirements for ENABLE_CLANG_PLUGINS

- Libraries/LibWebView/Application.cpp
- Libraries/LibWebView/HelperProcess.cpp
Maybe my terminal colors are weird, but I just could not read the callgrind commands before:
So this removes the background color from the ANSI sequence:
> LibWebView: A couple of `--profile-process` ergonomic improvements

- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Runtime/Value.h
1.1x speedup on strictly-equals-object.js
Suite       Test                         Speedup  Old (Mean ± Range)     New (Mean ± Range)
----------  -------------------------  ---------  ---------------------  ---------------------
MicroBench  strictly-equals-object.js      1.105  1.170 ± 1.100 … 1.250  1.059 ± 1.050 … 1.060
MicroBench  Total                          1.105  1.170                  1.059
All Suites  Total                          1.105  1.170                  1.059
> LibJS: Avoid roundtrip through Value for comparison bytecode evaluation

- Libraries/LibJS/Bytecode/Interpreter.cpp
https://tc39.es/ecma262/#sec-jobs specifies that we should only be running queued promise jobs and host-defined cleanup when the execution context stack is empty. It is asserted to _not_ be empty the line above, so remove it.
No impact on test262 or our test suites, Interpreter::run_executable is already (incorrectly) performing this unconditionally. run_promise_jobs also happens to do nothing when LibJS is embedded into LibWeb.
> LibJS: Don't run promise and cleanup jobs in Interpreter::run

- Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.cpp
- Libraries/LibJS/Runtime/AsyncFunctionDriverWrapper.h
- Libraries/LibJS/Runtime/GeneratorObject.cpp
- Libraries/LibJS/Runtime/GeneratorObject.h
- Libraries/LibJS/Runtime/GeneratorPrototype.cpp
- Libraries/LibJS/Runtime/IteratorHelper.cpp
- Libraries/LibJS/Runtime/IteratorHelper.h
- Libraries/LibJS/Runtime/IteratorHelperPrototype.cpp
- Create less GC pressure by making each `await` in async function skip iteration result object allocation.
- Skip uncached `Object::get()` calls to extract `value` and `done` from the iteration result object.
With this change, following function goes 30% faster on my computer:
```js
(async () => {
const resolved = Promise.resolve();
for (let i = 0; i < 5_000_000; i++) {
await resolved;
}
})();
```
> LibJS: Skip iteration result allocation in AsyncFunctionDriverWrapper

- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Tests/LibWeb/Layout/expected/block-and-inline/block-with-hidden-overflow-after-float-and-margin-left.txt
- Tests/LibWeb/Layout/input/block-and-inline/block-with-hidden-overflow-after-float-and-margin-left.html
We would only correct for the left margin of the containing block of the child box that we are laying out, but we actually need to correct for all left margins up until the containing block that contains both the float and the child box.
Fixes #4639, the sidebar on https://security.nl:
|--|--|
| ![Screenshot_20250509_120726](https://github.com/user-attachments/assets/819cd53f-0d19-4b8d-9071-45381c993b91) | ![Screenshot_20250509_120705](https://github.com/user-attachments/assets/82409ef9-d872-41fd-a17a-3444cde5c683) |
> LibWeb: Overlap float space and left margins for all shared ancestors

- Libraries/LibWeb/HTML/HTMLDetailsElement.cpp
- Libraries/LibWeb/HTML/HTMLDetailsElement.h
- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Libraries/LibWeb/HTML/HTMLInputElement.h
- Libraries/LibWeb/HTML/HTMLMeterElement.cpp
- Libraries/LibWeb/HTML/HTMLMeterElement.h
- Libraries/LibWeb/HTML/HTMLProgressElement.cpp
- Libraries/LibWeb/HTML/HTMLProgressElement.h
- Libraries/LibWeb/HTML/HTMLSelectElement.cpp
- Libraries/LibWeb/HTML/HTMLSelectElement.h
- Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Libraries/LibWeb/HTML/HTMLTextAreaElement.h
We were unnecessarily discarding the shadow tree of input elements when they were removed or detached from the DOM.
This especially caused a *lot* of churn when creating input elements via setting .innerHTML on something. We ended up building each input element's shadow tree 3 times instead of 1.
The original issue that we were trying to solve by discarding the shadow tree appears to have been solved elsewhere, and nothing else seems to break by just allowing the shadow tree to stay.
1.05x speedup on Speedometer's TodoMVC-jQuery.
> LibWeb: Don't throw away HTMLInputElement shadow trees willy-nilly

- AK/Utf16View.cpp
By piggybacking on the already-optimized implementation in
StringBuilder, we can get simdutf for the AllowInvalidCodeUnits::Yes
case here as well.
1.03x speedup on Speedometer's TodoMVC-jQuery.
> AK: Make Utf16View::to_utf8() use simdutf fast path more often

- .github/actions/setup/action.yml
- AK/Platform.h
- Libraries/LibWeb/MediaCapabilitiesAPI/MediaCapabilities.h
- Meta/CMake/common_compile_options.cmake
This causes a build failure when building a clang module for LibWeb.
> LibWeb: Add missing WebIDL/Types include to MediaCapabilities.h

- AK/Error.cpp
- AK/Error.h
- AK/Format.cpp
- AK/Format.h
This commit makes windows errors store the code instead of being a formatted string literat. This will allow comparing against the error, and checkign what it is. The formatting is now done in the formatter, and moved to an implementation file to avoid polluting headers with windows.h.
> AK: Rework windows error types to store the code

- AK/Error.h
Previously the check for is_errno did not check if the error kind was syscall, which also set errno so that behavior was incorrect.
> AK: Fix error is_errno

- Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Libraries/LibWeb/HTML/Parser/HTMLTokenizer.cpp
- Libraries/LibWeb/HTML/Parser/HTMLTokenizer.h
Instead of using UTF-8 iterators to traverse the HTMLTokenizer input stream one code point at a time, we now do a one-shot conversion up front from the input encoding to a Vector<u32> of Unicode code points.
This simplifies the tokenizer logic somewhat, and ends up being faster as well, so win-win.
1.02x speedup on Speedometer 2.1
> LibWeb: Let HTMLTokenizer walk over code points instead of UTF-8

- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
- Libraries/LibWeb/DOM/Node.h
- Libraries/LibWeb/HTML/HTMLLIElement.cpp
- Libraries/LibWeb/HTML/HTMLLIElement.h
- Libraries/LibWeb/HTML/HTMLOListElement.cpp
- Libraries/LibWeb/HTML/HTMLOListElement.h
- Tests/LibWeb/Ref/expected/li-change-value-attribute-ref.html
- Tests/LibWeb/Ref/expected/ol-change-reversed-attribute-ref.html
- Tests/LibWeb/Ref/expected/ol-change-start-attribute-ref.html
- Tests/LibWeb/Ref/expected/ol-change-type-attribute-ref.html
- Tests/LibWeb/Ref/input/li-change-value-attribute.html
- Tests/LibWeb/Ref/input/ol-change-reversed-attribute.html
- Tests/LibWeb/Ref/input/ol-change-start-attribute.html
- Tests/LibWeb/Ref/input/ol-change-type-attribute.html
Testcases I wrote for #4442 exposed some invalidation bugs related to ordered lists that are already present on `master`. These are separate from the performance improvements and therefore can be fixed in an independent PR.
I'm not entirely happy with the changes to `Element::list_owner()`, but the alternatives I could come up with didn't seem better either.
> LibWeb: Fix missing layout invalidation for ordered lists

- Libraries/LibJS/Runtime/AbstractOperations.cpp
- Libraries/LibJS/Runtime/ArgumentsObject.cpp
- Libraries/LibJS/Runtime/ArgumentsObject.h
By following the spec to the letter, our mapped arguments objects ended up with many extra GC allocations:
- 1 extra Object for the internal [[ParameterMap]].
- 2 extra NativeFunctions for each mapped parameter accessor.
- 1 extra Accessor to hold the aforementioned NativeFunctions.
This patch removes all those allocations and lets ArgumentsObject model the desired behavior in custom C++ instead of using script primitives.
1.06x speedup on Speedometer's TodoMVC-jQuery.
> LibJS: Make mapped arguments objects way less allocation-happy

- Base/res/ladybird/about-pages/settings.html
- Base/res/ladybird/about-pages/settings/search.js
- Libraries/LibWebView/Settings.cpp
- Libraries/LibWebView/WebUI/SettingsUI.cpp
Currently, enabling search is a bit hokey. You have to click a checkbox to get the search engines to show up, then you have to click a drop down to select an engine. Let's go with a simpler approach; now you only have to interact with the drop down.
This also auto-disables autocomplete when search is disabled, as search suggestions cannot work in that case.
> LibWebView: Some search settings ergonomic improvements

- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
- Libraries/LibWeb/DOM/Node.cpp
- Libraries/LibWeb/DOM/Node.h
The play_or_cancel_animations_after_display_property_change() helper was being called by Node::inserted() and Node::removed_from() and then recursing into the shadow-including subtree.
This had quadratic complexity since inserted() and removed_from() are themselves already invoked recursively for everything in the shadow-including subtree.
Only one caller of this API actually needed the recursive behavior, so this patch moves that responsibility to the caller and puts the logic in style recomputation instead.
1.02x speedup on Speedometer's TodoMVC-jQuery.
> LibWeb: Avoid O(n^2) traversal in play-or-cancel-animations logic

- Libraries/LibWeb/Painting/Command.h
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Tests/LibWeb/Ref/expected/css/line-height-zero-ref.html
- Tests/LibWeb/Ref/input/css/line-height-zero.html
Fixes #3578
We can't ignore 0-height inline boxes and the painting command can't just give the rect of the inline box as its bounding rect since that box only cares about the font's ascent and descent, modified to match the `line-height`, but glyphs may extend beyond that.
For example, I'm pretty sure diacritics on capital letters extend outside that box, like for Ä, Ö or Ü.
They definitely would once you start stacking multiple diacritics.
Here's the spec that says that inline boxes should have their height calculated this way: https://drafts.csswg.org/css-inline-3/#inline-height
> LibWeb: Draw text even if it needs to go into a 0-size inline box

- Libraries/LibWeb/DOMURL/URLSearchParams.cpp
- Libraries/LibWeb/Infra/Strings.cpp
- Tests/LibWeb/CMakeLists.txt
- Tests/LibWeb/TestStrings.cpp
I noticed `Infra::code_unit_less_than` when looking at the IDB merge request, and remembered that it would be useful in URLSearchParams, so made a MR to the URL spec to adopt that. But turns out our implementation has a bug which made our URL test import crash when using that, so fix that.
...I've also noticed that our implementation of less than is not correct for Strings in LibJS either: https://github.com/LadybirdBrowser/ladybird/blob/096eed35cc8c3b635db28ab6407713add9981137/Libraries/LibJS/Runtime/Value.cpp#L2393 since it goes over code points instead of code units, but will make a follow up MR for that.
> LibWeb: Fix bug in Infra::code_unit_less_than

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Runtime/ArrayIterator.cpp
- Libraries/LibJS/Runtime/ArrayIterator.h
- Libraries/LibJS/Runtime/ArrayIteratorPrototype.h
- Libraries/LibJS/Runtime/Iterator.cpp
- Libraries/LibJS/Runtime/Iterator.h
- Libraries/LibJS/Runtime/MapIterator.cpp
- Libraries/LibJS/Runtime/MapIterator.h
- Libraries/LibJS/Runtime/MapIteratorPrototype.h
- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/SetIterator.cpp
- Libraries/LibJS/Runtime/SetIterator.h
- Libraries/LibJS/Runtime/SetIteratorPrototype.h
- Libraries/LibJS/Runtime/StringIterator.cpp
- Libraries/LibJS/Runtime/StringIterator.h
- Libraries/LibJS/Runtime/StringIteratorPrototype.h
- Libraries/LibJS/Tests/redefine-next-in-builtin-iterators.js
81b6a11 regressed correctness by always bypassing the `next()` method resolution for built-in iterators, causing incorrect behavior when `next()` was redefined on built-in prototypes. This change fixes the issue by storing a flag on built-in prototypes indicating whether `next()` has ever been redefined.
> LibJS: Disable optimization in IteratorNextUnpack if next() is redefined

- Documentation/BuildInstructionsLadybird.md
When using non-BFD linkers, something about our CMake setup causes visibility checks from GenerateExportHeader to fail when clang-scan-deps is not found.
> Documentation: Add clang-tools to the Ubuntu/Debian build instructions

- Libraries/LibWeb/HTML/Parser/HTMLToken.swift
- Libraries/LibWeb/HTML/Parser/HTMLTokenizer.swift
- Libraries/LibWeb/HTML/Parser/SpeculativeHTMLParser.swift
I was curious about the state of Swift in Ladybird and started looking through the repo.
I stumbled upon this small inconsistency in the copyright headers and thought I'd send a patch.
> LibWeb: fix copyright headers with inconsistent > sign

- Libraries/LibGC/ConservativeVector.h
- Libraries/LibGC/RootHashMap.h
- Libraries/LibGC/RootVector.h
- Libraries/LibJS/AST.h
- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibThreading/Thread.h
- Libraries/LibWeb/HTML/HTMLAnchorElement.h
**LibGC: Make destructors non-virtual where possible**
`ConservativeVector`, `RootVector` and `RootHashMap` are final types, and their base classes have a protected destructor, so when their destructor is called, the static and dynamic types will be the same (can't destruct them through a pointer to a base or derived class). Therefore, there is no need for a virtual destructor.
This fixes the newly introduced `-Wunnecessary-virtual-specifier` Clang warning (https://github.com/llvm/llvm-project/pull/131188).
**LibJS: Make generate_labelled_evaluation non-virtual if possible**
We don't override anything with definitions of this function in `SwitchStatement` and `LabelledStatement`. Also, we can make the `IterationStatement` abstract, there is no need to add a fallback error-generating stub …
> Fix `-Wunnecessary-virtual-specifier` Clang trunk warnings

- Tests/LibWeb/Layout/expected/flex/flex-column-reverse-constrained-wrap.txt
- Tests/LibWeb/Layout/expected/flex/flex-gap-between-items-and-lines.txt
- Tests/LibWeb/Layout/expected/flex/flex-item-on-row-with-intrinsic-size.txt
- Tests/LibWeb/Layout/expected/flex/flex-row-reverse-constrained-wrap.txt
- Tests/LibWeb/Layout/expected/flex/justify-content-on-min-content-with-gap.txt
- Tests/LibWeb/Layout/expected/flex/justify-content-space-between-single-item.txt
- Tests/LibWeb/Layout/input/flex/flex-column-reverse-constrained-wrap.html
- Tests/LibWeb/Layout/input/flex/flex-constrained-wrap-reverse.html
- Tests/LibWeb/Layout/input/flex/flex-gap-between-items-and-lines.html
- Tests/LibWeb/Layout/input/flex/flex-item-on-row-with-intrinsic-size.html
- Tests/LibWeb/Layout/input/flex/flex-optimization-cases.html
- Tests/LibWeb/Layout/input/flex/flex-row-reverse-constrained-wrap.html
- Tests/LibWeb/Layout/input/flex/justify-content-on-min-content-with-gap.html
- Tests/LibWeb/Layout/input/flex/justify-content-space-between-single-item.html
This adds doctypes to all the flexbox layout tests that didn't have them yet and rebaselines them.
The only thing that changed in all the expectation files is the size of the HTML element.
(it is always 600px tall at least in quirks mode, not so in standards mode)
Adding all the doctypes everywhere is done over multiple PRs to make it more manageable and easier to review.
> Meta: Add doctypes to some flex layout tests

- Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
- Tests/LibWeb/Ref/expected/svg/zero-area-mask-ref.html
- Tests/LibWeb/Ref/input/svg/zero-area-mask.html
Fixes #4699
We can't just push a save to the display list and then nope out of the function before restoring that.
> LibWeb: Do not forget to unapply empty masks

- Documentation/CSSGeneratedFiles.md
- Libraries/LibWeb/CSS/PseudoElements.json
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoElement.cpp
This is needed for CSS view transitions and it should allow us to construct pseudo-elements and build trees out of them.
It also takes care of the pseudo-element TODO:  that used to be here. 
It'll probably need more stuff for CSS to properly match these and all that, but that'll be easier to add once I'm actually building trees out of them for the view transitions.
> LibWeb: Add support for trees of pseudo-elements

- Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Libraries/LibWeb/HTML/FormAssociatedElement.h
- Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Libraries/LibWeb/HTML/HTMLFormElement.h
- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Libraries/LibWeb/HTML/HTMLSelectElement.cpp
- Libraries/LibWeb/HTML/HTMLSelectElement.h
- Libraries/LibWeb/HTML/HTMLSelectElement.idl
- Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-reportValidity.txt
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/constraints/form-validation-reportValidity.html
This implements the previously stubbed out `report_validity` method.
The specification is not very clear on how to exactly report the validity. For now, we bring the first visible invalid control into view and focus it. In the future, however, it would make sense to support more complex scenarios and be more aligned with the other implementations.
> LibWeb/HTML: Implement `report_validity`

- Libraries/LibWeb/HTML/XMLSerializer.cpp
- Tests/LibWeb/Text/expected/wpt-import/domparsing/innerhtml-01.txt
With this fix, the second test in domparsing/innerhtml-01.xhtml passes.
> LibWeb: Implement XML Char validation for Text node serialization

- AK/Function.h
- Meta/CMake/common_options.cmake
- Meta/CMake/lagom_options.cmake
- Meta/Lagom/CMakeLists.txt
We were already silencing it at the site of the delete call, but gcc in
distribution mode is more aggressive about inlining and still sees a
delete that it doesn't like.
With these two changes, a gcc-13 Distribution preset builds and passes tests locally on Ubuntu 24.04.
> AK: Silence -Wfree-nonheap-object more generally in Function for gcc

- Libraries/LibJS/Bytecode/Interpreter.cpp
This commit adds a fast path for putting values into a TypedArray of an integer type, when the value being put in is a double. This leads to a 6% speedup on JetStream/gcc-loops.js.
> LibJS: Add fast path for float to int put

- Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Libraries/LibWeb/CSS/CSSStyleProperties.cpp
- Libraries/LibWeb/CSS/CSSStyleValue.cpp
- Libraries/LibWeb/CSS/CSSStyleValue.h
- Libraries/LibWeb/CSS/Interpolation.cpp
- Libraries/LibWeb/CSS/Parser/Parser.cpp
- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/CSS/StyleComputer.h
- Libraries/LibWeb/CSS/StyleValues/GuaranteedInvalidStyleValue.h
- Libraries/LibWeb/CSS/StyleValues/PendingSubstitutionStyleValue.h
- Libraries/LibWeb/Forward.h
- Tests/LibWeb/Text/expected/css/var-in-margin-shorthand.txt
- Tests/LibWeb/Text/input/css/var-in-margin-shorthand.html
Description from the main commit. The rest are prep/tangential fixes.
---
Previously, we would just assign the UnresolvedStyleValue to each
longhand, which was completely wrong but happened to work if it was a
ShorthandStyleValue (because that's basically a list of "set property X
to Y", and doesn't care which property it's the value of).
For example, the included `var-in-margin-shorthand.html` test would:
1. Set `margin-top` to `var(--a) 10px`
2. Resolve it to `margin-top: 5px 10px`
3. Reject that as invalid
What now happens is:
1. Set `margin-top` to a PendingSubstitutionValue
2. Resolve `margin` to `5px 10px`
3. Expand that out into its longhands
4. `margin-top` is `5px` 🎉
In order to support this, `for_each_property_expanding_shorthands()` now
runs the callback for the shorthand too …
> LibWeb/CSS: Use "pending-substitution value" for cascading unresolved shorthands

- Meta/WPT.sh
This makes it easier to figure out when a given run started.
Outputs timestamps like `20250515105535` instead of `1747302935`. Not sure how useful this is to anyone other than me, but I do find it occasionally useful to be able to tell at a glance what date a given WPT run is from.
> Meta: Use human readable timestamp in WPT run folder name

- Libraries/LibWeb/DOM/CharacterData.cpp
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Node.cpp
- Libraries/LibWeb/DOM/Range.cpp
- Libraries/LibWeb/DOM/Range.h
- Libraries/LibWeb/DOM/Text.cpp
- Libraries/LibWeb/Layout/Viewport.h
- Tests/LibWeb/Text/expected/HTML/Window-find-mutations.txt
- Tests/LibWeb/Text/input/HTML/Window-find-mutations.html
Fixes 1 crash in WPT's `editing/crashtests` and adds 23 new passes in `editing`. No regressions in `dom/ranges`.
> LibWeb: Range and text search fixes

- Libraries/LibCore/Version.cpp
- Meta/WPT.sh
This was previously done by passing the `LADYBIRD_GIT_VERSION` environment variable to `wpt`, but this doesn't work in chunked mode.
> Meta: Ensure wptreport `browser_version` field is always populated

- .github/actions/setup/action.yml
- .github/workflows/js-benchmarks.yml
- .github/workflows/libjs-test262.yml
We were using both wget and curl arbitrarily; use curl exclusively since that is installed by default on our machines and containers. Fixes the js-benchmarks workflow.
> CI: Switch from wget to curl

- .github/actions/setup/action.yml
- .github/workflows/js-benchmarks.yml
- .github/workflows/libjs-test262.yml
For our js-benchmarks and libjs-test262 workflow runs, we already know that they're provisioned with these repositories and can skip adding the key and repo altogether.
> CI: Only add LLVM repository if it is missing

- Meta/CMake/common_options.cmake
This is better CMake hygiene to avoid leaking our try_compile specific library requirements into the rest of the build.
Fixes #4730
> CMake: Clear CMAKE_REQUIRED_LIBRARIES after blocks and arc tests

- AK/CMakeLists.txt
- AK/Random.cpp
- AK/Random.h
- Libraries/LibCrypto/SecureRandom.h
- Libraries/LibJS/Runtime/MathObject.cpp
This commit implements a high quality randomness source for AK/Random. This avoids the fallback to rand(). The LibJS math xoshiro128+ prng is now seeded with SecureRandom. A convenience get_secure_random method was added to SecureRandom to directly construct the requested type.
> AK/LibJS/LibCrypto: implement random for Windows

- Libraries/LibWeb/CSS/SelectorEngine.cpp
- Tests/LibWeb/Ref/expected/wpt-import/css/selectors/selectors-4/lang-000-ref.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-000.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-001.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-002.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-003.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-004.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-005.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-006.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-007.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-008.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-009.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-010.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-011.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-012.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-013.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-014.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-015.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-016.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-017.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-018.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-019.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-020.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-021.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-022.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-023.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-024.html
- Tests/LibWeb/Ref/input/wpt-import/css/selectors/selectors-4/lang-025.html
With this, we pass the 8 ref tests in css/selectors/selectors-4/ which previously failed. This is not technically a full implementation, as we are supposed to first canonicalize the language range and tag, but that will require downloading and processing the IANA language subtag registry:
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
That's significantly more work, and WPT doesn't seem to test any cases that require that, so we can leave it for now.
> LibWeb/CSS: Bring :lang() matching closer to spec

- .github/workflows/js-benchmarks.yml
It's not needed. This is primarily to reduce the number of places needed to be updated on the next clang rollout.
Benchmarks ran fine on my fork (up until the webhooks ofc):
https://github.com/trflynn89/ladybird/actions/runs/15049233245/job/42299552137
> CI: Do not install clang in the JS benchmarks workflow

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Runtime/Array.cpp
- Libraries/LibJS/Runtime/Array.h
- Libraries/LibJS/Runtime/ModuleNamespaceObject.cpp
- Libraries/LibJS/Runtime/ModuleNamespaceObject.h
- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Libraries/LibJS/Runtime/PropertyKey.h
- Libraries/LibJS/Runtime/ProxyObject.cpp
- Libraries/LibJS/Runtime/ProxyObject.h
- Libraries/LibJS/Runtime/ReflectObject.cpp
- Libraries/LibJS/Runtime/StringObject.cpp
- Libraries/LibJS/Runtime/StringObject.h
- Libraries/LibJS/Runtime/TypedArray.h
- Libraries/LibWeb/Bindings/PlatformObject.cpp
- Libraries/LibWeb/Bindings/PlatformObject.h
- Libraries/LibWeb/HTML/CrossOrigin/AbstractOperations.cpp
- Libraries/LibWeb/HTML/CrossOrigin/AbstractOperations.h
- Libraries/LibWeb/HTML/Location.cpp
- Libraries/LibWeb/HTML/Location.h
- Libraries/LibWeb/HTML/WindowProxy.cpp
- Libraries/LibWeb/HTML/WindowProxy.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
1.24x improvement on the following micro benchmark (MicroBench/object-keys.js):
```js
function f() {
var object = {};
for (let i = 0; i < 100; i++) object["k" + i] = i;
for (var i = 0; i < 500_000; i++) {
Object.keys(object);
}
}
f();
```
> LibJS+LibWeb: Return Vector<PropertyKey> from internal_own_property_keys

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Runtime/Array.cpp
- Libraries/LibJS/Runtime/Array.h
- Libraries/LibJS/Runtime/ModuleNamespaceObject.cpp
- Libraries/LibJS/Runtime/ModuleNamespaceObject.h
- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Libraries/LibJS/Runtime/PropertyKey.h
- Libraries/LibJS/Runtime/ProxyObject.cpp
- Libraries/LibJS/Runtime/ProxyObject.h
- Libraries/LibJS/Runtime/ReflectObject.cpp
- Libraries/LibJS/Runtime/StringObject.cpp
- Libraries/LibJS/Runtime/StringObject.h
- Libraries/LibJS/Runtime/TypedArray.h
- Libraries/LibWeb/Bindings/PlatformObject.cpp
- Libraries/LibWeb/Bindings/PlatformObject.h
- Libraries/LibWeb/HTML/CrossOrigin/AbstractOperations.cpp
- Libraries/LibWeb/HTML/CrossOrigin/AbstractOperations.h
- Libraries/LibWeb/HTML/Location.cpp
- Libraries/LibWeb/HTML/Location.h
- Libraries/LibWeb/HTML/WindowProxy.cpp
- Libraries/LibWeb/HTML/WindowProxy.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
This reverts #4733.
This caused a large regression in [this WPT run](https://wpt.fyi/results/?diff&filter=ADC&run_id=5186203056078848&run_id=4830991476850688)
CC: @kalenikaliaksandr
> Revert "LibJS+LibWeb: Return Vector<PropertyKey> from internal_own_property_keys"

- Libraries/LibWeb/Layout/TextNode.cpp
- Tests/LibWeb/Layout/expected/text-collapse-inside-contenteditable.txt
- Tests/LibWeb/Layout/input/text-collapse-inside-contenteditable.html
- Tests/LibWeb/Text/expected/selectionchange-event.txt
- Tests/LibWeb/Text/input/selectionchange-event.html
This condition no longer seems to be necessary for anything, and it caused newlines to not render correctly in editable nodes.
|--|--|
| ![image](https://github.com/user-attachments/assets/71014966-f9ad-49d2-a306-38b929c0cda3) | ![image](https://github.com/user-attachments/assets/2a024862-2ac8-45be-a84c-214e294c7c46) |
Screenshots show the result for this snippet:
```html
<div contenteditable>abc
def</div>
```
> LibWeb: Do not override whitespace handling for editable elements

- Libraries/LibMedia/Color/ColorPrimaries.cpp
Small addition of BT601 primaries conversion. This allows us to play video from ChatGPT loader ([https://persistent.oaistatic.com/canvas/loop-swirl.mp4](https://persistent.oaistatic.com/canvas/loop-swirl.mp4))
> LibMedia: Implement conversion of BT601 primaries

- Libraries/LibWeb/CMakeLists.txt
- Libraries/LibWeb/CSS/CSSPageRule.cpp
- Libraries/LibWeb/CSS/CSSPageRule.h
- Libraries/LibWeb/CSS/PageSelector.cpp
- Libraries/LibWeb/CSS/PageSelector.h
- Libraries/LibWeb/CSS/Parser/Helpers.cpp
- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
- Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/cssom/cssom-pagerule.txt
- Tests/LibWeb/Text/input/wpt-import/css/cssom/cssom-pagerule.html
Most of the diff here is moving code around. I managed to forget about the FIXME when I first implemented `@page`, otherwise I would have put things in the right place to begin with. :sweat_smile:
> LibWeb/CSS: Implement CSSPageRule.setSelectorText()

- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Tests/LibWeb/Layout/expected/block-and-inline/negative-margin-with-padding.txt
- Tests/LibWeb/Layout/input/block-and-inline/negative-margin-with-padding.html
Originally part of a fix in 15103d172c2a4279c611d8a9d6262e15d3a3351e, it appears that this is no longer necessary and received a better fix in a more recent commit. Resolves a visual regression with the ACID3 test.
|--|--|
| ![image](https://github.com/user-attachments/assets/0c4ca378-a32d-4890-b614-5d3604b717a4) | ![image](https://github.com/user-attachments/assets/63081f8f-cddb-4d39-bb97-04b3823fd383) |
> LibWeb: Fix visual regression in ACID3 test

- Meta/Lagom/CMakeLists.txt
As shown below, before it didn't actually matter on Windows if you annotated or not as `set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)` makes all targets export by default.
Now that we explicitly turn off `WINDOWS_EXPORT_ALL_SYMBOLS` for targets that set the `EXPLICIT_SYMBOL_EXPORT` flag, forgetting to annotate will cause link-time errors, which is what already happens on Unix.
So now all platforms have consistent explicit export symbol behaviour wrt annotation requirements.
> Meta: Enforce symbol annotation for EXPLICIT_SYMBOL_EXPORT on Windows

- Libraries/LibWeb/DOM/EditingHostManager.cpp
- Libraries/LibWeb/DOM/EditingHostManager.h
- Libraries/LibWeb/DOM/InputEventsTarget.h
- Libraries/LibWeb/Editing/CommandNames.h
- Libraries/LibWeb/Editing/Commands.cpp
- Libraries/LibWeb/Editing/ExecCommand.cpp
- Libraries/LibWeb/Editing/Internal/Algorithms.cpp
- Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Libraries/LibWeb/HTML/FormAssociatedElement.h
- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Libraries/LibWeb/Page/EventHandler.cpp
- Libraries/LibWeb/UIEvents/InputTypes.h
- Libraries/LibWeb/UIEvents/KeyCode.h
- Tests/LibWeb/Text/expected/Editing/execCommand-preserveWhitespace.txt
- Tests/LibWeb/Text/input/Editing/execCommand-preserveWhitespace.html
+2053 WPT subtest passes. Some regressions in `editing/plaintext-only` that I'm going to look at in a new PR.
**WPT changes compared to master**
| Suite | Results |
|--|--|
| `editing/other` | +1163 passes, -4 crashes |
| `editing/plaintext-only` | -61 passes |
| `editing/run` | +10 passes |
| `editing/whitespaces` | +28 passes |
| `input-events` | +913 passes |
> LibWeb: Start integrating the editing API with user input

- Libraries/LibWeb/Bindings/AgentType.h
- Libraries/LibWeb/Bindings/MainThreadVM.h
- Libraries/LibWeb/HTML/DedicatedWorkerGlobalScope.h
- Libraries/LibWeb/HTML/EmbedderPolicy.h
- Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.cpp
- Libraries/LibWeb/HTML/SharedWorkerGlobalScope.cpp
- Libraries/LibWeb/HTML/SharedWorkerGlobalScope.h
- Libraries/LibWeb/HTML/Worker.cpp
- Libraries/LibWeb/HTML/WorkerAgentParent.cpp
- Libraries/LibWeb/HTML/WorkerAgentParent.h
- Libraries/LibWeb/HTML/WorkerGlobalScope.h
- Libraries/LibWeb/Page/Page.h
- Libraries/LibWeb/Worker/WebWorkerServer.ipc
- Services/WebWorker/CMakeLists.txt
- Services/WebWorker/ConnectionFromClient.cpp
- Services/WebWorker/ConnectionFromClient.h
- Services/WebWorker/Forward.h
- Services/WebWorker/WorkerHost.cpp
- Services/WebWorker/WorkerHost.h
Also push the onconnect event for the inital connection.
This still doesn't properly handle sending an onconnect event to a
pre-existing SharedWorkerGlobalScope with the same name for the same
origin, but it does give us a lot of WPT passes in the SharedWorker
category.
Running a full WPT run in parallel with `./Meta/WPT.sh run --parallel-instances 0 --log-wptreport expectations.json --log-wptscreenshot expectations.db` on master and this branch gave me the following:
master:
```
Total tests run: 59328
Ran as expected: 24648
Skipped: 0
Errored unexpectedly: 3635
Unexpected subtest results: 0
Longest run time: 6105.6s
```
this branch:
```
Total tests run: 59328
Ran as expected: 24852
Skipped: 0
Errored unexpectedly: 3633
Unexpected subtest results: 0
Longest run time: 5864.3s
```
@tcl3 is …
> LibWeb+WebWorker: Create SharedWorkerGlobalScope for Shared Workers 

- Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
This seems to have been broken for a while.
> LibWas: Unbreak compilation with `WASM_TRACE_DEBUG` enabled

- Services/RequestServer/ConnectionFromClient.cpp
Per [the curl docs](https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html), passing an empty string to CURLOPT_ACCEPT_ENCODING will automatically set the value with the encodings that curl supports.
The previous version broke for me, since my installed build of curl doesn't have brotli enabled, causing Ladybird to request an encoding that it couldn't decode
> RequestServer: Leave Accept-Encoding up to curl

- Libraries/LibWeb/DOM/Slottable.cpp
- Libraries/LibWeb/DOM/Slottable.h
- Libraries/LibWeb/HTML/HTMLSlotElement.cpp
- Tests/LibWeb/Text/expected/wpt-import/shadow-dom/slots-fallback-in-document.txt
- Tests/LibWeb/Text/expected/wpt-import/shadow-dom/slots-fallback.txt
- Tests/LibWeb/Text/expected/wpt-import/shadow-dom/slots-outside-shadow-dom.txt
- Tests/LibWeb/Text/expected/wpt-import/shadow-dom/slots.txt
- Tests/LibWeb/Text/input/wpt-import/shadow-dom/resources/shadow-dom.js
- Tests/LibWeb/Text/input/wpt-import/shadow-dom/slots-fallback-in-document.html
- Tests/LibWeb/Text/input/wpt-import/shadow-dom/slots-fallback.html
- Tests/LibWeb/Text/input/wpt-import/shadow-dom/slots-outside-shadow-dom.html
- Tests/LibWeb/Text/input/wpt-import/shadow-dom/slots.html
Improving our support for slot elements (trying to investigate a good way of fixing the optimization of https://github.com/LadybirdBrowser/ladybird/blob/ea7709210054c858465298d8e558e98955d06383/Libraries/LibWeb/DOM/Slottable.cpp#L185 without ruining performance, so building up some tests in the area).
The code here is very awkward, I am trying to think of better types to use instead of `Slottable` for the `find_.*slottable` APIs
> LibWeb: Implement and use 'find flattened slottables'

- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Tests/LibWeb/Ref/expected/css-custom-prop-fallback-ref.html
- Tests/LibWeb/Ref/input/css-custom-prop-fallback.html
This allows the existing fallback logic in `Parser::expand_variables` to run when a CSS-wide keyword is encountered.
Fixes #1157
> LibWeb+Tests: Continue variable expansion if CSS-wide keyword is parsed

- Libraries/LibWeb/CSS/MediaQuery.h
- Libraries/LibWeb/CSS/StyleProperty.h
- Libraries/LibWeb/Forward.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSEnums.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSKeyword.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMediaFeatureID.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
This has a noticeable effect on `MediaFeature`. The others I haven't observed a difference for but it also doesn't hurt.
> LibWeb/CSS: Specify sizes of generated enums

- CMakePresets.json
Make them work with the new preset names, and hide platform-specific
presets on platforms that don't support them.
> CMake: Rework Windows build and test presets

- CONTRIBUTING.md
The current url links to the same markdown file
> Documentation: Fix Ladybird's documentation url

- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Tests/regress/add-property-with-the-same-from-getter-in-prototype.js
Fixes a bug that reproduces with the following steps:
1. Create an object with a getter for property "a" in its prototype, where the getter adds an "a" property to the object itself.
2. Call the "a" getter in a loop for the first time. This triggers caching of metadata indicating that the "a" property is located in the prototype chain.
3. Call the "a" getter in a loop for the second time. Oops, the cache says the getter is in the prototype chain, but the object now also has its own "a" property that was added by the first getter call.
> LibJS: Skip caching get_by_id() if object's shape is changed by a getter

- Libraries/LibIPC/TransportSocket.cpp
- Libraries/LibIPC/TransportSocket.h
- Libraries/LibWeb/HTML/MessagePort.cpp
- Libraries/LibWeb/HTML/MessagePort.h
- Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Libraries/LibWeb/HTML/StructuredSerialize.h
- Libraries/LibWeb/HTML/StructuredSerializeTypes.h
- Libraries/LibWeb/Streams/AbstractOperations.cpp
- Libraries/LibWeb/Streams/AbstractOperations.h
- Libraries/LibWeb/Streams/ReadableStream.cpp
- Libraries/LibWeb/Streams/ReadableStream.h
- Libraries/LibWeb/Streams/TransformStream.cpp
- Libraries/LibWeb/Streams/TransformStream.h
- Libraries/LibWeb/Streams/WritableStream.cpp
- Libraries/LibWeb/Streams/WritableStream.h
- Tests/LibWeb/Text/expected/wpt-import/html/infrastructure/safe-passing-of-structured-data/window-postmessage.window.txt
- Tests/LibWeb/Text/expected/wpt-import/html/webappapis/structured-clone/structured-clone.any.txt
- Tests/LibWeb/Text/expected/wpt-import/streams/transferable/readable-stream.txt
- Tests/LibWeb/Text/expected/wpt-import/streams/transferable/transform-stream.txt
- Tests/LibWeb/Text/expected/wpt-import/streams/transferable/writable-stream.txt
- Tests/LibWeb/Text/input/wpt-import/streams/transferable/readable-stream.html
- Tests/LibWeb/Text/input/wpt-import/streams/transferable/resources/helpers.js
- Tests/LibWeb/Text/input/wpt-import/streams/transferable/transform-stream.html
- Tests/LibWeb/Text/input/wpt-import/streams/transferable/writable-stream.html
For stream transfer to work, this requires `MessagePort::disentangle` to flush pending messages before the transport socket is closed.
Fixes #3294
> LibWeb: Implement `ReadableStream`, `WritableStream` and `TransformStream` transfer

- Libraries/LibWeb/CSS/CSSDescriptors.cpp
- Libraries/LibWeb/CSS/CSSStyleProperties.cpp
- Libraries/LibWeb/CSS/Parser/Tokenizer.cpp
- Libraries/LibWeb/CSS/SelectorEngine.cpp
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/StyleElementUtils.cpp
- Libraries/LibWeb/Fetch/Infrastructure/NoSniffBlocking.cpp
- Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
- Libraries/LibWeb/HTML/HTMLElement.cpp
- Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Libraries/LibWeb/HTML/Navigable.cpp
- Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Libraries/LibWeb/HTML/XMLSerializer.cpp
- Libraries/LibWeb/Infra/Strings.cpp
- Libraries/LibWeb/Infra/Strings.h
- Libraries/LibWeb/WebGL/WebGL2RenderingContext.cpp
- Libraries/LibWeb/WebGL/WebGLRenderingContext.cpp
- Libraries/LibWeb/XHR/XMLHttpRequest.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSMediaFeatureID.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
- Services/WebContent/ConnectionFromClient.cpp
Which has an optmization if both size of the string being passed through are FlyStrings, which actually ends up being the case in some places during selector matching comparing attribute names. Instead of maintaining more overloads of
Infra::is_ascii_case_insensitive_match, switch everything over to equals_ignoring_ascii_case instead.
> LibWeb: Prefer using equals_ignoring_ascii_case

- Libraries/LibWeb/CSS/Selector.cpp
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Tests/LibWeb/Ref/expected/css-case-insensitive-html-attributes-selector-ref.html
- Tests/LibWeb/Ref/expected/css-tag-selector-case-sensitivity-html.html
- Tests/LibWeb/Ref/input/css-case-insensitive-html-attributes-selector.html
- Tests/LibWeb/Ref/input/css-tag-selector-case-sensitivity-html.html
This seems to fix many issues on nofluffjobs.com.
Fixes #4793.
> LibWeb/CSS: use case insensitive attribute name in ancestor hash

- .gitignore
- CMakePresets.json
- Meta/__init__.py
- Meta/ladybird.py
- Toolchain/__init__.py
WIP draft of the python script that can eventually replace `ladybird.sh`. There is Windows support, although there won't be a preset that will actually build successfully until https://github.com/LadybirdBrowser/ladybird/pull/4707 is sorted out.
To start there is just the `build`, but I will add the rest in subsequent commits, just putting up now so others can see it and give early feedback.
I also haven't fully tested configure yet on all platforms. So far, I've only done a full clean build and then ran `ctest` on my Mac Book as it is the fastest of my machines to build everything. A few JS/Wasm failures, so I'm probably missing something during config. For Linux/Windows so I just built with presets that were already configured.
So I'll still need to fix the JS/Wasm stuff and do full …
> Meta: Add ladybird.py project helper script

- Libraries/LibWeb/HTML/HTMLObjectElement.cpp
- Tests/LibWeb/Layout/expected/object-fallback.txt
- Tests/LibWeb/Layout/input/object-fallback.html
We were previously only testing for network errors, which includes e.g. DNS resolution and connection errors. It does not include e.g. HTTP 404 responses, which is exercised by Acid 2.
Acid 2 before this change (on macOS):
After this change:
> LibWeb: Handle non-OK network responses in `<object>` elements

- .github/actions/cache-save/action.yml
- .github/workflows/nightly-windows.yml
This job uses the windows_ci_ninja preset to build just the components and unit tests that are known to work with ClangCL on the amd64-pc-windows-msvc target triple.
As a nightly job, its failures are non-blocking for any PRs, though they should be fixed eventually or the job will get turned off by email-annoyed maintainers.
Hilariously, this job takes 1h10m to build vcpkg dependencies, and less than 5 to build and run AK unit tests. As far as I could tell, windows and ccache are not friends. When we get serious about windows, this will become a build time bottleneck that we'll need a solution for.
Rather than make a gigantic mess of lagom-template.yml, I moved the MVP CI invocations into their own pipeline.
> CI: Add nightly Windows CI job

- Meta/ladybird.py
* Use type hints
* Don't use `kwargs` as the one-and-only parameter everywhere
* Fix some bugs, e.g. `./Meta/ladybird.py run ladybird.org` previously did not work
* Remove all pyright warnings
* Format with `black`
* Minor style changes
> Meta: Some cleanup of ladybird.py

- Libraries/LibWeb/DOM/Document.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/dom/documents/dom-tree-accessors/nameditem-01.txt
- Tests/LibWeb/Text/input/wpt-import/html/dom/documents/dom-tree-accessors/nameditem-01.html
When an element's ID is removed we only want to remove it from `m_potentially_named_elements` if it is not also considered a potentially named element due to it's name content attribute.
Gains us atleast [one extra pass in WPT](http://wpt.live/html/dom/documents/dom-tree-accessors/nameditem-01.html)
> LibWeb: Be less aggressive in marking elements as not being named

- Libraries/LibWeb/CSS/CSSStyleValue.cpp
In a recent refactor of font styles (#4552), the new FontStyleStyleValue was introduced; however, the `to_font_slope()` function was not changed to understand this new type. When it tries to convert such a font style to a keyword, it fails. We then rendered the wrong font-style.
This bug caused text to render with the wrong font style, for example `font-style: italic` simply didn't render italic unless the font itself was italic.
*also* Fixes #4808
> LibWeb: Fix font-style to slope conversion

- Tests/LibWeb/TestConfig.ini
It is extremely slow on macOS.
> Tests: Disable XMLHttpRequest-override-mimetype-blob.html for now

- Libraries/LibWeb/Layout/Node.cpp
- Libraries/LibWeb/Layout/TreeBuilder.cpp
- Tests/LibWeb/Layout/expected/block-and-inline/block-inside-inline.txt
- Tests/LibWeb/Layout/input/block-and-inline/block-inside-inline.html
When restructuring a block node inside an inline parent, if the
nearest block ancestor is `display: inline-block`, ensure that
the generated anonymous wrappers also have `display: inline-block`.
This fixes layout issues with block elements nested
inside inline-block elements.
To reproduce:
```
This sentence
<div style="display: inline-block;">
<span>
<div style="display: block;"></div>
</span>
</div> should be in the same line as the above sentence.
```
> LibWeb: Prevent line break when block node is inside inline-block

- Meta/ladybird.py
Double quote strings nested within fstrings are invalid syntax and was causing the following error when running ladybird.py:
```
File "Meta/ladybird.py", line 397
print_process_stderr(e, f"Unable to build Ladybird {f"target {target}" if target else "project"}")
^^^^^^
SyntaxError: f-string: expecting '}'
```
> Meta: Avoid doublequote strings nested in fstrings in ladybird.py

- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-fonts/format-specifiers-variations.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-fonts/format-specifiers-variations.html
"format(woff-variations)" and pals are supposed to expand like so:
"format(woff) tech(variations)".
However, since we don't support tech() yet, this patch just adds a small
hack where we still treat "woff-variations" as "woff" so that fonts
load and get used, even if we don't make use of the variations yet.
Makes the monospace font load on https://terminal.shop/
BEFORE:
AFTER:
> LibWeb: Handle format(woff-variations) etc in @font-face src values

- Libraries/LibWeb/HTML/MessagePort.cpp
- Tests/LibWeb/Crash/wpt-import/streams/piping/crashtests/cross-piping.html
Otherwise, the remote end believes it is still entangled and may try to access its own (now null) remote port. This fixes a crash in WPT.
> LibWeb: Disentangle both ends of a MessagePort at once

- Libraries/LibCore/Socket.cpp
- Libraries/LibCore/Socket.h
- Libraries/LibIPC/TransportSocket.cpp
This seems to work on both linux and macOS.
With this we can stop trying to transfer 640 fds per message, and just rely on TransferSocket's send thread to keep sending fds 64 at a time in `sendmsg` calls with empty iov entries.
> LibIPC: Transfer extra fds in empty payload messages

- Libraries/LibWeb/HTML/Location.idl
This is quite a frequent FIXME log on quite a few sites which
does not serve much value at this stage. So instead of marking it
with a FIXME extended IDL attribute, let's just comment it out.
> LibWeb/HTML: Don't log FIXME messages for location.ancestorOrigins 

- AK/Error.h
- Libraries/LibJS/Runtime/DateConstructor.cpp
- Libraries/LibJS/Runtime/DateParser.h
- Libraries/LibJS/Tests/builtins/Date/Date.parse.js
- Libraries/LibJS/Tests/builtins/Date/Date.parse.nonStandard.js
Fixes #2625 
- Compatibility with Mozilla Firefox (134.0.1) and Chromium (131.0.6778.264), where they agree
- When hitting incompatibilities between browsers, choose the more sane one
- Add support for [ES timezone offset](https://tc39.es/ecma262/#sec-time-zone-offset-strings), including timezone nanoseconds (not in Firefox or Chrome at this time)
How? `RegexParser` (based on `GenericLexer`):
- Tries to parse ES date string with ISO8601 extensions.
- If that fails, continues with a greedy shallow parse, looking for all sorts of date parts. 
- Minor adjustments to the `Date.parse.js` unit tests, to bring them into compliance.
Bonus: added `AK::ErrorOr::value_or` convenience method in the spirit of `Optional::value_or`. Easy to remove from PR if there are objections :]m
> LibJS: Add support in Date.parse for non-standard date strings

- Libraries/LibCore/StandardPaths.cpp
- Libraries/LibCore/StandardPaths.h
- Libraries/LibGfx/CMakeLists.txt
- Libraries/LibGfx/Font/FontDatabase.cpp
- Libraries/LibGfx/Font/FontDatabase.h
- Libraries/LibGfx/Font/GlobalFontConfig.cpp
- Libraries/LibGfx/Font/GlobalFontConfig.h
- Libraries/LibGfx/Font/PathFontProvider.cpp
- Libraries/LibWebView/Plugins/FontPlugin.cpp
first timer here.
i run a rather obscure linux and none of the fallback fonts that are listed in update_generic_fonts are present on my system. my initial clue was to try to enable fontconfig, but result was fruitless. eventually after a bunch of printf (or in this case outln) debugging i figured out that the issues was that ladybird was not able to load the fonts that fontconfig was resolving because ladybird was not trying look into directories in which fontconfig has found fonts.
this might be related to #4601
i moved font_directories from StandardPaths to FontDatabase because it didn't seem like it would be appropriate to call to fontconfig funcs from within the LibCore (based on my brief observations of how everything is structured).
i'm not 100% confident that FontDatabase is the …
> LibCore+LibGfx: Rely on fontconfig(if enabled) for font directory resolution

- AK/Format.cpp
- AK/Format.h
This commit changes `AK::TypeErasedParameter` to store integer,
floating-point and string types as well as characters and booleans
directly instead of through a type-erased `void const*`.
This is advantageous for binary size:
- The compiler no longer needs to push both the parameter value and a
pointer to it to the stack (which contains the argument array);
storing just the value is enough.
- Instead of instantiating `__format_value` for these types and taking
its address (which generates a GOT entry and an ADRP+LDR pair in
assembly), we just store a constant `TypeErasedParameter::Type` value.
- The biggest saving comes from the fact that we used to instantiate a
distinct `__format_value` for each length of string literal. For
LibJS, this meant 69 different functions! We can now just …
> AK: Decrease the binary size overhead of formatting

- Libraries/LibCore/MimeData.cpp
- Tests/LibCore/CMakeLists.txt
- Tests/LibCore/TestLibCoreMimeType.cpp
Fix and tests for text/plain issue on .shellrc and CMakeList.txt lines folded in LibCore/MimeType.cpp
fixes #4859
> LibCore: MimeType for text/plain has base names with lines folded

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/Fetch/Infrastructure/NetworkPartitionKey.cpp
- Libraries/LibWeb/HTML/BrowsingContext.cpp
- Libraries/LibWeb/HTML/HTMLElement.cpp
- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Libraries/LibWeb/HTML/HTMLSelectElement.cpp
- Libraries/LibWeb/HTML/Navigable.cpp
- Libraries/LibWeb/HTML/Scripting/Environments.h
- Libraries/LibWeb/HTML/Scripting/SerializedEnvironmentSettingsObject.cpp
- Libraries/LibWeb/HTML/Scripting/SerializedEnvironmentSettingsObject.h
- Libraries/LibWeb/HTML/Window.cpp
This matches the definition in the spec, and is also a step towards removing the default constructor of URL::Origin.
Motivated by trying to change URL::Origin to use a nonce for opaque origins.
> LibWeb: Make Environment's top level origin nullable

- .github/workflows/lint-commits.yml
- .github/workflows/merge-conflict-labeler.yml
- .github/workflows/notes-push.yml
- .github/workflows/stale.yml
The people over at Blacksmith.sh have generously offered usage of their runners for our organization, so let's try to switch over some simple workflows. The runners should be drop-in replacements.
> CI: Switch over some workflows to Blacksmith.sh runners

- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Libraries/LibWeb/Layout/FormattingContext.h
- Tests/LibWeb/Layout/expected/block-and-inline/float-fits-exactly.txt
- Tests/LibWeb/Layout/expected/block-and-inline/float-nested-under-eachother.txt
- Tests/LibWeb/Layout/expected/block-and-inline/float-stress-1.txt
- Tests/LibWeb/Layout/input/block-and-inline/float-fits-exactly.html
- Tests/LibWeb/Layout/input/block-and-inline/float-nested-under-eachother.html
We used to take the maximum right margin of any containing box, but we want to subtract the entire right margin. This yielded incorrect results for the intrusion of right floats which in turn gave invalid/inconsistent values which are used in calculating the available width.
For this change I had to rebaseline one existing test, but I think it's more correct now (before/after):
As you can see in the before image there was easily enough space for both the text and other float box, but it wasn't being utilised because of the wrong intrusion calculation for the big right float.
> LibWeb: Correct the calculation for right float intrusion

- .github/actions/cache-restore/action.yml
- .github/actions/cache-save/action.yml
- .github/workflows/js-artifacts.yml
- .github/workflows/lagom-template.yml
- .github/workflows/libjs-test262.yml
- .github/workflows/nightly-windows.yml
Their cache action only works on their runners. For jobs that run on other runners, we have use the default cache action. At least until they update their cache product to work or fallback on other runners.
> CI: Use Blacksmith cache action only on Blacksmith runners

- .github/actions/setup/action.yml
Swift jobs were failing a test due to the llvm-symbolizer not being
available in the default location next to the clang binary. swift.org
toolchains don't ship this tool, so LSAN suppressions were not being
applied, failing TestWOFF2.
This was hard to reproduce locally, because I have always had a set of
alternatives set up for the full suite of LLVM tools on my machine.
Also bump the snapshot version. No idea why the April snapshot didn't work on macOS. Let's use the latest.
> CI: Changes to make Swift CI Pass

- Tests/LibCore/CMakeLists.txt
- Tests/LibCore/TestLibCoreMappedFile.cpp
- Tests/LibCore/TestLibCoreStream.cpp
These tests previously only ran on SerenityOS. They needed test input location changes. The Stream tests also needed to explicitly set SO_REUSEADDR for the tcp servers.
> Tests: Re-enable TestLibCoreMappedFile and TestLibCoreStream

- Libraries/LibWeb/Animations/Animation.cpp
- Libraries/LibWeb/Animations/KeyframeEffect.cpp
- Libraries/LibWeb/CSS/CSSTransition.cpp
- Libraries/LibWeb/CSS/CSSTransition.h
- Libraries/LibWeb/CSS/ComputedProperties.cpp
- Libraries/LibWeb/CSS/ComputedProperties.h
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
`start_needed_transitions()` decides which animations need to be started
based on previous and current style property values. Before this change,
we were using the style value without animations applied as the
"current" value. This caused issues such as starting a new transition
from the animation’s end value when an ongoing animation was
interrupted.
Before:
After:
Page I used for testing:
```html
<html>
<body>
<div id="sq"></div>
<style>
#sq {
width: 100px;
height: 100px;
background: #000;
transition: transform 2s;
margin: 200px;
}
#sq:hover {
transform: scale(5);
}
</style>
</body>
</html>
```
> LibWeb: Fix glitchy CSS transitions

- Libraries/LibWeb/WebAudio/AudioParam.cpp
- Libraries/LibWeb/WebAudio/AudioScheduledSourceNode.cpp
- Tests/LibWeb/TestConfig.ini
- Tests/LibWeb/Text/expected/wpt-import/webaudio/the-audio-api/the-audioparam-interface/audioparam-nominal-range.txt
This allows us to browse https://pierre.co/ instead of being navigated to error screen.
> LibWeb: Print FIXME instead of throwing NotSupportedError in WebAudio

- Meta/ladybird.py
For example, the "test" and "vcpkg" build commands do not.
Fixes #4913
> Meta: Don't assume all build commands have a target

- .github/actions/cache-restore/action.yml
The way we echo the cache keys for output variables strips these quotes.
So when we save the caches at the end of CI, the keys are sans quotes.
This patch adds an extra cache restore key without quotes to allow jobs
to fetch their own caches again. This will become moot once all runners
are able to use the Blacksmith cache action.
> CI: Add a quoteless cache restore key for GitHub runners

- Libraries/LibWeb/Animations/Animatable.cpp
- Libraries/LibWeb/Animations/Animatable.h
- Libraries/LibWeb/CSS/CSSTransition.cpp
- Libraries/LibWeb/CSS/CSSTransition.h
- Libraries/LibWeb/CSS/StyleComputer.cpp
We already had all necessary things for pseudo elements support in place except ability to save transition properties in Animatable. This commit adds the missing part.
> LibWeb: Implement CSS transitions support for pseudo elements

- Libraries/LibWeb/HTML/RenderingThread.cpp
Not cleaning these up by rejecting or resolving the promise causes the main thread to try to reject them at EventLoop::exit() time.
If the RenderThread has already been destroyed by then, we get into use-after-free territory and segfault.
> LibWeb: Clean up main thread promise when exiting RenderingThreads

- Libraries/LibGfx/CMakeLists.txt
- Meta/CMake/common_options.cmake
This requires a fix for the libfuzzer enabled build to not try to make executables for try_compile, as our try_compiles will get a duplicate main error.
> LibGfx: Add a strict CMake check for the libpng apng patch

- Libraries/LibGfx/CMakeLists.txt
This header file is never included by any other headers, and including it would require adding the fontconfig include paths to the swift interop header generation, which is not desirable.
> CMake: Exclude GlobalFontConfig.h from autogenerated clang module

- Libraries/LibWeb/CSS/StyleComputer.cpp
- Tests/LibWeb/Text/expected/WebAnimations/cancel-animation.txt
- Tests/LibWeb/Text/input/WebAnimations/cancel-animation.html
"none" value should be interpreted as "no animation" to trigger the path that cancels previous animation if it exists.
> LibWeb: Cancel previous animation if new animation-name is "none"

- AK/Base64.cpp
- Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.fromBase64.js
- Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.prototype.setFromBase64.js
- vcpkg.json
This PR includes a couple of package updates since updating simdutf busts our vcpkg cache anyways. The libjxl update was missed last time I updated packages, it includes a fix made by us.
> AK: Update simdutf and remove some now-unnecessary workarounds for base64

- Libraries/LibGfx/CMakeLists.txt
- Libraries/LibGfx/Filter.cpp
- Libraries/LibGfx/Filter.h
- Libraries/LibGfx/FilterImpl.h
- Libraries/LibGfx/Painter.h
- Libraries/LibGfx/PainterSkia.cpp
- Libraries/LibGfx/PainterSkia.h
- Libraries/LibGfx/SkiaUtils.cpp
- Libraries/LibGfx/SkiaUtils.h
- Libraries/LibWeb/CSS/ComputedValues.h
- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.cpp
- Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.h
- Libraries/LibWeb/HTML/Canvas/CanvasState.h
- Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Libraries/LibWeb/Layout/Node.cpp
- Libraries/LibWeb/Painting/Command.h
- Libraries/LibWeb/Painting/DisplayList.cpp
- Libraries/LibWeb/Painting/DisplayList.h
- Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Libraries/LibWeb/Painting/DisplayListPlayerSkia.h
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.h
- Libraries/LibWeb/Painting/PaintableBox.cpp
- Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
- Libraries/LibWeb/Painting/StackingContext.cpp
This is the first PR in a series aimed at implementing SVG filter support. This PR touches on many areas, so I wanted to get it merged first to avoid too many merge conflicts later on.
Until now, with CSS and canvas filters, we only needed linear combinations of filters, represented as a `Vector<Gfx::Filter>` when passed to the painter, which were then converted into one merged Skia filter with each paint. However, this approach is not suitable for SVG filters, which behave in a graph-like manner (https://www.w3.org/TR/filter-effects-1/).
There are two options I can think of for implementing filter graphs:
1) Make a `Gfx::Filter` behave like a graph and convert it to the equivalent Skia filter graph on each paint.
2) Make `Gfx::Filter` a wrapper for Skia filter graphs, as is done for …
> LibGfx+LibWeb: Prepare Gfx::Filter for SVG Filters

- Libraries/LibJS/Bytecode/Builtins.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Runtime/ArrayIterator.cpp
- Libraries/LibJS/Runtime/ArrayIterator.h
- Libraries/LibJS/Runtime/ArrayIteratorPrototype.cpp
- Libraries/LibJS/Runtime/ArrayIteratorPrototype.h
- Libraries/LibJS/Runtime/Iterator.cpp
- Libraries/LibJS/Runtime/Iterator.h
- Libraries/LibJS/Runtime/MapIterator.cpp
- Libraries/LibJS/Runtime/MapIterator.h
- Libraries/LibJS/Runtime/MapIteratorPrototype.cpp
- Libraries/LibJS/Runtime/MapIteratorPrototype.h
- Libraries/LibJS/Runtime/NativeFunction.cpp
- Libraries/LibJS/Runtime/NativeFunction.h
- Libraries/LibJS/Runtime/Object.cpp
- Libraries/LibJS/Runtime/Object.h
- Libraries/LibJS/Runtime/SetIterator.cpp
- Libraries/LibJS/Runtime/SetIterator.h
- Libraries/LibJS/Runtime/SetIteratorPrototype.cpp
- Libraries/LibJS/Runtime/SetIteratorPrototype.h
- Libraries/LibJS/Runtime/StringIterator.cpp
- Libraries/LibJS/Runtime/StringIterator.h
- Libraries/LibJS/Runtime/StringIteratorPrototype.cpp
- Libraries/LibJS/Runtime/StringIteratorPrototype.h
- Libraries/LibJS/Tests/redefine-prototype-of-builtin-iterators.js
Before this change each built-in iterator object has a boolean `m_next_method_was_redefined`. If user code later changed the iterator’s prototype (e.g. `Object.setPrototypeOf()`), we still believed the built-in fast-path was safe and skipped the user supplied override, producing wrong results.
With this change
`BuiltinIterator::as_builtin_iterator_if_next_is_not_redefined()` looks up the current `next` property and verifies that it is still the built-in native function.
> LibJS: Do more comprehensive check if `next()` fast path is possible

- Libraries/LibUnicode/TimeZone.cpp
- Libraries/LibUnicode/TimeZone.h
- Tests/LibJS/test-js.cpp
- Tests/LibUnicode/TestTimeZone.cpp
On Windows, ICU does not look at the `TZ` environment variable at all. So to support changing time zones in `test-js`, let's set ICU's default time zone directly.
Note that we no longer deal with "null" time zone strings. We just cache whatever ICU thinks is the current time zone before attempting to change it, for which we never have a null result.
> LibJS+LibUnicode: Change time zones in a way that works on Windows

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Libraries/LibWeb/HTML/HTMLInputElement.h
For example, button inputs shouldn't have a cursor displayed in their text since they're not editable, and are not meant to be editable.
Fixes #4140
I've decided to create a method that can tell Document if this element really needs a cursor or not, but I'm open to discussing and implementing alternative approaches.
> LibWeb: don't place cursor on certain <input> elements

- Meta/host_platform.py
This regressed when porting find_compiler.sh to python.
Fixes #4959
> Meta: Default chosen compilers to the CC and CXX environment variables

- Libraries/LibRegex/RegexByteCode.cpp
- Tests/LibRegex/TestRegex.cpp
Fixes an issue where + quantifiers failed on zero-width matches, such as empty backreferences.
Diff Tests:
test/annexB/language/literals/regexp/quantifiable-assertion-followed-by.js ❌ -> ✅
test/built-ins/RegExp/S15.10.2.5_A1_T5.js                                  ❌ -> ✅
test/built-ins/RegExp/S15.10.2.9_A1_T5.js                                  ❌ -> ✅
> LibRegex: Fix handling of + quantifier with zero-width matches

- Libraries/LibJS/Tests/builtins/Intl/Collator/Collator.prototype.resolvedOptions.js
- Libraries/LibJS/Tests/builtins/Intl/Intl.supportedValuesOf.js
- Libraries/LibUnicode/ICU.h
- Libraries/LibUnicode/TimeZone.cpp
- Libraries/LibUnicode/UnicodeKeywords.cpp
Completely missed this when implementing Intl.Collator!
test262 diff (this is a new test, which is probably why I didn't notice before):
```
test/intl402/Collator/prototype/resolvedOptions/resolved-collation-unicode-extensions-and-options.js ❌ -> ✅
```
> LibJS+LibUnicode: Implement retrieval of collator keyword values

- Tests/LibWeb/Layout/expected/css-counters/basic.txt
- Tests/LibWeb/Layout/expected/css-counters/counters-function-single-argument.txt
- Tests/LibWeb/Layout/expected/css-counters/counters-function.txt
- Tests/LibWeb/Layout/expected/css-counters/hidden-elements.txt
- Tests/LibWeb/Layout/expected/css-values/rect-non-token-contents-crash.txt
- Tests/LibWeb/Layout/expected/layout-tree-update/simple-update-inside-svg-subtree.txt
- Tests/LibWeb/Layout/expected/misc/grid-template-block-components-whitespace-crash.txt
- Tests/LibWeb/Layout/input/css-counters/basic.html
- Tests/LibWeb/Layout/input/css-counters/counters-function-single-argument.html
- Tests/LibWeb/Layout/input/css-counters/counters-function.html
- Tests/LibWeb/Layout/input/css-counters/hidden-elements.html
- Tests/LibWeb/Layout/input/css-values/rect-non-token-contents-crash.html
- Tests/LibWeb/Layout/input/layout-tree-update/simple-update-inside-svg-subtree.html
- Tests/LibWeb/Layout/input/misc/grid-template-block-components-whitespace-crash.html
This adds doctypes to layout tests in a bunch of miscellaneous folders.
None of these are supposed to be in quirks more from what I can tell.
The only thing that changed on all of them is that the HTML element is no longer 600 pixels tall, so none of the relevant layout information changed.
This is a step towards making the CI enforce these and I've decided to do them per-directory to make it more manageable.
This takes care of all directories except for the flex and grid ones.
> Meta: Add doctypes to a few more layout tests

- Libraries/LibJS/Runtime/Array.cpp
- Libraries/LibJS/Runtime/Array.h
- Libraries/LibJS/Runtime/IndexedProperties.cpp
If array has packed index property storage without holes, we could check
if indexed property is present simple by checking if it's less than
array's length.
Makes the following program go 1.1x faster:
```js
function f() {
let array = [];
for (let i = 0; i < 3_000; i++) {
array.push(i);
}
for (let i = 0; i < 10_000; i++) {
array.map(x => x * 2);
}
}
f();
```
> LibJS: Add fast path internal_has_property() for Array

- Libraries/LibWeb/DOM/Node.cpp
- Tests/LibWeb/Layout/expected/layout-tree-update/inline-element-position-change.txt
- Tests/LibWeb/Layout/input/layout-tree-update/inline-element-position-change.html
When marking a part of the layout tree for rebuild, if the subtree root that we're marking has an anonymous parent, we now mark from the nearest
non-anonymous ancestor instead.
This ensures that subtrees inside anonymous wrappers don't just get duplicated (i.e recreated but inserted instead of replaced).
Fixes this very wonky visual issue when resizing on https://patricia.no/2025/05/30/why_lean_software_dev_is_wrong.html
https://github.com/user-attachments/assets/bdeb278b-e4f3-4ccb-aac2-dd9e967e7856
> LibWeb: Invalidate layout tree at nearest non-anonymous ancestor

- Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.cpp
- Libraries/LibWeb/CSS/StyleValues/ImageStyleValue.h
- Libraries/LibWeb/CSS/URL.h
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/urls/resolve-relative-to-base.sub.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/urls/resolve-relative-to-stylesheet.txt
For `getComputedStyle()`, we must return an absolute URL for image style values. We currently return the raw parsed URL.
This fixes loading the marker icons on https://usermap.serenityos.org/.
Fixes #4972
> LibWeb: Absolutize CSS image URLs for computed style resolution

- Libraries/LibWeb/Layout/TableFormattingContext.cpp
- Libraries/LibWeb/Painting/TableBordersPainting.cpp
- Tests/LibWeb/Ref/expected/table-collapse-ignored-in-cells-ref.html
- Tests/LibWeb/Ref/input/table-collapse-ignored-in-cells.html
We previously checked the cell's computed values for the border-collapse property, but a cell is only in separated-borders mode if the table has border-collapse set to separate. Curiously in some other placed where this mode is checked we already did the correct thing.
For reference: https://www.w3.org/TR/css-tables-3/#border-collapse-property
> LibWeb: Use the correct definition of separated-borders mode

- Meta/ladybird.py
The install command was failing with `Namespace object has no attribute args` error because the argument parser for the install command was missing the 'args' parameter that allows passing additional arguments to the build system.
This fix adds the missing argument to match the behavior of other commands like build, run, and debug.
> Meta: Add missing 'args' argument to install command parser

- Libraries/LibJS/Runtime/Array.cpp
- Libraries/LibJS/Runtime/IndexedProperties.cpp
- Libraries/LibJS/Runtime/IndexedProperties.h
Makes MicroBench/array-prototype-map.js go 1.2x faster
> LibJS: Add more fast paths for arrays with simple storage

- UI/CMakeLists.txt
In a clean environment, building only headless-browser neglected to install the resource files needed to run the browser. These were only installed by the main Ladybird target.
Fixes #5003
> headless-browser: Ensure headless-browser depends on its resource files

- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Tests/LibWeb/Layout/expected/auto-margin-max-width-container.txt
- Tests/LibWeb/Layout/expected/bfc-fit-content-width-with-margin.txt
- Tests/LibWeb/Layout/input/auto-margin-max-width-container.html
- Tests/LibWeb/Layout/input/bfc-fit-content-width-with-margin.html
`BlockFormattingContext::compute_width()` stores the left and right margins in the layout state at the very end of the function. However, before doing so, it calls `FormattingContext::calculate_inner_width()` which ends up calling `FormattingContext::calculate_stretch_fit_width()` if the current box has `width: fit-content`.
Due to this, `calculate_stretch_fit_width()` would always see the margins from the layout state as zero and therefore not take them into account. Subsequently, the calculated width ended up being wrong.
Saving margins on the layout state earlier, before calling `calculate_inner_width()`, makes sure that the width is calculated correctly.
> LibWeb: Consider margins during fit-content sizing in BFC

- .github/actions/cache-restore/action.yml
- .github/actions/cache-save/action.yml
- .github/workflows/ci.yml
- .github/workflows/js-artifacts.yml
- .github/workflows/js-benchmarks.yml
- .github/workflows/lagom-template.yml
- .github/workflows/libjs-test262.yml
- .github/workflows/nightly-lagom.yml
- .github/workflows/nightly-windows.yml
The GitHub-provided runner frequently times out and is plain slow most of the time. And since Blacksmith does not yet offer macOS runners, let's use our self-hosted runner that is currently idle most of the time (when it's not running JS benchmarks).
**Note:** this cannot be auto-merged and after merging, the required checks for the `master` branch need updating.
> CI: Run all macOS jobs on self-hosted runner

- Libraries/LibWeb/HTML/HTMLButtonElement.cpp
- Libraries/LibWeb/HTML/HTMLDialogElement.cpp
- Libraries/LibWeb/HTML/HTMLDialogElement.h
- Libraries/LibWeb/HTML/HTMLElement.cpp
- Libraries/LibWeb/HTML/HTMLElement.h
- Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Libraries/LibWeb/HTML/PopoverInvokerElement.cpp
- Libraries/LibWeb/HTML/ToggleEvent.cpp
- Libraries/LibWeb/HTML/ToggleEvent.h
- Libraries/LibWeb/HTML/ToggleEvent.idl
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/popovers/popover-toggle-source.tentative.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/the-button-element/command-and-commandfor/on-dialog-behavior.txt
- Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/popover-toggle-source.tentative.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/popovers/resources/toggle-event-source-test.js
- Tests/LibWeb/Text/input/wpt-import/html/semantics/the-button-element/command-and-commandfor/on-dialog-behavior.html
See commit descriptions for spec PRs
> Implement ToggleEvent.source and the request-close command

- Libraries/LibWeb/DOM/Node.cpp
- Libraries/LibWeb/DOM/Node.h
- Libraries/LibWeb/TreeNode.h
Motivated by wanting to do `is_before()` on a Layout::Node, and thought I might as well move as many as possible while I was at it.
> LibWeb: Move non-DOM-related methods from DOM::Node to TreeNode

- Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveFactory.cpp
> LibWeb/ContentSecurityPolicy: Remove noisy "unknown directive" log

- Libraries/LibWeb/CSS/CSSRuleList.cpp
- Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
- Tests/LibWeb/Text/expected/css/namespace-rules.txt
- Tests/LibWeb/Text/input/css/namespace-rules.html
Resolves a FIXME in `CSSRuleList::insert_a_css_rule`. Gets us a bit closer to passing https://wpt.live/css/cssom/at-namespace.html but that requires more work around parsing of selectors with namespaces (namely disallowing use of undeclared selectors), which I have added a FIXME for.
> LibWeb: Throw error on insertRule with disallowed @namespace rule

- Libraries/LibWeb/DOM/Element.cpp
- Tests/LibWeb/Text/expected/DOM/removeAttribute-style.txt
- Tests/LibWeb/Text/input/DOM/removeAttribute-style.html
Previously we would just throw it away and construct a new (empty) one when required. This doesn't work as any existing references to the old instance will contain out of date information. Now we retain and update the existing instance instead.
> LibWeb: Update m_inline_style when element style attribute is removed

- Libraries/LibWeb/CSS/CSSStyleProperties.cpp
- Libraries/LibWeb/CSS/CSSStyleProperties.h
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/Editing/Internal/Algorithms.cpp
- Libraries/LibWeb/HTML/Window.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/cssom/getComputedStyle-pseudo.txt
- Tests/LibWeb/Text/input/wpt-import/css/cssom/getComputedStyle-pseudo.html
This PR adds support for `CSSStyleProperties` having no owner node, and takes advantage of that functionality when calling `getComputedStyle` with an invalid pseudo-element.
Gains us a few more WPT passes, https://wpt.live/css/cssom/getComputedStyle-pseudo.html
> LibWeb: Resolve FIXME in `Window::get_computed_style`

- pyproject.toml
This way we don't have to track the defaults.
Didn't notice this option existed in #5038 .
> Meta: Use `extend-select` to enable non-default python linters

- Libraries/LibWeb/WebIDL/AbstractOperations.cpp
- Libraries/LibWeb/WebIDL/AbstractOperations.h
As with a few other functions in this file, this is a combination of the current spec, and a PR that integrates shadow realms.
> LibWeb/WebIDL: Bring IDL::construct() up to date with the spec

- Libraries/LibWebView/Application.cpp
- Libraries/LibWebView/Application.h
- UI/Qt/Application.cpp
In particular, we need to defer creating the process manager until after we have decided whether or not to create a UI-specific event loop. If we create the process manager sooner, its event loop signal registration does not work, and we don't handle child processes exiting.
Fixes #5057
> LibWebView: Defer creating services until after application init

- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/HTML/EventLoop/EventLoop.cpp
- Libraries/LibWeb/Painting/ViewportPaintable.cpp
- Libraries/LibWeb/Painting/ViewportPaintable.h
See individual commits, but basically do a bit of caching to avoid work in `update_the_rendering`
> Slim down some things that we're currently doing 60 times/sec

- Libraries/LibDNS/Resolver.h
This helped narrow down the problem while working on issue #5070
> LibDNS: Add debug messages for error response codes in resolver

- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-text-decor/parsing/text-decoration-line-invalid.txt
Fixes all subtests in `css-text-decor/parsing/text-decoration-line-invalid.html`.
> LibWeb/CSS: Treat repeated `text-decoration-line` values as invalid

- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-align/gaps/gap-parsing-001.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-align/gaps/grid-gap-parsing-001.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-align/parsing/grid-gap-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/parsing/background-size-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-multicol/parsing/columns-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-multicol/parsing/columns-valid.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-align/parsing/grid-gap-invalid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-backgrounds/parsing/background-size-invalid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-multicol/parsing/columns-invalid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-multicol/parsing/columns-valid.html
This fixes at least 9 WPT subtests.
> LibWeb/CSS: Backtrack the parser if a property does not accept a value

- Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-animations/parsing/keyframes-name-invalid.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-animations/parsing/keyframes-name-invalid.html
This fixes 1 WPT subtest :tada::tada::tada:
> LibWeb: Disallow `default` as a keyframe name

- Libraries/LibCompress/GenericZlib.cpp
- Libraries/LibWeb/Compression/DecompressionStream.cpp
- Tests/LibWeb/Text/expected/wpt-import/compression/decompression-corrupt-input.tentative.any.txt
- Tests/LibWeb/Text/input/wpt-import/compression/decompression-corrupt-input.tentative.any.html
- Tests/LibWeb/Text/input/wpt-import/compression/decompression-corrupt-input.tentative.any.js
Turns out I miss @awesomekling videos about making "line go up" in WPT so much I decided to take bite to see it was as fun to do them as it is to watch them. PS: please bring them back I implore you ;)
This MR fixes a bug in our decompression mechanism by which we would try to decompress until the end of the stream right before flushing. In the happy case this would be fine as zlib would decompress the stream until then end and then return.
The problem arises when you have incomplete or corrupted streams where maybe not all the information has arrived. In this situation reading until the end of stream resulted in an infinite while loop. We would call into zlib which responded with an empty result as it couldn't process any more. The stream would not have reached the end so we would try …
> LibWeb: Fix decompression stream

- Libraries/LibWeb/CSS/Interpolation.cpp
- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/TransformFunctions.json
- Tests/LibWeb/Text/expected/wpt-import/css/css-transforms/parsing/transform-invalid.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-transforms/parsing/transform-invalid.html
This fixes 2 WPT subtests :tada:
> LibWeb/CSS: Disallow third argument in 2D scale functions

- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/StyleValues/ShadowStyleValue.cpp
- Libraries/LibWeb/CSS/StyleValues/ShadowStyleValue.h
- Tests/LibWeb/Text/expected/wpt-import/css/css-backgrounds/parsing/box-shadow-valid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-text-decor/text-shadow/parsing/text-shadow-valid.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-backgrounds/parsing/box-shadow-valid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-text-decor/text-shadow/parsing/text-shadow-valid.html
This fixes at least 38 WPT subtests.
> LibWeb: Don't serialize omitted `box-shadow` and `text-shadow` values

- Libraries/LibWeb/CSS/CSSStyleProperties.cpp
- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-contain/parsing/contain-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-contain/parsing/contain-valid.txt
Fixes at least 6 WPT subtests.
> LibWeb/CSS: Improve serialization of the `contain` property

- Libraries/LibWeb/CSS/Enums.json
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-box/parsing/clear-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-box/parsing/clear-valid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-box/parsing/float-computed.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-box/parsing/clear-computed.html
- Tests/LibWeb/Text/input/wpt-import/css/css-box/parsing/clear-valid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-box/parsing/float-computed.html
Currently `inline-start` and `inline-end` are always treated as `left` and `right` respectively. This is the same behavior that we currently have for the float property.
Fixes at least 6 WPT subtests.
> LibWeb: Add flow relative values for the clear property

- Libraries/LibGfx/CMakeLists.txt
- Libraries/LibIPC/Decoder.cpp
- Libraries/LibURL/Origin.cpp
- Libraries/LibURL/Origin.h
- Libraries/LibURL/URL.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Policy.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Policy.h
- Libraries/LibWeb/ContentSecurityPolicy/SerializedPolicy.cpp
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/DOM/DocumentLoading.h
- Libraries/LibWeb/HTML/BrowsingContext.cpp
- Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Libraries/LibWeb/HTML/Navigable.cpp
- Libraries/LibWeb/HTML/NavigationParams.h
- Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Libraries/LibWeb/HTML/Scripting/Environments.cpp
- Libraries/LibWeb/HTML/Scripting/SerializedEnvironmentSettingsObject.cpp
- Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.cpp
- Libraries/LibWeb/HTML/Scripting/WorkerEnvironmentSettingsObject.h
- Libraries/LibWeb/HTML/SharedWorkerGlobalScope.h
- Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
Precursor to changing URL::Origin to use a nonce for opaque origins.
> LibWeb+LibURL: Remove the default constructor for URL::Origin

- Libraries/LibJS/Runtime/TypedArray.cpp
- Libraries/LibJS/Runtime/TypedArray.h
- Libraries/LibJS/Runtime/TypedArrayPrototype.cpp
`TypedArray` objects need to know their own constructor objects to allow copying. This was implemented by storing a function pointer to the `Intrinsic` object's method which returns the constructor object.
The problem is that function pointers aren't polymorphic, we can't legally just cast e.g. a `Derived* (*ptr)(void)` to `Base* (*ptr)(void)` (this is why the code needed a `bit_cast` to even compile). But this wasn't actually a problem in practice because their ABIs were the same. But with pointer authentication (Apple's `arm64e` ABI) this signature mismatch becomes a hard failure and crashes the process.
Fix this by adding a virtual function that returns the intrinsic constructor (actually, a `NativeFunction`, as typed arrays constructors don't inherit from the base `TypedArray` …
> LibJS: Fix pointer authentication failure in `TypedArray`

- Tests/CMakeLists.txt
These tests work on Windows, can be just enabled.
> Tests: Enable LibTest, LibTextCodec and LibUnicode tests on Windows

- Libraries/LibWeb/HTML/Canvas/CanvasSettings.h
- Libraries/LibWeb/HTML/Canvas/CanvasSettings.idl
- Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
- Libraries/LibWeb/HTML/CanvasRenderingContext2D.idl
This refactors this mixin, that was introduced in #4506 to be the same as all other mixins, so that it can be used for #3788
This is necessary, to use `CanvasSettings` in #3788 . It also does the same as all other mixins, I have no plan, why it was not done like this in #4506 in the first place
> LibWeb: Factor out CanvasSettings mixin into separate file

- Libraries/LibWeb/WebAudio/AudioNode.cpp
- Libraries/LibWeb/WebAudio/AudioNode.h
Sets up the basic infrastructure for the audio node graph and implements the AudioNode `connect()` method with its related overides. AudioNodes store vectors of AudioNodeConnections and AudioParamConnections to represent links between nodes.
> LibWeb/WebAudio: Implement AudioNode::connect()

- Libraries/LibGfx/CMakeLists.txt
- Libraries/LibWeb/CMakeLists.txt
- Meta/CMake/FindWebP.cmake
Ran into some issues trying to build, and these changes seem to fix it.
The build was unable to find WebP on some systems, since it seems to expect the library to provide cmake files. When I reported this as [a bug to Gentoo](https://bugs.gentoo.org/937031), the response was that this might be expected behaviour.
To work around that, I've added a modified version of FindWebP.cmake from WebKit, adjusted to match the target names Ladybird expects.
(also removed the conditional lookups since I couldn't figure out how they were supposed to work)
Linking failed for me with this error:
```
[1/25] Linking CXX shared library lib64/liblagom-web.so.0.0.0
FAILED: lib64/liblagom-web.so.0.0.0
: && /usr/bin/c++ -fPIC -O2 -g -DNDEBUG  -fstack-protector-strong -Wl,-z,defs -Wl,--no-undefined …
```
> CMake: Improve support for linking to some system libraries

- Libraries/LibJS/Runtime/StringPrototype.cpp
Normative PR: https://github.com/tc39/ecma262/pull/3009 (unmerged as of this commit)
There are 24 test262 tests for this, see [https://test262.fyi/#built-ins/String/prototype](https://test262.fyi/#built-ins/String/prototype) and https://github.com/tc39/test262/pull/4404. JSC and Rhino have already added these changes.
Let me know if you would like to wait until the Normative PR is merged. I am subscribed to that PR.
> LibJS: Update to normative change to avoid Symbol methods for RegExp on primitives

- Libraries/LibWeb/Animations/AnimationEffect.cpp
- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.cpp
- Libraries/LibWeb/CSS/StyleValues/EasingStyleValue.h
- Tests/LibWeb/Text/expected/wpt-import/css/css-easing/timing-functions-syntax-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-easing/timing-functions-syntax-valid.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-easing/timing-functions-syntax-computed.html
- Tests/LibWeb/Text/input/wpt-import/css/css-easing/timing-functions-syntax-valid.html
This PR allows `calc()` values in `steps()` and `cubic-bezier()` easing functions.
This fixes at least 9 WPT subtests.
> LibWeb: Allow `calc()` values in some easing functions

- .github/actions/cache-restore/action.yml
- .github/actions/cache-save/action.yml
We were seeing lower ccache hitrates using Blacksmith's cache, and after some investigation it turned out that actions running on our `master` branch were pulling the caches from PRs. Blacksmith is looking into this - for now revert to GitHub's cache until the issue is resolved.
> CI: Use GitHub's actions cache instead of Blacksmith's for now

- Documentation/CSSGeneratedFiles.md
- Libraries/LibWeb/CMakeLists.txt
- Libraries/LibWeb/CSS/CSSDescriptors.cpp
- Libraries/LibWeb/CSS/CSSFontFaceDescriptors.cpp
- Libraries/LibWeb/CSS/CSSPageDescriptors.cpp
- Libraries/LibWeb/CSS/CSSStyleDeclaration.h
- Libraries/LibWeb/CSS/CSSStyleProperties.cpp
- Libraries/LibWeb/CSS/CSSStyleProperties.h
- Libraries/LibWeb/CSS/ComputedProperties.cpp
- Libraries/LibWeb/CSS/ComputedProperties.h
- Libraries/LibWeb/CSS/CountersSet.cpp
- Libraries/LibWeb/CSS/CountersSet.h
- Libraries/LibWeb/CSS/PseudoElements.json
- Libraries/LibWeb/CSS/StyleValues/CounterStyleValue.cpp
- Libraries/LibWeb/CSS/StyleValues/CounterStyleValue.h
- Libraries/LibWeb/DOM/AbstractElement.cpp
- Libraries/LibWeb/DOM/AbstractElement.h
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
- Libraries/LibWeb/DOM/PseudoElement.cpp
- Libraries/LibWeb/DOM/PseudoElement.h
- Libraries/LibWeb/Editing/Internal/Algorithms.cpp
- Libraries/LibWeb/Forward.h
- Libraries/LibWeb/HTML/Window.cpp
- Libraries/LibWeb/Layout/Node.h
- Libraries/LibWeb/Layout/TreeBuilder.cpp
- Libraries/LibWeb/Painting/PaintableBox.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPseudoElement.cpp
- Tests/LibWeb/Layout/expected/css/counters-on-pseudo-elements.txt
- Tests/LibWeb/Layout/input/css/counters-on-pseudo-elements.html
The CSS-Lists spec, where [counters](https://drafts.csswg.org/css-lists-3/#counter) are defined, generally just talks about "elements" having a counters set, but actually includes pseudo-elements in that. This PR gives them a CountersSet and greatly extends AbstractElement (previously known as ElementReference) so that the counters algorithms don't have to care whether they're dealing with a "real" element or not. There are also some related pseudo-element changes.
> LibWeb: Support counters on pseudo-elements

- Libraries/LibWeb/DOM/DOMImplementation.cpp
- Libraries/LibWeb/DOM/DOMImplementation.h
- Libraries/LibWeb/DOM/DocumentType.cpp
- Libraries/LibWeb/DOM/DocumentType.h
- Tests/LibWeb/Text/expected/wpt-import/dom/nodes/DOMImplementation-createDocumentType.txt
- Tests/LibWeb/Text/input/wpt-import/dom/nodes/DOMImplementation-createDocumentType.html
This now follows the latest specification steps.
Nets us at least 48 WPT subtest passes.
> LibWeb: Update `DOMImplementation.createDocumentType()` name validation

- Libraries/LibWeb/Layout/InlineLevelIterator.cpp
- Tests/LibWeb/Layout/expected/block-and-inline/atomic-inline-with-percentage-vertical-align.txt
- Tests/LibWeb/Layout/expected/block-and-inline/inline-block-leading-and-trailing-metrics.txt
- Tests/LibWeb/Layout/input/block-and-inline/inline-block-leading-and-trailing-metrics.html
In `InlineLevelIterator`, whenever we call `skip_to_next()` and enter a node with box model metrics, we could potentially accumulate leading and trailing metrics. This lead to a weird situation where an element with `display: inline-block` could adopt the leading metrics of an inline element that follows it, since we perform the call to `add_extra_box_model_metrics_to_item()` too late.
Move `skip_to_next()` down so it no longer interferes with the `Item` we're creating.
The test expectation for `atomic-inline-with-percentage-vertical-align.html` is updated, although neither the old nor new results are 100% accurate since either box jumps one pixel to the right.
> LibWeb: Prevent time-traveling leading inline metrics

- .github/workflows/ci.yml
- .github/workflows/lagom-template.yml
Each matrix item now defines whether it is enabled, and if not, the job conditionally disables itself. Apparantly we cannot use expressions in `matrix.exclude`, but it should work in the items' definitions.
This has the added benefit that this makes the job show up as "skipped", which could serve as a hint that it could be run on a PR.
> CI: Disable the Windows CI job by using a boolean exclusion

- Meta/WPT.sh
- Meta/import-wpt-test.py
This option can be used with the `WPT.sh import` subcommand or the ` import-wpt-test.py`  script to download and replace any files that already exist.
I have included an exclude list for files that we want to ensure don't get updated. These will need to be synchronized manually.
> Meta: Add `--force` option to WPT import script to update existing tests

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/HTML/HTMLBaseElement.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/document-metadata/the-base-element/base-data.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/document-metadata/the-base-element/base-javascript.txt
- Tests/LibWeb/Text/input/wpt-import/html/semantics/document-metadata/the-base-element/base-data.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/document-metadata/the-base-element/base-javascript.html
This implements the fallback to the documents fallback base url if the href of the first base element is a data or javascript url.
Additionally the frozen base url is set, if a base element becomes the first base element with an href content attribute because the previous one got removed.
> LibWeb/HTML: Correctly set base elements frozen base url

- Libraries/LibTLS/TLSv12.cpp
- Libraries/LibTLS/TLSv12.h
- Libraries/LibWebSocket/Impl/WebSocketImplSerenity.cpp
- Services/RequestServer/ConnectionFromClient.cpp
- Tests/LibDNS/TestDNSResolver.cpp
- Tests/LibTLS/TestTLSHandshake.cpp
- Utilities/dns.cpp
None of our real code use cases actually use blocking mode. So we should be testing non-blocking.
> LibTLS: Use non-blocking TLS socket in the handshake test

- .github/workflows/lagom-template.yml
The CI runs are supposed to upload test dumps for failed LibWeb tests as artifacts. However, the path for the artifact upload was wrong, it likely regressed in #5026.
Verified to work in https://github.com/LadybirdBrowser/ladybird/actions/runs/15828383994?pr=5180#artifacts
> CI: Fix path to test-dumps folder of LibWeb tests for artifact upload

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/Geolocation/Geolocation.cpp
- Libraries/LibWeb/Geolocation/Geolocation.h
- Libraries/LibWeb/Geolocation/GeolocationCoordinates.cpp
- Libraries/LibWeb/Geolocation/GeolocationCoordinates.h
- Libraries/LibWeb/Geolocation/GeolocationPosition.cpp
- Libraries/LibWeb/Geolocation/GeolocationPosition.h
- Libraries/LibWeb/Geolocation/GeolocationPositionError.cpp
- Libraries/LibWeb/Geolocation/GeolocationPositionError.h
- Libraries/LibWeb/HTML/EventLoop/Task.h
- Libraries/LibWeb/HTML/TraversableNavigable.cpp
- Libraries/LibWeb/HTML/TraversableNavigable.h
This implements enough of the Geolocation spec that it is now possible for websites to retrieve the current geo position or try to watch for updates (which currently never happen).
As it stands now, it only returns a single emulated position that points to San Francisco.
Adds ~5 WPT subtest passes.
> LibWeb: Implement emulated Geolocation

- Libraries/LibWeb/CSS/ComputedProperties.h
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/Layout/Node.cpp
- Tests/LibWeb/Layout/expected/percentage-font-size.txt
- Tests/LibWeb/Layout/input/percentage-font-size.html
Updated to handle percentage font-size values correctly instead of crashing.
just fyi I have no idea what I'm doing, please review with a heap of salt
> LibWeb: Handle percentage font-size values

- Libraries/LibWeb/CSS/CSSGroupingRule.cpp
- Libraries/LibWeb/CSS/CSSRuleList.cpp
- Libraries/LibWeb/CSS/CSSRuleList.h
- Libraries/LibWeb/CSS/CSSStyleRule.cpp
- Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Libraries/LibWeb/CSS/CSSStyleSheet.h
- Libraries/LibWeb/CSS/Parser/Parser.cpp
- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/CSS/Parser/SelectorParsing.cpp
- Tests/LibWeb/Ref/expected/wpt-import/css/css-namespaces/reference/ref-lime-1.xml
- Tests/LibWeb/Ref/input/wpt-import/css/css-conditional/at-supports-045.html
- Tests/LibWeb/Ref/input/wpt-import/css/css-conditional/support/fail.css
- Tests/LibWeb/Ref/input/wpt-import/css/css-namespaces/scope-002.xml
- Tests/LibWeb/Ref/input/wpt-import/css/css-namespaces/support/scope-002a.css
- Tests/LibWeb/Ref/input/wpt-import/css/css-namespaces/support/scope-002b.css
- Tests/LibWeb/Text/expected/wpt-import/css/cssom/at-namespace.txt
- Tests/LibWeb/Text/input/wpt-import/css/cssom/at-namespace.html
Selectors containing undeclared namespaces should be considered invalid, not just not matching any elements.
Gains us 3 new WPT passes.
> LibWeb: Consider CSS selector with undeclared namespaces invalid

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Libraries/LibWeb/HTML/HTMLImageElement.h
- Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Libraries/LibWeb/HTML/HTMLVideoElement.cpp
- Libraries/LibWeb/HTML/ListOfAvailableImages.cpp
- Libraries/LibWeb/HTML/ListOfAvailableImages.h
- Libraries/LibWeb/HTML/NavigableContainer.cpp
- Libraries/LibWeb/SVG/SVGImageElement.cpp
- Libraries/LibWeb/SVG/SVGScriptElement.cpp
The spec has been updated to use `encoding_parse_url()` and `encoding_parse_and_serialize_url()` instead.
> LibWeb: Replace usages of `Document::parse_url()`

- Libraries/LibGfx/Font/FontDatabase.cpp
This avoids a memory leak in `FontDatabase::font_directories()`.
Found by running the following command: `BUILD_PRESET=Sanitizer Meta/ladybird.py run test-web -f Text/input/selection-over-multiple-code-units.html`
> LibGfx: Destroy FontConfig string iterator after use

- Libraries/LibWeb/Layout/Node.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/tree-counting/sibling-index-keyframe-font-weight-dynamic.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-values/tree-counting/sibling-index-keyframe-font-weight-dynamic.html
Previously, using `font-weight` with a keyword or `calc()` value inside a keyframe rule would cause a crash.
AFAICT, this doesn't get us any more WPT passes, but it does prevent a crash in: http://wpt.live/css/css-values/tree-counting/sibling-index-keyframe-font-weight-dynamic.html, which I've imported.
> LibWeb: Handle non-numeric `font-weight` values in keyframes

- Libraries/LibWeb/CSS/Parser/MediaParsing.cpp
- Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
- Tests/LibWeb/Ref/expected/wpt-import/css/CSS2/reference/ref-this-text-should-be-green.xht
- Tests/LibWeb/Ref/input/wpt-import/css/CSS2/cascade/at-import-009.xht
- Tests/LibWeb/Ref/input/wpt-import/css/CSS2/cascade/support/import-green.css
- Tests/LibWeb/Text/expected/wpt-import/css/css-conditional/js/conditional-CSSGroupingRule.txt
This fixes a recent regression in: http://wpt.live/css/CSS2/cascade/at-import-009.xht
> LibWeb/CSS: Treat block at-rules with no block as invalid

- Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
- Tests/LibWeb/Text/expected/HTML/document-readyState-is-initially-complete.txt
- Tests/LibWeb/Text/expected/wpt-import/domparsing/xmldomparser.txt
- Tests/LibWeb/Text/input/HTML/document-readyState-is-initially-complete.html
- Tests/LibWeb/Text/input/wpt-import/domparsing/xmldomparser.html
Documents created via DOMParser.parseFromString()
are parsed synchronously and do not participate in the browsing context's loading pipeline.
This patch ensures that if the document has no browsing context (i.e. was parsed via DOMParser),
its readiness is set to "complete" synchronously.
Fixes WPT:
domparsing/xmldomparser.html
> LibWeb: Set readyState to complete for DOMParser documents

- Libraries/LibGfx/CMYKBitmap.cpp
- Libraries/LibGfx/CMYKBitmap.h
- Libraries/LibGfx/ImageFormats/BMPLoader.cpp
- Libraries/LibGfx/ImageFormats/GIFLoader.cpp
- Libraries/LibGfx/ImageFormats/ICOLoader.cpp
- Libraries/LibGfx/ImageFormats/ImageDecoder.h
- Libraries/LibGfx/ImageFormats/JPEGLoader.cpp
- Libraries/LibGfx/ImageFormats/TIFFLoader.cpp
- Libraries/LibGfx/ImageFormats/TinyVGLoader.cpp
- Services/ImageDecoder/ConnectionFromClient.cpp
- Tests/LibGfx/TestImageDecoder.cpp
- Utilities/image.cpp
This makes it a bit easier to reason about where bitmaps should be available.
> LibGfx: Use NonnullRefPtr<Bitmap> for frame descriptors

- Libraries/LibWeb/CSS/Parser/Parser.cpp
- Libraries/LibWeb/CSS/PropertyName.h
- Tests/LibWeb/Ref/expected/wpt-import/css/css-variables/support/color-green-ref.html
- Tests/LibWeb/Ref/input/wpt-import/css/css-variables/variable-supports-58.html
- Tests/LibWeb/Text/expected/wpt-import/css/css-variables/variable-empty-name-reserved.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-variables/variable-empty-name-reserved.html
This is reserved for future use by CSS.
Fixes 2 WPT tests.
Split off from #5209.
> LibWeb: Treat the custom property name "--" as invalid

- .github/workflows/ci-windows.yml
A very minor thing, but given all the other CI labels match their respective presets, might as well do the same for Windows CI
> CI: Make Windows CI label name consistent with the preset name

- AK/Utf16View.h
- Libraries/LibJS/Runtime/Utf16String.cpp
- Libraries/LibJS/Tests/builtins/RegExp/RegExp.prototype.exec.js
> AK+LibJS: Do not set UTF-16 code point length to its code unit length

- Libraries/LibCore/MimeData.cpp
- Tests/LibCore/TestLibCoreMimeType.cpp
Extension .xht was part of common_extensions for two MimeType array entries: application/xhtml+xml and text/html. Should only be part of one.
Duplicate .xht extension removed from text/html mime type and is now only part of application/xhtml+xml mime type.
Pull request as a follow-up to #4860.
As Andrew Kaster mentions [here](https://github.com/LadybirdBrowser/ladybird/pull/4860#discussion_r2104979619), an authoritative reference for .xht file is not easy to find.
Some mention of the extension and these MimeTypes, at the IANA mime type registry.
https://www.iana.org/assignments/media-types/application/xhtml+xml
https://www.iana.org/assignments/media-types/text/html
This Mozilla guide does not include the .xht extension in this table, only makes reference to .xhtml, html, htm …
> LibCore: Remove .xht from common_extensions in MimeType text/html

- Libraries/LibWeb/HTML/AudioTrack.cpp
Previously, a video or audio element with the `autoplay` and `muted` attributes set, would not mute the audio before playing.
This ensures the video is initially muted on: https://isle.pizza
I'm not sure how to test this change, since I don't think the bug is observable in JS.
> LibWeb: Ensure audio tracks are set to the correct volume before playing

- Libraries/LibWeb/HTML/HTMLMediaElement.cpp
- Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Tests/LibWeb/Text/expected/HTML/HTMLMediaElement-muted-content-attribute.txt
- Tests/LibWeb/Text/input/HTML/HTMLMediaElement-muted-content-attribute.html
The `muted` content attribute should only affect the state of the `muted` IDL property when the media element is first created. The attribute should have no dynamic effect.
> LibWeb: Avoid updating muted state on muted content attribute changes

- Libraries/LibWeb/Layout/InlineLevelIterator.cpp
Previously ligatures weren't being explicitly disabled in this case
Screenshots taken from: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures
Before:
After:
This fixes these WPT tests, but they can't be imported because we don't support any font other than SerenitySans in our tests:
* http://wpt.live/css/css-fonts/font-variant-02.html
* http://wpt.live/css/css-fonts/font-variant-ligatures-02.html
> LibWeb: Explicitly disable ligatures if `font_variant_ligatures` is none

- Libraries/LibWeb/HTML/HTMLInputElement.cpp
The color picker implementation allows for live updates to the input element until the final color is confirmed by the user, but previously it was marked as closed immediately after the first update.
> LibWeb: Don't mark <input type="color"> as closed until the picker is

- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/svg/painting/parsing/stroke-dasharray-invalid.txt
- Tests/LibWeb/Text/input/wpt-import/svg/painting/parsing/stroke-dasharray-invalid.svg
The spec says that if any value in a `<dasharray>` is negative then the value is invalid.
> LibWeb/SVG: Disallow negative `stroke-dasharray` values

- Libraries/LibURL/CMakeLists.txt
- Libraries/LibURL/Host.cpp
- Libraries/LibURL/URL.cpp
- Libraries/LibURL/URL.h
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWebView/URL.cpp
- Meta/CMake/common_options.cmake
- Meta/CMake/public_suffix.cmake
- Meta/Lagom/Tools/CodeGenerators/LibURL/GeneratePublicSuffixData.cpp
- Tests/LibURL/TestURL.cpp
This fixes a recently introduced regression after using this function in the Document.domain setter, exposing this issue.
Unfortunately get_registrable_domain is also broken, which I've only left a FIXME for now since I was getting a weird result when given ".com" which I haven't gotten around to fully looking into and understanding, and this already fixes a bunch of WPT regressions
> LibURL: Fix logic for getting public suffix from a host

- Libraries/LibURL/Site.cpp
- Tests/LibURL/TestURL.cpp
Previously if we had two opaque origins both URLs were being treated as same site.
> LibURL: Differentiate cross site opaque origins

- Meta/CMake/vcpkg/overlay-ports/angle/portfile.cmake
Reduces some warning log noise during CMake configuration
```
The following packages will be built and installed:
angle:x64-linux-dynamic@chromium_5414#9 -- /home/ayeteadoe/Development/ladybird/Meta/CMake/vcpkg/overlay-ports/angle
Restored 0 package(s) from /home/ayeteadoe/Development/ladybird/Build/caches/vcpkg-binary-cache in 5.19 us. Use --debug to see more details.
Installing 1/1 angle:x64-linux-dynamic@chromium_5414#9...
Building angle:x64-linux-dynamic@chromium_5414#9...
/home/ayeteadoe/Development/ladybird/Meta/CMake/vcpkg/debug-triplets/x64-linux-dynamic.cmake: info: loaded overlay triplet from here
/home/ayeteadoe/Development/ladybird/Meta/CMake/vcpkg/overlay-ports/angle: info: installing overlay port from here
CMake Warning at …
```
> Meta: Fix CMake configure warning in unix angle vcpkg port

- Tests/LibWeb/Text/expected/HTML/image-bitmap-from-invalid-types-no-crash.txt
- Tests/LibWeb/Text/input/HTML/image-bitmap-from-invalid-types-no-crash.html
Now that https://github.com/LadybirdBrowser/ladybird/pull/3788 and https://github.com/LadybirdBrowser/ladybird/commit/1d62bf7049fabaecc85a3d211d9bb7938a476823 have been merged, the invalid types ImageBitmap creation test can add the new unimplemented input
> LibWeb: Add OffscreenCanvas to ImageBitmap invalid-types-no-crash test

- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/HTML/HTMLElement.cpp
- Tests/LibWeb/Text/expected/HTML/scrollParent-infinite-loop.txt
- Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/scrollParent-shadow-tree.txt
- Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/scrollParent.txt
- Tests/LibWeb/Text/input/HTML/scrollParent-infinite-loop.html
We were failing to actually climb up the containing block chain, causing this API to infinite loop for anything but the most trivial cases.
By fixing the loop structure, we also make a bunch of the already imported WPT tests pass. :^)
> LibWeb: Avoid infinite loop in HTMLElement.scrollParent

- Meta/import-wpt-test.py
Previously, fetching URLs with `..` components would fail.
This was the single biggest cause of failures when synchronizing WPT tests in #5160.
Can be tested with `./Meta/WPT.sh import css/CSS2/visufx/clip-006.xht`.
> Meta: Normalize relative URLs before fetching them in the WPT importer

- Meta/CMake/vcpkg/overlay-ports/angle/portfile.cmake
It was working for about 4 hours in upstream until [the angle upgrade](https://github.com/LadybirdBrowser/ladybird/commit/286fa7b3caa6f37ed2e8c048f0b29a0ef627bf45) and my [unix angle config warning noise reduction fix](https://github.com/LadybirdBrowser/ladybird/commit/3bce1934b152634d3e8fa11bfd257628f7fa62d2) broke it 😅 
The angle build completes successfully on `Windows_Sanitizer_CI` locally, but this should get the `windows` label to confirm. Or alternatively, you can see the results of https://github.com/LadybirdBrowser/ladybird/actions/runs/15991077080/job/45104302629?pr=5229 as that PR is rebased on-top of this commit currently
> Meta: Fix windows vcpkg angle port

- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-columns-rows-get-set-multiple.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/exp-log-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/hypot-pow-sqrt-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/minmax-angle-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/minmax-length-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/minmax-percentage-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/minmax-time-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/signs-abs-invalid.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-values/exp-log-invalid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/minmax-angle-invalid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/minmax-percentage-invalid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/minmax-time-invalid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/signs-abs-invalid.html
Previously, we would allow calc values such as `calc(min(1 2))`, which would be simplified to `calc(3)` because we assumed  that numbers not separated by an operator represented a sum. We now validate that the number of operators we see is as we would expect before collecting these values into a sum node.
Fixes at least 16 WPT subtests.
> LibWeb: Validate operator count when parsing a calculation

- vcpkg.json
This bump includes a new version of meson that unbreaks the build on macOS 26 with xcode 26.
> Meta: Update vcpkg baseline

- Libraries/LibWeb/Painting/BorderPainting.cpp
- Tests/LibWeb/Ref/expected/css/transparent-borders-ref.html
- Tests/LibWeb/Ref/input/css/transparent-borders.html
With this test:
```html
<style>
.example {
width: 0;
height: 0;
background: orange;
border: 20px solid transparent;
margin-bottom: 10px;
}
</style>
<div class="example" style="border-style: dotted"></div>
<div class="example" style="border-style: dashed"></div>
<div class="example" style="border-style: solid"></div>
<div class="example" style="border-style: groove"></div>
<div class="example" style="border-style: ridge"></div>
<div class="example" style="border-style: inset"></div>
<div class="example" style="border-style: outset"></div>
```
Before:
After:
> LibWeb/Painting: Make transparent inset/outset borders transparent

- vcpkg.json
Several of us (including our WPT runner) are getting linker errors with 11.2.0, as Qt is pulling in the system harfbuzz.
> Meta: Pin harfbuzz to 10.2.0 for now

- Tests/LibWeb/TestConfig.ini
- Tests/LibWeb/Text/input/selection-over-multiple-code-units.html
The flake was reproducible by running the entire LibWeb test suite over and over again with sanitizers enabled. By making the test async and run at window `load` time instead of document `DOMContentLoaded` time, I've not been able to reproduce the issue locally.
Ideally I was able to find the underlying cause for this bug, but for now I'd rather run this regression test.
Disabled in #5258, fixes #5257.
> Tests: Unskip `selection-over-multiple-code-units.html` test

- Libraries/LibWeb/Selection/Selection.cpp
- Tests/LibWeb/Crash/wpt-import/selection/crashtests/selection-modify-per-word-in-table-header-group.html
Previously, this incorrect offset could cause a crash when moving the selection to the previous word.
> LibWeb: Use correct previous word location when moving selection offset

- Tests/LibWeb/Text/expected/wpt-import/webstorage/symbol-props.window.txt
- Tests/LibWeb/Text/input/wpt-import/webstorage/symbol-props.window.html
- Tests/LibWeb/Text/input/wpt-import/webstorage/symbol-props.window.js
I noticed a subtest in this test failing along with every other browser. After investigation, the failure was due to testing the previous specification before:
https://github.com/whatwg/webidl/commit/3fb6ab4
So this imports the now adjusted WPT test as of:
https://github.com/web-platform-tests/wpt/commit/bb3f032
> Tests/LibWeb: Import webstorage symbol-props WPT test

- Libraries/LibWeb/DOM/Range.cpp
- Libraries/LibWeb/Painting/PaintableFragment.cpp
- Libraries/LibWeb/Painting/PaintableFragment.h
- Tests/LibWeb/Ref/expected/range-not-assiciated-with-selection-should-not-affect-it-ref.html
- Tests/LibWeb/Ref/input/range-not-assiciated-with-selection-should-not-affect-it.html
This change fixes at least two issues:
- `update_associated_selection()` is responsible for selectionchange dispatch, and we were incorrectly dispatching this event on ranges that were not associated with a selection.
- `Range::get_client_rects()` was using `update_associated_selection()` to refresh the selection state in the paintable tree for the current range, but since a range might not be associated with a selection, this could make the painted selection reflect the state of an arbitrary range instead of the actual selection range.
Fixes a bug on Discord where any text typed into the message input would get selected.
> LibWeb: Skip `update_associated_selection()` when there's no selection

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
This means I don't have to type as much when debugging things involving PropertyIDs.
> Meta: Add formatter to PropertyID code generator

- Tests/LibWeb/TestHTMLTokenizer.cpp
Just a very basic test to ensure that named character reference tokenization doesn't regress in a trivial way.
> LibWeb: Add simple named character reference test to TestHTMLTokenizer

- Documentation/BuildInstructionsLadybird.md
Updating the documentation for the Build Instructions as recent changes to using Google Angle for Linux caused build issue mostly on Ubuntu based distributions.
Checked the following distributions and noted the following changes:
Ubuntu missing: python3-venv
Fedora missing: git
Manjaro OK
OpenSUSE missing: git
> Documentation: Update missing distribution packages for building

- Libraries/LibWeb/HTML/DOMStringList.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/infrastructure/common-dom-interfaces/collections/domstringlist.txt
- Tests/LibWeb/Text/input/wpt-import/html/infrastructure/common-dom-interfaces/collections/domstringlist.html
The included WPT test passes through -1 which ends up modolo'ing to u32 max at the IDL conversion layer, resulting in an unsigned overflow when checking bounds.
> LibWeb/HTML: Avoid potential overflow of index for DOMStringList

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/Layout/LineBuilder.cpp
- Libraries/LibWeb/Painting/PaintableBox.cpp
- Libraries/LibWeb/Painting/PaintableBox.h
- Tests/LibWeb/Text/expected/hit_testing/empty-anonymous-container-overlapping.txt
- Tests/LibWeb/Text/expected/hit_testing/inline-content-inside-anonymous-container.txt
- Tests/LibWeb/Text/expected/wpt-import/css/cssom-view/elementsFromPoint-inline-htb-ltr.txt
- Tests/LibWeb/Text/input/hit_testing/empty-anonymous-container-overlapping.html
- Tests/LibWeb/Text/input/hit_testing/inline-content-inside-anonymous-container.html
- Tests/LibWeb/Text/input/wpt-import/css/cssom-view/elementsFromPoint-inline-htb-ltr.html
A `PaintableWithLines` will first try to see if there are any fragments that have a hit. If not, it falls back to hit testing against its border box rect.
However, inline content is often hoisted out of its parent into an anonymous container to maintain the invariant that all layout nodes either have inline or block level children. If that's the case, we should not check the border box rect of the anonymous container, because we might trigger a hit too early if the node has previous siblings in its original parent node that overlap with their bounds.
By ignoring anonymous nodes, we leave the border box hit testing to the nearest non-anonymous ancestor, which correctly applies the hit testing order to its children.
> LibWeb: Fix hit testing of anonymous containers' contents

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/HTML/DOMParser.cpp
- Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Node-cloneNode-document-with-doctype.txt
- Tests/LibWeb/Text/input/wpt-import/dom/nodes/Node-cloneNode-document-with-doctype.html
Previously, a crash would occur when accessing the origin of a document created with DOMParser.
Relevant spec issue: https://github.com/whatwg/html/issues/11429
> LibWeb: Set Document origin for DOMParser created documents

- Libraries/LibWeb/CMakeLists.txt
- Libraries/LibWeb/ContentSecurityPolicy/BlockingAlgorithms.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ConnectSourceDirective.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/Directive.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveFactory.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveOperations.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveOperations.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/FontSourceDirective.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/FrameSourceDirective.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ImageSourceDirective.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ManifestSourceDirective.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ManifestSourceDirective.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/MediaSourceDirective.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/MediaSourceDirective.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ObjectSourceDirective.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ObjectSourceDirective.h
- Libraries/LibWeb/Forward.h
Part 9 of splitting up https://github.com/LadybirdBrowser/ladybird/pull/2854
A few more simple directives before introducing the more complex script-src directives.
> LibWeb/CSP: Implement manifest-src, media-src and object-src directives

- Libraries/LibWeb/Painting/BorderRadiusCornerClipper.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.h
- Libraries/LibWeb/Painting/StackingContext.cpp
Unbalanced save/restore within display list items recorded for a paintable means that some state only relevant for the paintable leaks to subsequent paintables, which is never expected behavior.
> Verify that save/restore are balanced within paintable 

- Libraries/LibWeb/Painting/Paintable.h
- Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
- Libraries/LibWeb/Painting/SVGSVGPaintable.h
- Libraries/LibWeb/Painting/StackingContext.cpp
These were only used in SVGSVGPaintable to apply scroll frame id, which is already handled by `before_paint()` and `after_paint()` hooks in PaintableBox.
> LibWeb: Delete `before_children_paint` and `after_children_paint` hooks

- Libraries/LibWeb/HTML/Navigation.cpp
- Tests/LibWeb/Text/expected/wpt-import/navigation-api/navigate-event/navigate-multiple-history-pushState.txt
- Tests/LibWeb/Text/input/wpt-import/navigation-api/navigate-event/navigate-multiple-history-pushState.html
Implements specification change:
https://github.com/whatwg/html/commit/335d7f4
Which fixes a crash in the imported test.
> LibWeb: Abort ongoing navigations when firing certain navigate events

- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/StackingContext.cpp
Unbalanced save and restore means that effects only relevant to a stacking context leak outside, which is never expected behavior. Having a `VERIFY()` for that makes it much easier to catch such issues.
> LibWeb: Verify that save and restore are balanced within StackingContext

- Meta/WPT.sh
This ensures the Ahem test font is installed.
Tested by running: `./Meta/WPT.sh run infrastructure/assumptions/ahem.html` on the WPT runner machine - for some reason the test already passed for me locally.
> Meta: Include the `--install-fonts` argument when running WPT

- Services/RequestServer/ConnectionFromClient.cpp
By default, if multiple requests start to a newly seen origin, curl will not wait for a connection to open to figure out if the server supports multiplexing and will instead open a new connection for each request (including a new TLS session and such)
This is particularly an issue for initial page load, where a complex website could, for example, request tens of items at once (e.g. a bunch of scripts).
We can be kinder to servers that support multiplexing by telling curl to wait till an initial connection is established to determine if multiplexing is supported.
On my machine and internet connection, this reduces the amount of connections to github.githubassets.com on initial load of https://github.com/LadybirdBrowser/ladybird from 12 to 2.
Pcap files (extension changed from pcapng to txt …
> RequestServer: Wait until initial connection is open for multiplexing

- Libraries/LibWeb/Painting/Paintable.h
- Libraries/LibWeb/Painting/PaintableBox.cpp
- Libraries/LibWeb/Painting/PaintableBox.h
- Libraries/LibWeb/Painting/SVGPaintable.cpp
- Libraries/LibWeb/Painting/SVGPaintable.h
- Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
- Libraries/LibWeb/Painting/SVGSVGPaintable.h
Previously, we always applied the enclosing clip rectangle for all paint
phases except overlays, and the own clip rectangle for the background
and foreground phases. The problem is that applying a clip rectangle
means emitting an AddClipRect display list item for each clip rectangle
in the containing block. With this change, we choose whether to include
the own clip based on the paint phase and this way avoid emitting
AddClipRect for enclosing clip rectangles twice.
> Apply either enclosing or own clip rect depending on PaintPhase

- Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Libraries/LibWeb/HTML/FormAssociatedElement.h
- Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/form-submission-0/historical.window.txt
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/form-submission-0/historical.window.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/form-submission-0/historical.window.js
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/form-submission-0/resources/targetted-form.js
This fixes a submission loop for the following WPT test:
http://wpt.live/accessibility/crashtests/validation-message.html
https://wpt.fyi/results/accessibility/crashtests/validation-message.html?label=master&label=experimental&product=ladybird&aligned
> LibWeb: implement 'no-validate state' concept

- Libraries/LibWeb/Painting/BackgroundPainting.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
Website      | DisplayList Items Before | DisplayList Items After
-------------|--------------------------|-------------------------
ladybird.org | 2753                     | 1117
null.com     | 5298                     | 4484
discord.com  | 6598                     | 4992
> LibWeb: Avoid unnecessary save/restore in `paint_background()`

- Libraries/LibJS/Runtime/Intl/NumberFormat.cpp
- Libraries/LibJS/Runtime/Intl/NumberFormat.h
- Libraries/LibUnicode/NumberFormat.cpp
- Libraries/LibUnicode/NumberFormat.h
Noticed while looking at UTF-16 stuff.
> LibJS+LibUnicode: Remove unused FormatNumericToString AO

- Libraries/LibWeb/Layout/FormattingContext.cpp
- Tests/LibWeb/Layout/expected/grid/img-with-percentage-width-and-height.txt
- Tests/LibWeb/Layout/input/grid/img-with-percentage-width-and-height.html
- Tests/LibWeb/Text/expected/wpt-import/css/css-flexbox/flex-aspect-ratio-img-column-011.txt
By the time we calculate the min-content height, the width is already known, so we can use it to calculate the height based on the natural aspect ratio.
> LibWeb: Account for natural aspect ratio in calculate_min_content_height

- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Tests/LibWeb/Text/expected/css/border-image-non-fill-keyword.txt
- Tests/LibWeb/Text/input/css/border-image-non-fill-keyword.html
Previously if we encountered a keyword other than `fill` when parsing `<border-image-slice` we would return a nullptr.
This could cause issues when we parse `<border-image-slice>` as part of parsing `border-image`, for example `border-image: 100% none` would fail as we would try parse `none` as part of the `<border-image-slice>` instead of `<border-image-source>`.
This change makes it so that we don't consume the token and leave it to be parsed as part of the next section of the grammar.
PR also includes an unrelated commit to remove some unused code in `StyleComputer::for_each_property_expanding_shorthands`
> LibWeb: Don't fail on non-fill keyword in <border-image-slice>

- .github/workflows/ci.yml
- .github/workflows/js-artifacts.yml
- .github/workflows/lagom-template.yml
- .github/workflows/nightly-lagom.yml
- CMakePresets.json
I've set up a shared vcpkg source assets cache using Azurite. By default, it runs in read-only mode allowing anyone who builds Ladybird to use the cache to speed up downloads of source tarballs. This should alleviate some of the more slower vcpkgs downloads I've been seeing lately.
CI runs on master put vcpkg in readwrite mode, updating the cache for everyone.
> CI+CMake: Enable vcpkg source assets cache

- Libraries/LibWeb/WebAudio/AudioNode.cpp
- Libraries/LibWeb/WebAudio/AudioNode.h
- Tests/LibWeb/TestConfig.ini
- Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-audionode-interface/audionode-disconnect-audioparam.html
- Tests/LibWeb/Text/input/wpt-import/webaudio/the-audio-api/the-audionode-interface/audionode-disconnect.html
Destubs AudioNode::disconnect() and its related overloads.
Ensures that inverse connections are properly removed when disconnecting AudioNodeConnections.
EDIT: added associated WPTs as mentioned below, but have skipped them in `TestConfig.ini` until `::start_rendering()` is implemented
> LibWeb/WebAudio: Implement AudioNode::disconnect()

- Libraries/LibJS/Print.cpp
- Libraries/LibJS/Print.h
- Utilities/js.cpp
Fixes https://github.com/LadybirdBrowser/ladybird/issues/4947 by flushing stdout/sterr before using an unbuffered `AK::Stream` on them.
```sh
❯ bin/js -c 'print("foo"); print("bar");' | cat 
"foo"
"bar"
```
Adds a better name for the flag that disables the string quotes and escaping as discussed in https://github.com/LadybirdBrowser/ladybird/pull/4946. If this gets merged, https://github.com/devsnek/esvu/pull/69 and https://github.com/CanadaHonk/esvu/pull/7 will need to be modified.
> js: Improvements for eshost

- Tests/LibGfx/CMakeLists.txt
This needs the `windows` label applied to test, but I have confirmed `Windows_Sanitizer_CI` passes for me locally
> Tests/LibGfx: Enable file based tests on Windows

- Libraries/LibWeb/SVG/AttributeNames.h
- Libraries/LibWeb/SVG/SVGAnimatedNumber.cpp
- Libraries/LibWeb/SVG/SVGAnimatedNumber.h
- Libraries/LibWeb/SVG/SVGFEBlendElement.cpp
- Libraries/LibWeb/SVG/SVGFEFloodElement.cpp
- Libraries/LibWeb/SVG/SVGFEGaussianBlurElement.cpp
- Libraries/LibWeb/SVG/SVGFEGaussianBlurElement.h
- Libraries/LibWeb/SVG/SVGFEGaussianBlurElement.idl
- Libraries/LibWeb/SVG/SVGGradientElement.cpp
- Libraries/LibWeb/SVG/SVGStopElement.cpp
- Libraries/LibWeb/SVG/SVGStopElement.h
- Tests/LibWeb/Text/expected/SVG/svg-feGaussianBlur-stdDeviation.txt
- Tests/LibWeb/Text/input/SVG/svg-feGaussianBlur-stdDeviation.html
* Fixed an issue with SVGFEGaussianBlurElement, SVGFEFloodElement and SVGFEBlendElement not exposing their APIs;
* Implemented SVGAnimatedNumber so we now actually read things like ladybird.org's gaussian blur's standard deviation values instead of hardcoding it to 125 :^)
> LibWeb: Implement SVGAnimatedNumber

- Libraries/LibWeb/CMakeLists.txt
- Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveFactory.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ScriptSourceAttributeDirective.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ScriptSourceAttributeDirective.h
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ScriptSourceElementDirective.cpp
- Libraries/LibWeb/ContentSecurityPolicy/Directives/ScriptSourceElementDirective.h
- Libraries/LibWeb/Forward.h
Part 11 of splitting up https://github.com/LadybirdBrowser/ladybird/pull/2854
With script-src now implemented, these are the two subset directives for it.
> LibWeb/CSP: Implement the script-src-elem and script-src-attr directives

- Libraries/LibTest/TestSuite.cpp
We were already taking the "elapsed" part of the global timer, by subtracting the known runtime from that we always ended up with 0 milliseconds.
CC @ttrssreal
> Tests: Fix calculation of elapsed time in tests

- Libraries/LibWeb/Layout/FormattingContext.cpp
- Tests/LibWeb/Layout/expected/input-placeholder-with-line-height.txt
- Tests/LibWeb/Layout/expected/vertical-align-middle-with-padding.txt
- Tests/LibWeb/Layout/input/vertical-align-middle-with-padding.html
For `vertical-align: middle` and `vertical-align: text-bottom`, we used just the content height of the inline box to determine its alignment position. This caused incorrect positioning when padding is applied.
This fixes the button alignment on our GitHub page, as well as the login button for RoundCube webmail.
Fixes #290.
|--|--|
| <img width="487" height="54" alt="Screenshot 2025-07-12 at 13 56 20" src="https://github.com/user-attachments/assets/6f9bda02-9ced-4c5e-9752-c366c97abd5e" /> | <img width="481" height="46" alt="Screenshot 2025-07-12 at 13 53 45" src="https://github.com/user-attachments/assets/537ced55-5fa5-4761-ad2d-b8b182f0bcd0" /> |
| <img width="338" height="159" alt="Screenshot 2025-07-12 at 14 28 34" …
> LibWeb: Use margin box height for inline-block vertical alignment

- Libraries/LibWeb/HTML/Navigable.h
- Libraries/LibWeb/Painting/BackingStoreManager.cpp
Recently, we moved the backing store manager into Navigable, which means we now try to allocate a backing store for all navigables, including those corresponding to SVG image documents. This change disables that behavior for all navigables except top-level non-SVG traversables, because otherwise it causes issues when we stop repainting: the browser process was notified about an allocated backing stores that does not correspond to the page, and then all subsequent repaints are ignored until the window is resized.
> LibWeb: Skip backing store allocation for traversables created for SVG

- Libraries/LibWeb/Layout/FormattingContext.cpp
- Libraries/LibWeb/Layout/LayoutState.cpp
- Tests/LibWeb/Text/expected/css/small-aspect-ratio.txt
- Tests/LibWeb/Text/input/css/small-aspect-ratio.html
This fixes a crash in http://wpt.live/css/css-sizing/aspect-ratio/small-aspect-ratio-crash.html
> LibWeb: Avoid division by zero with small aspect ratios

- Libraries/LibWeb/ContentSecurityPolicy/Directives/DirectiveOperations.cpp
- Tests/LibWeb/Text/expected/wpt-import/content-security-policy/frame-src/frame-src-self-unique-origin.txt
- Tests/LibWeb/Text/expected/wpt-import/content-security-policy/img-src/img-src-self-unique-origin.txt
- Tests/LibWeb/Text/input/wpt-import/content-security-policy/frame-src/frame-src-self-unique-origin.html
- Tests/LibWeb/Text/input/wpt-import/content-security-policy/img-src/img-src-self-unique-origin.html
This fixes 2 CSP WPT tests, which previously crashed.
> LibWeb: Avoid accessing opaque origin port during CSP checks

- Meta/CMake/vcpkg/overlay-ports/curl/curl-issue-17917.patch
- Meta/CMake/vcpkg/overlay-ports/curl/portfile.cmake
See: https://github.com/curl/curl/issues/17917
This allows us to connect to https://developer.mozilla.org/ with HTTP/3 enabled.
Thanks to Tim Ledbetter (https://github.com/tcl3) for finding that we couldn't connect!
> Meta/curl: Add upstream patch for issue 17917

- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
The `shorthands_for_longhand`, `longhands_for_shorthand`, and `expanded_longhands_for_shorthand` methods can be pretty hot in profiles where we serialize a lot of CSS properties.
By returning a const reference to a static vector instead of allocating and returning a new vector every time we can avoid a decent amount of work.
Overall runtime for the particularly serialization heavy https://wpt.live/css/cssom/cssom-getPropertyValue-common-checks.html decreased by ~20% comparing before and after this change.
> LibWeb: Avoid vector creation getting {short,long}hands for CSS property

- Libraries/LibWeb/HTML/Parser/Entities.cpp
- Libraries/LibWeb/HTML/Parser/Entities.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateNamedCharacterReferences.cpp
This is part 2 of my follow-ups to https://github.com/LadybirdBrowser/ladybird/pull/3011 and what I subsequently wrote about in [Slightly better named character reference tokenization than Chrome, Safari, and Firefox](https://www.ryanliptak.com/blog/better-named-character-reference-tokenization/) (part 1 was https://github.com/LadybirdBrowser/ladybird/pull/5297).
For those that have read the article, this implementation is mostly what's described in the [DAFSA with first-two-character acceleration](https://www.ryanliptak.com/blog/better-named-character-reference-tokenization/#dafsa-with-first-two-character-acceleration) section, but I've since figured out a way to avoid the additional 8 KiB of data.
---
Introduces a few ad-hoc modifications to the DAFSA aimed to increase performance while …
> LibWeb/HTML: Improve data structure of named character reference data

- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Tests/LibWeb/Layout/expected/block-and-inline/img-as-block-with-box-sizing-border-box.txt
- Tests/LibWeb/Layout/input/block-and-inline/img-as-block-with-box-sizing-border-box.html
Before this change, we were always behaving as if box-sizing were content-box for block-level replaced element widths.
This fixes the squishy logo (top left of the page) on https://videolan.org/
Before:
After:
> LibWeb: Honor box-sizing for block-level replaced element widths

- Libraries/LibGfx/FontCascadeList.cpp
- Libraries/LibGfx/FontCascadeList.h
By keeping track of the enclosing range around all Unicode ranges of a FontCascadeList entry, we can quickly reject any code point that's outside all ranges.
This knocks font_for_code_point() from 7% to 3% in the profile when scrolling on https://screenshotone.com/
> LibGfx: Let FontCascadeList quickly reject out-of-range code points

- Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
- Tests/LibWeb/Crash/DOM/xhtml-namespace-change.xhtml
This adds a null check that I missed in #5429. This caused a crash in: http://wpt.live/dom/nodes/Document-createElement-namespace.html. Not all subtests behaved correctly when this test was imported, so I extracted the part that caused the crash into a crash test instead.
> LibWeb: Check parent node exists before checking its type

- Libraries/LibWeb/CSS/Default.css
- Libraries/LibWeb/CSS/Enums.json
- Libraries/LibWeb/CSS/Keywords.json
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/Layout/LineBuilder.cpp
- Tests/LibWeb/Layout/expected/table/th-default-text-align.txt
- Tests/LibWeb/Layout/input/table/th-default-text-align.html
Because we defined `th { text-align: center }` in our UA stylesheet, it received a higher precedence than inherited (inline) styles. Firefox deals with this by defining a custom `text-align` value that prioritizes any inherited value before defaulting to `text-align: center`.
We now do this as well :^)
Fixes the heading alignment on our organization page.
| Before | After|
|--|--|
| <img width="591" height="131" alt="image" src="https://github.com/user-attachments/assets/cc29653a-0544-4bc5-9c5d-4c901ef51604" /> | <img width="593" height="134" alt="image" src="https://github.com/user-attachments/assets/bb34858b-110d-45c3-935e-f8d32a6790c8" /> |
> LibWeb: Prioritize inheriting `text-align` for `<th>`

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/DOM/Node.cpp
Both functions schedule HTML event loop processing but that's unnecessary, because we schedule a rendering task that checks if style/layout needs an update 60/s anyway.
> LibWeb: Delete `schedule_style_update()` and `schedule_layout_update()`

- Libraries/LibWeb/XHR/FormData.cpp
- Tests/LibWeb/Text/expected/XHR/FormData-constructor-takes-name-and-value-of-submitter.txt
- Tests/LibWeb/Text/expected/wpt-import/xhr/formdata/constructor-submitter.txt
- Tests/LibWeb/Text/input/XHR/FormData-constructor-takes-name-and-value-of-submitter.html
This fixes the SSO buttons on OpenAI's login page giving "Unknown error"
> LibWeb: Include submitter name and value when constructing FormData

- .devcontainer/features/vcpkg-cache/install.sh
This enables our vcpkg asset cache in the devcontainer setup, protecting
CI jobs against flaky upstream tarball downloads.
> Devcontainer: Enable vcpkg asset cache for vcpkg cache feature

- Libraries/LibWeb/HTML/Window.cpp
- Libraries/LibWeb/HTML/Window.h
- Libraries/LibWeb/HTML/Window.idl
Corresponds to https://github.com/w3c/csswg-drafts/commit/94fdd8ab1e7fa6c9ee098cbf1ee22e8f3911636b
Somehow I've already got `CSSStyleProperties` in `ElementCSSInlineStyle.style`, so I'm not sure what happened there.
> LibWeb/HTML: Return CSSStyleProperties from getComputedStyle()

- Libraries/LibCrypto/Hash/HKDF.cpp
- Libraries/LibJS/Tests/builtins/TypedArray/Uint8Array.fromBase64.js
- vcpkg.json
Updating simdutf for a fix for handling invalid trailing padding characters.
Updated other packages while I'm here since this is a cache-busting change.
test262 diff:
```
Diff Tests:
test/built-ins/Uint8Array/fromBase64/last-chunk-invalid.js ❌ -> ✅
```
> Meta: Update vcpkg, including simdutf for a `Uint8Array.fromBase64` fix

- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Libraries/LibWeb/CSS/Transformation.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/geometry/DOMMatrix-001.txt
This gains us 2 WPT passes as we now correctly disallow relative lengths in more places in the `DOMMatrix` constructor.
> LibWeb: Move `Transformation::to_matrix` to new CSV resolve methods

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/HTML/BarProp.cpp
- Libraries/LibWeb/HTML/BrowsingContext.h
- Libraries/LibWeb/WebDriver/Actions.cpp
Likely we forgot to update `WeakPtr` to `GC::Ptr` after converting `BrowsingContext` to GC-allocated object.
> LibWeb: Use GC::Ptr for BrowsingContext pointer saved in Document

- Libraries/LibWebView/Autocomplete.cpp
This PR fixes #5493 by preventing autocomplete suggestions when typing file:// URLs in the address bar.
- Added a check to return early with empty suggestions when the query starts with "file://"
- Typing "file://" or any file URL (e.g., "file:///home/user") shows no suggestions
- Regular URLs continue to show autocomplete suggestions as normal
Fixes #5493
> LibWebView: Don't provide autocomplete suggestions for file:// URLs

- Libraries/LibWeb/CSS/CSSPropertyRule.h
- Libraries/LibWeb/CSS/Parser/Parser.cpp
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Tests/LibWeb/Text/expected/css/at-property-initial-value-background-color.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/attr-all-types.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-variables/variable-css-wide-keywords.txt
- Tests/LibWeb/Text/input/css/at-property-initial-value-background-color.html
This is my first contribution to Ladybird. As suggested by @AtkinsSJ, I started with a simple implementation that can be improved later. 
This PR adds a basic connection between `@property` definitions and `var()` usage. It's noticeable on sites using TailwindCSS classes like `translate-x-[-1]`.
**Before:** <img width="1502" height="735" alt="Before" src="https://github.com/user-attachments/assets/dab168a3-ec69-4faa-882f-4d7400a46be3" />
**After:** <img width="1502" height="735" alt="After" src="https://github.com/user-attachments/assets/e98c8345-f3b7-42cb-ad7e-2e4f16832803" />
> LibWeb/CSS: Add basic registered properties support with initial values

- Libraries/LibWeb/DOM/DocumentLoading.cpp
- Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
- Libraries/LibWeb/XML/XMLDocumentBuilder.h
- Libraries/LibXML/Parser/Parser.cpp
- Libraries/LibXML/Parser/Parser.h
- Tests/LibWeb/Text/expected/XHTML/CDATASection-PI-Comment-Nodes.txt
- Tests/LibWeb/Text/expected/wpt-import/css/cssom/xml-stylesheet-pi-in-doctype.txt
- Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Comment-in-doctype.txt
- Tests/LibWeb/Text/expected/wpt-import/dom/nodes/Node-lookupPrefix.txt
- Tests/LibWeb/Text/expected/wpt-import/dom/nodes/ProcessingInstruction-in-doctype.txt
- Tests/LibWeb/Text/input/XHTML/CDATASection-PI-Comment-Nodes.xhtml
- Tests/LibWeb/Text/input/wpt-import/css/cssom/xml-stylesheet-pi-in-doctype.xhtml
- Tests/LibWeb/Text/input/wpt-import/dom/nodes/Comment-in-doctype.xhtml
- Tests/LibWeb/Text/input/wpt-import/dom/nodes/Node-lookupPrefix.xhtml
- Tests/LibWeb/Text/input/wpt-import/dom/nodes/ProcessingInstruction-in-doctype.xhtml
This allows listeners to be notified when a CDATASection or
ProcessingInstruction is encountered during parsing. The non-listener
path still has the incorrect behavior of silently treating CDATASection
as Text nodes, but this allows listeners to handle them correctly.
Fixes: https://github.com/LadybirdBrowser/ladybird/issues/840
> LibXML: Add parser hooks for CDATASection and ProcessingInstructions

- Libraries/LibWeb/WebAssembly/WebAssembly.cpp
- Libraries/LibWeb/WebAssembly/WebAssembly.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/wpt-import/wasm/jsapi/constructor/instantiate-bad-imports.any.txt
- Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/bad-imports.js
- Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/constructor/instantiate-bad-imports.any.html
- Tests/LibWeb/Text/input/wpt-import/wasm/jsapi/constructor/instantiate-bad-imports.any.js
Fixes ~1000 WPT tests in `/wasm`. Full comparison log here:
[wasm.txt](https://github.com/user-attachments/files/21327822/wasm.txt)
Also causes ~30 "regressions" in `/wasm`. These were actually incorrectly passing previously:
```
▶ Unexpected subtest result in /wasm/core/data.wast.js.html:
│ FAIL [expected PASS] #53 Test that a WebAssembly module is uninstantiable
│   → assert_true: expected link error, observed LinkError: Data segment attempted to write to out-of-bounds memory (0) in memory of size 0
at Error
at assert_uninstantiable (http://web-platform.test:8000/wasm/core/js/harness/async_index.js:372:15)
at data_wast_js (http://web-platform.test:8000/wasm/core/js/data.wast.js:85:22)
at http://web-platform.test:8000/wasm/core/js/data.wast.js:186:3
```
(Despite the "expected link error" …
> LibWeb: A few Wasm IDL fixes

- Libraries/LibGfx/Bitmap.h
- Libraries/LibWeb/HTML/HTMLCanvasElement.cpp
- Libraries/LibWeb/HTML/HTMLCanvasElement.h
- Libraries/LibWeb/HTML/ImageBitmap.cpp
- Libraries/LibWeb/HTML/StructuredSerialize.cpp
- Libraries/LibWeb/HTML/StructuredSerializeTypes.h
- Libraries/LibWeb/HTML/WindowOrWorkerGlobalScope.cpp
- Libraries/LibWeb/Streams/ReadableByteStreamController.cpp
- Tests/LibWeb/Text/expected/HTML/image-bitmap-from-invalid-types-no-crash.txt
- Tests/LibWeb/Text/expected/wpt-import/html/infrastructure/safe-passing-of-structured-data/window-postmessage.window.txt
- Tests/LibWeb/Text/expected/wpt-import/html/webappapis/structured-clone/structured-clone.any.txt
This is the last remaining `[Serializable]` IDL.
To make {,de}serialization of `ImageBitmap` work we also had to add support for creating an `ImageBitmap` from a `HTMLCanvasElement` in `WindowOrWorkerGlobalScopeMixin::create_image_bitmap_impl()`.
The two first commits are unrelated to the main change.
> LibWeb: Add {,de}serialization + transfer steps for ImageBitmap + a few minor unrelated changes

- Libraries/LibWeb/Editing/ExecCommand.cpp
- Libraries/LibWeb/Page/EventHandler.cpp
- Libraries/LibWeb/UIEvents/InputEvent.cpp
- Libraries/LibWeb/UIEvents/InputEvent.h
- Tests/LibWeb/Text/expected/UIEvents/inputevent-gettargetranges.txt
- Tests/LibWeb/Text/input/UIEvents/inputevent-gettargetranges.html
This returns a list of ranges that would be affected by a change to the DOM if the input event is not cancelled.
This gets us +930 WPT subtest passes in the `input-events` directory. Unfortunately, these tests are not importable because they rely on testdriver. I've made a test that uses `internals` instead.
> LibWeb: Implement `InputEvent.getTargetRanges()`

- Documentation/Troubleshooting.md
> Documentation: Troubleshoot `double free` race condition on exit

- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/CSS/StyleComputer.h
Before this change we were running the CSS cascade machinery twice per element:
- First, to compute the "logical alias mapping context" based on writing-mode and pals.
- Then, to compute all properties.
This patch factors out the heaviest work from the cascade machinery to a separate step that can be run only once. This step will:
- Collect all the matching rules for the element
- Resolve custom properties for the element
We still perform the per-element cascade twice, but now this is hogging less than 1% of CPU time when typing on Discord (compared to 9% before.)
> LibWeb: Avoid duplicate work when computing style

- Libraries/LibWeb/CSS/Enums.json
- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/Properties.json
- Tests/LibWeb/Ref/expected/wpt-import/css/css-overflow/overflow-overlay-ref.html
- Tests/LibWeb/Ref/input/wpt-import/css/css-overflow/overflow-overlay.html
- Tests/LibWeb/Text/expected/wpt-import/css/css-text/text-justify/distribute-alias.tentative.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-text/text-justify/distribute-alias.tentative.html
[Legacy value aliases](https://drafts.csswg.org/css-cascade-5/#css-legacy-value-alias) are, for now, keywords that get swapped for other keywords at parse-time. Specifically there are two users of this now, at least according to [webdex](https://dontcallmedom.github.io/webdex/l.html#legacy%20value%20alias%40%40CSS%40dfn):
- `overlay` in `overflow` is an alias for `auto`, also applying to `overflow-x` and `overflow-y`.
- `distribute` in `text-justify` is an alias for `inter-character`.
`overflow: overlay` specifically showed up on bbc.co.uk.
Until there are more uses of this, it doesn't seem worth implementing a proper automatic system to handle them, but I've left some FIXMEs about that.
> LibWeb/CSS: Support legacy value aliases for the properties that have them

- Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
- Tests/LibWeb/Crash/SVG/zero-width-svg.html
Previously, an SVG with width of zero would have an intrinsic aspect ratio of zero. With this change, if an SVG has a width or height of zero, the intrinsic aspect ratio is determined by the SVG's viewbox.
This fixes crashes in these 2 WPT tests:
* http://wpt.live/css/css-grid/alignment/grid-item-aspect-ratio-stretch-3.html
* http://wpt.live/css/css-grid/alignment/grid-item-no-aspect-ratio-stretch-4.html
These tests still fail for reasons beyond the scope of this PR, so they can't be imported.
> LibWeb: Ignore zero width when calculating SVG intrinsic aspect ratio

- AK/String.cpp
- AK/String.h
- Libraries/LibWeb/CSS/Enums.json
- Libraries/LibWeb/CSS/Keywords.json
- Libraries/LibWeb/CSS/StyleValues/CounterStyleValue.cpp
- Libraries/LibWeb/Layout/ListItemMarkerBox.cpp
- Libraries/LibWeb/Painting/MarkerPaintable.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/cssom/serialize-values.txt
This PR adds support for `lower-greek` as a counter style.
I implemented a member function `greek_letter_from` in AK's `String` type as it appears that `bijective_base_from` doesn't handle multibyte characters correctly. I wasn't sure, but it may be better to implement a variant of `bijective_base_from` which accepts multibyte characters instead of having a seperate function for greek letters, as it'll allow us to add support for other styles like `georgian`. My only concern with this approach is where we would place the respective alphabets.
The test case for `lower-greek` in `css/cssom/serialize-values.html` passes. 
The test cases in `css/css-counter-styles/lower-greek/` appear to fail, but when testing cases like those in `css/css-counter-styles/upper-roman`, those fail too, so I'm …
> AK+LibWeb/CSS: Add `lower-greek` counter style

- Libraries/LibRegex/RegexByteCode.cpp
- Libraries/LibRegex/RegexMatch.h
- Libraries/LibRegex/RegexMatcher.cpp
- Tests/LibRegex/TestRegex.cpp
- Tests/LibWeb/Text/expected/wpt-import/encoding/encodeInto.any.txt
- Tests/LibWeb/Text/expected/wpt-import/url/IdnaTestV2.window.txt
- Tests/LibWeb/Text/expected/wpt-import/url/a-element-origin.txt
- Tests/LibWeb/Text/expected/wpt-import/url/url-constructor.any.txt
- Tests/LibWeb/Text/expected/wpt-import/url/url-origin.any.txt
- Tests/LibWeb/Text/expected/wpt-import/url/urlsearchparams-sort.any.txt
- Tests/LibWeb/Text/expected/wpt-import/url/urlsearchparams-stringifier.any.txt
- Tests/LibWeb/Text/expected/wpt-import/urlpattern/urlpattern.any.txt
Fixes #5549
This lets Discord render emoji as it sees fit.
Before:
After:
> LibRegex: Compare code units (not code points) in non-Unicode char range

- Libraries/LibWeb/CSS/StyleValues/FilterValueListStyleValue.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/filter-effects/parsing/filter-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/filter-effects/parsing/filter-parsing-valid.txt
At some point `hue-rotate` was changed to use `AngleOrCalculated` rather than `Angle`, but `Angle` was still being used in a `visit`, which otherwise defaulted to zero. This caused all `hue-rotate` angles to serialize to zero.
> LibWeb: Use correct angle type when serializing hue-rotate filter values

- Libraries/LibWeb/HTML/ImageBitmap.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/canvas/element/manual/imagebitmap/canvas-ImageBitmap-close.txt
- Tests/LibWeb/Text/input/wpt-import/html/canvas/element/manual/imagebitmap/canvas-ImageBitmap-close.html
- Tests/LibWeb/Text/input/wpt-import/html/canvas/element/manual/imagebitmap/worker-onmessage-noop.js
This fixes a crash in the imported WPT test.
> LibWeb: Serialize empty ImageBitmap data as null

- Libraries/LibJS/Runtime/RegExpObject.cpp
- Libraries/LibJS/Tests/builtins/RegExp/RegExp.js
- Libraries/LibRegex/RegexByteCode.cpp
- Libraries/LibRegex/RegexMatcher.cpp
There apparently is a bit of a disconnect between the spec asking us to construct the pattern using code points and LibRegex not being able to swallow those. Whenever we had multi-byte code points in the pattern and tried to match that in unicode mode, we would fail.
Change the parser to encode all non-ASCII code units. Fixes 2 test262 cases in `language/literals/regexp`.
> LibRegex+LibJS: Fix non-ASCII unicode regex matching

- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Tests/LibWeb/Ref/expected/css/gradient-calc-inside-stop-color-ref.html
- Tests/LibWeb/Ref/input/css/gradient-calc-inside-stop-color.html
Before this change, calc() would resolve to different types depending on the nearest containing value context. This meant that rgb(calc(), ...) by itself worked correctly due to fallbacks, but rgb(calc(), ...) inside e.g a linear-gradient would create a calc() value that resolves to a length, which subsequently got rejected by the color value parser.
Fixing this makes various little gradients show up on Discord.
Before:
After:
> LibWeb: Always parse calc() inside CSS color functions consistently

- Libraries/LibWebSocket/WebSocket.cpp
- Libraries/LibWebSocket/WebSocket.h
- Services/RequestServer/WebSocketImplCurl.cpp
- Services/RequestServer/WebSocketImplCurl.h
`curl_easy_recv` must be called in a loop until it returns EAGAIN, because it may cache data, but only activate the read notifier once.
Additionally, the data received can contain multiple WebSocket frames and only activate the notifier once, so we have to keep reading frames until there isn't enough data.
We also have to do this immediately after connecting a WebSocket, since the server may immediately send data when the WebSocket opens and before we create the read notifier.
This makes Discord login faster and more reliable, and makes Discord activities start loading.
> RequestServer+LibWebSocket: Drain underlying socket and resulting frames

- Libraries/LibWeb/HTML/FormAssociatedElement.h
- Libraries/LibWeb/HTML/HTMLButtonElement.cpp
- Libraries/LibWeb/HTML/HTMLButtonElement.h
- Libraries/LibWeb/HTML/HTMLImageElement.cpp
- Libraries/LibWeb/HTML/HTMLImageElement.h
- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Libraries/LibWeb/HTML/HTMLInputElement.h
- Libraries/LibWeb/HTML/HTMLObjectElement.cpp
- Libraries/LibWeb/HTML/HTMLObjectElement.h
- Libraries/LibWeb/HTML/HTMLOutputElement.cpp
- Libraries/LibWeb/HTML/HTMLOutputElement.h
- Libraries/LibWeb/HTML/HTMLSelectElement.cpp
- Libraries/LibWeb/HTML/HTMLSelectElement.h
- Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Libraries/LibWeb/HTML/HTMLTextAreaElement.h
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-patternMismatch.txt
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/the-input-element/email.txt
This implements the missing part of the value sanitization algorithm for email inputs with the multiple attribute.
> LibWeb/HTML: Sanitize email input with multiple attribute

- Libraries/LibWeb/WebSockets/WebSocket.cpp
This makes the WebSockets on https://pro.kraken.com/app/trade/btc-usd happier, but the page doesn't quite work yet.
> LibWeb/WebSocket: Include the User-Agent header on connection

- Libraries/LibWeb/Animations/Animatable.cpp
- Libraries/LibWeb/CSS/StyleComputer.cpp
This lets us play animations and transitions when time values are stored in the form of calculated values, such as `calc(1s + 500ms)`.
Fixes #5570.
> LibWeb: Resolve calculated time values in animations and transitions

- .github/workflows/ci-windows.yml
- .github/workflows/flatpak-template.yml
- .github/workflows/nightly-lagom.yml
This will build both aarch64 and x86_64 flatpaks nightly. The test jobs
I did with the default GitHub runners took ~1h30m for aarch64 and
~2h30m for x86_64, but this will hopefully improve over time as the
cache is built up. And be better time-wise on the blacksmith runners.
Disk space is a large concern with these flatpak builds. A naive script
on my local machine showed that we needed a max of 10.3 GiB of free
space for the x86_64 build, with clang as the compiler. For some reason,
building with default gcc 14 uses more disk space than that, bumping
up against the default 14 GiB free space limit guaranteed by GitHub for
their default runners.
Here's a link to a successful build on my fork, albeit with a slightly different workflow file (no workflow call, gh standard runners, etc) …
> CI: Add nightly flatpak workflow 

- Libraries/LibRegex/RegexByteCode.cpp
- Tests/LibRegex/TestRegex.cpp
This prevents empty matches from overwriting non-empty captures in quantified alternations. Fixes patterns like `(a|a?)+` where the optional branch would incorrectly overwrite meaningful captures with empty strings.
> LibRegex: Fix capture groups in quantified alternations

- AK/Span.h
- AK/StringConversions.cpp
- AK/TypedTransfer.h
- AK/Utf16StringBase.h
- AK/Utf16View.h
- Libraries/LibGfx/Color.cpp
- Libraries/LibGfx/Color.h
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/Editing/Commands.cpp
- Libraries/LibWeb/Editing/Commands.h
- Libraries/LibWeb/Editing/ExecCommand.cpp
- Libraries/LibWeb/Editing/Internal/Algorithms.cpp
- Libraries/LibWeb/Editing/Internal/Algorithms.h
- Tests/AK/TestSpan.cpp
- Tests/AK/TestUtf16View.cpp
- Tests/LibWeb/Text/expected/Editing/execCommand-insertText.txt
- Tests/LibWeb/Text/input/Editing/execCommand-insertText.html
Both sides of the Editing internals now have to deal with some awkward converting between UTF-8 and UTF-16, but the upside is that it immediately exposed an issue with the `insertText` command: instead of dealing with code units, it was iterating over code points causing the selection to be updated only once instead of twice. This resulted in the final selection potentially ending up in between a surrogate pair.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/5547 (pasting/typing surrogate pairs).
> LibWeb: Convert Editing API internals to UTF-16

- Libraries/LibWeb/Painting/Command.h
- Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.h
- Libraries/LibWeb/Painting/StackingContext.cpp
- Tests/LibWeb/Ref/expected/css/stacking-context-with-unclipped-transformed-descendant-ref.html
- Tests/LibWeb/Ref/input/css/stacking-context-with-unclipped-transformed-descendant.html
Skia allows you to pass a bounding rect to its saveLayer() function as an optimization when you know that you won't paint outside those bounds. Unfortunately, we were passing a too-small rectangle that didn't take into account transformed descendants, etc.
For now, simply pass null instead of a bounding rect. This way, Skia figures it out internally. It may allocate larger temporary bitmaps than needed this way, but at least we get more correct results. I've left re-enabling the optimization as a FIXME in the code.
This fixes unwanted clipping in various parts of the Discord UI.
Before:
After:
> LibWeb: Don't clip descendants outside stacking context root rect

- Libraries/LibWeb/Painting/ClipFrame.cpp
- Libraries/LibWeb/Painting/ClipFrame.h
- Libraries/LibWeb/Painting/DisplayList.cpp
- Libraries/LibWeb/Painting/DisplayList.h
Fixes race condition introduced in eed47acb when rendering thread accesses ScrollFrame that could be mutated in the middle of rasterization by the main thread, resulting in broken rendering.
Fixes https://github.com/LadybirdBrowser/ladybird/issues/5553
> LibWeb: Use scroll state from snapshot while applying clip rectangles

- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Text/expected/Wasm/WebAssembly-instantiate.txt
- Tests/LibWeb/Text/expected/wpt-import/wasm/jsapi/global/constructor.any.txt
Gives us 20 additional WPT subtest passes in `wasm/jsapi`.
> LibWeb: Do not use namespace in interface names

- Libraries/LibWeb/HTML/DOMParser.cpp
- Tests/LibWeb/Text/expected/DOM/DOMParser-xml-document.txt
- Tests/LibWeb/Text/expected/wpt-import/domparsing/DOMParser-parseFromString-xml.txt
- Tests/LibWeb/Text/input/wpt-import/domparsing/DOMParser-parseFromString-xml.html
The HTML specification does not explicitly require a specific return type for parseFromString(),
but according to Web Platform TestsDOMParser-parseFromString.html, the expected return value for
XML MIME types is a Document—not an XMLDocument.
> LibWeb: Return base Document for non-HTML parses

- Libraries/LibWeb/DOM/EditingHostManager.cpp
Noticed that ctrl+right was jumping by characters, not words
> LibWeb: Invoke correct word-jumping method in EditingHostManager

- Libraries/LibCore/Timer.cpp
- Libraries/LibWebView/ViewImplementation.cpp
- Libraries/LibWebView/ViewImplementation.h
- Services/WebContent/ConnectionFromClient.cpp
- Services/WebContent/ConnectionFromClient.h
- Services/WebContent/PageClient.cpp
- Services/WebContent/PageClient.h
- Services/WebContent/WebContentServer.ipc
- UI/AppKit/Application/ApplicationDelegate.mm
- UI/AppKit/Interface/LadybirdWebView.h
- UI/AppKit/Interface/LadybirdWebView.mm
- UI/AppKit/Interface/LadybirdWebViewBridge.cpp
- UI/AppKit/Interface/LadybirdWebViewBridge.h
- UI/AppKit/Interface/TabController.mm
- UI/Qt/BrowserWindow.cpp
- UI/Qt/BrowserWindow.h
- UI/Qt/Tab.cpp
- UI/Qt/WebContentView.cpp
- UI/Qt/WebContentView.h
This allows us to paint web content at, for example, 120 FPS. This affects all painting, whether it's scrolling or driving a WebGL application with requestAnimationFrame.
https://github.com/user-attachments/assets/7a44cada-17ad-4974-a223-4ee1fc72078d
> LibWeb+LibWebView+WebContent+UI: Set the paint interval to the refresh rate of the current screen

- Libraries/LibWeb/WebSockets/WebSocket.cpp
WebSocket close codes can be `1000` or `3000-4999` according to the [whatwg spec](https://websockets.spec.whatwg.org//#dom-websocket-close).
> LibWeb: Fix acceptable WebSocket close code range

- UI/AppKit/Interface/LadybirdWebView.mm
- UI/Qt/WebContentView.cpp
- UI/Qt/WebContentView.h
Previously, when the mouse left the WebView, the currently hovered node would remain hovered (including the scroll bar). This felt a bit awkward and is not how other browsers behave.
Before:
https://github.com/user-attachments/assets/35b223fa-5958-4299-9e6f-06aa95cddf8c
After:
https://github.com/user-attachments/assets/f7e7af43-46f5-40b4-a3ef-a534f975ee86
(Note this doesn't trigger while the mouse is pressed down, so you can still click-and-drag the scroll bar outside of the view).
> UI: Inform WebContent when the mouse leaves the WebView widget

- Libraries/LibGfx/VulkanContext.cpp
Coverity static analysis reports that the code that scans the queue families for one that has the graphics bit, can be -1 if none are found, which could cause a problem when the -1 (signed) value is used later as an index in a uint32_t (unsigned) variable.
Its not immediately clear how often this could occur, not finding a queue family with the graphics bit, but adding some protecting just in case.
> LibGfx: VulkanContext coverity reports integer_overflow on index

- Tests/LibWeb/test-web/Application.cpp
- Tests/LibWeb/test-web/Application.h
- Tests/LibWeb/test-web/main.cpp
My intention was to use this to find flakes that depend on the order tests are executed. I wasn't able to find any instances of this, but the option still seems like it may be useful.
> test-web: Add an option to randomize the test order

- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Tests/LibWeb/Layout/expected/block-and-inline/float-with-negative-margin-containing-block.txt
- Tests/LibWeb/Layout/input/block-and-inline/float-with-negative-margin-containing-block.html
In 89ba00304ce8c022b7cdd47be16759bf8dc008b4, the box' X position was capped at 0 to prevent negative X positions to act as if there were intruding floats on the left side. Instead, we need to check whether the left side float intrusion we are going to calculate matters at all - because if there's no matching float box, the intrusion is always going to be 0 and we don't need to take the box' X position into account.
Fixes the floating publication images on https://lexfridman.com/.
CC @awesomekling
> LibWeb: Allow negative margins to influence inline offset after float

- Libraries/LibRegex/RegexOptimizer.cpp
- Tests/LibRegex/TestRegex.cpp
Not accounting for opcode size when calculating incoming jump edges meant that we were merging nodes where we otherwise shouldn't have been, for example `/.*a|.*b/`
> LibRegex: Account for opcode size when calculating incoming jump edges

- AK/IPv6Address.h
- Tests/AK/TestIPv6Address.cpp
This disallows parsing IPv4 mapped IPv6 address strings with multiple compression prefixes.  Tests are provided for the updated functionality.
> AK: Resolve TODO in IPv6Address for IPv4 mapped IPv6 prefixes

- Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Libraries/LibWeb/Fetch/Infrastructure/FetchRecord.cpp
- Libraries/LibWeb/Fetch/Infrastructure/FetchRecord.h
- Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.h
- Libraries/LibWeb/HTML/Scripting/Environments.cpp
- Libraries/LibWeb/HTML/Scripting/Environments.h
Otherwise we end up holding on to every fetch record indefinitely.
Found by analyzing GC heap graphs on Discord.
> LibWeb: Make ESO "fetch group" weakly reference the fetch records

- Libraries/LibWeb/CSS/CSSStyleSheet.cpp
- Libraries/LibWeb/CSS/CSSStyleSheet.h
- Libraries/LibWeb/CSS/FontFace.cpp
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/CSS/StyleComputer.h
- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
This allows them to keep style sheets alive while loading fonts for them. Fixes some GC crashes seen on the WPT WOFF2 tests after 66a19b85501dad8c0bfc5577b8d0b835877ad0dc stopped FetchRecord leaks from keeping various other things alive.
> LibWeb: Make StyleComputer and FontLoader GC-allocated

- Libraries/LibWeb/Editing/Commands.cpp
- Libraries/LibWeb/Editing/Internal/Algorithms.cpp
- Libraries/LibWeb/Editing/Internal/Algorithms.h
The `RecordedNodeValue` struct contains a `GC::Ref` to a DOM node, which might disappear as a result of a garbage collection. For example, during the "outdent" command, we record nodes, split the parent of those nodes potentially resulting in all kinds of DOM changes, and then try to restore the nodes' values. This caused a crash in the `editing/run/outdent.html` WPT subtests.
By returning a `ConservativeVector`, we make sure the `GC::Ref` gets marked during sweeps and nodes do not suddenly disappear.
CC @kalenikaliaksandr @tcl3
> LibWeb: Use ConservativeVector for recorded node values in Editing API

- Meta/WPT.sh
Previously, importing tests would fail if the WPT repository wasn't already cloned.
> Meta: Ensure WPT repository exists before attempting to import tests

- Libraries/LibWeb/Painting/PaintableBox.cpp
Makes the cursor less blurry looking.
`draw_rect` renders the outline of a rectangle. `fill_rect` seems like a better option for rendering the cursor.
> LibWeb: Improve cursor appearance

- Libraries/LibWeb/Page/Page.h
- Services/WebContent/ConnectionFromClient.cpp
- UI/AppKit/Application/ApplicationDelegate.mm
- UI/AppKit/Interface/TabController.h
- UI/AppKit/Interface/TabController.mm
- UI/Qt/BrowserWindow.cpp
- UI/Qt/BrowserWindow.h
- UI/Qt/Tab.cpp
- UI/Qt/Tab.h
Page::is_same_origin_policy_enabled is unused, and the original FIXME has been implemented.
> LibWeb+WebContent+UI: Remove unused same-origin policy toggle

- Libraries/LibWeb/Painting/DisplayList.cpp
- Libraries/LibWeb/Painting/DisplayListCommand.h
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Tests/LibWeb/Text/expected/display_list/simple-overflow-hidden.txt
Output display list dumps with an indentation level to show balanced commands. It makes it much easier to see what is happening between e.g. PushStackingContext and PopStackingContext, or SaveLayer and Restore.
> LibWeb: Add indentation to display list dumps

- Libraries/LibWeb/DOM/Element.h
- Libraries/LibWeb/HTML/FormControlInfrastructure.cpp
- Meta/import-wpt-test.py
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/attributes-common-to-form-controls/dirname-only-if-applies.txt
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/attributes-common-to-form-controls/dirname-only-if-applies.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/attributes-common-to-form-controls/resources/dirname-iframe.html
- Tests/LibWeb/Text/input/wpt-import/html/semantics/forms/attributes-common-to-form-controls/resources/dirname.js
This commit changes form data to only include the direction of auto directionality form associated elements.
This fixes [this test](http://wpt.live/html/semantics/forms/attributes-common-to-form-controls/dirname-only-if-applies.html), but I struggled to import the test. It submits the form in an iframe to check the search parameters, but when running the test from a file, this fails because the iframe is a cross-origin object. Changing the action attribute of the form from `resources/dirname-iframe.html` to `.` allows the test to run, but I am not sure if it is fine to change imported WPT tests.
> LibWeb/HTML: Only include direction if dirname applies

- Base/res/ladybird/about-pages/settings/search.js
This PR fixes a runtime issue in `addCustomSearchEngine` by replacing `const` with `let` in a for loop to allow correct iteration and engine name comparison.
> Base: Stop relying on const-ness not being enforced by LibJS

- Libraries/LibWeb/HTML/HTMLImageElement.h
- Libraries/LibWeb/Page/EventHandler.cpp
Previously, the value of the `src` tag would always be used as the image source URL when requesting an image context menu, which may not be correct if an image uses a `srcset` or has a parent picture tag.
Fixes #5689 
Here's a demo of the fixed behavior on: https://jpegxl.info
https://github.com/user-attachments/assets/e0b45a65-7970-4469-be02-65cc83209a8e
As far as I can tell there isn't an easy way to add an automated test for this.
> LibWeb: Ensure image context menu uses the correct image source

- Libraries/LibGfx/TextLayout.cpp
- Tests/LibWeb/Layout/expected/letter-spacing-end-of-line-001.txt
- Tests/LibWeb/Layout/expected/tab-size-letter-spacing.txt
Previously we would omit the letter spacing for the end glyph of each chunk in a misguided attempt to conform to the spec's instruction that we "really should not append letter spacing to the right or trailing edge of a line", this behaviour can be removed entirely as other browsers (Firefox, Chrome) don't implement it either.
> LibWeb: Respect `letter-spacing` for last glyph of each chunk

- Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
Very minor cleanup of LibWeb/Crypto:
- Use Base64 helpers better
- Remove dangling TODO/FIXMEs
- Update spec comments
> LibWeb/Crypto: Minor cleanup

- Libraries/LibWeb/CSS/CSS.cpp
- Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-properties-values-api/at-property-cssom.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/attr-all-types.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-variables/variable-css-wide-keywords.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-properties-values-api/at-property-cssom.html
All logic related to initial values in `@property` should be now complete.
Proper handling of inherited values and detection of computational independence will be addressed in future PRs.
> LibWeb/CSS: Finish initial `@property` values

- Libraries/LibWeb/ServiceWorker/Job.cpp
The spec language specifies 'Set maxScopeString to "/", followed by the strings in XXXX’s path (including empty strings), separated from each other by "/"': That is, adjacent components are separated by a '/', but the last component does not get a trailing '/'.
This resulted in the generated scope string ending with '//' in some cases, incorrectly tripping the 'Service-Worker-Allowed' security check.
Found this while investigating some unrelated WPT failures.
> LibWeb: Remove extraneous trailing '/' from service worker script scope

- Libraries/LibWeb/SVG/SVGSVGElement.cpp
This was accidentally included in #5418.
Oops :sweat_smile:
> LibWeb: Remove unnecessary debug logging from `SVGSVGElement`

- Libraries/LibWeb/CSS/ComputedProperties.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/calc-z-index-fractions-001.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-values/calc-z-index-fractions-001.html
Previously we would just cast to an int.
Gains us 3 WPT tests.
> LibWeb: Correctly round non-integer z-indexes

- Tests/LibWeb/add_libweb_test.py
Creating the image is left as an exercise to the user, but this saves some copypasta when adding a new test.
> Tests/LibWeb: Generate screenshot test boilerplate in add_libweb_test.py

- Libraries/LibWeb/Page/EventHandler.cpp
- Libraries/LibWeb/Page/EventHandler.h
Updating the hovered node may fire events, and so we can't assume the
layout and paintable nodes we've found via hit testing will be valid
after doing it.
> LibWeb: Defer updating hovered node until end of mouse event handling

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/HTML/Navigable.cpp
- Services/WebContent/PageClient.cpp
- Services/WebContent/PageClient.h
Before this change we were re-evaluating media queries on every frame which adds up in 1-4% in profiles on Discord.
> Re-evaluate media queries only when things they depend on change

- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Libraries/LibWeb/Layout/FormattingContext.cpp
- Libraries/LibWeb/Layout/FormattingContext.h
- Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Libraries/LibWeb/Layout/LayoutState.cpp
- Tests/LibWeb/Layout/expected/flex/aspect-ratio-and-cyclic-percentages-row.txt
- Tests/LibWeb/Layout/expected/flex/aspect-ratio-with-percentage-width-and-height.txt
- Tests/LibWeb/Layout/input/flex/aspect-ratio-and-cyclic-percentages-row.html
- Tests/LibWeb/Layout/input/flex/aspect-ratio-with-percentage-width-and-height.html
> Fix two aspect-ratio bugs that were breaking blacksmith.sh

- Tests/LibWeb/test-web/Fuzzy.cpp
- Tests/LibWeb/test-web/Fuzzy.h
- Tests/LibWeb/test-web/main.cpp
Main thing here is to report the fuzzy difference even if we're not doing a fuzzy test, so that we can more easily know what the configuration should be.
> Tests: Improve fuzzy test reports

- Libraries/LibWeb/Page/EventHandler.cpp
Instead of the currently hovered element.
cc @AtkinsSJ
> LibWeb: Use the soon-to-be hovered element for tooltip notifications

- Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Tests/LibWeb/Layout/expected/flex/cross-alignment-when-nested-in-gfc.txt
- Tests/LibWeb/Layout/input/flex/cross-alignment-when-nested-in-gfc.html
- Tests/LibWeb/Text/expected/wpt-import/css/css-flexbox/dynamic-grid-flex-abspos.txt
FFC expects parent formatting context to mark size as definite if that's the case, because otherwise it cannot figure cross line size correctly. Fixes incorrect alignment when FFC is nested in GFC.
Progress on https://web.telegram.org/a/ layout.
> LibWeb: Mark width & height of grid item definite before inside layout

- Libraries/LibWeb/Internals/Internals.cpp
- Libraries/LibWeb/Internals/Internals.h
- Libraries/LibWeb/Internals/Internals.idl
- Libraries/LibWeb/SVG/SVGElement.cpp
- Libraries/LibWeb/SVG/SVGUseElement.cpp
- Tests/LibWeb/Text/expected/Internals/getShadowRoot.txt
- Tests/LibWeb/Text/expected/SVG/removeChild-on-ancestor-of-use-element.txt
- Tests/LibWeb/Text/expected/SVG/use-shadowRoot-closed.txt
- Tests/LibWeb/Text/input/Internals/getShadowRoot.html
- Tests/LibWeb/Text/input/SVG/removeChild-on-ancestor-of-use-element.html
- Tests/LibWeb/Text/input/SVG/use-shadowRoot-closed.html
See individual commits! Improves https://cal.com/
Before:
After:
> Fix some SVG use element bugs for cal.com

- Libraries/LibWeb/ContentSecurityPolicy/Violation.cpp
- Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Libraries/LibWeb/Fetch/Fetching/Fetching.h
- Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
- Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.h
- Libraries/LibWeb/Fetch/Request.cpp
This pulls in a few changes from the Fetch spec:
LibWeb: Define stream variable before using it:
- https://github.com/whatwg/fetch/pull/1817
LibWeb: Replace request's "window" with "traversable for user prompts" 
- https://github.com/whatwg/fetch/pull/1823
LibWeb: Implement AO populate request from client
LibWeb: Align Fetching chapter's "To fetch" with latest spec changes
- https://github.com/whatwg/fetch/pull/1793
> LibWeb: Align with parts of the Fetch specification steps

- Libraries/LibWeb/CSS/StyleValues/CalculatedStyleValue.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/calc-catch-divide-by-0.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/calc-infinity-nan-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/calc-infinity-nan-serialize-angle.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/calc-infinity-nan-serialize-length.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/calc-infinity-nan-serialize-number.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/calc-infinity-nan-serialize-time.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/round-mod-rem-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/signed-zero.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-values/signs-abs-serialize.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-values/calc-catch-divide-by-0.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/calc-infinity-nan-computed.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/calc-infinity-nan-serialize-angle.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/calc-infinity-nan-serialize-number.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/calc-infinity-nan-serialize-time.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/signed-zero.html
- Tests/LibWeb/Text/input/wpt-import/css/css-values/signs-abs-serialize.html
This PR improves our handling of `NaN` and `Infinity` in the following CSS functions:
- `min()`
- `max()`
- `round()`
- `clamp()`
Gains us 30 WPT tests.
> LibWeb: Improve handling of non-finite values in calcs

- Libraries/LibWeb/SVG/SVGFilterElement.cpp
This prevents an unknown filter debug message would be printed for comments.
> LibWeb: Ignore all `CharacterData` nodes when evaluating filters

- Libraries/LibRequests/NetworkError.h
- Libraries/LibRequests/RequestClient.cpp
- Libraries/LibRequests/RequestClient.h
- Libraries/LibWeb/Loader/ResourceLoader.cpp
- Libraries/LibWeb/Loader/ResourceLoader.h
- Libraries/LibWeb/WebSockets/WebSocket.cpp
- Libraries/LibWebView/Application.cpp
- Services/RequestServer/ConnectionFromClient.cpp
- Services/RequestServer/ConnectionFromClient.h
- Services/RequestServer/RequestServer.ipc
- Services/WebContent/ConnectionFromClient.cpp
- Services/WebContent/ConnectionFromClient.h
- Services/WebContent/WebContentServer.ipc
- Services/WebContent/main.cpp
If RequestServer heroically dies, we now re-establish UI and WebContent connections.
https://github.com/user-attachments/assets/8713f320-1c52-404a-8dd8-3a91f181a1e6
> LibWeb+LibWebView+RequestServer: Gracefully handle RequestServer death

- Libraries/LibWeb/Page/EventHandler.cpp
- Tests/LibWeb/Text/expected/double-click-password.txt
- Tests/LibWeb/Text/input/double-click-password.html
This matches the behavior of other browsers, and hides any indication of word boundaries in the password.
Fixes #5795
> LibWeb: Select the entire input when double clicking password fields

- AK/StringUtils.cpp
- AK/Utf16View.cpp
- AK/Utf16View.h
In the following synthetic benchmark, the simdutf version is 4x faster:
```c++
BENCHMARK_CASE(find)
{
auto string = u"😀Foo😀Bar"sv;
for (size_t i = 0; i < 100'000'000; ++i)
(void)string.find_code_unit_offset('a');
}
```
> AK: Use simdutf for searching strings for a single code unit

- Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Libraries/LibWeb/Fetch/Infrastructure/HTTP.h
- Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.cpp
- Libraries/LibWeb/Fetch/Infrastructure/HTTP/Requests.h
- Libraries/LibWeb/Fetch/Infrastructure/HTTP/Responses.h
- Libraries/LibWeb/HTML/Navigable.cpp
LibWeb: Pass top-level navigation initiator origin to Fetch's Request
- https://github.com/whatwg/html/pull/10991
LibWeb: Update Fetch's compute the redirect-taint concept
- https://github.com/whatwg/fetch/pull/1807
> LibWeb: A couple fetch/navigables spec changes

- Libraries/LibWeb/HTML/HTMLDetailsElement.cpp
I did this back in April then never PRed it for some reason. :sweat_smile:
> LibWeb/HTML: Add missing if to `<details>` attribute_changed() logic

- Libraries/LibWeb/Layout/FormattingContext.cpp
- Tests/LibWeb/Layout/expected/grid/replaced-box-with-percentage-max-width-2.txt
- Tests/LibWeb/Layout/input/grid/replaced-box-with-percentage-max-width-2.html
Brings back some code removed in 652a457, but this time with explanation from https://www.w3.org/TR/css-sizing-3 spec.
> LibWeb: Fix cyclic percentage resolution in calculate_min_content_width

- Libraries/LibWeb/DOM/Element.cpp
- Tests/LibWeb/Text/expected/focus-shouldIndicateFocus.txt
- Tests/LibWeb/Text/input/focus-shouldIndicateFocus.html
This was a misinterpretation of the spec; we should only indicate focus if the form associated element supports keyboard input, for which FormAssociatedTextControlElement is a much better match.
> LibWeb: Don't indicate focus for all form associated elements

- Libraries/LibWeb/HTML/HTMLFormElement.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/selectors/user-valid.txt
- Tests/LibWeb/Text/input/wpt-import/css/selectors/user-valid.html
There were some `set_user_validity(false)`s when they should've been `set_user_validity(true)`s.
> LibWeb: Correct typos for user validity of form elements on submission

- Libraries/LibWeb/Page/EventHandler.cpp
- Tests/LibWeb/Text/expected/selection-on-rendered-text.txt
- Tests/LibWeb/Text/input/selection-on-rendered-text.html
This effectively reverts da26941b505ea3a2aab1dae99c3a6d648f4222a9.
When the user double-clicks a word on screen, they are interacting with the rendered text, which has e.g. whitespace collapsing applied. If we acquire word boundaries from the raw text, the resulting selection is not right.
With the following page:
```html
<p id="text">Lorem     ipsum dolor sit amet</p>
```
Double-clicking the word "ipsum" would previously render as:
It now renders as:
We still have issues with acquiring the right selection via APIs such as `document.getSelection`. The offsets computed here are effectively then applied to the raw text. But this issue is present all over EventHandler and this patch at least makes the selection visually accurate.
> LibWeb: Use rendered text to find word boundaries when double-clicking

- Libraries/LibWeb/Editing/Commands.cpp
- Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Tests/LibWeb/Text/expected/Editing/execCommand-forwardDelete.txt
- Tests/LibWeb/Text/expected/input-delete.txt
- Tests/LibWeb/Text/input/Editing/execCommand-delete.html
- Tests/LibWeb/Text/input/Editing/execCommand-forwardDelete.html
- Tests/LibWeb/Text/input/input-delete.html
We currently delete a single code unit. If the user presses backspace on a multi code point emoji, they are going to expect the entire emoji to be removed. This now matches the behavior of Chrome and Firefox.
Before:
https://github.com/user-attachments/assets/1ed48740-bb48-4e50-8f67-67838995826a
After:
https://github.com/user-attachments/assets/815d9a80-6f05-42b8-b290-5ce502bbda73
> LibWeb: Delete entire graphemes when the delete/backspace key is pressed

- Libraries/LibWeb/Painting/PaintableBox.cpp
Previously we would paint the cursor the entire height of the text fragment - this didn't look great with large line-heights. Now we only paint it the height of the actual text, with the top of the cursor aligning with the font "ascent" and the bottom the "descent".
Before:
After:
> LibWeb: Make text cursor same height as text

- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/DOM/AbstractElement.cpp
- Libraries/LibWeb/DOM/AbstractElement.h
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
- Tests/LibWeb/Layout/expected/slot-style-inheritance.txt
- Tests/LibWeb/Layout/input/slot-style-inheritance.html
When a subtree is projected through a slot, its root now inherits style from the slot's parent, rather than the parent of the unprojected root.
This fixes a ton of subtle issues, and is very noticeable on Reddit.
Before:
After:
> LibWeb: Allow style inheritance through slots

- Libraries/LibWeb/HTML/HTMLLinkElement.cpp
Some websites do not specify the MIME type of style sheets, instead using as= or just leaving it empty.
Both Chromium and Firefox do load them regardless, so let's do it too.
Note: This is just #3757 with a slightly edited commit message since the original got stalebotted and I can't update it directly.
> LibWeb: Allow loading style sheets without a MIME type

- Libraries/LibGfx/InterpolationColorSpace.h
- Libraries/LibWeb/CSS/ComputedProperties.cpp
- Libraries/LibWeb/CSS/ComputedProperties.h
- Libraries/LibWeb/CSS/ComputedValues.h
- Libraries/LibWeb/CSS/Enums.json
- Libraries/LibWeb/CSS/Keywords.json
- Libraries/LibWeb/CSS/Properties.json
- Libraries/LibWeb/Layout/Node.cpp
- Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Libraries/LibWeb/Painting/PaintStyle.h
- Libraries/LibWeb/SVG/SVGElement.cpp
- Libraries/LibWeb/SVG/SVGGradientElement.cpp
- Libraries/LibWeb/SVG/SVGGradientElement.h
- Libraries/LibWeb/SVG/SVGLinearGradientElement.cpp
- Libraries/LibWeb/SVG/SVGRadialGradientElement.cpp
- Tests/LibWeb/Ref/expected/wpt-import/svg/pservers/reftests/reference/gradient-color-interpolation-ref.svg
- Tests/LibWeb/Ref/input/wpt-import/svg/pservers/reftests/gradient-color-interpolation.svg
- Tests/LibWeb/Text/expected/css/CSSStyleDeclaration-has-indexed-property-getter.txt
- Tests/LibWeb/Text/expected/css/CSSStyleProperties-all-supported-properties-and-default-values.txt
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-cascade/all-prop-revert-layer.txt
- Tests/LibWeb/Text/expected/wpt-import/css/cssom/shorthand-values.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/painting/parsing/color-interpolation-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/painting/parsing/color-interpolation-valid.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/styling/presentation-attributes-irrelevant.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/styling/presentation-attributes-relevant.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/styling/presentation-attributes-unknown.txt
- Tests/LibWeb/Text/input/wpt-import/svg/painting/parsing/color-interpolation-invalid.svg
- Tests/LibWeb/Text/input/wpt-import/svg/painting/parsing/color-interpolation-valid.svg
This changes the operating color space for gradient `<linearGradient>` and `<radialGradient>` elements.
Gets us +50 WPT subtests in the `svg/painting` directory
Examples of the use of this property can be seen on  https://developer.mozilla.org/en-US/docs/Web/CSS/color-interpolation  and https://developer.mozilla.org/en-US/docs/Web/SVG/Reference/Attribute/color-interpolation.
> LibWeb: Implement the `color-interpolation` property for SVG gradients

- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/IntersectionObserver/IntersectionObserver.cpp
- Tests/LibWeb/Layout/expected/display-contents-blockification-of-flex-items.txt
- Tests/LibWeb/Layout/input/display-contents-blockification-of-flex-items.html
Flex/grid items are always blockified (have their CSS display forced
into "block") by style computation.
We were doing this by looking at the CSS display of the parent. However,
if the parent has `display: contents`, we must look at the *grandparent*
instead.
This corrects the layout of buttons underneath Reddit article cards.
Before:
After:
(+bonus missing null check for IntersectionObserver that happened once while working on this and I don't know how to reproduce it.)
> LibWeb: Allow blockification across display: contents boundary

- Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
This causes a compiler error on GCC 15.0.1 and should be unnecessary since paint_style already is of type SVGGradientPaintStyle.
> LibWeb: Remove unnecessary as_if<SVGGradientPaintStyle>() on paint_style

- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/radio-valueMissing.txt
This fixes a bug in the algorithm for determining if radio buttons are missing their value. Previously it was only checked if the button itself is required. Now the algorithm checks if the radio button group contains a required radio button in order to determine if the value is required.
> LibWeb/HTML: Check all radio buttons in group for required attribute

- Libraries/LibJS/Runtime/ErrorTypes.cpp
- Libraries/LibJS/Runtime/ErrorTypes.h
- Meta/ladybird.py
This brings Octane back down to previous numbers on my machine.
> LibJS: Revert common error types to only hold a single string

- Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Tests/LibWeb/Layout/expected/grid/gfc-between-relpos-gfc-and-abspos-item.txt
- Tests/LibWeb/Layout/input/grid/gfc-between-relpos-gfc-and-abspos-item.html
...by another GFC. When searching for grid item that contains an abspos box positioned relative to GFC, it's incorrect to assume that the closest ancestor box whose parent establishes GFC is always the one we are looking for, because there may be non-positioned GFC in between.
Fixes regression introduced in 80c8e78.
> LibWeb: Handle correctly case when abspos and relpos GFC is interleaved

- Libraries/LibWeb/CSS/ComputedProperties.cpp
- Libraries/LibWeb/CSS/ComputedProperties.h
- Libraries/LibWeb/CSS/ComputedValues.h
- Libraries/LibWeb/CSS/Enums.json
- Libraries/LibWeb/CSS/Keywords.json
- Libraries/LibWeb/CSS/Properties.json
- Libraries/LibWeb/Forward.h
- Libraries/LibWeb/Layout/Node.cpp
- Libraries/LibWeb/Painting/DisplayListCommand.h
- Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.h
- Libraries/LibWeb/Painting/PaintableBox.h
- Libraries/LibWeb/Painting/SVGPaintable.cpp
- Libraries/LibWeb/Painting/SVGPaintable.h
- Libraries/LibWeb/Painting/SVGPathPaintable.cpp
- Libraries/LibWeb/Painting/ShouldAntiAlias.h
- Libraries/LibWeb/SVG/SVGElement.cpp
- Tests/LibWeb/Text/expected/css/CSSStyleDeclaration-has-indexed-property-getter.txt
- Tests/LibWeb/Text/expected/css/CSSStyleProperties-all-supported-properties-and-default-values.txt
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-cascade/all-prop-revert-layer.txt
- Tests/LibWeb/Text/expected/wpt-import/css/cssom/shorthand-values.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/painting/parsing/shape-rendering-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/painting/parsing/shape-rendering-valid.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/styling/presentation-attributes-irrelevant.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/styling/presentation-attributes-relevant.txt
- Tests/LibWeb/Text/expected/wpt-import/svg/styling/presentation-attributes-unknown.txt
- Tests/LibWeb/Text/input/wpt-import/svg/painting/parsing/shape-rendering-invalid.svg
- Tests/LibWeb/Text/input/wpt-import/svg/painting/parsing/shape-rendering-valid.svg
Anti-aliasing is disabled if `shape-rendering` is set to `optimizeSpeed` or `crispEdges`.
Here's an example from https://developer.mozilla.org/en-US/docs/Web/CSS/shape-rendering - previously all of these ellipses looked the same:
> LibWeb: Use `shape-rendering` to control anti aliasing for SVG paths

- AK/Utf16FlyString.h
- AK/Utf16String.h
- AK/Utf16StringBase.h
- Tests/AK/TestUtf16FlyString.cpp
- Tests/AK/TestUtf16String.cpp
We added this for String some time ago, so let's give Utf16String the same optimization. Note that Utf16String was already handling its data member potentially being null as of 5af99f4dd0f0288eb7b9d4edaa3fdbace.
> AK: Specialize Optional for Utf16String and Utf16FlyString

- Libraries/LibCore/Process.cpp
Both gdb and lldb interrupt execution after attaching to the process, so no need to send a SIGTRAP immediately after which would require typing `continue` in the debugger twice.
> LibCore: Don't send SIGTRAP when debugger attaches

- Libraries/LibWeb/Painting/PaintableBox.cpp
PaintableBox::handle_mouseleave is turning off scrollbar updating, but the user might still have the primary button down. Don't turn it off here.
Resolves crashing on MacOSX AppKit and Qt where gutter_size is 0 when mouse is moved outside window.
fixes: #5844
> LibWeb: Don't stop drawing scrollbar on mouseleave

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/Page/EventHandler.cpp
- Libraries/LibWeb/UIEvents/MouseEvent.cpp
- Libraries/LibWeb/UIEvents/MouseEvent.h
- Libraries/LibWeb/UIEvents/PointerEvent.cpp
- Libraries/LibWeb/UIEvents/PointerEvent.h
- Libraries/LibWeb/UIEvents/WheelEvent.cpp
- Libraries/LibWeb/UIEvents/WheelEvent.h
- Tests/LibWeb/Text/expected/UIEvents/UIEventInit-view.txt
- Tests/LibWeb/Text/input/UIEvents/UIEventInit-view.html
Fixing this allows the globe to be rotated on: https://earth.nullschool.net
> LibWeb: Ensure `UIEventInit.view` is set for mouse and pointer events

- Libraries/LibWeb/Selection/Selection.cpp
- Tests/LibWeb/Text/expected/selection-focuses-editing-host.txt
- Tests/LibWeb/Text/input/selection-focuses-editing-host.html
We were constraining the focusing behavior for editing hosts a bit too much; regardless of how the selection changed, if the start container is inside an editing host and it's currently not focused, we should focus it. This fixes focus stealing by other elements that set a selection inside an editing host on a click event, for example.
> LibWeb: Always focus on editing host if currently not focused

- Libraries/LibWeb/DOM/Document.cpp
- Libraries/LibWeb/DOM/Position.cpp
- Libraries/LibWeb/DOM/Position.h
- Libraries/LibWeb/Painting/PaintableBox.cpp
We can only construct positions if there's a node involved, which was already enforced by Position::create() only accepting a GC::Ref.
> LibWeb: Make DOM::Position's node mandatory

- .github/workflows/js-and-wasm-benchmarks.yml
The output format for js-benchmarks is going to change, and while the webhook parsing the results has not yet been updated fixate the js-benchmark checkout to a specific commit.
> CI: Fixate js-benchmarks to current master

- Libraries/LibWeb/Painting/Paintable.cpp
- Tests/LibWeb/Ref/expected/border-radius-normalization-ref.html
- Tests/LibWeb/Ref/input/border-radius-normalization.html
Fixes rendering of elements with large border-radius values by scaling radii proportionally when they exceed element dimensions per CSS spec.
Noticed this on a number of elements on beta.digg.com
> before
> after
> LibWeb: Implement CSS border radius overlapping algorithm

- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/CSS/StyleComputer.h
The majority of the logic in these functions was redundant with the only actual functionality being:
- Resolving `initial` and `inherit` when we originally had `unset` when called from `compute_properties`.
- Resolving inheritance for `text-align: -libweb-inherit-or-center` when called from `compute_properties`
- Resolving inheritance for `color: currentcolor` when called from `compute_properties`
- Setting all values to `property_initial_value` when called from `create_document_style`
There are more natural places to handle each of these so let's do it there and remove these functions.
Only functionality change is that we now correctly handle inheritance of animated color values for `color: currentcolor` (atleast once #5926 is merged)
> LibWeb: Remove compute_defaulted_{values|property_value} 

- Libraries/LibCore/MimeData.cpp
- Tests/LibCore/TestLibCoreMimeType.cpp
This allows you to open local avif files using the `file://` schema.
> LibCore: Add AVIF to registered types in MimeData

- Libraries/LibCore/SocketWindows.cpp
- Libraries/LibTLS/TLSv12.cpp
- Tests/CMakeLists.txt
- Tests/LibTLS/CMakeLists.txt
Initially was done just so `Tests/LibDNS` could be enabled (working towards loading web pages from `https` requests on Windows Ladybird), but I later found this also addresses #5355 too. This needs the `windows` label
> LibTLS+Tests/LibDNS: Load Windows default certificate store and enable TLS-dependent tests in Windows CI

- Libraries/LibDNS/CMakeLists.txt
- Libraries/LibDNS/Message.h
- Libraries/LibJS/CMakeLists.txt
- Libraries/LibMedia/Audio/Loader.h
- Libraries/LibMedia/Audio/PlaybackStream.h
- Libraries/LibMedia/Audio/PulseAudioWrappers.h
- Libraries/LibMedia/Audio/SampleFormats.h
- Libraries/LibMedia/CMakeLists.txt
- Libraries/LibMedia/Containers/Matroska/Reader.h
- Libraries/LibMedia/FFmpeg/FFmpegVideoDecoder.h
- Libraries/LibMedia/PlaybackManager.h
- Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
- Libraries/LibWasm/CMakeLists.txt
- Libraries/LibWasm/Printer/Printer.h
- Libraries/LibWasm/Types.h
- Libraries/LibWasm/Wasi.h
- Libraries/LibXML/CMakeLists.txt
- Libraries/LibXML/DOM/Node.h
- Libraries/LibXML/Parser/Parser.h
- Tests/LibJS/CMakeLists.txt
- Utilities/CMakeLists.txt
- Utilities/wasm.cpp
If desirable I can file an issue for this for eventual follow-up but I think having test-js running in Windows CI now, despite not having ASAN enabled, is still valuable to catch general LibJS Windows bitrot at CI-time
> Tests/LibJS+Utilities: Enable abench+dns+image+wasm+xml and test-js on Windows

- Libraries/LibWeb/Layout/GridFormattingContext.cpp
- Tests/LibWeb/Ref/expected/wpt-import/css/css-grid/abspos/absolute-positioning-changing-containing-block-001-ref.html
- Tests/LibWeb/Ref/input/wpt-import/css/css-grid/abspos/absolute-positioning-changing-containing-block-001.html
- Tests/LibWeb/Text/expected/wpt-import/css/css-grid/abspos/absolute-positioning-grid-container-parent-001.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-grid/abspos/absolute-positioning-grid-container-parent-001.html
Now elements with position `absolute` properly resolve their position inside parent elements with `grid`. I also imported some WPT tests related to that topic.
Part 2 of resolving issues on https://hack4krak.pl
Before:
After:
> LibWeb/CSS: Fix basic absolute positioning inside grid containers

- Libraries/LibWeb/Layout/TreeBuilder.cpp
- Tests/LibWeb/Layout/expected/table/abspos-pseudo-element-inside-table.txt
- Tests/LibWeb/Layout/expected/table/wrap-float-in-anonymous-table-cell.txt
- Tests/LibWeb/Layout/input/table/wrap-float-in-anonymous-table-cell.html
This fixes an issue where floating children of a table box would not get laid out at all if they were surrounded by nothing but whitespace.
Visual progression on https://symmetricstrength.com/
Before:
After:
> LibWeb: Wrap out-of-flow table children in anonymous table cells

- Libraries/LibWeb/Animations/AnimationEffect.cpp
- Libraries/LibWeb/CSS/CSSStyleProperties.cpp
- Libraries/LibWeb/CSS/ComputedProperties.cpp
- Libraries/LibWeb/CSS/ComputedProperties.h
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/CSS/StyleComputer.h
- Libraries/LibWeb/CSS/StylePropertyMapReadOnly.cpp
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/GenerateCSSPropertyID.cpp
- Services/WebContent/ConnectionFromClient.cpp
We only ever compute values for longhands so having space allocated for shorthands is just wasted memory.
Most of the commits are around making sure we don't ever try to get shorthands from ComputedProperties but there are a couple miscellaneous cleanups that don't warrant their own PR as well - see individual commits for details.
> LibWeb: Dont allocate space for shorthands in ComputedProperties

- AK/Variant.h
- Libraries/LibWasm/AbstractMachine/AbstractMachine.cpp
- Libraries/LibWasm/AbstractMachine/AbstractMachine.h
- Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
- Libraries/LibWasm/AbstractMachine/Configuration.cpp
- Libraries/LibWasm/AbstractMachine/Configuration.h
- Libraries/LibWasm/AbstractMachine/Validator.cpp
- Libraries/LibWasm/AbstractMachine/Validator.h
- Libraries/LibWasm/Opcode.h
- Libraries/LibWasm/Parser/Parser.cpp
- Libraries/LibWasm/Printer/Printer.cpp
- Libraries/LibWasm/Types.h
- Utilities/CMakeLists.txt
- Utilities/wasm.cpp
This still passes the values on the stack, but registers are now allowed to cross a call boundary.
This is a very significant (>50%) improvement on the small call microbenchmarks on my machine.
> LibWasm: Don't clobber registers on (most) calls

- Libraries/LibWeb/HTML/Scripting/Fetching.cpp
- Tests/LibWeb/Text/expected/error-stack-must-contain-full-url.txt
- Tests/LibWeb/Text/input/error-stack-must-contain-full-url.html
Atlassian login gets the base URL for its module scripts by throwing an error and pulling out the current script's URL from error.stack with regex.
Since we only returned a basename for module scripts, it would fail to match and try and use `/` as a base URL (because it does [matched_string] + "/"), which is not a valid base URL.
> LibWeb: Set filename of module scripts to full URL instead of basename

- Libraries/LibWeb/Fetch/FetchMethod.cpp
- Tests/LibWeb/Text/expected/Fetch/fetch-controller-abort-with-body-does-not-crash-with-timeout.txt
- Tests/LibWeb/Text/input/Fetch/fetch-controller-abort-with-body-does-not-crash-with-timeout.html
If the request has a body, the abort will interact with promises, which requires callbacks to be enabled.
Fixes crashing on Atlassian products.
> LibWeb/Fetch: Enable callbacks in the abort signal algorithm callback

- Libraries/LibWeb/Animations/Animation.cpp
- Libraries/LibWeb/Animations/KeyframeEffect.h
- Libraries/LibWeb/DOM/Document.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-transitions/transitioncancel-003.txt
If an animation got to its finished state before its target's computed properties could be updated, we would end up with invalid styles. Do not skip finished animations, but prevent effect invalidation on timeline updates if the animation is already finished.
This fixes the CI flake on WPT test `css/css-transitions/inherit-height-transition.html`.
> LibWeb: Always update computed properties for finished animations

- Libraries/LibWeb/HTML/HTMLLinkElement.cpp
- Libraries/LibWeb/SVG/SVGDecodedImageData.cpp
- Libraries/LibWeb/SVG/SVGDecodedImageData.h
Adds a path that checks if blob contains SVG image before reaching for image decoder.
Fixes logged image decoding errors on https://chatgpt.com/
> LibWeb: Support decoding SVG favicons

- Libraries/LibWeb/SVG/SVGAnimatedLength.cpp
- Libraries/LibWeb/SVG/SVGElement.cpp
- Libraries/LibWeb/SVG/SVGElement.h
- Libraries/LibWeb/SVG/SVGEllipseElement.cpp
- Libraries/LibWeb/SVG/SVGForeignObjectElement.cpp
- Libraries/LibWeb/SVG/SVGImageElement.cpp
- Libraries/LibWeb/SVG/SVGLength.cpp
- Libraries/LibWeb/SVG/SVGLength.h
- Libraries/LibWeb/SVG/SVGLineElement.cpp
- Libraries/LibWeb/SVG/SVGLinearGradientElement.cpp
- Libraries/LibWeb/SVG/SVGRadialGradientElement.cpp
- Libraries/LibWeb/SVG/SVGRectElement.cpp
- Libraries/LibWeb/SVG/SVGSVGElement.cpp
- Libraries/LibWeb/SVG/SVGUseElement.cpp
- Tests/LibWeb/Text/expected/SVG/svg-rect-animated-length.txt
- Tests/LibWeb/Text/input/SVG/svg-rect-animated-length.html
An SVGLength can be read-only, e.g. all animVal values cannot be modified. Implement this for all instantiations of SVGLength.
While we're here, add `fake_animated_length_fixme()` so we can easily find all sites where we need to improve our animated length game.
> LibWeb: Implement SVGLength's read-only property

- Libraries/LibWeb/Layout/LayoutState.cpp
- Libraries/LibWeb/Layout/LayoutState.h
- Tests/LibWeb/Layout/expected/inline-nested-with-padding.txt
- Tests/LibWeb/Layout/input/inline-nested-with-padding.html
Improves layout of [Wikipedia's monobook skin](https://en.wikipedia.org/wiki/Main_Page?useskin=monobook):
|--|--|
| <img width="544" height="155" alt="image" src="https://github.com/user-attachments/assets/dd569f8c-457e-4d3d-be23-945777ba1cc3" /> | <img width="545" height="155" alt="image" src="https://github.com/user-attachments/assets/06501c9e-c6a4-44cd-bdad-28f76799d7f5" /> |
Also fixes #3491:
|--|--|
| <img width="92" height="51" alt="image" src="https://github.com/user-attachments/assets/0a3f2eb3-3830-4745-9b35-28894122112f" /> | <img width="111" height="52" alt="image" src="https://github.com/user-attachments/assets/e7a8d623-f3ae-4936-a885-b3f39df4cdc0" /> |
> LibWeb: Apply nested inline margin box sizes to inline layout nodes

- Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Libraries/LibWeb/Layout/LayoutState.h
- Libraries/LibWeb/Layout/LineBuilder.cpp
- Libraries/LibWeb/Layout/LineBuilder.h
- Tests/LibWeb/Layout/expected/block-and-inline/abspos-inline.txt
- Tests/LibWeb/Layout/input/block-and-inline/abspos-inline.html
If we were calculating the static position for an absolutely positioned inline box that resides in the last line of its containing block, we would not have yet provided the fragments in that line with their final positions. Additionally, we would always move the box beneath the fragment, which was incorrect.
Fixes #5867.
|--|--|
| <img width="55" height="46" alt="image" src="https://github.com/user-attachments/assets/a62e0f1e-e9db-4c91-bee0-2fcc8218c37f" /> | <img width="60" height="30" alt="image" src="https://github.com/user-attachments/assets/48af8187-14bf-40a1-8408-661f2d850d6e" /> |
> LibWeb: Correctly position absolute inline boxes in last line

- Libraries/LibWeb/Layout/LayoutState.cpp
- Tests/LibWeb/Crash/Layout/button-display-inline-with-nested-inlines.html
> LibWeb: Prevent creation of new UsedValues for nested inline nodes

- Libraries/LibJS/Runtime/Temporal/AbstractOperations.cpp
- Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Libraries/LibJS/Runtime/Temporal/InstantPrototype.cpp
- Libraries/LibJS/Runtime/Temporal/ZonedDateTimePrototype.cpp
- Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.prototype.total.js
The first commits are normative just because they change order of fallible operations for consistency, thus are observable. The third commit is a bugfix to the spec that fixes an assertion.
test262 diff:
```
test/built-ins/Temporal/Duration/prototype/total/blank-duration.js                                     💥️ -> ✅
test/built-ins/Temporal/Instant/prototype/since/options-read-before-algorithmic-validation.js          ❌ -> ✅
test/built-ins/Temporal/Instant/prototype/toString/options-read-before-algorithmic-validation.js       ❌ -> ✅
test/built-ins/Temporal/Instant/prototype/until/options-read-before-algorithmic-validation.js          ❌ -> ✅
test/built-ins/Temporal/PlainDate/prototype/since/options-read-before-algorithmic-validation.js        ❌ -> ✅ …
```
> LibJS: A couple Temporal normative and editorial updates

- Documentation/EditorConfiguration/CLionConfiguration.md
This piece of documentation currently refers to a "default" preset.
Sam Atkins informed me it is supposed to say "Release".
This PR addresses this.
> Documentation: Rectify incorrect preset name

- Libraries/LibWeb/HTML/FormAssociatedElement.cpp
- Libraries/LibWeb/HTML/FormAssociatedElement.h
- Libraries/LibWeb/HTML/HTMLButtonElement.cpp
- Libraries/LibWeb/HTML/HTMLButtonElement.h
- Libraries/LibWeb/HTML/HTMLButtonElement.idl
- Libraries/LibWeb/HTML/HTMLFieldSetElement.cpp
- Libraries/LibWeb/HTML/HTMLFieldSetElement.h
- Libraries/LibWeb/HTML/HTMLFieldSetElement.idl
- Libraries/LibWeb/HTML/HTMLInputElement.cpp
- Libraries/LibWeb/HTML/HTMLInputElement.h
- Libraries/LibWeb/HTML/HTMLInputElement.idl
- Libraries/LibWeb/HTML/HTMLLinkElement.idl
- Libraries/LibWeb/HTML/HTMLObjectElement.cpp
- Libraries/LibWeb/HTML/HTMLObjectElement.h
- Libraries/LibWeb/HTML/HTMLObjectElement.idl
- Libraries/LibWeb/HTML/HTMLOutputElement.cpp
- Libraries/LibWeb/HTML/HTMLOutputElement.h
- Libraries/LibWeb/HTML/HTMLOutputElement.idl
- Libraries/LibWeb/HTML/HTMLSelectElement.cpp
- Libraries/LibWeb/HTML/HTMLSelectElement.h
- Libraries/LibWeb/HTML/HTMLSelectElement.idl
- Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Libraries/LibWeb/HTML/HTMLTextAreaElement.h
- Libraries/LibWeb/HTML/HTMLTextAreaElement.idl
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/forms/constraints/form-validation-validity-valueMissing.txt
I noticed 3 functions:
* `report_validity`
* `check_validity`
* `will_validate`
Where repeated in many classes. Considering we have a FormAssociatedElement class to unify this kind of behavior I decided to refactor the code out.
I also went ahead and implemented a barebones `validation_message` that gives us one more WPT test.
This removes 15 FIXME's in IDL files for very little effort :)
> Unify functions in form associated element

- Libraries/LibWeb/DOM/Node.h
- Libraries/LibWeb/HTML/FormAssociatedElement.cpp
Previously we would only trigger change events on insertion, which resulted in javascript code missing changes due to deletion.
This makes the calculator on the [MDN simple web worker demo](https://mdn.github.io/dom-examples/web-workers/simple-web-worker/) update on deletion as well.
> LibWeb: Fire change events on deletion in FormAssociated Text Elements

- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Bytecode/Instruction.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Interpreter.h
- Libraries/LibJS/Bytecode/Op.h
- Libraries/LibJS/Runtime/AbstractOperations.cpp
- Libraries/LibJS/Runtime/BoundFunction.cpp
- Libraries/LibJS/Runtime/BoundFunction.h
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.h
- Libraries/LibJS/Runtime/FunctionObject.h
- Libraries/LibJS/Runtime/NativeFunction.cpp
- Libraries/LibJS/Runtime/NativeFunction.h
- Libraries/LibJS/Runtime/ProxyObject.cpp
- Libraries/LibJS/Runtime/ProxyObject.h
We already do this for normal Call contexts, so this is just continuing
to propagate the same pattern to other instructions.
Fixes #6026
> LibJS: Always allocate callee contexts up front

- Libraries/LibIDL/IDLParser.cpp
- Libraries/LibIDL/Types.h
- Libraries/LibWeb/CSS/CSSNumericArray.idl
- Libraries/LibWeb/CSS/CSSUnparsedValue.idl
Previously, an error would occur if an `iterable<T>` was defined before the required value iterator. An is now also reported if an`iterable<T>` is defined before a pair iterator, previously this error would only be reported if the iterable was defined after the pair iterator.
Fixes #5940
> LibIDL: Allow `iterable<T>` to be defined before property getter 

- Libraries/LibWeb/Gamepad/Gamepad.cpp
- Libraries/LibWeb/Gamepad/Gamepad.h
- Libraries/LibWeb/Gamepad/GamepadButton.cpp
- Libraries/LibWeb/Gamepad/GamepadButton.h
- Libraries/LibWeb/Gamepad/NavigatorGamepad.cpp
- Libraries/LibWeb/Gamepad/NavigatorGamepad.h
- Libraries/LibWeb/Gamepad/SDLGamepadForward.h
- Libraries/LibWeb/Internals/InternalGamepad.cpp
- Libraries/LibWeb/Internals/InternalGamepad.h
- Libraries/LibWeb/Page/EventHandler.cpp
- Libraries/LibWeb/Page/EventHandler.h
The recent Gamepad PR added the SDL3 dependency, which caused the following build error on Windows:
```
In file included from C:\Users\ayeteadoe\Development\ladybird\Libraries\LibWeb\Gamepad\Gamepad.cpp:14:
In file included from C:\Users\ayeteadoe\Development\ladybird\Libraries\LibWeb\HTML\Navigator.h:14:
In file included from C:\Users\ayeteadoe\Development\ladybird\Libraries\LibWeb\HTML\NavigatorConcurrentHardware.h:10:
In file included from C:\Users\ayeteadoe\Development\ladybird\Libraries\LibCore\System.h:35:
C:\Users\ayeteadoe\Development\ladybird\Libraries\LibCore\SocketAddressWindows.h(21,9): error: 'WINAPI_FAMILY_PARTITION' macro redefined [-Werror,-Wmacro-redefined]
21 | #define WINAPI_FAMILY_PARTITION(x) 1
|         ^
C:\Program Files (x86)\Windows …
```
> LibWeb/Gamepad: Forward declare SDL components to fix Windows build

- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Tests/assignment-evaluation-order.js
Previously, the given test would create an object with the test property that pointed to itself.
This is because `temp = temp.test || {}` overwrote the `temp` local register, and `temp.test = temp` used the new object instead of the original one it fetched.
Allows https://www.yorkshiretea.co.uk/ to load, which was failing in Gsap library initialization.
> LibJS: Copy base object of LHS of assignment to preserve eval order

- Libraries/LibWeb/FileAPI/Blob.cpp
- Libraries/LibWeb/FileAPI/Blob.h
- Libraries/LibWeb/FileAPI/File.cpp
- Libraries/LibWeb/FileAPI/File.h
While reviewing #6039 I was made aware that we do not always run the
proper constructors steps depending on which of the two `Blob::create()`
methods were used.
Previously we did not execute the constructor steps if we constructed a
Blob from a ByteBuffer and a String. Though we only construct a Blob
from ByteBuffer and String internally we still need to run these steps.
By creating the new type 'BlobPartsOrByteBuffer' we can consolidate
those two approaches to creating a Blob into our already existing
constructor steps.
> LibWeb/FileAPI: Make sure to always run the constructor steps for Blob

- Libraries/LibWeb/DOM/Node.cpp
- Libraries/LibWeb/Editing/Commands.cpp
- Libraries/LibWeb/Editing/Internal/Algorithms.cpp
- Libraries/LibWeb/Selection/Selection.cpp
- Tests/LibWeb/Text/expected/Editing/execCommand-delete.txt
- Tests/LibWeb/Text/expected/Editing/execCommand-insertParagraph.txt
- Tests/LibWeb/Text/input/Editing/execCommand-delete.html
- Tests/LibWeb/Text/input/Editing/execCommand-insertParagraph.html
If a node with `contenteditable=true/plaintextonly` is the child of an editable node or an editing host, we should make it editable instead of an editing host. This effectively merges nested editing hosts together, which is how other browsers deal with this as well.
Gains us 5 WPT subtest passes in `editing`.
> LibWeb: Merge nested editing hosts

- Libraries/LibWasm/Opcode.h
The opcode entry declared i16x8_replace_lane with pushes = -1, but replace_lane pops 2 (vector, lane value) and pushes 1 result vector. Set pushes to 1 to match the other replace_lane opcodes.
> LibWasm: Fix pushes for i16x8.replace_lane in Opcode table

- Libraries/LibWasm/Parser/Parser.cpp
SIMD loads/stores checked bit 0x20 of the align immediate to detect a following memory index, unlike scalar mem ops which use 0x40 per the multi-memory encoding. This caused the memidx byte to be misparsed as the next immediate (e.g. offset).
Update both SIMD sites (v128 load/store and lane variants) to check and clear 0x40, then read LEB128<u32> memidx.
Repro:
```
(module (memory $m0 1) (memory $m1 1)
(func (export "go")
i32.const 0
v128.load (memory 1)
drop))
```
Before: printed memidx 0 with offset 1.
After:  prints memidx 1 with offset 0.
> LibWasm: Use 0x40 flag for SIMD memory memidx like scalar ops

- Libraries/LibWeb/DOM/Document.h
- Libraries/LibWeb/DOM/DocumentLoading.cpp
- Libraries/LibWeb/HTML/Parser/HTMLParser.cpp
- Tests/LibWeb/Text/expected/wpt-import/html/browsers/browsing-the-web/read-text/load-text-plain.txt
- Tests/LibWeb/Text/input/wpt-import/common/text-plain.txt
- Tests/LibWeb/Text/input/wpt-import/html/browsers/browsing-the-web/read-text/load-text-plain.html
This fixes at least 1 wpt bug where text/plain documents are rendered in quirks mode. The test in question: https://wpt.live/html/browsers/browsing-the-web/read-text/load-text-plain.html
> LibWeb: Ensure parser cannot change the mode is handled

- Libraries/LibWeb/CSS/ComputedValues.h
- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/Properties.json
- Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp
- Libraries/LibWeb/Layout/Node.cpp
- Tests/LibWeb/Text/expected/css/CSSStyleDeclaration-has-indexed-property-getter.txt
- Tests/LibWeb/Text/expected/css/CSSStyleProperties-all-supported-properties-and-default-values.txt
- Tests/LibWeb/Text/expected/css/getComputedStyle-print-all.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-multicol/parsing/columns-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-multicol/parsing/columns-invalid.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-multicol/parsing/columns-valid.txt
- Tests/LibWeb/Text/input/wpt-import/css/css-multicol/parsing/columns-computed.html
- Tests/LibWeb/Text/input/wpt-import/css/css-multicol/parsing/columns-invalid.html
- Tests/LibWeb/Text/input/wpt-import/css/css-multicol/parsing/columns-valid.html
This gives us some extra WPT passes around parsing the `columns` shorthand.
> LibWeb: Add CSS column-height property

- Libraries/LibWeb/HTML/NavigableContainer.cpp
...navigable shared attribute processing steps.
After e095bf3a5f6
https://wpt.live/html/rendering/pixel-length-attributes.html ends up in this function with null navigable, which leads to crash while executing steps. Adding early return in case iframe's document doesn't have a navigable is enough to make the test pass again.
This commit doesn't import the WPT test, because it's already imported and we have it disabled since it takes too much time on CI.
> LibWeb: Early return if document doesn't have navigable in container

- Libraries/LibWebView/Application.cpp
The HTTP cache is now stable enough that we can ask more people to help us testing it. So let's turn it on by default! It can be turned off with --disable-http-cache if needed.
> LibWebView: Enable HTTP cache by default

- Base/res/ladybird/templates/error.html
- Libraries/LibWebView/ViewImplementation.cpp
I've been looking at the crash-page too much recently and the slight scrollbar caused by the padding has been annoying me.
> LibWebView+Base: Remove unnecessary scrollbar from error pages

- Libraries/LibWeb/ResizeObserver/ResizeObserver.cpp
- Tests/LibWeb/Text/expected/wpt-import/resize-observer/observe.txt
- Tests/LibWeb/Text/input/ResizeObserver/observe.html
- Tests/LibWeb/Text/input/wpt-import/resize-observer/observe.html
- Tests/LibWeb/Text/input/wpt-import/resize-observer/resources/iframe.html
- Tests/LibWeb/Text/input/wpt-import/resize-observer/resources/resizeTestHelper.js
ResizeObserver spec doesn't seem to mention this behavior explicitly,
but https://wpt.live/resize-observer/observe.html test expects it (we
can't import the WPT test because it hangs for some reason).
> LibWeb: Use ResizeObserver instance as this in callback function

- Libraries/LibWeb/ViewTransition/ViewTransition.cpp
- Tests/LibWeb/Crash/wpt-import/css/css-view-transitions/first-line-reparent-crash.html
- Tests/LibWeb/Crash/wpt-import/css/css-view-transitions/list-style-position-style-change-crash.html
- Tests/LibWeb/Crash/wpt-import/css/css-view-transitions/root-element-cv-hidden-crash.html
- Tests/LibWeb/Crash/wpt-import/css/css-view-transitions/root-element-display-none-crash.html
- Tests/LibWeb/Crash/wpt-import/css/css-view-transitions/root-element-display-none-during-transition-crash.html
This used to crash a lot of attempted view transitions, now it doesn't anymore.
> LibWeb: Use correct style rule index in view transitions and import crash tests

- Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Libraries/LibWeb/HTML/WorkerAgentParent.cpp
- Libraries/LibWeb/HTML/WorkerAgentParent.h
- Libraries/LibWeb/WebSockets/WebSocket.cpp
- Libraries/LibWeb/Worker/WebWorkerClient.cpp
- Libraries/LibWeb/Worker/WebWorkerClient.h
- Libraries/LibWeb/Worker/WebWorkerClient.ipc
- Services/WebWorker/PageHost.cpp
- Services/WebWorker/PageHost.h
Allows formulas to update on Google Sheets, which uses a Worker to
update them and makes cookie authenticated requests, which was failing
before this PR.
This has the limitation that it has to proxy through the WebContent
process, but that's how the current infrastructure is, which is outside
the scope of this PR.
https://github.com/user-attachments/assets/004cf98b-30a2-4669-ba4a-835d281eb150
> LibWeb: Implement cookie fetching for Workers

- Libraries/LibWeb/DOM/Document.cpp
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibWeb/Crash/wpt-import/css/css-view-transitions/root-element-display-none-during-transition-crash.html
This allows us to run some more view transitions WPT tests, one of which has been imported.
I'm sure there is some others that this makes us pass as well that could be imported, but I don't want to go down the entire list to find them.
> LibWeb: Implement optional function IDL arguments

- Tests/LibWeb/TestConfig.ini
- Tests/LibWeb/test-web/main.cpp
Similar to ref tests, we don't want to incorrectly pass a test that did not remove this attribute.
> test-web: Wait for crash tests with a `test-wait` attribute

- Libraries/LibWeb/CSS/Parser/RuleParsing.cpp
- Tests/LibWeb/Text/expected/DOM/replaceSync-Property.txt
- Tests/LibWeb/Text/input/DOM/replaceSync-Property.html
This is the fix for [https://github.com/LadybirdBrowser/ladybird/issues/6063](https://github.com/LadybirdBrowser/ladybird/issues/6063)
This commit fixes a crash in the LibWeb when converting an at-rule to a property rule. It handles a case where a document might not be available by falling back to using the realm to get the ParsingParams.
> LibWeb: Avoid dereferencing a null pointer to document

- Libraries/LibJS/Bytecode/ASTCodegen.cpp
- Libraries/LibJS/Bytecode/Generator.cpp
- Libraries/LibJS/Bytecode/Generator.h
- Libraries/LibJS/Bytecode/Instruction.h
- Libraries/LibJS/Bytecode/Interpreter.cpp
- Libraries/LibJS/Bytecode/Op.h
- Libraries/LibJS/Tests/builtins/Object/Object.defineProperties.js
Previously, PutById constructed a PropertyKey from the identifier,
which coerced numeric-like strings to numbers. This moves that decision
to bytecode generation: the bytecode generator now emits PutByNumericId
for numeric keys and PutById for string keys. This removes per-execution
parsing from the interpreter.
1.4x speedup on the following microbenchmark:
```js
const o = {};
for (let i = 0; i < 10_000_000; i++) {
o.a = 1;
o.b = 2;
o.c = 3;
}
```
> LibJS: Add PutByNumericId and change PutById to be string key only

- Libraries/LibWeb/CSS/StyleComputer.cpp
A new parameter was added to Web::CSS::StyleValue::to_string() in PR #2820 but this debug message was never updated. If CSS_TRANSITIONS_DEBUG was enabled, compilation would fail.
> LibWeb/CSS: Fix compilation with CSS_TRANSITIONS_DEBUG

- Libraries/LibWeb/Crypto/CryptoAlgorithms.cpp
Fixed a typo in a comment in CryptoAlgorithms.cpp on the line 5352.
> LibCrypto: Fix typo in comment

- Libraries/LibJS/Runtime/ArrayConstructor.cpp
- Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
- Libraries/LibJS/Runtime/ObjectConstructor.cpp
- Libraries/LibJS/Runtime/ObjectPrototype.cpp
- Libraries/LibJS/Runtime/PromiseConstructor.cpp
- Libraries/LibJS/Runtime/PrototypeObject.h
- Libraries/LibJS/Runtime/Reference.cpp
- Libraries/LibJS/Runtime/TypedArrayConstructor.cpp
- Libraries/LibJS/Runtime/Value.cpp
- Libraries/LibJS/Runtime/Value.h
- Libraries/LibJS/Runtime/ValueInlines.h
- Libraries/LibWeb/Crypto/CryptoKey.cpp
- Libraries/LibWeb/Crypto/KeyAlgorithms.cpp
- Libraries/LibWeb/WebIDL/AsyncIterator.h
- Meta/Lagom/Tools/CodeGenerators/LibWeb/BindingsGenerator/IDLGenerators.cpp
- Tests/LibJS/test-js.cpp
Adds inline implementation for the most common case when `Value` is already an object.
1.47x improvement on the following benchmark:
```js
const o = {};
for (let i = 0; i < 10_000_000; i++) {
o.a = 1;
o.b = 2;
o.c = 3;
}
```
> LibJS+LibWeb: Inline fast path for `Value::to_object()`

- Libraries/LibWeb/Geometry/DOMMatrix.cpp
Assuming 0 and -0 are distinct values, `a != 0 || a != -0` is always true.
I don't know enough about how -0 is represented to know if is actually distinct from 0, but let's write it correctly anyway. :^)
> LibWeb/Geometry: Correct typos in DOMMatrix "not 0 or -0" checks

- Libraries/LibWeb/Fetch/Body.cpp
- Tests/LibWeb/Text/expected/Fetch/multipart-form-data-crlf.txt
- Tests/LibWeb/Text/input/Fetch/multipart-form-data-crlf.html
According to RFC 2046, the BNF of the form data body is:
multipart-body := [preamble CRLF]
dash-boundary transport-padding CRLF
body-part *encapsulation
close-delimiter transport-padding
[CRLF epilogue]
Where "epilogue" is any text that "may be ignored or discarded". So we should stop parsing the body once we encounter the terminating delimiter ("--").
Note that our parsing function is from an attempt to standardize the grammar in the spec: https://andreubotella.github.io/multipart-form-data This proposal hasn't been updated in ~4 years, and the fetch spec still does not have a formal definition of the body string.
Fixes #6195
> LibWeb: Do not require multipart form data to end with CRLF

- Libraries/LibWeb/Painting/VideoPaintable.cpp
The extra representations of a video element are unnecessary to specify in VideoPaintable, as the playback system itself should take care of all the details of the representation as specified.
Just another little simplification that's leading up to the playback rewrite.
> LibWeb: Remove a FIXME and simplify the painting of video frames

- Base/res/ladybird/about-pages/settings.html
- Base/res/ladybird/about-pages/settings/privacy.js
- Libraries/LibWeb/CMakeLists.txt
- Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
- Libraries/LibWeb/GPC/GlobalPrivacyControl.cpp
- Libraries/LibWeb/GPC/GlobalPrivacyControl.h
- Libraries/LibWeb/GPC/GlobalPrivacyControl.idl
- Libraries/LibWeb/HTML/Navigator.cpp
- Libraries/LibWeb/HTML/Navigator.h
- Libraries/LibWeb/HTML/Navigator.idl
- Libraries/LibWeb/HTML/WorkerNavigator.h
- Libraries/LibWeb/HTML/WorkerNavigator.idl
- Libraries/LibWeb/Loader/ResourceLoader.h
- Libraries/LibWebView/Settings.cpp
- Libraries/LibWebView/Settings.h
- Libraries/LibWebView/ViewImplementation.cpp
- Libraries/LibWebView/ViewImplementation.h
- Libraries/LibWebView/WebUI/SettingsUI.cpp
- Libraries/LibWebView/WebUI/SettingsUI.h
- Services/WebContent/ConnectionFromClient.cpp
- Services/WebContent/ConnectionFromClient.h
- Services/WebContent/WebContentServer.ipc
- UI/Qt/Settings.h
Global Privacy Control aims to be a replacement for Do Not Track. DNT ended up not being a great solution, as it wasn't enforced by law. This actually resulted in the DNT header serving as an extra fingerprinting data point.
GPC is becoming enforced by law in USA states such as California and Colorado. CA is further working on a bill which requires that browsers implement such an opt-out preference signal (OOPS):
https://cppa.ca.gov/announcements/2025/20250911.html
This patch replaces DNT with GPC and hooks up the associated settings.
> LibWeb+LibWebView+WebContent: Replace DNT with GPC

- AK/Optional.h
- Libraries/LibCrypto/BigInt/SignedBigInteger.cpp
- Libraries/LibCrypto/BigInt/UnsignedBigInteger.cpp
- Libraries/LibGfx/Font/TypefaceSkia.cpp
- Libraries/LibJS/Runtime/Intl/Locale.cpp
- Libraries/LibTest/TestRunner.h
- Libraries/LibWasm/WASI/Wasi.cpp
- Libraries/LibWeb/CSS/CSSRule.cpp
- Libraries/LibWeb/CSS/CSSRule.h
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/HTML/HTMLTextAreaElement.cpp
- Libraries/LibWeb/HTML/ListOfAvailableImages.cpp
- Libraries/LibWeb/Layout/ImageBox.cpp
- Libraries/LibWeb/Painting/Paintable.cpp
- Libraries/LibWeb/Painting/ScrollFrame.h
We often use Optional<T> in a cache pattern such as:
```cpp
if (!m_cache.has_value())
m_cache = slow_thing();
return m_cache.value();
```
The new ::ensure() makes it a bit simpler:
```cpp
return m_cache.ensure([&] { return slow_thing(); });
```
> AK: Add Optional<T>::ensure() 

- Libraries/LibDNS/Message.h
- Libraries/LibRegex/RegexByteCode.h
When building with ENABLE_ALL_THE_DEBUG_MACROS there are a number of issues encountered.  See #6173 for the details.
This PR fixes the remaining linking issues (undefined references) by adding X_API macros (DNS_API and REGEX_API) to the specific classes that encountered the issue.
1- DNS_DEBUG issue with `Libraries/LibDNS/Resolver.h:1003` with undefined reference `DNS::Messages::Records::SIG::to_string() const`
which impacts
- bin/dns
- bin/TestDNSResolver
- libexec/RequestServer
2- REGEX_DEBUG issue with `Libraries/LibRegex/RegexDebug.h:76` with undefined reference `regex::OpCode_Compare::variable_arguments_to_byte_string(AK::Optional<regex::MatchInput const&>) const`
which impacts:
- bin/TestRegex
3- REGEX_DEBUG issue with `Libraries/LibRegex/RegexByteCode.h:672` with undefined …
> Add missing X_API macros to classes needing them for DEBUG macro builds

- Libraries/LibURL/URL.h
- Libraries/LibWebView/Application.cpp
- Libraries/LibWebView/Application.h
- Libraries/LibWebView/Menu.h
- Libraries/LibWebView/ViewImplementation.cpp
- Libraries/LibWebView/ViewImplementation.h
- Libraries/LibWebView/WebContentClient.cpp
- UI/AppKit/Application/Application.h
- UI/AppKit/Application/Application.mm
- UI/AppKit/Application/ApplicationDelegate.h
- UI/AppKit/Application/ApplicationDelegate.mm
- UI/AppKit/Interface/LadybirdWebView.h
- UI/AppKit/Interface/LadybirdWebView.mm
- UI/AppKit/Interface/Menu.mm
- UI/AppKit/Interface/Tab.mm
- UI/AppKit/Interface/TabController.h
- UI/AppKit/Interface/TabController.mm
- UI/Qt/Application.cpp
- UI/Qt/Application.h
- UI/Qt/BrowserWindow.cpp
- UI/Qt/BrowserWindow.h
- UI/Qt/Menu.cpp
- UI/Qt/Tab.cpp
- UI/Qt/WebContentView.h
* A couple minor fixes and simplifications after #6062
* Add a couple more menu icons for macOS Tahoe
* Generate the actions to open `about:` pages
* Generate the remaining actions for the Inspect menu and then the menu itself
> LibWebView+UI: A couple menu fixes and improvements, and generate the Inspect menu

- Libraries/LibWeb/CSS/CSSStyleProperties.cpp
- Libraries/LibWeb/CSS/CSSStyleProperties.h
- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/DOM/AbstractElement.cpp
- Libraries/LibWeb/DOM/AbstractElement.h
- Libraries/LibWeb/DOM/Element.cpp
- Libraries/LibWeb/DOM/Element.h
- Libraries/LibWeb/DOM/PseudoElement.h
- Services/WebContent/ConnectionFromClient.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-nesting/nested-declarations-cssom.txt
We are expected to preserve their order within a style declaration, so let's do that. Passes 1 tracked WPT subtest.
Saw this failure while reviewing a PR earlier and was confused why we didn't pass it. Turns out this was why.
> LibWeb: Store custom properties in an OrderedHashMap

- Libraries/LibWeb/HTML/Navigable.cpp
- Libraries/LibWeb/HTML/Navigable.h
- Libraries/LibWeb/Internals/Internals.cpp
- Libraries/LibWeb/Internals/Internals.h
- Libraries/LibWeb/Internals/Internals.idl
- Libraries/LibWeb/Page/EventHandler.cpp
- Libraries/LibWeb/Page/EventHandler.h
- Libraries/LibWebView/Application.cpp
- Libraries/LibWebView/Application.h
- Libraries/LibWebView/HeadlessWebView.cpp
- Libraries/LibWebView/HeadlessWebView.h
- Libraries/LibWebView/ViewImplementation.cpp
- Libraries/LibWebView/ViewImplementation.h
- Libraries/LibWebView/WebContentClient.cpp
- Services/WebContent/ConnectionFromClient.cpp
- Services/WebContent/ConnectionFromClient.h
- Services/WebContent/WebContentServer.ipc
- Tests/LibWeb/test-web/Application.cpp
- Tests/LibWeb/test-web/Application.h
- UI/AppKit/Application/Application.h
- UI/AppKit/Application/Application.mm
- UI/AppKit/Interface/LadybirdWebView.mm
- UI/Qt/Application.cpp
- UI/Qt/Application.h
- UI/Qt/Tab.cpp
This PR first does a bit of organization around clipboard handling, then ports the `paste` action to UTF-16.
> LibWeb+WebContent+UI: Port text pasting to UTF-16

- Libraries/LibGfx/Font/Font.cpp
- Libraries/LibGfx/Font/Font.h
- Libraries/LibGfx/ShapeFeature.h
- Libraries/LibGfx/TextLayout.cpp
- Libraries/LibGfx/TextLayout.h
- Libraries/LibWeb/HTML/Canvas/CanvasText.h
- Libraries/LibWeb/HTML/Canvas/CanvasText.idl
- Libraries/LibWeb/HTML/CanvasRenderingContext2D.cpp
- Libraries/LibWeb/HTML/CanvasRenderingContext2D.h
- Libraries/LibWeb/HTML/OffscreenCanvasRenderingContext2D.cpp
- Libraries/LibWeb/HTML/OffscreenCanvasRenderingContext2D.h
- Libraries/LibWeb/Layout/BlockFormattingContext.cpp
- Libraries/LibWeb/Layout/ImageBox.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.h
- Libraries/LibWeb/Painting/ImagePaintable.cpp
- Libraries/LibWeb/Painting/MarkerPaintable.cpp
- Libraries/LibWeb/Painting/MediaPaintable.cpp
- Libraries/LibWeb/Painting/MediaPaintable.h
- Libraries/LibWeb/Painting/PaintableBox.cpp
This patch introduces a per-`Gfx::Font` cache for harfbuzz text shaping
results. As long as the same OpenType features are used, we now cache
the results of harfbuzz shaping, saving massive amounts of time during
text layout.
As an example, it saves multiple seconds when loading the ECMAScript
specification at <https://tc39.es/ecma262>. Before this change, harfbuzz
shaping was taking up roughly 11% of a profile of loading that page.
The cache brings it down to 1.8%.
Note that the cache currently grows unbounded. I've left a FIXME about
adding some limits.
> LibWeb: Cache results of harfbuzz text shaping

- Meta/CMake/wasm_spec_tests.cmake
The current HEAD contains a bunch of stuff not supported by wabt (or us), that also appear to not be fully merged yet; stick to the last known commit for now.
> Meta: Pin Wasm spec testsuite to a known commit

- Libraries/LibJS/Runtime/Shape.cpp
- Libraries/LibJS/Runtime/Shape.h
- Libraries/LibJS/Tests/regress/inline-caching.js
Adds missing PrototypeChainValidity invalidation for add/set/delete operations on dictionary-mode prototype shapes.
> LibJS: Invalidate PrototypeChainValidity when prototype shape is a dict

- Libraries/LibMedia/FFmpeg/FFmpegVideoDecoder.h
The destructor lacked any of these specifiers, and others lacked the virtual specifier.
> LibMedia: Mark FFmpegVideoDecoder functions with virtual override

- Libraries/LibIPC/TransportSocket.cpp
- Libraries/LibIPC/TransportSocket.h
- Libraries/LibMedia/Audio/PlaybackStreamPulseAudio.cpp
- Libraries/LibMedia/Audio/PulseAudioWrappers.h
- Libraries/LibThreading/BackgroundAction.h
- Libraries/LibThreading/Forward.h
- Libraries/LibThreading/Thread.h
- Libraries/LibWeb/HTML/RenderingThread.cpp
- Libraries/LibWeb/HTML/RenderingThread.h
- Libraries/LibWebView/MachPortServer.cpp
- Libraries/LibWebView/MachPortServer.h
`Threading::Thread` is ref-counted, so using forward declarations in a lot of headers currently including Thread.h is an easy change.
Also, `Weakable` is not thread-safe, so taking a strong reference from a `WeakPtr<Thread>` may result in a use-after-free. We don't use this functionality anywhere anyway, so remove it.
No functional changes, hopefully.
> LibThreading: Forward-declare Thread and remove its Weakable functionality

- Libraries/LibWeb/CSS/Properties.json
- Libraries/LibWeb/CSS/StyleValues/ShorthandStyleValue.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-area-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-area-shorthand.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-area-valid.txt
This PR implements spec-compliant serialization for `grid-area` and ensures `grid-area` and longhands don't fail to parse when they contain a custom-ident.
I *think* the remaining subtest failures should be fixed by the custom-ident escaping implemented in #6267.
Fixes 23 WPT subtests in the `css/css-grid` directory.
> LibWeb: Improve parsing and serialization of `grid-area`

- Libraries/LibWeb/Layout/SVGFormattingContext.cpp
- Tests/LibWeb/Ref/expected/svg/min-max-size-constraints-ref.html
- Tests/LibWeb/Ref/input/svg/min-max-size-constraints.html
When displaying SVGs inside a navigable directly, we want to display them in the size specified by their width and height attributes instead of stretching them to the viewport as layout normally would.
However, when doing so, we need to actually check that the SVG we are laying out is indeed directly inside the navigable. Otherwise we just blindly overwrite whatever content sizes have been calculated by layout code for e.g. SVG elements inlined somewhere in an HTML document.
Due to the way this was written originally, the bug was not very noticable. The code overwrote the content width/height with the computed width/height, which was often still correct in the sense that those two had the same value. However, content size may also be the result of {min,max}-{width,height} constraints, …
> LibWeb: Do not stomp over content size of SVGs

- Libraries/LibWeb/CSS/Parser/Parser.h
- Libraries/LibWeb/CSS/Parser/PropertyParsing.cpp
- Libraries/LibWeb/CSS/Parser/ValueParsing.cpp
- Libraries/LibWeb/CSS/Properties.json
- Tests/LibWeb/Text/expected/wpt-import/css/css-fonts/animations/font-style-interpolation.txt
This change adds the allowed angle range to the `font-style` property definition. This allows these angles to be clamped after interpolation.
Ideally, the generator should be updated so that we can specify the angle is in degrees. This would allow us to make use of this information during parsing, which we can't do currently because we don't know what the unit is. Using this value for interpolation purposes is fine because the angle has been converted to its canonical unit by this point.
> LibWeb: Clamp interpolated `font-style` angle

- Libraries/LibWeb/Painting/DisplayList.cpp
- Libraries/LibWeb/Painting/DisplayList.h
- Libraries/LibWeb/Painting/DisplayListCommand.h
- Libraries/LibWeb/Painting/DisplayListPlayerSkia.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.h
Teach the display list executor to derive a bounding rectangle for stacking contexts whose inner commands can all report bounds, that is, most contexts without nested stacking contexts.
This yields a large performance improvement on https://tc39.es/ecma262/ where the display list contains thousands of groups like:
```
PushStackingContext blending=Multiply
DrawGlyphRun
PopStackingContext
```
Previously, `PushStackingContext` triggered an unbounded `saveLayer()` even when the glyph run lies wholly outside the viewport. With this change, we (1) cull stacking contexts that fall outside the viewport and (2) provide bounds to `saveLayer()` when they are visible.
With this change rendering thread goes from 70% to 1% in profiles of https://tc39.es/ecma262/. Also makes a huge performance …
> LibWeb: Calculate and use bounds for "simple" stacking contexts

- Libraries/LibCore/ThreadedPromise.h
- Tests/LibCore/TestLibCorePromise.cpp
Four data race warnings reported while running test TestLibCorePromise (from file `Tests/LibCore/TestLibCorePromise.cpp`)  under ThreadSanitizer in g++. (See pull request #6034)
Attaching complete log of TestLibCorePromise test run with ThreadSanitizer
[ThreadSanitizer_TestLibCorePromise.log](https://github.com/user-attachments/files/22100748/ThreadSanitizer_TestLibCorePromise.log)
Explanations:
1) Two warnings (one in test case `threaded_promise_instantly_resolved` and one in `threaded_promise_resolved_later`) about a data race in ThreadedPromise with `m_has_completed` flag variable access not controlled when accessed from multiple threads.  To resolve the data race the class variable m_has_completed changed to Atomic to make the access controlled.
```
WARNING: ThreadSanitizer: data race …
```
> LibCore: Fix ThreadedPromise issues found with ThreadSanitizer

- Libraries/LibWeb/CSS/GridTrackPlacement.cpp
- Libraries/LibWeb/CSS/GridTrackPlacement.h
- Libraries/LibWeb/CSS/StyleValues/GridTrackPlacementStyleValue.cpp
- Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-area-computed.txt
- Tests/LibWeb/Text/expected/wpt-import/css/css-grid/parsing/grid-area-valid.txt
With this change we ensure that custom-idents used by `grid-area` and its longhands are correctly escaped.
I've also included a drive-by commit to avoid some copies in `GridTrackPlacement`.
> LibWeb: Escape custom-ident when serializing grid track placement values

- Tests/LibWeb/Ref/input/wpt-import/css/filter-effects/effect-reference-feimage-001.html
- Tests/LibWeb/Screenshot/input/css-background-blob-url.html
- Tests/LibWeb/TestConfig.ini
I seem to be clicking the "re-run failed jobs" button rather a lot lately. So, I've disabled a few and hacked some others to hopefully flake less. I don't think this is *all* the flakes, by an means, but I went through all the failing CI jobs in the PR queue, and these are the ones that I've seen failing a lot.
> Tests: Disable/hack-fix some regularly-flaking tests

- Libraries/LibWeb/Painting/DisplayList.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.cpp
- Libraries/LibWeb/Painting/DisplayListRecorder.h
- Libraries/LibWeb/Painting/StackingContext.cpp
This makes it so that the bounds for any paint-contained stacking context are not derived from its children, but rather just set to the rectangle that they will be clipped to anyways due to the paint containment. Should make rendering faster on pages that use paint containment.
This is what I meant when I wrote my comment on  #6291.
> LibWeb: Compute bounds for paint-contained stacking contexts

- Libraries/LibWeb/Layout/ImageBox.cpp
This gets rid of the assumption that the DOM node of an ImageBox is also its image provider. This will become necessary when generating the image boxes for view transition pseudos, for which the DOM node won't be the image provider. (that'll be the pseudo element itself)
> LibWeb: Don't assume ImageBox's image provider is the DOM node

- .github/actions/setup/action.yml
- Documentation/BuildInstructionsLadybird.md
- Tests/AK/TestStringConversions.cpp
- vcpkg.json
The primary motivation for this is version 8.1.0 of `fast_float`, which contains a change that fixes #6205.
Since the baseline update already caused everything to rebuild, I've also bumped all other dependencies that were a straightforward version change. There is nothing super relevant in the changelogs for these versions as far as I can tell. The most interesting thing might be some security fixes in the curl update, which are probably good to have.
> Meta+Tests: Update vcpkg dependencies

- Libraries/LibDevTools/Actors/FrameActor.cpp
- Libraries/LibDevTools/Actors/StyleSheetsActor.cpp
- Libraries/LibWeb/CSS/StyleSheetIdentifier.h
This makes our style sheets appear more like how Firefox displays its own, and also fixes a bug where the style sheet list wouldn't appear at all if there were multiple inline style sheets on the page.
> LibDevTools: Some fixes to the style sheets list

- Libraries/LibDevTools/Actors/PageStyleActor.cpp
Width and height are doubles, so get_string() will return nothing and fail. We just want a JsonValue here without caring what type it is, so let's just use get() instead.
Before:
After:
> LibDevTools: Don't assume computed layout values are strings

- .github/workflows/libjs-test262.yml
libtool is required to build gperf
> Meta: Fix libjs-test262 CI workflow

- Libraries/LibJS/Lexer.cpp
When compiled with LEXER_DEBUG or ENABLE_ALL_THE_DEBUG_MACROS=ON and the test-js is run, the following backtrace will be seen:
(see #6173 where this all started)
Note: there is another issue in LibJS (and test-js) that will strike first when using ENABLE_ALL_THE_DEBUG_MACROS=ON.  See #6263
```
VERIFICATION FAILED: index < length_in_code_units() at /home/bobo/projects/myladybird/AK/Utf16View.h:366
/home/bobo/projects/myladybird/Build/release/lib/liblagom-ak.so.0(dump_backtrace+0x4a) [0x7fe1cbeb34fa]
/home/bobo/projects/myladybird/Build/release/lib/liblagom-ak.so.0(ak_trap+0xf) [0x7fe1cbeb375f]
/home/bobo/projects/myladybird/Build/release/lib/liblagom-ak.so.0(ak_verification_failed+0x49) [0x7fe1cbeb3499]
/home/bobo/projects/myladybird/Build/release/lib/liblagom-js.so.0 JS::Lexer::consume() …
```
> LibJS: LEXER_DEBUG code_unit_at() goes beyond end of line

- Libraries/LibJS/Runtime/Temporal/Duration.cpp
- Libraries/LibJS/Runtime/Temporal/Duration.h
- Libraries/LibJS/Runtime/Temporal/DurationPrototype.cpp
- Libraries/LibJS/Runtime/Temporal/PlainDate.cpp
- Libraries/LibJS/Runtime/Temporal/PlainDateTime.cpp
- Libraries/LibJS/Runtime/Temporal/PlainYearMonth.cpp
- Libraries/LibJS/Runtime/Temporal/ZonedDateTime.cpp
- Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.prototype.round.js
- Libraries/LibJS/Tests/builtins/Temporal/Duration/Duration.prototype.total.js
This is a normative change in the Temporal proposal. See:
https://github.com/tc39/proposal-temporal/commit/1a089eb
test262 diff:
```
test/intl402/Temporal/Duration/prototype/round/relativeto-dst-back-transition.js   ❌ -> ✅
test/intl402/Temporal/Duration/prototype/total/relativeto-dst-back-transition.js   ❌ -> ✅
test/intl402/Temporal/ZonedDateTime/prototype/since/same-date-reverse-wallclock.js 💥️ -> ✅
test/intl402/Temporal/ZonedDateTime/prototype/until/same-date-reverse-wallclock.js 💥️ -> ✅
```
> LibJS: Handle relativeTo ZDTs that fall within second DST wallclock time

- Libraries/LibWeb/CSS/ComputedProperties.cpp
- Libraries/LibWeb/CSS/ComputedProperties.h
- Libraries/LibWeb/CSS/ComputedValues.h
- Libraries/LibWeb/CSS/StyleComputer.cpp
- Libraries/LibWeb/Layout/InlineFormattingContext.cpp
- Libraries/LibWeb/Layout/Node.cpp
- Libraries/LibWeb/Layout/Node.h
- Tests/LibWeb/Layout/expected/block-and-inline/abspos-block.txt
- Tests/LibWeb/Layout/input/block-and-inline/abspos-block.html
Fixes #5798
Whether an absbox is positioned below or to the right of its previous sibling in an `InlineFormattingContext` is determined by the display-outside value before blockification, so we store the pre-blockification `display` value in `ComputedValues` to access it in `InlineFormattingContext` and position the box accordingly.
Before:
After:
> LibWeb: Position absolute block-level boxes below previous siblings in inline formatting contexts

- Libraries/LibWeb/XML/XMLDocumentBuilder.cpp
- Libraries/LibWeb/XML/XMLDocumentBuilder.h
- Libraries/LibXML/Parser/Parser.cpp
- Libraries/LibXML/Parser/Parser.h
- Tests/LibWeb/Text/data/invalid_utf8_corrupt.svg
- Tests/LibWeb/Text/expected/corrupt-svg-favicon.txt
- Tests/LibWeb/Text/input/corrupt-svg-favicon.html
`set_source` takes a ByteString but the implementation might require a
specific encoding. Make it fallible so that we don't need to crash in
the case of invalid UTF-8 or similar.
The test includes a sequence of invalid UTF-8 bytes that crash the
browser without this change.
Related issue: #6279, related PR #6348
> LibWeb+LibXML: Make `Listener::set_source(ByteString)` fallible

- Libraries/LibWeb/HTML/HTMLDialogElement.cpp
- Libraries/LibWeb/HTML/HTMLDialogElement.h
- Tests/LibWeb/Text/expected/wpt-import/html/semantics/interactive-elements/the-dialog-element/dialog-focus-previous-outside.txt
- Tests/LibWeb/Text/input/wpt-import/html/semantics/interactive-elements/the-dialog-element/dialog-focus-previous-outside.html
When a dialog is closed, restore focus to the previously focused element if focus is within the dialog or if the dialog was modal.
> LibWeb/HTML: Implement focus restoration in HTMLDialogElement

- Libraries/LibGfx/TextLayout.cpp
I spotted this leak when WebContent was exiting with ASan enabled on a page with a media element. MediaPaintable calls Gfx::Font::width(), which calls through to measure_text_width(), which then drops an hb_buffer_t* without freeing it.
> LibGfx: Free the harfbuzz buffer when measuring text width

- Libraries/LibWeb/Page/EventHandler.cpp
- Tests/LibWeb/Text/expected/wheel-event-should-be-consumed-by-innermost-scrollable.txt
- Tests/LibWeb/Text/input/wheel-event-should-be-consumed-by-innermost-scrollable.html
...before falling back to containing block. Fixes a bug when we can't scroll innermost scrollable element, because wheel event dispatching immediately falls back to containing block.
> LibWeb: Try to dispatch wheel event on hit-testing target first

- Libraries/LibWeb/IndexedDB/Internal/Algorithms.cpp
Motivation: I wanted to see what it takes to get [demo.actualbudget.org](https://demo.actualbudget.org) working. On `master` the page crashes on initial load; this change lets the initial screen load.
Minimal repro of the issue (error in the console without this PR):
```html
<script>
const r = indexedDB.open("t", 1);
r.onupgradeneeded = e => e.target.result.createObjectStore("s", { keyPath: "id" });
r.onsuccess = () => r.result.transaction("s", "readonly").objectStore("s").getAllKeys();
</script>
```
No additional WPT tests pass from this change on its own, because the tests under https://wpt.live/IndexedDB/idbobjectstore_getAllKeys.any.html are currently timing out in `close_a_database_connection` (I think maybe https://github.com/LadybirdBrowser/ladybird/pull/6182 is the fix for that). …
> LibWeb/IndexedDB: Allow `queryOrOptions` to be null in `getAllKeys`

- Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.cpp
- Libraries/LibWasm/AbstractMachine/BytecodeInterpreter.h
This also "fixes" the "address leak" detected by GCC (which is not actually leaked to the tailcalled function).
(doesn't really have much of an effect on perf since memory.* are usually one-off instructions)
> LibWasm: Avoid revalidating memory/address for every element in memory.*

- .github/workflows/js-and-wasm-artifacts.yml
This allows us to manually kick off jobs for the JS/WASM artifacts build with an explicit reference to build, which is useful if we want to generate benchmark results for older commits.
Note that this workflow does not actually produce benchmark results - that's the job of another workflow. The webhook storing the benchmark results only appends new benchmarks; existing ones will be kept.
Also note that the GitHub checkout action defaults to the default reference if `inputs.reference_to_build` is not provided, such as in the case of a push to the master branch.
> CI: Add manual workflow dispatch to JS/WASM artifacts build

- .github/workflows/js-and-wasm-benchmarks.yml
If we ever want to rerun benchmarks for an older commit, e.g. if we added new benchmarks that we would want historical performance data on, we need to consider that some benchmarks might fail because of a bug or missing feature. For manual runs of the upstream build, pass `--continue-on-failure` so we simply skip these failing benchmarks.
> CI: Run js-benchmarks with --continue-on-failure for manual builds

- Libraries/LibWeb/HTML/HTMLScriptElement.cpp
- Libraries/LibWeb/HTML/HTMLScriptElement.h
- Tests/LibWeb/Text/expected/htmlscript-src-reflection.txt
- Tests/LibWeb/Text/expected/usvstring-url-reflection.txt
- Tests/LibWeb/Text/input/htmlscript-src-reflection.html
- Tests/LibWeb/Text/input/usvstring-url-reflection.html
LibWeb: Make HTMLScriptElement.src getter resolve to absolute URL
The src IDL attribute was previously implemented as an inline getter that returned the raw attribute value. This broke spec semantics and sites like Telegram Web that rely on document.currentScript.src to compute Webpack’s publicPath.
According to the HTML Standard:
https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflecting-content-attributes-in-idl-attributes
For URL-reflecting attributes:
1. If contentAttributeValue is null, then return the empty string.
2. Let urlString be the result of encoding-parsing-and-serializing a URL given contentAttributeValue, relative to element’s node document.
3. If urlString is not failure, then return urlString.
This PR implements these steps
Fixes #6253
> LibWeb: Make HTMLScriptElement.src getter resolve to absolute URL
